### PR TITLE
Target Language Word Highlighting in the Scripture Pane

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Target Language Word Highlighting in the Scripture Pane
- **Dependency:**  https://github.com/translationCoreApps/ScripturePane/pull/95

#### Please include detailed Test instructions for your pull request:
- Open a Titus project with **tW** and make a selection in the verse check area and as you save your selection/s it should Highlighting in the target language pane in the Scripture Pane.
- Make sure to add the target language pane to the scripture Pane if you didn't previously add it.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3905)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905)*

**Comment by RoyalSix** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[package.json, line 146 at r1](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3905#-L68vT5w6Qr1mOtdcfVy:-L68vT5w6Qr1mOtdcfVz:b59a8hw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e58fe3018ef818000d3f56191c8616a069df2063/package.json#L146)):*
> ```JSON
>     "semver": "5.5.0",
>     "simple-git": "1.43.0",
>     "string-punctuation-tokenizer": "^0.7.0",
> ```

Do we need this in the core and in the scripture pane?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3905)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 146 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905#-L68vT5w6Qr1mOtdcfVy:-L6B4EgxuuDvYCsS2KOo:bcgvb4t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e58fe3018ef818000d3f56191c8616a069df2063/package.json#L146)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we need this in the core and in the scripture pane?
</blockquote></details>

the scripture pane needs it for the test to pass on travis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905)*

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905)*

**Comment by PhotoNomad0** [comment]
Having trouble getting it to work with Hindi Project.  Previous selections don't appear highlighted and new selections don't show the highlighting.

[hi_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1759887/hi_tit.zip)

**Comment by klappy** [comment]
@photonomad0: Do they show up in the Selection Mode of the VerseCheck tool area and not in the SP? Or does it not work for both?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905#-:-L6IUBVqTJQ-sZpqb1wv:b7m9q8)*

**Comment by PhotoNomad0** [comment]
LGTM
WOrking now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905#-:-L6IUekT_fpu0fkuZYHI:bsejy54)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905#-:-L6IUlFgaLg9VjJ_dFu2:bnfp4nl)*

**Comment by klappy** [comment]
*[package.json, line 146 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905#-L68vT5w6Qr1mOtdcfVy:-L6IcXfDOirr3yN0gfi1:ba1hqyn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e58fe3018ef818000d3f56191c8616a069df2063/package.json#L146)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

the scripture pane needs it for the test to pass on travis
</blockquote></details>

@royalsix : Can you acknowledge the solution so that reviewable is ready to merge?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3905)*

**Pull request merged**
