### PR TITLE
App Crashes From Invalid Project Name

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes an issue with having an invalid book name being fixed in the manifest but not in the project target language folder

#### Please include detailed Test instructions for your pull request:
- [ITT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1882010/ITT.usfm.zip)
- Import the usfm file
- Choose Titus as the book and English as the language
- Open in Word Alignment
- Everything should work as expected

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4281)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4281)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - Works with the given project and select `Titus` and `en`, but then after that when I import a valid Titus USFM project and select `aa` as language, I get a failure.  There is no warning that the import failed, but the project is deleted from imports folder and there no project in app (or projects folder).

screen shot 2018-04-07 at 7 06 44 am

**Comment by PhotoNomad0** [comment]
@RoyalSix - also when preparing a bug fix for release, you need to start your branch from release - not develop.  And then when you create your PR, you need to select release branch as the base.  Fortunately, github lets you change the base for a PR and in this case will only merge in your commits.  But it is messy in testing your branch locally - your branch has different app version, different tool commits, etc.  May not be a problem in this case.

**Comment by PhotoNomad0** [comment]
I tested with: 

[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1886309/57-TIT.usfm.zip)

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4281)*

**Comment by mannycolon** [comment]
@RoyalSix Increase test coverage

**Comment by mannycolon** [comment]
Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4281)*

**Comment by PhotoNomad0** [comment]
:lgtm: Code Review
:lgtm: Local Testing

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4281#-:-L9f3y4k-4GZhzsbiWfg:b-g4za6j)*

**Comment by mannycolon** [comment]
:lgtm: Code Review
:lgtm: Local Testing

**Comment by mannycolon** [comment]
@RoyalSix Will merge now. a separate PR can be made to increase test coverage.

**Pull request merged**
