### PR TITLE
feature 4936/Show None available in GL drop down if no GL support

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Show None available in GL drop down if no GL support for book/tool.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5005)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (e192927)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-e192927.zip) is ready for download.
[macOS build 1.0.0 (e192927)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-e192927.dmg) is ready for download.
[Windows x64 build 1.0.0 (e192927)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-e192927.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (e192927)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-e192927.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5005#-:-LLoq7WwE8c85B-AKN9J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
Found a problem. In the GL dropdown, it says `None Available` but the Launch button is still clickable is this expected behavior? when I launch the app it works fine.

screen shot 2018-09-07 at 12 32 59 pm

screen shot 2018-09-07 at 12 33 07 pm

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (711afa4)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-711afa4.zip) is ready for download.
[macOS build 1.0.0 (711afa4)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-711afa4.dmg) is ready for download.
[Windows x64 build 1.0.0 (711afa4)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-711afa4.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (711afa4)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-711afa4.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5005#-:-LLpMdVU1HqeGjh-tTc5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
screen shot 2018-09-07 at 3 02 37 pm

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5005#-:-LLpldq--ZqSorPfxhNS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5005)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
