### PR TITLE
No longer requiring .git url

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request addresses users who load online projects by copying the URL in the address bar, instead of the url for cloning. What it does is if it sees that the .git extension is not on the end, it adds it and attempts to load the project. Previously, it would throw an error, because git does not support those urls, but now we can modify them instead.

#### How to test this pull request:

Attempt to load a project from Door43, do so by copying the link that you're supposed to, and also try copying the url in the address bar and load that. Also, wait for the tests to pass or fail, as those were modified as well.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/772)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/b.LoadOnline.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/772#-Ke0mVmsPK6f8V5nMS2b:-Ke0mVmsPK6f8V5nMS2c:brcco4z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/750b8c75fc468e224b0f519233730aa1dba95547/tests/b.LoadOnline.js#L29)):*
> ```JavaScript
>     });
>   });
>   
> ```

Thanks for going the extra mile and writing the test :1st_place_medal: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/772)*

**Comment by EllDoubleYew** [comment]
Tested with and without `.git` extensions and works fine. Are we still waiting on tests @ihoegen ?

**Comment by ihoegen** [comment]
@EllDoubleYew Tests failed, I will look into it real quick

**Comment by ihoegen** [comment]
@EllDoubleYew Fixed tests, ready to merge

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/772)*

**Comment by mannycolon** [comment]
@ihoegen the following tests is failing in your branch 
```
Upload.sendFilePath(USFM project)
    1) should load a USFM project
```

**Comment by ihoegen** [comment]
@mannycolon Latest tests are showing a pass on Linux, and Mac servers are down, so you should only refer to Linux.

**Comment by mannycolon** [comment]
this is from my local machine

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/772#-:-Ke6lPzXLOcdKTKTf-b3:b-ein3gl)*

**Comment by mannycolon** [comment]
@ihoegen this is from my local machine

**Comment by ihoegen** [comment]
@mannycolon What's the associated error message?

**Comment by mannycolon** [comment]
@ihoegen 
Upload.sendFilePath(USFM project)
    1) should load a USFM project

**Comment by ihoegen** [comment]
@mannycolon At the very bottom, there should be an explanation to the error message

**Pull request merged**
