### PR TITLE
added email to feedback and improved speed

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4555 
- added the email and username to the body of the email
- truncated some data from the log to improve speed of submission.

#### Please include detailed Test instructions for your pull request:
- open a large project like Matthew and send some feedback. The feedback should send quickly rather than hanging for a few moments.
- also check the network response in the console to see the email and name are included in the body of the message.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4727)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (0a4b9f8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-0a4b9f8.zip) is ready for download.
[macOS build 0.10.1 (0a4b9f8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-0a4b9f8.dmg) is ready for download.
[Windows x64 build 0.10.1 (0a4b9f8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-0a4b9f8.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (0a4b9f8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-0a4b9f8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (8fd6a87)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-8fd6a87.zip) is ready for download.
[macOS build 0.10.1 (8fd6a87)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-8fd6a87.dmg) is ready for download.
[Windows x64 build 0.10.1 (8fd6a87)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-8fd6a87.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (8fd6a87)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-8fd6a87.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4727)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
While logged as a local user, I loaded a Matthew project with wA tool. Then click the actions button to send feedback. I typed a message and typed my email address then clicked Submit. The Internet access warning popped up and then I clicked access internet. However, I got the following alert `Unable to connect to the server. Please check your Internet connection.` but I actually did have internet connection.

I found the folloing errors in the console
screen shot 2018-07-18 at 4 35 37 pm

**Comment by mannycolon** [comment]
Additional console errors

screen shot 2018-07-18 at 4 39 55 pm

**Comment by mannycolon** [comment]
@neutrinog 

Additional console errors

screen shot 2018-07-18 at 4 39 55 pm

**Pull request merged**
