### PR TITLE
Bugfixes For Check Categories

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes the categories display sorting mechanism

#### Please include detailed Test instructions for your pull request:
- Temporarily delete the following folder `~/translationCore/resource/en/translationHelps/translationWords/v9/kt`
- Open any project. Observe the Categories are displayed in the order of "Other Terms" "Names"
- Uncheck all categories, ensure the launch button is disabled.
- Ensure normal project loading still works, with specified categories. As well as progress indication

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5624)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (aecfc96)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-linux-x64-1.1.0-aecfc96.deb) is ready for download.
[macOS build 1.1.0 (aecfc96)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-macos-x64-1.1.0-aecfc96.dmg) is ready for download.
[Windows x64 build 1.1.0 (aecfc96)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x64-1.1.0-aecfc96.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (aecfc96)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x32-1.1.0-aecfc96.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5624)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
@RoyalSix - sorry the launch button was not disabled with everything unselected.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3838d53)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-linux-x64-1.1.0-3838d53.deb) is ready for download.
[macOS build 1.1.0 (3838d53)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-macos-x64-1.1.0-3838d53.dmg) is ready for download.
[Windows x64 build 1.1.0 (3838d53)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x64-1.1.0-3838d53.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3838d53)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x32-1.1.0-3838d53.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM

**Comment by PhotoNomad0** [comment]
Disabling of launch button working now, but TW crashed on acts with kt removed.
screen shot 2018-12-26 at 2 07 47 pm

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (238a7b8)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-linux-x64-1.1.0-238a7b8.deb) is ready for download.
[macOS build 1.1.0 (238a7b8)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-macos-x64-1.1.0-238a7b8.dmg) is ready for download.
[Windows x64 build 1.1.0 (238a7b8)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x64-1.1.0-238a7b8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (238a7b8)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x32-1.1.0-238a7b8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (693b95c)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-linux-x64-1.1.0-693b95c.deb) is ready for download.
[macOS build 1.1.0 (693b95c)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-macos-x64-1.1.0-693b95c.dmg) is ready for download.
[Windows x64 build 1.1.0 (693b95c)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x64-1.1.0-693b95c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (693b95c)](https://tc-builds.door43.org/build/bugfix-jay-5193/translationCore-win-x32-1.1.0-693b95c.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5624)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
LGTM

**Pull request merged**
