### PR TITLE
Modals Refactoring 

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/450)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/450)*

**Comment by mannycolon** [comment]
@ihoegen  can you merge with develop??

**Comment by mannycolon** [comment]
@ihoegen enabling developer mode in settings modal isn't working

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/js/components/core/Loader.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/450#-K_jlbJmg8hN9A6tzP2f:-K_jlbJmg8hN9A6tzP2g:b-tyt2k1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/44abf560f029f8cd5a6f40aa6e2c44eff8518822/src/js/components/core/Loader.js#L16)):*
> ```JavaScript
> 
>   render() {
>     console.log(this.props.progress);
> ```

remove console logs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/450)*

**Comment by ihoegen** [comment]
@mannycolon Could you tell me what you mean by isn't working? The setting is updating, and on refresh saves. I have noticed that it does not work without a refresh, if that's what you mean

**Comment by ihoegen** [comment]
@mannycolon Fixed the settings

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/450)*

**Pull request merged**
