### PR TITLE
Added Persistence To Groups Data

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
#1011 

#### How to test this pull request:
To test this PR:
checkout js_groups in tW
start with a fresh project
load tW (observer wait time)
reload and see if it is faster

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1063)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/js/actions/GetDataActions.js, line 260 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSb8ASFDnCAg1ID_tc:-KhSb8ASFDnCAg1ID_td:b-qmapyg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L260)):*
> ```JavaScript
> 
> /*
>  * @description Loaded previous project data into the filesystem given a path.
> ```

can we break this action up a little further??

---

*[src/js/actions/GetDataActions.js, line 272 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_5nWCl5pPKO4ldtm:-KhS_5nWCl5pPKO4ldtn:b-9m7n0y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L272)):*
> ```JavaScript
>             let groupIndexObj = fs.readJsonSync(Path.join(dataFolder, 'index.json'))
>             dispatch(GroupsIndexActions.setGroupsIndex(groupIndexObj));
>             dispatch(GroupsIndexActions.loadedGroupsIndexFromFS(true));
> ```

this action seems redundant. shouldn't this happen as a result of setGrousIndexin the previous line?

---

*[src/js/actions/GetDataActions.js, line 274 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_R9G3io3sjiKDod5:-KhS_R9H_WNBO12o3kEz:b-p7953v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L274)):*
> ```JavaScript
>             dispatch(GroupsIndexActions.loadedGroupsIndexFromFS(true));
>             let groupDataFolderPath = Path.join(dataFolder, params.bookAbbr);
>             fs.readdir(groupDataFolderPath, (err, groupDataFolderObjs) => {
> ```

you may wanna add ` if (err) throw "message"  ` right before the `if  (!err) { }`

---

*[src/js/actions/GetDataActions.js, line 280 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_xAjoH12IcRaLzOU:-KhS_xAkBZT1BADQhC6O:b-tcusqd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L280)):*
> ```JavaScript
>                     var i = 1;
>                     for (var groupId in groupDataFolderObjs) {
>                         if (groupDataFolderObjs[groupId].split('.')[1] != 'json') {
> ```

you can use path.extname() instead 

---

*[src/js/actions/GroupsDataActions.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSaEhySdOmOwski9Zl:-KhSaEhzeM3Q3MnKFKUH:b-7oqs0t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GroupsDataActions.js#L18)):*
> ```JavaScript
> };
> 
> export const loadedGroupsDataFromFS = (allGroupsData) =>{
> ```

can we rename this to loadGroupsDataFromFS

---

*[src/js/actions/GroupsIndexActions.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSaNV-FEoCJkWswsi8:-KhSaNV-FEoCJkWswsi9:bhvx1q3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GroupsIndexActions.js#L27)):*
> ```JavaScript
> };
> 
> export const loadedGroupsIndexFromFS = (val) =>{
> ```

same here why not use load instead of loaded??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063)*

**Comment by RoyalSix** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 260 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSb8ASFDnCAg1ID_tc:-KhSkZMS-I9gdsRzTw1i:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L260)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we break this action up a little further??
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 272 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_5nWCl5pPKO4ldtm:-KhSkM6eyJ5vTjD0b02n:b-a97w07) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L272)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this action seems redundant. shouldn't this happen as a result of setGrousIndexin the previous line?
</blockquote></details>

There are cases where you will call setGroupIndex without it being from the FS, so I kept them seperate

---

*[src/js/actions/GetDataActions.js, line 274 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_R9G3io3sjiKDod5:-KhSkLYNGY_T6wRtdz7I:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L274)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you may wanna add ` if (err) throw "message"  ` right before the `if  (!err) { }`
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 280 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhS_xAjoH12IcRaLzOU:-KhSk_8BjBc46aAdVm9_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GetDataActions.js#L280)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you can use path.extname() instead 
</blockquote></details>

Done.

---

*[src/js/actions/GroupsDataActions.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSaEhySdOmOwski9Zl:-KhTDYgeALX3xghI0c1W:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GroupsDataActions.js#L18)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we rename this to loadGroupsDataFromFS
</blockquote></details>

Done.

---

*[src/js/actions/GroupsIndexActions.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-KhSaNV-FEoCJkWswsi8:-KhTDZBa6mZRxKRQG3Bq:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3db695e97051f9ec9786cc80d6d2ff916f5a5237/src/js/actions/GroupsIndexActions.js#L27)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here why not use load instead of loaded??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1063#-:-KhUy5FnaUSuzMz9WDff:bnfp4nl)*

**Pull request merged**
