### PR TITLE
Updated English UDT references to UST

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated English UDT references to UST 

#### Please include detailed Test instructions for your pull request:
- Open a project with tW 
- If you didn't previously have English UDT in your pane settings Click the add new bible resource button
- You should see English `UST` instead of `UDT` and `unfoldingWord Simplified Text` instead of `unfoldingWord Dynamic Text`

# Dependencies
- https://github.com/translationCoreApps/tC_Resources/pull/43
- https://github.com/translationCoreApps/translationWords/pull/140

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4677)

### CODE REVIEW

**Comment by RoyalSix** [comment]
tW does not load with this [project](https://github.com/unfoldingWord-dev/translationCore/files/2167475/en_ulb_1ti_book.zip) (works on develop)
I am getting this error 
screen shot 2018-07-05 at 9 42 55 am 2

**Review by richmahn — COMMENTED** [review]
Also getting that error with that project.

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4677#-:-LGkdqAwAKhUpO6W6ev-:b-wkrbsb)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @richmahn)

**Comment by richmahn** [comment]
Ok, error happens in develop so not part of this story.

**Review by richmahn — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4677)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by richmahn — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4677#-:-LGlYlSGDmUY0x8U6rB9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
