### PR TITLE
Moving Project Save Location to ~/tC/projects

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR gets rid of showing non-project related folders in the projects available to open from within the app

#### How to test this pull request:
To test this PR try opening the app and viewing your projects and then checking in your filesystem for the old folders ~/translationCore/ converted to the new one in the projects folder ~/translationCore/projects

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2199)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-:-KpJJ1XlPa3OfMt5tsCH:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/actions/MyProjectsActions.js, line 106 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-KpL3tdFZaB-LMaK004Q:-KpL3tdFZaB-LMaK004R:b-i06670) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c9a830d66919f410b866788a41e51f1b456efb88/src/js/actions/MyProjectsActions.js#L106)):*
> ```JavaScript
>   for (var folder of directories) {
>     let isDirectory = fs.lstatSync(path.join(OLD_DEFAULT_SAVE, folder)).isDirectory()
>     if (folder != 'resources' && folder != 'projects' && isDirectory) {
> ```

This implementation is nice and clean.

I do have a use case for where this might cause some issues:
I have other directories in my user `translationCore` directory. I have one for `exports`,  one for `archive`, and `resources`. 
I'm sure other people like Koz create random folders in here too.

Here's a possible solution:
What if we move all the folders that have a `manifest.json` in the root of the project folder. All other folders should be collections or have nested folders.
Since somebody can add a manifest.json from an accidental copy/paste or drag and drop, we should also maintain your whitelist.


Does that make sense? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Comment by klappy** [comment]
Implementation is nice and clean. I do have one comment that needs to be discussed and addressed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-:-KpL5n_JdzcuP-fztPe6:b-415p2w)*

**Comment by klappy** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/js/actions/MyProjectsActions.js, line 106 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-KpL3tdFZaB-LMaK004Q:-KpM4j9NdVT7eYs3FeCS:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c9a830d66919f410b866788a41e51f1b456efb88/src/js/actions/MyProjectsActions.js#L106)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This implementation is nice and clean.

I do have a use case for where this might cause some issues:
I have other directories in my user `translationCore` directory. I have one for `exports`,  one for `archive`, and `resources`. 
I'm sure other people like Koz create random folders in here too.

Here's a possible solution:
What if we move all the folders that have a `manifest.json` in the root of the project folder. All other folders should be collections or have nested folders.
Since somebody can add a manifest.json from an accidental copy/paste or drag and drop, we should also maintain your whitelist.


Does that make sense? 

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Comment by mannycolon** [comment]
@RoyalSix Fixed merge conflicts.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-:-KpQ7gWgtSxRNiHBCMZ0:bnfp4nl)*

**Comment by mannycolon** [comment]
Good job! I'll test in a few minutes.

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Comment by mannycolon** [comment]
@RoyalSix you have a duplicate declaration of `ipcRenderer` in RecentProjectsActions.js

**Comment by mannycolon** [comment]
When moving files from `~/tC` to `~/tC/projects` check for duplicates and if a duplicate project is found then don't move the project file.

For example, I had `ar_eph_text_ulb` in my  `~/tC` path and a copy of the same project in my`projects folder` inside `~/tC`.

I got the following error
```
Uncaught Error: EEXIST: file already exists, link 
'/Users/mannycolon/translationCore/ar_eph_text_ulb' -> 
'/Users/mannycolon/translationCore/projects/ar_eph_text_ulb'
```

**Comment by klappy** [comment]
Good catch Manny. I didn't think to test that use case. Glad you caught it before @cckozie did :upside_down_face: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-:-KpQSbkk8CIW1vGwbJ_D:bap0pqx)*

**Comment by mannycolon** [comment]
@RoyalSix don't forget to merge with develop and fix merge conflicts

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199#-:-KpQagVxrrNMGHnBDx07:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r4, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2199)*

**Pull request merged**
