### PR TITLE
Improved door43 project search actions to return more results

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Improved door43 project search actions to return more results

#### How to test this pull request:
- Previous search results for search criteria (**Language Code:** hi and **Book:** Titus)
image

-New search results based on the search criteria in the picture should return the projects in the picture above and the project in the picture below and more.

image

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3132)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@mannycolon - ~~Sorry, but when I run your branch, I am still only seeing the top three results.  The bottom project is not shown.~~  Nevermind, it didn't pull down the latest.  Working good now.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3132#-:-KySFoeoWH-PTspstIdj:bnfp4nl)*

**Comment by klappy** [comment]
@mannycolon Is this ready to review? I see that the title says `WIP` and test coverage decreased.

**Comment by mannycolon** [comment]
@klappy this isn't good to go. I'm still working on tests.

**Comment by RoyalSix** [comment]
Reviewed 3 of 26 files at r3.
Review status: 3 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3132)*

**Comment by RoyalSix** [comment]
Reviewed 23 of 26 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3132)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3132#-:-Kyq9VUXmaOXfCEyMFpB:bnfp4nl)*

**Comment by richmahn** [comment]
@mannycolon Tests are failing for this one.

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3132)*

**Pull request merged**
