### PR TITLE
Handling Single Chunk USFM From TS

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR address an issue were chunk files without explicit verse marker tags were being detected as missing verses, when they should be detected as the file name of the chunk. (Thats the same as the verse  number)

#### How to test this pull request:

[abu_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1323094/abu_tit_text_reg.tstudio.zip)

Test this project and ensure the only missing verses are:
Titus 1:1
Titus 1:9
Titus 1:10
And all of Chapter 2

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2728)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2728)*

**Comment by klappy** [comment]
@royalsix: Can you fix the failing tests?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2728#-:-Kue4YCI-AIkQ1JI-Mn-:b-kjzh6f)*

**Comment by RoyalSix** [comment]
@klappy Fixed. 👍

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2728)*

**Comment by klappy** [comment]
@royalsix Can you remove the submodule commits?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2728#-:-KugYgMHwAcYIdkTwzvr:b-hkxf09)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2728)*

**Pull request merged**
