### PR TITLE
USFM Export

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Adding USFM export feature. This PR also updates the usfm-parser module in the package.json
module is located at https://github.com/translationCoreApps/usfm-parser which already has been updated.

#### How to test this pull request:
Try exporting a project, and re-importing it.
Try exporting multiple types of projects. Some are referenced in the USFM import PR

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2185)

### CODE REVIEW

**Comment by klappy** [comment]
*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpFFsUdWiBbiLgx0-IK:b875nuc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
> ```JSON
>     "simple-git": "1.43.0",
>     "sudo-prompt": "^6.2.1",
>     "usfm-parser": "git+https://github.com/translationCoreApps/usfm-parser.git",
> ```

Can you add a tag to this and ensure we are only checking out that tag? This can be very dangerous with a simple breaking change to the default branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
*[src/js/actions/MyProjectsActions.js, line 74 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFGZwJwPR2IF0KPOVv:-KpFGZwJwPR2IF0KPOVw:brs8g2l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/MyProjectsActions.js#L74)):*
> ```JavaScript
>       } else {
> 
>         const usfmText = fs.readFileSync(projectFolders[projectName].usfmPath).toString();
> ```

Where does .usfmPath come from? In a previous fix in the other PR, I updated the importing of USFM to archive the source file to fit the full import workflow. This will need to be updated to the archive path after the other is merged or vice versa. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
*[src/js/actions/TargetLanguageActions.js, line 73 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFHTQeztWUA10XQ5EH:-KpFHTQeztWUA10XQ5EI:bbgwjsb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/TargetLanguageActions.js#L73)):*
> ```JavaScript
>     }
>     for (var chapter in entireBook) {
>       if (isNaN(chapter)) continue;
> ```

This will cause a merge conflict with my latest PR. But shouldn't be too difficult to handle. I refactored this to not rely on the finished_chunks array.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
*[src/js/actions/USFMExportActions.js, line 64 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFIaL5whYf9INBB7G3:-KpFIaL5whYf9INBB7G4:b2kvfp9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/USFMExportActions.js#L64)):*
> ```JavaScript
>   let targetLanguageCode = `${manifest.target_language.id}_${manifest.target_language.id}_${manifest.target_language.direction}`
>   /**Date object when project was las changed in FS */
>   let lastEdited = fs.statSync(projectPath).atime;
> ```

Can you use the book folder to get the edit timestamp of just the text?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
This is looking really good. Only a few minor things. I'm adding comments inline to the code and a few here that I couldn't find where to comment...
In testing, two things happen: 
1. Blank verses are exported as undefined instead of an empty string. 
2. I have at least one project that will crash the app while exporting. https://git.door43.org/klappy/hi_eph_text_reg

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-:-KpFDu7u_c0a_ra5zA7r:b-6x8eqn)*

**Comment by klappy** [comment]
Reviewed 2 of 12 files at r1.
Review status: 2 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
Reviewed 2 of 12 files at r1.
Review status: 4 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 5 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 6 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 7 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by RoyalSix** [comment]
Review status: 7 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpG20aYktAkMJfOlNQm:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you add a tag to this and ensure we are only checking out that tag? This can be very dangerous with a simple breaking change to the default branch.
</blockquote></details>

Done.

---

*[src/js/actions/MyProjectsActions.js, line 74 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFGZwJwPR2IF0KPOVv:-KpG40AMOnI8IJrTxLaY:bnjyhn7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/MyProjectsActions.js#L74)):*
>  updated the importing 
This will only happen if a usfm file is present in the translationCore save folder on startup. So I don't know if it will interfere

---

*[src/js/actions/TargetLanguageActions.js, line 73 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFHTQeztWUA10XQ5EH:-KpGQ7-quc7hXrXJWZJZ:b-p3d651) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/TargetLanguageActions.js#L73)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This will cause a merge conflict with my latest PR. But shouldn't be too difficult to handle. I refactored this to not rely on the finished_chunks array.
</blockquote></details>

I saw your implementation is good. I am thinking about merging with yours first. or at least waiting until your PR is merged

---

*[src/js/actions/USFMExportActions.js, line 64 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFIaL5whYf9INBB7G3:-KpGQRtiosiGOj55k3Md:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/src/js/actions/USFMExportActions.js#L64)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you use the book folder to get the edit timestamp of just the text?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by RoyalSix** [comment]
I am making changes on this PR...

**Comment by klappy** [comment]
I keep noticing that your PRs keep failing tests on Travis. For some reason the package-lock.json isn't handling dependencies and missing modules. They also fail on my local machine. To fix them I do two things: 
1. Delete the package-lock.json and node_modules folder. 
2. Run `npm install --save`
3. Run `npm test` and confirm that the tests run.

Can you do that?

**Comment by RoyalSix** [comment]
I did that along with other miscellaneous fixes. The tests are passing locally.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 12 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpJH5JmW4HjcHm1bHKz:blvd9on) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

shouldn't a tag look as following `@0.2.1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-:-KpJI-oyk92h2NOgmnPt:bnfp4nl)*

**Comment by klappy** [comment]
*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpL6o4Vwbea2_WTCrJj:b84iozu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

shouldn't a tag look as following `@0.2.1`
</blockquote></details>

Looks like he's right: https://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpM6Z8EPYDLrb6GWAUN:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Looks like he's right: https://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpMgIylpijcQXD0rg8n:b-8tx2e6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

btw isnt that our module??? lol
why are we concern about using other versions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by mannycolon** [comment]
@RoyalSix @klappy why don't we just post the new version of `usfm-parser` to npm.

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpPu-k6Q6-_c3ZJQuQD:b-12qfxe) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

btw isnt that our module??? lol
why are we concern about using other versions?
</blockquote></details>

That module that we were using was on ians github

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by mannycolon** [comment]
@RoyalSix @klappy Yeah that's what I mean we should publish our own updated copy.

**Comment by RoyalSix** [comment]
Ok yea lets do it! Recommendations on naming? @klappy @mannycolon

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-:-KpQ967jArAwEcHVyeAN:b-go9igg)*

**Comment by mannycolon** [comment]
`usfm-formatter`, `js-usfm-parser` or `usfm-parser-io` idk naming is the hardest thing ever lol

**Comment by mannycolon** [comment]
USFM export doesn't work if the project was never opened with `tC`

**Comment by mannycolon** [comment]
@RoyalSix I get the following two errors when exporting and then reimporting the following project.
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1159578/fr_eph_text_ulb.zip)

```
TypeError: Cannot read property 'includes' of undefined
    at Object.getIDsFromUSFM (LoadHelpers.js [sm]:422)
    at Object.setUpUSFMFolderPath (ProjectSelectionHelpers.js [sm]:41)
    at /Users/mannycolon/dev/translationCore/src/js/actions/ImportLocalActions.js:41
    at CallbacksRegistry.apply (/Users/mannycolon/dev/translationCore/node_modules/electron-prebuilt-compile/node_modules/electron/…:48)
    at EventEmitter.<anonymous> (/Users/mannycolon/dev/translationCore/node_modules/electron-prebuilt-compile/node_modules/electron/…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:194)
```

```
Uncaught TypeError: Cannot read property 'id' of null
    at Object.setUpUSFMFolderPath (ProjectSelectionHelpers.js [sm]:38)
    at /Users/mannycolon/dev/translationCore/src/js/actions/ImportLocalActions.js:41
    at CallbacksRegistry.apply (/Users/mannycolon/dev/translationCore/node_modules/electron-prebuilt-compile/node_modules/electron/…:48)
    at EventEmitter.<anonymous> (/Users/mannycolon/dev/translationCore/node_modules/electron-prebuilt-compile/node_modules/electron/…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:194)
```

**Comment by RoyalSix** [comment]
@mannycolon I tried exporting and re-importing that project multiple times and I couldn't reproduce your errors.

**Comment by mannycolon** [comment]
Reviewed 2 of 6 files at r4, 7 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpR3efN41P0oqnc4UW8:bw5y1ni) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

That module that we were using was on ians github
</blockquote></details>

did you get a chance to update Ians module?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-KpFFsUdWiBbiLgx0-IJ:-KpRBDEwkrR_cf7_a5xO:b-8f4s09) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4bf99ffcb5dffa8603ebd7eccb0c1d39eebff96/package.json#L89)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

did you get a chance to update Ians module?
</blockquote></details>

Yea I tried, it looks like I don't have push permissions to the repo anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by RoyalSix** [comment]
I wasn't able to get a non opened project showing up in the 'my projects' section I used [this](https://github.com/unfoldingWord-dev/translationCore/files/1160158/bil_1ti_text_reg.zip) project and the project card is half rendered as such 
screen shot 2017-07-19 at 9 34 25 am
@mannycolon @klappy

**Comment by mannycolon** [comment]
@RoyalSix Have you verify if the manifest file has all the required data?

**Comment by mannycolon** [comment]
Same thing happens with this project [gux_tit_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1160230/gux_tit_text_reg.zip)

**Comment by mannycolon** [comment]
Don't know why yet. They also don't open when using the `Open local project option`

**Comment by RoyalSix** [comment]
Those issues should be fixed @mannycolon

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185)*

**Comment by mannycolon** [comment]
I exported the following project 
[ar_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1162818/ar_eph_text_ulb.zip) and reimported it using the `local import` option and got the following error.

Here is the .usfm file just in case it's helpful: [ar_eph_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1162820/ar_eph_text_ulb.usfm.zip)

screen shot 2017-07-20 at 11 22 35 am

**Comment by mannycolon** [comment]
The same happened with this file when importing it from local.

[fr_eph_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1162825/fr_eph_text_ulb.usfm.zip)

**Comment by RoyalSix** [comment]
I just imported to tC (ar_eph_text_ulb)  --> exported to USFM (ar_eph_text_ulb) --> imported to tC (ar_eph_text_ulb.usfm) and no errors

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-:-KpVdy8kSbe7UZvQyADJ:b-335xkz)*

**Comment by mannycolon** [comment]
@RoyalSix when you say `imported` do you mean imported the project using the local import option?

**Comment by RoyalSix** [comment]
Yes @mannycolon

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2185#-:-Kp_fI7_etirvdWgKbyC:bnfp4nl)*

**Pull request merged**
