### PR TITLE
Added SET_PROJECT_DETAIL action to project details actions

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

this PR adds an action **setProjectDetail()** which sets a project detail to the projectdetailReducer.
for example:

```
"source_translations": [
    {
      "language_id": "en",
      "resource_id": "ulb",
      "checking_level": "",
      "date_modified": "2017-03-27T16:59:29.727Z",
      "version": ""
    }
```

#### How to test this pull request:

- Import the **setProjectDetail()** in the toolsContainer.js
- Add it to the matchDispatchToProps and call it inside a componentWillMount() as follows: **this.props.actions.setProjectDetail( )**

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1007)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/actions/projectDetailsActions.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga41WLfyrDarjiuCYH:-Kga41WMFECTbQVA2LfA:b-x5p5ja) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L23)):*
> ```JavaScript
>  *  }
>  * @param {sting} detailName - projectDetailReducer property name where detailData is saved.
>  * @param {multiple} detailData - this varaiable could be anything from a string, array,
> ```

Instead of "multiple" the standard convention for any type is * (see: http://usejsdoc.org/tags-param.html). If we ever implement some kind of web docs for TC it wouldn't recognize "multiple" if they were auto-generated but it would recognize *

---

*[src/js/actions/projectDetailsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga4Od1RgDM5kx1SSdR:-Kga4Od1RgDM5kx1SSdS:bagtmq5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L31)):*
> ```JavaScript
>     type: consts.SET_PROJECT_DETAIL,
>     detailName,
>     detailData
> ```

This actually brings up a more interesting point. Do we want an action that exports a function this generic? I am just worried this could easily be abused/misused for the wrong things. The more explicit we are in our actions the less likely someone is to use them incorrectly and this just seems like it could open the door for all sorts of new misuse. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by mannycolon** [comment]
@EllDoubleYew as we spoke on vidyo, this is a middle point to where we want to be. so after jay finishes his PRs i will be able to determined what exact actions we need.

**Comment by klappy** [comment]
*[src/js/actions/projectDetailsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga4Od1RgDM5kx1SSdR:-KgatBOJypmslABtJwnC:bhj7988) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L31)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

This actually brings up a more interesting point. Do we want an action that exports a function this generic? I am just worried this could easily be abused/misused for the wrong things. The more explicit we are in our actions the less likely someone is to use them incorrectly and this just seems like it could open the door for all sorts of new misuse. What do you think?
</blockquote></details>

Sadly many other actions/reducers can be a generic store for what ever they want. I'm more concerned about us being too specific than too generic at this point. I think we're okay in these cases. But yes, it could be abused but I'm not too concerned yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
*[src/js/actions/projectDetailsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga4Od1RgDM5kx1SSdR:-Kgatdxf3BoXzwmW7ERh:b91u7lz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Sadly many other actions/reducers can be a generic store for what ever they want. I'm more concerned about us being too specific than too generic at this point. I think we're okay in these cases. But yes, it could be abused but I'm not too concerned yet.
</blockquote></details>

Since it is this generic, maybe just call it "key" and "value" instead of detailName and detailData :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kgau05FfUQbyOwhHYvJ:-Kgau05Gqf4cd5iEUH41:b-vwqhj7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f681f76d94c468af05a52b1292700e929fee285e/src/js/reducers/projectDetailsReducer.js#L21)):*
> ```JavaScript
>         manifest: action.manifest
>       }
>       break;
> ```

Why get rid of the breaks? Do we want it to keep looping through and hitting more than one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by mannycolon** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/projectDetailsActions.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga41WLfyrDarjiuCYH:-KgeLhbbcastytS46rkd:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L23)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Instead of "multiple" the standard convention for any type is "*" (see: http://usejsdoc.org/tags-param.html). If we ever implement some kind of web docs for TC it wouldn't recognize "multiple" if they were auto-generated but it would recognize "*"
</blockquote></details>

Done.

---

*[src/js/actions/projectDetailsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kga4Od1RgDM5kx1SSdR:-KgeLja0TjMvEk84gYnA:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d7a54b28211116a2f1fbe00902c49bed2c01cd3f/src/js/actions/projectDetailsActions.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Since it is this generic, maybe just call it "key" and "value" instead of detailName and detailData :)
</blockquote></details>

Done.

---

*[src/js/reducers/projectDetailsReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kgau05FfUQbyOwhHYvJ:-KgeL2qt4iOyszpu-BW2:bf2bkvs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f681f76d94c468af05a52b1292700e929fee285e/src/js/reducers/projectDetailsReducer.js#L21)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Why get rid of the breaks? Do we want it to keep looping through and hitting more than one?
</blockquote></details>

return handles the break, therefore, we don't need the break

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-Kgau05FfUQbyOwhHYvJ:-KgoO10soY5fUm0S55Mq:b4n02cf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f681f76d94c468af05a52b1292700e929fee285e/src/js/reducers/projectDetailsReducer.js#L21)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

return handles the break, therefore, we don't need the break
</blockquote></details>

Oh yeah, that's right, I remember testing that for another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1007#-:-KgoOEifmkwUaFx6kI7X:bnfp4nl)*

**Pull request merged**
