### PR TITLE
Feature #3186/migrate alignment data

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Migrates alignment data to tc version 2.  Changes 'strongs' to 'strong'.  Fixes mistakes in target language occurrence(s) counts.

#### How to test this pull request:

When you open a tc version 1 project, the manifest will get updated to tc version 2. Also alignment data (in '.apps/translationCore/alignmentData') should have references to strongs converted to strong, as well as occurrence/occurrences cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3749)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 2 of 19 files at r1.
Review status: 2 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 10 of 19 files at r1.
Review status: 12 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 3 of 19 files at r1.
Review status: 15 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 1 of 19 files at r1.
Review status: 16 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 1 of 19 files at r1.
Review status: 17 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4hIaM009TXhjTOV7Nq:-L4hIaM009TXhjTOV7Nr:b-akz6hd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L77)):*
> ```JavaScript
>         alignmentWords[word][occurrence] = wordItem;
>       }
> ```

This is looking good. I can follow along but it's a little challenging to follow what is in certain variables.
Do you mind adding a little more documentation for some of the complex lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by mannycolon** [comment]
Reviewed 5 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by RoyalSix** [comment]
Reviewed 9 of 19 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i3KZMgijHNKHR1dXE:-L4i3KZMgijHNKHR1dXF:brp4ua4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
> ```JavaScript
> 
>       let modifiedOccurrence = false;
>       for (let word of Object.keys(alignmentWords)) {
> ```

Wondering why you didn't use something like?
```
alignmentWords.map( (wordData) => {
//use wordData here
})
```
Was it just preference?

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 87 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i46hEGMMVNRmx5hYF:-L4i46hEGMMVNRmx5hYG:b-ar1mcz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L87)):*
> ```JavaScript
>           const wordItem = wordData[itemOccurrence];
>           if (parseInt(itemOccurrence) !== i + 1) { // if occurrence is off
>             console.log("changing occurrence of '" + wordItem.word + "' from " + wordItem.occurrence +
> ```

These are useful for testing/development, but now that its going to be in  production do we need the logs?

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 100 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i4GLx-1D5XmvGU1LT:-L4i4GLyH7v9qdQJzqWv:b-ar1mcz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L100)):*
> ```JavaScript
> 
>       if (modifiedOccurrence) {
>         console.log("updated occurence(s) in verse " + verse + " of '" + path.basename(filePath) + "'");
> ```

These are useful for testing/development, but now that its going to be in  production do we need the logs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[__tests__/fixtures/migration/fix_occurrences/tit1:1.json, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i4qbYCe-bSr7v4e2h:-L4i4qbYCe-bSr7v4e2i:b-9rzvrr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/__tests__/fixtures/migration/fix_occurrences/tit1:1.json#L1)):*
> ```JSON
> {
> ```

Very big file here. Is there no way to leverage other alignment json's present in the app?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by RoyalSix** [comment]
Just tested on this project [this](https://github.com/unfoldingWord-dev/translationCore/files/1701529/bhadrawahi_tit.zip) and I'm getting the following errors in their respective order after only opening.
screen shot 2018-02-06 at 6 31 44 pm
image

The project works fine on develop.

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[__tests__/fixtures/migration/fix_occurrences/tit1:1.json, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i4qbYCe-bSr7v4e2h:-L4k4y20se_3wRnCdSd1:b-spme53) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/__tests__/fixtures/migration/fix_occurrences/tit1:1.json#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Very big file here. Is there no way to leverage other alignment json's present in the app?
</blockquote></details>

No, this has specific occurrence errors that need to be fixed.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i3KZMgijHNKHR1dXE:-L4k5IYFflxjXwSwdiBd:blfzdpp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Wondering why you didn't use something like?
```
alignmentWords.map( (wordData) => {
//use wordData here
})
```
Was it just preference?
</blockquote></details>

Good point, that would be simpler.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 87 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i46hEGMMVNRmx5hYF:-L4k5RbPuYv7VgHbxk9V:bdcv6l8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L87)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

These are useful for testing/development, but now that its going to be in  production do we need the logs?
</blockquote></details>

Good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i3KZMgijHNKHR1dXE:-L4k7bZMJzEzyIpN-aX9:b-4s1rla) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Good point, that would be simpler.
</blockquote></details>

Hmm...alignmentWords is an object, not an array.  Not sure how to simplify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Oops, need to filter out .DS_Store.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-:-L4k8wPF8r5F_F9pa1Il:b-1h1qj2)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 100 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4i4GLx-1D5XmvGU1LT:-L4k9A6P8JtCcLz8E__P:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L100)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

These are useful for testing/development, but now that its going to be in  production do we need the logs?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4kN9BM7KL_cyfqdTgj:-L4kN9BM7KL_cyfqdTgk:b-8rz22) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
> ```JavaScript
> 
>       let modifiedOccurrence = false;
>       for (let word of Object.keys(alignmentWords)) {
> ```

Looks like i can just do this over object:  for (let word of alignmentWords) {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4kN9BM7KL_cyfqdTgj:-L4kOXY9bvsMy0CyTrTi:b-ut45g6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Looks like i can just do this over object:  for (let word of alignmentWords) {
</blockquote></details>

Nuts - doesn't work in our babel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4kN9BM7KL_cyfqdTgj:-L4kPLnMoeotjTBnoBN0:b-fzyssh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L79)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Nuts - doesn't work in our babel.
</blockquote></details>

OK, see that you have to use 'in' to iterate objects and 'of' for arrays.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/helpers/ProjectMigration/migrateToVersion2.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-L4hIaM009TXhjTOV7Nq:-L4kbfa7VfjmIxBYfQXe:b-8s6148) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00e17d07632311d1ad16c2f299c8ae5d104a3278/src/js/helpers/ProjectMigration/migrateToVersion2.js#L77)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This is looking good. I can follow along but it's a little challenging to follow what is in certain variables.
Do you mind adding a little more documentation for some of the complex lines?

</blockquote></details>

Not just the variable names, but the code needs to be broken down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r2.
Review status: 19 of 20 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-:-L4lJmabKfSjU1MK1v8f:bnfp4nl)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3749#-:-L4lL8_42IbGQSDoivkJ:bnfp4nl)*

**Pull request merged**
