### PR TITLE
Invalidated Alignment Data

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR addresses resetting invalidated alignments.
  - Invalid alignments can be caused by changes to the target language verse text (which have been aligned), or to the greek source text (which has been aligned).
  - Check the [story](https://github.com/unfoldingWord-dev/translationCore/issues/3193) for a more detailed description.

#### Please include detailed Test instructions for your pull request:
- First make sure you are on the latests tC_resources, node modules, and tC_apps.
- Open a project with or without alignments.
- Do some alignments (remember the verse!)
- Open the tW tool, edit that same verse in the target language. Save.
- Open the word alignment tool, the alignments should now be reset.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3894)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_resources, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894#-L5skcNFR3fxR2ObMVJE:-L5skcNFR3fxR2ObMVJF:bn2cbdz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5d96ea8cd10cfa457a75eabd74519a8dc4181766/tC_resources#L1)):*
> ```
> Subproject commit 10495055b15ffc000b3f68fd10a9735d2ec5fe56
> ```

Are you sure you want to commit this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/VerseObjectHelpers.js, line 128 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894#-L5sl1Ueol4SW76HIzRH:-L5sl1Ueol4SW76HIzRI:bozwtjk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5d96ea8cd10cfa457a75eabd74519a8dc4181766/src/js/helpers/VerseObjectHelpers.js#L128)):*
> ```JavaScript
>  * @description merge verse data into a string
>  * @param {Object|Array} verseData
>  * @param {array}
> ```

missing variable name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by PhotoNomad0** [comment]
Sorry, saw this in review, but didn't notice that this was WIP.

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 13 files at r2.
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by PhotoNomad0** [comment]
Reviewed 4 of 13 files at r2.
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[__tests__/VerseObjectHelpers.test.js, line 186 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894#-L5xo7lEmOMW7MgR37kj:-L5xo7lEmOMW7MgR37kk:b6m029k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbf9e5fcb252d73ec0dd12262c36c1438191382b/__tests__/VerseObjectHelpers.test.js#L186)):*
> ```JavaScript
>   it('handles arrays with nested milestones and text', () => {
>     // given
>     const testFile = path.join('__tests__', 'fixtures', 'verseObjects', 'matt1-1.json');
> ```

Not comfortable with replacing `tit1-4.json` with `matt1-1.json`.  matt1-1.json file here doesn't have any milestones in it at all.  I think the whole point here was to make sure that we can handle the case of milestones nested within milestones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by PhotoNomad0** [comment]
Have a Hebrew project with a verse aligned.  As soon as I open it in WA tool my alignments are reset.  Looking to see what is causing that to make sure the reason is valid.  It certainly is annoying to have the work all wiped out.

**Comment by PhotoNomad0** [comment]
It looks like the problem is with the Greek in checkVerseForChanges() - the words are the same but in different order.  Makes me wonder if we need to order the alignments before getting the greek word list.  Think we did something like that in merge (or unmerge).  Don't think users will be happy having all their work wiped out due to alignments not being sorted properly.  Thoughts @klappy ?

**Comment by PhotoNomad0** [comment]
Also opened Aligned Hindi ULB.  It wiped out the alignments for the first verse due to a comma in the UGNT greek.

**Comment by PhotoNomad0** [comment]
[hi_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1748471/hi_tit.zip)

Here is an example, even though it detects 1:1 has changed, alignments remain.  But in 1:2 it clears all alignments.

**Comment by PhotoNomad0** [comment]
[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1748492/English_tit.zip)

This has similar issues.  But also in Titus 3:3 the complete indicators turning on an off as you move between various verses (it cleared the alignments thinking the verse has changed, it should not be turning on).  For example when I change selection from 3:3 to 3:4 the check mark turns on for 3:3 even though it has no alignments.  Then when I select 3:5, the check mark turns off for 3:3.

**Comment by RoyalSix** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/helpers/VerseObjectHelpers.js, line 128 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894#-L5sl1Ueol4SW76HIzRH:-L5yRcxEVoonzoA9sehu:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5d96ea8cd10cfa457a75eabd74519a8dc4181766/src/js/helpers/VerseObjectHelpers.js#L128)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

missing variable name
</blockquote></details>

Done.

---

*[tC_resources, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894#-L5skcNFR3fxR2ObMVJE:-L5yRnNT0AwmrBFd2Rly:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5d96ea8cd10cfa457a75eabd74519a8dc4181766/tC_resources#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Are you sure you want to commit this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by RoyalSix** [comment]
The projects you sent have blank `.usfm` files @PhotoNomad0 
I will see if I can reporduce

**Comment by PhotoNomad0** [comment]
> The projects you sent have blank .usfm files @PhotoNomad0
> I will see if I can reporduce

these are full projects zipped up - alignments and json, etc. should be able to unzip into projects folder.

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 13 files at r2, 3 of 3 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3894)*

**Comment by RoyalSix** [comment]
Do not show button, 
Change current verse to this verse
Don't show alert if there were not alignments

**Pull request closed without merging**
