### PR TITLE
This PR introduces ES6 compiling to our codebase (hurray!!)

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/597)

### CODE REVIEW

**Comment by RoyalSix** [comment]
These tests need to pass, or do the tests need to change

**Comment by mannycolon** [comment]
I believe tests need to change

**Comment by mannycolon** [comment]
@ihoegen

**Comment by mannycolon** [comment]
@RoyalSix @ihoegen this test error have nothing to do with this PR. **if your run NPM TEST on develop you will get the same errors**

**Comment by RoyalSix** [comment]
@mannycolon The tests are passing on develop for me

**Comment by ihoegen** [comment]
Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/597)*

**Pull request merged**
