### PR TITLE
WIP: Bugfix #2714/usfm import fixes

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: https://github.com/unfoldingWord-dev/translationCore/issues/2714

Update to use new usfm-js with USFM parsing fixes.

#### How to test this pull request:

Waiting for usfm-js to be published.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3512)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3512)*

**Comment by mannycolon** [comment]
@PhotoNomad0 when i run **npm install** i get `No matching version found for usfm-js@1.0.0-beta.17.2`

**Comment by klappy** [comment]
Can we close this one? It was addressed in another PR that already got merged.

**Comment by richmahn** [comment]
Why is this still WIP, and others are saying it is already fixed? What should be done? Closed as in don't merge close, or merge close?

**Comment by PhotoNomad0** [comment]
The remaining items in this issue have already been resolved in tc app, no need to modify usfm-js for chapters with leading 0's and inline verse markers.

**Comment by PhotoNomad0** [comment]
The remaining items in this issue have already been resolved in tc app, no need to modify usfm-js for chapters with leading 0's and inline verse markers.

**Pull request closed without merging**
