### PR TITLE
Updated locale strings

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):

Related to https://github.com/unfoldingWord-dev/translationCore/issues/4030

- The English locale (the source locale) has been migrated to the newly organized json file provided by Koz.
- Added two utilities for discovering missing and un-used locale strings.
  - `npm run find:extra-local`
  - `npm run find:missing-locale`
- Removed all locale except English and Hindi

#### Please include detailed Test instructions for your pull request:

- Just locale changes. You can run the app to ensure everything works.
- There are still a few corner cases that are not yet localized. Some of those will require components be refactored.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4104)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 12 of 138 files at r1.
Review status: 12 of 138 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by mannycolon** [comment]
Reviewed 65 of 138 files at r1.
Review status: 77 of 138 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by mannycolon** [comment]
Reviewed 61 of 138 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by mannycolon** [comment]
@neutrinog Is this PR supposed to add the Hindi strings?

**Comment by mannycolon** [comment]
**Code Review:** `LGTM`
**Local Test:** `LGTM`

**Comment by mannycolon** [comment]
@neutrinog Please dont type the word `fixes` before the issue number since that will close the issue when we merge the PR

**Comment by da1nerd** [comment]
@mannycolon  Yes this is supposed to add Hindi strings.
None of the commits contain `fixes <issue number>`.

**Comment by mannycolon** [comment]
> None of the commits contain fixes <issue number>.

@neutrinog Because I removed it

**Comment by mannycolon** [comment]
@neutrinog so are we supposed to have the localized Hindi strings in tC?

**Comment by da1nerd** [comment]
Re `fixes`: Ah, I thought that only applied to the actual commits not the PR description. I [see now](https://help.github.com/articles/closing-issues-using-keywords/) that it does.

Regarding Hindi strings see the related issue (#4030).

**Note**: This localization into Hindi is just a rough draft using a machine translator. Once @cckozie is pleased with the string migration I'm sure we'll find some humans to review the Hindi locale before release.

**Comment by mannycolon** [comment]
@neutrinog Ok looks good

**Comment by da1nerd** [comment]
@mannycolon I'm blocking this temporarily so we can run the Hindi translation through the Google translator. It should be a bit more accurate.

**Comment by klappy** [comment]
Reviewed 32 of 138 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by klappy** [comment]
Reviewed 3 of 138 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by da1nerd** [comment]
@mannycolon this is good to go.

>EDIT: except I forgot to update the tests!

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104#-:-L89pQwl_Uyfe5HQ3HIT:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 39 of 138 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by klappy** [comment]
Reviewed 2 of 138 files at r1, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Comment by klappy** [comment]
Reviewed 55 of 138 files at r1, 13 of 14 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4104)*

**Pull request merged**
