### PR TITLE
New Menu/Submenu Implementation

### PR DESCRIPTION
**Pull request by mannycolon**
- Test using multiple projects from different sources (**local storage**, **Door43**, maybe even **usfm** files)

- Test using **translationWords**, **translationNotes** and even the **checkingRubric tool** would work

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/309)

### CODE REVIEW

**Comment by mannycolon** [comment]
#305 #306

**Comment by mannycolon** [comment]
#305

**Comment by mannycolon** [comment]
#306

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/309)_

**Comment by ihoegen** [comment]
Reviewed 4 of 9 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/309)*

**Comment by ihoegen** [comment]
When performing a test check, I get this error.
This occurs when I click save and continue.
```
C:\Users\Ian\AppData\Roaming\translationCore\packages-compiled\translationNotes\View.js:219 Uncaught TypeError: Cannot read property 'chapter' of undefinedReactErrorUtils.invokeGuardedCallback @ C:\Users\Ian\Documents\Work\tC\node_modules\react\lib\ReactErrorUtils.js:70
C:\Users\Ian\AppData\Roaming\translationCore\packages-compiled\translationNotes\View.js:112 Uncaught TypeError: Cannot read property 'checkStatus' of undefined
```

**Comment by mannycolon** [comment]
@ihoegen 
That looks like a problem with modules (tools) not my changes

what project did you use?
do you know how i can recreate it that error?

**Comment by mannycolon** [comment]
@ihoegen i hadn't merge with develop that's why i didn't work. should be fine now.

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/309)*

**Pull request merged**
