### PR TITLE
Feature 6600/Add markdown support to occurrenceNotes

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- added markdown conversion to html for displayed occurrenceNote

#### Please include detailed Test instructions for your pull request:
- already tested with https://github.com/unfoldingWord/tc-ui-toolkit/pull/247, but if you want to test again:
  - can test with attached build.  Should support strong/emphasis in tN.  
  - open a titus project with GL set to EN and should not see markdown such as the *** displayed checks (see https://github.com/unfoldingword/translationcore/issues/6600)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6607)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (9582c1f)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-9582c1f.deb) is ready for download.
[macOS build 2.1.0 (9582c1f)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-9582c1f.dmg) is ready for download.
[Windows x64 build 2.1.0 (9582c1f)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-9582c1f.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (9582c1f)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-9582c1f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (e7d4a0e)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-e7d4a0e.deb) is ready for download.
[macOS build 2.1.0 (e7d4a0e)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-e7d4a0e.dmg) is ready for download.
[Windows x64 build 2.1.0 (e7d4a0e)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-e7d4a0e.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (e7d4a0e)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-e7d4a0e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-3df9aaf.deb) is ready for download.
[macOS build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-3df9aaf.dmg) is ready for download.
[Windows x64 build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-3df9aaf.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-3df9aaf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-3df9aaf.deb) is ready for download.
[macOS build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-3df9aaf.dmg) is ready for download.
[Windows x64 build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-3df9aaf.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3df9aaf)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-3df9aaf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (1ad4aa8)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-1ad4aa8.deb) is ready for download.
[macOS build 2.1.0 (1ad4aa8)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-1ad4aa8.dmg) is ready for download.
[Windows x64 build 2.1.0 (1ad4aa8)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-1ad4aa8.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (1ad4aa8)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-1ad4aa8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (22c9dd6)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-linux-x64-2.1.0-22c9dd6.deb) is ready for download.
[macOS build 2.1.0 (22c9dd6)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-macos-x64-2.1.0-22c9dd6.dmg) is ready for download.
[Windows x64 build 2.1.0 (22c9dd6)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x64-2.1.0-22c9dd6.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (22c9dd6)](https://tc-builds.door43.org/build/feature-mcleanb-6600/translationCore-win-x32-2.1.0-22c9dd6.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
