### PR TITLE
New Eslint Config

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6414)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (f4cb6d7)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-f4cb6d7.deb) is ready for download.
[macOS build 2.0.0 (f4cb6d7)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-f4cb6d7.dmg) is ready for download.
[Windows x64 build 2.0.0 (f4cb6d7)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-f4cb6d7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (f4cb6d7)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-f4cb6d7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (d72e080)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-d72e080.deb) is ready for download.
[macOS build 2.0.0 (d72e080)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-d72e080.dmg) is ready for download.
[Windows x64 build 2.0.0 (d72e080)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-d72e080.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (d72e080)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-d72e080.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (fbf7f42)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-fbf7f42.deb) is ready for download.
[macOS build 2.0.0 (fbf7f42)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-fbf7f42.dmg) is ready for download.
[Windows x64 build 2.0.0 (fbf7f42)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-fbf7f42.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (fbf7f42)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-fbf7f42.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Please dont merge this yet

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (20e1afe)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-20e1afe.deb) is ready for download.
[macOS build 2.0.0 (20e1afe)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-20e1afe.dmg) is ready for download.
[Windows x64 build 2.0.0 (20e1afe)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-20e1afe.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (20e1afe)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-20e1afe.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (3afc6c6)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-3afc6c6.deb) is ready for download.
[macOS build 2.0.0 (3afc6c6)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-3afc6c6.dmg) is ready for download.
[Windows x64 build 2.0.0 (3afc6c6)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-3afc6c6.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (3afc6c6)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-3afc6c6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (09ceee9)](https://tc-builds.door43.org/build/feature-eslint/translationCore-linux-x64-2.0.0-09ceee9.deb) is ready for download.
[macOS build 2.0.0 (09ceee9)](https://tc-builds.door43.org/build/feature-eslint/translationCore-macos-x64-2.0.0-09ceee9.dmg) is ready for download.
[Windows x64 build 2.0.0 (09ceee9)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x64-2.0.0-09ceee9.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (09ceee9)](https://tc-builds.door43.org/build/feature-eslint/translationCore-win-x32-2.0.0-09ceee9.setup.exe) is ready for download.

**Pull request merged**
