### PR TITLE
Remove rollbar from development, only enabled on production

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request removes Rollbar from the development branch, but copies it back into production when a build is created. This is good because sometimes when developing errors are thrown, and we don't exactly want for that to happen. This is important for the integrating Rollbar with Github, as it will decrease our number of stories. 

#### How to test this pull request:

There isn't really a way to test this, you will most likely need to wait until a build is created.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/771)

### CODE REVIEW

**Comment by ihoegen** [comment]
Rollbar issues are now connected to Github issues as well.

**Comment by EllDoubleYew** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[index.html, line 20 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771#-Ke0nV07vA-kHigOxRlw:-Ke0nV08iL5m57JS6VEr:balc11u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36a0ffe0a0290b90372eccd9f224545db80a26c5/index.html#L20)):*
> ```HTML
>     
>     <link rel="stylesheet" type="text/css" href="src/css/styles.css">
>     <script>
> ```

Thank god this is gone

---

*[requirements.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771#-Ke0nbkkLuMMFv9HI1FA:-Ke0nbkkLuMMFv9HI1FB:b-a0y57p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36a0ffe0a0290b90372eccd9f224545db80a26c5/requirements.js#L38)):*
> ```JavaScript
>         }
>       });
>       Rollbar.error(JSON.stringify(err));
> ```

So there is some sketchiness that comes from error handling in requirements.js. Sometimes the stack trace gets messed up. We will see how rollbar interprets these error stacks but it may end up stripping info. If so we will need to find another place to catch these guys.

---

*[scripts/builds/index.html, line 28 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771#-Ke0nuhuMJ9pfWRlQgd-:-Ke0nuhuMJ9pfWRlQgd0:b-9gc8iq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6dfc11c381859b8542af95918dee5623400be272/scripts/builds/index.html#L28)):*
> ```HTML
>         }
>     };
>     !function(r){function e(t){if(o[t])return o[t].exports;var n=o[t]={exports:{},id:t,loaded:!1};return r[t].call(n.exports,n,n.exports,e),n.loaded=!0,n.exports}var o={};return e.m=r,e.c=o,e.p="",e(0)}([function(r,e,o){"use strict";var t=o(1).Rollbar,n=o(2);_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||"https://d37gvrvc0wt4s1.cloudfront.net/js/v1.9/rollbar.min.js";var a=t.init(window,_rollbarConfig),i=n(a,_rollbarConfig);a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,i)},function(r,e){"use strict";function o(r){return function(){try{return r.apply(this,arguments)}catch(e){try{console.error("[Rollbar]: Internal error",e)}catch(o){}}}}function t(r,e,o){window._rollbarWrappedError&&(o[4]||(o[4]=window._rollbarWrappedError),o[5]||(o[5]=window._rollbarWrappedError._rollbarContext),window._rollbarWrappedError=null),r.uncaughtError.apply(r,o),e&&e.apply(window,o)}function n(r){var e=function(){var e=Array.prototype.slice.call(arguments,0);t(r,r._rollbarOldOnError,e)};return e.belongsToShim=!0,e}function a(r){this.shimId=++c,this.notifier=null,this.parentShim=r,this._rollbarOldOnError=null}function i(r){var e=a;return o(function(){if(this.notifier)return this.notifier[r].apply(this.notifier,arguments);var o=this,t="scope"===r;t&&(o=new e(this));var n=Array.prototype.slice.call(arguments,0),a={shim:o,method:r,args:n,ts:new Date};return window._rollbarShimQueue.push(a),t?o:void 0})}function l(r,e){if(e.hasOwnProperty&&e.hasOwnProperty("addEventListener")){var o=e.addEventListener;e.addEventListener=function(e,t,n){o.call(this,e,r.wrap(t),n)};var t=e.removeEventListener;e.removeEventListener=function(r,e,o){t.call(this,r,e&&e._wrapped?e._wrapped:e,o)}}}var c=0;a.init=function(r,e){var t=e.globalAlias||"Rollbar";if("object"==typeof r[t])return r[t];r._rollbarShimQueue=[],r._rollbarWrappedError=null,e=e||{};var i=new a;return o(function(){if(i.configure(e),e.captureUncaught){i._rollbarOldOnError=r.onerror,r.onerror=n(i);var o,a,c="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(o=0;o<c.length;++o)a=c[o],r[a]&&r[a].prototype&&l(i,r[a].prototype)}return e.captureUnhandledRejections&&(i._unhandledRejectionHandler=function(r){var e=r.reason,o=r.promise,t=r.detail;!e&&t&&(e=t.reason,o=t.promise),i.unhandledRejection(e,o)},r.addEventListener("unhandledrejection",i._unhandledRejectionHandler)),r[t]=i,i})()},a.prototype.loadFull=function(r,e,t,n,a){var i=function(){var e;if(void 0===r._rollbarPayloadQueue){var o,t,n,i;for(e=new Error("rollbar.js did not load");o=r._rollbarShimQueue.shift();)for(n=o.args,i=0;i<n.length;++i)if(t=n[i],"function"==typeof t){t(e);break}}"function"==typeof a&&a(e)},l=!1,c=e.createElement("script"),p=e.getElementsByTagName("script")[0],d=p.parentNode;c.crossOrigin="",c.src=n.rollbarJsUrl,c.async=!t,c.onload=c.onreadystatechange=o(function(){if(!(l||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){c.onload=c.onreadystatechange=null;try{d.removeChild(c)}catch(r){}l=!0,i()}}),d.insertBefore(c,p)},a.prototype.wrap=function(r,e){try{var o;if(o="function"==typeof e?e:function(){return e||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._wrapped){r._wrapped=function(){try{return r.apply(this,arguments)}catch(e){throw"string"==typeof e&&(e=new String(e)),e._rollbarContext=o()||{},e._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=e,e}},r._wrapped._isWrap=!0;for(var t in r)r.hasOwnProperty(t)&&(r._wrapped[t]=r[t])}return r._wrapped}catch(n){return r}};for(var p="log,debug,info,warn,warning,error,critical,global,configure,scope,uncaughtError,unhandledRejection".split(","),d=0;d<p.length;++d)a.prototype[p[d]]=i(p[d]);r.exports={Rollbar:a,_rollbarWindowOnError:t}},function(r,e){"use strict";r.exports=function(r,e){return function(o){if(!o&&!window._rollbarInitialized){var t=window.RollbarNotifier,n=e||{},a=n.globalAlias||"Rollbar",i=window.Rollbar.init(n,r);i._processShimQueue(window._rollbarShimQueue||[]),window[a]=i,window._rollbarInitialized=!0,t.processPayloads()}}}}]);
> ```

What happens when it tries to hit this CDN offline? Does it fail gracefully?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771)*

**Comment by EllDoubleYew** [comment]
So without any concrete way to test this how do we want to handle when we decide to merge?

**Comment by ihoegen** [comment]
Yes it fails gracefully when there is no connection. And surprisingly, it handles stack traces fairly well. The header of the message ends up being the title, and stack trace becomes part of the message

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[scripts/builds/index.html, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771#-Ke4ayzAuaamtkQ9xdH1:-Ke4ayzAuaamtkQ9xdH2:b-z1kuae) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6dfc11c381859b8542af95918dee5623400be272/scripts/builds/index.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

what happens when I make changes to index.html in the src folder?? is it going to merge the changes for both index.html files??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/771)*

**Comment by ihoegen** [comment]
@mannycolon We just have to update the copy as well. This is the setup we have with the index.js, and so far, I haven't had any issues with that. The index.html file probably won't undergo many changes either, so I wouldn't worry too much about it

**Pull request merged**
