### PR TITLE
Bugfix 6275/Fix smurf bar should be in GL

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- remove hard-coding of tN helps to en when copying resources.
- on tn GL changes reload tn Helps index and update occurrence not in contextId

#### Please include detailed Test instructions for your pull request:
- make sure you have latest en and hi resources
- in tN tool for various projects, try launching tN both with en and hi as GL.  Make sure that note in smurf bar matches GL language.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (ad899d9)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-linux-x64-2.0.0-ad899d9.deb) is ready for download.
[macOS build 2.0.0 (ad899d9)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-macos-x64-2.0.0-ad899d9.dmg) is ready for download.
[Windows x64 build 2.0.0 (ad899d9)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x64-2.0.0-ad899d9.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (ad899d9)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x32-2.0.0-ad899d9.setup.exe) is ready for download.

**Comment by richmahn** [comment]
I get an error when I load this project and go into tN.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @richmahn)

___
*[src/js/actions/ProjectDetailsActions.js, line 135 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283#-LkyO6O231lE1wzJlOeS:-LkyO6O375-oyByukO1T:b-kxm9pz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ad899d929653a98ea90bf015806a4591f04ad8ce/src/js/actions/ProjectDetailsActions.js#L135)):*
> ```JavaScript
>     dispatch(ResourcesActions.loadBiblesByLanguageId(selectedGL));
>     if (toolName === TRANSLATION_NOTES) {
>       dispatch(ResourcesHelpers.updateGroupIndexForGl(toolName, selectedGL));
> ```

Can you explain why this only needs to happen for tN?

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @richmahn)

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @richmahn and @RoyalSix)

___
*[src/js/actions/ProjectDetailsActions.js, line 135 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283#-LkyO6O231lE1wzJlOeS:-LkyQUxY-nDsOqLDPCWZ:b-3bvn6u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ad899d929653a98ea90bf015806a4591f04ad8ce/src/js/actions/ProjectDetailsActions.js#L135)):*
> ```
> updateGroupIndexForGl
> ```

I had in updateGroupIndexForGl(), but will copy it here.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (e733502)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-linux-x64-2.0.0-e733502.deb) is ready for download.
[macOS build 2.0.0 (e733502)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-macos-x64-2.0.0-e733502.dmg) is ready for download.
[Windows x64 build 2.0.0 (e733502)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x64-2.0.0-e733502.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (e733502)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x32-2.0.0-e733502.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (dc8aaba)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-linux-x64-2.0.0-dc8aaba.deb) is ready for download.
[macOS build 2.0.0 (dc8aaba)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-macos-x64-2.0.0-dc8aaba.dmg) is ready for download.
[Windows x64 build 2.0.0 (dc8aaba)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x64-2.0.0-dc8aaba.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (dc8aaba)](https://tc-builds.door43.org/build/bugfix-mcleanb-6275/translationCore-win-x32-2.0.0-dc8aaba.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6283#-:-LkyoD0DA16gThTTqQyT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
