### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5359)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (7ffcb24)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-7ffcb24.deb) is ready for download.
[macOS build 1.1.0 (7ffcb24)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-7ffcb24.dmg) is ready for download.
[Windows x64 build 1.1.0 (7ffcb24)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-7ffcb24.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (7ffcb24)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-7ffcb24.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fb73814)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fb73814.deb) is ready for download.
[macOS build 1.1.0 (fb73814)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fb73814.dmg) is ready for download.
[Windows x64 build 1.1.0 (fb73814)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fb73814.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fb73814)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fb73814.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (07e615c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-07e615c.deb) is ready for download.
[macOS build 1.1.0 (07e615c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-07e615c.dmg) is ready for download.
[Windows x64 build 1.1.0 (07e615c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-07e615c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (07e615c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-07e615c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (94e49ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-94e49ba.deb) is ready for download.
[macOS build 1.1.0 (94e49ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-94e49ba.dmg) is ready for download.
[Windows x64 build 1.1.0 (94e49ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-94e49ba.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (94e49ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-94e49ba.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-8890f30.deb) is ready for download.
[macOS build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-8890f30.dmg) is ready for download.
[Windows x64 build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-8890f30.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-8890f30.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-8890f30.deb) is ready for download.
[macOS build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-8890f30.dmg) is ready for download.
[Windows x64 build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-8890f30.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8890f30)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-8890f30.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a41e9ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-a41e9ba.deb) is ready for download.
[macOS build 1.1.0 (a41e9ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-a41e9ba.dmg) is ready for download.
[Windows x64 build 1.1.0 (a41e9ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-a41e9ba.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a41e9ba)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-a41e9ba.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (00dbbcf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-00dbbcf.deb) is ready for download.
[macOS build 1.1.0 (00dbbcf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-00dbbcf.dmg) is ready for download.
[Windows x64 build 1.1.0 (00dbbcf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-00dbbcf.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (00dbbcf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-00dbbcf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b620f2f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b620f2f.deb) is ready for download.
[macOS build 1.1.0 (b620f2f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b620f2f.dmg) is ready for download.
[Windows x64 build 1.1.0 (b620f2f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b620f2f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b620f2f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b620f2f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (708a413)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-708a413.deb) is ready for download.
[macOS build 1.1.0 (708a413)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-708a413.dmg) is ready for download.
[Windows x64 build 1.1.0 (708a413)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-708a413.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (708a413)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-708a413.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (55d7b15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-55d7b15.deb) is ready for download.
[macOS build 1.1.0 (55d7b15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-55d7b15.dmg) is ready for download.
[Windows x64 build 1.1.0 (55d7b15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-55d7b15.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (55d7b15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-55d7b15.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9ec8ac6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9ec8ac6.deb) is ready for download.
[macOS build 1.1.0 (9ec8ac6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9ec8ac6.dmg) is ready for download.
[Windows x64 build 1.1.0 (9ec8ac6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9ec8ac6.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9ec8ac6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9ec8ac6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-41d7e51.deb) is ready for download.
[macOS build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-41d7e51.dmg) is ready for download.
[Windows x64 build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-41d7e51.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-41d7e51.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-41d7e51.deb) is ready for download.
[macOS build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-41d7e51.dmg) is ready for download.
[Windows x64 build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-41d7e51.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (41d7e51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-41d7e51.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (553a853)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-553a853.deb) is ready for download.
[macOS build 1.1.0 (553a853)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-553a853.dmg) is ready for download.
[Windows x64 build 1.1.0 (553a853)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-553a853.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (553a853)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-553a853.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fa35a25)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fa35a25.deb) is ready for download.
[macOS build 1.1.0 (fa35a25)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fa35a25.dmg) is ready for download.
[Windows x64 build 1.1.0 (fa35a25)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fa35a25.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fa35a25)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fa35a25.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9dfa84a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9dfa84a.deb) is ready for download.
[macOS build 1.1.0 (9dfa84a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9dfa84a.dmg) is ready for download.
[Windows x64 build 1.1.0 (9dfa84a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9dfa84a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9dfa84a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9dfa84a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (613c82b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-613c82b.deb) is ready for download.
[macOS build 1.1.0 (613c82b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-613c82b.dmg) is ready for download.
[Windows x64 build 1.1.0 (613c82b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-613c82b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (613c82b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-613c82b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b29e54d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b29e54d.deb) is ready for download.
[macOS build 1.1.0 (b29e54d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b29e54d.dmg) is ready for download.
[Windows x64 build 1.1.0 (b29e54d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b29e54d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b29e54d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b29e54d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (62941de)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-62941de.deb) is ready for download.
[macOS build 1.1.0 (62941de)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-62941de.dmg) is ready for download.
[Windows x64 build 1.1.0 (62941de)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-62941de.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (62941de)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-62941de.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b1de5a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b1de5a8.deb) is ready for download.
[macOS build 1.1.0 (b1de5a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b1de5a8.dmg) is ready for download.
[Windows x64 build 1.1.0 (b1de5a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b1de5a8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b1de5a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b1de5a8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9983b4e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9983b4e.deb) is ready for download.
[macOS build 1.1.0 (9983b4e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9983b4e.dmg) is ready for download.
[Windows x64 build 1.1.0 (9983b4e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9983b4e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9983b4e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9983b4e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1dfeff0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-1dfeff0.deb) is ready for download.
[macOS build 1.1.0 (1dfeff0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-1dfeff0.dmg) is ready for download.
[Windows x64 build 1.1.0 (1dfeff0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-1dfeff0.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1dfeff0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-1dfeff0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0fa1d85)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-0fa1d85.deb) is ready for download.
[macOS build 1.1.0 (0fa1d85)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-0fa1d85.dmg) is ready for download.
[Windows x64 build 1.1.0 (0fa1d85)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-0fa1d85.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0fa1d85)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-0fa1d85.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (73739c0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-73739c0.deb) is ready for download.
[macOS build 1.1.0 (73739c0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-73739c0.dmg) is ready for download.
[Windows x64 build 1.1.0 (73739c0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-73739c0.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (73739c0)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-73739c0.setup.exe) is ready for download.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5359)* status: 2 of 3 files reviewed, all discussions resolved

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5359)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (446fd2a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-446fd2a.deb) is ready for download.
[macOS build 1.1.0 (446fd2a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-446fd2a.dmg) is ready for download.
[Windows x64 build 1.1.0 (446fd2a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-446fd2a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (446fd2a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-446fd2a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (47feae7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-47feae7.deb) is ready for download.
[macOS build 1.1.0 (47feae7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-47feae7.dmg) is ready for download.
[Windows x64 build 1.1.0 (47feae7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-47feae7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (47feae7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-47feae7.setup.exe) is ready for download.

**Pull request merged**
