### PR TITLE
Now showing the total number of invalidated checks and alignments in the tool cards

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Now showing the total number of invalidated checks and alignments in the tool cards

#### Please include detailed Test instructions for your pull request:
- Load a fresh project with tW and make a selection in the verse edit component
- Then in the same check break the selection by editing the word you selected above.
- Go to the tools page on the home screen.
- And it should show one invalidated check in the tW card (if it was a fresh project otherwise it will show one more than it was before you made the invalidation)

- Now open the same project with wA tool
- try to align a verse that you can then edit to cause an alignment invalidation which in this case it will show one invalidated alignment on the wA tool card.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4395)

### CODE REVIEW

**Comment by RoyalSix** [comment]
I tried loading this project and got some errors 
[57-TIT.usfm 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1961842/57-TIT.usfm.2.zip)

Note: this project works on develop

**Comment by RoyalSix** [comment]
Reviewed 1 of 277 files at r1, 1 of 1 files at r2.
Review status: 2 of 277 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4395)*

**Comment by RoyalSix** [comment]
Reviewed 275 of 277 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4395)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`

**Comment by RoyalSix** [comment]
@mannycolon I just tried loading another project 
[bhadrawahi_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1965107/bhadrawahi_tit.zip)
And I got the following errors. 
screen shot 2018-05-01 at 1 27 40 pm
Sorry you have to keep going back haha
image

**Comment by RoyalSix** [comment]
This is also an example of why we need integration testing

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`

**Comment by richmahn** [comment]
Code Review: LGTM
Local test: LGTM

---

Reviewed 275 of 277 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4395#-:-LBXZ00X0qd0mgCrlzJn:b-m5xjqt)*

**Pull request merged**
