### PR TITLE
Default CSV Export Location

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR addresses issues in #1693 

#### How to test this pull request:
To test try exporting to different locations and see if it saves the last place.
The first attempt to save should also be in the Documents folder (Win & Mac)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1735)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/js/actions/CoreActionConsts.js, line 128 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km84hlPd6EElLBZ-RPB:-Km84hlPd6EElLBZ-RPC:b-psnfur) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/actions/CoreActionConsts.js#L128)):*
> ```JavaScript
>   SET_SWITCHING_TOOL_OR_PROJECT_TO_FALSE: "SET_SWITCHING_TOOL_OR_PROJECT_TO_FALSE",
>   SET_SWITCHING_TOOL_OR_PROJECT_TO_TRUE: "SET_SWITCHING_TOOL_OR_PROJECT_TO_TRUE",
>   CSV_SAVE_LOCATION: "CSV_SAVE_LOCATION"
> ```

can we come up with a more descriptive action constant?

---

*[src/js/actions/RecentProjectsActions.js, line 133 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85Qy5w3nbeoLaB_y0:-Km85Qy5w3nbeoLaB_y1:bbcns2s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/actions/RecentProjectsActions.js#L133)):*
> ```JavaScript
>  * @param {string} projectPath - Path to current project
>  */
> export function exportToCSV(projectPath, csvSaveLocation) {
> ```

maybe just get csvSaveLocation from getState().settingsReducer

---

*[src/js/containers/RecentProjectsContainer.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km84ttjiuMMtamXQUiM:-Km84ttjiuMMtamXQUiN:b-ml4q5k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L42)):*
> ```JavaScript
>         <button className="btn-second"
>           style={{width: "120px", margin: "10px 5px 10px 0"}}
>           onClick={()=> this.props.exportToCSV(projectPath, this.props.csvSaveLocation)}
> ```

could we get this from the state in the action creator function instead??

---

*[src/js/containers/RecentProjectsContainer.js, line 117 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km854dIHJVqxWIllstK:-Km854dJTcFfFNmySdr8:b-m9ck9u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L117)):*
> ```JavaScript
>     userdata: state.loginReducer.userdata,
>     modalReducer: state.newModalReducer,
>     csvSaveLocation: state.settingsReducer.csvSaveLocation
> ```

this should be 
settingsReducer:  state.settingsReducer

---

*[src/js/containers/RecentProjectsContainer.js, line 144 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85GooP8Me_DG0pS-o:-Km85GooP8Me_DG0pS-p:b-cv7xii) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L144)):*
> ```JavaScript
>       dispatch(recentProjectsActions.getProjectsFromFolder());
>     },
>     exportToCSV: (projectPath, defaultPath) => {
> ```

you don't need the second argument here since you can get it directly from the state using getStatet()

---

*[src/js/reducers/settingsReducer.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85dgPg7qeubpSZM3J:-Km85dgQDTDUn9g1Nv-F:bmvzci) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/reducers/settingsReducer.js#L8)):*
> ```JavaScript
>     textSelect: 'drag',
>     developerMode: false,
>     csvSaveLocation: null
> ```

why do we save this variable in settingsReducer? is it the appropriate reducer to save this variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by RoyalSix** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/reducers/settingsReducer.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85dgPg7qeubpSZM3J:-Km8BSlyBFuds4ZoOEtA:bokyxsm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/reducers/settingsReducer.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we save this variable in settingsReducer? is it the appropriate reducer to save this variable?
</blockquote></details>

The csv location setting is a user setting not a project level setting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by RoyalSix** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/CoreActionConsts.js, line 128 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km84hlPd6EElLBZ-RPB:-Km8BcwAEDjPwrSEbQJm:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/actions/CoreActionConsts.js#L128)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we come up with a more descriptive action constant?
</blockquote></details>

Done.

---

*[src/js/containers/RecentProjectsContainer.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km84ttjiuMMtamXQUiM:-Km8BduD6xgIx4-f4VJB:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we get this from the state in the action creator function instead??
</blockquote></details>

Done.

---

*[src/js/containers/RecentProjectsContainer.js, line 117 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km854dIHJVqxWIllstK:-Km8BeHuFe62uXrVUw9i:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L117)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should be 
settingsReducer:  state.settingsReducer


</blockquote></details>

Done.

---

*[src/js/containers/RecentProjectsContainer.js, line 144 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85GooP8Me_DG0pS-o:-Km8BezYgOAO8Vs27QMh:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/containers/RecentProjectsContainer.js#L144)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you don't need the second argument here since you can get it directly from the state using getStatet()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r2, 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/RecentProjectsActions.js, line 133 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-Km85Qy5w3nbeoLaB_y0:-Km8Cqn_KOX3x0VpZnx3:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b91a483cb449c4e0ec533c0453714419662cb403/src/js/actions/RecentProjectsActions.js#L133)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe just get csvSaveLocation from getState().settingsReducer
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-:-Km8CswDflC7mCSsdrld:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1735#-:-Km8D01MgFjdkK7-asYs:bg7igk9)*

**Pull request merged**
