### PR TITLE
Build off branches

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

Finishes #3203. This refactors the build process to generate builds when certain branches receive updates.

* `develop`
* `release-*`
* `sandbox-*`
* and all tags

#### How to test this pull request:

You can see an overview of builds at http://tc.unfoldingword.surge.sh. If you push up a branch following the above naming conventions the appropriate web page will be updated to reflect the successful build and distributables will be available for download.

I have personally tested the sandbox and release branches already. However, the only way to test the develop branch builds is to merge in this PR.
Likewise in order to test builds on tags we'll need to tag a new release.

For a complete description of the build process see the [New DSM dev team](https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#) document.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3298)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298#-L-3FEEPHt4zZ2hnUXsT:-L-3FEEPHt4zZ2hnUXsU:by3ornm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a4b70575a6cf36a0d6f3abe97d0deae1bd07ca5/src/main.js#L25)):*
> ```JavaScript
> 
>   if('developer_mode' in p && p.developer_mode) {
>     mainWindow.webContents.openDevTools();
> ```

We are putting this back? 
There was a story to remove this. Just making sure it was intentional.
https://github.com/unfoldingWord-dev/translationCore/issues/2172

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298)*

**Comment by da1nerd** [comment]
*[src/main.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298#-L-3FEEPHt4zZ2hnUXsT:-L-3GFrP9_bQ8XJvsNCW:bd73koi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a4b70575a6cf36a0d6f3abe97d0deae1bd07ca5/src/main.js#L25)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

We are putting this back? 
There was a story to remove this. Just making sure it was intentional.
https://github.com/unfoldingWord-dev/translationCore/issues/2172
</blockquote></details>

I added that in for development builds only. e.g. anything built on the develop or sandbox branches will display the developer tools. I did this to aid in debugging. However, anything built on a tag or release branch will not show the developer tools.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298#-L-3FEEPHt4zZ2hnUXsT:-L-3MK10I6P6TdCYr2xy:b-qamxr4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a4b70575a6cf36a0d6f3abe97d0deae1bd07ca5/src/main.js#L25)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

I added that in for development builds only. e.g. anything built on the develop or sandbox branches will display the developer tools. I did this to aid in debugging. However, anything built on a tag or release branch will not show the developer tools.
</blockquote></details>

Awesome. Nice work! :+1: :100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298)*

**Comment by RoyalSix** [comment]
I did a test on the sandbox builds with branch ```sandbox-bugfix/jay/2811 ```
Its the same branch as ```bugfix/jay/2811```
How long does the build take, and will I know that it passed if I see it up? 
@neutrinog

**Comment by da1nerd** [comment]
@RoyalSix right now the builds are taking around 10-20 minutes. :(
Part of that is setup for the windows builds and part of it is we're using the slower travis images with root access because we need to install system packages for the virtual windows environment.

**Comment by RoyalSix** [comment]
@neutrinog My push didn't create a build, is there some sort of log to check what happened? Or if the hook actually was triggered?

**Comment by da1nerd** [comment]
@RoyalSix here is the build log https://travis-ci.org/unfoldingWord-dev/translationCore/builds. None of the branches you've pushed have my build code. If you want to test the builds you'll need to pull down this branch and push it to whatever test branch you want.

e.g. 
```
git checkout -b sandbox-enhancement/joel/builds origin/sandbox-enhancement/joel/builds
git push origin sandbox-enhancement/joel/builds:sandbox-jay/test
```
where origin is pointing to https://github.com/unfoldingWord-dev/translationCore. If you have multiple remotes configured it may be named something else such as `upstream`

**Comment by klappy** [comment]
Reviewed 5 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298)*

**Comment by klappy** [comment]
Reviewed 4 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3298#-:-L-7apVFnO29qCNU7DMk:bnfp4nl)*

**Pull request merged**
