### PR TITLE
Js load fix

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/490)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/pages/app.js, line 564 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrLELUqI7AxL_QaUm:-KanrLENqhEPXmZvD-BK:b-ps08nu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L564)):*
> ```JavaScript
>           show: 'link',
>           submitLink: (callback) => {
>             debugger;
> ```

debugger

---

*[src/js/pages/app.js, line 594 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrMq62VtAKhxTEM4O:-KanrMq7ZA5-FL_yA3pU:b-ps08nu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L594)):*
> ```JavaScript
>           onClick: (type) => {
>             if (type == 'link') {
>               debugger;
> ```

debugger

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490)*

**Comment by ihoegen** [comment]
What does this PR do, in terms of fixing?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/pages/app.js, line 564 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrK_PInS0q-mI_4V0:-KanrK_PInS0q-mI_4V1:b-dmj7wz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L564)):*
> ```JavaScript
>           show: 'link',
>           submitLink: (callback) => {
>             debugger;
> ```

You should remove this debugger;

---

*[src/js/pages/app.js, line 594 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrN-O9cPx4ixLX9Fy:-KanrN-O9cPx4ixLX9Fz:b2nreh6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L594)):*
> ```JavaScript
>           onClick: (type) => {
>             if (type == 'link') {
>               debugger;
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-:-KanrS114ecdchW9SOvz:bwhtroy)*

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/pages/app.js, line 564 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrK_PInS0q-mI_4V0:-KansarbguKW72XAGG6T:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L564)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

You should remove this debugger;
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 564 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrLELUqI7AxL_QaUm:-Kansb6PDCqERyEdOZfi:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L564)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

debugger
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 594 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrMq62VtAKhxTEM4O:-Kansbc4dl1HRZVwu6tP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L594)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

debugger
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 594 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490#-KanrN-O9cPx4ixLX9Fy:-KansbtGncdRDVuJL15w:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08955d1f1fa05e127a61b5511a9a210b7510159f/src/js/pages/app.js#L594)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/490)*

**Pull request merged**
