### PR TITLE
Bring in USFM Support

### PR DESCRIPTION
**Pull request by ihoegen**
A number of changes are brought in by this commit.
They are as follows:
- Ability to export original, gateway, and target language to .usfm files
- Abiilty to open a USFM file as a project, and to perform checks on it.
- Reworking of workflow in upload to better support persistence.
- Added new node module usfm-parser to package.json
- Callback is not a function errors removed from AccessProject.js
- DragDrop now supports any type of file as chosen.
- MenuBar includes option to Export Project as USFM

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/64)

### CODE REVIEW

**Comment by klappy** [comment]
When we now import a USFM file to perform checks on it, what is the workflow? 
Where is the data stored as it is imported?
Do we alter the USFM files or just copy them into the project folder? 
@ihoegen

**Comment by mannycolon** [comment]
Reviewed 117 of 117 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/64)_

**Comment by mannycolon** [comment]
already review all the files and look good. Pending running and testing app in your branch.

**Comment by ihoegen** [comment]
@klappy When a usfm file is imported, a tc-manifest file is created in the same directory as it, and a checkdata folder is created for the check data. The usfm files are not altered, my node module parses it into json and then save it in memory.

**Comment by klappy** [comment]
@ihoegen, Since we are importing it, what do you think about creating a new folder inside of where we download projects so that we can make sure it's safe for git actions, pushes and pulls during sync?

**Comment by ihoegen** [comment]
@klappy So just copy the usfm file to that folder, and use that as a default save and open location? It seems like there's a couple of things that could go wrong with that process, but it would make it safe for git actions, as opposed to say their Downloads folder.

**Comment by ihoegen** [comment]
What @klappy recommended is done, so if you guys feel this is complete, we can accept the pull request.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/64)_

**Comment by mannycolon** [comment]
@ihoegen How can I test this new changes

**Comment by ihoegen** [comment]
@mannycolon Open any project, then export it as usfm from the top menu. Then open that usfm file from the load modal.

**Comment by EllDoubleYew** [comment]
Just tested this with several AVD usfm files and I get this error:

`/Users/lukewilson/Sites/translationCore/node_modules/usfm-parser/src/js/usfmToJson.js:16 Uncaught TypeError: Cannot read property '1' of null`

I set the book to Galatians and the reading direction to Right to Left.

[Heres a link to the usfm file I was testing with](https://api.unfoldingword.org/avd/txt/1/avd-ar/48-GAL.usfm)

Any idea what might be causing this bug?

**Comment by ihoegen** [comment]
@EllDoubleYew I don't know what would be causing that, I'll take a look at it. It looks like it's happening in the usfm-parser module

**Comment by ihoegen** [comment]
@EllDoubleYew Fixed it, just run `npm install` then it should be good to go.

**Comment by EllDoubleYew** [comment]
@ihoegen so after some further testing, reports do not correctly display the name of the book when you load it in from USFM, leading me to believe that it may not being put in the store properly when you select the book when loading a project. Rather than the book name I just get `-bookName-`

**Comment by ihoegen** [comment]
@EllDoubleYew It should display the book name now.

**Comment by EllDoubleYew** [comment]
I am still getting the `Uncaught TypeError: Cannot read property '1' of null` from usfmToJson.js when I try and load in [this project](https://api.unfoldingword.org/avd/txt/1/avd-ar/54-1TI.usfm) (1 Timothy, Right to Left). I also want to note that this was tested on a branch I merged with develop.

**Comment by EllDoubleYew** [comment]
@ihoegen its works! That's the last issue I had so I am going to merge.

**Pull request merged**
