### PR TITLE
Move Import Online Functionality To Modal w/Redux

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/572)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/reducers/loginReducer.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572#-KbVjjnWc1GLBgmkAsau:-KbVjjnWc1GLBgmkAsav:b-y7e64g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08810a62663fbb25ca5ae87e36f2b3fac8aa37fb/src/js/reducers/loginReducer.js#L5)):*
> ```JavaScript
> 
> const initialState = {
>   userdata: {
> ```

any reason why you removed this from here??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572)*

**Comment by mannycolon** [comment]
@RoyalSix so while I'm working on a project and want to switch between projects and click load locally and then click the load button it just stays there maybe it should redirect the user to the tools tab so that they can select the new tool??
what do you think ?

**Comment by RoyalSix** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/reducers/loginReducer.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572#-KbVjjnWc1GLBgmkAsau:-KbVt9rMK3wMLwwd8NFU:b-ci8uis) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08810a62663fbb25ca5ae87e36f2b3fac8aa37fb/src/js/reducers/loginReducer.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

any reason why you removed this from here??
</blockquote></details>


Yes, and no. I should have left username:null. I removed it because in an action I was checking for the object being initialized or not, which is different than if it has the value "" for every field which is how is was before 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/reducers/loginReducer.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572#-KbVjjnWc1GLBgmkAsau:-KbW-yji-sL4TMD-eurX:be4v5ch) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/08810a62663fbb25ca5ae87e36f2b3fac8aa37fb/src/js/reducers/loginReducer.js#L5)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes, and no. I should have left username:null. I removed it because in an action I was checking for the object being initialized or not, which is different than if it has the value "" for every field which is how is was before 
</blockquote></details>

ok now makes more sense. great job

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/572)*

**Pull request merged**
