### PR TITLE
The gl dropdown list for the wa tool now only includes  GLs w/ lexicons & auto selecting a GL if only one is found in the list

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- The gl dropdown list for the wa tool now only includes  GLs w/ lexicons & auto selecting a GL if only one is found in the list

#### Please include detailed Test instructions for your pull request:
- Select a project and in the wordAlignment Tool verify that only English or GL resources with lexicons show up on the list.
- Open an older project that was last used at least 3 days ago
- If there is only one GL available for a tool card,  then it should be auto-selected instead of displaying "Select Gateway Language"

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6342)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c9a8e08)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-linux-x64-2.0.0-c9a8e08.deb) is ready for download.
[macOS build 2.0.0 (c9a8e08)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-macos-x64-2.0.0-c9a8e08.dmg) is ready for download.
[Windows x64 build 2.0.0 (c9a8e08)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x64-2.0.0-c9a8e08.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c9a8e08)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x32-2.0.0-c9a8e08.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (2188d94)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-linux-x64-2.0.0-2188d94.deb) is ready for download.
[macOS build 2.0.0 (2188d94)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-macos-x64-2.0.0-2188d94.dmg) is ready for download.
[Windows x64 build 2.0.0 (2188d94)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x64-2.0.0-2188d94.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (2188d94)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x32-2.0.0-2188d94.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (af33395)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-linux-x64-2.0.0-af33395.deb) is ready for download.
[macOS build 2.0.0 (af33395)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-macos-x64-2.0.0-af33395.dmg) is ready for download.
[Windows x64 build 2.0.0 (af33395)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x64-2.0.0-af33395.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (af33395)](https://tc-builds.door43.org/build/feature-mannycolon-6297/translationCore-win-x32-2.0.0-af33395.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 29 of 29 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6342)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
