### PR TITLE
New Online Mode Workflow

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR takes the legacy offline mode away and introduces a default offline mode and a confirm dialog for accessing the internet.

#### How to test this pull request:
To test this PR try accessing things that require internet such as:
Importing, uploading, viewing licenses, logging in, submitting feedback, any urls not loaded locally in tHelps ...etc

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2116)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix fix merge conflicts

**Comment by mannycolon** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/OnlineModeActions.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohB_GcYf80gu85h5MV:-KohB_GcYf80gu85h5MW:b-1j8q0k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L25)):*
> ```JavaScript
> export function agreeCheckBox(checkBoxAction) {
>   return (
>     <Checkbox
> ```

shouldn't this be its own component?

---

*[src/js/actions/OnlineModeActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBf2N3qYob7M5wErE:-KohBf2N3qYob7M5wErF:b-y5pi24) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L38)):*
> ```JavaScript
> export function onlineModeWarning(checkBoxAction) {
>   return (
>     <MuiThemeProvider>
> ```

same here this should be its own component

---

*[src/js/actions/OnlineModeActions.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBsWXMOjnxmZDwwH8:-KohBsWXMOjnxmZDwwH9:b7z5w2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L58)):*
> ```JavaScript
>  * @param {function} dispatch - The dispatcher
>  */
> export function getATags(dispatch) {
> ```

this may slow down the app.

---

*[src/js/components/SideBar/StatusBar.js, line 84 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohC58fuqrjM7EPV9mR:-KohC58fuqrjM7EPV9mS:b-wozz6z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/components/SideBar/StatusBar.js#L84)):*
> ```JavaScript
>       child: {
>         width: 'auto',
>         float: 'left',
> ```

i think if you just remove float: right it should do the same as having float left?

---

*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-KohCMGhOnRLq23vs7sY:b-c85qre) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
> ```JavaScript
>     }
>     this.props.actions.getResourcesFromStaticPackage();
>     this.props.actions.getATags()
> ```

what does `getATags` mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/OnlineModeActions.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohB_GcYf80gu85h5MV:-Koh_TddSi3ERplgdF0v:b2nhswy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L25)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

shouldn't this be its own component?
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/OnlineModeActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBf2N3qYob7M5wErE:-Koh_VAvM8Ynh0LhN2Wi:b2nhswy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L38)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here this should be its own component
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/OnlineModeActions.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBsWXMOjnxmZDwwH8:-Koh_WGQXZDpeDYQkcKa:bx258gt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L58)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this may slow down the app.
</blockquote></details>

Well its a requirement, and I tested haven't seen even the smallest lag. Theres not going to be nesting of components more than the 100,000 range I think we can expect not to see performance issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-Koh_qAj2x10K-xaLTMd:bza2kzs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what does `getATags` mean?
</blockquote></details>

That function has a description where its declared

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/components/SideBar/StatusBar.js, line 84 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohC58fuqrjM7EPV9mR:-Kohc08wFwk17p-mTFlq:b-utowor) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/components/SideBar/StatusBar.js#L84)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i think if you just remove float: right it should do the same as having float left?
</blockquote></details>

I tried it. And it doesn't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/OnlineModeActions.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohB_GcYf80gu85h5MV:-KojDeRF5x23kgsjl911:b-z1a8ht) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L25)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

can we move this code to a component file?

---

*[src/js/actions/OnlineModeActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBf2N3qYob7M5wErE:-KojDku1vH25PMGTkfTC:b-c4ql58) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L38)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

move this code to a component

---

*[src/js/components/SideBar/StatusBar.js, line 84 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohC58fuqrjM7EPV9mR:-KojDnWMyJYomobbDxcF:b32wtd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/components/SideBar/StatusBar.js#L84)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I tried it. And it doesn't
</blockquote></details>

ok

---

*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-KojDqHZvdujgjU5bYeH:btyvxgl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

That function has a description where its declared
</blockquote></details>

but what does it even mean ?? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-KojDvVTwV3qTHFcBq3T:bv2aw2e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

but what does it even mean ?? 
</blockquote></details>

i think the function name should be a little more descriptive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-Kom3F57OavTtHnSWmVQ:b-3nqav5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i think the function name should be a little more descriptive
</blockquote></details>

I believe it is get <a> tags, I see how it can be misleading when out of context. Maybe, getAnchorTags or getHtmlLinks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-Kom3_OmRgjxZsy7qxrx:b-skide6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I believe it is get <a> tags, I see how it can be misleading when out of context. Maybe, getAnchorTags or getHtmlLinks.
</blockquote></details>

I typed "get <a> tags" but somehow the `<a>` got deleted when I submitted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-Kom3mJvZTtcYsTK-tvW:b-3643it) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I typed "get <a> tags" but somehow the `<a>` got deleted when I submitted.
</blockquote></details>

did it again, `<a>` must be rendering html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
*[src/js/actions/OnlineModeActions.js, line 58 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-Kom40uQ3kFNXR2VQBDn:-Kom40uQ3kFNXR2VQBDo:b-grg5lb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0cdd4d31b262c3c079e4c922a2be6228794996a3/src/js/actions/OnlineModeActions.js#L58)):*
> ```JavaScript
>  * @param {function} dispatch - The dispatcher
>  */
> export function getATags(dispatch) {
> ```

Per @mannycolon's  suggestion, this should be getAnchorTags or getHtmlLinks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: 10 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/OnlineModeActions.js, line 25 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohB_GcYf80gu85h5MV:-KomWZckzD1LCPUVUd_5:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L25)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we move this code to a component file?
</blockquote></details>

Done.

---

*[src/js/actions/OnlineModeActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohBf2N3qYob7M5wErE:-KomW_9bu6zvMIYlQl15:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/actions/OnlineModeActions.js#L38)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

move this code to a component
</blockquote></details>

Done.

---

*[src/js/actions/OnlineModeActions.js, line 58 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-Kom40uQ3kFNXR2VQBDn:-KomWWbnSdAKfFrE-MnN:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0cdd4d31b262c3c079e4c922a2be6228794996a3/src/js/actions/OnlineModeActions.js#L58)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Per @mannycolon's  suggestion, this should be getAnchorTags or getHtmlLinks.
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 34 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KohCMGhOnRLq23vs7sX:-KomWYGO9-x2Es-cz9-R:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aa89dd4d18a94b6733d1b8452b8f593ed1e12ce7/src/js/pages/app.js#L34)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

did it again, `<a>` must be rendering html.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/components/dialogComponents/OnlineDialog.js, line 5 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KomrXukIERh3Q_pHXIy:-KomrXukIERh3Q_pHXIz:b-ul7oqm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9b887b2bbbf384edf7f30823966835953f5fec8f/src/js/components/dialogComponents/OnlineDialog.js#L5)):*
> ```JavaScript
> import { Checkbox } from 'material-ui';
> 
> const OnlineDialog = (checkBoxAction) => {
> ```

Good job!

---

*[src/js/utils/loadMethods.js, line 22 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KomrlCxBJhSU60-1Fz6:-KomrlCxBJhSU60-1Fz7:bh2isbx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9b887b2bbbf384edf7f30823966835953f5fec8f/src/js/utils/loadMethods.js#L22)):*
> ```JavaScript
>       if (!settings.toolsSettings) settings.toolsSettings = {};
>       settings.onlineMode = false;
>       //this is a temporary fix until there is a better workflow for persisting online/offline mode.
> ```

you can do this in the InitialState object of the settings reducer instead of here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by RoyalSix** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/dialogComponents/OnlineDialog.js, line 5 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KomrXukIERh3Q_pHXIy:-KomvP36CjK4zguK_PZN:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9b887b2bbbf384edf7f30823966835953f5fec8f/src/js/components/dialogComponents/OnlineDialog.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Good job!
</blockquote></details>

Done.

---

*[src/js/utils/loadMethods.js, line 22 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116#-KomrlCxBJhSU60-1Fz6:-KomvSNfkRHuxTIJa1j5:b-voij07) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9b887b2bbbf384edf7f30823966835953f5fec8f/src/js/utils/loadMethods.js#L22)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you can do this in the InitialState object of the settings reducer instead of here
</blockquote></details>

I can't because this overwrites the initial settings of the app. And we still want it to overwrite the other properties such as tools settings, csv save location etc...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r4.
Review status: 12 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r4.
Review status: 13 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r4.
Review status: 14 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3, 4 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by mannycolon** [comment]
@RoyalSix fix merge conflicts

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2116)*

**Pull request merged**
