### PR TITLE
Copyright Check

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Adds copy right check (Front end and Back end)
- Removes params reference from the codebase.

#### How to test this pull request:
- Load a project that has no LICENSE.MD file. (Copyright Check  should open in the stepper)
- Load a project that doesn't have the `license` property in the manifest. json file. (Copyright Check  should open in the stepper)
- Load a project that has both the  LICENSE.MD file and has the `license` property in the manifest. json file. (Copyright Check  should not open in the stepper)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2412)

### CODE REVIEW

**Comment by klappy** [comment]
I see that you marked this as TODO, so I'm wondering if its ready to review yet?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-:-KrHdNi9hdKFPuDwX8qE:bieadm5)*

**Comment by mannycolon** [comment]
@klappy this is pending jays PR being merged first.

**Comment by klappy** [comment]
Do we want to move the license md files to the static folder since they aren't code?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-:-KrqZlalWzyhYuJlBk14:bp06qo3)*

**Comment by klappy** [comment]
They work in the Assets folder, so no either works.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-:-Krq_EAt6dXhykWFi_yh:bfzdm2j)*

**Comment by klappy** [comment]
Reviewed 16 of 46 files at r8, 1 of 1 files at r10.
Review status: 17 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 29 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-Krqb1yxDnWmsth3zTuX:-Krqb1yxDnWmsth3zTuY:b-aza9fz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/reducers/projectDetailsReducer.js#L29)):*
> ```JavaScript
>         }
>       };
>     case consts.ADD_MANIFEST_PROPERTY:
> ```

Ah!!!! This is so nice. Sure beats the arbitrary adding of attributes spread throughout our the base.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by klappy** [comment]
*[src/js/utils/localStorage.js, line 51 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-KrqbqDdpx75yjudED-v:-KrqbqDdpx75yjudED-w:b-fao08d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/utils/localStorage.js#L51)):*
> ```JavaScript
>     saveLocalUserdata(newState);
>     // save manifest only if it is defined.
>     if (newState.projectDetailsReducer.manifest && Object.keys(newState.projectDetailsReducer.manifest).length > 0) {
> ```

Do we have any use cases where this will be a partial manifest and accidentally overwrite a good one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by klappy** [comment]
*[tC_apps/VerseCheck, line 1 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-Krqc5S7W8rifRzU-RFd:-Krqc5S7W8rifRzU-RFe:b-w8idml) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/619de2040ab0846088404b0e423cac89c91bce5c/tC_apps/VerseCheck#L1)):*
> ```
> Subproject commit cb0d97aef8770b24b7447b5d707da489235b4b25
> ```

Do we need this commit here or was it accidental?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by klappy** [comment]
*[src/js/actions/ProjectInformationCheckActions.js, line 11 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-KrqcF2957c3W2mvQ9U4:-KrqcF2957c3W2mvQ9U5:b-96vslo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/actions/ProjectInformationCheckActions.js#L11)):*
> ```JavaScript
> export function validate() {
>   return ((dispatch) => {
>     // dispatch({
> ```

Just checking to see why these are commented out. I'm not following how it will work without them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by mannycolon** [comment]
Reviewed 5 of 46 files at r8.
Review status: 20 of 42 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectInformationCheckActions.js, line 11 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-KrqcF2957c3W2mvQ9U4:-KrqdnBQdKylyWSfRWAa:b-bsle95) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/actions/ProjectInformationCheckActions.js#L11)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Just checking to see why these are commented out. I'm not following how it will work without them?
</blockquote></details>

this belongs to another story / PR

---

*[src/js/reducers/projectDetailsReducer.js, line 29 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-Krqb1yxDnWmsth3zTuX:-KrqdtLc1DVEgKjjcDdP:b2ni78k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/reducers/projectDetailsReducer.js#L29)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Ah!!!! This is so nice. Sure beats the arbitrary adding of attributes spread throughout our the base.
</blockquote></details>

lol

---

*[src/js/utils/localStorage.js, line 51 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-KrqbqDdpx75yjudED-v:-Krqe-Yw9kOcSNozs5xc:b-tw9t9y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/utils/localStorage.js#L51)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we have any use cases where this will be a partial manifest and accidentally overwrite a good one?
</blockquote></details>

I can't think of one

---

*[tC_apps/VerseCheck, line 1 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-Krqc5S7W8rifRzU-RFd:-Krqe6vLJdTp7nrfj9RQ:bquhij5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/619de2040ab0846088404b0e423cac89c91bce5c/tC_apps/VerseCheck#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this commit here or was it accidental?
</blockquote></details>

yes we need it here 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by mannycolon** [comment]
@klappy this PR should go along with https://github.com/translationCoreApps/VerseCheck/pull/63#issuecomment-323431319

**Comment by klappy** [comment]
Reviewed 27 of 46 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by RoyalSix** [comment]
Reviewed 21 of 38 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectInformationCheckActions.js, line 11 at r10](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-KrqcF2957c3W2mvQ9U4:-KrqkEVSo4XcvKOiR_BB:buyl1v3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89fa0718659534534e26a328bace6d01160f8244/src/js/actions/ProjectInformationCheckActions.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this belongs to another story / PR
</blockquote></details>

That's the project information check @klappy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412#-:-Krqu5wJ8m7RlbRvbpni:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r11.
Review status: 42 of 43 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2412)*

**Pull request merged**
