### PR TITLE
Alignment Data Errors

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR addresses resetting invalidated alignments.
  - Invalid alignments can be caused by changes to the target language verse text (which have been aligned), or to the greek source text (which has been aligned).
  - Check the [story](https://github.com/unfoldingWord-dev/translationCore/issues/3193) for a more detailed description.

#### Please include detailed Test instructions for your pull request:
- First make sure you are on the latests tC_resources, node modules, and tC_apps.
- Open a project with or without alignments.
- Do some alignments (remember the verse!)
- Open the tW tool, edit that same verse in the target language. Save.
- Open the word alignment tool, the alignments should now be reset.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3906)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/VerseObjectActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L68vapZhfWGwPona2FD:-L68vapZhfWGwPona2FE:bng3luh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5cbc0d344a9ff422caceef575a5e04b83c908dbc/src/js/actions/VerseObjectActions.js#L38)):*
> ```JavaScript
> };
> 
> const addContentAttributeToChildren = (childrens, parentObject, grandParentContent) => {
> ```

Because you delete this file and did not copy the latest version of this file some of the code I added is getting lost if this PR is merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by mannycolon** [comment]
Code Looks good

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/VerseObjectActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L68vapZhfWGwPona2FD:-L694QpXHhVc0t8sP9Dx:b330bbl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5cbc0d344a9ff422caceef575a5e04b83c908dbc/src/js/actions/VerseObjectActions.js#L38)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Because you delete this file and did not copy the latest version of this file some of the code I added is getting lost if this PR is merged.
</blockquote></details>

Ok nice catch. Will fix!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/WordAlignmentHelpers.test.js, line 231 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6Hs51w6c8HTGVLaoSS:-L6Hs51w6c8HTGVLaoST:b-rbkhjs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/WordAlignmentHelpers.test.js#L231)):*
> ```JavaScript
> 
>     const usfm = await WordAlignmentHelpers.convertAlignmentDataToUSFM(wordAlignmentDataPath, targetLanguageDataPath, chapterFiles, targetLanguageDataPath);
>     const foundMatch = usfm.includes('\\zaln-s | x-strong="G25960" x-lemma="κατά" x-morph="Gr,P,,,,,A,,," x-occurrence="1" x-occurrences="1" x-content="κατ"');
> ```

Out of curiosity, what changed to remove this accent in the text? `κατ’` should be preserved from the original language word object and not be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsS9H7cHlCA-vOhhr:-L6HsS9H7cHlCA-vOhhs:b-rbkhjs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L2)):*
> ```JSON
> {
>   "alignedVerseString": "Παῦλος δοῦλος Θεοῦ ἀπόστολος δὲ Ἰησοῦ Χριστοῦ κατὰ πίστιν ἐκλεκτῶν Θεοῦ καὶ ἐπίγνωσιν ἀληθείας τῆς κατ εὐσέβειαν",
> ```

Out of curiosity, what changed to remove this accent in the text? `κατ’` should be preserved from the original language word object and not be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 387 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsUuamUFxR06LE6mF:-L6HsUubM87sD8gZPPPB:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L387)):*
> ```JSON
>       "tag": "zaln",
>       "type": "milestone",
>       "content": "κατ",
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 768 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsYKUzOtlz74IUjHM:-L6HsYKUzOtlz74IUjHN:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L768)):*
> ```JSON
>       "topWords": [
>         {
>           "word": "κατ",
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsS9H7cHlCA-vOhhr:-L6Hs_UqpCqHnQtb1C13:bv60kur) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L2)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Out of curiosity, what changed to remove this accent in the text? `κατ’` should be preserved from the original language word object and not be removed.
</blockquote></details>

We need to know if we can preserve that from the original language or not. If we can't we may have to spend some extra time rethinking the approach or discussing implications with Ben/Jesse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/VerseObjectActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L68vapZhfWGwPona2FD:-L6IofxKNZaXkqujYtlf:b-7lnfj3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5cbc0d344a9ff422caceef575a5e04b83c908dbc/src/js/actions/VerseObjectActions.js#L38)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ok nice catch. Will fix!
</blockquote></details>

ok np

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by RoyalSix** [comment]
@klappy One of the parsers was classifying that accent as punctuation, therefore causing the alignments to be rendered invalid even though it was actually the same word without the accent

**Comment by klappy** [comment]
*[__tests__/WordAlignmentHelpers.test.js, line 231 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6Hs51w6c8HTGVLaoSS:-L6JIXXsCe5g3R6bP3gH:b-o74l1s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/WordAlignmentHelpers.test.js#L231)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Out of curiosity, what changed to remove this accent in the text? `κατ’` should be preserved from the original language word object and not be removed.
</blockquote></details>

@jag3773: Can you confirm that the above is an accent and not punctuation? If it is an accent, and it is using the same punctuation character as a single quote, we will need to research and find out how to encode this differently in the UGNT if possible and differentiate it from a single quote character. There isn't a clear programmatic approach at differentiating this use case from other standard single quotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by jag3773** [comment]
*[__tests__/WordAlignmentHelpers.test.js, line 231 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6Hs51w6c8HTGVLaoSS:-L6M_gMphb_cwZ_SDnQk:b-xvqwpi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/WordAlignmentHelpers.test.js#L231)):*
> κατ’

@klappy The apostrophe is marking a contraction.  The full form of the word is κατά but in certain cases the final ά is contracted, so we are left with κατ and the apostrophe marks the contraction.

The bigger issue is with how the tokenizer is treating apostrophes.  Currently they cause a word split, which is a breaking change in many languages.  I would prefer if apostrophes do not cause a word split.  In the current case, the ’ needs to stay with the term or the highlighting/alignment data is not complete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/WordAlignmentHelpers.test.js, line 231 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6Hs51w6c8HTGVLaoSS:-L6MeMAIXw8mp2-FaOL6:b-ysuly0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/WordAlignmentHelpers.test.js#L231)):*
<details><summary><i>Previously, jag3773 (Jesse Griffin) wrote…</i></summary><blockquote>

> κατ’

@klappy The apostrophe is marking a contraction.  The full form of the word is κατά but in certain cases the final ά is contracted, so we are left with κατ and the apostrophe marks the contraction.

The bigger issue is with how the tokenizer is treating apostrophes.  Currently they cause a word split, which is a breaking change in many languages.  I would prefer if apostrophes do not cause a word split.  In the current case, the ’ needs to stay with the term or the highlighting/alignment data is not complete.
</blockquote></details>

Causing a word split wouldn't fix this as there is no word split here. It is the last character. It can be associated with our word splitting issue like, `God's` being turned into `God` and `s`. We may have to just treat this as a separate issue from this story as it is related but cannot be cleanly solved here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/WordAlignmentHelpers.test.js, line 231 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6Hs51w6c8HTGVLaoSS:-L6MgjrlgVk-3wi4x7R-:b-it50ra) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/WordAlignmentHelpers.test.js#L231)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Causing a word split wouldn't fix this as there is no word split here. It is the last character. It can be associated with our word splitting issue like, `God's` being turned into `God` and `s`. We may have to just treat this as a separate issue from this story as it is related but cannot be cleanly solved here.
</blockquote></details>

OK, Let's just merge this and create a new issue. This PR does not cause the problem, it just exposes a pre-existing one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsS9H7cHlCA-vOhhr:-L6JIOA2GFspS0Gm_yUH:b-it50ra) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L2)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We need to know if we can preserve that from the original language or not. If we can't we may have to spend some extra time rethinking the approach or discussing implications with Ben/Jesse.
</blockquote></details>

OK, Let's just merge this and create a new issue. This PR does not cause the problem, it just exposes a pre-existing one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 387 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsUuamUFxR06LE6mF:-L6Mgw9zBIYfiLtOGCF9:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L387)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 768 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsYKUzOtlz74IUjHM:-L6MgxdPZ6ttZ9_o_azT:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L768)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
OK, Let's just merge this and create a new issue. This PR does not cause the problem, it just exposes a pre-existing one.

@mannycolon Can you merge this? I'm suppose to be off today but spent a few hours digging to see if we could solve this one in this PR or if it truly was a pre-existing issue to ensure we address but not here.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-:-L6MhAkx8lvHL-enFO8z:b-qc43zk)*

**Comment by klappy** [comment]
@mannycolon Forget that. I think I realized an approach that should work. 
Before we merge it we need to try it to preserve the apostrophe in the original text.

@RoyalSix: The loss comes in attempting to convert the ugnt verseObjects or Alignment to a string and then back to verseObjects. There is no need for doing so. We need to compare the list of objects instead of converting to strings for the UGNT. There is no representation of the text as string in our system because it would cause loss. The loss of information, in this case the apostrophe belonging to the word not it's own, should maintain it's placement if the objects are compared. Comparing the objects whether VO or WO have the same important attributes of text/word and occurrence(s) that can be compared.

**Comment by RoyalSix** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsS9H7cHlCA-vOhhr:-L6ShnY67bBwTjvAa_ud:bscvud5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L2)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

OK, Let's just merge this and create a new issue. This PR does not cause the problem, it just exposes a pre-existing one.
</blockquote></details>

I commented out that test for now. I tried many different implementations to get that test to work but nothing yet. I think making a separate issue is good for now.

---

*[src/js/actions/VerseObjectActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L68vapZhfWGwPona2FD:-L6Sj4StusT3lAscetLu:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5cbc0d344a9ff422caceef575a5e04b83c908dbc/src/js/actions/VerseObjectActions.js#L38)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ok np
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by RoyalSix** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6SkO9l1F8ArXKh_4gJ:-L6SkO9l1F8ArXKh_4gK:b335kn7) (no related file):*
I guess the problem I'm facing here is the data for the tests comes like this: `alignedVerseString`, `alignments`, and a `wordBank`.
The input data for the actual methods being tested is `ugntVerseObjects`, `alignments`, and the `wordBank`. 
So im trying to use the aligned string and create verse objects just for the tests (this scenario would not happen in production because the format is already as expected). In the current implementation of the `test generator` function the `alignedVerseString` gets tokenized and separates the accent mark.
I think I will have to dumb down the test generator for now and have missing fields until we can solve the other problem at a higher level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by RoyalSix** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6SkO9l1F8ArXKh_4gJ:-L6SvuSaeYdx4V-Isvl5:b-d99cw5) (no related file):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I guess the problem I'm facing here is the data for the tests comes like this: `alignedVerseString`, `alignments`, and a `wordBank`.
The input data for the actual methods being tested is `ugntVerseObjects`, `alignments`, and the `wordBank`. 
So im trying to use the aligned string and create verse objects just for the tests (this scenario would not happen in production because the format is already as expected). In the current implementation of the `test generator` function the `alignedVerseString` gets tokenized and separates the accent mark.
I think I will have to dumb down the test generator for now and have missing fields until we can solve the other problem at a higher level.
</blockquote></details>

@klappy I think I made an implementation to fit your suggestion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by RoyalSix** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 387 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsUuamUFxR06LE6mF:-L6UMgi8Ku9CaV-Bqvzn:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L387)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---

*[__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json, line 768 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6HsYKUzOtlz74IUjHM:-L6UMhCjYqFqndQ-81tc:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/529e8a2a6c87fa0f9f4850740c2c2175343640fc/__tests__/fixtures/pivotAlignmentVerseObjects/tit1-1.json#L768)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 13 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - unit tests failing

**Comment by PhotoNomad0** [comment]
Still having problems with that it wants to reset many of the alignments of my aligned EN ULB project (see https://github.com/unfoldingWord-dev/translationCore/pull/3894).  It does give a prompt now, but no way to decline. So much work is loss.  I thought we decided to prompt and be able to decline alignment reset? @cckozie @benjore

**Comment by PhotoNomad0** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/WordAlignmentLoadActions.js, line 60 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3906#-L6asjymELQhf4Yk8veU:-L6asjymELQhf4Yk8veV:b3i3eln) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1f371171881ffa08b29224c847d88f801983bbb0/src/js/actions/WordAlignmentLoadActions.js#L60)):*
> ```JavaScript
>           </div>
>         ));
>         chapterData[verse] = WordAlignmentHelpers.resetWordAlignmentsForVerse(ugntVerse, targetLanguageVerse);
> ```

Don't we want to give the option to cancel before reseting?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - Adding notes from Slack

> Chris Kosieracki [18 minutes ago]
> I believe that is what was decided... warning that alignments for the verse will be reset without option to cancel. @ben_jore Do you agree?
> 
> Bruce McLean [17 minutes ago]
> What we have now is that alignments are reset and then the user is alerted.
> 
> Ben Jore [16 minutes ago]
> That is correct.
> 
> Ben Jore [16 minutes ago]
> We already have similar functionality in the tW tool when a selection is edited.
> 
> Chris Kosieracki [14 minutes ago]
> The message text should indicate that the alignments have been reset rather than will be.

If we just make the change to reset after the user hits OK, then I think this is good to go after merge conflict resolved.

**Comment by PhotoNomad0** [comment]
> If we just make the change to reset after the user hits OK, then I think this is good to go after merge conflict resolved.

This still hasn't been corrected.

**Comment by PhotoNomad0** [comment]
Looks like Travis is failing to generate jsdocs.  Error is here:

Parsing /home/travis/build/unfoldingWord-dev/translationCore/src/js/helpers/WordAlignmentHelpers.js ...
ERROR: Unable to parse a tag's type expression for source file /home/travis/build/unfoldingWord-dev/translationCore/src/js/helpers/WordAlignmentHelpers.js in line 324 with tag title "type" and text "{Object[{topWords, bottomWords}]}": Invalid type expression "Object[{topWords, bottomWords}]": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "\u200C", "\u200D", "_", "|", "~", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9] or end of input but "[" found.

**Comment by PhotoNomad0** [comment]
I think alignments is an array here anyway.  And there is a typo in the jsdocs above, variable name is misspelled.  Should be 'alignments', and should be described as array of alignment objects.

**Comment by RoyalSix** [comment]
@PhotoNomad0 I updated the documentation.

**Comment by RoyalSix** [comment]
@PhotoNomad0 Now resetting the alignments after the dialog has been closed

**Comment by PhotoNomad0** [comment]
@RoyalSix - confused here.  Did you push up your changes?  I don't see commits here after my comments and don't see any difference in the app.

**Comment by RoyalSix** [comment]
Yes forgot to push sorry.

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r2.
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3.
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by klappy** [comment]
*[src/js/actions/WordAlignmentLoadActions.js, line 60 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906#-L6asjymELQhf4Yk8veU:-L6rRVlgzZtTdN_HFBYb:b9mu1do) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1f371171881ffa08b29224c847d88f801983bbb0/src/js/actions/WordAlignmentLoadActions.js#L60)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Don't we want to give the option to cancel before reseting?
</blockquote></details>

If I remember correctly, Koz and Ben didn't want an option for cancel. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by PhotoNomad0** [comment]
jsdocs are still failing in Travis but without additional info.  Think you are going to have to remove this line:

  /** @type [{topWords, bottomWords}] */

**Comment by PhotoNomad0** [comment]
Will need to merge with latest develop to test, Rich has made changes to resource versions.

**Comment by PhotoNomad0** [comment]
Will probably need to merge latest develop to test with latest resources Rich generated.

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r8.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3906)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - looks like the prompt is fixed, it doesn't reset the alignment before OK.  But the text probably should read that we are going to reset the alignment rather than we have reset the alignment.

**Pull request merged**
