### PR TITLE
Added info icon to "no selection needed" checkbox & made expanded scripture pane and verse editor dialogs draggable

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added info icon to "no selection needed" checkbox
- Made expanded scripture pane and verse editor dialogs draggable

#### Please include detailed Test instructions for your pull request:
1. Open tn or tw tool and open the verse check component in the selection mode. (The info icon should be on the right hand side of the "no selection needed" checkbox. Hovering over it should open the tooltip)
1. Open the expanded scripture pane and click & drag the blue title bar (It should be draggable now)
1. Now click the pencil to edit a verse and the verse edit dialog will open. Repeat step 2. (It should be draggable as well)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6156)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4ecad6a)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-linux-x64-1.2.0-4ecad6a.deb) is ready for download.
[macOS build 1.2.0 (4ecad6a)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-macos-x64-1.2.0-4ecad6a.dmg) is ready for download.
[Windows x64 build 1.2.0 (4ecad6a)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-win-x64-1.2.0-4ecad6a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4ecad6a)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-win-x32-1.2.0-4ecad6a.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6156)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
LGTM - code review and test. I like the draggable dialogs!

@mannycolon - Still need to reserve merge conflicts in packages.

**Comment by mannycolon** [comment]
@PhotoNomad0  Done

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (6c9cc3f)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-linux-x64-1.2.0-6c9cc3f.deb) is ready for download.
[macOS build 1.2.0 (6c9cc3f)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-macos-x64-1.2.0-6c9cc3f.dmg) is ready for download.
[Windows x64 build 1.2.0 (6c9cc3f)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-win-x64-1.2.0-6c9cc3f.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (6c9cc3f)](https://tc-builds.door43.org/build/feature-mannycolon-5868/translationCore-win-x32-1.2.0-6c9cc3f.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Verified on b50f3ec

**Pull request merged**
