### PR TITLE
Now loading bibles base on a new data structure that uses languageIds to organize bibles

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Now loading bibles base on a new data structure that uses **languageIds** to organize bibles
- **Dependencies:**
   - https://github.com/translationCoreApps/VerseCheck/pull/91
   - https://github.com/translationCoreApps/translationWords/pull/113
   - https://github.com/translationCoreApps/ScripturePane/pull/97
   - https://github.com/translationCoreApps/wordAlignment/pull/25
   - https://github.com/translationCoreApps/ScripturePane/pull/99

Command to pull all branches
`runGitCommands() { git checkout feature-mannycolon-3549 && git pull; }; runGitCommands; cd tC_apps/ScripturePane; runGitCommands; cd ../VerseCheck; runGitCommands; cd ../translationWords; runGitCommands; cd ../wordAlignment;  cd ../../;`
#### Please include detailed Test instructions for your pull request:
- Load a project selecting English as the GL:
   - The project should load fine.
   - You should be able to load both **English ULB** and **Hindi ULB**
 - Load a project selecting Hindi as the GL:
   - The project should load fine.
  - **Hindi ULB** should be currently displayed in the scripture pane.
   - You should be able to load both **English ULB** and **Hindi ULB**
- Try editing the verse in the verse check change check and comeback and make sure that your edit worked.
- Other parts where we display Bible text should render without any problems.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3967)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 10 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3967)*

**Comment by PhotoNomad0** [comment]
screen shot 2018-03-05 at 9 30 10 am

seeing errors when opening projects.  Double checked that I had all the dependencies

**Comment by RoyalSix** [comment]
@mannycolon merge conflicts

**Comment by mannycolon** [comment]
> @mannycolon merge conflicts

@RoyalSix Should be good now

**Comment by richmahn** [comment]
Unable to go into wA and tW tools now. Getting many errors in the console:
```
C:\web\translationCore\node_modules\fbjs\lib\warning.js:33 Warning: Failed prop type: The prop `languageId` is marked as required in `Pane`, but its value is `undefined`.
    in Pane (created by View)
    in View (created by ScripturePane)
    in MuiThemeProvider (created by ScripturePane)
    in ScripturePane (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container (created by DragDropContext(Container))
    in DragDropContext(Container) (created by Tool)
    in Provider (created by Tool)
    in Tool (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
printWarning @ C:\web\translationCore\node_modules\fbjs\lib\warning.js:33
C:\web\translationCore\tC_apps\ScripturePane\src\components\Pane.js:61 Uncaught TypeError: Cannot read property 'undefined' of undefined
    at Pane.render (C:/web/translationCore/tC_apps/ScripturePane/src/components/Pane.js:17:19)
    at finishClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873:31)
    at updateClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850:12)
    at beginWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225:16)
    at performUnitOfWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224:16)
    at workLoop (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581:16)
    at invokeGuardedCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438:27)
    at renderRoot (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366:7)
C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:9747 The above error occurred in the <Pane> component:
    in Pane (created by View)
    in div (created by View)
    in div (created by View)
    in div (created by View)
    in View (created by ScripturePane)
    in MuiThemeProvider (created by ScripturePane)
    in ScripturePane (created by Container)
    in div (created by Container)
    in div (created by Container)
    in Container (created by DragDropContext(Container))
    in DragDropContext(Container) (created by Tool)
    in Provider (created by Tool)
    in Tool (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, Tool.
```

**Comment by RoyalSix** [comment]
Getting the same error as @PhotoNomad0 on first load of tW
screen shot 2018-03-05 at 2 55 32 pm

**Comment by richmahn** [comment]
@RoyalSix Did you remove your settings.json file and reload the app?

**Comment by RoyalSix** [comment]
Why should I have to do that?
We can't expect the users to do that @richmahn

**Comment by mannycolon** [comment]
> Why should I have to do that?
We can't expect the users to do that @richmahn

@RoyalSix if you opened my branch with my previous implementation that had a bug that would mess up with the new fixed implementation. something users would not encounter because they never opened tC with my previous bug.

**Comment by mannycolon** [comment]
@PhotoNomad0 @RoyalSix @richmahn everything should be good to go now except.

Note: Now there is a new branch to pull to test this PR. **(In wordAlignment tool)**

**Comment by richmahn** [comment]
Getting these errors now:```
C:\web\translationCore\node_modules\fbjs\lib\warning.js:33 Warning: Failed prop type: The prop `languageId` is marked as required in `Pane`, but its value is `undefined`.
    in Pane (created by View)
    in View (created by ScripturePane)
    in MuiThemeProvider (created by ScripturePane)
    in ScripturePane
    in div
    in div
    in View
    in Container (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
printWarning @ C:\web\translationCore\node_modules\fbjs\lib\warning.js:33
warning @ C:\web\translationCore\node_modules\fbjs\lib\warning.js:57
checkPropTypes @ C:\web\translationCore\node_modules\prop-types\checkPropTypes.js:52
validatePropTypes @ C:\web\translationCore\node_modules\react\cjs\react.development.js:1171
createElementWithValidation @ C:\web\translationCore\node_modules\react\cjs\react.development.js:1268
(anonymous) @ View.js:27
render @ View.js:25
finishClassComponent @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873
updateClassComponent @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850
beginWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225
performUnitOfWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224
workLoop @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288
callCallback @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542
invokeGuardedCallbackDev @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581
invokeGuardedCallback @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438
renderRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366
performWorkOnRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:11014
performWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10967
requestWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10878
scheduleWorkImpl @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10732
scheduleWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10689
enqueueSetState @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:6212
Component.setState @ C:\web\translationCore\node_modules\react\cjs\react.development.js:237
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:222
notify @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:30
notifyNestedSubs @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:69
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:219
dispatch @ C:\web\translationCore\node_modules\redux\lib\createStore.js:186
(anonymous) @ C:\web\translationCore\node_modules\redux-promise\lib\index.js:21
(anonymous) @ C:\web\translationCore\node_modules\redux-thunk\lib\index.js:14
dispatch @ C:\web\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectDataLoadingActions.js:44
Pane.js:17 Uncaught TypeError: Cannot read property '#<Object>' of undefined
    at Pane.render (C:/web/translationCore/tC_apps/ScripturePane/src/components/Pane.js:17:19)
    at finishClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873:31)
    at updateClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850:12)
    at beginWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225:16)
    at performUnitOfWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224:16)
    at workLoop (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581:16)
    at invokeGuardedCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438:27)
    at renderRoot (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366:7)
render @ Pane.js:17
finishClassComponent @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873
updateClassComponent @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850
beginWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225
performUnitOfWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224
workLoop @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288
callCallback @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542
invokeGuardedCallbackDev @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581
invokeGuardedCallback @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438
renderRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366
performWorkOnRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:11014
performWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10967
requestWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10878
scheduleWorkImpl @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10732
scheduleWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10689
enqueueSetState @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:6212
Component.setState @ C:\web\translationCore\node_modules\react\cjs\react.development.js:237
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:222
notify @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:30
notifyNestedSubs @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:69
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:219
dispatch @ C:\web\translationCore\node_modules\redux\lib\createStore.js:186
(anonymous) @ C:\web\translationCore\node_modules\redux-promise\lib\index.js:21
(anonymous) @ C:\web\translationCore\node_modules\redux-thunk\lib\index.js:14
dispatch @ C:\web\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectDataLoadingActions.js:44
C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:9747 The above error occurred in the <Pane> component:
    in Pane (created by View)
    in div (created by View)
    in div (created by View)
    in div (created by View)
    in View (created by ScripturePane)
    in MuiThemeProvider (created by ScripturePane)
    in ScripturePane
    in div
    in div
    in View
    in Container (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:9747
captureError @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10540
renderRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10391
performWorkOnRoot @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:11014
performWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10967
requestWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10878
scheduleWorkImpl @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10732
scheduleWork @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10689
enqueueSetState @ C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:6212
Component.setState @ C:\web\translationCore\node_modules\react\cjs\react.development.js:237
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:222
notify @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:30
notifyNestedSubs @ C:\web\translationCore\node_modules\react-redux\lib\utils\Subscription.js:69
onStateChange @ C:\web\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:219
dispatch @ C:\web\translationCore\node_modules\redux\lib\createStore.js:186
(anonymous) @ C:\web\translationCore\node_modules\redux-promise\lib\index.js:21
(anonymous) @ C:\web\translationCore\node_modules\redux-thunk\lib\index.js:14
dispatch @ C:\web\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectDataLoadingActions.js:44
Pane.js:17 Uncaught (in promise) TypeError: Cannot read property '#<Object>' of undefined
    at Pane.render (C:/web/translationCore/tC_apps/ScripturePane/src/components/Pane.js:17:19)
    at finishClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873:31)
    at updateClassComponent (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850:12)
    at beginWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225:16)
    at performUnitOfWork (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224:16)
    at workLoop (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581:16)
    at invokeGuardedCallback (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438:27)
    at renderRoot (C:\web\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366:7)```

**Comment by richmahn** [comment]
LGTM

---

Reviewed 5 of 10 files at r1, 2 of 4 files at r2, 3 of 3 files at r4, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3967#-:-L6sfbw-YuoJ_Hmyfxw7:bb6ywmx)*

**Comment by RoyalSix** [comment]
Reviewed 3 of 7 files at r8.
Review status: 10 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3967)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing: `LGTM`

---

Review status: 10 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3967#-:-L6wrF0BEd9fgSLQAHEq:b-xvn5x)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3967#-:-L6wss5KsfkFYAPZZukv:bnfp4nl)*

**Pull request merged**
