### PR TITLE
update wordmap to provide performance improvements

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Improves the performance of wordMAP in certain corner cases. See #6554 
- Improves the accuracy of word occurrences. #6237

wordMAP changes can be viewed here https://github.com/unfoldingWord/wordMAP/compare/e2a037...v0.8.0

#### Please include detailed Test instructions for your pull request:
- See the introductory comment in #6554 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6647)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d043c08)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-linux-x64-2.1.0-d043c08.deb) is ready for download.
[macOS build 2.1.0 (d043c08)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-macos-x64-2.1.0-d043c08.dmg) is ready for download.
[Windows x64 build 2.1.0 (d043c08)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-win-x64-2.1.0-d043c08.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d043c08)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-win-x32-2.1.0-d043c08.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3750051)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-linux-x64-2.1.0-3750051.deb) is ready for download.
[macOS build 2.1.0 (3750051)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-macos-x64-2.1.0-3750051.dmg) is ready for download.
[Windows x64 build 2.1.0 (3750051)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-win-x64-2.1.0-3750051.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3750051)](https://tc-builds.door43.org/build/bugfix-joel-6554/translationCore-win-x32-2.1.0-3750051.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
LGTM - not seeing the lock ups.

**Pull request merged**
