### PR TITLE
Module API Removal

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1789)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 4 of 54 files at r1.
Review status: 4 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1789)*

**Comment by klappy** [comment]
Reviewed 1 of 54 files at r1.
Review status: 5 of 54 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1789)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1789#-:-Km8p81YXx1G6qrCfDOT:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 49 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1789)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Reviewed 27 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1789#-:-Km8pGrFU2DF_oKnzlZF:bnfp4nl)*

**Pull request merged**
