### PR TITLE
Add Reports To Modal w/ Redux Implementation

### PR DESCRIPTION
**Pull request by mannycolon**
The Reports components need further refactor. they are one of the only ones that were never touched while we were going through the refactor face. it will need a lot of attention going forward. however I made it work as redux as possible for now. 

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/568)

### CODE REVIEW

**Comment by ihoegen** [comment]
@mannycolon Check out the Travis Build log, looks like there's an issue with capitalization

**Comment by ihoegen** [comment]
@mannycolon Also, update with develop, looks like some of your tools are behind.

**Comment by mannycolon** [comment]
@ihoegen my tools should be the latest

**Comment by ihoegen** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/components/core/reports/ReportSideBar.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2Dg86WlXU_4xVBhM:-KbT2Dg86WlXU_4xVBhN:bxhmv4i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/ReportSideBar.js#L8)):*
> ```JavaScript
> bootstrapUtils.addStyle(Button, 'blue');
> const ReportFilters = require("./ReportFilters.js");
> const style = require("./Style");
> ```

Lowercase this

---

*[src/js/components/core/reports/style.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2A1PqFZtQuzSh7Ne:-KbT2A1QOxGRa4nmdt1e:b-bblb1a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/style.js#L1)):*
> ```JavaScript
> var style = {
> ```

This is probably the file in question. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568)*

**Comment by mannycolon** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/reports/ReportSideBar.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2Dg86WlXU_4xVBhM:-KbT40b_jrVwdr5r_zfm:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/ReportSideBar.js#L8)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Lowercase this
</blockquote></details>

Done.

---

*[src/js/components/core/reports/style.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2A1PqFZtQuzSh7Ne:-KbT42jFOgYqCKQgE-RH:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/style.js#L1)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

This is probably the file in question. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568)*

**Comment by ihoegen** [comment]
Anything else we're waiting on?

**Comment by mannycolon** [comment]
@ihoegen @RoyalSix and I just fixed the bug you guys were talking about earlier

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/reports/ReportSideBar.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2Dg86WlXU_4xVBhM:-KbTExjnNh3qzKwTmwv0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/ReportSideBar.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/js/components/core/reports/style.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568#-KbT2A1PqFZtQuzSh7Ne:-KbTF0HmD6ljSvsF2dJ6:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4676745a222d37df54cd0d86e79a6296fba58dcb/src/js/components/core/reports/style.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568)*

**Comment by RoyalSix** [comment]
Reviewed 12 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/568)*

**Pull request merged**
