### PR TITLE
Bugfix mcleanb 5388/Fix edge cases for USFM parsing

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fix convert JSON to USFM where verse starts with a newline.

#### Please include detailed Test instructions for your pull request:
- test with [usfm-body-testF.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2704201/usfm-body-testF.usfm.zip)
- import above usfm file and then export to USFM.  Comparing input with output file the only difference should be in the first line.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5627)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0a4cd01)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-0a4cd01.deb) is ready for download.
[macOS build 1.1.0 (0a4cd01)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-0a4cd01.dmg) is ready for download.
[Windows x64 build 1.1.0 (0a4cd01)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-0a4cd01.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0a4cd01)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-0a4cd01.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
I did the steps above and used a diff checker to see if there is a difference. Not sure if its related to your story but I did find differences beyond the first line check it out here
https://www.diffchecker.com/FXkoPMU4

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (317b0c5)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-317b0c5.deb) is ready for download.
[macOS build 1.1.0 (317b0c5)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-317b0c5.dmg) is ready for download.
[Windows x64 build 1.1.0 (317b0c5)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-317b0c5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (317b0c5)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-317b0c5.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1d0662e)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-1d0662e.deb) is ready for download.
[macOS build 1.1.0 (1d0662e)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-1d0662e.dmg) is ready for download.
[Windows x64 build 1.1.0 (1d0662e)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-1d0662e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1d0662e)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-1d0662e.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@RoyalSix Updated dependencies and have it working now in concourse build https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-1d0662e.dmg

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-36a8dc2.deb) is ready for download.
[macOS build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-36a8dc2.dmg) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-36a8dc2.deb) is ready for download.
[macOS build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-36a8dc2.dmg) is ready for download.
[Windows x64 build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-36a8dc2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (36a8dc2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-36a8dc2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9f6b976)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-9f6b976.deb) is ready for download.
[macOS build 1.1.0 (9f6b976)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-9f6b976.dmg) is ready for download.
[Windows x64 build 1.1.0 (9f6b976)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-9f6b976.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9f6b976)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-9f6b976.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (47d1c53)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-47d1c53.deb) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (47d1c53)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-47d1c53.deb) is ready for download.
[macOS build 1.1.0 (47d1c53)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-47d1c53.dmg) is ready for download.
[Windows x64 build 1.1.0 (47d1c53)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-47d1c53.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (47d1c53)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-47d1c53.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ec890fc)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-ec890fc.deb) is ready for download.
[macOS build 1.1.0 (ec890fc)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-ec890fc.dmg) is ready for download.
[Windows x64 build 1.1.0 (ec890fc)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-ec890fc.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ec890fc)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-ec890fc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fe53fe2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-fe53fe2.deb) is ready for download.
[macOS build 1.1.0 (fe53fe2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-fe53fe2.dmg) is ready for download.
[Windows x64 build 1.1.0 (fe53fe2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-fe53fe2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fe53fe2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-fe53fe2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (5cfa48d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-linux-x64-1.1.0-5cfa48d.deb) is ready for download.
[macOS build 1.1.0 (5cfa48d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-macos-x64-1.1.0-5cfa48d.dmg) is ready for download.
[Windows x64 build 1.1.0 (5cfa48d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x64-1.1.0-5cfa48d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (5cfa48d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5388/translationCore-win-x32-1.1.0-5cfa48d.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r3, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5627)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
