### PR TITLE
Import Online 

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3314)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 9 of 13 files at r1, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[__tests__/OnlineImportWorkflowHelpers.test.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CXqOwz8p1EuuK1HvF:-L-CXqOwz8p1EuuK1HvG:b-p4g2bu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/__tests__/OnlineImportWorkflowHelpers.test.js#L9)):*
> ```JavaScript
> const IMPORTS_PATH = path.join(pathex.homedir(), 'translationCore', 'imports');
> 
> jest.unmock('simple-git');
> ```

do we wanna mock this or is it too time-consuming for now?

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CYKnXoOXgrtnHmUwo:-L-CYKnXoOXgrtnHmUwp:b51d426) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/actions/Import/OnlineImportWorkflowActions.js#L13)):*
> ```JavaScript
> export const onlineImport = () => {
>   return((dispatch) => {
>     dispatch(OnlineImportWorkflowHelpers.cloneRepo());
> ```

do we need the dispatch?

---

*[src/js/actions/Import/ProjectMigrationActions.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CYZAZH2-ZCEeOoEQI:-L-CYZAZH2-ZCEeOoEQJ:b-kqrayk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/actions/Import/ProjectMigrationActions.js#L9)):*
> ```JavaScript
> export const migrate = () => {
>   return ((dispatch, getState) => {
>     let { projectSaveLocation } = getState().projectDetailsReducer;
> ```

do you think is a good idea to save the path to the `imports` folder in the projectSaveLocation. should we find a better place and only save it there once it's in the `projects` folder

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 3 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CZXfjYDTY-IYBxlVc:-L-CZXfjYDTY-IYBxlVd:bmf528j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L3)):*
> ```JavaScript
> import git from '../GitApi';
> import path from 'path';
> import pathex from 'path-extra';
> ```

use path-extra instead of `path`
so just do this

import path from 'path-extra'

`path-extra` includes all methods from  the 'path' module  and more

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 4 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CZJQ9DUNLQsnsyBOg:-L-CZJQ9DUNLQsnsyBOh:b-2qdm51) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L4)):*
> ```JavaScript
> import path from 'path';
> import pathex from 'path-extra';
> import * as fs from 'fs-extra';
> ```

this can be imported without the `* as`

---

*[src/js/helpers/ProjectValidation/MissingVersesHelpers.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-C_m5onIjAqM_kmzLU:-L-C_m5onIjAqM_kmzLV:b-6fcvph) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/helpers/ProjectValidation/MissingVersesHelpers.js#L6)):*
> ```JavaScript
>  */
> 
> import * as fs from 'fs-extra';
> ```

why the `* as`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by RoyalSix** [comment]
#3234
#3237 
#3245 
#3236 
#3242

**Comment by mannycolon** [comment]
Reviewed 1 of 13 files at r1, 1 of 18 files at r3, 1 of 30 files at r6, 1 of 19 files at r7, 2 of 39 files at r9, 2 of 36 files at r11, 4 of 37 files at r12, 33 of 33 files at r13.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[__tests__/ProjectDetails.test.js, line 55 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-HqbFDy4G14UZl6Tmz:-L-HqbFDy4G14UZl6Tn-:bo9lo5b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/__tests__/ProjectDetails.test.js#L55)):*
> ```JavaScript
>   });
> 
>   // test('should select word Alignment tool and load it to the store', () => {
> ```

we dont need this unit tests anymore?

---

*[__tests__/projectSelection.test.js, line 33 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hqh9OowKEaBHoxn5F:-L-Hqh9OowKEaBHoxn5G:bm0v59q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/__tests__/projectSelection.test.js#L33)):*
> ```JavaScript
> 
>   test('should select a project and import a valid manifest to the store', () => {
>     // store.dispatch(ProjectSelctionActions.selectProject(noMergeConflictsProjectPath));
> ```

we dont need this anynmore?

---

*[src/js/actions/ImportOnlineActions.js, line 49 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hr0qtz4HamjCzkwHM:-L-Hr0qtz4HamjCzkwHN:bvg0ozq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/src/js/actions/ImportOnlineActions.js#L49)):*
> ```JavaScript
>  */
> function handleImportResults(dispatch, url, savePath, errMessage) {
>   debugger;
> ```

remove the debbuger

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 14 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hrbhj1jffpVEZz7rA:-L-Hrbhj1jffpVEZz7rB:b-lnf88u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/src/js/actions/Import/OnlineImportWorkflowActions.js#L14)):*
> ```JavaScript
>     try {
>     let link = getState().importOnlineReducer.importLink;
>     let projectPath = await dispatch(clone(link));
> ```

isnt clone a helper? do we need to dispatch it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[__tests__/OnlineImportWorkflowHelpers.test.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CXqOwz8p1EuuK1HvF:-L-IC2-PEjV9xMQtD-Gs:b-llbwl8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/__tests__/OnlineImportWorkflowHelpers.test.js#L9)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we wanna mock this or is it too time-consuming for now?
</blockquote></details>

We can mock it

---

*[__tests__/ProjectDetails.test.js, line 55 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-HqbFDy4G14UZl6Tmz:-L-IBzQFu8xHIzpl4yFG:b37h8yf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/__tests__/ProjectDetails.test.js#L55)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont need this unit tests anymore?
</blockquote></details>

It won't work until the import process is fixed.

---

*[__tests__/projectSelection.test.js, line 33 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hqh9OowKEaBHoxn5F:-L-ICYy4c2Y_-3g-tgx9:bdoh8zn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/__tests__/projectSelection.test.js#L33)):*
> It won't work until the import process is fixed.
It won't work until the import process is fixed.

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CYKnXoOXgrtnHmUwo:-L-ICeCKR0x6dz5S8HNL:bankha0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/actions/Import/OnlineImportWorkflowActions.js#L13)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need the dispatch?
</blockquote></details>

We do need the dispatcher

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 14 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hrbhj1jffpVEZz7rA:-L-ICpnS_88LN9DpsP3B:bpnpmix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/src/js/actions/Import/OnlineImportWorkflowActions.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

isnt clone a helper? do we need to dispatch it?
</blockquote></details>

It needs the dispatcher so maybe it should be an action

---

*[src/js/actions/Import/ProjectMigrationActions.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CYZAZH2-ZCEeOoEQI:-L-IDGa6HobqvG1AmBVL:b-rm13ld) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/actions/Import/ProjectMigrationActions.js#L9)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do you think is a good idea to save the path to the `imports` folder in the projectSaveLocation. should we find a better place and only save it there once it's in the `projects` folder
</blockquote></details>

I thought we were saving it from the imports folder after the clone and then to the projects folder after the migration and validation.
Is there something wrong with that workflow?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by RoyalSix** [comment]
Review status: 33 of 40 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ImportOnlineActions.js, line 49 at r13](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-Hr0qtz4HamjCzkwHM:-L-IS9QcI731MLhKsWeq:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/133ac184d9a20d72d358ee9b458cabc632c442a6/src/js/actions/ImportOnlineActions.js#L49)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove the debbuger
</blockquote></details>

Done.

---

*[src/js/helpers/ProjectValidation/MissingVersesHelpers.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-C_m5onIjAqM_kmzLU:-L-ISCoeGcWvfH3OI8MX:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/helpers/ProjectValidation/MissingVersesHelpers.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why the `* as`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by richmahn** [comment]
Reviewed 5 of 13 files at r1, 1 of 18 files at r3, 1 of 30 files at r6, 1 of 19 files at r7, 2 of 39 files at r9, 2 of 36 files at r11, 2 of 37 files at r12, 29 of 33 files at r13, 3 of 5 files at r14, 4 of 4 files at r15.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by richmahn** [comment]
Coverage has greatly decreased.

**Comment by mannycolon** [comment]
*[src/js/actions/Import/ProjectMigrationActions.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CYZAZH2-ZCEeOoEQI:-L-JI76PFoHJSJEecJic:b-v6woet) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/src/js/actions/Import/ProjectMigrationActions.js#L9)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I thought we were saving it from the imports folder after the clone and then to the projects folder after the migration and validation.
Is there something wrong with that workflow?
</blockquote></details>

not sure I fully understand. I was just wondering if that would cause any issues. but if you feel its ok then it shouldn't be a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by mannycolon** [comment]
Reviewed 2 of 5 files at r14, 3 of 4 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/OnlineImportWorkflowHelpers.test.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-CXqOwz8p1EuuK1HvF:-L-JHYnPecOAvmjeNDgN:bb7x46g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/caf1ec19efcb58105d1dd155d43ac1cb43bca825/__tests__/OnlineImportWorkflowHelpers.test.js#L9)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

We can mock it
</blockquote></details>

ok cool

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 8 at r15](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314#-L-JHrTFed_FJ-viR-ia:-L-JHrTFed_FJ-viR-ib:bdite7z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6373986f5e810b6608fce6d28ade9c1b75861e57/src/js/actions/Import/ProjectImportFilesystemActions.js#L8)):*
> ```JavaScript
> export const move = () => {
>   return ((dispatch) => {
>     dispatch({ type: 'MOVE' });
> ```

maybe merge with the latest of feature/import-refactor so you have access to the actual move action 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by mannycolon** [comment]
@RoyalSix Merge with the latest of `feature/import-refactor`

**Comment by mannycolon** [comment]
Reviewed 1 of 5 files at r14, 1 of 4 files at r15, 3 of 3 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3314)*

**Comment by mannycolon** [comment]
@RoyalSix Can you check if you merged with the latest on `feature/import-refactor`

**Pull request merged**
