### PR TITLE
Added fix for blank screen on tool reselect

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Since tN tool progress is based on the GL we need to run some processing after each GL selection to get the progress. 
This was breaking because we cleared the contextId after each GL progress selection (including auto selection on mount of the component). When the tool component tried to reopen the same tool that was already open it does not take into account if there is a contextId. Only if the toolName is the same (and some other things [here](https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/components/home/toolsManagement/ToolCard.js#L145)). When the tool renders with a blank contextId weird things can happen. (These should be fixed else where)
To fix this we are explicitly clearing the toolName after each GL change in tN. This PR also includes a performance fix to only regenerate progress if the GL selected in tN is different. This keeps the quick tool open for the already selected tool.

#### Please include detailed Test instructions for your pull request:
- To test open a tool , and then go back to the tools page and open the same tool

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6483)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (5a7b365)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-linux-x64-2.0.0-5a7b365.deb) is ready for download.
[macOS build 2.0.0 (5a7b365)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-macos-x64-2.0.0-5a7b365.dmg) is ready for download.
[Windows x64 build 2.0.0 (5a7b365)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-win-x64-2.0.0-5a7b365.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (5a7b365)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-win-x32-2.0.0-5a7b365.setup.exe) is ready for download.

**Review by mannycolon — DISMISSED** [review]
So no need to clear the data that was being cleared before? 

I think McLean worked on this so I would like his feedback before merging.

**Comment by PhotoNomad0** [comment]
Test problem with tW - get a critical error when relaunching tW:

Screen Shot 2019-10-11 at 12 53 18 PM

**Comment by RoyalSix** [comment]
#6438 Need to make sure this still works with new functionality
Update: Looks good

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6483)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (d621638)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-linux-x64-2.0.0-d621638.deb) is ready for download.
[macOS build 2.0.0 (d621638)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-macos-x64-2.0.0-d621638.dmg) is ready for download.
[Windows x64 build 2.0.0 (d621638)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-win-x64-2.0.0-d621638.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (d621638)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-win-x32-2.0.0-d621638.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Still needs the latest checking-tool-wrapper.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6483)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (9579e17)](https://tc-builds.door43.org/build/feature-jay-6472-2/translationCore-linux-x64-2.0.0-9579e17.deb) is ready for download.
Some builds failed

**Pull request merged**
