### PR TITLE
Add data migration

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This renames the apps folder to .apps if applicable. Does so after clicking select. 

#### How to test this pull request:

Test on a project that does not have an apps folder. Test one with an apps folder. Test one with a .apps folder and an apps folder. Test one with a .apps folder.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1636)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/LoadHelpers.js, line 477 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1636#-KkWaBGxKHoLd16aAHx8:-KkWaBGyxxqQqLjV_AQW:b-1a67c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/025e58d0348a56bd34fd12c0f7b3bf9a6810d22f/src/js/helpers/LoadHelpers.js#L477)):*
> ```JavaScript
>     let projectDir = fs.readdirSync(projectPath);
>     if (projectDir.includes('apps') && projectDir.includes('.apps')) {
>         fs.removeSync(Path.join(projectPath, '.apps'))
> ```

why would you remove the .apps folder in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1636#-:-KkWaFDFVwYoB--Gd2dZ:bnfp4nl)*

**Comment by ihoegen** [comment]
@mannycolon It's for the case where they used the app after the rename, but before the migration came

**Comment by mannycolon** [comment]
@ihoegen makes senseme I'm ready to merge it. Do you want someone else to also take a look at your PR?

**Comment by EllDoubleYew** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1636#-:-KkWe1CBenoJFsgjEG_O:bnfp4nl)*

**Comment by EllDoubleYew** [comment]
@mannycolon @ihoegen LGTM over here to. Im good to merge

**Pull request merged**
