### PR TITLE
Fixed The Menu Using Old Props Bug

### PR DESCRIPTION
**Pull request by RoyalSix**
-This PR also includes a bug fix for USFM

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/540)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/pages/app.js, line 171 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540#-KbDflCz8pYoeutoHV1L:-KbDflCz8pYoeutoHV1M:b-6fd7jj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b85252f39e398cac7f6960abf094b3adf8cf234e/src/js/pages/app.js#L171)):*
> ```JavaScript
>     //We are going to have to change the way we are handling the isCurrentItem, it does not need to be
>     //attached to every menu/submenuitem
>     this.setState({
> ```

Why is this no longer being merged?

---

*[src/js/pages/app.js, line 180 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540#-KbDfpG1hXBhBoJ66SWl:-KbDfpG1hXBhBoJ66SWm:b-nuo3ey) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b85252f39e398cac7f6960abf094b3adf8cf234e/src/js/pages/app.js#L180)):*
> ```JavaScript
>       currentBookName: bookName,
>     }, () => {
>       console.log(this.state)
> ```

Console log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540)*

**Comment by RoyalSix** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 171 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540#-KbDflCz8pYoeutoHV1L:-KbLxWnAt0SLltJqId4H:b-tt6c5q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b85252f39e398cac7f6960abf094b3adf8cf234e/src/js/pages/app.js#L171)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Why is this no longer being merged?
</blockquote></details>

Because it is being completely replaced by old props, the old props that don't match the key will stay. The merge was making the states concat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540)*

**Comment by RoyalSix** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 180 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540#-KbDfpG1hXBhBoJ66SWl:-KbLxz9ubonneYdJLKAd:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b85252f39e398cac7f6960abf094b3adf8cf234e/src/js/pages/app.js#L180)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Console log
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540)*

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540)*

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/540)*

**Pull request merged**
