### PR TITLE
BugFix 4554/Fix to output front matter in USFM3 export

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes bug that front matter was not being output with USFM3 export.

#### Please include detailed Test instructions for your pull request:
- install build from bottom of page
- do online import of project: https://git.door43.org/lrsallee/en_tit
- do export USFM3 of project
- check USFM file that was saved.  Should see front matter in each of the three chapters between chapter marker and verse 1.  For example:

```
\c 1
\p 
\v 1 
```

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4660)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6a6cd7c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6a6cd7c.zip) is ready for download.
[macOS build 0.10.0 (6a6cd7c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6a6cd7c.dmg) is ready for download.
[Windows x64 build 0.10.0 (6a6cd7c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6a6cd7c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6a6cd7c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6a6cd7c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (80d3677)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-80d3677.zip) is ready for download.
[macOS build 0.10.0 (80d3677)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-80d3677.dmg) is ready for download.
[Windows x64 build 0.10.0 (80d3677)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-80d3677.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (80d3677)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-80d3677.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4660)*

**Pull request merged**
