### PR TITLE
Fixed persistence for tool cards category selection 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- This project had all tW checkboxes checked on the tool card in 1.1.4. 
- Copy [en_new_rut_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3432604/en_new_rut_book.zip) to the projects folder.
- Open tC and select it.
- All tW checkboxes should be selected. 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6288)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (46974a2)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-linux-x64-2.0.0-46974a2.deb) is ready for download.
[macOS build 2.0.0 (46974a2)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-macos-x64-2.0.0-46974a2.dmg) is ready for download.
[Windows x64 build 2.0.0 (46974a2)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-win-x64-2.0.0-46974a2.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (46974a2)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-win-x32-2.0.0-46974a2.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6288)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
Using attached build translationCore 2.0.0 (46974a2), don't see any tW categories selected when I open en_new_rut_book for first time.

**Comment by PhotoNomad0** [comment]
See this error in console: 
Screen Shot 2019-07-30 at 7 27 19 AM

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (664b6ca)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-linux-x64-2.0.0-664b6ca.deb) is ready for download.
[macOS build 2.0.0 (664b6ca)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-macos-x64-2.0.0-664b6ca.dmg) is ready for download.
[Windows x64 build 2.0.0 (664b6ca)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-win-x64-2.0.0-664b6ca.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (664b6ca)](https://tc-builds.door43.org/build/bugfix-mannycolon-5996/translationCore-win-x32-2.0.0-664b6ca.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6288)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
