### PR TITLE
Check Box Fix For Online Dialog

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR address the online action dialog having weird behavior of re-mounting after clicking the check box and also not showing expected feedback that it actually has been checked.

#### How to test this pull request:
Open the app
and trigger an action that will show the ```Online Action Dialog```
This could be trying to import a project from online or even accessing one of the urls in the app.
You should be able to check and uncheck the box without any problems.

**Note: This problem was unrelated to React 16.**
The problem occurred from the component being re-mounted by ```react-localize-redux```
They're API highly suggests not using the ```localize``` wrapper for components already wrapped by react-redux ```connect```. 
I took the liberty to make the fix for the Alert Modal Dialog but similar issues that are out of scope of this story may happen in the future if we do not account for those.
i.e. ```src/js/pages/app.js``` lines 58-59 are wrapping two containers with ```withLocale``` those are also wrapped with ```connect```.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3762)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix I would suggest talking with @neutrinog about this changes if you haven't done so already.

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/dialogComponents/Alert.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rZG2pIcAtWiF2hFpN:-L4rZG2pIcAtWiF2hFpO:b-dy7eoc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/components/dialogComponents/Alert.js#L8)):*
> ```JavaScript
> 
> class Alert extends Component {
>   componentDidMount(){
> ```

do we need componentDidMount and componentWillUnmount?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762)*

**Comment by da1nerd** [comment]
FYI, the suggestion to not connect a component more than once is motivated by performance. You can (usually) connect a component many times without any adverse affects. There are some cases where the order of connections matters, but that's no the norm.

The performance impact should only be a concern for very complicated components where there is a lot of nested updating.

**Comment by da1nerd** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/Locale.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rd-K6ibX_1G8-VT_m:-L4rd-K6ibX_1G8-VT_n:b9u26ab) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/components/Locale.js#L17)):*
> ```JavaScript
> };
> 
> export const withTranslate = (state) => {
> ```

Rather than adding this new withTranslate method you can use the existing `getTranslate` method found in `src/js/selectors/index.js`.

---

*[src/js/containers/AlertDialogContainer.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rcWdJAWTVgX658bue:-L4rcWdJAWTVgX658buf:b-swb4us) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/containers/AlertDialogContainer.js#L33)):*
> ```JavaScript
>   return {
>     alertModalReducer: state.alertModalReducer,
>     translate: withTranslate(state)
> ```

Good. There were a number of cases where the state could be rolled up into the component instead of injecting it from the outside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/Locale.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rd-K6ibX_1G8-VT_m:-L4rdkWGMpn2NJ93xZm3:byqw7uj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/components/Locale.js#L17)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Rather than adding this new withTranslate method you can use the existing `getTranslate` method found in `src/js/selectors/index.js`.
</blockquote></details>

Ahh ok. Thanks

---

*[src/js/components/dialogComponents/Alert.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rZG2pIcAtWiF2hFpN:-L4rdrii1--DqsZniJ31:b-tqbppe) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/components/dialogComponents/Alert.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need componentDidMount and componentWillUnmount?
</blockquote></details>

Only for testing, I can refactor tho so that it looks better

---

*[src/js/containers/AlertDialogContainer.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-L4rcWdJAWTVgX658bue:-L4re1ii3nGQenWzDNFn:b-zcjvte) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/98779a2d86ade1bbbd7bb30d6583d624eb10e1c8/src/js/containers/AlertDialogContainer.js#L33)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Good. There were a number of cases where the state could be rolled up into the component instead of injecting it from the outside.
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762)*

**Comment by da1nerd** [comment]
Reviewed 1 of 8 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762)*

**Comment by PhotoNomad0** [comment]
Testing app works fine on checkbox.

**Comment by PhotoNomad0** [comment]
See a problem with checkbox to access internet: if you select the box and then click cancel, then the next time you try to access the internet you don't get a warning prompt.  I think if you select cancel, then the box check box selection should be ignored.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3762#-:-L4vPFtV9pghJFrWk-ks:bnfp4nl)*

**Comment by RoyalSix** [comment]
@cckozie @benjore Is this expected behavior? Should the cancel button invalidate the users preference of showing the dialog for online actions?

**Comment by da1nerd** [comment]
The underlying problem here is that we're using redux to control the checkbox state. Really, the checkbox should be managed by the component state and then only stored in the redux state when the user confirms.

> Edit: if indeed canceling should invalidate the user's preference as mentioned by @RoyalSix above.

**Comment by cckozie** [comment]
@RoyalSix @neutrinog Actually I raised the issue about the checkbox taking effect even when the cancel button is clicked way back when this was first implemented, and Ben affirmed that it is the desired behavior. If the box is checked when either button is clicked, the warning will not be displayed again until the app is closed or the user logs out.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3762#-:-L4visNUrAnYYzUne4AB:bnfp4nl)*

**Comment by mannycolon** [comment]
Was @neutrinog last comment addressed ?

**Pull request merged**
