### PR TITLE
Local user implementation #1407

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- the need of a local user to use tC offline.

#### How to test this pull request:

- [x] Creating a Local User
  - [x] When clicking on "Terms and Conditions" in the main screen, the screen will change to show the Terms and Conditions (as per the mockup)
    - [x] Clicking "Go Back" will return the user to the main Create Local User page
    - [ ] Clicking one of the hyperlinks will open a modal with that document
  - [x] The "Create" button is deactivated until the checkbox is selected and a username is entered
  - [x] When a user is created, that user stays "logged in" until they "log out"
  - [x] If a user logs out, they must create a new local user (there is no list of created usernames available in the app at this time) or log in with Door43
- [x] In "Import Online Projects" show "Unable to connect to the online projects. Please log into your Door43 account." for the top part, keep the URL import enabled.
- [x] In "My Projects" - when the user clicks "Upload" return a message saying "Please log in to Door43 to upload your projects"

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1491)

### CODE REVIEW

**Comment by ihoegen** [comment]
@mannycolon Looks good to me, I'll remove the console log, and test

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/login/LocalLogin.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1491#-KjecS8r2H3AM_JczI04:-KjecS8r2H3AM_JczI05:byp18fd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1f03d2c1cb5142047fdf1d843e54cb8b9d0f0bb3/src/js/components/core/login/LocalLogin.js#L23)):*
> ```JavaScript
>     let {showTermsAndConds} = this.state;
>     let disabledButton = this.props.userdata.username && this.state.checkBoxChecked ? false : true;
>     console.log(disabledButton)
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1491#-:-Kjecd7jxuJuYJeQVmpt:b6pduvw)*

**Comment by ihoegen** [comment]
@mannycolon Hyperlinks do not work, the user is logged out when refreshing. Also, I think the create button should change colors when it is okay to click. Also, this error comes up on startup
image

**Comment by mannycolon** [comment]
@ihoegen did you get a chance to review this PR again.

**Comment by ihoegen** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1491)*

**Pull request merged**
