### PR TITLE
issue 1068, styling changes to sidebar collapse button

### PR DESCRIPTION
**Pull request by cdwhitfield73**
#### This pull request addresses:

change color and size of sidebar collapse button to match desired formatting

#### How to test this pull request:

collapse button should be black and thinner (like the tHelps side) and vertically centered.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1079)

### CODE REVIEW

**Comment by cdwhitfield73** [comment]
Added more code to this PR.  Now includes changing the background color of sub menu items and left alignment of sub menu items.

**Comment by ihoegen** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/groupMenu/GroupItem.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-KhZcA8jeI7P97zgNcvK:-KhZcA8jeI7P97zgNcvL:bi3fj5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/60ceb43bce00d42b98415cf802eb4c8ebe3837fc/src/js/components/core/groupMenu/GroupItem.js#L13)):*
> ```JavaScript
>    */
>   statusGlyph(selections, active) {
>     let statusGlyph = <Glyphicon glyph="" style={style.menuItem.statusIcon.blank} /> // blank as default, in case no data or not active
> ```

Is there a reason you're using a Glyphicon instead of a div here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079)*

**Comment by ihoegen** [comment]
@cdwhitfield73 I have a hunch that the reason the tests are failing is because your PR is coming off of a branch from another Repo

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/groupMenu/GroupItem.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-KhZcA8jeI7P97zgNcvK:-Khc-ApbHu4RSHQOYZqe:bf9egxk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/60ceb43bce00d42b98415cf802eb4c8ebe3837fc/src/js/components/core/groupMenu/GroupItem.js#L13)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Is there a reason you're using a Glyphicon instead of a div here?
</blockquote></details>

yeah i have the same question

---

*[src/js/components/core/groupMenu/Style.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-Khc-Egl17nLBQNXklPm:-Khc-Egl17nLBQNXklPn:b-8lu24u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1eb43df685e994d4aed8e860f389a09e98c1508/src/js/components/core/groupMenu/Style.js#L12)):*
> ```JavaScript
>         cursor: "pointer",
>         borderBottom: "1px solid #747474",
>         cursor: 'pointer',
> ```

why did you remove this code??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079)*

**Comment by cdwhitfield73** [comment]
That may be, but this is the third PR I have done and the other two did not have any problems.  I will try pushing future changes directly to a branch on the main repo.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/groupMenu/GroupItem.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-KhZcA8jeI7P97zgNcvK:-KhcPCVbDzasB_wxtT9M:b-qd3ig3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/60ceb43bce00d42b98415cf802eb4c8ebe3837fc/src/js/components/core/groupMenu/GroupItem.js#L13)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

yeah i have the same question
</blockquote></details>

The goal is to have the text moved over so it is aligned with the group text, meaning that there should be a space for the glyphicon even when there isn't one.  I tried to accomplish this with the blank div by giving it padding, etc. and it didn't work right, so I just created a default blank glyphicon to fill the space instead and it works great.  This blank one gets replaced by the bookmark or checkmark as needed.

---

*[src/js/components/core/groupMenu/Style.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-Khc-Egl17nLBQNXklPm:-KhcPf1qPOYioThOhpQq:brc4c2h) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1eb43df685e994d4aed8e860f389a09e98c1508/src/js/components/core/groupMenu/Style.js#L12)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you remove this code??
</blockquote></details>

I removed one of the lines that said "cursor: pointer" because there were two of them, which is redundant.  (See two lines above the deletion)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1079#-:-KhcOp8Q1tsNmASG7hSB:byqj6jd)*

**Pull request merged**
