### PR TITLE
Implementation of Redux for New Menu Design

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/636)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636)*

**Comment by ihoegen** [comment]
It looks good to me, just merge. However, I'm not the expert on Redux so you might want @mannycolon 's review as well

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/containers/StatusBarContainer.js, line 20 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636#-Kc6l4vCY-ZU8NpXcvk9:-Kc6l4vCY-ZU8NpXcvkA:b-aimqdh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0f185317b9da979b8b760dec5a694f5cff747cb0/src/js/containers/StatusBarContainer.js#L20)):*
> ```JavaScript
>         openModalAndSpecificTab: (visible, tabkey, sectionKey) => {
>             dispatch(modalActions.showModalContainer(true));
>             dispatch(modalActions.selectModalTab(tabkey, sectionKey));
> ```

could we make this two actions one action ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636)*

**Comment by RoyalSix** [comment]
Review status: 5 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/containers/StatusBarContainer.js, line 20 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636#-Kc6l4vCY-ZU8NpXcvk9:-Kc789RYY5mzrHc-KNDQ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0f185317b9da979b8b760dec5a694f5cff747cb0/src/js/containers/StatusBarContainer.js#L20)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we make this two actions one action ??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636)*

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/636)*

**Comment by mannycolon** [comment]
@RoyalSix I made the Tabs component, in the LoadModalContainer , a controlled state component. they used to be a uncontrolled state. at least this modal needed this changes we will find out as we go if the other sections need this changes as well.

**Pull request merged**
