### PR TITLE
Replaced stringHelperse.js with `string-punctuation-tokenizer` library when needed

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Replaced stringHelperse.js with `string-punctuation-tokenizer` library when needed

#### Please include detailed Test instructions for your pull request:
- Just make sure the app works as expected. (Hard to pinpoint what to test)
- I would follow the list below.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3916)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3916)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Testing: Not able to get tW to open. Getting error ```Warning: Failed prop type: The prop `projectDetailsReducer.currentProjectToolsSelectedGL` is marked as required in `Container`, but its value is `undefined`.```

**Comment by PhotoNomad0** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3916)*

**Comment by mannycolon** [comment]
@RoyalSix it looks like you did not run `npm run load-apps` after you change branches

**Comment by mannycolon** [comment]
@RoyalSix It should no longer be a problem. I just merged latest develop into this branch

**Comment by PhotoNomad0** [comment]
@mannycolon @RoyalSix - I am seeing the same problem as Jay when opening old projects:

Warning: Failed prop type: The prop `projectDetailsReducer.currentProjectToolsSelectedGL` is marked as required in `Container`, but its value is `undefined`.
    in Container (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
printWarning @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/fbjs/lib/warning.js:33
warning @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/fbjs/lib/warning.js:57
checkPropTypes @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/prop-types/checkPropTypes.js:52
validatePropTypes @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react/cjs/react.development.js:1171
createElementWithValidation @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react/cjs/react.development.js:1268
render @ ToolsContainer.js [sm]:44
finishClassComponent @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:7873
updateClassComponent @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:7850
beginWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:8225
performUnitOfWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10224
workLoop @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10288
callCallback @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:542
invokeGuardedCallbackDev @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:581
invokeGuardedCallback @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:438
renderRoot @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10366
performWorkOnRoot @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:11014
performWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10967
requestWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10878
scheduleWorkImpl @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10732
scheduleWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10689
enqueueSetState @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6212
Component.setState @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react/cjs/react.development.js:237
onStateChange @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-redux/lib/components/con…:222
dispatch @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux/lib/createStore.js:186
(anonymous) @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux-promise/lib/index.js:21
(anonymous) @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux-thunk/lib/index.js:14
dispatch @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux/lib/applyMiddleware.js:45
(anonymous) @ ProjectDataLoadingActions.js [sm]:38
Container.js [sm]:34 Uncaught TypeError: Cannot read property 'translationWords' of undefined
    at Container.componentWillReceiveProps (Container.js [sm]:8)
    at callComponentWillReceiveProps (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6389)
    at updateClassInstance (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6575)
    at updateClassComponent (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:7848)
    at beginWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:8225)
    at performUnitOfWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10224)
    at workLoop (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10288)
    at HTMLUnknownElement.callCallback (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:542)
    at Object.invokeGuardedCallbackDev (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:581)
    at invokeGuardedCallback (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:438)
    at renderRoot (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10366)
    at performWorkOnRoot (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:11014)
    at performWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10967)
    at requestWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10878)
    at scheduleWorkImpl (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10732)
    at scheduleWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10689)
    at Object.enqueueSetState (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6212)
componentWillReceiveProps @ Container.js [sm]:34
callComponentWillReceiveProps @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6389
updateClassInstance @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6575
updateClassComponent @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:7848
beginWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:8225
performUnitOfWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10224
workLoop @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10288
callCallback @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:542
invokeGuardedCallbackDev @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:581
invokeGuardedCallback @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:438
renderRoot @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10366
performWorkOnRoot @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:11014
performWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10967
requestWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10878
scheduleWorkImpl @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10732
scheduleWork @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:10689
enqueueSetState @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:6212
Component.setState @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react/cjs/react.development.js:237
onStateChange @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/react-redux/lib/components/con…:222
dispatch @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux/lib/createStore.js:186
(anonymous) @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux-promise/lib/index.js:21
(anonymous) @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux-thunk/lib/index.js:14
dispatch @ /Users/blm/Development/Electron/testDir/translationCore/node_modules/redux/lib/applyMiddleware.js:45
(anonymous) @ ProjectDataLoadingActions.js [sm]:38
/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.develo…:9747

**Comment by PhotoNomad0** [comment]
@mannycolon - I am seeing the same problem as @RoyalSix when opening old (and new) projects in tW.

screen shot 2018-03-01 at 12 17 33 pm

**Comment by mannycolon** [comment]
@RoyalSix @PhotoNomad0 It should work now if you get the latest version of the branch.

**Comment by RoyalSix** [comment]
@mannycolon Everything looks good now. I'll wait a few to merge if @PhotoNomad0 has time
If not I'll just merge.

**Pull request merged**
