### PR TITLE
Fixes #6285 - Scroll User Feedback when long text

### LINKED ISSUE #6285: Feedback window has UI issue
- [x] Add a scroll bar when the text gets too long

Include Application logs is not displayed.

To reproduce the problem on the projects screen, Click on send feedback and add lines of text to feedback.

It looks like it needs to be made scroll-able.

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes layout for User Feedback form to scroll when large amount of text (#6285)

#### Please include detailed Test instructions for your pull request:
- Go to user feedback form, type in lots of text in the feedback text area, watch the most awesome scroll bar ever appear!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6302)

### CODE REVIEW

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6302)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (ccdf4b7)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-linux-x64-2.0.0-ccdf4b7.deb) is ready for download.
[macOS build 2.0.0 (ccdf4b7)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-macos-x64-2.0.0-ccdf4b7.dmg) is ready for download.
[Windows x64 build 2.0.0 (ccdf4b7)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-win-x64-2.0.0-ccdf4b7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (ccdf4b7)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-win-x32-2.0.0-ccdf4b7.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6302)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a1ed691)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-linux-x64-2.0.0-a1ed691.deb) is ready for download.
[macOS build 2.0.0 (a1ed691)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-macos-x64-2.0.0-a1ed691.dmg) is ready for download.
[Windows x64 build 2.0.0 (a1ed691)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-win-x64-2.0.0-a1ed691.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a1ed691)](https://tc-builds.door43.org/build/bugfix-richmahn-6285/translationCore-win-x32-2.0.0-a1ed691.setup.exe) is ready for download.

**Pull request merged**
