### PR TITLE
redux tests

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1757)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 10 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Comment by klappy** [comment]
*[tests/i.alertModalReducer.js, line 94 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757#-Km8-WutxLW2puVVkBzE:-Km8-WutxLW2puVVkBzF:b-yls19b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2fa299cf8d3849286fcd9f93adb062ee32a7fb40/tests/i.alertModalReducer.js#L94)):*
> ```JavaScript
>         }
>       )
>     ).to.deep.equal(initialState);
> ```

update to `.to.eql(...` for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Comment by mannycolon** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/i.alertModalReducer.js, line 94 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757#-Km8-WutxLW2puVVkBzE:-Km8-v7ZI_be4PoQQpjZ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2fa299cf8d3849286fcd9f93adb062ee32a7fb40/tests/i.alertModalReducer.js#L94)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

update to `.to.eql(...` for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757#-:-Km808KsS2t2viTa6iHp:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 11 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757#-:-Km80BepI-h-TYShWC8i:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1757)*

**Pull request merged**
