### PR TITLE
New mockups implementation in the side nav bar and top status bar

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/264)

### CODE REVIEW

**Comment by mannycolon** [comment]
# ToDo-Assistant
to-do list application.

Features
---
- Ability to add, edit, remove or complete a to-do item.

- **Persistence:** if the user closes and re-opens the application, the list will be recover since it is saved in the locally.

- Due dates for items

- Categorizing items

- Ability to nest to-do items

- Multi-user.

**Comment by EllDoubleYew** [comment]
I have just a few comments on some styling changes. A screenshot is below, let me know if there is anything that you do not agree with.
sidebarchanges
- I have changed the overall width to 100px rather than 120px
- I have changed the logo to 85 by 85px rather than 80 by 85px
- I have removed all the box shadows

**Comment by mannycolon** [comment]
@EllDoubleYew looks good, just wondering why you removed the shadow??
@EllDoubleYew 

remember that this is going to be used to keep the menu view words/phrase so enough width needs to be account for.

**Comment by mannycolon** [comment]
did you ever review the code? @EllDoubleYew

**Comment by mannycolon** [comment]
@EllDoubleYew @ihoegen @RoyalSix Could we probably approve this PR today???

**Pull request merged**
