### PR TITLE
Updated Home Stepper To Suggested Fixes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR makes the home stepper labels dynamic to the content they hold, and makes the steps that are out of order unclickable (disabled)
- The selections (username, selected project, etc.) are being displayed.
- The out of sequence steps should not be clickable.

#### How to test this pull request:
Try opening multiple projects and testing all the workflow of maneuvering in the home stepper and looking for inconsistencies.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2542)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix could you please describe more specifically what things were fixed by this PR so i can tests them. I mean like list the things I should tests.

**Comment by mannycolon** [comment]
When testing verified that the out of sequence steps are not clickable.

**Comment by mannycolon** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/BodyUIActions.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPMxmGpmqfQOl9KjwK:-KsPMxmH-WpKP9O5Ub3X:bq8dlw7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L37)):*
> ```JavaScript
>   return ((dispatch, getState) => {
>     const { stepIndex } = getState().homeScreenReducer.stepper;
>     return dispatch(goToStep(stepIndex + 1))
> ```

why do you return the dispatch? that seems unnecessary.

---

*[src/js/actions/BodyUIActions.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPN4XbzndT4N-TOfsU:-KsPN4XbzndT4N-TOfsV:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L44)):*
> ```JavaScript
>   return ((dispatch, getState) => {
>     const { stepIndex } = getState().homeScreenReducer.stepper;
>     return dispatch(goToStep(stepIndex - 1))
> ```

ibid

---

*[src/js/actions/BodyUIActions.js, line 104 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPNA6GyMIfz1kcHwle:-KsPNA6GyMIfz1kcHwlf:b1f0uu4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L104)):*
> ```JavaScript
> }
> 
> export const canGoToIndex = (stepIndex, state) => {
> ```

could you please add documentation for this action. For some reason, I can't figure out what does the canGoToIndex action do.

---

*[src/js/actions/LoginActions.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPNiktiNsPiDCiGxvj:-KsPNiktiNsPiDCiGxvk:bqd0pwd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/LoginActions.js#L14)):*
> ```JavaScript
>     if (local) {
>       dispatch({
>         type: consts.RECEIVE_LOGIN,
> ```

do we may wanna change the `RECEIVE_LOGIN` CONSTANT TO MAYBE LOGIN_USER. I know this isn't part of the story but do we wanna address it now since we are changing the action. 

---

*[src/js/helpers/ProjectSelectionHelpers.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPlD9inrhRH_qOF-77:-KsPlD9inrhRH_qOF-78:bdk0p0b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/helpers/ProjectSelectionHelpers.js#L46)):*
> ```JavaScript
> }
> 
> export function getProjectName(projectPath) {
> ```

do we want to add documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/BodyUIActions.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPMxmGpmqfQOl9KjwK:-KsPpPa7Xms8eeq_ssD9:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L37)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do you return the dispatch? that seems unnecessary.
</blockquote></details>

Fixed.

---

*[src/js/actions/BodyUIActions.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPN4XbzndT4N-TOfsU:-KsPpQet38euSOL3dLTO:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L44)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Fixed.

---

*[src/js/actions/BodyUIActions.js, line 104 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPNA6GyMIfz1kcHwle:-KsPpgpBHhvg7wFSbGil:bqqadf5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L104)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could you please add documentation for this action. For some reason, I can't figure out what does the canGoToIndex action do.
</blockquote></details>

Sorry forgot, added it back.

---

*[src/js/actions/LoginActions.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPNiktiNsPiDCiGxvj:-KsPs9-eUpDS4m54LDgI:bn9fpvw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/LoginActions.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we may wanna change the `RECEIVE_LOGIN` CONSTANT TO MAYBE LOGIN_USER. I know this isn't part of the story but do we wanna address it now since we are changing the action. 
</blockquote></details>

Good catch, and good idea. fixed.

---

*[src/js/helpers/ProjectSelectionHelpers.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPlD9inrhRH_qOF-77:-KsPtLRhwx75SY0vt8Ss:bqmjwcz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/helpers/ProjectSelectionHelpers.js#L46)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we want to add documentation?
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542)*

**Comment by RoyalSix** [comment]
@mannycolon updated to suggestions and merged

**Comment by klappy** [comment]
Reviewed 16 of 16 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/BodyUIActions.js, line 104 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-KsPNA6GyMIfz1kcHwle:-KsdTwDMJsuD-yKYsw0S:b37ebyy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d4c9f14418c682d86785950ebb76041d52036a0/src/js/actions/BodyUIActions.js#L104)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Sorry forgot, added it back.
</blockquote></details>

could you also add what it does?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-:-KsdUThWlAEdBAWNIiRw:bnfp4nl)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2542#-:-KsdkDcixXa_Q_2bHjLM:bnfp4nl)*

**Pull request merged**
