### PR TITLE
Implemented new layout design for report view and added filters

### PR DESCRIPTION
**Pull request by mannycolon**
**This pull request adds the following:**
- Made report an internal component that will render in front of all the layout of the app.
- More cohesive layout for reports cards.
- New report filtering options.
- Added report sidebar to handle filtering.
- Added the ability to search for notes, proposed word/phrase and other locations.
- Removed the unnecessary HTML report template.
- Added the ability to display a much more in detail presentation of the data for completed checks total, unfinished checks total, flagged checks total.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/176)

### CODE REVIEW

**Comment by mannycolon** [comment]
#122

**Comment by mannycolon** [comment]
#50

**Comment by mannycolon** [comment]
#147

**Comment by mannycolon** [comment]
#173

**Comment by mannycolon** [comment]
#172

**Comment by RoyalSix** [comment]
Looks really clean! Noticed one small problem thought;
When I did a search for a random string, I couldn't the reports to show anymore

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/176#-:-KTCzWLvFPNcftYk2DzA:bsmkt2x)_

**Comment by mannycolon** [comment]
@RoyalSix What happened exactly, did  the other filters stop working??

**Comment by mannycolon** [comment]
@RoyalSix what do i need to do in order to get this PR approve??

**Comment by mannycolon** [comment]
@RoyalSix  just pushed the fix for the searchbox, this should be PR ready

**Comment by RoyalSix** [comment]
Awesome it looks like that works great now! Just one more small thing. Might seem tedious but it effects usability.
If you filter by chapter, and then want to go back to "chapter" there is no way to see every chapter again without closing and re-opening the window.

---

Reviewed 2 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/176#-:-KTKibyBRtdmwhBztKA1:b-ittfxu)_

**Comment by mannycolon** [comment]
@RoyalSix let me take a look at that

**Comment by mannycolon** [comment]
@RoyalSix it should be good now

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/176)_

**Pull request merged**
