### PR TITLE
Feature #3186/Fix broken unit tests

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Fix broken unit tests due to switch to usfm-js with verseObjects.

#### How to test this pull request:

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3735)

### CODE REVIEW

**Review by klappy — APPROVED** [review]

**Comment by klappy** [comment]
Reviewed 2 of 10 files at r1.
Review status: 2 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r1, 1 of 3 files at r2.
Review status: 4 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 2 of 10 files at r1.
Review status: 6 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r2.
Review status: 7 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
*[src/js/actions/WordAlignmentLoadActions.js, line 133 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-L4HkHBgghTq1xEjkM0M:-L4HkHBgghTq1xEjkM0N:brv92nb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ff1e4579d4b8f26c55e647a17c2d2348665e6697/src/js/actions/WordAlignmentLoadActions.js#L133)):*
> ```JavaScript
>   const wordBank = verseWords.map((word, index) => {
>     let occurrences = stringHelpers.occurrencesInString(_verseText, word);
>     let occurrence = stringHelpers.getOccurrenceInString(_verseText, index, word);
> ```

This should be updated to remove `getOccurrenceInString` in favor for `occurrenceInString`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 2 of 10 files at r1, 1 of 3 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by PhotoNomad0** [comment]
Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/WordAlignmentLoadActions.js, line 133 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-L4HkHBgghTq1xEjkM0M:-L4Htgghr6poIT8sU1eR:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ff1e4579d4b8f26c55e647a17c2d2348665e6697/src/js/actions/WordAlignmentLoadActions.js#L133)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This should be updated to remove `getOccurrenceInString` in favor for `occurrenceInString`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r3.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
This is looking really good!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-:-L4ISPrBkLsi8evjW2mh:b-i2sit7)*

**Comment by klappy** [comment]
*[src/js/helpers/AlignmentHelpers.js, line 76 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-L4IS-pmbkxAXYbHmYFz:-L4IS-pnlrMrtznLe4g0:bgel5ka) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41aa39766653fcc4cf827c9ac8ee2b37a1a4e7da/src/js/helpers/AlignmentHelpers.js#L76)):*
> ```JavaScript
>   let baseMilestones = [], wordBank = [];
>   let alignments = [];
>   for (let i = 0; i < verseObjects.length; i++) {
> ```

Is this any different than verseObjects.forEach?
If not, what do you think of using forEach here for consistency?
We've tried to replace most for loops with forEach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
*[src/js/helpers/AlignmentHelpers.js, line 76 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-L4IS-pmbkxAXYbHmYFz:-L4ISbNjkGMHbXtxVu78:b-y791or) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41aa39766653fcc4cf827c9ac8ee2b37a1a4e7da/src/js/helpers/AlignmentHelpers.js#L76)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is this any different than verseObjects.forEach?
If not, what do you think of using forEach here for consistency?
We've tried to replace most for loops with forEach.
</blockquote></details>

It looks like it would be a direct replacement. Since verseObject is an array, we should be able to just do `verseObjects.forEach(verseObject => {...})`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by RoyalSix** [comment]
I ran ```rm -rf node_modules/```, ```npm run update-apps``` , ```npm install```, and ```npm test``` 
(also tried deleting the tC_resources)
And got the following test failing  
```
FAIL  __tests__/AlignmentHelpers.test.js
  ● Merge Alignment into Verse Objects › handles titus 1:1 
```
Theres lots of differences in the expected vs  received object.
I used a diff checker for the big one, hopefully it can help you to debug.
https://www.diffchecker.com/x8wearbd

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/AlignmentHelpers.js, line 76 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-L4IS-pmbkxAXYbHmYFz:-L4J6bdMDT7p0RuKaEKw:b-89zwu9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41aa39766653fcc4cf827c9ac8ee2b37a1a4e7da/src/js/helpers/AlignmentHelpers.js#L76)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

It looks like it would be a direct replacement. Since verseObject is an array, we should be able to just do `verseObjects.forEach(verseObject => {...})`
</blockquote></details>

Yes, this could be simpler.  Think I did a bunch of refactoring.  Actually prefer using `for (let verseObject of verseObjects) {` since the debugger will automatically step into it.  `forEach(` requires you set a breakpoint inside the loop inside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by RoyalSix** [comment]
Reviewed 7 of 10 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by RoyalSix** [comment]
```LGTM```

**Comment by PhotoNomad0** [comment]
Can't reproduce what you are seeing, and it is passing on Travis.  Looking at the diff, it looks like you don't have the latest code.  Try pulling the branch again?

---

Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-:-L4J9IcwFJlKSySjxS-e:b8ttd4e)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3735#-:-L4LnHeoVBMqni_Yla9Y:bnfp4nl)*

**Pull request merged**
