### PR TITLE
Upload Project Message Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR address two things, the structure of the recent projects actions file and the order of actions dispatched for confirming and online action. 

#### How to test this pull request:
To test this PR try using the buttons in the project card and ensure working functionality.
CSV, and Upload Online were refactored into their own files so test those throughly.
Next make sure that the message displayed when a project is being uploading will show 'spinning tc icon'. This is the same message that shows when importing a project from online which should also be fixed now.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2272)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by klappy** [comment]
@royalsix: Looks good. Can you merge in latest develop? I'll test it after its updated.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-:-KpvdPOLedq8jni1DnIy:b-ktz9rs)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by RoyalSix** [comment]
Merged @klappy

**Comment by klappy** [comment]
*[src/js/components/login/Door43Login.js, line 2 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq-H-XuL83yT3VUdajf:-Kq-H-XuL83yT3VUdajg:bforc8a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c4741495eff25d24580ade3125925a9a06609a2/src/js/components/login/Door43Login.js#L2)):*
> ```JavaScript
> import React from 'react';
> var open = require("open");
> ```

can you use import for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 3 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq-H41iQQUDP-DoQsAy:-Kq-H41iQQUDP-DoQsAz:bforc8a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c4741495eff25d24580ade3125925a9a06609a2/src/js/components/home/usersManagement/Login.js#L3)):*
> ```JavaScript
> import React, { Component } from 'react'
> import { Glyphicon } from 'react-bootstrap';
> var open = require("open");
> ```

can you use import for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by mannycolon** [comment]
Reviewed 8 of 10 files at r1, 2 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[package-lock.json, line 0 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8fkY4rLpVVcco1xTH:-Kq8fkY4rLpVVcco1xTI:bljf09o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/package-lock.json#L0)):*
I thought we said we would add the `package-lock.json` to our `.gitignore`

---

*[src/js/actions/ProjectUploadActions.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8glq88zPXJ13RI1v2:-Kq8glq88zPXJ13RI1v3:b-gw87jl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/actions/ProjectUploadActions.js#L8)):*
> ```JavaScript
> import * as AlertModalActions from './AlertModalActions';
> import * as OnlineModeActions from './OnlineModeActions';
> import open from 'open';
> ```

whats the purpose to use open??



if the purpose is to open a link on  an external browser window (ex. Chrome) then you can do the following

import { shell } from 'electron';

shell.openExternal('url');

---

*[src/js/components/home/projectsManagement/MyProjects.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8hX4A5GJqvi_WZeAK:-Kq8hX4A5GJqvi_WZeAL:b-30otp3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/components/home/projectsManagement/MyProjects.js#L6)):*
> ```JavaScript
> import ProjectCard from './ProjectCard';
> 
> let MyProjects = (props) => {
> ```

how about we destruct this props like this

let MyProjects = ({
    myProjects,
    user
}) => {

---

*[src/js/components/home/usersManagement/Login.js, line 42 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8hsA5NaJ-p4G43S6v:-Kq8hsA5NaJ-p4G43S6w:bekpeix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/components/home/usersManagement/Login.js#L42)):*
> ```JavaScript
>   openDoor43AccountWindow() {
>     this.props.actions.confirmOnlineAction(() => {
>       open('https://git.door43.org/user/sign_up');
> ```

why are you changing this to open() ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by klappy** [comment]
*[package-lock.json, line  at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8fkY4rLpVVcco1xTH:-Kq8neEvBEuJd7gXoHEI:b-bhcfxq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/package-lock.json#L)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I thought we said we would add the `package-lock.json` to our `.gitignore`
</blockquote></details>

We had to undo this for builds. We need it. 
Also, if we all use the same NPM version `5.1.0` since it is required for builds, there are no issues like this. I will update with 5.1.0 and this issue goes away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by klappy** [comment]
*[package-lock.json, line  at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8fkY4rLpVVcco1xTH:-Kq8ns5p5pf4lR9rE5Ru:b-43ospy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/package-lock.json#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We had to undo this for builds. We need it. 
Also, if we all use the same NPM version `5.1.0` since it is required for builds, there are no issues like this. I will update with 5.1.0 and this issue goes away.

</blockquote></details>

`npm i -g npm@5.1.0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by klappy** [comment]
Can you update from latest develop branch and fix merge conflicts?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-:-Kq8oYoN6WSVTD8G0jz0:bjsdxzl)*

**Comment by RoyalSix** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ProjectUploadActions.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8glq88zPXJ13RI1v2:-Kq8t8TpspoLFFWLgSIW:b-g2tv2o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/actions/ProjectUploadActions.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

whats the purpose to use open??



if the purpose is to open a link on  an external browser window (ex. Chrome) then you can do the following

import { shell } from 'electron';

shell.openExternal('url');
</blockquote></details>

Addressed this

---

*[src/js/components/home/projectsManagement/MyProjects.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8hX4A5GJqvi_WZeAK:-Kq8t5Lkse3xAwIEQB56:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/components/home/projectsManagement/MyProjects.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how about we destruct this props like this

let MyProjects = ({
    myProjects,
    user
}) => {
</blockquote></details>

Done.

---

*[src/js/components/home/usersManagement/Login.js, line 3 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq-H41iQQUDP-DoQsAy:-Kq8t4SU0_dv3kOKZU4c:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b8521cf88d97ea85472c4fda76b1a587f8980762/src/js/components/home/usersManagement/Login.js#L3)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

can you use import for consistency?
</blockquote></details>

Done.

---

*[src/js/components/home/usersManagement/Login.js, line 42 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8hsA5NaJ-p4G43S6v:-Kq8rszMsiMBptzjuJ0k:b9foov5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/components/home/usersManagement/Login.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you changing this to open() ??
</blockquote></details>

the shell module in electron was having issues in the build. Something about being a native module to electron. I tried fixing it but I took longer debugging and tracing down the issue rather than just simply using a different module

---

*[src/js/components/login/Door43Login.js, line 2 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq-H-XuL83yT3VUdajf:-Kq8t3pfQNhlDKpXw8pG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b8521cf88d97ea85472c4fda76b1a587f8980762/src/js/components/login/Door43Login.js#L2)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

can you use import for consistency?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by RoyalSix** [comment]
Review status: 10 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ProjectUploadActions.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-Kq8glq88zPXJ13RI1v2:-Kq8vJF7W-zxSTBdAeOE:bn7tz44) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0c7f3bbf99123d4f54508c64e38fe5f3c05938e9/src/js/actions/ProjectUploadActions.js#L8)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Addressed this
</blockquote></details>

the shell module in electron was having issues in the build. Something about being a native module to electron. I tried fixing it but I took longer debugging and tracing down the issue rather than just simply using a different modul

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272)*

**Comment by RoyalSix** [comment]
Anything else I need to do for this PR?

---

Review status: 10 of 14 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-:-KqLSu4rChogLrQyXI1M:b-ohyhcp)*

**Comment by mannycolon** [comment]
@klappy ^^

**Comment by klappy** [comment]
I'm going to run npm install --save with npm 5.1.0 in hopes to minimize lines of code changed for package-lock.json

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2272#-:-KqZPzAYWzO61v1iCnAp:b-emhzpd)*

**Comment by klappy** [comment]
nvm, just saw it was already merged.

**Pull request merged**
