### PR TITLE
Created my projects FAB

### PR DESCRIPTION
**Pull request by mannycolon**
### This pull request addresses:

Created my projects FAB #1980

### How to test this pull request:

- Go to the `My Projects` section and click on the FAB on the bottom right. 
- Should open other FAB buttons which at this point shouldn't be functional.
- Each button should have label cards on the left as in the mockups

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2024)

### CODE REVIEW

**Comment by RoyalSix** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-:-KnuA_o3k7eesWF_xVO3:bnfp4nl)*

**Comment by RoyalSix** [comment]
This looks good to me @klappy

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-:-KnuAchsF1xahRqeX57G:b-3j4qw4)*

**Comment by klappy** [comment]
*[src/js/components/home/projectsManagement/ProjectsFAB.js, line 4 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-Knua445DXjgXOa0bRI8:-Knua445DXjgXOa0bRI9:b-3589wj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/02daa55c944e17d3012f8d885ae213cc2874e7bc/src/js/components/home/projectsManagement/ProjectsFAB.js#L4)):*
> ```JavaScript
> import {Glyphicon} from 'react-bootstrap';
> 
> let ProjectFAB = (props) => {
> ```

What's wrong with this being a stateless component? All of this can work with this instead of class ProjectFAB extends Component. It encourages us to keep it as light weight as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024)*

**Comment by klappy** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-:-KnuawW3vstXRTjxY488:bnfp4nl)*

**Comment by mannycolon** [comment]
@klappy 
to keep components as lightweight as possible we don't necessarily need to make them stateless components. we just have to try to not write any business logic in the component but in actions and if necessary in the containers.

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-:-KnufdyjiyKDLuO8lpk4:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/components/home/projectsManagement/ProjectsFAB.js, line 4 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024#-Knua445DXjgXOa0bRI8:-Knufm4Ye2sHVw3l_-U_:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/02daa55c944e17d3012f8d885ae213cc2874e7bc/src/js/components/home/projectsManagement/ProjectsFAB.js#L4)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

What's wrong with this being a stateless component? All of this can work with this instead of class ProjectFAB extends Component. It encourages us to keep it as light weight as possible.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2024)*

**Pull request merged**
