### PR TITLE
Bugfix 5351/Invalidation problems with footnotes

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fix for footnotes throwing off occurrences check.

#### Please include detailed Test instructions for your pull request:
- use steps in issue https://github.com/unfoldingWord-dev/translationCore/issues/5351
- should not see warning about selections invalidated when you open tW the second time.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5638)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (605de07)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-linux-x64-1.1.0-605de07.deb) is ready for download.
[macOS build 1.1.0 (605de07)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-macos-x64-1.1.0-605de07.dmg) is ready for download.
[Windows x64 build 1.1.0 (605de07)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x64-1.1.0-605de07.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (605de07)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x32-1.1.0-605de07.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fe6c41c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-linux-x64-1.1.0-fe6c41c.deb) is ready for download.
[macOS build 1.1.0 (fe6c41c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-macos-x64-1.1.0-fe6c41c.dmg) is ready for download.
[Windows x64 build 1.1.0 (fe6c41c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x64-1.1.0-fe6c41c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fe6c41c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x32-1.1.0-fe6c41c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fa49b5c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-linux-x64-1.1.0-fa49b5c.deb) is ready for download.
[macOS build 1.1.0 (fa49b5c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-macos-x64-1.1.0-fa49b5c.dmg) is ready for download.
[Windows x64 build 1.1.0 (fa49b5c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x64-1.1.0-fa49b5c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fa49b5c)](https://tc-builds.door43.org/build/bugfix-mcleanb-5351/translationCore-win-x32-1.1.0-fa49b5c.setup.exe) is ready for download.

**Review by richmahn — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5638)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @richmahn)

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5638#-:-LVdMKoS-Js6DVdwIcJi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
