### PR TITLE
updated tc-ui-toolkit to add truncation to long strings in menu

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #5097
- Adds the latest ui-toolkit updates that provide truncation support to long strings in the menu.

#### Please include detailed Test instructions for your pull request:
- See the issue for details.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5263)

### CODE REVIEW

**Comment by richmahn** [comment]
@neutrinog Should this cover all the requests of the issue? I am using your branch with tc-ui-toolkit 0.10.10 installed, but when I select long text in Matthew, the book name doesn't change to "mat 24:15" as the issue requested. Oddly I'm also not getting a popup when I hover over. It does, unlike if I do this in the develop branch, adds a ellipsis to the selected text, so I assume I have your changes.

screen shot 2018-10-18 at 8 05 15 am

**Comment by richmahn** [comment]
Per Manny's requests for GIFs:
selection_truncate

**Comment by da1nerd** [comment]
I don't know what you mean by book name, but yes this should add both an ellipses and a popup.

**Comment by da1nerd** [comment]
@richmahn which os are  you on?

**Comment by da1nerd** [comment]
I just added a few missing features in https://github.com/translationCoreApps/tc-ui-toolkit/pull/72

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @richmahn)

**Comment by mannycolon** [comment]
@richmahn I tried waiting for Travis but took too long if you get a chance to merge please do so. Already tested it.

**Comment by mannycolon** [comment]
@richmahn Never mind lol

**Comment by richmahn** [comment]
Ah, been waiting to test this, but glad you got it.

**Pull request merged**
