### PR TITLE
Added translationWords, Fixed Many USFM Workflow Issues

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR address issues with changing a usfm book / target language, and imported the same type of project, as well as merge conflicts.

#### How to test this pull request:
Try importing two projects with the same book / target language combination, you should not be able to.
Try importing a project with no book, and then enter a book that is already matching a projects book / target language combination.
Try the above with and without merge conflicts.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2971)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2971)*

**Comment by mannycolon** [comment]
@RoyalSix When importing the following new projects (Not in the projects folder) 

[abu_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1395567/abu_tit_text_reg.tstudio.zip)
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1395568/fr_tit_text_ulb.tstudio.zip)

I get the following alert "The project you selected already exists. Reimporting existing projects is not currently supported."

**Comment by mannycolon** [comment]
I imported the following project it worked fine [fr_eph_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1395581/fr_eph_text_reg.usfm.zip)

**Comment by RoyalSix** [comment]
@mannycolon It was a problem with tstudio projects...
It's fixed! :)

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2971)*

**Comment by mannycolon** [comment]
@RoyalSix Thanks. Good Job!

**Pull request merged**
