### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5312)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e30c86b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e30c86b.deb) is ready for download.
[macOS build 1.1.0 (e30c86b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e30c86b.dmg) is ready for download.
[Windows x64 build 1.1.0 (e30c86b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e30c86b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e30c86b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e30c86b.setup.exe) is ready for download.

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a6e916d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-a6e916d.deb) is ready for download.
[macOS build 1.1.0 (a6e916d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-a6e916d.dmg) is ready for download.
[Windows x64 build 1.1.0 (a6e916d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-a6e916d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a6e916d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-a6e916d.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@RoyalSix - looks like you approved, but didn't merge.  Should this have been merged into release-v1.0.2?

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (acbdef5)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-acbdef5.deb) is ready for download.
[macOS build 1.1.0 (acbdef5)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-acbdef5.dmg) is ready for download.
[Windows x64 build 1.1.0 (acbdef5)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-acbdef5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (acbdef5)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-acbdef5.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5312#-:-LPd7jVO8Xu2ZzRB-jjf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
