### PR TITLE
Simplified Authentication Process

### PR DESCRIPTION
**Pull request by RoyalSix**
Now we only need one auth file in the root (check slack)
Added api function call for developers to use auth
Also fixed minor issue with alert modal spacing

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/26)

### CODE REVIEW

**Comment by therealsamf** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[modules/lexical_check_module/Door43DataFetcher.js, line 19 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzicmKVWtN5Q1K_oBS:-KOziHVsfPfDwtkaheOP:b-jj7rr0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/lexical_check_module/Door43DataFetcher.js#L19)):_

> ``` JavaScript
> 
>   const AUTHENTICATION = window.ModuleApi.getAuthToken('git');
> ```

How does this work? You removed 'access_token='. Did you test this? Even if it's working I have a hard time believing it's actually making authenticated API calls

---

_[modules/lexical_check_module/translation_words/TranslationWordsFetcher.js, line 11 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzismnKSpDBBkfGUhL:-KOzismnKSpDBBkfGUhM:bhey2on) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/lexical_check_module/translation_words/TranslationWordsFetcher.js#L11)):_

> ``` JavaScript
> const GITHUB_API_URL = "https://api.github.com/repos/Door43/d43-en/contents/obe?ref=master",
>   REQUEST_FAILED = "Request failed",
>   AUTHENTICATION = window.ModuleApi.getAuthToken('git'),
> ```

Same thing here

---

_[modules/phrase_check_module/parsers/Door43DataFetcher.js, line 18 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzix-LgwR2uH2RZ6kS:-KOzix-LgwR2uH2RZ6kT:b76stq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/phrase_check_module/parsers/Door43DataFetcher.js#L18)):_

> ``` JavaScript
>   REQUEST_FAILURE = "HttpRequest failed";
> 
>   const AUTHENTICATION = window.ModuleApi.getAuthToken('git');
> ```

and same thing here

---

_[src/js/ModuleApi.js, line 301 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzj1mzWAFw8XgbKqC5:-KOzj1mzWAFw8XgbKqC6:brf99h0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/ModuleApi.js#L301)):_

> ``` JavaScript
>   }
> 
>   getAuthToken(type) {
> ```

This is inefficient. After the first time a token is read in it should be stored within the API, not reread every time

---

_[src/js/components/core/parsers/Door43DataFetcher.js, line 24 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzjX5BkcqYIkXGyhqJ:-KOzjX5CBLy_IvDaLrZi:b-puq7p0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/components/core/parsers/Door43DataFetcher.js#L24)):_

> ``` JavaScript
> class Door43DataFetcher {
>   contructor() {
>       this.AUTHENTICATION = window.ModuleApi.getAuthToken('git');
> ```

Same thing here as I've listed earlier... removing 'access_token=' is breaking it and I think you haven't tested by running the fetchdatas again. Maybe I'm completely wrong ... Also why did you move this into the class definition? Seemed okay as a constant outside of it

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by RoyalSix** [comment]
I did leave out the "access_token" accidentally , I tested it and it "worked".
After looking at your comments I tested it with gibberish text on new projects and it loads the fetch datas. 
I also tested with replacing the token with an empty string. 
Maybe door43 changed the permissions for reading from the TN/TW repos?

**Comment by therealsamf** [comment]
It must just ignore the anything after a '?' in the URL if it isn't valid. But if that 'access_token' isn't there then the calls won't be authenticated, so it still needs to be put back.

Also none of that is Door43, it's all Github. So I doubt door43 can do anything about changing the permissions associated with making authenticated API calls whether they're accessing a door43 repo or not

**Comment by RoyalSix** [comment]
Ok, I put it in the auth file that I uploaded to slack. Seems like it is better suited there anyway a developer doesn't really need to add that manually.
But its not authenticating regardless, looking into that now.

**Comment by klappy** [comment]
Does that mean it's currently working without authentication? Could that be because the repositories are public and not private? I may be missing not the point of the discussion above but if that is the case and we can get the data without proper authentication, should we not worry about proper authentication and avoid the need to distribute secret authentication files.

**Comment by RoyalSix** [comment]
I think thats a good idea, I just removed it.

---

Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/parsers/Door43DataFetcher.js, line 24 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzjX5BkcqYIkXGyhqJ:-KOzljEHwrv_aO1E3IpN:b-9k9ye0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/components/core/parsers/Door43DataFetcher.js#L24)):_
<details><summary>

<i>Previously, therealsamf wrote…</i></summary>



> Same thing here as I've listed earlier... removing 'access_token=' is breaking it and I think you haven't tested by running the fetchdatas again. Maybe I'm completely wrong ... Also why did you move this into the class definition? Seemed okay as a constant outside of it
> </details>
> I had it as a constant at first, for some reason the api was not being compiled until after this file, so it would come up as undefinded. I also changed the order of requires in app.js, but same result.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-:-KPE6OO9VkvJTlTLsys9:blrenw7)_

**Comment by RoyalSix** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[modules/lexical_check_module/Door43DataFetcher.js, line 19 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzicmKVWtN5Q1K_oBS:-KPEELoULPtUhniZZynU:bq2wdhq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/lexical_check_module/Door43DataFetcher.js#L19)):_
<details><summary>

<i>Previously, therealsamf wrote…</i></summary>



> How does this work? You removed 'access_token='. Did you test this? Even if it's working I have a hard time believing it's actually making authenticated API calls
> </details>
> because I have faith.

---

_[src/js/ModuleApi.js, line 301 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzj1mzWAFw8XgbKqC5:-KPEEY1fxO0l3gdPifbN:b-9eqd6o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/ModuleApi.js#L301)):_
<details><summary>

<i>Previously, therealsamf wrote…</i></summary>



> This is inefficient. After the first time a token is read in it should be stored within the API, not reread every time
> </details>
> I disagree, it will only be read on a new project, which is just when it needs to be.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by therealsamf** [comment]
We need the authenticated API calls or else we'll run out of calls per hour. We ran into this problem during the summer before we had the authentication. Unauthenticated calls gives you 60 per hour, with authenticated you get 1000 or 10000  I forget. So it might work for one project, but if you switched within an hour you should run out of calls from the same machine. https://developer.github.com/v3/#rate-limiting

**Comment by therealsamf** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/ModuleApi.js, line 301 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzj1mzWAFw8XgbKqC5:-KPEk-o3ZKWJYr-e5Qa-:b-sfzyzp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/ModuleApi.js#L301)):_
<details><summary>

<i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary>



> I disagree, it will only be read on a new project, which is just when it needs to be.
> </details>
> Everytime this method is called it rereads the file. Should only do it once. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by RoyalSix** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[modules/lexical_check_module/Door43DataFetcher.js, line 19 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzicmKVWtN5Q1K_oBS:-KPEoQODJNL7MovJzSY8:bcajxz8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/lexical_check_module/Door43DataFetcher.js#L19)):_
<details><summary>

<i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary>



> because I have faith.
> </details>
> I added this information to the JSON instead

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by RoyalSix** [comment]
Review status: 5 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/ModuleApi.js, line 301 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzj1mzWAFw8XgbKqC5:-KPEtLbdYXXmaNFGOlgF:btdsfzr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/src/js/ModuleApi.js#L301)):_
<details><summary>

<i>Previously, therealsamf wrote…</i></summary>



> Everytime this method is called it rereads the file. Should only do it once. 
> </details>
> I see.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by therealsamf** [comment]
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/js/components/core/Upload.js, line 205 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KPF1VXalxcT36gkWuwR:-KPF1VXalxcT36gkWuwS:b-30ewth) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1310b6581c3a3395219148e9aaadfda7fcf4b097/src/js/components/core/Upload.js#L205)):_

> ``` JavaScript
>     //this currently just uses 'require' and if it throws an error it will return false
>     try {
>       fs.accessSync(Path.join(path, 'tc-manifest.json'));
> ```

I think git is being stupid and didn't merge the latest develop correct with your branch. This is the method that should be used

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by klappy** [comment]
Thanks to both of you for your thorough work on this. How much do you feel is left before this can be merged?

**Comment by klappy** [comment]
I'm doing some testing from this branch and it sure is a huge improvement on getting the project up and running. I actually just typed `touch .auth` to generate a blank file and so far everything appears to load. Although the progress bar when loading modules doesn't appear to work at the moment. It looks stuck at the beginning but when looking at the network tab of the inspector, it shows files being downloaded.

**Comment by therealsamf** [comment]
Hmm, I think only a few minor changes remain, then I can test it and look into that issue @klappy . I'll ping Jay and let him know I reviewed the PR again

**Comment by EllDoubleYew** [comment]
As far as rate limits are concerned, is this still an issue now that we save all of our data in local storage after the initial load? Ideally our FetchData.js will only be called once when you first initialize your project. For reference, @therealsamf do you know how many API calls are made in the tW fetchdata?

**Comment by EllDoubleYew** [comment]
Reviewed 2 of 10 files at r1.
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Comment by EllDoubleYew** [comment]
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

_[modules/lexical_check_module/Door43DataFetcher.js, line 19 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26#-KOzicmKVWtN5Q1K_oBS:-KPKSfNMeegBZ0TJNgjU:b-naarpa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbe3664472c43bfe52b2b443d3730793c1f0b527/modules/lexical_check_module/Door43DataFetcher.js#L19)):_
<details><summary>

<i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary>



> I added this information to the JSON instead
> </details>
> Do we want the 'access_token=' in the json or in the file here? I honestly don't know which way makes more sense.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/26)_

**Pull request merged**
