### PR TITLE
Migrate concourse tasks to GitHub actions

### PR DESCRIPTION
**Pull request by da1nerd**
This PR provides a [GitHub actions](https://help.github.com/en/actions) alternative to our concourse CI server.

Things to be completed before this PR is ready:
* [x] Execute tests
* ~[ ] clean up action interface (inputs/outputs)~
* [x] Build application
  * [x] Read github environment variables
  * [x] Configure secrete keys
* [x] Upload builds
* ~[ ] Post build links in PR comment.~
* ~[ ] Put target platforms into build matrix~
* [x] Rename `.github/workflows/nodejs.yml` to `.github/workflows/main.yml`
* ~[ ] Rename `.github/actions/build` to `.github/actions/environment`~
* [x] Send notifications to Zulip
  * [x] PRs
  * [x] Merges into master
  * [x] Merges into develop
* [x] When the time is right, please squash this PR so the noisy history doesn't drive the other developers crazy.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6512)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (eaf128b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-eaf128b.deb) is ready for download.
[macOS build 2.0.0 (eaf128b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-eaf128b.dmg) is ready for download.
[Windows x64 build 2.0.0 (eaf128b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-eaf128b.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (eaf128b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-eaf128b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1348ae6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-1348ae6.deb) is ready for download.
[macOS build 2.0.0 (1348ae6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-1348ae6.dmg) is ready for download.
[Windows x64 build 2.0.0 (1348ae6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-1348ae6.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1348ae6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-1348ae6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (29fbe42)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-29fbe42.deb) is ready for download.
[macOS build 2.0.0 (29fbe42)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-29fbe42.dmg) is ready for download.
[Windows x64 build 2.0.0 (29fbe42)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-29fbe42.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (29fbe42)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-29fbe42.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b3fd0cf)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-b3fd0cf.deb) is ready for download.
[macOS build 2.0.0 (b3fd0cf)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-b3fd0cf.dmg) is ready for download.
[Windows x64 build 2.0.0 (b3fd0cf)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-b3fd0cf.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b3fd0cf)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-b3fd0cf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (ee8a088)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-ee8a088.deb) is ready for download.
[macOS build 2.0.0 (ee8a088)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-ee8a088.dmg) is ready for download.
[Windows x64 build 2.0.0 (ee8a088)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-ee8a088.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (ee8a088)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-ee8a088.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (76c9da1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-76c9da1.deb) is ready for download.
[macOS build 2.0.0 (76c9da1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-76c9da1.dmg) is ready for download.
[Windows x64 build 2.0.0 (76c9da1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-76c9da1.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (76c9da1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-76c9da1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (09d7dc9)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-09d7dc9.deb) is ready for download.
[macOS build 2.0.0 (09d7dc9)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-09d7dc9.dmg) is ready for download.
[Windows x64 build 2.0.0 (09d7dc9)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-09d7dc9.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (09d7dc9)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-09d7dc9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (98d28d1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-98d28d1.deb) is ready for download.
[macOS build 2.0.0 (98d28d1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-98d28d1.dmg) is ready for download.
[Windows x64 build 2.0.0 (98d28d1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-98d28d1.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (98d28d1)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-98d28d1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (f5df324)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-f5df324.deb) is ready for download.
[macOS build 2.0.0 (f5df324)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-f5df324.dmg) is ready for download.
[Windows x64 build 2.0.0 (f5df324)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-f5df324.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (f5df324)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-f5df324.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (93a2952)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-93a2952.deb) is ready for download.
[macOS build 2.0.0 (93a2952)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-93a2952.dmg) is ready for download.
[Windows x64 build 2.0.0 (93a2952)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-93a2952.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (93a2952)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-93a2952.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (182ad82)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-182ad82.deb) is ready for download.
[macOS build 2.0.0 (182ad82)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-182ad82.dmg) is ready for download.
[Windows x64 build 2.0.0 (182ad82)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-182ad82.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (182ad82)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-182ad82.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (def30c7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-def30c7.deb) is ready for download.
[macOS build 2.0.0 (def30c7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-def30c7.dmg) is ready for download.
[Windows x64 build 2.0.0 (def30c7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-def30c7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (def30c7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-def30c7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c0fec4a)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-c0fec4a.deb) is ready for download.
[macOS build 2.0.0 (c0fec4a)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-c0fec4a.dmg) is ready for download.
[Windows x64 build 2.0.0 (c0fec4a)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-c0fec4a.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c0fec4a)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-c0fec4a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (2b02b7f)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-2b02b7f.deb) is ready for download.
[macOS build 2.0.0 (2b02b7f)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-2b02b7f.dmg) is ready for download.
[Windows x64 build 2.0.0 (2b02b7f)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-2b02b7f.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (2b02b7f)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-2b02b7f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (68a2fea)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-68a2fea.deb) is ready for download.
[macOS build 2.0.0 (68a2fea)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-68a2fea.dmg) is ready for download.
[Windows x64 build 2.0.0 (68a2fea)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-68a2fea.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (68a2fea)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-68a2fea.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a032428)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-a032428.deb) is ready for download.
[macOS build 2.0.0 (a032428)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-a032428.dmg) is ready for download.
[Windows x64 build 2.0.0 (a032428)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-a032428.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a032428)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-a032428.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (87c41a7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-87c41a7.deb) is ready for download.
[macOS build 2.0.0 (87c41a7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-87c41a7.dmg) is ready for download.
[Windows x64 build 2.0.0 (87c41a7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-87c41a7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (87c41a7)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-87c41a7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (9d74c76)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-9d74c76.deb) is ready for download.
[macOS build 2.0.0 (9d74c76)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-9d74c76.dmg) is ready for download.
[Windows x64 build 2.0.0 (9d74c76)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-9d74c76.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (9d74c76)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-9d74c76.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (5024bc4)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-5024bc4.deb) is ready for download.
[macOS build 2.0.0 (5024bc4)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-5024bc4.dmg) is ready for download.
[Windows x64 build 2.0.0 (5024bc4)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-5024bc4.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (5024bc4)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-5024bc4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (054bf83)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-054bf83.deb) is ready for download.
[macOS build 2.0.0 (054bf83)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-054bf83.dmg) is ready for download.
[Windows x64 build 2.0.0 (054bf83)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-054bf83.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (054bf83)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-054bf83.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (14f05a2)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-14f05a2.deb) is ready for download.
[macOS build 2.0.0 (14f05a2)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-14f05a2.dmg) is ready for download.
[Windows x64 build 2.0.0 (14f05a2)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-14f05a2.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (14f05a2)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-14f05a2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (67e8b26)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-67e8b26.deb) is ready for download.
[macOS build 2.0.0 (67e8b26)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-67e8b26.dmg) is ready for download.
[Windows x64 build 2.0.0 (67e8b26)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-67e8b26.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (67e8b26)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-67e8b26.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (6bee660)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-6bee660.deb) is ready for download.
[macOS build 2.0.0 (6bee660)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-6bee660.dmg) is ready for download.
[Windows x64 build 2.0.0 (6bee660)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-6bee660.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (6bee660)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-6bee660.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
test comment

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1e8549b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-1e8549b.deb) is ready for download.
[macOS build 2.0.0 (1e8549b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-1e8549b.dmg) is ready for download.
[Windows x64 build 2.0.0 (1e8549b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-1e8549b.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1e8549b)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-1e8549b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (bd9b6b6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-linux-x64-2.0.0-bd9b6b6.deb) is ready for download.
[macOS build 2.0.0 (bd9b6b6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-macos-x64-2.0.0-bd9b6b6.dmg) is ready for download.
[Windows x64 build 2.0.0 (bd9b6b6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x64-2.0.0-bd9b6b6.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (bd9b6b6)](https://tc-builds.door43.org/build/concourse-to-actions/translationCore-win-x32-2.0.0-bd9b6b6.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6512)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
