### PR TITLE
Removed all unused reducers, actions etc that was moved to tools' codebases

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Test & merge w/ https://github.com/unfoldingWord/wordAlignment/pull/248
- Make sure all verse edit actions work correctly for wA tool
- Make editing a verse in tN, & tW tools still work correctly
- Make sure all tools work correctly 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6683)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 32 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6683)* status: 32 of 48 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/helpers/ProjectOverwriteHelpers.js, line 188 at r1](https://reviewable.io/reviews/unfoldingword/translationcore/6683#-M0NpwLb1fQJ0DvQ98UD:-M0NpwLb1fQJ0DvQ98UE:b-qdi1sv) ([raw file](https://github.com/unfoldingword/translationcore/blob/771e0776029fd6d4df6219655291bbe9bee8ae78/src/js/helpers/ProjectOverwriteHelpers.js#L188)):*
> ```JavaScript
>     console.log('====================================');
>     console.log('groupsData', groupsData);
>     console.log('====================================');
> ```

Is this still needed?

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 15 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6683)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6683)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/helpers/ProjectOverwriteHelpers.js, line 188 at r1](https://reviewable.io/reviews/unfoldingword/translationcore/6683#-M0NpwLb1fQJ0DvQ98UD:-M0NqscI8yvmXUHMMdKd:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/771e0776029fd6d4df6219655291bbe9bee8ae78/src/js/helpers/ProjectOverwriteHelpers.js#L188)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Is this still needed?
</blockquote></details>

Done.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6683)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
