### PR TITLE
Bug fix/mcleanb/2715/windows import fix (QA fail)

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

A Fix for Windows so that the local import file dialog stays modal: background is dimmed and cannot click off file dialog.

- had to change to use ipcRenderer.sendSync() for dialog to be modal on windows.
- had to put dim screen call before toggle FABs to get screen to go dark on windows.

#### How to test this pull request:

On Windows select import a local project, the main screen should be dimmed, but when you click on the FAB, the file Explorer should stay in front.  Verify that import cancel still works, and then verify that file import still works.
On Mac should see same behavior as above.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3201)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3201)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3201#-:-Kz4UhlXujVrYM5vwf80:bnfp4nl)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Code looks good now testing on my local.

**Comment by mannycolon** [comment]
This branch doesn't work on mac. It may or may not be your fault.

**Comment by mannycolon** [comment]
@PhotoNomad0 when was the last time you merged with develop?

**Comment by mannycolon** [comment]
@PhotoNomad0 I merged develop into your branch and now the app opens. it would not open on a Mac before merging with develop branch.

**Comment by mannycolon** [comment]
I loaded a project from local and since I already have that project the alert below should say so but instead, I get a blank alert.
screen shot 2017-11-16 at 11 03 53 am 2

**Comment by mannycolon** [comment]
I loaded a local project that was previously loaded in tC and I got the alert below instead of **the alert saying reimporting projects is not allowed**
screen shot 2017-11-16 at 11 03 53 am

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3201)*

**Comment by PhotoNomad0** [comment]
@mannycolon - think I have the blank alert fixed now.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3201)*

**Pull request merged**
