### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4625)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (50817ed)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-50817ed.zip) is ready for download.
[macOS build 0.10.0 (50817ed)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-50817ed.dmg) is ready for download.
[Windows x64 build 0.10.0 (50817ed)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-50817ed.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (50817ed)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-50817ed.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (0425026)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-0425026.zip) is ready for download.
[macOS build 0.10.0 (0425026)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-0425026.dmg) is ready for download.
[Windows x64 build 0.10.0 (0425026)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-0425026.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (0425026)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-0425026.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
I've updated the locale in Crowdin so this PR is now safe to merge in.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (7c0ac92)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7c0ac92.zip) is ready for download.
[macOS build 0.10.0 (7c0ac92)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7c0ac92.dmg) is ready for download.
[Windows x64 build 0.10.0 (7c0ac92)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-7c0ac92.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (7c0ac92)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-7c0ac92.setup.exe) is ready for download.

**Pull request merged**
