### PR TITLE
Attempt to fix Intermittent text in menu bar

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Attempt to fix Intermittent text in menu bar

#### How to test this pull request:
- I could not recreate the bug. so hard to test this issue only @cckozie encounters this bug on his machine.

- Just open both tools and make sure I did not break the top menu bar.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3736)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package-lock.json, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JBp05Bc-kilTvq_54:-L4JBp05Bc-kilTvq_55:bb1a871) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/package-lock.json#L1)):*
> ```JSON
> {
> ```

Necessary to change the package-lock?

---

*[src/css/styles.css, line 309 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JCDGOOU7ek2QkPzkO:-L4JCDGOOU7ek2QkPzkP:bsrykwg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/src/css/styles.css#L309)):*
> ```CSS
>   overflow: visible;
>   box-shadow: none;
>   left: -31415px;
> ```

Not saying this isn't the way to do it, just wondering why ```-31415px``` for the left property?

---

*[src/js/components/StatusBar.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JCTuWrnBGIC-4GNti:-L4JCTuWrnBGIC-4GNtj:bb70w76) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/src/js/components/StatusBar.js#L14)):*
> ```JavaScript
>   }
> 
>   componentDidCatch(error, info) {
> ```

Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736)*

**Comment by RoyalSix** [comment]
Tested the app and works good.

**Comment by mannycolon** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package-lock.json, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JBp05Bc-kilTvq_54:-L4SxmqJWjWfQkX4jNt-:bjxtsp9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/package-lock.json#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Necessary to change the package-lock?
</blockquote></details>

This is a result of running `npm i`

---

*[src/css/styles.css, line 309 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JCDGOOU7ek2QkPzkO:-L4SyHdtpRwo1gEoEsv6:bed2d37) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/src/css/styles.css#L309)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Not saying this isn't the way to do it, just wondering why ```-31415px``` for the left property?
</blockquote></details>

Its just way to make sure nothing else messes with it. this is a fix found online for this.

---

*[src/js/components/StatusBar.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-L4JCTuWrnBGIC-4GNti:-L4Sy4O8gOq66VSuP_nI:b-3duiwv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6850da45fdb2fcac911d60a824aa8057e6201d8/src/js/components/StatusBar.js#L14)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Nice
</blockquote></details>

haha just adding some react 16 features 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736)*

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3736#-:-L4bL6BcWfC-E8bemEbL:bnfp4nl)*

**Pull request merged**
