### PR TITLE
Moves all DCS URL references to a constant

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Changes tC to use a constant for the DCS Base URL and form URLs and RegExps from that

#### Please include detailed Test instructions for your pull request:
- Test that all features of DCS work: login, search, download (both from search results and a git.door43.org URL), upload.
- Test that you can change git.door43.org in constants.js to bg.door43.org, make a new user and repo on bg.door43.org and makes sure all works the same on that test server as it would on the main git server.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6524)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1cae2ad)](https://tc-builds.door43.org/build/richmahn-dcs-constant/translationCore-linux-x64-2.0.0-1cae2ad.deb) is ready for download.
[macOS build 2.0.0 (1cae2ad)](https://tc-builds.door43.org/build/richmahn-dcs-constant/translationCore-macos-x64-2.0.0-1cae2ad.dmg) is ready for download.
[Windows x64 build 2.0.0 (1cae2ad)](https://tc-builds.door43.org/build/richmahn-dcs-constant/translationCore-win-x64-2.0.0-1cae2ad.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1cae2ad)](https://tc-builds.door43.org/build/richmahn-dcs-constant/translationCore-win-x32-2.0.0-1cae2ad.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6524)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
@richmahn - seeing problems with upload. I logged into bg.door43.org.  Downloaded a project and then uploaded the project and see:

Screen Shot 2019-11-05 at 8 06 35 AM

**Comment by PhotoNomad0** [comment]
@richmahn - Looks like this was missed: https://github.com/unfoldingWord/translationCore/blob/richmahn-dcs-constant/src/js/helpers/GogsApiHelpers.js#L8

and probably this also:
https://github.com/unfoldingWord/translationCore/blob/richmahn-dcs-constant/src/js/components/home/usersManagement/pages/CreativeCommonsPage.js#L50

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6524)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
