### PR TITLE
Bundle git with application

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This is related to #4960
- Updates the application to use isomorphic git instead of relying on a natively installed version.
- Resolves missing dependency that ended up containing malware. See https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/

#### Please include detailed Test instructions for your pull request:
- Test anything relating to git operations such as upload, download, rename, etc.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494)

### CODE REVIEW

**Comment by da1nerd** [comment]
Wow! I found one of the new dependencies has malware `flatmap-stream`. Trying to figure out which one has it so I can get a working alternative.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (39eae2b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-39eae2b.deb) is ready for download.
[macOS build 1.1.0 (39eae2b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-39eae2b.dmg) is ready for download.
[Windows x64 build 1.1.0 (39eae2b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-39eae2b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (39eae2b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-39eae2b.setup.exe) is ready for download.

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> Reviewed 35 of 39 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494#-:-LSVptCO3ogc2esXNq_g:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 36 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494#-LSVpVT_6iAVI-O8Xuok:-LSVpVT_6iAVI-O8Xuol:boqevil) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c041ab3670e1427709afbe9cba94ca8dd78cd494/src/js/actions/Import/ProjectImportFilesystemActions.js#L36)):*
> ```JavaScript
> 
> /**
>  * Deletes a project from the imports folder
> ```

Why did you remove this code?

**Comment by mannycolon** [comment]
Please resolve merge conflict with package-lock.json

**Comment by da1nerd** [comment]
Testing results so far.

* [ ] windows 32bit 
* [x] windows 64bit
* [x] macos
* [x] linux

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4c4b38a)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-4c4b38a.deb) is ready for download.
[macOS build 1.1.0 (4c4b38a)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-4c4b38a.dmg) is ready for download.
[Windows x64 build 1.1.0 (4c4b38a)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-4c4b38a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4c4b38a)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-4c4b38a.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Testing on Win64 and got an error:
```
2ProjectUploadActions.js:86 TypeError: Cannot read property 'split' of null
    at new GitConfig (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:1195:30)
    at Function.from (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:1217:12)
    at Function.get (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:1327:22)
    at process._tickCallback (internal/process/next_tick.js:68)
(anonymous) @ ProjectUploadActions.js:86
```

to reproduce:
- did USFM import of Jeremiah
- selected to upload to D43
- got prompt to allow internet access.
- clicked on continue
- screen locked up for about 20 seconds and then got an error message about the split above.

**Comment by PhotoNomad0** [comment]
Also tried downloading a project from my repo, changed target identifier, and then tried to upload.  Got this error:

```
WordAlignmentActions.js:44 TypeError: Cannot read property 'indexOf' of undefined
    at C:/Program Files (x86)/translationCore/resources/app.asar/src/js/helpers/WordAlignmentHelpers.js:151:45
    at new Promise (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\es6.promise.js:177:7)
    at Object.convertAlignmentDataToUSFM (C:/Program Files (x86)/translationCore/resources/app.asar/src/js/helpers/WordAlignmentHelpers.js:130:10)
    at C:/Program Files (x86)/translationCore/resources/app.asar/src/js/actions/WordAlignmentActions.js:22:45
    at new Promise (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\es6.promise.js:177:7)
    at C:/Program Files (x86)/translationCore/resources/app.asar/src/js/actions/WordAlignmentActions.js:17:12
    at C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux-thunk\lib\index.js:11:18
    at dispatch (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux\lib\applyMiddleware.js:45:18)
    at C:/Program Files (x86)/translationCore/resources/app.asar/src/js/actions/ProjectUploadActions.js:38:19
    at C:/Program Files (x86)/translationCore/resources/app.asar/src/js/actions/OnlineModeConfirmActions.js:40:12
(anonymous) @ WordAlignmentActions.js:44
run @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\es6.promise.js:75
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\es6.promise.js:92
flush @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\_microtask.js:18
_tickCallback @ internal/process/next_tick.js:61
ProjectUploadActions.js:86 GitError: Could not read file "C:\Users\blm\translationCore\projects\yab_zzzz_mrk_book\LICENSE.md".
    at Object.add (C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:1047:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(anonymous) @ ProjectUploadActions.js:86
_tickCallback @ internal/process/next_tick.js:68
async function (async)
(anonymous) @ ProjectUploadActions.js:29
(anonymous) @ OnlineModeConfirmActions.js:40
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux-thunk\lib\index.js:11
dispatch @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectUploadActions.js:29
Promise @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\modules\es6.promise.js:177
(anonymous) @ ProjectUploadActions.js:22
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux-thunk\lib\index.js:11
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\redux\lib\bindActionCreators.js:7
onClick @ Menu.js:95
callCallback @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:100
invokeGuardedCallbackDev @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:138
invokeGuardedCallback @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:201
executeDispatch @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:466
executeDispatchesInOrder @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:488
executeDispatchesAndRelease @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:597
forEachAccumulated @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:567
runEventsInBatch @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:728
runExtractedEventsInBatch @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:737
handleTopLevel @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4201
batchedUpdates @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12537
batchedUpdates @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1939
dispatchEvent @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4282
interactiveUpdates @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12592
interactiveUpdates @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:1958
dispatchInteractiveEvent @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4259
```

**Review by mannycolon — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
Seeing same upload errors on Mac:

downloaded https://git.door43.org/photonomad1/yab_mrk_text_reg
changed translation identifier at the prompt
then uploaded.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0f688b1)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-0f688b1.deb) is ready for download.
[macOS build 1.1.0 (0f688b1)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-0f688b1.dmg) is ready for download.
[Windows x64 build 1.1.0 (0f688b1)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-0f688b1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0f688b1)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-0f688b1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ee707a7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-ee707a7.deb) is ready for download.
[macOS build 1.1.0 (ee707a7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-ee707a7.dmg) is ready for download.
[Windows x64 build 1.1.0 (ee707a7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-ee707a7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ee707a7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-ee707a7.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
In the process of getting things working I did discover some bugs with the project renaming, but those existed before so I'll open a separate issue.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (5c465c7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-5c465c7.deb) is ready for download.
[macOS build 1.1.0 (5c465c7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-5c465c7.dmg) is ready for download.
[Windows x64 build 1.1.0 (5c465c7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-5c465c7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (5c465c7)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-5c465c7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cdbf60b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-cdbf60b.deb) is ready for download.
[macOS build 1.1.0 (cdbf60b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-cdbf60b.dmg) is ready for download.
[Windows x64 build 1.1.0 (cdbf60b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-cdbf60b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cdbf60b)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-cdbf60b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a92e304)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-linux-x64-1.1.0-a92e304.deb) is ready for download.
[macOS build 1.1.0 (a92e304)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-macos-x64-1.1.0-a92e304.dmg) is ready for download.
[Windows x64 build 1.1.0 (a92e304)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x64-1.1.0-a92e304.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a92e304)](https://tc-builds.door43.org/build/enhancement_joel_4960_bundle-git/translationCore-win-x32-1.1.0-a92e304.setup.exe) is ready for download.

**Review by mannycolon — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 3 of 5 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

**Review by mannycolon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5494#-:-LSvXkK89QWvFHUF3_5E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

**Pull request merged**
