### PR TITLE
Updated Resource Helpers for Greek tW

### PR DESCRIPTION
**Pull request by klappy**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Copies Greek tW Groups data to the user resources path when launching app.
- Copies Greek tW Groups data to the project's resource path when launching the tool.

#### Please include detailed Test instructions for your pull request:
- Either import new Project or Delete `./.apps/translationCore/index/translationWords` path in the project.
- Open project and tW tool and make sure checks are based off of the Greek.
- You can know for sure by looking in the `./.apps/translationCore/index/translationWords` path in the project look in the .json files for greek quotes.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3838)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/helpers/ResourcesHelpers.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0YAbGRBvvvYmaXo7:-L5Q0YAbGRBvvvYmaXo8:b-gsj2pa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L18)):*
> ```JavaScript
>       const STATIC_RESOURCES_BIBLES_PATH = path.join(STATIC_RESOURCES_PATH, languagesId, 'bibles');
>       const BIBLE_RESOURCES_PATH = path.join(USER_RESOURCES_PATH, languagesId, 'bibles');
>       let bibleNames = fs.readdirSync(STATIC_RESOURCES_BIBLES_PATH).filter(folder => { // filter out .DS_Store
> ```

We no longer need to filter out `.DS_Store`?

---

*[src/js/helpers/ResourcesHelpers.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0iQD0EM9iPH_ZOSh:-L5Q0iQD0EM9iPH_ZOSi:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L42)):*
> ```JavaScript
>     const staticTranslationHelpsPath = path.join(STATIC_RESOURCES_PATH, languageId, 'translationHelps');
>     const userTranslationHelpsPath = path.join(USER_RESOURCES_PATH, languageId, 'translationHelps');
>     const tHelpsNames = fs.readdirSync(staticTranslationHelpsPath).filter(folder => { // filter out .DS_Store
> ```

ibid

---

*[src/js/helpers/ResourcesHelpers.js, line 65 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0ltUQpfITISDjJ_H:-L5Q0ltUQpfITISDjJ_I:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L65)):*
> ```JavaScript
>     const staticPath = path.join(STATIC_RESOURCES_PATH, languageId, 'lexicons');
>     const userPath = path.join(USER_RESOURCES_PATH, languageId, 'lexicons');
>     const folders = fs.readdirSync(staticPath).filter(folder => { // filter out .DS_Store
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Comment by klappy** [comment]
*[src/js/helpers/ResourcesHelpers.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0YAbGRBvvvYmaXo7:-L5QMLLBMCk6p0QQaGmL:b-eem2gh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L18)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

We no longer need to filter out `.DS_Store`?
</blockquote></details>

It wasn't doing what we thought it was. Filtering out the .DS_Store filters out files, in this case we are only looking at directories. The .DS_Store files that were an issue were deeper in the path and not at this level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Comment by klappy** [comment]
*[src/js/helpers/ResourcesHelpers.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0iQD0EM9iPH_ZOSh:-L5QMjJCfXgboWI4_8HJ:b2nreh6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Comment by klappy** [comment]
*[src/js/helpers/ResourcesHelpers.js, line 65 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0ltUQpfITISDjJ_H:-L5QMvJ780RA6l4mUaUO:b2nreh6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L65)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/helpers/ResourcesHelpers.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838#-L5Q0YAbGRBvvvYmaXo7:-L5QNEaDw8Hz3hdzLlxH:bkegu8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/20796636510248e3d313c7d426733b48d3f9fab7/src/js/helpers/ResourcesHelpers.js#L18)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

It wasn't doing what we thought it was. Filtering out the .DS_Store filters out files, in this case we are only looking at directories. The .DS_Store files that were an issue were deeper in the path and not at this level.
</blockquote></details>

Yeah, this seems to be ok to no longer need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Comment by richmahn** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3838)*

**Pull request merged**
