### PR TITLE
Previous and next buttons removal

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/461)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/461)*

**Comment by ihoegen** [comment]
Is there a reason to keep the next and previous button files in the repo?

**Comment by mannycolon** [comment]
@ihoegen I  removed the  next and previous button files

**Comment by ihoegen** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/461)*

**Pull request merged**
