### PR TITLE
Sort check apps

### PR DESCRIPTION
**Pull request by lancelebanoff**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/23)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/SwitchCheckModal.js, line 39 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-KOwSRxstRyQgR7lGnda:-KOwSRxstRyQgR7lGndb:boeg8de) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/05f279b48623c69d39db7ae55ce476834af65eba/src/js/components/core/SwitchCheckModal.js#L39)):_

> ``` JavaScript
>     this.getDefaultModules((moduleFolderPathList) => {
>       _this.fillDefaultModules(moduleFolderPathList, (metadatas) => {
>         this.sortMetadatas(metadatas);
> ```

different "this" context? I'm assuming this was purposefully but just wanted to check

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23)_

**Comment by RoyalSix** [comment]
So this index is up to the developer? What if two developers want their index as 1?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KOwT1zdzL1hY4OSfiys:bysj6gt)_

**Comment by lancelebanoff** [comment]
This is a bit of a problem. I'm thinking that we're going to pre-package these 3 apps as "default" apps, and these will be ordered at the top of the list. Any other apps created by developers will be at the bottom of the list. If anybody has better ideas, that would be nice.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/SwitchCheckModal.js, line 39 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-KOwSRxstRyQgR7lGnda:-KOxESSx9zhprjEHno88:b9igorz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/05f279b48623c69d39db7ae55ce476834af65eba/src/js/components/core/SwitchCheckModal.js#L39)):_
<details><summary>

<i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary>



> different "this" context? I'm assuming this was purposefully but just wanted to check
> </details>
> Oh snap! No, I wanted it to be "_this". How the heck did this work when I tested it?! haha

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KOxDbB6tgYrKamVnN-s:bitfc5g)_

**Comment by therealsamf** [comment]
I would suggest just sorting alphabetically by the module's name. It's intuitive

**Comment by lancelebanoff** [comment]
Then, the Example Checker would be first, and I feel like that would confuse most first-time users.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KOzFLoMIY68x7DASe93:b3mgzvd)_

**Comment by klappy** [comment]
This conversation seems to touch on a discussion on another issue that spawned a new task...
https://github.com/unfoldingWord-dev/translationCore/issues/27

The goal is to eventually get tC to be app/module-less at least as far as the repo is concerned. We may have a way for apps to be bundled with the app upon build, but we need to extract them from the core's codebase.

**Comment by lancelebanoff** [comment]
I suppose this issue can wait until we've moved all of the apps to their own repos then.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KP0YezM8F-7l72M13H3:b-3l8g14)_

**Comment by klappy** [comment]
Can we modify it to at least to have some order, that way it isn't seemingly random each time it loads? 

Alphabetical or by last used time stamp makes sense to me. That way we do get a sort and it works for future plans. Would that be hard to modify your current code to do either one of those Lance?

**Comment by lancelebanoff** [comment]
Sure, I can make it sort by last used time stamp, and alphabetical if there are no time stamps. Shouldn't be too hard.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KP3FWHM04vV3xPYRGcI:b-yp0prk)_

**Comment by lancelebanoff** [comment]
Never mind, I just made it alphabetical. Someone can make it ordered by timestamp if they want to.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KP3f6fSdHifkuNyAwhb:b3kdrol)_

**Comment by klappy** [comment]
That sounds good to me. Time stamp sounds like more work including adding a last used time stamp and updating each time it's used.

**Comment by EllDoubleYew** [comment]
Any reason to still hold off on this merge? Aside from the mixed context that Jay commented on?

**Comment by lancelebanoff** [comment]
I fixed the mixed context already, so I think it's fine to merge now

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KPK_YonMtbAqltihpf-:bf5dlcg)_

**Comment by EllDoubleYew** [comment]
I dont want this PR to fall too far behind but I just tested it and there are some problems with the authentication stuff. @lancelebanoff could you do a merge with develop and see if you can fix it? I can't really test it until I figure out why it does not like the .auth file.

**Comment by lancelebanoff** [comment]
Sure.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KPT-9T4uSaacMDUkArf:b-80tlqk)_

**Comment by lancelebanoff** [comment]
I merged develop into my branch, and I don't see any problems with authentication.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/23#-:-KPYyLQATp6jtO8fcUM8:brs1jsi)_

**Comment by EllDoubleYew** [comment]
We may need to ice this branch for some future changes. One thing Chris mentioned that I think would be really nice is to have the load app screen replace the "Click apps to start checking" text that is in the main view right now. I think that feature would live well on this branch and it may be something I implement as soon as we clear out our current sprint backlog.

**Comment by mannycolon** [comment]
@EllDoubleYew sounds good. I have been waiting for us to address that screen for weeks lol I really think it is essential that we do something about that for better User experience .

**Comment by klappy** [comment]
@EllDoubleYew: Should we address this before it gets too far behind?

**Comment by EllDoubleYew** [comment]
@klappy I just gave this another test by throwing some fake apps at it and it still orders them correctly. I will merge before it falls off pace of develop.

**Pull request merged**
