### PR TITLE
bugfix 5063/Fixes for white space on USFM3 import/export and ScripturePane

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Note
https://github.com/translationCoreApps/tc-ui-toolkit/pull/77 must be merged and published before this can be merged.

#### Describe what your pull request addresses (Please include relevant issue numbers):
- uses updated usfm-js, word-aligner, and tc-ui-toolkit modules to fix white space issues in USFM3 import/export and scripturePane.

#### Please include detailed Test instructions for your pull request:
- **delete resources folder** so they get recreated
- install sandbox build linked at bottom of this PR
- open project `https://git.door43.org/lrsallee/en_ult_mat_book`
- export project as USFM3 and reimport as local project.
- open WA to Mat 4:6
- in target language, after USFM3 export and re-import correct spacing should be preserved around quotes:

screen shot 2018-10-24 at 6 02 55 am

- with UGNT, should not see extra spacing around angled double quotes (fix to scripturePane rendering):

screen shot 2018-10-24 at 6 02 55 am 2

- with ULT, should see the fixes in green due to reprocessing of resources with library fixes.  Unfortunately the error in red is due to missing space in the catalog and will require catalog entry to be re-export with 1.0.2

screen shot 2018-10-24 at 6 02 55 am 2 2

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5307)

### CODE REVIEW

**Comment by bspidel** [comment]
In Mat 4:16 the second and 4th patterns I see space before H and T like: (' H)

**Comment by PhotoNomad0** [comment]
untitled

This is what I am seeing on my windows machine.

**Comment by PhotoNomad0** [comment]
Concourse Builds:

https://tc-builds.door43.org/build/release-test-5063/translationCore-macos-x64-1.0.2-6ee2283.dmg
https://tc-builds.door43.org/build/release-test-5063/translationCore-win-x64-1.0.2-6ee2283.setup.exe
https://tc-builds.door43.org/build/release-test-5063/translationCore-win-x32-1.0.2-6ee2283.setup.exe

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing: `LGTM`

**Comment by PhotoNomad0** [comment]
Sandbox test builds:

https://tc-builds.door43.org/build/release-test-5063/translationCore-macos-x64-1.0.2-f0825c3.dmg
https://tc-builds.door43.org/build/release-test-5063/translationCore-win-x64-1.0.2-f0825c3.setup.exe

**Comment by bspidel** [comment]
Using sandbox build resulted in successful quoting of English

**Review by bspidel — APPROVED** [review]
:lgtm:

> Reviewed 15 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5307#-:-LPkLllF75z9CXXYe3Dj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
