### PR TITLE
Logout Card

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds the logout functionality to the user card

#### How to test this pull request:
Test the functionality of the user card logout and go to next step

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1947)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/js/components/home/usersManagement/Logout.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnL1ImimMbIxKvAE8WZ:-KnL1ImjE7TB_AWCHcIw:b2j2uez) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L6)):*
> ```JavaScript
>     render() {
>         return (
>             <div style={{ height: '100%', marginBottom: 0 }}>
> ```

shouldnt this be name profile?? im not sure just wanted to confirm. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 65 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMK8mubkkKqZhc7rFd:-KnMK8mubkkKqZhc7rFe:b-n80nhg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/containers/home/UsersManagementContainer.js#L65)):*
> ```JavaScript
> 
> const mapDispatchToProps = (dispatch, ownProps) => {
>   return {
> ```

Can we nest all these dispatches inside 'actions'? This gets cluttered and I was confused when in the component that uses them as to where these were defined because they weren't placed inside of actions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMLytEwReUACBhSu8n:-KnMLytEwReUACBhSu8o:b-jfff6t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/containers/home/UsersManagementContainer.js#L41)):*
> ```JavaScript
>         User
>       <MuiThemeProvider>
>           <Card style={{
> ```

Try to set multiline styles as variables that are passed in. Define them before the return, and just reference it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Logout.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMMHJLKbf1X6CCxfM6:-KnMMHJLKbf1X6CCxfM7:b-8vuy4t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L16)):*
> ```JavaScript
>                     className={"btn-prime"}
>                     style={{ width: "100%", margin: "40px 0px 10px" }}
>                     onClick={() => this.props.goToNextStep()}>
> ```

can these be nested in this.props.actions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 39 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMMh4ISTAb0DG2dI0f:-KnMMh4Jz-IIrGvTIzNQ:bywrmko) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Login.js#L39)):*
> ```JavaScript
>     let u = this.state.username
>     let p = this.state.password
>     let disabledButton = (u == null || u == "") || (p == null || p == "")
> ```

Try to avoid single character variables. This should be easier to maintain:
```
    let { username, password } = this.state;
    let disabledButton = !username || !password;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 82 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMNAyg41jp6ZoxpUci:-KnMNAyg41jp6ZoxpUcj:b-o1c9ag) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Login.js#L82)):*
> ```JavaScript
>             style={{ width: "100%", margin: "10px 0px 20px" }}
>             onClick={() => this.props.showAlert(
>               <div>
> ```

Can this be assigned somewhere as a const and then passed in to the alert? Nesting this deep is hard to maintain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/components/home/overview/TemplateCard.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMOOl5SnX5M16B1t_4:-KnMOOl6thFrswFYSd1H:b-f3zjy1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/components/home/overview/TemplateCard.js#L27)):*
> ```JavaScript
>     let emptyContent = this.emptyContent(emptyMessage, emptyButtonLabel, emptyButtonOnClick, disabled);
>     let content = this.props.content ? this.props.content : emptyContent;
>     let cardStyle = { marginTop: '5px', height: '110px' }
> ```

Removing this makes the cards look bad as the design seemed strict to a set height.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by klappy** [comment]
*[src/js/components/home/overview/TemplateCard.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMOOl5SnX5M16B1t_4:-KnMPeZ_Nvm2cZ_Exbhy:bo3uits) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/components/home/overview/TemplateCard.js#L27)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Removing this makes the cards look bad as the design seemed strict to a set height.
</blockquote></details>

After Testing with that put back in it still looks good with the minimal height with your change below. Go ahead and put this one back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/js/components/home/overview/TemplateCard.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMOOl5SnX5M16B1t_4:-KnQgrYZntfV9EW4QB9D:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/components/home/overview/TemplateCard.js#L27)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

After Testing with that put back in it still looks good with the minimal height with your change below. Go ahead and put this one back.
</blockquote></details>

Done.

---

*[src/js/components/home/usersManagement/Login.js, line 39 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMMh4ISTAb0DG2dI0f:-KnQhFa8rd3Usxw_dfRA:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Login.js#L39)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Try to avoid single character variables. This should be easier to maintain:
```
    let { username, password } = this.state;
    let disabledButton = !username || !password;
```
</blockquote></details>

Done.

---

*[src/js/components/home/usersManagement/Login.js, line 82 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMNAyg41jp6ZoxpUci:-KnQhdaNQUvi12JrzTQC:b-ovwawk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Login.js#L82)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can this be assigned somewhere as a const and then passed in to the alert? Nesting this deep is hard to maintain.
</blockquote></details>

Good idea!

---

*[src/js/components/home/usersManagement/Logout.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnL1ImimMbIxKvAE8WZ:-KnQoDxHx343ITam3w9d:br69i8n) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

shouldnt this be name profile?? im not sure just wanted to confirm. 
</blockquote></details>

Sorry not sure what you mean by "this"

---

*[src/js/components/home/usersManagement/Logout.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMMHJLKbf1X6CCxfM6:-KnQoAIXmp24-xZzPkL1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L16)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

can these be nested in this.props.actions?
</blockquote></details>

Done.

---

*[src/js/containers/home/UsersManagementContainer.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMLytEwReUACBhSu8n:-KnQk8C9_pKZSNJU2es6:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/containers/home/UsersManagementContainer.js#L41)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Try to set multiline styles as variables that are passed in. Define them before the return, and just reference it here.
</blockquote></details>

Done.

---

*[src/js/containers/home/UsersManagementContainer.js, line 65 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMK8mubkkKqZhc7rFd:-KnQkKmlRiBsVRbxiQj0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/containers/home/UsersManagementContainer.js#L65)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can we nest all these dispatches inside 'actions'? This gets cluttered and I was confused when in the component that uses them as to where these were defined because they weren't placed inside of actions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/js/components/home/usersManagement/Logout.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnL1ImimMbIxKvAE8WZ:-KnXKnGoZGOb6-ERqLMP:bhmzya8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L6)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Sorry not sure what you mean by "this"
</blockquote></details>

Sorry, I meant shouldnt this file be named profile instead of logout?

---

*[src/js/components/home/usersManagement/Logout.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947#-KnMMHJLKbf1X6CCxfM6:-KnXL-W-wYtAK8FiMK8d:b-71e82c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e488d9cb7e70cf8518d1f077c9d3b070d68ef3f2/src/js/components/home/usersManagement/Logout.js#L16)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

did you nested the actions??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1947)*

**Pull request closed without merging**
