### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5590)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (2b6cb55)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-2b6cb55.deb) is ready for download.
[macOS build 1.1.0 (2b6cb55)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-2b6cb55.dmg) is ready for download.
[Windows x64 build 1.1.0 (2b6cb55)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-2b6cb55.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2b6cb55)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-2b6cb55.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d493bd8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-d493bd8.deb) is ready for download.
[macOS build 1.1.0 (d493bd8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-d493bd8.dmg) is ready for download.
[Windows x64 build 1.1.0 (d493bd8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-d493bd8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d493bd8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-d493bd8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (37e5bd2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-37e5bd2.deb) is ready for download.
[macOS build 1.1.0 (37e5bd2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-37e5bd2.dmg) is ready for download.
[Windows x64 build 1.1.0 (37e5bd2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-37e5bd2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (37e5bd2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-37e5bd2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (2e77e02)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-2e77e02.deb) is ready for download.
[macOS build 1.1.0 (2e77e02)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-2e77e02.dmg) is ready for download.
[Windows x64 build 1.1.0 (2e77e02)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-2e77e02.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2e77e02)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-2e77e02.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (71b4eb4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-71b4eb4.deb) is ready for download.
[macOS build 1.1.0 (71b4eb4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-71b4eb4.dmg) is ready for download.
[Windows x64 build 1.1.0 (71b4eb4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-71b4eb4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (71b4eb4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-71b4eb4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6ef0ba3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6ef0ba3.deb) is ready for download.
[macOS build 1.1.0 (6ef0ba3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6ef0ba3.dmg) is ready for download.
[Windows x64 build 1.1.0 (6ef0ba3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6ef0ba3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6ef0ba3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6ef0ba3.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4fb234e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-4fb234e.deb) is ready for download.
[macOS build 1.1.0 (4fb234e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-4fb234e.dmg) is ready for download.
[Windows x64 build 1.1.0 (4fb234e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-4fb234e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4fb234e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-4fb234e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f914aaf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-f914aaf.deb) is ready for download.
[macOS build 1.1.0 (f914aaf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-f914aaf.dmg) is ready for download.
[Windows x64 build 1.1.0 (f914aaf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-f914aaf.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f914aaf)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-f914aaf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a7b01f8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-a7b01f8.deb) is ready for download.
[macOS build 1.1.0 (a7b01f8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-a7b01f8.dmg) is ready for download.
[Windows x64 build 1.1.0 (a7b01f8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-a7b01f8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a7b01f8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-a7b01f8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3ad963a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3ad963a.deb) is ready for download.
[macOS build 1.1.0 (3ad963a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3ad963a.dmg) is ready for download.
[Windows x64 build 1.1.0 (3ad963a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3ad963a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3ad963a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3ad963a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ff2d711)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-ff2d711.deb) is ready for download.
[macOS build 1.1.0 (ff2d711)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-ff2d711.dmg) is ready for download.
[Windows x64 build 1.1.0 (ff2d711)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-ff2d711.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ff2d711)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-ff2d711.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b4e0c3e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b4e0c3e.deb) is ready for download.
[macOS build 1.1.0 (b4e0c3e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b4e0c3e.dmg) is ready for download.
[Windows x64 build 1.1.0 (b4e0c3e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b4e0c3e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b4e0c3e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b4e0c3e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e94c812)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e94c812.deb) is ready for download.
[macOS build 1.1.0 (e94c812)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e94c812.dmg) is ready for download.
[Windows x64 build 1.1.0 (e94c812)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e94c812.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e94c812)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e94c812.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1124a67)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-1124a67.deb) is ready for download.
[macOS build 1.1.0 (1124a67)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-1124a67.dmg) is ready for download.
[Windows x64 build 1.1.0 (1124a67)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-1124a67.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1124a67)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-1124a67.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cea546d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-cea546d.deb) is ready for download.
[macOS build 1.1.0 (cea546d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-cea546d.dmg) is ready for download.
[Windows x64 build 1.1.0 (cea546d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-cea546d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cea546d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-cea546d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3335aae)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3335aae.deb) is ready for download.
[macOS build 1.1.0 (3335aae)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3335aae.dmg) is ready for download.
[Windows x64 build 1.1.0 (3335aae)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3335aae.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3335aae)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3335aae.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (63c5f0a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-63c5f0a.deb) is ready for download.
[macOS build 1.1.0 (63c5f0a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-63c5f0a.dmg) is ready for download.
[Windows x64 build 1.1.0 (63c5f0a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-63c5f0a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (63c5f0a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-63c5f0a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fe66dd3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fe66dd3.deb) is ready for download.
[macOS build 1.1.0 (fe66dd3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fe66dd3.dmg) is ready for download.
[Windows x64 build 1.1.0 (fe66dd3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fe66dd3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fe66dd3)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fe66dd3.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f1990b6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-f1990b6.deb) is ready for download.
[macOS build 1.1.0 (f1990b6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-f1990b6.dmg) is ready for download.
[Windows x64 build 1.1.0 (f1990b6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-f1990b6.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f1990b6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-f1990b6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3bdc895)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3bdc895.deb) is ready for download.
[macOS build 1.1.0 (3bdc895)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3bdc895.dmg) is ready for download.
[Windows x64 build 1.1.0 (3bdc895)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3bdc895.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3bdc895)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3bdc895.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (37a713b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-37a713b.deb) is ready for download.
[macOS build 1.1.0 (37a713b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-37a713b.dmg) is ready for download.
[Windows x64 build 1.1.0 (37a713b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-37a713b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (37a713b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-37a713b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (dac8184)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-dac8184.deb) is ready for download.
[macOS build 1.1.0 (dac8184)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-dac8184.dmg) is ready for download.
[Windows x64 build 1.1.0 (dac8184)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-dac8184.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (dac8184)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-dac8184.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d4d9e6a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-d4d9e6a.deb) is ready for download.
[macOS build 1.1.0 (d4d9e6a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-d4d9e6a.dmg) is ready for download.
[Windows x64 build 1.1.0 (d4d9e6a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-d4d9e6a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d4d9e6a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-d4d9e6a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (23736b1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-23736b1.deb) is ready for download.
[macOS build 1.1.0 (23736b1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-23736b1.dmg) is ready for download.
[Windows x64 build 1.1.0 (23736b1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-23736b1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (23736b1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-23736b1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a0bf6ec)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-a0bf6ec.deb) is ready for download.
[macOS build 1.1.0 (a0bf6ec)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-a0bf6ec.dmg) is ready for download.
[Windows x64 build 1.1.0 (a0bf6ec)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-a0bf6ec.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a0bf6ec)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-a0bf6ec.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (da59fa9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-da59fa9.deb) is ready for download.
[macOS build 1.1.0 (da59fa9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-da59fa9.dmg) is ready for download.
[Windows x64 build 1.1.0 (da59fa9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-da59fa9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (da59fa9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-da59fa9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c983be4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-c983be4.deb) is ready for download.
[macOS build 1.1.0 (c983be4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-c983be4.dmg) is ready for download.
[Windows x64 build 1.1.0 (c983be4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-c983be4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c983be4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-c983be4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6750f82)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6750f82.deb) is ready for download.
[macOS build 1.1.0 (6750f82)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6750f82.dmg) is ready for download.
[Windows x64 build 1.1.0 (6750f82)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6750f82.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6750f82)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6750f82.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (56da4af)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-56da4af.deb) is ready for download.
[macOS build 1.1.0 (56da4af)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-56da4af.dmg) is ready for download.
[Windows x64 build 1.1.0 (56da4af)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-56da4af.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (56da4af)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-56da4af.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3d6809e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3d6809e.deb) is ready for download.
[macOS build 1.1.0 (3d6809e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3d6809e.dmg) is ready for download.
[Windows x64 build 1.1.0 (3d6809e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3d6809e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3d6809e)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3d6809e.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
