### PR TITLE
Fixed bugs with local and online project import

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Fixed bugs with local and online project import

#### How to test this pull request:
- Try importing a project from online.
- Try importing a project from your local file system.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2498)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498)*

**Comment by klappy** [comment]
When testing this, it imports the project but doesn't convert it to a tC project. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498#-:-Ks5VAVnGrNE_phgH5ow:bo7rnhp)*

**Comment by klappy** [comment]
If it helps, using the current Dev branch, I can open that same project and it works fine. I imported it with your branch and then switched to Develop branch and it appeared to convert the project when opening it from the project list.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498#-:-Ks5jhqzhLDDrk3MvQZP:b-hg2pc6)*

**Comment by mannycolon** [comment]
Done. @klappy @royalsix This PR should be good to go now.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498#-:-KsADEbouggiw-ABxVkB:b-rxa11f)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix This PR should be good to go now.

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498#-:-KsAehNOH7Iy8wDd4nO8:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2498)*

**Pull request merged**
