### PR TITLE
TC Wifi Fix On Hibernate

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes the issues related to going offline after the computer is hibernate mode.

#### How to test this pull request:
To test this you can have your wifi on then close you computer wait about 20 mins open back up, and see if your wifi is still on.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/914)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/CoreActionsRedux.js, line 35 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDWthnkKLKwwA9RvYp:-KfDWthnkKLKwwA9RvYq:b-4yoaz8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/actions/CoreActionsRedux.js#L35)):*
> ```JavaScript
> module.exports.changeOnlineStatus = function (online, firstLoad, fromButton) {
>   return ((dispatch) => {
>     if (!document.hasFocus() && !fromButton) return;
> ```

Is this the line to see if it's hibernating or not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by klappy** [comment]
*[src/js/components/core/SideBar/OnlineStatus.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDXBX5d46WMki3nNgx:-KfDXBX5d46WMki3nNgy:b-2foord) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/components/core/SideBar/OnlineStatus.js#L44)):*
> ```JavaScript
>   }
> 
>   setOnline(fromButton) {
> ```

is passing the button/sender the way to ensure only the button action is called explicitly and not without user interaction?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by RoyalSix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/CoreActionsRedux.js, line 35 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDWthnkKLKwwA9RvYp:-KfISp4ucRT3yVpzIXVy:bbjdi9v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/actions/CoreActionsRedux.js#L35)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is this the line to see if it's hibernating or not?
</blockquote></details>

Yes! I added comments :)

---

*[src/js/components/core/SideBar/OnlineStatus.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDXBX5d46WMki3nNgx:-KfISsC2wJOJcETDN-kb:bbjdi9v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/components/core/SideBar/OnlineStatus.js#L44)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

is passing the button/sender the way to ensure only the button action is called explicitly and not without user interaction?
</blockquote></details>

Yes! I added comments :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/SideBar/OnlineStatus.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDXBX5d46WMki3nNgx:-KfNYPpC1JIMAQVTjyob:b-qz25r4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/components/core/SideBar/OnlineStatus.js#L44)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes! I added comments :)
</blockquote></details>

where is the comment that explains the fromButton argument?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by mannycolon** [comment]
@RoyalSix merge with develop

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/SideBar/OnlineStatus.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-KfDXBX5d46WMki3nNgx:-KfShWl4dXmMBXDmWBxn:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7befcf862b1e2fb38c87bb2f26233d40c107560e/src/js/components/core/SideBar/OnlineStatus.js#L44)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

where is the comment that explains the fromButton argument?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/914#-:-KfSzD7ILVqqzTU-8wOX:bnfp4nl)*

**Pull request closed without merging**
