### PR TITLE
Feature/2251 Inconsistent use of icons for language

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: #2251

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3134)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134#-:-KyYZxS07YNE6lW0p-4p:bnfp4nl)*

**Comment by klappy** [comment]
Tests pass, and looks good when loading the app. Addresses concerns in the issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134#-:-KyY_Rh2JHKmmHuVd9-0:b-w4ps29)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134)*

**Review by richmahn — DISMISSED** [review]
TravisCI no longer passes, snapshots do not match.

**Comment by richmahn** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/ProjectCard.test.js, line 10 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134#-Kybm_W3JxC1Z5Elam4B:-Kybm_W3JxC1Z5Elam4C:btk0h00) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bd68de8d870ca457b8f090a28190657293796a05/__tests__/ProjectCard.test.js#L10)):*
> ```JavaScript
> // Tests for ProjectCard React Component
> describe('Test ProjectCard component',()=>{
>   test('Comparing ProjectCard Component render should match snapshot', () => {
> ```

Is there a reason to remove the date from the test description? This is used as the key in the snapshot file to know which snapshot to use. While we can update the snapshots with -u from the command line, changing the date in the description not only makes a new snapshot for that date, but also ensures we know when the snapshot was last taken. It actually is a good thing to keep historical snapshots for comparison of change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134)*

**Comment by richmahn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134#-:-KybxVIWsQwCSgt885Ta:bnfp4nl)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/ProjectCard.test.js, line 10 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134#-Kybm_W3JxC1Z5Elam4B:-Kybxgx6Wvl6wm9z3s0H:b-pq1aql) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bd68de8d870ca457b8f090a28190657293796a05/__tests__/ProjectCard.test.js#L10)):*
>  
:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3134)*

**Pull request merged**
