### PR TITLE
Added latest tc-ui-tollkit that includes removal of the unnecessary usage of the theme provider

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 181 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459#-LRhc-lO9gfVe9eZQinS:-LRhc-lO9gfVe9eZQinT:b-6046is) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/58992f5a2256f3388c363b9b398058a4b5d57ff3/package.json#L181)):*
> ```JSON
>     "tc-strings": "0.1.7",
>     "tc-tool": "^2.0.0",
>     "tc-ui-toolkit": "^0.12.4",
> ```

Think you want this to be "0.12.4" so we don't accidentally pull in development releases in the future.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 181 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459#-LRhccjJ0rd0b3K04G3n:-LRhccjJ0rd0b3K04G3o:b-m8iaz8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/58992f5a2256f3388c363b9b398058a4b5d57ff3/package.json#L181)):*
> ```JSON
>     "tc-strings": "0.1.7",
>     "tc-tool": "^2.0.0",
>     "tc-ui-toolkit": "^0.12.4",
> ```

Think you want this to be "0.12.4" so we don't accidentally pull in development releases of tc-ui-toolkit in the future.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (58992f5)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-linux-x64-1.1.0-58992f5.deb) is ready for download.
[macOS build 1.1.0 (58992f5)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-macos-x64-1.1.0-58992f5.dmg) is ready for download.
[Windows x64 build 1.1.0 (58992f5)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x64-1.1.0-58992f5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (58992f5)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x32-1.1.0-58992f5.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM - code review and testing, but Travis is not building it.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3843bd6)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-linux-x64-1.1.0-3843bd6.deb) is ready for download.
[macOS build 1.1.0 (3843bd6)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-macos-x64-1.1.0-3843bd6.dmg) is ready for download.
[Windows x64 build 1.1.0 (3843bd6)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x64-1.1.0-3843bd6.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3843bd6)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x32-1.1.0-3843bd6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ba257b4)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-linux-x64-1.1.0-ba257b4.deb) is ready for download.
[macOS build 1.1.0 (ba257b4)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-macos-x64-1.1.0-ba257b4.dmg) is ready for download.
[Windows x64 build 1.1.0 (ba257b4)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x64-1.1.0-ba257b4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ba257b4)](https://tc-builds.door43.org/build/bugfix-mannycolon-5403/translationCore-win-x32-1.1.0-ba257b4.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5459)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
