### PR TITLE
Bugfix bspidel 3072

### PR DESCRIPTION
**Pull request by bspidel**
#### This pull request addresses:

Added a period to dialog text.

#### How to test this pull request:
Visual inspection
1 Login as Guest
2 Select project
3 Click on ellipsis
4 Select "Upload to Door43

Note end of notice

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3140)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3140#-:-KyaRT6ykcmMcSa2HIlw:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3140)*

**Comment by klappy** [comment]
*[tC_apps/translationWords, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3140#-Kyblzn6HLiig3rYO21m:-Kyblzn6HLiig3rYO21n:b-n27i4q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8834eb809bb174512f8d49ce11b59d897068830c/tC_apps/translationWords#L1)):*
> ```
> Subproject commit a27f3b79fb72e384bbdebcbde1c6c58fbe142c48
> ```

@bspidel: If you can run npm run update-apps, it should update to what would match on develop branch. Commit that revision and it would essentially be like undoing the accidental commit.
Or you could also manually copy paste the red commit from here to that file and save/commit it, but it seems like more work than just running the command and committing/pushing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3140)*

**Comment by klappy** [comment]
@bspidel Looks good, only one small thing to address and we're ready to merge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3140#-:-KybmI2Em_-LrB9X8oHs:b9t8uia)*

**Pull request merged**
