### PR TITLE
Add way to stop loading after delay

### PR DESCRIPTION
**Pull request by ihoegen**
During loading, a user can hit Ctrl or Cmd + W to cancel loading, and if loading takes longer than 10 seconds, the loading modal will show a link to stop loading.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/704)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/core/MenuBar.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-KcpxGmvjlGS8AxdTBC6:-KcpxGmvjlGS8AxdTBC7:be2lcvt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cf8de1f9e2bb6a2fb7abc7b08c03dc38d219a804/src/js/components/core/MenuBar.js#L27)):*
> ```JavaScript
>           Upload.clearPreviousData();
>           CoreStore.currentCheckNamespace = ' ';
>           CoreActions.killLoading();
> ```

We should convert this to Redux as not to refer back to old code (Core Actions) that we are trying to refactor out. If you want help with this let me know

---

*[src/js/pages/app.js, line 678 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-Kcpxd5m1TtNHBmpRQkx:-Kcpxd5napXScLU3DuN4:b2nreh6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cf8de1f9e2bb6a2fb7abc7b08c03dc38d219a804/src/js/pages/app.js#L678)):*
> ```JavaScript
>           killLoading: () => {
>             Upload.clearPreviousData();
>             CoreActions.killLoading();
> ```

Same as above.

---

*[src/js/pages/app.js, line 685 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-KcpxyBqy8Za1T4TCyRq:-KcpxyBqy8Za1T4TCyRr:b49fxu6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cf8de1f9e2bb6a2fb7abc7b08c03dc38d219a804/src/js/pages/app.js#L685)):*
> ```JavaScript
>               if (!CoreStore.doneLoading) {
>                 setTimeout(() => {
>                   this.setState(merge({}, this.state, {
> ```

Again, instead of setting the state in app.js,  we should be dispatching an action that results in a new state

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by ihoegen** [comment]
@RoyalSix I implemented redux

**Comment by RoyalSix** [comment]
Reviewed 4 of 5 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r1, 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/components/core/MenuBar.js, line 27 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-KcviTnD9mkhzHGwoOr8:-KcviTnD9mkhzHGwoOr9:b7o3cpj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/417fc239869be074a5aa53ca46b141f5bfe0f383/src/js/components/core/MenuBar.js#L27)):*
> ```JavaScript
>           Upload.clearPreviousData();
>           CoreStore.currentCheckNamespace = ' ';
>           CoreActions.killLoading();
> ```

Nice implementation, we can factor out CoreActions.killLoading() at a later time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by EllDoubleYew** [comment]
Reviewed 2 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/LoaderActions.js, line 5 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-Kd2OwInhE3t1w9xFGqA:-Kd2OwIoXCxtqFoUcOu0:b-mkn6lp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0bd2ef9901baa127d10764a67f4de088690e9fec/src/js/actions/LoaderActions.js#L5)):*
> ```JavaScript
> module.exports.toggleLoader = function () {
>   return {
>     type: consts.TOGGLE_LOADER_MODAL,
> ```

so we dont have to add actions to the coreActionsConst we can just do "TOGGLE_LOADER_MODAL" instead so we dont have to always got to that const file.

---

*[src/js/components/core/MenuBar.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-KcpxGmvjlGS8AxdTBC6:-Kd2PEExsKK-J5qzOAZi:bcv6t20) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cf8de1f9e2bb6a2fb7abc7b08c03dc38d219a804/src/js/components/core/MenuBar.js#L27)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

We should convert this to Redux as not to refer back to old code (Core Actions) that we are trying to refactor out. If you want help with this let me know
</blockquote></details>

I agree we should don't just limit the usage of old code but eliminated for good.

---

*[src/js/pages/app.js, line 685 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704#-KcpxyBqy8Za1T4TCyRq:-Kd2PjmxGvBqfSOoBOdX:b-k0jjew) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cf8de1f9e2bb6a2fb7abc7b08c03dc38d219a804/src/js/pages/app.js#L685)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Again, instead of setting the state in app.js,  we should be dispatching an action that results in a new state
</blockquote></details>

How about we actually do the Redux implementation of all of this. why are we still using app.js for business logic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/704)*

**Comment by ihoegen** [comment]
@mannycolon I think we should always refer to the consts file, so that we know what specific actions exists. It should be using redux now, and for now, the CoreActions call needs to be left in menu bar because there's no way for it to communicate with the dispatcher.

**Pull request merged**
