### PR TITLE
Adds support for ignorable alerts

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #5259 
- Adds new alert system which supports ignorable alerts.
- Adds ignorable alerts to the tool api.

#### Please include detailed Test instructions for your pull request:
- Nothing in this PR is directly testable. You'll need to test along with the wA updates.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)

### CODE REVIEW

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 20 of 37 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)* status: 21 of 37 files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
@neutrinog - tried changing user, and it didn't switch off the ignore.  Otherwise working well.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 16 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by da1nerd** [comment]
@PhotoNomad0 I fixed the alerts resetting when the user logs out.

**Comment by da1nerd** [comment]
@PhotoNomad0 I ended up reverting all the travis changes because it was consistently breaking. We can do that another time.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r3, 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)* status: 41 of 43 files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[__tests__/WordAlignmentActions.test.js, line 38 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330#-LPzZBNs85p2wFO_JZje:-LPzZBNs85p2wFO_JZjf:b-u8o1uo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/94f2da398a3cd686242a3c76811335db8a8166e4/__tests__/WordAlignmentActions.test.js#L38)):*
> ```JavaScript
>   });
>   it('should export a usfm file given a correct path to the project', () => {
>     jest.setTimeout(30000);
> ```

Think the original was more readable and don't see that this improves the test.

**Comment by PhotoNomad0** [comment]
@neutrinog - local testing LGTM, like how you fixed the logout.

Prefer reverting changes to tests not related to issue.

Test coverage is down.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 7 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Pull request merged**
