### PR TITLE
Several fixes for styling and wording

### PR DESCRIPTION
**Pull request by cdwhitfield73**
#### This pull request addresses:

Issues 1250, 1225, 1224, 1233, 1187, and 1283 all having to do with style or wording changes in the core

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1287)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ApplicationModalContainer.js, line 7 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1287#-Kih5Su_9m3eV-anm1zM:-Kih5Su_9m3eV-anm1zN:bfs99xk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/210a9234a5efb9b8a36983e4e2da703335e6a37c/src/js/containers/ApplicationModalContainer.js#L7)):*
> ```JavaScript
> import Login from '../components/core/login/Login.js';
> import Profile from '../components/core/login/Profile';
> import Settings from '../components/core/Settings.js';
> ```

How about also removing the settings component import

---

*[src/js/containers/LoadModalContainer.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1287#-Kih5lkfhtcJXm2TEhf-:-Kih5lkfhtcJXm2TEhf0:bnpoh41) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/210a9234a5efb9b8a36983e4e2da703335e6a37c/src/js/containers/LoadModalContainer.js#L10)):*
> ```JavaScript
> import DragDrop from '../components/core/DragDrop';
> import Projects from '../components/core/login/Projects';
> import Report from "../components/core/reports/ReportGenerator";
> ```

same here remove the Report import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1287#-:-Kih6V8rhxRZOLSvBV6-:bnfp4nl)*

**Comment by mannycolon** [comment]
I tested this branch everything seems to be fine except for #1283 on my mac I'm still able to see the menu bar.

**Comment by mannycolon** [comment]
@ihoegen hey do you have any idea why the tests are failing??

**Comment by mannycolon** [comment]
#1250, #1225, #1224, #1233, #1187, and #1283

**Comment by ihoegen** [comment]
@mannycolon Basically, there's a new version of the npm module `xvfb-maybe` and the version is flawed. In my upcoming pull request for builds, I have a backtracked version of this module, which will fix the issue.

**Comment by klappy** [comment]
Reviewed 4 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1287)*

**Comment by klappy** [comment]
I think once you remove the 'Settings' import from the ApplicationModalContainer, it's good to go.

**Pull request merged**
