### PR TITLE
Initial commit of fixing state

### PR DESCRIPTION
**Pull request by klappy**
## This PR Addresses:
State issues for checkData are now resolved.

## Test This:
Use fresh project/tool. Perform selections, reminders, edits, comments and navigate around. They should not get jumbled anymore. Check the filesystem to see that random wrong checkData isn’t stored like it was.

## TODO:
- [ ] Apply similar condition for groupData and groupIndex data.
- [ ] Figure out if throttle is still needed and if so, figure out how to make it work with setupSubscriptions

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1132)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/pages/root.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132#-KiAl3niTBpqNMJ-HHfl:-KiAl3niTBpqNMJ-HHfm:bfs5l29) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9803e61efbbd793cf05945e26ac539c3f8c4bea8/src/js/pages/root.js#L3)):*
> ```JavaScript
> import React from 'react'
> import { Provider } from 'react-redux'
> import setupSubscriptions from 'redux-subscriptions'
> ```

Just a note: it looks like this library has been abandoned for https://github.com/xaviervia/redux-haiku is there a reason we want to use this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132#-:-KiB-Kope5JRvWKGhu7p:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/pages/root.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132#-KiAl3niTBpqNMJ-HHfl:-KiB7gjA2ZDFnsF0gQnD:b4k8emy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9803e61efbbd793cf05945e26ac539c3f8c4bea8/src/js/pages/root.js#L3)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Just a note: it looks like this library has been abandoned for https://github.com/xaviervia/redux-haiku is there a reason we want to use this one?
</blockquote></details>

good point luke also looks like theres not many issues opened. Maybe its pretty standalone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132#-:-KiB7x9DVXQLzivwhhBm:bnfp4nl)*

**Comment by ihoegen** [comment]
@klappy Can we get the tests to pass again?

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1132#-:-KiCZYu1xvmsY31FbVDH:bnfp4nl)*

**Pull request merged**
