### PR TITLE
Fixes check icon not dismissing in tW

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5654
- Fixes a typo in a context id that was breaking the visual update.

#### Please include detailed Test instructions for your pull request:
- See connected issue for testing instructions.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5713)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-linux-x64-1.1.0-3e562c1.deb) is ready for download.
[macOS build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-macos-x64-1.1.0-3e562c1.dmg) is ready for download.
[Windows x64 build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-win-x64-1.1.0-3e562c1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-win-x32-1.1.0-3e562c1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-linux-x64-1.1.0-3e562c1.deb) is ready for download.
[macOS build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-macos-x64-1.1.0-3e562c1.dmg) is ready for download.
[Windows x64 build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-win-x64-1.1.0-3e562c1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3e562c1)](https://tc-builds.door43.org/build/bugfix_joel_5654_checkmark-not-cleared/translationCore-win-x32-1.1.0-3e562c1.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
@RoyalSix would you mind reviewing this one? I want to make sure I correctly covered your use case here in the VerseEditActions.

**Comment by RoyalSix** [comment]
@neutrinog No problem, on it!

**Review by RoyalSix — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5713)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
