### PR TITLE
Feature - #4618 - Updates tC to 1.0.0, changes version for resources

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses new resources for the tC_resources dir (UGNT v0.2) but also makes the develop branch be officially for the 1.0.0 development

#### Please include detailed Test instructions for your pull request:
- Checkout feature-richmahn-4618 for tC_resources if it is not already merged in
- Verify UGNT v0.2 is being used (1 Peter 1:16 is a good verse to check)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @richmahn)

___
*[tC_resources, line 1 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839#-LJEw_CcCFmzt9gdczPp:-LJEw_Cd42J1metitzlH:b24q64m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fd661e91a0e9ca0923fe589a55306d23d3ec817c/tC_resources#L1)):*
> ```
> Subproject commit 09f81931ba9000649b0f31cb1e76d23f8f4bb038
> ```

need to remove
___
*[tC_apps/wordAlignment, line 1 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839#-LJEwblEEbBypJTNpJnW:-LJEwblEEbBypJTNpJnX:biedi4k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fd661e91a0e9ca0923fe589a55306d23d3ec817c/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit 1f47a9cf211f293052784edc592a1b3cb458a35b
> ```

need to remove

**Review by richmahn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839)* status: all files reviewed, 2 unresolved discussions (waiting on @richmahn and @PhotoNomad0)

___
*[tC_apps/wordAlignment, line 1 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839#-LJEwblEEbBypJTNpJnW:-LJF34Cl6mafPQwRgJpL:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fd661e91a0e9ca0923fe589a55306d23d3ec817c/tC_apps/wordAlignment#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

need to remove
</blockquote></details>

Done.

**Review by richmahn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

___
*[tC_resources, line 1 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839#-LJEw_CcCFmzt9gdczPp:-LJF54-Z7Taof5OrTYhr:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fd661e91a0e9ca0923fe589a55306d23d3ec817c/tC_resources#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

need to remove
</blockquote></details>

Done.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4839)* status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

**Pull request merged**
