### PR TITLE
Updated reference from ULB to ULT

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated reference from ULB to ULT
- **Note:** `Unit tests will fail until the tC_resources PR is merged`
#### Please include detailed Test instructions for your pull request:
- Verify that all **ULB** and **Unlocked Literal Bible** references were removed from the UI and replaced with **ULT** and **unfoldingWord Literal Text** respectively.
- **Dependencies:**
  - https://github.com/translationCoreApps/VerseCheck/pull/94
  - https://github.com/translationCoreApps/translationWords/pull/116
  - https://github.com/translationCoreApps/ScripturePane/pull/105
  - https://github.com/translationCoreApps/tC_Resources/pull/35

- **Recommended merge order:**
  - tC_resources repo 
  - Wait for it to go through
  - Rerun travis on this PR and wait for unit tests to pass.
  - Merge this PR and then the rest.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4081)

### CODE REVIEW

**Comment by RoyalSix** [comment]
`runGitCommands() { git checkout enhancement-mannycolon-4025 && git pull; }; runGitCommands; cd tC_apps/ScripturePane; runGitCommands; cd ../VerseCheck; runGitCommands; cd ../translationWords; runGitCommands; cd ../../tC_resources; runGitCommands; cd ../;`

**Comment by RoyalSix** [comment]
Code Review: `Pending`
Local Testing: 
I loaded a project and loaded the bibles in the scripture pane in the following order: `UDB, ULT(en), ULT(hi)`, it causes the scripture pane to have 4 bibles like the following.
screen shot 2018-03-15 at 11 31 26 am

**Comment by mannycolon** [comment]
@RoyalSix interesting... let me take a look at it now

**Comment by richmahn** [comment]
LGTM. Unable to reproduce Jay's bug find above.

---

Reviewed 74 of 75 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4081#-:-L7f4roH00RL-vKdFHXw:bvou7lw)*

**Comment by mannycolon** [comment]
@RoyalSix I cant recreate your bug. Is there any missing step that may help me recreate it?

**Comment by RoyalSix** [comment]
[fwe_tit_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1816875/fwe_tit_reg.zip)
This is my project

**Comment by RoyalSix** [comment]
I can't reproduce anymore, I think it had to do with running two electron instances, so its fine.

**Comment by RoyalSix** [comment]
Doing code review now

**Comment by RoyalSix** [comment]
Reviewed 74 of 75 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4081)*

**Pull request merged**
