### PR TITLE
Add submodule support for the Application

### PR DESCRIPTION
**Pull request by ihoegen**
`git submodule update --init --recursive` Will clone the submodules for you

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/460)

### CODE REVIEW

**Comment by RoyalSix** [comment]
How can this be tested?

**Comment by ihoegen** [comment]
Try creating a new project and opening a tool.

**Comment by ihoegen** [comment]
Also: `git submodule update --init --recursive`

**Comment by mannycolon** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/460)*

**Comment by mannycolon** [comment]
@ihoegen update the commits and/or release number for the tools, you could also add translationNotes if you want

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/460)*

**Pull request merged**
