### PR TITLE
Update USFM Export Workflow

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Creates one button on the export card, and shows two options to export from there.
If usfm 3(TL with alignment data embedded) is chosen then project must have no alignment errors. 
If there is alignment errors the user has the option to reset them.
This PR also uses the same workflow mentioned above to fix alignments for door43 uploads.

#### Please include detailed Test instructions for your pull request:
1. 
- Load a new project (No alignments, and no checks, edits, etc...)
- Go to projects page, click on the three dot menu, and click on `Export To USFM`
- [ ] The app should ask where to export
- [ ] After selecting the location the project should get exported in usfm2 format
- [ ] Verify it is the same project that got exported by re-loading it into tC
2.
- Load a project with alignments
- Go to projects page, click on the three dot menu, and click on `Export To USFM`
- [ ] The app should ask if you want to export as usfm 2 or usfm 3, select usfm 3
- [ ] The app should ask where to export
- [ ] After selecting the location the project should get exported in usfm3 format
- [ ] Verify it is the same project that got exported by re-loading it into tC (This will not be completely working until #4093 is working and merged)
3. 
- Load a project with alignments and alignment data errors
  - This is achieved by aligning a verse and editing the verse text in that same verse
- Go to projects page, click on the three dot menu, and click on `Export To USFM`
- [ ] The app should ask if you want to export as usfm 2 or usfm 3, select usfm 3
- [ ] The app should ask where to export
- [ ] The app should show a dialog stating there are errors and if you want to cancel or reset the invalid alignments and `Export`. Select `Export`
- [ ] After selecting the location the project should get exported in usfm3 format
- [ ] Verify it is the same project that got exported by re-loading it into tC (This will not be completely working until #4093 is working and merged)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4095)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4095)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - there is a jsdocs error breaking the Travis build.

**Comment by mannycolon** [comment]
Reviewed 2 of 17 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4095)*

**Comment by mannycolon** [comment]
@RoyalSix Fix failing unit tests

**Comment by mannycolon** [comment]
Reviewed 10 of 17 files at r1, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4095)*

**Comment by mannycolon** [comment]
**Code:** `LGTM`
**Local Test:** `Pending`

**Comment by mannycolon** [comment]
@RoyalSix 

Base on #3850 the following don't match the story:
- The color of the Radio button should probably be black.
- The buttons order should go as follow `Cancel` button on the left and `Export` button on the right. (Same for the alert Modal)

screen shot 2018-03-21 at 1 51 57 pm

**Comment by mannycolon** [comment]
When trying to export the following Project [english_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1834610/english_tit.zip) as `USFM 3` I got the alert but when I clicked the`export` button, the export did not go through. 

Also, got the following error message.

```
Uncaught TypeError: Cannot read property 'verseObjects' of undefined
    at /Users/mannycolon/dev/translationCore/src/js/helpers/WordAlignmentHelpers.js:535:50
```

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4095)*

**Comment by RoyalSix** [comment]
Let me update tests

**Comment by mannycolon** [comment]
@RoyalSix Exporting to `usfm 3` says it completely exported the project to `usfm 3` when it actually hasn't finished exporting the file. Thus when I go to the location where the file is supposed to be, it's not there yet then it appears in a few minutes.

**Note:** Checked the exported usfm file and it looks correct.

**Comment by mannycolon** [comment]
Reviewed 13 of 15 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4095)*

**Pull request merged**
