### PR TITLE
Updated tC api methods and documentation

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This is mildly related to https://github.com/unfoldingWord-dev/translationCore/issues/4319.
The updates in this PR will support some future updates in wA.

Also related to https://github.com/unfoldingWord-dev/translationCore/issues/4555

- update the tc-tool version to expose some more advanced features to tools.
- updated tc api methods provided to tools
- updated tc api docs.
- fixes the feedback dialog from disappearing while in the wA tool.

#### Please include detailed Test instructions for your pull request:
- Log out and in to reset the internet confirmation dialog.
- enter wA and open the feedback dialog.
- After submitting the feedback you should be presented with the internet confirmation.
- Toggle the checkbox in the confirmation dialog. Previously the feedback dialog would disappear at this point. However, it should now remain open.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 13 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[src/js/actions/GroupMenuActions.js, line 25 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711#-LHL9yjg4J69iWEmsiV0:-LHL9yjg4J69iWEmsiV1:b93bt87) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fcedd04057c6a7c65ef64fa62d1b736a41a326d1/src/js/actions/GroupMenuActions.js#L25)):*
> ```JavaScript
>  * @return {Function}
>  */
> export const changeGroup = contextId => dispatch => {
> ```

Was this not previously working?

**Comment by da1nerd** [comment]
___
*[src/js/actions/GroupMenuActions.js, line 25 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711#-LHL9yjg4J69iWEmsiV0:-LHLBUgS9Q6YbqUkmXWu:b-ev66tr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fcedd04057c6a7c65ef64fa62d1b736a41a326d1/src/js/actions/GroupMenuActions.js#L25)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Was this not previously working?
</blockquote></details>

it did not exist before.
Rather than creating a dynamic function when mapping to props I moved it into a new action.
This keeps the component cleaner and also improves performance because react will see the same function every time instead of a new one each time.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/GroupMenuActions.js, line 25 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4711#-LHL9yjg4J69iWEmsiV0:-LHLhCFp1z6yKbcSk5qY:b-jeuoxj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fcedd04057c6a7c65ef64fa62d1b736a41a326d1/src/js/actions/GroupMenuActions.js#L25)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

it did not exist before.
Rather than creating a dynamic function when mapping to props I moved it into a new action.
This keeps the component cleaner and also improves performance because react will see the same function every time instead of a new one each time. 
</blockquote></details>

Nice, I've seen this inefficiency before! Nice job identifying it.

**Pull request merged**
