### PR TITLE
Fix #3366/tW crash on projects missing verses

### LINKED ISSUE #3366: Write manifest migrations from tStudio to tC
- Manifests coming from tS with a package_version lower than 3 need to be tweaked a bit to work in tC.

- The tweaking is happening somewhere in the project validation process when it should happen in the migrations process.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: https://github.com/unfoldingWord-dev/translationCore/issues/3366

On Import missing verses are inserted into chapter jsons as empty strings so we don't get null exceptions.

#### How to test this pull request:

import online project from https://git.door43.org/168b7e635905dd89/uw-gal-hsl

Open tW and should see not see empty panel.

#### Note:  coverage is down because duplicated code was removed.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3489)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3489)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Tested the branch and it works well. Great job!

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3489)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3489)*

**Pull request merged**
