### PR TITLE
Bugfix 5963/change langId from grc to el-x-koine

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- change langId from `grc` to `el-x-koine`
- update bundled resources

#### Please include detailed Test instructions for your pull request:
- start tCore 
- check resources folder `grc` should be removed and new `el-x-koine` folder with updated ugnt 0.5 should be added
- change catalog_modified_time in manifest.json at resources⁩ ▸ ⁨el-x-koine⁩ ▸ ⁨bibles⁩ ▸ ⁨ugnt⁩ ▸ ⁨v0.5 - set it back to an earlier date such as 2018.
- Do check for source content updates - should no longer see `grc`, but should see an entry for Koine Greek (`el-x-koine`): 
Screen Shot 2019-04-12 at 10 18 19 AM
- select a Greek project and launch WA
  - in scripture pane, click on add resource - should not see `grc` entry in possible selections.
  - click on greek words to make sure lexicon popups are still working.
- select a Hebrew project and launch WA
  - click on Hebrew words to make sure lexicon popups are still working.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5974)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (5a55658)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-5a55658.deb) is ready for download.
[macOS build 1.2.0 (5a55658)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-5a55658.dmg) is ready for download.
[Windows x64 build 1.2.0 (5a55658)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-5a55658.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (5a55658)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-5a55658.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (5b09cc8)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-5b09cc8.deb) is ready for download.
[macOS build 1.2.0 (5b09cc8)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-5b09cc8.dmg) is ready for download.
[Windows x64 build 1.2.0 (5b09cc8)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-5b09cc8.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (5b09cc8)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-5b09cc8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (27eb0e1)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-27eb0e1.deb) is ready for download.
[macOS build 1.2.0 (27eb0e1)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-27eb0e1.dmg) is ready for download.
[Windows x64 build 1.2.0 (27eb0e1)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-27eb0e1.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (27eb0e1)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-27eb0e1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (e0d35a2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-e0d35a2.deb) is ready for download.
[macOS build 1.2.0 (e0d35a2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-e0d35a2.dmg) is ready for download.
[Windows x64 build 1.2.0 (e0d35a2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-e0d35a2.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (e0d35a2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-e0d35a2.setup.exe) is ready for download.

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> Reviewed 69 of 71 files at r1, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5974#-:-Lcg6g5n9tPTsyZGuDib:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/common/BooksOfTheBible.js, line 157 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5974#-Lcg663o8m596GbHTx9G:-Lcg663o8m596GbHTx9H:b-gz0s6t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e0d35a2860016be90e81566621d69ab4e6a71924/src/js/common/BooksOfTheBible.js#L157)):*
> ```JavaScript
> }
> 
> export const NT_ORIG_LANG = 'el-x-koine';
> ```

How about we use these constants throughout the codebase so that in the future we only have to update it in one place?

**Comment by mannycolon** [comment]
`Pending local test`

**Comment by mannycolon** [comment]
Local Test: `LGTM` 
Except for one thing:


Opened tC, Koine Greek was copied over to user resources folder, however, when I clicked the source content updater it still shows Koine Greek as an update. Something seems odd about this.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (80e06e2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-80e06e2.deb) is ready for download.
[macOS build 1.2.0 (80e06e2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-80e06e2.dmg) is ready for download.
[Windows x64 build 1.2.0 (80e06e2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-80e06e2.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (80e06e2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-80e06e2.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
I had left greek at 0.4, updated resources now.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (342c6cf)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-342c6cf.deb) is ready for download.
[macOS build 1.2.0 (342c6cf)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-342c6cf.dmg) is ready for download.
[Windows x64 build 1.2.0 (342c6cf)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-342c6cf.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (342c6cf)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-342c6cf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (98e9629)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-98e9629.deb) is ready for download.
[macOS build 1.2.0 (98e9629)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-98e9629.dmg) is ready for download.
[Windows x64 build 1.2.0 (98e9629)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-98e9629.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (98e9629)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-98e9629.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (c164394)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-c164394.deb) is ready for download.
[macOS build 1.2.0 (c164394)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-c164394.dmg) is ready for download.
[Windows x64 build 1.2.0 (c164394)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-c164394.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (c164394)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-c164394.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f6a316d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-linux-x64-1.2.0-f6a316d.deb) is ready for download.
[macOS build 1.2.0 (f6a316d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-macos-x64-1.2.0-f6a316d.dmg) is ready for download.
[Windows x64 build 1.2.0 (f6a316d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x64-1.2.0-f6a316d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f6a316d)](https://tc-builds.door43.org/build/bugfix-mcleanb-5963/translationCore-win-x32-1.2.0-f6a316d.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 12 of 30 files at r6, 5 of 20 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5974#-:-LclB6XRERtePXwHmp0F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Pull request merged**
