### PR TITLE
Local user QA fail issues

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- #1466

1. [x] When a local user navigates to the Import Online Projects page, the project list area on that page momentarily displays a no projects found a message which is quickly overwritten by a list of Door43 projects. I have no idea of what repo the list is from.
2. [x] The hyperlinks on the Terms and Conditions screen do not work.
3. [x] When a local user attempts to upload to Door43, the error message states "Error Uploading: Please log in to Door43 to upload your project." rather than what was specified in the list of requirements above.
4. [x] When logging into a Door43 account, as soon as any typing begins in the username field in the Door43 area, the terms and conditions checkbox gets enabled which is confusing since we don't require agreeing when logging in with a Door43 profile.
5. [x] After navigating to the terms and conditions the username edit box is cleared.

#### How to test this pull request:

- Open the app and follow the above scenarios.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1517)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1517)*

**Comment by klappy** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1517)*

**Comment by klappy** [comment]
> When a local user attempts to upload to Door43, the error message states "Error Uploading: Please log in to Door43 to upload your project." rather than what was specified in the list of requirements above.

Everything looks good but I'm not sure what the requirements above were for this one... Right now when I test this it appears to give me, "Error Uploading: Incorrect username or password"

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1517#-:-KjoYmskQGRT_WkqRZ6v:bi5ta3a)*

**Comment by mannycolon** [comment]
@klappy thats so interesting. That doesnt happen on my end.
screen shot 2017-05-11 at 1 07 25 am

**Comment by mannycolon** [comment]
@klappy I just discovered this is a separate issue. My changes didn't mess up with project uploading.

**Comment by klappy** [comment]
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1517#-:-Kjs0U9GU_TqTxivZ1PW:b-85i64v)*

**Pull request merged**
