### PR TITLE
Bugfix - Project card time since last opened fix

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Makes it so we now save the last time a project is opened to a settings.json file in the project's root dir and use that for the relative time in the project card from when the project was last opened.
- Will display "Never opened" for projects that were added before this fix until they are opened with this fix.
- Relative time on the project card also changes based on locale chosen
- Refs: #4927 & #6306  

#### Please include detailed Test instructions for your pull request:
- Use this build
- Go to the projects page. All projects you already have should say "Never opened" in the project card
- Open a project, go back to projects. Should see it was opened a few seconds ago.
- Import a project, go back to project page, should see it was opened a few second ago.
- Export a project to Door43, settings.json should appear in your repo on git.door43.org
- Change the locale, should see the time ago in that language
- You should also see the relative time update every minute when you stay on the home or projects page for a while.
- Check all of this on the project card on the home screen as well once you have opened a project.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6406)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (e8c1e47)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-linux-x64-2.0.0-e8c1e47.deb) is ready for download.
[macOS build 2.0.0 (e8c1e47)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-macos-x64-2.0.0-e8c1e47.dmg) is ready for download.
[Windows x64 build 2.0.0 (e8c1e47)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x64-2.0.0-e8c1e47.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (e8c1e47)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x32-2.0.0-e8c1e47.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1940b97)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-linux-x64-2.0.0-1940b97.deb) is ready for download.
[macOS build 2.0.0 (1940b97)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-macos-x64-2.0.0-1940b97.dmg) is ready for download.
[Windows x64 build 2.0.0 (1940b97)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x64-2.0.0-1940b97.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1940b97)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x32-2.0.0-1940b97.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (38ee40a)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-linux-x64-2.0.0-38ee40a.deb) is ready for download.
[macOS build 2.0.0 (38ee40a)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-macos-x64-2.0.0-38ee40a.dmg) is ready for download.
[Windows x64 build 2.0.0 (38ee40a)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x64-2.0.0-38ee40a.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (38ee40a)](https://tc-builds.door43.org/build/bugfix-richmahn-4927/translationCore-win-x32-2.0.0-38ee40a.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 2 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6406)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
