### PR TITLE
Using Tool API For wA Progress loading

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes a small use case bug with loading the progress loading

#### Please include detailed Test instructions for your pull request:
- Load [this project](https://github.com/unfoldingWord-dev/translationCore/files/3331674/58-PHM.usfm.zip) from usfm
- Make verse edits
- Load [this project](https://github.com/unfoldingWord-dev/translationCore/files/3331674/58-PHM.usfm.zip) from usfm under a different identifier
- Go to tool card

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6286)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (fe85c69)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-linux-x64-2.0.0-fe85c69.deb) is ready for download.
[macOS build 2.0.0 (fe85c69)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-macos-x64-2.0.0-fe85c69.dmg) is ready for download.
[Windows x64 build 2.0.0 (fe85c69)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-win-x64-2.0.0-fe85c69.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (fe85c69)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-win-x32-2.0.0-fe85c69.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6286)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
LGTM - need merge conflict resolved

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6286)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (62cfc4d)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-linux-x64-2.0.0-62cfc4d.deb) is ready for download.
[macOS build 2.0.0 (62cfc4d)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-macos-x64-2.0.0-62cfc4d.dmg) is ready for download.
[Windows x64 build 2.0.0 (62cfc4d)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-win-x64-2.0.0-62cfc4d.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (62cfc4d)](https://tc-builds.door43.org/build/bugfix-jay-6181-3/translationCore-win-x32-2.0.0-62cfc4d.setup.exe) is ready for download.

**Pull request merged**
