### PR TITLE
Feature - #3663 - Add importing OT projects

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Makes it so all restriction of New Testament Only is removed, especially for Online Import from Door43, per #3663 

#### Please include detailed Test instructions for your pull request:
- Check out this branch in tC and make sure all packages and apps are up to date
- Load tC, update Ancient Hebrew content
- On the project page do an Online Import. Make sure you can get any OT book from Door43 using the search by book in the interface
- Localization has been done for the books of the Bible in both the Online Import form and the Project Details form. There won't be Hindi translations when you review this, but once in develop I will make the translations on Crowdin.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (382712c)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-382712c.deb) is ready for download.
[macOS build 1.1.0 (382712c)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-382712c.dmg) is ready for download.
[Windows x64 build 1.1.0 (382712c)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-382712c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (382712c)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-382712c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0823066)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-0823066.deb) is ready for download.
[macOS build 1.1.0 (0823066)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-0823066.dmg) is ready for download.
[Windows x64 build 1.1.0 (0823066)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-0823066.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0823066)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-0823066.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6eb02ec)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-6eb02ec.deb) is ready for download.
[macOS build 1.1.0 (6eb02ec)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-6eb02ec.dmg) is ready for download.
[Windows x64 build 1.1.0 (6eb02ec)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-6eb02ec.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6eb02ec)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-6eb02ec.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
image
Is this supposed to say that? It says unsupported on wA as well

**Comment by richmahn** [comment]
@RoyalSix Yes, we can't do tW for OT books. This isn't what I worked on. They can only use WA. I worked on the book lists in Online Import and Project Details.

**Comment by richmahn** [comment]
Import the Ancient Hebrew to get an OL. WA needs a OL.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (5059670)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-5059670.deb) is ready for download.
[macOS build 1.1.0 (5059670)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-5059670.dmg) is ready for download.
[Windows x64 build 1.1.0 (5059670)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-5059670.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (5059670)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-5059670.setup.exe) is ready for download.

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 7 of 11 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: all files reviewed, 2 unresolved discussions (waiting on @richmahn)

___
*[src/js/common/BooksOfTheBible.js, line 146 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSRBJ-a-3jvZjsvrYM8:-LSRBJ-a-3jvZjsvrYM9:b-o7r847) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/common/BooksOfTheBible.js#L146)):*
> ```JavaScript
> };
> 
> export function getAllBibleBooks(translate=null) {
> ```

Just wondering if this the same as this?

```
export function getAllBibleBooks(translate= k => k) {
...
}
```
___
*[src/js/helpers/localizationHelpers.js, line 20 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSREeup1AB_NDlador3:-LSREeup1AB_NDlador4:b-t3me0z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/helpers/localizationHelpers.js#L20)):*
> ```JavaScript
>   let translation = nonTranslatable[key]; // check for static translation
>   if (!translation && translate) { // if not found, try translation lookup
>     console.log("here");
> ```

Console logs

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (64ec96b)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-64ec96b.deb) is ready for download.
[macOS build 1.1.0 (64ec96b)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-64ec96b.dmg) is ready for download.
[Windows x64 build 1.1.0 (64ec96b)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-64ec96b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (64ec96b)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-64ec96b.setup.exe) is ready for download.

**Review by richmahn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/common/BooksOfTheBible.js, line 146 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSRBJ-a-3jvZjsvrYM8:-LSVW2_rCY9oxHy3s6He:b-kfn0sg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/common/BooksOfTheBible.js#L146)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Just wondering if this the same as this?

```
export function getAllBibleBooks(translate= k => k) {
...
}
```
</blockquote></details>

Change made
___
*[src/js/helpers/localizationHelpers.js, line 20 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSREeup1AB_NDlador3:-LSVW5BcAdm6HsFSgQ24:bss4a2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/helpers/localizationHelpers.js#L20)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Console logs
</blockquote></details>

Removed.

**Review by richmahn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/common/BooksOfTheBible.js, line 146 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSRBJ-a-3jvZjsvrYM8:-LSVWChc3qTXOHoTHwns:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/common/BooksOfTheBible.js#L146)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Change made
</blockquote></details>

Done.
___
*[src/js/helpers/localizationHelpers.js, line 20 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-LSREeup1AB_NDlador3:-LSVWC-83aYztXfw8OGm:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/505967071ad885ea5819542ce5867b3c9f6b4de0/src/js/helpers/localizationHelpers.js#L20)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Done.

**Review by mannycolon — DISMISSED** [review]
> Reviewed 5 of 11 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

**Comment by mannycolon** [comment]
@richmahn Resolve merge conflicts

Suggested Fix:
```
rm -rf package-lock.json
npm i
```

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6afd03d)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-6afd03d.deb) is ready for download.
[macOS build 1.1.0 (6afd03d)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-6afd03d.dmg) is ready for download.
[Windows x64 build 1.1.0 (6afd03d)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-6afd03d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6afd03d)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-6afd03d.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-:-LSpTxii1kmm2l-Z6CXz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (2c40800)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-2c40800.deb) is ready for download.
[macOS build 1.1.0 (2c40800)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-2c40800.dmg) is ready for download.
[Windows x64 build 1.1.0 (2c40800)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-2c40800.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2c40800)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-2c40800.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6ed91cf)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-linux-x64-1.1.0-6ed91cf.deb) is ready for download.
[macOS build 1.1.0 (6ed91cf)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-macos-x64-1.1.0-6ed91cf.dmg) is ready for download.
[Windows x64 build 1.1.0 (6ed91cf)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x64-1.1.0-6ed91cf.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6ed91cf)](https://tc-builds.door43.org/build/feature-richmahn-3663/translationCore-win-x32-1.1.0-6ed91cf.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5461#-:-LSveNHVEqYChYHjy86I:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

**Pull request merged**
