### PR TITLE
Truncated Selection In Menu

### PR DESCRIPTION
**Pull request by RoyalSix**
This PR puts the selection on the side bar menu. If it is too long it is truncated. 

Try different selections and see if the selected word(s) appear next to the check reference as described in #1691

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2135)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/groupMenu/Group.js, line 62 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-KomtI5qip3Z7OMhDelh:-KomtI5rIQiLoooQcavi:bk7gvv9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bef212e2ea3db34331c725e0cbff09389ee61320/src/js/components/groupMenu/Group.js#L62)):*
> ```JavaScript
>     let selectionState = JSON.parse(JSON.stringify(this.props));
>     for (var groupItemData of groupData) {
>       let selectionsArray = [];
> ```

is it possible we could move this logic to an action of up to the container?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-KomtXruNJ5Jc1OdaCJW:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix Tests look good. I would only suggest adding marginLeft or paddingLeft to the selected text in the menu. It looks too close to the verse number.

**Comment by klappy** [comment]
To Manny's point, I'm wondering if the popup should not be positioned over the menu but to the right and over the check area? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-Kon2OIusLUtmsRKEcHd:b-aludzh)*

**Comment by klappy** [comment]
Or at least directly over the text itself and not the status glyph and reference like manny said, which may mean it overlaps the check area.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-Kon2ndgAjj2XUroU4Qi:b-9lp8g9)*

**Comment by RoyalSix** [comment]
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/groupMenu/Group.js, line 62 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-KomtI5qip3Z7OMhDelh:-Koo9EztBcN-g9SWLYSe:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2daee44d5b4d12c122d59c134a4c589d0de061/src/js/components/groupMenu/Group.js#L62)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is it possible we could move this logic to an action of up to the container?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135)*

**Comment by klappy** [comment]
Reviewed 4 of 7 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-KorZgVZdhjnO0pirTsV:bnfp4nl)*

**Comment by klappy** [comment]
My preference is to not pass components from containers to components via props. I'd like us to circle back and refactor this to just pass the required data through and then let the components turn the data into props. I feel like that helps tease apart the separation of concerns. Use the containers for business logic to adapt the data to the components needs, then let the components map the transformed data into the React components. 

What are your thoughts @mannycolon and @royalsix?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-KordmYYaC6nJGHGlveM:b1omg38)*

**Comment by RoyalSix** [comment]
I agree I really considered fixing how the group menu is structured. Its very difficult to manage right now. But I didn't want to chase the rabbit hole of going through that for this PR. But if your suggesting, and I also see the benefit then maybe I should just go ahead and do it?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2135#-:-KosL52a0EFh3aSd5A3-:bsimmi4)*

**Comment by klappy** [comment]
I just was thinking about next steps. We can move on for now. I'm more concerned with seeing what you guys thought.

**Pull request merged**
