### PR TITLE
init git repo, little cleanup for git module

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Uploading to D43 should now work.
Git Init is run before each save happens, which after research is harmless.
Addresses QA Fail for #974 

#### How to test this pull request:

Upload projects that do not have a .git folder in them, which should be most after our refactor.
To be sure, try on any USFM imported project.

Check QA issues #974 
Hand for the link, space between text and link.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2184)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184#-:-KpJGsfE_tIvZc-IE1DG:bnfp4nl)*

**Comment by klappy** [comment]
Updated Branch with Develop, can be merged when ready.

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184#-:-KpLbfCxlZTbm0dVWvSP:bnfp4nl)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184#-:-KpLboIGz6bYAL2KK55p:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2184)*

**Pull request merged**
