### PR TITLE
Refactoring of Build Process

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

This PR addresses issues with the Build Process.
The build process is now lighter, less code, mostly a few config files.

- [x] Mac x64 builds (dmg)
- [ ] Windows x86 builds (exe)
- [x] Testing on Linux x64 but no builds
- [x] Leveraging Electron-Forge.
- [x] Moved some essential files to be compatible and simplify the build process.
- [x] Updated references to essential files that were moved.
- [x] Non-destructive builds.

#### How to test this pull request:

- [ ] Delete `node_modules` folder from project.
- [ ] Run `npm install`
- [ ] Run `npm test` to make sure all tests still pass.
- [ ] Run `npm start` to make sure app still starts and runs.
- [ ] Load projects and tools to ensure all looks well.
- [ ] Run `npm make` on Mac to build the app.
- [ ] Run the generated app in the `out/make` to ensure local build works.
- [ ] Run `git status` to ensure the build was not destructive.

If Questions aren't answered in documentation let me know so it can be updated: https://github.com/unfoldingWord-dev/translationCore/wiki/Distributing-tC:-Package-Build-Publish 

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2120)

### CODE REVIEW

**Comment by RoyalSix** [comment]
klappys branch: https://github.com/klappy/translationCore/tree/develop

**Comment by RoyalSix** [comment]
`npm start` doesn't work for me but `electron .` works and the apps works as expected. Although it is a hair slower. This is the error I get on `npm start`: 
screen shot 2017-07-10 at 11 29 25 am

**Comment by RoyalSix** [comment]
After I manually installed `electron-forge` npm start works and the app is the same speed again.

**Comment by RoyalSix** [comment]
after running `npm run make` I got this error
`Jays-MBP:translationCore jay$ npm run make

> translationCore@0.7.1-beta.55 make /Users/jay/Desktop/translationCore
> electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Compiling Application
✔ Preparing native dependencies: 3 / 3
✔ Packaging Application
Making for the following targets:
⠋ Making for target: dmg - On platform: darwin - For arch: x64
An unhandled exception has occurred inside Forge:
Module version mismatch. Expected 48, got 53.
Error: Module version mismatch. Expected 48, got 53.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jay/Desktop/translationCore/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jay/Desktop/translationCore/node_modules/macos-alias/index.js:1:80)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translationCore@0.7.1-beta.55 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the translationCore@0.7.1-beta.55 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jay/.npm/_logs/2017-07-10T18_46_26_952Z-debug.log`

**Comment by mannycolon** [comment]
Reviewed 4 of 38 files at r1, 4 of 4 files at r3.
Review status: 8 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 24 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2120#-Kok5MVpZxY_97E7WTfb:-Kok5MVpZxY_97E7WTfc:b-hry9t3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/494933c075b94171b8c909cb6b034afd300bcf3a/package.json#L24)):*
> ```JSON
>   "repository": {
>     "type": "git",
>     "url": "git+https://github.com/klappy/translationCore.git"
> ```

do we want the code to point to your repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2120)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 29 of 38 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2120#-:-Kok61eUPlh9C233_4QY:bnfp4nl)*

**Comment by klappy** [comment]
@royalsix: I added a section in the documentation to follow for Electron-Forge installation. It covers deleting node_modules folder, installing e-f, npm install and you should be good.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2120#-:-Kom148INuEV2uEUCmNr:bu5b8uh)*

**Comment by mannycolon** [comment]
@klappy I was thinking that maybe we need to test this branch in a Windows environment

**Comment by klappy** [comment]
@mannycolon I have been testing on Windows concurrently. The build process isn't ready for Windows yet though. The PR is focused on Mac builds currently as well as my progress for Windows.

Once we get this merged we can have builds for QA on Mac.

**Comment by RoyalSix** [comment]
Looks like it had some trouble getting the loader image for tC when I did npm start but the build finds it just fine

screen shot 2017-07-11 at 6 04 32 pm

**Comment by RoyalSix** [comment]
updated comment^^

**Comment by klappy** [comment]
@RoyalSix: Nice catch. I'm fixing that reference and any others I can find.

**Comment by klappy** [comment]
@RoyalSix: Let me know if you find anything else.

**Comment by klappy** [comment]
@RoyalSix @mannycolon: All issues are resolved and updated with latest develop branch. Is there anything else you need to merge this? Each time we merge into develop branch this process gets harder the longer we wait.

**Pull request merged**
