### PR TITLE
Merge Conflict Testing

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Added testing for merge conflict helpers. All core functionality of merge conflicts is being tested with many different use cases. More use cases to be made in the future.

#### How to test this pull request:
run <code>npm test</code>

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2523)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix tests are failing on travis for some reason

**Comment by RoyalSix** [comment]
@mannycolon fixed :thumbsup:  

---

Review status: 0 of 307 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-:-KsN69r-np3VCDTzmYXb:b-rjnadd)*

**Comment by mannycolon** [comment]
Reviewed 3 of 309 files at r1.
Review status: 3 of 308 files reviewed at latest revision, 3 unresolved discussions.

---

*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPlSOOiuk15KtS_L9f:-KsPlSOOiuk15KtS_L9g:bf8vzxg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package-lock.json#L3)):*
> ```JSON
> {
>   "name": "translationCore",
>   "version": "0.7.1-beta.52",
> ```

do we want to reduce the version number? or this just happened by accident  

---

*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPl_LUhZTeCsV22ldD:-KsPl_LUhZTeCsV22ldE:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package.json#L4)):*
> ```JSON
>   "name": "translationCore",
>   "productName": "translationCore",
>   "version": "0.7.1-beta.52",
> ```

ibid

---

*[src/js/actions/CopyrightCheckActions.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPldsxk1wvnvQAHH0Q:-KsPldsxk1wvnvQAHH0R:bslym41) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/src/js/actions/CopyrightCheckActions.js#L41)):*
> ```JavaScript
>     } else {
>       // close project validation stepper
>       dispatch(ProjectValidationActions.cancelProjectValidationStepper())
> ```

this seems to come from a different PR. you may want to merge with develop.n

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by mannycolon** [comment]
@RoyalSix merge with develop

**Comment by RoyalSix** [comment]
@mannycolon updated to suggestions and merged

**Comment by RoyalSix** [comment]
Reviewed 1 of 309 files at r1.
Review status: 2 of 308 files reviewed at latest revision, 3 unresolved discussions.

---

*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPlSOOiuk15KtS_L9f:-KsQAS35Cd6Y9wITdTex:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package-lock.json#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we want to reduce the version number? or this just happened by accident  
</blockquote></details>

Fixed.

---

*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPl_LUhZTeCsV22ldD:-KsQAUORV69GM3LXujIT:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package.json#L4)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Fixed.

---

*[src/js/actions/CopyrightCheckActions.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPldsxk1wvnvQAHH0Q:-KsQAWD0uYs4HAA-f2qh:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/src/js/actions/CopyrightCheckActions.js#L41)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this seems to come from a different PR. you may want to merge with develop.n
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by klappy** [comment]
*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPlSOOiuk15KtS_L9f:-KsdAC1nx31LBVEEmqWq:b-pci4o7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package-lock.json#L3)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

I don't see this fixed yet. Do you need to push again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by klappy** [comment]
Reviewed 2 of 309 files at r1.
Review status: 2 of 297 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by klappy** [comment]
Reviewed 1 of 13 files at r2.
Review status: 3 of 297 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by klappy** [comment]
Reviewed 3 of 13 files at r2.
Review status: 3 of 297 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by mannycolon** [comment]
Reviewed 295 of 309 files at r1, 4 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[package-lock.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPlSOOiuk15KtS_L9f:-KsdvKEy7QAAwSZeVCje:bjsedcq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package-lock.json#L3)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I don't see this fixed yet. Do you need to push again?
</blockquote></details>

is this fixed yet?

---

*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPl_LUhZTeCsV22ldD:-KsdvNmlkfqWaHchWs0B:b-6bn6zq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package.json#L4)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

is this fixed yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by mannycolon** [comment]
@RoyalSix could you resolve the merge conflicts for: 
```
package-lock.json
package.json
```

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523#-KsPl_LUhZTeCsV22ldD:-KseCoIoU5R20TJP8RvC:b-2r93j6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/da31ba981bc96c1e06c845808f95f11e54dbb49b/package.json#L4)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this fixed yet?n
</blockquote></details>

I think its supposed to be 
```
"version": "0.7.1-beta.55"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Comment by mannycolon** [comment]
Reviewed 1 of 309 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2523)*

**Pull request merged**
