### PR TITLE
check data grabber: refactored View to Container

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/443)

### CODE REVIEW

**Comment by ihoegen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/core/create_project/CheckDataGrabber.js, line 59 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/443#-K_aKrlx7K1fW4FbXGjt:-K_aKrlx7K1fW4FbXGju:bhdokje) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36a7f9f4b5bd43ac49518667f89e2c1f988a05a6/src/js/components/core/create_project/CheckDataGrabber.js#L59)):*
> ```JavaScript
>     try {
>       for (let module of checkArray) {
>         let viewObj = require(Path.join(module.location, 'Container'));
> ```

We should keep support for tools that use View as well. Maybe we can use the Main property in the tool's manifest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/443)*

**Comment by ihoegen** [comment]
Or instead we could use the main property of the tools manifest.

**Comment by mannycolon** [comment]
using the main property of the manifest sounds like a good idea
@ihoegen

**Comment by ihoegen** [comment]
And in the line following that, where it can either be `viewObj.view` or `viewObj.container`, we could probably just use `viewObj.container || viewObj.view`

**Comment by mannycolon** [comment]
@ihoegen makes sense

**Pull request closed without merging**
