### PR TITLE
User Login Persistence

### PR DESCRIPTION
**Pull request by RoyalSix**
Resolves issue #273

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/290)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Requires npm install

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/290)_

**Comment by mannycolon** [comment]
@RoyalSix you forgot to save **crypto-js**to the dependencies

**Comment by mannycolon** [comment]
@RoyalSix great job. I'm ready to merge your branch just add **crypto-js** to the package.JSON dependencies

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/290)_

**Pull request merged**
