### PR TITLE
Lw error messages

### PR DESCRIPTION
**Pull request by EllDoubleYew**
#### This pull request addresses:

This addresses https://github.com/unfoldingWord-dev/translationCore/issues/1246 and https://github.com/unfoldingWord-dev/translationCore/issues/1245

#### How to test this pull request:

Try and login with a wrong account, the message should be different now. Try and login with no internet connection. You should get a different error now.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1344)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/LoginActions.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-KiqrJ0TM-YUa9z7LZVl:-KiqrJ0TM-YUa9z7LZVm:b5ycdx4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ebd1b6580454d2c696c5ce03fb29cef4c1b0ce5f/src/js/actions/LoginActions.js#L44)):*
> ```JavaScript
>         dialog.showErrorBox('Login Failed', 'Invalid username or password');
>       } else {
>         dialog.showErrorBox('Login Failed', 'Either you are not connected to the internet or something is wrong with the GOGS server');
> ```

I dont think this is the desired message error we wanted. consult with Whitfield about this story.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344)*

**Comment by klappy** [comment]
*[src/js/components/core/licenses/ThirdParty.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-KirOjzV8T-LbLtDoIqO:-KirOjzWJp9RzVm4g54c:bmekaov) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ebd1b6580454d2c696c5ce03fb29cef4c1b0ce5f/src/js/components/core/licenses/ThirdParty.js#L12)):*
> ```JavaScript
>           <center>{license}</center>
>           <center>{Licenses[license].licenses}</center>
>           <center><a href={Licenses[license].repository}>link to license</a></center>
> ```

This is a link to the repository, not the license.
Let's update the text to match what it does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344)*

**Comment by klappy** [comment]
*[src/js/components/core/licenses/ThirdParty.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-KirOjzV8T-LbLtDoIqO:-KirPFh5Ly440AY9VsA6:b-8kbbwq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ebd1b6580454d2c696c5ce03fb29cef4c1b0ce5f/src/js/components/core/licenses/ThirdParty.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This is a link to the repository, not the license.
Let's update the text to match what it does.
</blockquote></details>

Can you update this from develop first? Whitfield has updated this to remove the log and to fix the key issue for the list. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344)*

**Comment by EllDoubleYew** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/LoginActions.js, line 44 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-KiqrJ0TM-YUa9z7LZVl:-Kj3zANjRomxD4z_pYBe:b-xgusox) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ebd1b6580454d2c696c5ce03fb29cef4c1b0ce5f/src/js/actions/LoginActions.js#L44)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I dont think this is the desired message error we wanted. consult with Whitfield about this story.
</blockquote></details>

I have no information about different verbiage on this error. 

---

*[src/js/components/core/licenses/ThirdParty.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-KirOjzV8T-LbLtDoIqO:-Kj3z1lPJDbzmxOB4BhY:b-20xgam) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ebd1b6580454d2c696c5ce03fb29cef4c1b0ce5f/src/js/components/core/licenses/ThirdParty.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you update this from develop first? Whitfield has updated this to remove the log and to fix the key issue for the list. 
</blockquote></details>

This PR does not address anything to do with licensing. There was a console.log() left in this file from a previous PR that was removed in this one. Sorry for the confusion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344)*

**Comment by mannycolon** [comment]
@EllDoubleYew consult with @cdwhitfield73  about the verbiage. he had suggested catching specific errors that seemed like a good idea for this issue.

**Comment by mannycolon** [comment]
@EllDoubleYew so whats holding this back??

**Comment by mannycolon** [comment]
@EllDoubleYew so whats holding this back??

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1344#-:-KjJDbUx43Ykex1N4HRu:bnfp4nl)*

**Pull request merged**
