### PR TITLE
Add templates

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:
Recently, there has been an issue where pull requests have not been detailed enough. This pull request address this by adding a default template for pull requests.

#### How to test this pull request:
Take a look at the template. If you feel that more things are needed, comment. Otherwise, merge.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/757)

### CODE REVIEW

**Comment by mannycolon** [comment]
@ihoegen great idea. Will review in a few min.

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/757)*

**Comment by mannycolon** [comment]
@ihoegen maybe we could add some suggestions to how to make PRs for tools commits

**Comment by ihoegen** [comment]
Yeah, I can add that to the contributing.md file. I'll also copy the pull request template to all the tools as well

**Comment by mannycolon** [comment]
@ihoegen ok cool

**Comment by ihoegen** [comment]
@mannycolon Updated the contributing files, copying pull request template to the tools now. I'll add those to this pull request

**Comment by ihoegen** [comment]
@mannycolon Just added the PR template to all tools that are under active development

**Pull request merged**
