### PR TITLE
Localized Components

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This update provides localization for most of the components within the application.
There are still a number of items that need localization. However, these will require some major refactoring therefore I'll put those in a separate PR.

This makes progress on #2265.

#### How to test this pull request:

You won't be able to see any changes by running the app since all of the localization are defaulting to English at the moment. Therefore it's sufficient to simply ensure the application opens properly without crashing. You could also check in the console to ensure there are no errors about missing translation keys.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3699)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 90 of 126 files at r1.
Review status: 89 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[__tests__/LocaleSettings.test.js, line 49 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L47_yccq2UQM3VyhQi4:-L47_yccq2UQM3VyhQi5:b-nmp08d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/__tests__/LocaleSettings.test.js#L49)):*
> ```JavaScript
>         let addTranslationActions = store.getActions().map(action => {
>           if(action.type === '@@localize/ADD_TRANSLATION_FOR_LANGUGE') return action;
>         });
> ```

Just wondering does this actually test that it actually changes the locale to en_US?

---

*[src/js/components/projectValidation/ProjectValidationContentWrapper.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L481kxsb2kdWSLrjzy2:-L481kxts2cQYeq0Q8bO:b-7maraf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/projectValidation/ProjectValidationContentWrapper.js#L21)):*
> ```JavaScript
>  * @constructor
>  */
> const ProjectValidationContentWrapper = ({instructions, translate, children}) => (
> ```

This component name threw me off, maybe ProjectValidationInstructionsWrapper suits better? Or is it not strictly being used for instructions?

---

*[src/js/containers/home/HomeContainer.js, line 55 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L48CQ7lcY3aKAGtJDGO:-L48CQ7lcY3aKAGtJDGP:bgmo664) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/containers/home/HomeContainer.js#L55)):*
> ```JavaScript
>     switch (stepIndex) {
>       case 0:
>         displayContainer = <Overview {...this.props}/>;
> ```

Need all the props here? or just translate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by RoyalSix** [comment]
I noticed that in the translations you left the variables as apart of the strings, is that best practice for that library?
<s>I'm just thinking about long term having to hand off translations to other people if it makes sense to have those in there because that variable is independent of the translation and there is no way to change it besides in the code.</s>

** edit ** 
Actually I see you're only doing that for certain things...Im guessing that the library finds the corresponding translation for those things so you don't have to do a double translation.

Also wondering about best practice for having html in the translation

**Comment by RoyalSix** [comment]
Reviewed 34 of 126 files at r1.
Review status: 123 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by RoyalSix** [comment]
Good job on this by the way, looks like alot of work haha

---

Review status: 123 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-:-L48I_zV2lIk-_3YViP_:brox5mg)*

**Comment by da1nerd** [comment]
yes this library does provide support for injecting variables out of the box. I'm only using it for things that should not be translated themselves, e.g. proper nouns, file names, paths, etc.

Usually this will be things stored in the `_` namespace e.g. `translate('_.app_name')` will produce `translationCore`.
I didn't have to store the non-translatable things there, it just seems convenient to have it all in one place.

The tool we are using for translation (Crowdin) has very good support for translating strings that contain html. Although I do not personally prefer including html in translation strings, there was no other good way to format the strings. And I'm very much against splitting up the text so we can fit it around html markup.

---

Review status: 123 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[__tests__/LocaleSettings.test.js, line 49 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L47_yccq2UQM3VyhQi4:-L48HI9b9k-HX9_Q03yO:b8ut6w9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/__tests__/LocaleSettings.test.js#L49)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Just wondering does this actually test that it actually changes the locale to en_US?
</blockquote></details>

yes. in this test we are testing the creation of an action. All it needs to do is check that the action was generated correctly. 
A few lines further down we make assertions that we've added some keys to the translation.
We don't care to test if the changes were actually persisted to the store because the code surrounding that is form a third party library.

---

*[src/js/components/projectValidation/ProjectValidationContentWrapper.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L481kxsb2kdWSLrjzy2:-L48IFktSPJxyy_tJXZ0:bd56yzv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/projectValidation/ProjectValidationContentWrapper.js#L21)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This component name threw me off, maybe ProjectValidationInstructionsWrapper suits better? Or is it not strictly being used for instructions?
</blockquote></details>

It does hold the instructions, but it's also holding the content of the component. So an argument could be made for both names. I'm not particularly fond of using "wrapper" in class names either because it's very ambiguous, but I wasn't feeling especially inspired at the moment.

---

*[src/js/containers/home/HomeContainer.js, line 55 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L48CQ7lcY3aKAGtJDGO:-L48J-t-T8RHj1f3PlEl:b-o5ti0r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/containers/home/HomeContainer.js#L55)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Need all the props here? or just translate?
</blockquote></details>

it probably doesn't. I left it there for legacy's sake (trying not to change everything touch).
However, in general I prefer not to blindly pass parameters like that because it makes it harder to read the flow of data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-:-L48JbnRbhZ0-L4uDygv:b8fv7ly)*

**Comment by RoyalSix** [comment]
Review status: 123 of 125 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/components/projectValidation/ProjectValidationContentWrapper.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L481kxsb2kdWSLrjzy2:-L49EWwBPnrcjMAf7Fkr:b-md3m9i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/projectValidation/ProjectValidationContentWrapper.js#L21)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

It does hold the instructions, but it's also holding the content of the component. So an argument could be made for both names. I'm not particularly fond of using "wrapper" in class names either because it's very ambiguous, but I wasn't feeling especially inspired at the moment.
</blockquote></details>

Oh I didn't see the children component hahah my bad, I guess thats what happens when you review lots of files fast. :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 126 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-:-L49FJ1nGLocyjgw8CA4:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 40 of 126 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/components/home/overview/UserCard.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4Cy1ae7ELCNPt9Ezd7:-L4Cy1ae7ELCNPt9Ezd8:b-2jfje4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/home/overview/UserCard.js#L9)):*
> ```JavaScript
> import UserCardMenu from '../usersManagement/UserCardMenu';
> import Hint from '../../Hint';
> import {getLocaleLanguages, getLocaleSettingsOpen} from '../../../reducers';
> ```

Why are we getting getLocaleLanguages and getLocaleSettingsOpenfrom the reducers file and not from the state or an action or helper instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by mannycolon** [comment]
Reviewed 47 of 126 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by mannycolon** [comment]
Reviewed 38 of 126 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/index.js, line 72 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D1IFG_EG-Qi2sY8Op:-L4D1IFG_EG-Qi2sY8Oq:bl4veqf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/reducers/index.js#L72)):*
> ```JavaScript
> 
> /**
>  * Retrieves an application setting
> ```

just wondering if the functions below should be helpers or actions 

---

*[src/locale/Spanish-es_ES.json, line 135 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D3C0lO-XwFLl9uB_Z:-L4D3C0lO-XwFLl9uB__:b-lh7su3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/locale/Spanish-es_ES.json#L135)):*
> ```JSON
>       "select_project": "Seleccione un proyecto",
>       "select_tool": "Seleccione una herramienta",
>       "launch": "Lanzamiento",
> ```

this should be 'Lanzar' not 'lanzamiento' lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by da1nerd** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/components/home/overview/UserCard.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4Cy1ae7ELCNPt9Ezd7:-L4DsAMoLss4BspdCEGb:b-b7ungd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/home/overview/UserCard.js#L9)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Why are we getting getLocaleLanguages and getLocaleSettingsOpenfrom the reducers file and not from the state or an action or helper instead?
</blockquote></details>

Because that's the suggested pattern for redux.
There are a number of benefits to this pattern:

1. keeps business logic and business data in a single location for better clarity.
2. if  you make changes to the state structure you only have to update the reducer.
3. makes business logic easier to test
4. make reducers easier to test
5. makes components easier to test

---

*[src/js/reducers/index.js, line 72 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D1IFG_EG-Qi2sY8Op:-L4DsyyvczzEhCGakHQh:bl125dj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/reducers/index.js#L72)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

just wondering if the functions below should be helpers or actions 
</blockquote></details>

In redux the suggested pattern is to encapsulate the logic for retrieving state within the reducers. These methods  are referred to as "selectors".
Then we expose all the selectors in our reducer index.js file in which we give slices of the state object to the selectors.
This is a lot of extra boiler plate., but the benefits long term are easier state management especially for large projects.

Here's a video where the creator of redux explains this pattern  https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers.

Btw that whole course is a really good watch.

---

*[src/locale/Spanish-es_ES.json, line 135 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D3C0lO-XwFLl9uB_Z:-L4DtipuhiQ27q6f7AWS:b-rgu3si) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/locale/Spanish-es_ES.json#L135)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should be 'Lanzar' not 'lanzamiento' lol
</blockquote></details>

Oops! Hey I only speak English and a little German :)
The translations were ran through google translate just to illustrate the localization.
There is going to be a review of the current strings before we formally translate them. So these will all get handled at a later time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699)*

**Comment by da1nerd** [comment]
@mannycolon btw, I forgot I had used selectors in these changes. I was going to bring it up to the team before going down my own path. But, I got sick today and missed all the meetings.
Sorry to dump all these changes on you guys.

I would like to know what you think about the selector paradigm. It's described here: https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers

**Comment by richmahn** [comment]
This also LGTM from my review yesterday, but I see Manny has seen things I wasn't able to see, so will let him be the 2nd reviewer.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 126 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/components/home/overview/UserCard.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4Cy1ae7ELCNPt9Ezd7:-L4HvuhxaRs5CMicw28n:b3o46h1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/components/home/overview/UserCard.js#L9)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Because that's the suggested pattern for redux.
There are a number of benefits to this pattern:

1. keeps business logic and business data in a single location for better clarity.
2. if  you make changes to the state structure you only have to update the reducer.
3. makes business logic easier to test
4. make reducers easier to test
5. makes components easier to test
</blockquote></details>

Awesome Thank you so much for taking the time to explain it. It makes a lot more sense now. 

---

*[src/js/reducers/index.js, line 72 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D1IFG_EG-Qi2sY8Op:-L4Hw884NAeF6tYUucwR:bmb91qq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/js/reducers/index.js#L72)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

In redux the suggested pattern is to encapsulate the logic for retrieving state within the reducers. These methods  are referred to as "selectors".
Then we expose all the selectors in our reducer index.js file in which we give slices of the state object to the selectors.
This is a lot of extra boiler plate., but the benefits long term are easier state management especially for large projects.

Here's a video where the creator of redux explains this pattern  https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers.

Btw that whole course is a really good watch.
</blockquote></details>

Thank you so much. I will take a look at the video. very helpful.

---

*[src/locale/Spanish-es_ES.json, line 135 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-L4D3C0lO-XwFLl9uB_Z:-L4HwMCH2TQMszx6D4P5:b-jutzdw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a14518fc0a2d2d93ec7d2a24aa63fe5e169dfc76/src/locale/Spanish-es_ES.json#L135)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Oops! Hey I only speak English and a little German :)
The translations were ran through google translate just to illustrate the localization.
There is going to be a review of the current strings before we formally translate them. So these will all get handled at a later time.
</blockquote></details>

haha I was joking. nothing to worry about lol. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3699#-:-L4HvrTNh0uPtrll0B7o:bnfp4nl)*

**Pull request merged**
