### PR TITLE
Created check data loading actions

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

**Loading Data from Data Persistence #985**
Added loading actions to load comments, reminders, selections and verseEdits data from the filesystem

#### How to test this pull request:
- Import the loading actions in ToolsContainer.js and then call them inside a componentWillMount() function.
- Make sure you have the files previously saved in the file system in the appropriate directory.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1006)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-:-KgZWfxVe2mplLocStwH:bnfp4nl)*

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/actions/checkDataLoadActions.js, line 68 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-KgZtl5Cd454_Nyd-L_6:-KgZtl5Dl-tq_ANTjnBA:b-5m8auh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/972195f3c3877a5eb9fdc13fc51d61a4d1675b31/src/js/actions/checkDataLoadActions.js#L68)):*
> ```JavaScript
> }
> 
> export function loadComments() {
> ```

Can we get some documentation on these functions?

---

*[src/js/utils/saveMethods.js, line 78 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-KgZu2g-nscoa0IXmHH9:-KgZu2g-nscoa0IXmHHA:b8xexgh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/972195f3c3877a5eb9fdc13fc51d61a4d1675b31/src/js/utils/saveMethods.js#L78)):*
> ```JavaScript
>  * @param {string} checkDataName - checkDate folder name where data is saved.
>  *  @example 'comments', 'reminders', 'selections', 'verseEdits' etc.
>  * @param {object} reducer - comments/reminders/selections/verseEdits reducer
> ```

Rather than have the entire reducer passed, would it make more sense to just pass the timestamp if that is all we use? I could completely be wrong here but I just don't see why we would need to pass the entire object if we are just using one of its attributes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006)*

**Comment by mannycolon** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/checkDataLoadActions.js, line 68 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-KgZtl5Cd454_Nyd-L_6:-Kg_B3_MoicpRp-CU5ng:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/972195f3c3877a5eb9fdc13fc51d61a4d1675b31/src/js/actions/checkDataLoadActions.js#L68)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Can we get some documentation on these functions?
</blockquote></details>

Done.

---

*[src/js/utils/saveMethods.js, line 78 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-KgZu2g-nscoa0IXmHH9:-Kg_B5_IsfCNkko6-vmP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/972195f3c3877a5eb9fdc13fc51d61a4d1675b31/src/js/utils/saveMethods.js#L78)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Rather than have the entire reducer passed, would it make more sense to just pass the timestamp if that is all we use? I could completely be wrong here but I just don't see why we would need to pass the entire object if we are just using one of its attributes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006)*

**Comment by EllDoubleYew** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1006#-:-Kgafjqp-f_ufn1tQ8Lz:bnfp4nl)*

**Pull request merged**
