### PR TITLE
Refactoring tools reducer to support new tool loading.

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4672. This does not complete the issue. This is simply an incremental PR to avoid a HUGE PR to review later.

- refactored tool loading
- refactored tool reducer
- migrated all direct reducer references to selectors.

#### Please include detailed Test instructions for your pull request:
The application should function normally without any new features.
- open a project in tW and wA and ensure things don't explode!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (2797945)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-2797945.deb) is ready for download.
[macOS build 1.1.0 (2797945)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-2797945.dmg) is ready for download.
[Windows x64 build 1.1.0 (2797945)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-2797945.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2797945)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-2797945.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-a38e8d9.deb) is ready for download.
[macOS build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-a38e8d9.dmg) is ready for download.
[Windows x64 build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-a38e8d9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-a38e8d9.setup.exe) is ready for download.

**Review by richmahn — CHANGES_REQUESTED** [review]
> Reviewed 24 of 42 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 27 of 44 files reviewed, 3 unresolved discussions (waiting on @neutrinog)

___
*[src/js/actions/ContextIdActions.js, line 131 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4FSjg8INeOuucCXJc:-LT4FSjg8INeOuucCXJd:b-kllc22) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/ContextIdActions.js#L131)):*
> ```JavaScript
>     let { projectSaveLocation, manifest } = state.projectDetailsReducer;
>     let { groupsIndex } = state.groupsIndexReducer;
>     const currentToolName = getSelectedToolName(state);
> ```

Think it is best to keep the same variable name where this is used, thus `selectedToolName` would be better
___
*[src/js/actions/GroupsDataActions.js, line 36 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4OydD1gv8UaJlZVtm:-LT4OydE-HPbOFum3m4W:bi2ot7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/GroupsDataActions.js#L36)):*
> ```JavaScript
>   return ((dispatch, getState) => {
>     const state = getState();
>     const toolName = getSelectedToolName(state);
> ```

Here as well, selectedToolName would be clearer.
___
*[src/js/actions/SourceContentUpdatesActions.js, line 87 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4PEghAktMgvY5Zf9t:-LT4PEghAktMgvY5Zf9u:b-4dnu6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/SourceContentUpdatesActions.js#L87)):*
> ```JavaScript
>     const translate = getTranslate(getState());
>     const contextId = getContext(getState());
>     const currentToolName = getSelectedToolName(getState());
> ```

name variable selectedToolName

**Review by richmahn — CHANGES_REQUESTED** [review]
> Reviewed 5 of 42 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 33 of 44 files reviewed, 4 unresolved discussions (waiting on @neutrinog)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 21 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4QteyDcKjkm8Qw0bw:-LT4QteyDcKjkm8Qw0bx:b-mmpos7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/gatewayLanguageHelpers.js#L21)):*
> ```JavaScript
> export const getGatewayLanguageCodeAndQuote = (state, contextId = null) => {
>   const { currentProjectToolsSelectedGL } = state.projectDetailsReducer;
>   const currentToolName= getSelectedToolName(state);
> ```

use selectedToolName and put a space after.

**Review by richmahn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 33 of 44 files reviewed, 5 unresolved discussions (waiting on @neutrinog)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 40 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4Qyme2v4AwVZJdlfF:-LT4Qyme2v4AwVZJdlfG:begqb5v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/gatewayLanguageHelpers.js#L40)):*
> ```JavaScript
> export const getGatewayLanguageCode = (state) => {
>   const currentProjectToolsSelectedGL = state.projectDetailsReducer && state.projectDetailsReducer.currentProjectToolsSelectedGL;
>   const currentToolName = getSelectedToolName(state);
> ```

selectedToolName

**Review by richmahn — CHANGES_REQUESTED** [review]
> Reviewed 3 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 36 of 44 files reviewed, 6 unresolved discussions (waiting on @neutrinog)

___
*[src/js/helpers/ResourcesHelpers.js, line 438 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4R4HeBT2jGbNy8gQx:-LT4R4HeBT2jGbNy8gQy:begqb5v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/ResourcesHelpers.js#L438)):*
> ```JavaScript
>   addResource(resources, olLanguageID, olBibleId); // make sure loaded even if not in pane settings
>   const gatewayLangId = getGatewayLanguageCode(state) || 'en'; // default to English
>   const currentToolName = getSelectedToolName(state);
> ```

selectedToolName

**Review by richmahn — COMMENTED** [review]
> Reviewed 5 of 42 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: all files reviewed, 6 unresolved discussions (waiting on @neutrinog)

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-a38e8d9.deb) is ready for download.
[macOS build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-a38e8d9.dmg) is ready for download.
[Windows x64 build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-a38e8d9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a38e8d9)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-a38e8d9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d134e39)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-d134e39.deb) is ready for download.
[macOS build 1.1.0 (d134e39)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-d134e39.dmg) is ready for download.
[Windows x64 build 1.1.0 (d134e39)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-d134e39.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d134e39)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-d134e39.setup.exe) is ready for download.

**Review by richmahn — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: all files reviewed, 6 unresolved discussions (waiting on @neutrinog)

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: all files reviewed, 6 unresolved discussions (waiting on @richmahn)

___
*[src/js/actions/ContextIdActions.js, line 131 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4FSjg8INeOuucCXJc:-LT4itULEVhtsFuNga1g:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/ContextIdActions.js#L131)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Think it is best to keep the same variable name where this is used, thus `selectedToolName` would be better
</blockquote></details>

Done.
___
*[src/js/actions/GroupsDataActions.js, line 36 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4OydD1gv8UaJlZVtm:-LT4iwim9LRznJp47zxF:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/GroupsDataActions.js#L36)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Here as well, selectedToolName would be clearer.
</blockquote></details>

Done.
___
*[src/js/actions/SourceContentUpdatesActions.js, line 87 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4PEghAktMgvY5Zf9t:-LT4j-R2CXXdnI25_w3D:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/actions/SourceContentUpdatesActions.js#L87)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

name variable selectedToolName
</blockquote></details>

Done.
___
*[src/js/helpers/gatewayLanguageHelpers.js, line 21 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4QteyDcKjkm8Qw0bw:-LT4j4tq3xOhVpG_yFGI:b-rydwq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/gatewayLanguageHelpers.js#L21)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

use selectedToolName and put a space after.
</blockquote></details>

come on.. you're going to make me create a PR just to include a space?
___
*[src/js/helpers/gatewayLanguageHelpers.js, line 40 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4Qyme2v4AwVZJdlfF:-LT4jCye73EiS7nXbDaG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/gatewayLanguageHelpers.js#L40)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

selectedToolName
</blockquote></details>

Done.
___
*[src/js/helpers/ResourcesHelpers.js, line 438 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4R4HeBT2jGbNy8gQx:-LT4jGtWCw3aRt_b0Ebu:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/ResourcesHelpers.js#L438)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

selectedToolName
</blockquote></details>

Done.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 48 of 49 files reviewed, 6 unresolved discussions (waiting on @richmahn)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 21 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-LT4QteyDcKjkm8Qw0bw:-LT4kjY627FhzSxJgn4L:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a38e8d977b3928332d0ce199cec960de2c6b5fa5/src/js/helpers/gatewayLanguageHelpers.js#L21)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

come on.. you're going to make me create a PR just to include a space?
</blockquote></details>

Done.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-ada8860.deb) is ready for download.
[macOS build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-ada8860.dmg) is ready for download.
[Windows x64 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-ada8860.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-ada8860.setup.exe) is ready for download.

**Review by richmahn — COMMENTED** [review]
Code review: :lgtm: 
Local testing: :lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531#-:-LT56iQX07LeVrCPYGdw:bg6bxn)* status: 48 of 49 files reviewed, 6 unresolved discussions (waiting on @richmahn)

**Review by richmahn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: 48 of 49 files reviewed, all discussions resolved (waiting on @richmahn)

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-ada8860.deb) is ready for download.
[macOS build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-ada8860.dmg) is ready for download.
[Windows x64 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-ada8860.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-ada8860.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-ada8860.deb) is ready for download.
[macOS build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-ada8860.dmg) is ready for download.
[Windows x64 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-ada8860.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ada8860)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-ada8860.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (59fbd9e)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-59fbd9e.deb) is ready for download.
[macOS build 1.1.0 (59fbd9e)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-59fbd9e.dmg) is ready for download.
[Windows x64 build 1.1.0 (59fbd9e)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-59fbd9e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (59fbd9e)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-59fbd9e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (67ba192)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-linux-x64-1.1.0-67ba192.deb) is ready for download.
[macOS build 1.1.0 (67ba192)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-macos-x64-1.1.0-67ba192.dmg) is ready for download.
[Windows x64 build 1.1.0 (67ba192)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x64-1.1.0-67ba192.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (67ba192)](https://tc-builds.door43.org/build/enhancement_joel_4672_load-tool-api/translationCore-win-x32-1.1.0-67ba192.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5531)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
