### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5367)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (052e316)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-052e316.deb) is ready for download.
[macOS build 1.1.0 (052e316)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-052e316.dmg) is ready for download.
[Windows x64 build 1.1.0 (052e316)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-052e316.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (052e316)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-052e316.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
Some builds failed

**Comment by dsm-git** [comment]
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (46c5566)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-46c5566.deb) is ready for download.
[macOS build 1.1.0 (46c5566)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-46c5566.dmg) is ready for download.
[Windows x64 build 1.1.0 (46c5566)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-46c5566.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (46c5566)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-46c5566.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5367)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e800ea2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e800ea2.deb) is ready for download.
[macOS build 1.1.0 (e800ea2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e800ea2.dmg) is ready for download.
[Windows x64 build 1.1.0 (e800ea2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e800ea2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e800ea2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e800ea2.setup.exe) is ready for download.

**Pull request merged**
