### PR TITLE
Remove links from thelps in offline

### PR DESCRIPTION
**Pull request by EllDoubleYew**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/748)

### CODE REVIEW

**Comment by RoyalSix** [comment]
I'm still seeing links offline @EllDoubleYew

**Comment by ihoegen** [comment]
This PR might be irrelevant now...

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/748)*

**Comment by ihoegen** [comment]
We should wait on this pull request, my PR on translationHelps kind of takes care of this indirectly

**Comment by EllDoubleYew** [comment]
This issue is addressed in https://github.com/unfoldingWord-dev/translationCore/pull/753. Closed

**Pull request closed without merging**
