### PR TITLE
Require signin

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request clears the project when signing out, and when signed out, only lets a user open the login tab. 

#### How to test this pull request:

Sign out, try to load a project. Sign in, load project, sign out

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1518)

### CODE REVIEW

**Comment by cdwhitfield73** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-Kjs1JjF8a2aUVEGoQcr:-Kjs1JjF8a2aUVEGoQcs:bg93lpq) (no related file):*
Functionality works great...but you need to change the two NotificationActions.showNotification to AlertModalActions.openAlertDialog to use the new standard dialog box instead of the snack bar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-:-Kjs5YLhBGXEDRJKA2dl:bnfp4nl)*

**Comment by mannycolon** [comment]
@ihoegen address merge conflicts

**Comment by mannycolon** [comment]
@ihoegen never mind i got the merge conflicts fixed for you lol

**Comment by cdwhitfield73** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-:-Kjt8SuIoIJIXOkyeVEh:bnfp4nl)*

**Comment by cdwhitfield73** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-Kjs1JjF8a2aUVEGoQcr:-Kjt8YMuCLCQW16cgKQZ:b-3m4b7h) (no related file):*
<details><summary><i>Previously, cdwhitfield73 wrote…</i></summary><blockquote>

Functionality works great...but you need to change the two NotificationActions.showNotification to AlertModalActions.openAlertDialog to use the new standard dialog box instead of the snack bar
</blockquote></details>

This has been fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518)*

**Comment by cdwhitfield73** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-Kjs1JjF8a2aUVEGoQcr:-Kjt97sLnXOR6Jn5d1yC:b32w0x) (no related file):*
<details><summary><i>Previously, cdwhitfield73 wrote…</i></summary><blockquote>

This has been fixed
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518)*

**Comment by cdwhitfield73** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-Kjs1JjF8a2aUVEGoQcr:-Kjt9Mtk-Ghi9xfs13KB:bg7igkv) (no related file):*
<details><summary><i>Previously, cdwhitfield73 wrote…</i></summary><blockquote>

OK
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518)*

**Comment by cdwhitfield73** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1518#-:-KjtDdME_KgUHYEGlz2R:bnfp4nl)*

**Pull request merged**
