### PR TITLE
USFM Export Fix For False Positive Merge Conflicts

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes the behavior of a merge conflict not getting reset in the data and causing usfm export to think there is a conflict even though it is from the last project. 

#### Please include detailed Test instructions for your pull request:
1. Import https://git.door43.org/tc06/en-x-demo1_php_text_ulb
2. Resolve the merge conflicts and open in Word Alignment
3. Go back to the projects page
4. Click on the 3 dot menu on a different project and choose Export to USFM
5. You should not get an alert saying that there were merge conflicts
#### Standard Test Instructions for PR Review Process:

- [x] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [x] Checkout the branch locally and ensure that app runs as expected
  - [x] Ensure tests pass
  - [x] Open and watch the console for errors
  - [x] Make sure all actions perform as expected
  - [x] Import and Load a new Project
  - [x] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4149)

### CODE REVIEW

**Comment by bspidel** [comment]
When I import project referenced in PR, I see the following on console. Do not know if it is significant.

e/react-devtools-faq
C:\Users\Owner\Projects\translationCore\node_modules\fbjs\lib\warning.js:33 Warning: Failed prop type: The prop `chapter` is marked as required in `MergeConflictsCheck`, but its value is `undefined`.
    in MergeConflictsCheck (created by MergeConflictsCheck)
    in MergeConflictsCheck (created by ProjectValidationContainer)
    in div (created by ProjectValidationContainer)
    in div (created by DialogInline)
    in div (created by Paper)
    in Paper (created by DialogInline)
    in div (created by TransitionItem)
    in TransitionItem (created by TransitionGroup)
    in div (created by TransitionGroup)
    in TransitionGroup (created by DialogInline)
    in div (created by DialogInline)
    in DialogInline
printWarning @ C:\Users\Owner\Projects\translationCore\node_modules\fbjs\lib\warning.js:33
warning @ C:\Users\Owner\Projects\translationCore\node_modules\fbjs\lib\warning.js:57
checkPropTypes @ C:\Users\Owner\Projects\translationCore\node_modules\prop-types\checkPropTypes.js:52
validatePropTypes @ C:\Users\Owner\Projects\translationCore\node_modules\react\cjs\react.development.js:1171
createElementWithValidation @ C:\Users\Owner\Projects\translationCore\node_modules\react\cjs\react.development.js:1268
mergeConflictCards @ index.js:40
render @ index.js:83
finishClassComponent @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7873
updateClassComponent @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:7850
beginWork @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:8225
performUnitOfWork @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10224
workLoop @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10288
callCallback @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:542
invokeGuardedCallbackDev @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:581
invokeGuardedCallback @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:438
renderRoot @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10366
performWorkOnRoot @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:11014
performWork @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10967
requestWork @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10878
scheduleWorkImpl @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10732
scheduleWork @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:10689
enqueueSetState @ C:\Users\Owner\Projects\translationCore\node_modules\react-dom\cjs\react-dom.development.js:6212
Component.setState @ C:\Users\Owner\Projects\translationCore\node_modules\react\cjs\react.development.js:237
onStateChange @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:222
notify @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\utils\Subscription.js:30
notifyNestedSubs @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\utils\Subscription.js:69
onStateChange @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:219
notify @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\utils\Subscription.js:30
notifyNestedSubs @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\utils\Subscription.js:69
onStateChange @ C:\Users\Owner\Projects\translationCore\node_modules\react-redux\lib\components\connectAdvanced.js:219
dispatch @ C:\Users\Owner\Projects\translationCore\node_modules\redux\lib\createStore.js:186
(anonymous) @ C:\Users\Owner\Projects\translationCore\node_modules\redux-promise\lib\index.js:21
(anonymous) @ C:\Users\Owner\Projects\translationCore\node_modules\redux-thunk\lib\index.js:14
dispatch @ C:\Users\Owner\Projects\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectImportStepperActions.js:67
(anonymous) @ C:\Users\Owner\Projects\translationCore\node_modules\redux-thunk\lib\index.js:11
dispatch @ C:\Users\Owner\Projects\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectImportStepperActions.js:50
(anonymous) @ C:\Users\Owner\Projects\translationCore\node_modules\redux-thunk\lib\index.js:11
dispatch @ C:\Users\Owner\Projects\translationCore\node_modules\redux\lib\applyMiddleware.js:45
(anonymous) @ ProjectImportStepperActions.js:33
(anonymous) @ C:\Users\Owner\Projects\translationCore\node_modules\redux-thunk\lib\index.js:11
dispatch @ C:\Users\Owner\Projects\translationCore\node_modules\redux\lib\applyMiddleware.js:45
_callee2$ @ ProjectValidationActions.js:72
tryCatch @ C:\Users\Owner\Projects\translationCore\node_modules\babel-polyfill\node_modules\regenerator-runtim…:65
invoke @ C:\Users\Owner\Projects\translationCore\node_modules\babel-polyfill\node_modules\regenerator-runtim…:303
prototype.(anonymous function) @ C:\Users\Owner\Projects\translationCore\node_modules\babel-polyfill\node_modules\regenerator-runtim…:117
step @ C:\Users\Owner\Projects\translationCore\src\js\actions\Import\ProjectValidationActions.js:60
(anonymous) @ C:\Users\Owner\Projects\translationCore\src\js\actions\Import\ProjectValidationActions.js:60
_tickCallback @ internal/process/next_tick.js:103

**Comment by RoyalSix** [comment]
I can fix this, thanks @bspidel

**Comment by bspidel** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4149)*

**Comment by RoyalSix** [comment]
@bspidel I could not reproduce the error with the project given

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4149)*

**Comment by mannycolon** [comment]
Test coverage decreased

**Comment by RoyalSix** [comment]
@mannycolon I will write tests. 
Did you get the same error as @bspidel ?

**Comment by mannycolon** [comment]
Local Test :lgtm:
Core Review :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4149#-:-L8nFWe_4O6G6W7VuhHC:b88bjtp)*

**Comment by mannycolon** [comment]
> @mannycolon I will write tests.
Did you get the same error as @bspidel?

@RoyalSix I did not.

**Comment by mannycolon** [comment]
@RoyalSix Merge with latest develop branch

**Pull request merged**
