### PR TITLE
Adds dependencies needed for new menu filter

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4443
- Updates dependencies and babel configuration.
- Adds project api to retrieve the book name.

#### Please include detailed Test instructions for your pull request:
- Not much to test. The application should function as before.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4104297)](https://tc-builds.door43.org/build/enhancement_joel_4443_menu-filter/translationCore-linux-x64-1.1.0-4104297.deb) is ready for download.
[macOS build 1.1.0 (4104297)](https://tc-builds.door43.org/build/enhancement_joel_4443_menu-filter/translationCore-macos-x64-1.1.0-4104297.dmg) is ready for download.
[Windows x64 build 1.1.0 (4104297)](https://tc-builds.door43.org/build/enhancement_joel_4443_menu-filter/translationCore-win-x64-1.1.0-4104297.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4104297)](https://tc-builds.door43.org/build/enhancement_joel_4443_menu-filter/translationCore-win-x32-1.1.0-4104297.setup.exe) is ready for download.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @neutrinog and @PhotoNomad0)

___
*[package.json, line 114 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664#-LWBmEE73O4qs3ZRNW1k:-LWBmEE73O4qs3ZRNW1l:b4krxl1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4104297f3bba330cb00b0dd1fab4c26dd2c9ea28/package.json#L114)):*
> ```JSON
>     "@material-ui/core": "^3.8.3",
>     "@material-ui/icons": "^3.0.2",
>     "@material-ui/styles": "^3.0.0-alpha.7",
> ```

Are any of these new dependencies actually used in this PR?

Also are you sure you want to have the up carat?  I worry about breaking changes.  Think we should not have the up carat since dependabot will nag us.

**Comment by PhotoNomad0** [comment]
LGTM except for questions in reviewable.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @neutrinog)

___
*[package.json, line 114 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664#-LWBmEE73O4qs3ZRNW1k:-LWCi1N71bMlRH0EZJXN:b1u8cx8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4104297f3bba330cb00b0dd1fab4c26dd2c9ea28/package.json#L114)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Are any of these new dependencies actually used in this PR?

Also are you sure you want to have the up carat?  I worry about breaking changes.  Think we should not have the up carat since dependabot will nag us.
</blockquote></details>

Oops the up carat was an oversight. I'll remove that. The dependencies "will" be used in the tools. Unfortunately, because of how our tools are loaded into the project we need to install all tool dependencies into tC directly.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5664)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
