### PR TITLE
Migrate to manifest.json instead of tc-manifest.json

### PR DESCRIPTION
**Pull request by EllDoubleYew**
#### This pull request addresses:
Addresses issue 813. The beginning of our data migration from our tc-manifest to simply manifest.

#### How to test this pull request:

Load any project. If the project had a tc-manifest.json file it will now have a manifest.json file. If the project had no manifest it should now have a manifest.json file. If the project has a manifest.json file from a translation studio project the manifest.json file should now be updated to be compatable with translation core. If you open the manifest.json file you should see a new property of "tcInitialized" in the manifest to signify that this manifest has been initialized by translation core and is compatable with the latest version.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/915)

### CODE REVIEW

**Comment by ihoegen** [comment]
Overall, UploadMethods.js looks good. I will test it shortly. However, there are references to the tc-manifest file inside of AccessProject.js, ImportUSFM.js, and the tests. Either modify those, or delete the functions that call it. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/core/UploadMethods.js, line 61 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915#-KfJSxebY9GaPYdMQGKu:-KfJSxebY9GaPYdMQGKv:b-npz1sx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a92343e67b43865e923e22e6b66a02ce02539bc/src/js/components/core/UploadMethods.js#L61)):*
> ```JavaScript
>       }
>       loadFile(path, 'manifest.json', (err, manifest) => {
>         if (manifest && manifest.tcInitialized) { // fs.access('manifest.json')
> ```

Maybe we should call it `tcProject` instead. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915#-:-KfJVJ1_gjSoILsFsygG:bdygnbm)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/core/UploadMethods.js, line 61 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915#-KfJSxebY9GaPYdMQGKu:-KfNZo5vOlsOHCPVM2vl:bup73ps) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a92343e67b43865e923e22e6b66a02ce02539bc/src/js/components/core/UploadMethods.js#L61)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Maybe we should call it `tcProject` instead. 
</blockquote></details>

i agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915)*

**Comment by mannycolon** [comment]
@EllDoubleYew merge with develop

**Comment by klappy** [comment]
*[src/js/components/core/UploadMethods.js, line 61 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915#-KfJSxebY9GaPYdMQGKu:-KfSzbN3AKP1lAfL3jCz:b-gkpila) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a92343e67b43865e923e22e6b66a02ce02539bc/src/js/components/core/UploadMethods.js#L61)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i agree
</blockquote></details>

Either is fine with me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915)*

**Comment by klappy** [comment]
*[src/js/components/core/UploadMethods.js, line 79 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915#-KfSzrU_YdRuiOSVT2Eo:-KfSzrU_YdRuiOSVT2Ep:bbzpki1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a92343e67b43865e923e22e6b66a02ce02539bc/src/js/components/core/UploadMethods.js#L79)):*
> ```JavaScript
>                 //ts-manifest is present, creating tc-manifest and initiate load
>                 saveManifest(path, link, verifiedManifest, (err, newManifest) => {
>                   // fs.unlink(Path.join(path, 'tc-manifest.json'), (err) =>{
> ```

Do we need this code that is commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915)*

**Comment by EllDoubleYew** [comment]
@klappy so that commented out code is the code that deletes the old manifest. I was cautious to leave it in because it just seemed like a disaster waiting to happen if something went wrong and a project had its manifest deleted and it was ruined. What do you think?

**Comment by klappy** [comment]
It shouldn't be a big deal to delete the tc-manifest, we generated it so we can regenerate it as needed. No actual real data is stored there.

**Comment by mannycolon** [comment]
@EllDoubleYew i think i fixed the failing test for you

**Comment by ihoegen** [comment]
Are the other methods where tc-manifest is referenced addressed?

**Comment by EllDoubleYew** [comment]
@ihoegen they are now :)

**Comment by ihoegen** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915)*

**Comment by ihoegen** [comment]
@EllDoubleYew I'm having an issue starting the App, it's caused by recentprojects. Try having a project that has not been migrated in there, that'll cause an issue. To fix it, you probably just need a catch where you read manifest.json as a backup

**Comment by ihoegen** [comment]
Reviewed 4 of 6 files at r6, 2 of 2 files at r7.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/915)*

**Comment by ihoegen** [comment]
@EllDoubleYew Looks like we're getting there, let's get this test figured out and it'll be ready to roll

**Pull request merged**
