### PR TITLE
Revamped fetch datas & loading process

### PR DESCRIPTION
**Pull request by mannycolon**
## This pull request addresses:
- Removed fetch data from componentWillMount() & componentWillRecevceProps from tools.
- Made changes to improve loader
- Now setting the project bookName to the projectDetailReducer when the project is selected.
- Created a delay function helper to help delay dispatching actions.
- Changed all filesystem functions (fs) to use synchronous functions. For example, Now using outputJsonSync instead of outputJson. Now reading the Group Data directory synchronous instead of asynchronous making the read process much more efficient.
- Created the loadBiblesFromFS() action creator to handle loading bibles from the filesystem and loading them to the resources reducer. (this happens when the tools fetch data is not run.) Now loading bibles from filesystem when tools fetch data isn't run (loadBiblesFromFS).
- Added docs consistently throughout the codebase.
- Now flushing/clearing data much more cleanly than before when switching tools wich fixes multiple bugs when switching tools.
- Fixed bug where groupIndex was being overwritten in the filesystem by saving an empty array
- Moved setProjectPath, setProjectManifest actions to the appropriate action creator file (projectDetailsActions.js)

## How to test this pull request:
**Make sure you pull from both tools the branch with the name feature/mc-1499**
- [ ] Load a large project like Luke or Psalm and it should load.
- [ ] The Loader should work fine. although should not show progress since that feature was removed.
- [ ] you should be able to switch tools and project very quickly no matter how large the project is.
- [ ] Make sure to tests with a fresh project. or just make sure your project isn't corrupted. 

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1602)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 19 files at r1.
Review status: 1 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by klappy** [comment]
*[src/js/components/core/AppDescription.js, line 90 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkQjkL_JIpQyfb_y0sF:-KkQjkL_JIpQyfb_y0sG:b-7d8lwd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/components/core/AppDescription.js#L90)):*
> ```JavaScript
>           </h4><span>{"Version " + version}</span><br />
>           <span style={{color: "#FFFFFF", marginBottom: ""}}>{description}</span><br /><br /><br />
>           <Button bsStyle="white" onClick={() => this.props.handleLoadTool(folderName, this.props.loggedInUser, name)}
> ```

Should we say toolName? I wasn't confident when reading this if it was toolName until I looked it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by klappy** [comment]
Reviewed 18 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-:-KkQlE8z3lGAD8WzGpDo:bnfp4nl)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/AppDescription.js, line 90 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkQjkL_JIpQyfb_y0sF:-KkQviUf0nurd4e6ueFS:b-rdf7x2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/components/core/AppDescription.js#L90)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should we say toolName? I wasn't confident when reading this if it was toolName until I looked it up.
</blockquote></details>

I only re-used what was already there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by mannycolon** [comment]
@klappy changing the label name to toolTame would mean refactoring a lot of code throughout our codebase.

**Comment by mannycolon** [comment]
#1369 #1307

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 306 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkRJZCXlIOfYrM-P4JQ:-KkRJZCYc0vw25YyxlA9:b-kta2or) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/actions/GetDataActions.js#L306)):*
> ```JavaScript
> 
>         .catch(err => {
>           console.warn(err);
> ```

I noticed you're not toggling the home view here, is that intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-:-KkRMGCGLoJcYrpuhfgp:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 450 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkRNKxOLyhEAc7EZwsC:-KkRNKxOLyhEAc7EZwsD:bsf2r4j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/actions/GetDataActions.js#L450)):*
> ```JavaScript
>     };
> 
>     currentModuleFetchData(props).then(dispatch({type: consts.DONE_LOADING}));
> ```

This doesn't ensure the fetchdata is done when the next line of code is executed. Should this be promisified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 306 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkRJZCXlIOfYrM-P4JQ:-KkRSEdnBMqzhdBKK2dt:b11r8t7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/actions/GetDataActions.js#L306)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I noticed you're not toggling the home view here, is that intentional?
</blockquote></details>

Good catch. thanks.
lol i had it there and removed it for some reason and forgot to add it back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by mannycolon** [comment]
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 306 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkRJZCXlIOfYrM-P4JQ:-KkRU9guTjAxwXitRP3_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/actions/GetDataActions.js#L306)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Good catch. thanks.
lol i had it there and removed it for some reason and forgot to add it back.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by mannycolon** [comment]
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 450 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602#-KkRNKxOLyhEAc7EZwsC:-KkRbmbmQd9XopuwQ9k1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f1e4f1c9116bc7eb04d4c2b974545e732f925cfe/src/js/actions/GetDataActions.js#L450)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This doesn't ensure the fetchdata is done when the next line of code is executed. Should this be promisified?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1602)*

**Pull request merged**
