### PR TITLE
WIP: feature 4805/Update Pre-aligned EN ULT.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated resource only

#### Please include detailed Test instructions for your pull request:
- make sure aligned en ULT is usable in NT books

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4964)

### CODE REVIEW

**Comment by mannycolon** [comment]
@PhotoNomad0 Please fix the failing unit test

**Review by mannycolon — COMMENTED** [review]
> Reviewed 8 of 2377 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4964)* status: 8 of 2377 files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (6252f59)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-6252f59.zip) is ready for download.
[macOS build 1.0.0 (6252f59)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-6252f59.dmg) is ready for download.
[Windows x64 build 1.0.0 (6252f59)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-6252f59.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (6252f59)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-6252f59.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (6573eae)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-6573eae.zip) is ready for download.
[macOS build 1.0.0 (6573eae)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-6573eae.dmg) is ready for download.
[Windows x64 build 1.0.0 (6573eae)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-6573eae.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (6573eae)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-6573eae.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
This will be handled by content script in future.  Closing this.

**Pull request closed without merging**
