### PR TITLE
Bugfix 6063/Fix Broken % Complete for tN and tW

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- changed toolsManagement/ToolCard to call getProjectProgressForTools() to get progress
- fixed resource paths in getToolProgress() to search the parent folders for sub-categories.

#### Please include detailed Test instructions for your pull request:
- can use this project: [en_test_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3157902/en_test_1ti_book.zip) and follow steps in https://github.com/unfoldingword-dev/translationcore/issues/6063 for testing tN
- then for tW card select names only - should read 0% (if no selections are made) launch tool and select one name and save.  Go back to tool card and should see 9%.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (71e81bc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-linux-x64-1.2.0-71e81bc.deb) is ready for download.
[macOS build 1.2.0 (71e81bc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-macos-x64-1.2.0-71e81bc.dmg) is ready for download.
[Windows x64 build 1.2.0 (71e81bc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x64-1.2.0-71e81bc.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (71e81bc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x32-1.2.0-71e81bc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (16e95bb)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-linux-x64-1.2.0-16e95bb.deb) is ready for download.
[macOS build 1.2.0 (16e95bb)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-macos-x64-1.2.0-16e95bb.dmg) is ready for download.
[Windows x64 build 1.2.0 (16e95bb)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x64-1.2.0-16e95bb.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (16e95bb)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x32-1.2.0-16e95bb.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (dbca10d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-linux-x64-1.2.0-dbca10d.deb) is ready for download.
[macOS build 1.2.0 (dbca10d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-macos-x64-1.2.0-dbca10d.dmg) is ready for download.
[Windows x64 build 1.2.0 (dbca10d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x64-1.2.0-dbca10d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (dbca10d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6063/translationCore-win-x32-1.2.0-dbca10d.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @PhotoNomad0)

___
*[src/js/actions/ProjectDetailsActions.js, line 119 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087#-Lf6w6HV3BeqVHxhk0JG:-Lf6w6HW82n98-BMSyfr:b-f7m6y3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dbca10df241892abc45a364b6176b76933565cd3/src/js/actions/ProjectDetailsActions.js#L119)):*
> ```JavaScript
>  * @return {Function}
>  */
> export function getProjectProgressForTools(toolName, results=null) {
> ```

Hey, I think it is an anti-pattern to use the result of an action to update the state. Check my comment below for a suggested fix. You want the action to cause a render and use the reducer value rather than the object parameter `result`
___
*[src/js/components/home/toolsManagement/ToolCard.js, line 42 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087#-Lf6wdj9CoUsEQJYUzuJ:-Lf6wdj9CoUsEQJYUzuK:bmhw5ws) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dbca10df241892abc45a364b6176b76933565cd3/src/js/components/home/toolsManagement/ToolCard.js#L42)):*
> ```JavaScript
>     setTimeout(() => {
>       const results = {};
>       actions.getProjectProgressForTools(tool.name, results);
> ```

Instead of passing `result` here you would just call the action and then use the prop from the reducer as the current progress
___
*[src/js/components/home/toolsManagement/ToolCard.js, line 121 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087#-Lf6wyzA36SO5SGqEm2v:-Lf6wyzA36SO5SGqEm2w:b-2s0wuh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dbca10df241892abc45a364b6176b76933565cd3/src/js/components/home/toolsManagement/ToolCard.js#L121)):*
> ```JavaScript
>       availableCategories
>     } = this.props;
>     const {progress, selectedGL} = this.state;
> ```

Here progress would come from the reducer instead of the state. We already have an object called `currentProjectToolsProgress` that is an object and can hold
```
{ 
  translationNotes:"50", translationWords:"95"
}
```
in the `projectDetailsReducer`
___
*[src/js/components/home/toolsManagement/ToolsCards.js, line 91 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087#-Lf6xSKr-hehTsUrTMLH:-Lf6xSKs0UYTVrE_dii_:b-jbpa2o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/43e5230b011798a803507eaebd39ed1bd6db94c1/src/js/components/home/toolsManagement/ToolsCards.js#L91)):*
> ```JavaScript
>                 }}
>                 invalidatedReducer={invalidatedReducer}
>                 currentProjectToolsProgress={currentProjectToolsProgress}
> ```

If you use the implementation I mentioned above you would be leaving this prop

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @PhotoNomad0)

___
*[src/js/actions/ProjectDetailsActions.js, line 120 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6087#-Lf6xcXkEU3_TgpdIRVA:-Lf6xcXkEU3_TgpdIRVB:b-yrzbvo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dbca10df241892abc45a364b6176b76933565cd3/src/js/actions/ProjectDetailsActions.js#L120)):*
> ```JavaScript
>  */
> export function getProjectProgressForTools(toolName, results=null) {
>   return (dispatch, getState) => {
> ```

If you do indeed need a synchronous calculator for the progress then there is no need to make this an action. Just move it to the helpers.
There also be a use case for both. In that case, you could still move it to a helper but just call the helper in the action, and use the helper where you don't need redux

**Pull request merged**
