### PR TITLE
Fix saving in windows.

### PR DESCRIPTION
**Pull request by EllDoubleYew**
#### This pull request addresses:

#1052 

#### How to test this pull request:

Try and save some data in windows. It works now. Please test this on macOS. I have not tested in linux yet but plan to.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1092)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/utils/saveMethods.js, line 88 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwclcw0ofnBawkApTl:-Khwclcw0ofnBawkApTm:b-bq3jza) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L88)):*
> ```JavaScript
>   try {
>     let savePath = generateSavePath(state, checkDataName, modifiedTimestamp);
>     if (savePath !== undefined) {
> ```

how about if savePath is null??

---

*[src/js/utils/saveMethods.js, line 92 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-KhwcwOjMcU_2jLZu1l1:-KhwcwOkYAz3Hrd2-f8r:bu7qv3k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L92)):*
> ```JavaScript
>       // let's not overwrite files, so check to see if it exists.
>       if (fs.existsSync(savePath)) {
>         fs.writeJson(savePath, payload, err => {console.log(err)});
> ```

why did you add this?? here

 if the path doesn't exist we don't want to write to it.

---

*[src/js/utils/saveMethods.js, line 105 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwf32lFTpksMRoN6Ok:-Khwf32lFTpksMRoN6Ol:b-xib8ud) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L105)):*
> ```JavaScript
> 
> /**
>  *@description recursively generetes directory to fix windows specific issue.
> ```

let's remove this if we are not using it yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-:-Khwf63vj3ZJ26LKvjUp:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-:-Khwfp2SOn9M8VXpLKWu:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/utils/saveMethods.js, line 88 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwclcw0ofnBawkApTl:-Khwg1dYf1uWwtrxc9Vv:bi2f9he) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L88)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how about if savePath is null??
</blockquote></details>

I guess we can discuss using `if (savePath) {` as our convention since it handles both null and undefined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092)*

**Comment by EllDoubleYew** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/utils/saveMethods.js, line 88 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwclcw0ofnBawkApTl:-KhwgSblBI083qNOmGZg:b25rm3j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L88)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I guess we can discuss using `if (savePath) {` as our convention since it handles both null and undefined.
</blockquote></details>

path.join will always return undefined if the path is not valid. 

---

*[src/js/utils/saveMethods.js, line 105 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwf32lFTpksMRoN6Ok:-KhwgbcjaPInM3EjRKc8:ba0543g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L105)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

let's remove this if we are not using it yet
</blockquote></details>

I have concerns that this will be necessary later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092)*

**Comment by klappy** [comment]
*[src/js/utils/saveMethods.js, line 105 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-Khwf32lFTpksMRoN6Ok:-Khx5CS2abeXlL2cYUtU:b-ccdf2l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e7d5f340e26aa279271d7480b20535b907aadfbf/src/js/utils/saveMethods.js#L105)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

I have concerns that this will be necessary later.
</blockquote></details>

Should you move it into a util or helper so that it can be used later and not orphaned here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1092#-:-KhyszOR1PJfSnNVNUB7:bnfp4nl)*

**Pull request merged**
