### PR TITLE
Fix Check Selection

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes a function that ensures the check is valid. It was giving false negatives

#### How to test this pull request:
Try opening of checks in tN and tW and ensuring that it shows the right one. If the quote is missing from the verse the check should not show. I think we need a usability feature that dialogs the user when the check is not available

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2396)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396#-:-Kr1FxHE0pY_L--F_2u6:bnfp4nl)*

**Comment by mannycolon** [comment]
@klappy take a look at this one. I think you're the best suited to review this one since I think you wrote the first version of this code.

**Comment by klappy** [comment]
@royalsix: Can you make this a different function to do this? It no longer serves the same purpose and would affect the expected response for other uses for this helper.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396#-:-Kr2CDInKn0bbjilnLvQ:b89b67)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396)*

**Comment by RoyalSix** [comment]
@klappy @mannycolon This is updated

**Comment by mannycolon** [comment]
@klappy @RoyalSix 

I got the following error when testing this branch.

screen shot 2017-08-09 at 2 04 30 pm

**Comment by RoyalSix** [comment]
@mannycolon is that a fresh project?

**Comment by mannycolon** [comment]
@klappy @RoyalSix It still works though

**Comment by mannycolon** [comment]
@RoyalSix no.

**Comment by RoyalSix** [comment]
@mannycolon did you try with a fresh one? What bugs did you encounter?

**Comment by mannycolon** [comment]
I encountered what is shown in the picture.

**Comment by RoyalSix** [comment]
Ok I am not able to replicate this error. I tried with fresh projects @mannycolon

**Comment by klappy** [comment]
@mannycolon @royalsix: I'll review this once my PR is merged and this one is updated with my changes.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396#-:-Kr7mAUiH1cXjMoTfjsD:b-dr9te)*

**Comment by mannycolon** [comment]
@RoyalSix but not all projects are going to be fresh projects

**Comment by RoyalSix** [comment]
@mannycolon true. I just believe my last PR was creating bad target language folders. Can you send me your project?

**Comment by mannycolon** [comment]
[bhadrawahi_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1212909/bhadrawahi_tit.zip)

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396)*

**Comment by mannycolon** [comment]
@RoyalSix @klappy this branch should be good to go

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2396#-:-KrGEqmHnhvUYdRdpGV6:bnfp4nl)*

**Pull request merged**
