### PR TITLE
Fix Dialog Message For Local User Upload

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes the dialog message that appears when a local user attempts to upload a project.

#### How to test this pull request:
Login as a local user and try to upload a project to door43 you should be prompted a error message stating that action is not possible

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2499)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2499#-:-Ks5bWx9qEx_OfYwvkBS:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix By looking at the story I realize that @cckozie also said the following 

```
Since we don't allow uploading when logged in as a local user, 
the "You are about to use the Internet" message should not be displayed.

```
I was able to see this alert while using a local user and clicking `upload project to Door43`

**Comment by RoyalSix** [comment]
Nice catch!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2499#-:-Ks6dCR64Lz6knDYIte3:b-73m6vw)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2499)*

**Pull request merged**
