### PR TITLE
Change Gogs Login Requirements

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
address issue #1370 
#### How to test this pull request:
Try different scenarios of being logged in and syncing, opening a project, tool etc.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1412)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/RecentProjectsActions.js, line 28 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1412#-KjDuc1bN6x7OBfmH4wp:-KjDuc1bN6x7OBfmH4wq:b-zbowh8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/50a3cdde6d9ffb296edd01a0689b647cc3749d44/src/js/actions/RecentProjectsActions.js#L28)):*
> ```JavaScript
>       })
>     }).catch(function (reason) {
>         dialog.showErrorBox('Error Uploading', "You must be logged in to upload");
> ```

Couldnt there be other reasons this could fail? What if the promise from login() gets a 404?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1412)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/RecentProjectsActions.js, line 28 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1412#-KjDuc1bN6x7OBfmH4wp:-KjE-neBue0A5GSkWfU4:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/50a3cdde6d9ffb296edd01a0689b647cc3749d44/src/js/actions/RecentProjectsActions.js#L28)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Couldnt there be other reasons this could fail? What if the promise from login() gets a 404?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1412)*

**Comment by ihoegen** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1412)*

**Comment by ihoegen** [comment]
Looks good to me. Merging

**Pull request merged**
