### PR TITLE
Folder Structure For Resources

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.
This PR creates new structure presented in #1832 

#### How to test this pull request:
Nothing to test

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1839)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1839#-:-KmX0RngWtxo_T8eZwAM:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix do we want to make the file a file.json file instead?

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1839#-:-KmdSASpSH6BeLzYdyYR:bnfp4nl)*

**Comment by klappy** [comment]
Should we close this PR and only merge @royalsix's new PR with all resources in it?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1839#-:-Kmm6SWtJbvBV7TjfOOI:b8y1n2l)*

**Pull request closed without merging**
