### PR TITLE
Added Same Progress From Tool Card To Home

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes a bug with the Home Page using the legacy progress calculation method

#### Please include detailed Test instructions for your pull request:
- Follow the same steps in #5651 and ensure that the bug does not occur

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5700)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5700)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
LGTM

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (86f0782)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-linux-x64-1.1.0-86f0782.deb) is ready for download.
[macOS build 1.1.0 (86f0782)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-macos-x64-1.1.0-86f0782.dmg) is ready for download.
[Windows x64 build 1.1.0 (86f0782)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x64-1.1.0-86f0782.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (86f0782)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x32-1.1.0-86f0782.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-linux-x64-1.1.0-d1a2d64.deb) is ready for download.
[macOS build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-macos-x64-1.1.0-d1a2d64.dmg) is ready for download.
[Windows x64 build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x64-1.1.0-d1a2d64.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x32-1.1.0-d1a2d64.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-linux-x64-1.1.0-d1a2d64.deb) is ready for download.
[macOS build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-macos-x64-1.1.0-d1a2d64.dmg) is ready for download.
[Windows x64 build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x64-1.1.0-d1a2d64.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d1a2d64)](https://tc-builds.door43.org/build/feature-jay-5651/translationCore-win-x32-1.1.0-d1a2d64.setup.exe) is ready for download.

**Pull request merged**
