### PR TITLE
Feature/speed up tool checking in tW and tN

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated to latest checking-tool-wrapper with performance boosts

#### Please include detailed Test instructions for your pull request:
- Test opening [this](https://github.com/unfoldingWord-dev/translationCore/files/3646538/en_test_mat_book.zip) project with build below.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6455)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a8c7045)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-linux-x64-2.0.0-a8c7045.deb) is ready for download.
[macOS build 2.0.0 (a8c7045)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-macos-x64-2.0.0-a8c7045.dmg) is ready for download.
[Windows x64 build 2.0.0 (a8c7045)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x64-2.0.0-a8c7045.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a8c7045)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x32-2.0.0-a8c7045.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (adbda6c)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-linux-x64-2.0.0-adbda6c.deb) is ready for download.
[macOS build 2.0.0 (adbda6c)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-macos-x64-2.0.0-adbda6c.dmg) is ready for download.
[Windows x64 build 2.0.0 (adbda6c)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x64-2.0.0-adbda6c.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (adbda6c)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x32-2.0.0-adbda6c.setup.exe) is ready for download.

**Review by mannycolon — COMMENTED** [review]
Can we fix the problem instead of the symptom for the unit tests issues

**Comment by PhotoNomad0** [comment]
> Can we fix the problem instead of the symptom for the unit tests issues

taking that out, since it actually didn't fix Travis unit tests.

**Review by mannycolon — APPROVED** [review]

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (5a12351)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-linux-x64-2.0.0-5a12351.deb) is ready for download.
[macOS build 2.0.0 (5a12351)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-macos-x64-2.0.0-5a12351.dmg) is ready for download.
[Windows x64 build 2.0.0 (5a12351)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x64-2.0.0-5a12351.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (5a12351)](https://tc-builds.door43.org/build/feature-mcleanb-conversion-optimization-test/translationCore-win-x32-2.0.0-5a12351.setup.exe) is ready for download.

**Pull request merged**
