### PR TITLE
Feature 4403/add resource id and nickname to project details

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- https://github.com/unfoldingWord-dev/translationCore/issues/4403 and https://github.com/unfoldingword-dev/translationcore/issues/4402

#### Please include detailed Test instructions for your pull request:
- When a project is opened, it should be migrated to tc_version 6.  if there is not a Translation Identifier (resourceId) in the manifest, it should open the project ID and prompt for project ID.
- Project Details page layout is changed to match design in: https://github.com/unfoldingWord-dev/translationCore/issues/3421
- on project import (USFM, tstudio, door43), it should check for Translation Identifier and nickname in possible places in manifest on migration). It then should prompt for Translation Identifier if not present.  Expected behavior on imports:

| test project  | project type   | expected results   |
|---|---|---|
| Local USFM import  | USFM | Should prompt for Translation Identifier (resource ID)  |
| Local tStudio  | ts project  | Should not prompt for Translation Identifier (should be found in manifest)  |
| https://git.door43.org/tc01/es-419_eph_text_ulb  | ts project  | Should not prompt for Translation Identifier (should be found in manifest)  |
| https://git.door43.org/tc01/ar_mat_text_ulb  | 0.7.0 tc project no checking  | Should not prompt for Translation Identifier (should be found in manifest)  |
| https://git.door43.org/photonomad0/es-419_luk  | 0.8.0 tc project no checking  | Should not prompt for Translation Identifier (should be found in manifest)  |
| https://git.door43.org/tc02/English_tit | 0.8.1 tc project with alignment, no checking  | Should not prompt for Translation Identifier (should be found in manifest) |
| https://git.door43.org/tc02/am_1co_ulb  | 0.9.0 tc project no checking  | Should not prompt for Translation Identifier (should be found in manifest)  |
| https://git.door43.org/photonomad0/el_tit | 0.9.0 tc project with checking  | Should prompt for Translation Identifier (resource ID)  |

- on Project Details page, check that Translation Identifier input is validated - should be 3 to 4 characters and those should be latin letters.
- Resource Nickname is optional.  If resource ID is entered, it should be shown on upper title bar.  Enter a long nickname such as "Unlocked Literal Greek Titus".  After saving, it should show up on title bar  as "Project: "+nickname with ellipsis, and hover text should show full nickname on black background.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4535)

### CODE REVIEW

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4535)*

**Comment by mannycolon** [comment]
Local tests: 'In progress (still need to do more)'

**Pull request merged**
