### PR TITLE
QA Fail Fixes (Project Check Category Persistence, Tool Card Order)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes the following issues
```
- If the user unselects a a checkbox or two, save those settings (pegged to the project)
Now it does save the setting, but it is not pegged to the project. It is used for all projects until changed again.

- The UI mockups show the checkboxes in the sequence of Key Terms, Other Terms, Names, but as implemented the sequence is Key Terms, Names, Other Terms.
```

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c20423e)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-linux-x64-1.1.0-c20423e.deb) is ready for download.
[macOS build 1.1.0 (c20423e)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-macos-x64-1.1.0-c20423e.dmg) is ready for download.
[Windows x64 build 1.1.0 (c20423e)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x64-1.1.0-c20423e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c20423e)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x32-1.1.0-c20423e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c408774)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-linux-x64-1.1.0-c408774.deb) is ready for download.
[macOS build 1.1.0 (c408774)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-macos-x64-1.1.0-c408774.dmg) is ready for download.
[Windows x64 build 1.1.0 (c408774)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x64-1.1.0-c408774.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c408774)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x32-1.1.0-c408774.setup.exe) is ready for download.

**Review by da1nerd — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/actions/ProjectDetailsActions.js, line 41 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyesOO3qo6fYAhCBXo:-LTyesOO3qo6fYAhCBXp:b-9zrunr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ProjectDetailsActions.js#L41)):*
> ```JavaScript
>   return (dispatch, getState) => {
>     const state = getState();
>     const {projectDetailsReducer: {toolsCategories, projectSaveLocation, manifest: {project = {}}}  } = state;
> ```

Please use selectors instead of accessing the state object directly. This is tightly coupled code that will be difficult to maintain.

e.g. these existing ones
* `getProjectManifest(state)`
* `getProjectSaveLocation(state)`

You'll need to create a selector for retrieving the tools categories. Refer to the above selectors as an example.
___
*[src/js/actions/ToolActions.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyg2Vc4cF9F9tWTWme:-LTyg2Vc4cF9F9tWTWmf:b-zdrbwh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ToolActions.js#L80)):*
> ```JavaScript
>     return new Promise((resolve, reject) => {
>       let { projectDetailsReducer } = getState();
>       let { projectSaveLocation, manifest, toolsCategories } = projectDetailsReducer;
> ```

FYI: this could also benefit from using selectors. See my other comment about selectors for details. The reducer was already in use in the old code so not a big deal in this case. But you'll notice a 20 second refactor will help to decouple the state structure from the action which means code that's easier to maintain in the future.
___
*[src/js/actions/ToolActions.js, line 181 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygBzh9fL-Tas-PXbv:-LTygBzh9fL-Tas-PXbw:b-ozgm18) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ToolActions.js#L181)):*
> ```JavaScript
>         groupsDataAlreadyLoaded = categoriesIndexObject.loaded;
>       } catch (e) {
>         //
> ```

This can make it hard to hunt down errors in the code. If it's not a critical error then at least print it to the console as a warning e.g. `console.warn(e)`
___
*[src/js/containers/home/ToolsManagementContainer.js, line 24 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygvJy5gk4tZZOEm2l:-LTygvJy5gk4tZZOEm2m:b7np9fk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/containers/home/ToolsManagementContainer.js#L24)):*
> ```JavaScript
>   }
> 
>   componentWillMount() {
> ```

This react lifecycle method is deprecated. A better location for this code would be in `componentDidMount`.
___
*[src/js/containers/home/ToolsManagementContainer.js, line 68 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyj6QOCxJsDxL9iTu4:-LTyj6QOCxJsDxL9iTu5:b3s8kq7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/containers/home/ToolsManagementContainer.js#L68)):*
> ```JavaScript
>           currentProjectToolsProgress,
>           currentProjectToolsSelectedGL,
>           toolsCategories
> ```

FYI. technically we'd want to pull in this data using selectors in mapStateToProps, but since this just an addition to old code I won't give you too hard of a time :smile:

**Comment by da1nerd** [comment]
___
*[src/js/actions/ProjectDetailsActions.js, line 41 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyesOO3qo6fYAhCBXo:-LTyl69r3zjqgicJn38m:b-xpir88) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ProjectDetailsActions.js#L41)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

Please use selectors instead of accessing the state object directly. This is tightly coupled code that will be difficult to maintain.

e.g. these existing ones
* `getProjectManifest(state)`
* `getProjectSaveLocation(state)`

You'll need to create a selector for retrieving the tools categories. Refer to the above selectors as an example.

</blockquote></details>

Giving you a hard time on this one because it's new code. If we always access state using selectors in new code we'll eventually have a clean abstraction between state and everything else so it will be a LOT easier to update/improve how state works without having to refactor everything else.

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @neutrinog)

___
*[src/js/actions/ProjectDetailsActions.js, line 41 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyesOO3qo6fYAhCBXo:-LU1OyEsErmBXv6Zeyiu:b-qu6n94) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ProjectDetailsActions.js#L41)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

Giving you a hard time on this one because it's new code. If we always access state using selectors in new code we'll eventually have a clean abstraction between state and everything else so it will be a LOT easier to update/improve how state works without having to refactor everything else.
</blockquote></details>

Good point. Done.
___
*[src/js/actions/ToolActions.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTyg2Vc4cF9F9tWTWme:-LU1QUEN4xcZlLHdL8Tm:bsmd4l2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ToolActions.js#L80)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

FYI: this could also benefit from using selectors. See my other comment about selectors for details. The reducer was already in use in the old code so not a big deal in this case. But you'll notice a 20 second refactor will help to decouple the state structure from the action which means code that's easier to maintain in the future.
</blockquote></details>

Yes. Done
___
*[src/js/actions/ToolActions.js, line 181 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygBzh9fL-Tas-PXbv:-LU1QqrT9_fhYD7JjxKm:bb6un1j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/actions/ToolActions.js#L181)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

This can make it hard to hunt down errors in the code. If it's not a critical error then at least print it to the console as a warning e.g. `console.warn(e)`
</blockquote></details>

Done
___
*[src/js/containers/home/ToolsManagementContainer.js, line 24 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygvJy5gk4tZZOEm2l:-LU1SNklC4cate0M5ISt:b-vpnoy0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/containers/home/ToolsManagementContainer.js#L24)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

This react lifecycle method is deprecated. A better location for this code would be in `componentDidMount`.
</blockquote></details>

Ok, 
From the docs: `componentWillMount() is invoked just before mounting occurs. It is called before render(), therefore calling setState() synchronously in this method will not trigger an extra rendering. Generally, we recommend using the constructor() instead. Avoid introducing any side-effects or subscriptions in this method. For those use cases, use componentDidMount() instead. This is the only lifecycle hook called on server rendering.`

I think this is a better use case for the constructor than CDM

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b11f71d)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-linux-x64-1.1.0-b11f71d.deb) is ready for download.
[macOS build 1.1.0 (b11f71d)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-macos-x64-1.1.0-b11f71d.dmg) is ready for download.
[Windows x64 build 1.1.0 (b11f71d)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x64-1.1.0-b11f71d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b11f71d)](https://tc-builds.door43.org/build/feature-jay-5193/translationCore-win-x32-1.1.0-b11f71d.setup.exe) is ready for download.

**Review by da1nerd — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/containers/home/ToolsManagementContainer.js, line 24 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygvJy5gk4tZZOEm2l:-LU1l0Z--qC4U273e4a6:b-z85gkv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/containers/home/ToolsManagementContainer.js#L24)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ok, 
From the docs: `componentWillMount() is invoked just before mounting occurs. It is called before render(), therefore calling setState() synchronously in this method will not trigger an extra rendering. Generally, we recommend using the constructor() instead. Avoid introducing any side-effects or subscriptions in this method. For those use cases, use componentDidMount() instead. This is the only lifecycle hook called on server rendering.`

I think this is a better use case for the constructor than CDM
</blockquote></details>

Make sure you are reading the latest documentation https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
This method will be removed in future versions of react. If we keep using it we'll just have to remove it later. At the very least we should place the code in UNSAFE_componentWillMount() however, the official suggestion is to use componentDidMount.

**Comment by da1nerd** [comment]
___
*[src/js/containers/home/ToolsManagementContainer.js, line 24 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597#-LTygvJy5gk4tZZOEm2l:-LU1m4kH1Jv9kN10T4k8:b-4ddgjn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c4087747f5ff9fdd472013c64c4cd729539977a0/src/js/containers/home/ToolsManagementContainer.js#L24)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

Make sure you are reading the latest documentation https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
This method will be removed in future versions of react. If we keep using it we'll just have to remove it later. At the very least we should place the code in UNSAFE_componentWillMount() however, the official suggestion is to use componentDidMount.
</blockquote></details>

oops I didn't realize you updated it to be in the constructor. That is also an acceptable location :)

**Review by da1nerd — APPROVED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5597)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by da1nerd** [comment]
Tested locally and it looks good.

**Pull request merged**
