### PR TITLE
Updated k- to zaln- attribute and x-strong in usfm-js

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated `k-` to `zaln-` and strong to x-strong. 
- Updated in **usfm-js** `k-` to `zaln-` and strong to x-strong 
- Updated **usfm-js** to **1.0.0-beta.26**

**Dependencies:**
- [x] https://github.com/translationCoreApps/tC_Resources/pull/20
- [x] https://github.com/translationCoreApps/tC_Resources/pull/21
- [x] https://github.com/translationCoreApps/usfm-js/pull/32

#### Please include detailed Test instructions for your pull request:
- Delete you node_modules folder
- `npm install`
- Open the app and load a new **usfm** project from local
- Open the project with **wordAlignment** tool and then go to the project page and try to export it as **usfm** and also export alignment data.
- everything should work as expected 

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3839)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 19 of 21 files at r1.
Review status: 19 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r2.
Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839#-:-L5PDxBku9Qfa5eu4qw-:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 18 of 21 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r4.
Review status: 15 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r4.
Review status: 16 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
Reviewed 2 of 10 files at r4.
Review status: 18 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by klappy** [comment]
Reviewed 6 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by PhotoNomad0** [comment]
Reviewed 8 of 21 files at r1, 1 of 3 files at r2, 8 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3839#-:-L5QPQChCfZZVj3aEGXW:bnfp4nl)*

**Pull request merged**
