### PR TITLE
2. re-structure the way redux was implemented in tC. Now using storeConfiguration for easy data persistence implementation (Second)

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

re-structure the way redux was implemented in tC. Now using storeConfiguration to easy data persistence implementation

This PR s related to **Implement redux data persistence #892**

#### How to test this pull request:

open the app and try performing an action related to redux.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/893)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/PopoverActions.js, line 14 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoP53Um7Pz5o_gg7Os:-KeoP53Um7Pz5o_gg7Ot:b2ol4eq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/63910c848ae7d72d08331b450f4cd3f4fc702e14/src/js/actions/PopoverActions.js#L14)):*
> ```JavaScript
> export const closePopover = () => {
>   return {
>     type: consts.CLOSE_POPOVER,
> ```

remove the ","

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/actions/CoreActionConsts.js, line 54 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoP8JNinwTVoKE-ah-:-KeoP8JNinwTVoKE-ah0:b-gpezrs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/63910c848ae7d72d08331b450f4cd3f4fc702e14/src/js/actions/CoreActionConsts.js#L54)):*
> ```JavaScript
>   SELECT_MODAL_SECTION: "SELECT_MODAL_SECTION",
>   SHOW_POPOVER: "SHOW_POPOVER",
>   CLOSE_POPOVER: "CLOSE_POPOVER",
> ```

remove the last ,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/actions/SideBarActions.js, line 7 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoPBxpBuwq7Q2_G67B:-KeoPBxpBuwq7Q2_G67C:b3kqv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/63910c848ae7d72d08331b450f4cd3f4fc702e14/src/js/actions/SideBarActions.js#L7)):*
> ```JavaScript
>   return {
>     type: consts.TOGGLE_SUBMENU,
>     openCheck: id,
> ```

,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/reducers/popoverReducer.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoPKdO0r8HYqqzsfDY:-KeoPKdO0r8HYqqzsfDZ:b3kqv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/63910c848ae7d72d08331b450f4cd3f4fc702e14/src/js/reducers/popoverReducer.js#L18)):*
> ```JavaScript
>         title: action.title,
>         bodyText: action.bodyText,
>         positionCoord: action.positionCoord,
> ```

,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/reducers/popoverReducer.js, line 26 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoPLrnatTkPEVtTM0L:-KeoPLrnatTkPEVtTM0M:b3kqv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/63910c848ae7d72d08331b450f4cd3f4fc702e14/src/js/reducers/popoverReducer.js#L26)):*
> ```JavaScript
>         title: '',
>         bodyText: '',
>         positionCoord: [0, 0],
> ```

,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by EllDoubleYew** [comment]
Reviewed 34 of 34 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/actions/CoreActionConsts.js, line 54 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoMHKX2WPEVQWmdBAR:-KeoMHKX2WPEVQWmdBAS:b-adtjsq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/actions/CoreActionConsts.js#L54)):*
> ```JavaScript
>   SELECT_MODAL_SECTION: "SELECT_MODAL_SECTION",
>   SHOW_POPOVER: "SHOW_POPOVER",
>   CLOSE_POPOVER: "CLOSE_POPOVER",
> ```

Not to nitpick but remove this comma=

---

*[src/js/actions/SideBarActions.js, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoMQ4xhjLo87YFKUMg:-KeoMQ4xhjLo87YFKUMh:blanhy0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/actions/SideBarActions.js#L2)):*
> ```JavaScript
> const CheckStoreActions = require('./CheckStoreActions.js');
> const consts = require('./CoreActionConsts');
> ```

I am going to second @klappy suggestion here and say that we should tag the constants onto the actions file. I never thought about this in the past but it makes sense and will help keep related files closer together. If this would cause any problems let me know.

---

*[src/js/components/core/Popover.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoPAa3Tw3TQ5zzSPnf:-KeoPAa3Tw3TQ5zzSPng:b-lgnul6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/components/core/Popover.js#L21)):*
> ```JavaScript
>           arrowOffsetTop={-1000}
>           title={<span>
>                   {title}
> ```

same suggestion about moving this component construction somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/components/core/Popover.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoPAa3Tw3TQ5zzSPnf:-KeoQ1RceDzkMtDYGYkg:b-ef57fw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/components/core/Popover.js#L21)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

same suggestion about moving this component construction somewhere else.
</blockquote></details>

I agree, nesting here seems awkward

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
*[src/js/actions/SideBarActions.js, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoMQ4xhjLo87YFKUMg:-KeoQCfEmata8gyL5egk:b8dgde8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/actions/SideBarActions.js#L2)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

I am going to second @klappy suggestion here and say that we should tag the constants onto the actions file. I never thought about this in the past but it makes sense and will help keep related files closer together. If this would cause any problems let me know.
</blockquote></details>

I know it's the same number of lines, but it would be cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by klappy** [comment]
Overall, this is really shaping up and makes the App feel so much cleaner and easier to follow.

**Comment by mannycolon** [comment]
Review status: 15 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/actions/SideBarActions.js, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893#-KeoMQ4xhjLo87YFKUMg:-KeoQYso5GvA0gLMaqtd:b-j4zaxu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a37f6c3445a0a6415559543519ebd8d58b2f7059/src/js/actions/SideBarActions.js#L2)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I know it's the same number of lines, but it would be cleaner.
</blockquote></details>

we cannot do that because you not always use `CoreActionConsts` and `CheckStoreActions` together

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Comment by RoyalSix** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/893)*

**Pull request merged**
