### PR TITLE
SideBarContainer w/ Redux (this should help fix the bugs introduced from my last PR)

### PR DESCRIPTION
**Pull request by mannycolon**
TODO:

- [ x ] Opening and closing (toggling) submenus it's still buggy.

- [ x ] Remove last tool's menu buttons when switching between tools. 

**added latest commits from tools**

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/614)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/navigation_menu/MenuHeaders.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-KbzcnYM8W1ywcOsuo0-:-KbzcnYM8W1ywcOsuo00:b-98ml5i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/47ba74a31e3b813f860417269fc0a10af98eb41c/src/js/components/core/navigation_menu/MenuHeaders.js#L10)):*
> ```JavaScript
> class MenuHeaders extends React.Component {
>   render() {
>     console.log(this.props);
> ```

Remove console log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by ihoegen** [comment]
image
@mannycolon The menu isn't correct when tools are switched still

**Comment by EllDoubleYew** [comment]
Reviewed 9 of 12 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/components/core/AppDescription.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-eBZZRxPfcBxO8Mie:-Kc-eBZ_G0Isni4LIpvW:brh4ft0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/src/js/components/core/AppDescription.js#L60)):*
> ```JavaScript
>     switch (name) {
>       case "ImportantWords":
>         Styles = iW.appWindow;
> ```

Are all mentions of tW changing to iW?

---

*[src/js/pages/app.js, line 109 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-euarPcps0nkMmyse:-Kc-euarPcps0nkMmysf:bm1e0az) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/src/js/pages/app.js#L109)):*
> ```JavaScript
>     });
>   },
>   /*changeCheck(tool) {
> ```

Can we just remove this if we aren't using it?

---

*[tC_apps/TranslationHelps, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fBHAWpFcDRSWi3WC:-Kc-fBHAWpFcDRSWi3WD:b-1z5w1w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/TranslationHelps#L1)):*
> ```
> Subproject commit 4637acb579f8a4da3c014ab4fe9a9dae22e7f019
> ```

Should the submodule commits be a part of this PR? 

---

*[tC_apps/translationNotes, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fG8jo7EHvXBJTON4:-Kc-fG8kqqbPfd3F5Hpv:bb6xk7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/translationNotes#L1)):*
> ```
> Subproject commit 4c9b2526960c8170aad72f768eae7ecb6a09a2e4
> ```

Ibid

---

*[tC_apps/translationWords, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fGs8j9ObmWNYrpjY:-Kc-fGs8j9ObmWNYrpjZ:bb6xk7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/translationWords#L1)):*
> ```
> Subproject commit b8447b405cee5aac640ea3cf9f59b632b27b39f4
> ```

Ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/components/core/AppDescription.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-eBZZRxPfcBxO8Mie:-Kc-n-cNjcIFtY_lGgnl:bum0551) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/src/js/components/core/AppDescription.js#L60)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Are all mentions of tW changing to iW?
</blockquote></details>

Done. yes, they should.

---

*[src/js/components/core/navigation_menu/MenuHeaders.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-KbzcnYM8W1ywcOsuo0-:-Kc-n1sJfwfWwUPpQ_BJ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/47ba74a31e3b813f860417269fc0a10af98eb41c/src/js/components/core/navigation_menu/MenuHeaders.js#L10)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Remove console log.
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 109 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-euarPcps0nkMmyse:-Kc-n4FN_Hyr_LQ5sl1v:b-jp4nau) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/src/js/pages/app.js#L109)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Can we just remove this if we aren't using it?
</blockquote></details>

Not yet i need it there for now. until the menu working well.

---

*[tC_apps/TranslationHelps, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fBHAWpFcDRSWi3WC:-Kc-nBrUkhitYruyqiO1:b-q60880) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/TranslationHelps#L1)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Should the submodule commits be a part of this PR? 
</blockquote></details>

Done. yes. 

---

*[tC_apps/translationNotes, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fG8jo7EHvXBJTON4:-Kc-nF8wslyZD8n6TPKH:b-q60880) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/translationNotes#L1)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Ibid
</blockquote></details>

Done. yes. 

---

*[tC_apps/translationWords, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-fGs8j9ObmWNYrpjY:-Kc-nFo_W-lvsfqQ_f6L:b-q60880) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72347bf89e26119095cc32f65ad861f23f5fe526/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Ibid
</blockquote></details>

Done. yes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by RoyalSix** [comment]
Reviewed 4 of 12 files at r1, 3 of 5 files at r2, 1 of 2 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/actions/SideBarActions.js, line 14 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0Bo6HjFHdOCL4JRsA:-Kc0Bo6HjFHdOCL4JRsB:bi9h2wq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3a9db3433fedaee7a1ede10c23f39f81eef5851/src/js/actions/SideBarActions.js#L14)):*
> ```JavaScript
>   return ((dispatch) => {
>       dispatch(CheckStoreActions.goToCheck(currentToolNamespace, currentGroupIndex, currentCheckIndex));
>       dispatch({
> ```

you can use dispatch(this.toggleSubmenu()) if you like, just letting you know

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 12 files at r1, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by ihoegen** [comment]
Reviewed 7 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/js/components/core/navigation_menu/MenuHeaders.js, line 12 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0vephDjeqwr7F22Il:-Kc0vepiuyqZHlIlC4Ut:b-byhy63) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/67119441b99c5fafb8bf61a5855081f29479f9ec/src/js/components/core/navigation_menu/MenuHeaders.js#L12)):*
> ```JavaScript
>     let { groups, currentGroupIndex, currentCheckIndex } = this.props;
>     let subGroupObjects = {};
>     if(groups != null && currentGroupIndex != null){
> ```

I don't think this covers if they are undefined. 

---

*[src/js/reducers/checkStoreReducer.js, line 21 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0w1u_mJDQ9TYeM4BB:-Kc0w1uamqxdMvBc0oqu:b-pc5cje) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/67119441b99c5fafb8bf61a5855081f29479f9ec/src/js/reducers/checkStoreReducer.js#L21)):*
> ```JavaScript
>       break;
>     case "SET_GROUPS_OBJECTS":
>       return Object.assign({}, state, {
> ```

Why `Object.assign` instead of merge? This is inconsistent. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Comment by ihoegen** [comment]
Was this always like this: 
image

**Comment by ihoegen** [comment]
Physical testing looks good, no issues I can find

**Comment by mannycolon** [comment]
this PR has not changed anything related to tN

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/js/actions/SideBarActions.js, line 14 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0Bo6HjFHdOCL4JRsA:-Kc116_5j25WZZAA4m6V:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3a9db3433fedaee7a1ede10c23f39f81eef5851/src/js/actions/SideBarActions.js#L14)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

you can use dispatch(this.toggleSubmenu()) if you like, just letting you know
</blockquote></details>

Done.

---

*[src/js/components/core/AppDescription.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc-eBZZRxPfcBxO8Mie:-Kc1186lGL28d6D9IGU0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00ca526976047a0555da3eec4e4bd3f766ce7f0a/src/js/components/core/AppDescription.js#L60)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done. yes, they should.
</blockquote></details>

Done.

---

*[src/js/components/core/navigation_menu/MenuHeaders.js, line 12 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0vephDjeqwr7F22Il:-Kc11Ab4wud-aq1ewD98:b-pxp2nt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/67119441b99c5fafb8bf61a5855081f29479f9ec/src/js/components/core/navigation_menu/MenuHeaders.js#L12)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think this covers if they are undefined. 
</blockquote></details>

how would you do that while keeping the != null condition? I tried doing (groups && currentGroupIndex) but at some point, it would fail either because groups was null or currentGroupIndex was = 0 which make the condition false when it needed to be actually true so that it would read groups at index 0  

---

*[src/js/reducers/checkStoreReducer.js, line 21 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0w1u_mJDQ9TYeM4BB:-Kc11ru9G-ctKTTndjRk:bs89f07) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/67119441b99c5fafb8bf61a5855081f29479f9ec/src/js/reducers/checkStoreReducer.js#L21)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Why `Object.assign` instead of merge? This is inconsistent. 
</blockquote></details>

In this case, we cannot merge because we want to write the previous state so that the menus don't render the buttons of the previous tool. in other words we do assign to overwrite whatever data it's in groups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-:-Kc12MR8-PJwb71Hi6q5:b-hbknw4)*

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/components/core/navigation_menu/MenuHeaders.js, line 12 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614#-Kc0vephDjeqwr7F22Il:-Kc18yDodaFNVhgcyPon:bd1pj1s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/67119441b99c5fafb8bf61a5855081f29479f9ec/src/js/components/core/navigation_menu/MenuHeaders.js#L12)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how would you do that while keeping the != null condition? I tried doing (groups && currentGroupIndex) but at some point, it would fail either because groups was null or currentGroupIndex was = 0 which make the condition false when it needed to be actually true so that it would read groups at index 0  
</blockquote></details>

Could probably just add ` && !isNaN(groups) && !isNaN(currentGroupIndex)` For some reason, javascript thinks null is a number, so you would have to keep the `!= null` check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/614)*

**Pull request merged**
