### PR TITLE
Updated Verse Edit Actions

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #2004 

- This changes the verse edit actions to support editing any verse. The original functionality only allowed editing the currently selected verse.

#### Please include detailed Test instructions for your pull request:
- Try editing a verse using https://github.com/translationCoreApps/ScripturePane/pull/108 and make sure the files are written to the correct location on the disk.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4152)

### CODE REVIEW

**Comment by mannycolon** [comment]
I suggest testing `csv export` when testing this branch

**Comment by richmahn** [comment]
Tested both in wA and tW, multiple verses, verses with alignment and selected text, properly cleared edited words. Tested CSV & USFM 2 & 3 export. Local Test: :lgtm:

Code review: :lgtm: 

---

Reviewed 12 of 15 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152#-:-L8sc8ox6eFk_NvRl50r:bh7m72s)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 15 files at r1, 2 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/js/actions/WordAlignmentLoadActions.js, line 73 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152#-L8siirmBi21gtN0qcs-:-L8siirmBi21gtN0qcs0:b-bkutw3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e82245da40e546c0aa6d0facf8ac356e32c58af2/src/js/actions/WordAlignmentLoadActions.js#L73)):*
> ```JavaScript
>  * @return {Function}
>  */
> export const resetVerseAlignments = (bookId, chapter, verse) => {
> ```

There is already a method WordAlignmentHelpers.resetAlignmentsForVerse()

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 15 files at r1, 2 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152)*

**Comment by da1nerd** [comment]
*[src/js/actions/WordAlignmentLoadActions.js, line 73 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152#-L8siirmBi21gtN0qcs-:-L8smENc9O9TtAVckbtJ:b8ahl5l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e82245da40e546c0aa6d0facf8ac356e32c58af2/src/js/actions/WordAlignmentLoadActions.js#L73)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

There is already a method WordAlignmentHelpers.resetAlignmentsForVerse()
</blockquote></details>

That method does not work the same as this one. This one is updating the data in the reducer. The other one is changing data on the filesystem.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152)*

**Comment by richmahn** [comment]
@neutrinog Any way we can get some test coverage so it doesn't drop here?

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4152)*

**Pull request merged**
