### PR TITLE
Drag to select option / api.settings

### PR DESCRIPTION
**Pull request by EllDoubleYew**
This merge introduces both new selection options as well as the api.settings which are accessible from the settings pane of the side nav bar.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/145)

### CODE REVIEW

**Comment by ihoegen** [comment]
:lgtm: just going to test now

---

Reviewed 5 of 11 files at r2, 6 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/145#-:-KSCSJ3hB-yR_J5Okekm:b-kvltcu)_

**Comment by ihoegen** [comment]
@EllDoubleYew So as I'm running QA, I notice a few things:
- The words aren't bolded when dragged to select, however they are when clicked.
- This feature has only worked on translationWords for me, is there a plan to implement this in translationNotes?
- Highlighting the words with click to select enabled still adds them to proposed changes.
- If you click on a word, without highlighting it, and drag to select is enabled, it will change the verse that is displayed.
- If you accidentally highlight the translationAcademy well, it will add those words to proposed changes

[Video showing issues](https://drive.google.com/file/d/0Bxaf4ZxVpTQkZlZSX21sbno3YWc/view)

**Comment by EllDoubleYew** [comment]
@ihoegen Addressing each issue respectively:
- Bolding was something I did not implement but would be an easy fix, I didn't know the click to select component was bolding but that is something I could change without much trouble.
- No implementation for translationNotes yet but that is actually what I am going to work on tonight and tomorrow.
- Its because a highlight is still a click event, that happened before my implementation but I can see what it would take to fix, should we just cancel the click event if there is a selection made? That might not be too hard but I didn't modify anything else in the click-to-select component
- I see what you mean and this is a problem specific to Arabic and how it decides to display words based on what characters it is next to. If you highlight an area that is already highlighted some funny things can happen. I thought it was enough of an edge case to slip through but I may still need to address it.
- This certainly should not happen. I don't exactly know how you managed to get it to happen in the video but I saw you do it. The onMouseUp event needs to happen inside of the targetversedisplay for it to grab the selection, so if your selection ends outside of that component nothing should happen at all. Ill look into it.

Ill see how much I can get fixed by tomorrow, busy day today so I will see what I can get to tonight.

**Comment by EllDoubleYew** [comment]
@ihoegen I believe I have addressed all of the issues mentioned above.

**Comment by ihoegen** [comment]
@elldoubleyew I'll be sure to give it a look tomorrow.

**Comment by ihoegen** [comment]
@EllDoubleYew It looks good on my system.

**Comment by ihoegen** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/145)_

**Pull request merged**
