### PR TITLE
Feature 4404/Update project naming to meet spec

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- project names will be migrated (renamed) when project is opened and on project  import to match:
  - project name will be in format: `[lang_id]\_[resource_id]\_[project_id]\_[type]`
    - where `resource_id` is "Translation Identifier" on project details
    - where `project_id` is the id of the book
    - where `lang_id` is the target language code
   - where `type` is type.id in manifest or defaults to 'text' if not given.

#### Please include detailed Test instructions for your pull request:
- open existing projects and the project names will be migrated (unless that name already exists) to match spec.
- imports from D43 should be renamed to match spec.
- local imports of tstudio projects should be renamed to match spec.
- when project details are edited, changes to language code, book, or "Translation Identifier" should result in project being renamed to match spec (unless that name already exists).

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4548)

### CODE REVIEW

**Comment by da1nerd** [comment]
[Linux build 0.10.0 (5c763e5)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-5c763e5.zip) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (0fb9bef)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-0fb9bef.zip) is ready for download.
[macOS build 0.10.0 (0fb9bef)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-0fb9bef.dmg) is ready for download.
[Windows x64 build 0.10.0 (0fb9bef)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-0fb9bef.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (0fb9bef)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-0fb9bef.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (cff91d3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-cff91d3.zip) is ready for download.
[macOS build 0.10.0 (cff91d3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-cff91d3.dmg) is ready for download.
[Windows x64 build 0.10.0 (cff91d3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-cff91d3.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (cff91d3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-cff91d3.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (79c4c68)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-79c4c68.zip) is ready for download.
[macOS build 0.10.0 (79c4c68)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-79c4c68.dmg) is ready for download.
[Windows x64 build 0.10.0 (79c4c68)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-79c4c68.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (79c4c68)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-79c4c68.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (e747295)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-e747295.zip) is ready for download.
[macOS build 0.10.0 (e747295)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-e747295.dmg) is ready for download.
[Windows x64 build 0.10.0 (e747295)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-e747295.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (e747295)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-e747295.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/js/actions/Import/ProjectValidationActions.js, line 83 at r5](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4548#-LEAfe5LDOGDq9VpZPvX:-LEAfe5LDOGDq9VpZPvY:bbusqs9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e74729599a1316cec00adf7999cfa471c88fd74e/src/js/actions/Import/ProjectValidationActions.js#L83)):*
> ```JavaScript
>  * @return {string}
>  */
> export const generateNewProjectName = (manifest) => {
> ```

this function should probably be moved to a helper file

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4548#-:-LEAfw3V9s-gIw01BPEw:bnfp4nl)*

**Comment by mannycolon** [comment]
Local Test: `Pending`

**Comment by mannycolon** [comment]
Loaded this project [am_ulb_1co_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2069651/am_ulb_1co_text.zip) from the project folder and the following happened

screen shot 2018-06-04 at 3 05 58 pm

**Comment by mannycolon** [comment]
It automatically nicknames projects to  `Unlocked Literal Bible`. is this right?
@PhotoNomad0

**Comment by mannycolon** [comment]
Project was automatically nicknamed `Unlocked Dynamic Bible`. Is this normal ?
screen shot 2018-06-04 at 3 15 56 pm

**Comment by PhotoNomad0** [comment]
> Project was automatically nicknamed Unlocked Dynamic Bible. Is this normal ?

This is normal if it is already in the manifest under `resource.name`

**Comment by mannycolon** [comment]
> This is normal if it is already in the manifest under resource.name

The story asked for that to happen? it just seems so weird that it would automatically nickname the project with the resource name

**Comment by mannycolon** [comment]
@PhotoNomad0

**Pull request merged**
