### PR TITLE
QA Fail - #4685 - Fixes for Project Details page

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes the display problems of Project Details page in QA Fail #4685 

#### Please include detailed Test instructions for your pull request:
- Checkout this branch, set up, and then either load project page of existing project, or import a new project. The main fields fixed are the text boxes for `Translation Identifier` and `Project Nickname`, but all fields should position correctly in both large and small resolutions, and each field on a row should line up pretty well.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5648)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (69d60c4)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-69d60c4.deb) is ready for download.
[macOS build 1.1.0 (69d60c4)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-69d60c4.dmg) is ready for download.
[Windows x64 build 1.1.0 (69d60c4)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-69d60c4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (69d60c4)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-69d60c4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ddea833)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-ddea833.deb) is ready for download.
[macOS build 1.1.0 (ddea833)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-ddea833.dmg) is ready for download.
[Windows x64 build 1.1.0 (ddea833)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-ddea833.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ddea833)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-ddea833.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ed4ff7e)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-ed4ff7e.deb) is ready for download.
[macOS build 1.1.0 (ed4ff7e)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-ed4ff7e.dmg) is ready for download.
[Windows x64 build 1.1.0 (ed4ff7e)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-ed4ff7e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ed4ff7e)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-ed4ff7e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-cbf8a65.deb) is ready for download.
[macOS build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-cbf8a65.dmg) is ready for download.
[Windows x64 build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-cbf8a65.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-cbf8a65.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (5f60978)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-5f60978.deb) is ready for download.
[macOS build 1.1.0 (5f60978)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-5f60978.dmg) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-cbf8a65.deb) is ready for download.
[macOS build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-cbf8a65.dmg) is ready for download.
[Windows x64 build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-cbf8a65.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cbf8a65)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-cbf8a65.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM testing

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 3 of 8 files at r2, 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5648)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @richmahn)

___
*[package.json, line 112 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5648#-LVnobVK1d4zz8yUANob:-LVnobVK1d4zz8yUANoc:b-o0uueu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cbf8a65be3f1d1ad8bb03c175ffb244ffe894da1/package.json#L112)):*
> ```JSON
>   },
>   "dependencies": {
>     "@material-ui/core": "^3.8.2",
> ```

Did you actually use this?

**Review by PhotoNomad0 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5648)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4ddb86a)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-linux-x64-1.1.0-4ddb86a.deb) is ready for download.
[macOS build 1.1.0 (4ddb86a)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-macos-x64-1.1.0-4ddb86a.dmg) is ready for download.
[Windows x64 build 1.1.0 (4ddb86a)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x64-1.1.0-4ddb86a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4ddb86a)](https://tc-builds.door43.org/build/qafail-richmahn-4685/translationCore-win-x32-1.1.0-4ddb86a.setup.exe) is ready for download.

**Pull request merged**
