### PR TITLE
Implementation of New Menu Design

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/617)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/ModalActions.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/617#-Kc0IFYPNls47WsNZapM:-Kc0IFYQFCyqO_VDHmxf:b-xfrp61) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/491bd93ed110b10671e3ab72aebf1e025ad31d67/src/js/actions/ModalActions.js#L9)):*
> ```JavaScript
> }
> 
> module.exports.selectModalTab = function (tabKey, sectionKey) {
> ```

good job. I knew we needed to add this at some point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/617)*

**Comment by mannycolon** [comment]
@RoyalSix maybe do a more redux like implementation if you can

**Comment by ihoegen** [comment]
Also merge with develop and the tests should pass.

**Comment by ihoegen** [comment]
@RoyalSix The last menu item get's hidden: 
image

**Comment by mannycolon** [comment]
@RoyalSix maybe a more redux like implementation of this would be better. if you have time.

**Comment by RoyalSix** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/ModalActions.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/617#-Kc0IFYPNls47WsNZapM:-Kc3zv_0L7L5LScvDQRp:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/491bd93ed110b10671e3ab72aebf1e025ad31d67/src/js/actions/ModalActions.js#L9)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

good job. I knew we needed to add this at some point.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/617)*

**Pull request merged**
