### PR TITLE
Scripture Pane Descriptions Localization

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR brings in the updated version of the `tc-ui-toolkit`

#### Please include detailed Test instructions for your pull request:
- Make sure that the Scripture Pane Headings are localized in the app

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5470)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5470)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-linux-x64-1.1.0-53f9d5c.deb) is ready for download.
[macOS build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-macos-x64-1.1.0-53f9d5c.dmg) is ready for download.
[Windows x64 build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-win-x64-1.1.0-53f9d5c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-win-x32-1.1.0-53f9d5c.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Problems in testing:

I checked with a Hindi translation, but not seeing the localized string.  This is what it has for target:
```
    "target_language": {
        "id": "hi",
        "name": "हिन्दी, हिंदी",
        "direction": "ltr",
        "book": {
            "name": "तीतुस"
        }
    },
```

But I am not seeing the language string, only “Target Language”

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-linux-x64-1.1.0-53f9d5c.deb) is ready for download.
[macOS build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-macos-x64-1.1.0-53f9d5c.dmg) is ready for download.
[Windows x64 build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-win-x64-1.1.0-53f9d5c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (53f9d5c)](https://tc-builds.door43.org/build/feature-jay-5399/translationCore-win-x32-1.1.0-53f9d5c.setup.exe) is ready for download.

**Pull request merged**
