### PR TITLE
Addressed QA issues related to project upload/sync to door43.

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

#1223

#### How to test this pull request:
- [x] Sign in to your d43 acct. Import https://git.door43.org/faustin-azaza/en-x-demo1_eph_text_reg make any changes to the project then try to upload to door 43.
- [ ] Try uploading a project that **DOESN'T HAVE** the repo URL in its manifest.
- [ ] Try uploading a project that does **HAVE**  the repo URL in its manifest.
- [ ] While logged in to Door43 activate the offline mode or just disconnect your Internet connection then attempts to upload your project to door43. you should get the following alert message **Unable to connect to the server. Please check your Internet connection.** NOT **getaddrinfo ENOTFOUND**

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1541)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541)*

**Comment by klappy** [comment]
When uploading a new repo, I get a delay, and wasn't sure that it worked. After it alerted me of the success, I opened the console and got a fatal error in the console... 

`/Users/christopherklapp/GitHub/translationCore/node_modules/simple-git/src/git.js:226`
` fatal: repository 'https://65df9be2817778ac81e055b34a615bb4d351929a@git.door43.org/klappy/79-EPHarb-vd.git/'`
`not found`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-:-Kjtb1zR0H54xh7JsWZR:brpi0mc)*

**Comment by klappy** [comment]
*[src/js/components/core/SideBar/GitSync.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-KjtbqUu-qEMdWHYYi_O:-KjtbqUu-qEMdWHYYi_P:b2i1wai) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41d258ec9d9244220631c3d1f17c8759051d2282/src/js/components/core/SideBar/GitSync.js#L18)):*
> ```JavaScript
>   console.error = console.errorold;
>   if (user) {
>     git(projectPath).save(user, 'Updating with Door43', projectPath, function() {
> ```

Since this is technically Uploading to Door43, should we say that instead of updating? Updating is more like syncing, I would think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541)*

**Comment by klappy** [comment]
All other testing passes from what I can tell, just need to consider the above, and maybe the commit message to uploading instead of updating.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-:-KjtcYs8mwSIu46BldNT:b-p4xwdy)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-Kjtd-ENzNQx1c1D9J7C:-Kjtd-EOlLCN8EoLqvfv:b-hmzwpr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41d258ec9d9244220631c3d1f17c8759051d2282/src/js/actions/RecentProjectsActions.js#L46)):*
> ```JavaScript
>       sync(projectPath, manifest, authenticatedUser, showAlert);
>       dispatch({
>         type: consts.SYNC_PROJECT
> ```

Should we consider renaming this constant to UPLOAD_PROJECT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541)*

**Comment by mannycolon** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/RecentProjectsActions.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-Kjtd-ENzNQx1c1D9J7C:-KjxVz5Lu6GGfLRiTvA4:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41d258ec9d9244220631c3d1f17c8759051d2282/src/js/actions/RecentProjectsActions.js#L46)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should we consider renaming this constant to UPLOAD_PROJECT?
</blockquote></details>

Done.

---

*[src/js/components/core/SideBar/GitSync.js, line 18 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541#-KjtbqUu-qEMdWHYYi_O:-KjxW-6mrbD4i6eHkudc:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/41d258ec9d9244220631c3d1f17c8759051d2282/src/js/components/core/SideBar/GitSync.js#L18)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Since this is technically Uploading to Door43, should we say that instead of updating? Updating is more like syncing, I would think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541)*

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1541)*

**Comment by ihoegen** [comment]
When I try to upload, with local user, I get an error saying incorrect username or password. I then logout, then login with my normal account. I then get the same error. I refresh the window, try with my normal account, it works, kinda, it opens the git credential manager.

**Comment by mannycolon** [comment]
@ihoegen there's a different issue/story for the **incorrect username or password** bug.

I was wondering if you could help me find out why is opening the  **git credential manager** the token is being passed to it so I don't know why it still shows up.

**Comment by ihoegen** [comment]
@mannycolon Let's try and figure that out on Monday

**Comment by ihoegen** [comment]
Git manager does not come up anymore

**Pull request merged**
