### PR TITLE
Added diagrams folder

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This simply adds a non-code folder to hold diagrams of concepts within the application.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[diagrams/README.md, line 8 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821#-LJEBA2uELeH5xcDigRH:-LJEBA2uELeH5xcDigRI:bq7gn4r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c72584b30bd8ba5df03e73dd4f202655d8c9cf0e/diagrams/README.md#L8)):*
> ```Markdown
> mmdc -i input.mmd -o output.png
> ```
> ```

Since the installation instructions are hidden for mermaid (and global install is not recommended ).  Would recommend adding them here as well as a quick script to generate the pngs:

npm install mermaid.cli

for i in diagrams/*.mmd; do ./node_modules/.bin/mmdc -i "$i" -o "$i.png"; done

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[diagrams/README.md, line 8 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4821#-LJEBA2uELeH5xcDigRH:-LJECOWD8yWdm5J8cGv0:b-vu6v9b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c72584b30bd8ba5df03e73dd4f202655d8c9cf0e/diagrams/README.md#L8)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Since the installation instructions are hidden for mermaid (and global install is not recommended ).  Would recommend adding them here as well as a quick script to generate the pngs:

npm install mermaid.cli

for i in diagrams/*.mmd; do ./node_modules/.bin/mmdc -i "$i" -o "$i.png"; done

</blockquote></details>

Here is the reference to the install instructions: https://github.com/mermaidjs/mermaid.cli

**Comment by da1nerd** [comment]
These will instead be stored at https://forum.ccbt.bible/

**Pull request closed without merging**
