### PR TITLE
Project Import Refactor

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes all known issues with the import processes, including refactor of workflows.
This should lead to a more stable import process.

#### How to test this pull request:
Try different iterations of the following process:
Import an online project
Change tools
Import a local project
Change projects
Also maybe try refreshing and not refreshing during certain points

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3329)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 69 of 69 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/projectSelection.test.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-bWzJHMEUgFcLlHViQ:-L-bWzJHMEUgFcLlHViR:bd17v5r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c7a76b3dd48fed9abd9cb23f23a2c675f09dc365/__tests__/projectSelection.test.js#L33)):*
> ```JavaScript
> 
>   test('should select a project and import a valid manifest to the store', () => {
>     // store.dispatch(ProjectSelctionActions.selectProject(noMergeConflictsProjectPath));
> ```

do we need this tests or can we get rid of it all together?

---

*[src/js/actions/ProjectSelectionActions.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-bXcEMS1WtWNNG7Eto:-L-bXcEMS1WtWNNG7Etp:b-7kelin) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c7a76b3dd48fed9abd9cb23f23a2c675f09dc365/src/js/actions/ProjectSelectionActions.js#L4)):*
> ```JavaScript
> // actions
> import * as ToolsMetadataActions from './ToolsMetadataActions';
> import * as BodyUIActions from './BodyUIActions';
> ```

do we still need this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
Reviewed 1 of 23 files at r3.
Review status: 37 of 63 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[__tests__/ProjectDetails.test.js, line 54 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cn2fW4ryh-QIMhngV:-L-cn2fW4ryh-QIMhngW:bk5twvp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/__tests__/ProjectDetails.test.js#L54)):*
> ```JavaScript
>   });
> 
>   // test('should select word Alignment tool and load it to the store', () => {
> ```

Do we want to leave this commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/actions/ProjectSelectionActions.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-bXcEMS1WtWNNG7Eto:-L-cnRNKbvj7L-JY4LwB:b98wm5p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c7a76b3dd48fed9abd9cb23f23a2c675f09dc365/src/js/actions/ProjectSelectionActions.js#L4)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we still need this file?
</blockquote></details>

There should be a new one called ProjectLoadingActions that takes its place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
Reviewed 2 of 69 files at r1, 4 of 16 files at r2, 21 of 23 files at r3.
Review status: 62 of 63 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/actions/Import/FileConversionActions.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpVfrifyA59SXQGUq:-L-cpVfrifyA59SXQGUr:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/actions/Import/FileConversionActions.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversion/index.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cphxiVEUdRHcsOI2p:-L-cphxiVEUdRHcsOI2q:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/index.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversion/translationCoreFileConversionHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpkKilOw-PlcX5uQ9:-L-cpkKilOw-PlcX5uQA:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/translationCoreFileConversionHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversion/translationStudioFileConversionHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpm6ninp2pW-AjFp1:-L-cpm6ninp2pW-AjFp2:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/translationStudioFileConversionHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversion/UsfmFileConversionHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpo8gjurDjD98iUCD:-L-cpo8gjurDjD98iUCE:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/UsfmFileConversionHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversion/ZipFileConversionHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cppkmJnkyoYC0uLzV:-L-cppkmJnkyoYC0uLzW:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/ZipFileConversionHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/Import/LocalImportWorkflowHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpuImUSScPhsaIPX8:-L-cpuImUSScPhsaIPX9:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/Import/LocalImportWorkflowHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/ProjectValidation/DuplicateVersesHelpers.js, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpwCTAXiO8uw6_qvM:-L-cpwCTAXiO8uw6_qvN:b-20gt9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/ProjectValidation/DuplicateVersesHelpers.js#L0)):*
Do we need this empty file? Did we create this for the skeleton and not use it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[tC_apps/ScripturePane, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cqFUZbxqWq20We1O0:-L-cqFUZbxqWq20We1O1:byty0g0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit 919c5198c36ced48e6c3763e9ca3e61ed5050d59
> ```

Is this commit intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
Reviewed 22 of 69 files at r1.
Review status: 62 of 63 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 7 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-csx5a_bGBKDHs7eQj:-L-csx5bo3gcZmT8HSSX:b8f1od3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L7)):*
> ```JavaScript
> 
> export const convertToProjectFormat = () => {
> ```

Is this intentionally left blank?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
Reviewed 13 of 69 files at r1.
Review status: 62 of 63 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by klappy** [comment]
I left a few questions on random files, from blank files to some lines commented out, can't remember the rest. They should be easy to find since they are the ones I didn't mark as reviewed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-:-L-ctNgVBrmvX7jRbUXv:bajgk5c)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix After my changes it seems `codecov` doesn't work

**Comment by mannycolon** [comment]
@neutrinog Hey sorry to bother do you know what exactly did I do wrong here that `codecov` stopped working ?

**Comment by mannycolon** [comment]
Reviewed 8 of 16 files at r2, 1 of 23 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/js/actions/ProjectSelectionActions.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-bXcEMS1WtWNNG7Eto:-L-dKP7zH4nX9ZUdmIrX:b-mtz992) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c7a76b3dd48fed9abd9cb23f23a2c675f09dc365/src/js/actions/ProjectSelectionActions.js#L4)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

There should be a new one called ProjectLoadingActions that takes its place.
</blockquote></details>

I thought I deleted this file. didn't Ii?

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 7 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-csx5a_bGBKDHs7eQj:-L-dKWFmgbgPGqElFzHh:bx9adsu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L7)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is this intentionally left blank?
</blockquote></details>

yes, this is where usfm convertion will be

---

*[tC_apps/ScripturePane, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cqFUZbxqWq20We1O0:-L-dK_VlkLF18BY_LsjM:bsvx138) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is this commit intentional?
</blockquote></details>

i believe so

---

*[src/js/actions/Import/FileConversionActions.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpVfrifyA59SXQGUq:-L-dKcgXcLjLc5nC1aDA:bleejuk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/actions/Import/FileConversionActions.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

this file was deleted because we did not use it for the import refactor

---

*[src/js/helpers/FileConversion/index.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cphxiVEUdRHcsOI2p:-L-dKj6UPdEpPuhcqgho:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/index.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/FileConversion/translationCoreFileConversionHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpkKilOw-PlcX5uQ9:-L-dKnh_JriC2I3qcHB0:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/translationCoreFileConversionHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/FileConversion/translationStudioFileConversionHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpm6ninp2pW-AjFp1:-L-dKov_qHmx8g1BrYKy:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/translationStudioFileConversionHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/FileConversion/UsfmFileConversionHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpo8gjurDjD98iUCD:-L-dKpdCcq3Ne--Ve6np:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/UsfmFileConversionHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/FileConversion/ZipFileConversionHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cppkmJnkyoYC0uLzV:-L-dKqeb6UfDNsLy1qII:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/FileConversion/ZipFileConversionHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/Import/LocalImportWorkflowHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpuImUSScPhsaIPX8:-L-dKrJ1zKgswCOk74Ic:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/Import/LocalImportWorkflowHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---

*[src/js/helpers/ProjectValidation/DuplicateVersesHelpers.js, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cpwCTAXiO8uw6_qvM:-L-dKtDeDGJoohpuVUZ_:b8qm8d7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ab7e48267840081173a3c40e75129f515a35e5ac/src/js/helpers/ProjectValidation/DuplicateVersesHelpers.js#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we need this empty file? Did we create this for the skeleton and not use it?
</blockquote></details>

same here. this file was deleted. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by da1nerd** [comment]
@mannycolon you didn't break it. Codecov only comments once on a PR. Any additional commits you make will be reflected in that original comment.

Furthermore, I checked just to be sure and I can indeed see your last commit on Codecov. You'll notice your last commit is reflected in this screenshot (`3395130`).

image

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[__tests__/ProjectDetails.test.js, line 54 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cn2fW4ryh-QIMhngV:-L-gNXHD4D8a7SSc-6-f:bnn5ivn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/__tests__/ProjectDetails.test.js#L54)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we want to leave this commented out?
</blockquote></details>

This test cannot work right now because its goal it to load a project and find the amount of wordAlignment progress, but right now the only workflow we have is to import a .tstudio project and there is no way to represent a tstudio project with alignments done

---

*[tC_apps/ScripturePane, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329#-L-cqFUZbxqWq20We1O0:-L-gXReN2eKfovTgOS35:bjfyt8v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/33951305d105c3ff89a75be39f57fff70754fe95/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i believe so
</blockquote></details>

I didn't change the repo, not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by RoyalSix** [comment]
Reviewed 34 of 69 files at r1, 4 of 16 files at r2, 18 of 23 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3329)*

**Comment by RoyalSix** [comment]
Made some refactor changes to runGitCommand and some tests...WIP

**Comment by RoyalSix** [comment]
Test To Be Made:
- Migration Modules
- <s>Project Selection Helpers</s>
- <s>Missing Verses</s>
- <s>Merge Conflicts</s>
- <s>Convert Over Project Validation Actions</s>
- usfmHelpers
  - Should we keep the functions that may/may not be used in the future?
- <s>CopyrightCheckActions</s>
- <s>LoadHelpers</s>

Updates:
- Take out manifest migrations

**Comment by mannycolon** [comment]
@RoyalSix Great work making the latest changes. Please don't make any further changes before we meet again. I've been working on USFM import process and I'm afraid if you make any new changes it's going to cause me too many merge conflicts.

**Pull request merged**
