### PR TITLE
Merge Conflict Projects Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes an issue with merge conflict projects not able to be opened.

#### Please include detailed Test instructions for your pull request:
- Download the project from [this](https://github.com/unfoldingword-dev/translationcore/issues/3856) story.
- Load it and ensure the merge conflict is detected.
- Resolve the merge conflict by selecting a version to use and selecting continue.
- Ensure that the selected conflict is actually there in the project. (ch.1 v.5 -6)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4136)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4136)*

**Comment by mannycolon** [comment]
Local Testing: `LGTM `
Code Review: `LGTM`

**Comment by mannycolon** [comment]
merge latest develop into `feature-jay-3856`

**Comment by bspidel** [comment]
Code :lgtm: 
Local Testing :lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4136#-:-L8ZFSH_5ZzHsySNmFpo:b-m0advv)*

**Pull request merged**
