### PR TITLE
Support for new new UGNT v0.2 and lexicon

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Replaces Greek UGNT with v0.2 and updated lexicon.

#### How to test this pull request:

- Check out the same branch on Core
- Delete your ~/translationCore/resources folder so that launching the app populates the resources folder
- Load a Titus project, and tW, click on the Greek words in the scripture pane to get the Lexicon entries.
- Load a non-Titus project and tW, verify that the app doesn't crash but displays placeholder text.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2722)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2722#-:-Ku_3qSkoQp_2OCgzG8x:bnfp4nl)*

**Comment by mannycolon** [comment]
@klappy this happened when I opened this [am_1co_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1321908/am_1co_text_ulb.zip) project 

screen shot 2017-09-21 at 11 53 20 am


I was able to open a Titus project.
Is this expected behavior?

screen shot 2017-09-21 at 11 56 25 am

**Comment by mannycolon** [comment]
Non-titus project error
screen shot 2017-09-21 at 12 07 17 pm

**Comment by klappy** [comment]
@mannycolon: Did you checkout the branch on both the Core and the ScripturePane repos? It looks like you only have the PR checked out for the Core.

https://github.com/translationCoreApps/ScripturePane/pull/63

This has to be checked out at the same time.

**Comment by RoyalSix** [comment]
@klappy This works well! Nice job. Just if you can remove the console logs, and wondering one thing. Are there missing lexicon entries for titus? Or is this a bug?
screen shot 2017-09-21 at 10 28 52 am

**Comment by klappy** [comment]
@royalsix Yeah, that happens when ever there is old resources folder in the user translationCore folder.

delete it and launch the app and it will load the lexicon data.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2722#-:-Kua8l_3hPJKOptTCpmi:bjb4avt)*

**Pull request merged**
