### PR TITLE
BugFix 3606/Missing Default tC

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Minimize redrawing of project information screen - particularly a problem on slow windows machines.
- Made a combined method to set all language parameters in the reducer with only one call (minimizes messaging and chances of clicking next before all language parameters have been updated).
- Added validation of settings before finalizing or saving project information settings to account for race conditions.

#### Please include detailed Test instructions for your pull request:
- On slow windows PC, try to do the USFM import steps on https://github.com/unfoldingWord-dev/translationCore/issues/3606.  Should not see any import failures as described

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4079)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/LanguageIdTextBox.test.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079#-L8-ES6K07eICsClR9Qk:-L8-ES6LGzdNlnmE6MxP:bqj8um3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3cfafc4258dd584ac17ea4b90c8c9014f38327f9/__tests__/LanguageIdTextBox.test.js#L16)):*
> ```JavaScript
> 
> describe('Test LanguageIdTextBox.selectLanguage()',()=> {
>   let updateLanguageId, updateLanguageName, updateLanguageAll;
> ```

why updateLanguageAll() ?
What does that even mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079)*

**Comment by mannycolon** [comment]
@PhotoNomad0 I could not test this on windows since I don't have a windows PC

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/LanguageIdTextBox.test.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079#-L8-ES6K07eICsClR9Qk:-L8-Gc-XvuyUiayn8Xsq:b-fzlu6l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3cfafc4258dd584ac17ea4b90c8c9014f38327f9/__tests__/LanguageIdTextBox.test.js#L16)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why updateLanguageAll() ?
What does that even mean?
</blockquote></details>

It is a call to change all the language settings (code, name, and direction) with one call rather than three separate calls.  Minimizes a lot of messaging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079)*

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 I could not test this on windows since I don't have a windows PC

Probably not a big deal since Kos tested it on his slow PCs.  As long as it still works on Mac for you.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079#-:-L8-KNaUPbTQzYgqckYd:bnfp4nl)*

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `Pending...`

**Comment by RoyalSix** [comment]
Reviewed 1 of 10 files at r2, 2 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/js/actions/ProjectInformationCheckActions.js, line 52 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4079#-L846K5i4MxuCaXDPtJ-:-L846K5jDqN_1myu3gJj:b-hx53ow) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9855833a4a0678b1744c114ad9e6965a950ac8b8/src/js/actions/ProjectInformationCheckActions.js#L52)):*
> ```JavaScript
>  * to the project details reducer under the manifest property.
>  */
> export function finalize() {
> ```

Reason you wanted to change this name?
All the home stepper actions have a `finalize` function 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4079)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4079)*

**Pull request merged**
