### PR TITLE
Fixed missing text in the scripture pane

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Verify the following verse isn't missing words (Titus 1:3)

image

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 176 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232#-LOx5uvC7DWrKqoKbYBE:-LOx5uvC7DWrKqoKbYBF:b-7362nw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/18106cb64b1fa187b5765db243d0e2a40b557ff4/package.json#L176)):*
> ```JSON
>     "tc-tool": "^2.0.0-rc.1",
>     "tc-ui-toolkit": "^0.10.6",
>     "telnet-client": "0.15.5",
> ```

shouldn't this be 0.10.5 for v1.0.1?

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 176 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232#-LOx6pHy73VrGR9zFkTL:-LOx6huE24woecPf1vLj:bo1vkrq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/18106cb64b1fa187b5765db243d0e2a40b557ff4/package.json#L176)):*
> ```JSON
>     "tc-tool": "^2.0.0-rc.1",
>     "tc-ui-toolkit": "^0.10.6",
>     "telnet-client": "0.15.5",
> ```

I think this should be `"tc-ui-toolkit": "0.10.5",` so you don't pull in 0.10.6 which is for v1.0.2

**Comment by PhotoNomad0** [comment]
@mannycolon - it looks like this does fix the issue, but breaks the edit in tWords. I think if we pulled in a commit to tWords, then we will be good.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 176 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232#-LOx6pHy73VrGR9zFkTL:-LOxC6sK8KxTasa6Lr9n:b-aircvn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/18106cb64b1fa187b5765db243d0e2a40b557ff4/package.json#L176)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

I think this should be `"tc-ui-toolkit": "0.10.5",` so you don't pull in 0.10.6 which is for v1.0.2
</blockquote></details>

Unfortunately if you change this things are still broken.

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 176 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232#-LOx5uvC7DWrKqoKbYBE:-LOxNnn7AFTYxfZbrzYB:bwi4575) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/18106cb64b1fa187b5765db243d0e2a40b557ff4/package.json#L176)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

shouldn't this be 0.10.5 for v1.0.1?
</blockquote></details>

Not anymore 
___
*[package.json, line 176 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232#-LOx6pHy73VrGR9zFkTL:-LOxNrdM12R1ELJE7Bnh:b-6xxga2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/18106cb64b1fa187b5765db243d0e2a40b557ff4/package.json#L176)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Unfortunately if you change this things are still broken.
</blockquote></details>

Not that's not the case I added new versions 0.10.6 is for 1.0.1 and 0.10.7 is for 1.0.2

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Review by PhotoNomad0 — APPROVED** [review]

**Review by PhotoNomad0 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5232)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
