### PR TITLE
Navigation Optimization 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)

### CODE REVIEW

**Comment by da1nerd** [comment]
@mannycolon do you want to change the base branch to develop?

**Comment by mannycolon** [comment]
@neutrinog Actually this PR is for `1.0.2` and I will merge `release-v1.0.2` to develop after this branch is merged in.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 12 of 18 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 176 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116#-LNztOU51etWaVeHrFlf:-LNzshZb4U37UidXViT3:b-s19uo9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6a67c103957aa817cd492278febe61859078c413/package.json#L176)):*
> ```JSON
>     "tc-strings": "0.1.7",
>     "tc-tool": "^2.0.0-rc.1",
>     "tc-ui-toolkit": "github:translationCoreApps/tc-ui-toolkit#bugfix-mannycolon-5092",
> ```

Is this a temporary fix?

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 2 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[package.json, line 176 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116#-LNztOU51etWaVeHrFlf:-LO--Rbb2lXUHkr-z_wY:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6a67c103957aa817cd492278febe61859078c413/package.json#L176)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is this a temporary fix? 
</blockquote></details>

Done.

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @RoyalSix)

**Review by RoyalSix — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5116)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by da1nerd** [comment]
@mannycolon can you delete your feature branch when you are done with it? Thanks.

**Pull request merged**
