### PR TITLE
Fix - #2132 & #2297 -  Project Card column line-up and text wrapping

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

This fixes two issues which are fixed by making the project card tabular content be in HTML tables so every card has the same size column for time, book and language (https://github.com/unfoldingWord-dev/translationCore/issues/2297), and also when the text does wrap, it stays under the text rather than the glyph (https://github.com/unfoldingWord-dev/translationCore/issues/2132)

#### How to test this pull request:

- Add multiple projects, look at the projects page, note that the columns all line up to easily look for a certain project. 
- Add projects with a long book title or language (or just resize the window) and the text should wrap, being indented (not under the glyph)
- Run unit test "ProjectCard"

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3060)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3060)*

**Comment by mannycolon** [comment]
`Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. See ProjectCard > table > tr. Add a <tbody> to your code to match the DOM tree generated by the browser.
printWarning @ /Users/mannycolon/dev/translationCore/node_modules/fbjs/lib/warning.js:33`

**Comment by mannycolon** [comment]
@richmahn ^

**Comment by richmahn** [comment]
@mannycolon Fixed

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3060)*

**Pull request merged**
