### PR TITLE
Alignment tool drops the number "430" from Gal 3:17

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR addresses fixing the tokenization of numbers in the word alignment tool

#### Please include detailed Test instructions for your pull request:
- Download the project [here](https://github.com/unfoldingWord-dev/translationCore/files/2493708/49-GAL.usfm.zip)
- Load Gal 3:17 in tC and ensure `430` is in the word list and the target language
- `rm -rf node_modules`
- `npm i`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5295)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.2 (3545dad)](https://tc-builds.door43.org/build/feature-jay-4559/translationCore-linux-x64-1.0.2-3545dad.deb) is ready for download.
[macOS build 1.0.2 (3545dad)](https://tc-builds.door43.org/build/feature-jay-4559/translationCore-macos-x64-1.0.2-3545dad.dmg) is ready for download.
[Windows x64 build 1.0.2 (3545dad)](https://tc-builds.door43.org/build/feature-jay-4559/translationCore-win-x64-1.0.2-3545dad.setup.exe) is ready for download.
[Windows x32 build 1.0.2 (3545dad)](https://tc-builds.door43.org/build/feature-jay-4559/translationCore-win-x32-1.0.2-3545dad.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5295)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[tC_apps/wordAlignment, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5295#-LPShZtU5uo-BM5B8HC8:-LPShZtU5uo-BM5B8HC9:b-c80417) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6825851bd2b229bae0d58be1ccc6b31976c0cb27/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit d4afe90296d58f1aedb3252952a36541f727afdb
> ```

It looks like this is not the right wA tool commit?

**Comment by mannycolon** [comment]
I checked on the wA tool repo and the release-v1.0.2 branch and the Latest commit is `8e4d349.` Not sure if this is wrong in the branch or you're committing the wrong one. @RoyalSix

**Comment by RoyalSix** [comment]
@mannycolon I added the commit because I updated the modules in tC that the word alignment tool is using. Just keeping the wA and tC packages in sync even though wA does even use its own `package.json` for its modules

**Comment by mannycolon** [comment]
Local Testing: `LGTM`
Core review: `LGTM`

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5295)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
