### PR TITLE
Rewrote Project/Tool loading

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Fixed fresh project bug with Project Card.
- Moved 
```
CurrentToolsActions
ToolsActions
GetDataActions
openProjectActions
```
To 
```
ProjectSelectionActions.js
ToolSelectionActions.js
ProjectLoadingActions.js
ToolsMetadataActions.js
``` 

#### How to test this pull request:

-Load a used and a fresh project with tW and tN.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2018)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: 1 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: 2 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: 3 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: 4 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by RoyalSix** [comment]
Reviewed 21 of 22 files at r3.
Review status: 20 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ProjectLoadingActions.js, line 86 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpaJYLR3_jEfroWdVE:-KnpaJYLR3_jEfroWdVF:bnxu8jp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ProjectLoadingActions.js#L86)):*
> ```JavaScript
>  * @return {object} object action / Promises.
>  */
> export function getGroupData(dispatch, dataDirectory, currentToolName, params) {
> ```

getGroupData vs getGroupsData any reason you're going with the singular here?

---

*[src/js/actions/ProjectLoadingActions.js, line 107 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-Knparlstg5ZoijCOb86:-Knparlstg5ZoijCOb87:bdau22v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ProjectLoadingActions.js#L107)):*
> ```JavaScript
>       ResourcesHelpers.copyGroupsDataToProjectResources(currentToolName, groupsDataDirectory, params.bookAbbr);
>       // read in the groupsData files
>       let groupDataFolderObjs = fs.readdirSync(groupsDataDirectory);
> ```

If the second part of this else (lines ) `allGroupsData = loadAllGroupsData(groupDataFolderObjs, groupsDataDirectory, currentToolName, dispatch);` to `resolve(true);` is the same as above does it make sense to factor it out into another function?

---

*[src/js/actions/ResourcesActions.js, line 50 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbmydTSSk-FWchfuS:-KnpbmydTSSk-FWchfuT:bjlfqvq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ResourcesActions.js#L50)):*
> ```JavaScript
>           let bibleData = {};
>           bibleData[chapter] = bibleChapterData;
>           console.log(bibleData)
> ```

console log

---

*[src/js/actions/TargetLanguageActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbwbjxnYlD9HKa2jV:-KnpbwbjxnYlD9HKa2jW:beeijrz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c025e2f66d98a3e2b17cb3b7c6cd148c74657aa/src/js/actions/TargetLanguageActions.js#L13)):*
> ```JavaScript
> export function loadTargetLanguageChapter(chapterNumber) {
>   return ((dispatch, getState) => {
>     let projectDetailsReducer = getState().projectDetailsReducer;
> ```

spacing on this line is off I believe

---

*[src/js/actions/ToolSelectionActions.js, line 40 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-Knpc98z4BCe722lSbui:-Knpc98z4BCe722lSbuj:bb8ruu8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ToolSelectionActions.js#L40)):*
> ```JavaScript
>       dispatch(saveToolViews(checkArray));
>       // load project data
>       dispatch(ProjectLoadingActions.loadProjectData(currentToolName));
> ```

Nice separation of actions here

---

*[src/js/containers/LoaderContainer.js, line 21 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpcT-6HGxUnv6mD2Zv:-KnpcT-6HGxUnv6mD2Zw:bmlbhcl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/containers/LoaderContainer.js#L21)):*
> ```JavaScript
> };
> 
> const mapDispatchToProps = (dispatch, ownProps) => {
> ```

Do we still need this function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by RoyalSix** [comment]
When I opened this [project](https://github.com/unfoldingWord-dev/translationCore/files/1113513/bes_tit_text_reg.zip) and opening tN when the tool first loads the translation article file is blank

**Comment by klappy** [comment]
*[src/js/actions/ProjectLoadingActions.js, line 86 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpaJYLR3_jEfroWdVE:-Knpe_wkxu8uhkNNymcg:b-q3jqm2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ProjectLoadingActions.js#L86)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

getGroupData vs getGroupsData any reason you're going with the singular here?
</blockquote></details>

From the look of the code, it appears to get allGroupsData, so it should be plural.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by mannycolon** [comment]
Review status: 20 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ProjectLoadingActions.js, line 86 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpaJYLR3_jEfroWdVE:-Knpg6OphvqydbAKRGFZ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ProjectLoadingActions.js#L86)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

From the look of the code, it appears to get allGroupsData, so it should be plural.
</blockquote></details>

Done.

---

*[src/js/actions/ProjectLoadingActions.js, line 107 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-Knparlstg5ZoijCOb86:-KnpiS_r49NpVWbWuAUs:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ProjectLoadingActions.js#L107)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

If the second part of this else (lines ) `allGroupsData = loadAllGroupsData(groupDataFolderObjs, groupsDataDirectory, currentToolName, dispatch);` to `resolve(true);` is the same as above does it make sense to factor it out into another function?
</blockquote></details>

Done.

---

*[src/js/actions/ResourcesActions.js, line 50 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbmydTSSk-FWchfuS:-KnpgjcnwaTlTMnOHvyg:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ResourcesActions.js#L50)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

console log
</blockquote></details>

Done.

---

*[src/js/actions/TargetLanguageActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbwbjxnYlD9HKa2jV:-Knpgte2tXm_xbp2jLWz:b-7jfxaj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c025e2f66d98a3e2b17cb3b7c6cd148c74657aa/src/js/actions/TargetLanguageActions.js#L13)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

spacing on this line is off I believe
</blockquote></details>

Don't see any spacing issues. what exactly do you mean?

---

*[src/js/actions/ToolSelectionActions.js, line 40 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-Knpc98z4BCe722lSbui:-KnpgzG_Y5tv_tXFG58K:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/actions/ToolSelectionActions.js#L40)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Nice separation of actions here
</blockquote></details>

Done.

---

*[src/js/containers/LoaderContainer.js, line 21 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpcT-6HGxUnv6mD2Zv:-Knph6NI8FX4nKORcrLo:b-4we5iw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/03015895115c753bf7a584174c5ac2384d3fd008/src/js/containers/LoaderContainer.js#L21)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we still need this function?
</blockquote></details>

Not right now but in the future we may need to add actions here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: 19 of 21 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r4.
Review status: 20 of 21 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/TargetLanguageActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbwbjxnYlD9HKa2jV:-KnrZHKLgqDPp4XTMxKK:b-exicl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c025e2f66d98a3e2b17cb3b7c6cd148c74657aa/src/js/actions/TargetLanguageActions.js#L13)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Don't see any spacing issues. what exactly do you mean?
</blockquote></details>

looks good now, not sure what happened haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/TargetLanguageActions.js, line 13 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-KnpbwbjxnYlD9HKa2jV:-Knt5-myRMSqjMZM3i29:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c025e2f66d98a3e2b17cb3b7c6cd148c74657aa/src/js/actions/TargetLanguageActions.js#L13)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

looks good now, not sure what happened haha
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 2 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 22 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018#-:-KntBl4D6vYMrgrCR-Ps:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r5.
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix Now this branch should be working the same way as develop

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2018)*

**Pull request merged**
