### PR TITLE
Fix package manager

### PR DESCRIPTION
**Pull request by ihoegen**
Issues resolved by this PR:
#281 
#249 
#300 
#385 

This PR should make npm and babel work for everybody, including builds, and fix some common errors found in the package manager.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/386)

### CODE REVIEW

**Comment by t3hpr1m3** [comment]
I noticed that you got rid of all those shims in `scripts/build/.bin`.  Noice! +1

**Comment by mannycolon** [comment]
Reviewed 30 of 33 files at r1, 7 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/386)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/386)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/386)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/386)*

**Pull request merged**
