### PR TITLE
redux resources

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

This PR aims to eliminate the usage of the following api calls:
```
api.getDataFromCommon('originalLanguage'); **greek/hebrew**
api.getDataFromCommon('gatewayLanguage'); **ULB/UDB**
api.getDataFromCommon('targetLanguage');
api.getDataFromCheckStore('TranslationHelps', 'wordList');
api.getDataFromCheckStore('TranslationHelps', 'sectionList')
```
Now all of these resources will be pass down as props from resourcesReducer

**TODO: still need to load this resources to the resourcesReducer with the new project load implementation. therefore resourcesReducer only has all resources when fetch data in run.**

#### How to test this pull request:

1. To test this branch you must load a fresh project.
2. pull all the branches mentioned below.
3. log this.props in app.js render method and make sure you see the resourcesReducer with bibles 
(originalLanguage, targetLanguage, ULB and UDB) and resources (tN or tW)

This PR is related to the following PRs and branches in the tools repos:

- https://github.com/translationCoreApps/translationWords_Check_plugin/pull/49 (feature/mc-fetchdata-redux)

- https://github.com/translationCoreApps/translationNotes_Check_plugin/pull/44 (feature/mc-fetchdata-redux)

- https://github.com/translationCoreApps/ScripturePane/pull/22 (feature/mc-fetchdata-redux)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/924)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfbERSU78Qt2EN4CSXF:-KfbERSU78Qt2EN4CSXG:b-s5gkqk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/69bc9c59578c06bbc8668e80814db37fe89742a5/src/js/reducers/projectDetailsReducer.js#L13)):*
> ```JavaScript
>           ...state,
>           projectSaveLocation: action.pathLocation,
>         }
> ```

I'm not certain but I vaguely remember having an issue where a Switch that returns without a break still returns a second time in the default. I'm going to test it and comment on my findings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfbERSU78Qt2EN4CSXF:-KfbFZ6iC56vGaS-9YVt:buubmqy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/69bc9c59578c06bbc8668e80814db37fe89742a5/src/js/reducers/projectDetailsReducer.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm not certain but I vaguely remember having an issue where a Switch that returns without a break still returns a second time in the default. I'm going to test it and comment on my findings.
</blockquote></details>

Looks good, the return breaks naturally and no need to add it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by klappy** [comment]
*[src/js/reducers/projectDetailsReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfbERSU78Qt2EN4CSXF:-KfbFkVGuP2q92xb2Doz:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/69bc9c59578c06bbc8668e80814db37fe89742a5/src/js/reducers/projectDetailsReducer.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Looks good, the return breaks naturally and no need to add it.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by klappy** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by RoyalSix** [comment]
Review status: 10 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/components/core/create_project/CheckDataGrabber.js, line 20 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfdsV5KKWG4r9mTwDp3:-KfdsV5KKWG4r9mTwDp4:b-tzoutf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52025407ba327a9f20f53d6a143488e9d08b26df/src/js/components/core/create_project/CheckDataGrabber.js#L20)):*
> ```JavaScript
> import { saveModule } from '../../../actions/LoaderActions';
> import { addNewResource, addNewBible } from '../../../actions/ResourcesActions';
> >>>>>>> 544e5a244d9c42a74c60b0511a79a6268e10586e
> ```

Git merge leftovers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by RoyalSix** [comment]
Review status: 10 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/index.js, line 41 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-Kfdsmik9nESplvvQYHE:-Kfdsmik9nESplvvQYHF:bum08bq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52025407ba327a9f20f53d6a143488e9d08b26df/src/js/reducers/index.js#L41)):*
> ```JavaScript
>   popoverReducer,
>   resourcesReducer,
> <<<<<<< HEAD
> ```

Unfinished git merge 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by RoyalSix** [comment]
Error on usfm import 
screen shot 2017-03-19 at 9 07 48 pm

**Comment by mannycolon** [comment]
Review status: 10 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/create_project/CheckDataGrabber.js, line 20 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfdsV5KKWG4r9mTwDp3:-KfgKshQe_Ww7C0iWaIG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52025407ba327a9f20f53d6a143488e9d08b26df/src/js/components/core/create_project/CheckDataGrabber.js#L20)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Git merge leftovers
</blockquote></details>

Done.

---

*[src/js/reducers/index.js, line 41 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-Kfdsmik9nESplvvQYHE:-KfgKvHPlotbiJb1DRyG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52025407ba327a9f20f53d6a143488e9d08b26df/src/js/reducers/index.js#L41)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Unfinished git merge 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by mannycolon** [comment]
Review status: 10 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/reducers/projectDetailsReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KfbERSU78Qt2EN4CSXF:-KfgKy85XhIjGGF6nuud:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/69bc9c59578c06bbc8668e80814db37fe89742a5/src/js/reducers/projectDetailsReducer.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by ihoegen** [comment]
@mannycolon Could you update the tests as well

**Comment by EllDoubleYew** [comment]
Reviewed 9 of 18 files at r1, 6 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/components/core/MenuBar.js, line 18 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflQrYewkbu9m9iXEDB:-KflQrYewkbu9m9iXEDC:b-t1jjxz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/components/core/MenuBar.js#L18)):*
> ```JavaScript
> import { showNotification } from '../../actions/NotificationActions.js'
> import { dispatch } from "../../pages/root"
> const fs = require(window.__base + 'node_modules/fs-extra');
> ```

why cant we just say import fs from 'fs-extra' ? 

---

*[src/js/utils/loadMethods.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflRHOmCaGx0_lP6A2L:-KflRHOmCaGx0_lP6A2M:b-g830qs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/utils/loadMethods.js#L6)):*
> ```JavaScript
> const PARENT = pathex.datadir('translationCore')
> const SETTINGS_DIRECTORY = pathex.join(PARENT, 'settings.json')
> const RESOURCES_DATA_DIR = pathex.join('apps', 'translationCore', 'resources')
> ```

I know ian mentioned his concerns with windows compatability on this file path. I tested another branch that used this same implementation with no problems, however I would like to test this branch explicitly. @ihogen could you test this too on your windows to be sure?

---

*[src/js/utils/saveMethods.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflRWmSVT8Cs0N7Qmu7:-KflRWmSVT8Cs0N7Qmu8:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/utils/saveMethods.js#L6)):*
> ```JavaScript
> const PARENT = pathex.datadir('translationCore')
> const SETTINGS_DIRECTORY = pathex.join(PARENT, 'settings.json')
> const RESOURCES_DATA_DIR = pathex.join('apps', 'translationCore', 'resources')
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by mannycolon** [comment]
Review status: 12 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/core/MenuBar.js, line 18 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflQrYewkbu9m9iXEDB:-Kflfkjl-vb74PXhHhPm:bo0b2ia) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/components/core/MenuBar.js#L18)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

why cant we just say import fs from 'fs-extra' ? 
</blockquote></details>

That was not me it was just there. idk why they did it.
Done.

---

*[src/js/utils/loadMethods.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflRHOmCaGx0_lP6A2L:-Kflfyw2cvmokT38fV64:b-erj2ah) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/utils/loadMethods.js#L6)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

I know ian mentioned his concerns with windows compatability on this file path. I tested another branch that used this same implementation with no problems, however I would like to test this branch explicitly. @ihogen could you test this too on your windows to be sure?
</blockquote></details>

this should be good. basically following the new data structure. but yeah definitely test the branch.

---

*[src/js/utils/saveMethods.js, line 6 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924#-KflRWmSVT8Cs0N7Qmu7:-KflgKTRREqAqE7baNDA:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99599b596223293dde919485d84d904446fbea6c/src/js/utils/saveMethods.js#L6)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/924)*

**Comment by ihoegen** [comment]
@mannycolon You need to delete the folders CommentBox and ProposedChanges, they are causing tests to fail.

**Comment by ihoegen** [comment]
@mannycolon Fix the tests and I'll merge

**Comment by ihoegen** [comment]
@mannycolon it appears you removed ScripturePane, translationNotes, and translationWords as well

**Comment by ihoegen** [comment]
image
I added the missing submodules, but now I also get this error:

**Comment by ihoegen** [comment]
The first error occurs when loading a project from localStorage. The other occurs when clicking recent projects on the main screen

**Comment by mannycolon** [comment]
im fixing it

**Comment by ihoegen** [comment]
@mannycolon Now it won't start for me: 
image

**Pull request merged**
