### PR TITLE
Feature mcleanb 4078/unblock OT in non-developer mode

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- unblocked OT in non-developer mode

#### Please include detailed Test instructions for your pull request:
- install the build attached at bottom of this PR.
- switch off developer mode
- download Ancient Hebrew (uhb) resources.
- should be able to do USFM import of OT books
- when editing project details, book name drop down should include OT books
- should be able to select an OT book and go to tools menu.  WA should be enabled to launch.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5438)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9a5f794)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-linux-x64-1.1.0-9a5f794.deb) is ready for download.
[macOS build 1.1.0 (9a5f794)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-macos-x64-1.1.0-9a5f794.dmg) is ready for download.
[Windows x64 build 1.1.0 (9a5f794)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x64-1.1.0-9a5f794.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9a5f794)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x32-1.1.0-9a5f794.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8a37e65)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-linux-x64-1.1.0-8a37e65.deb) is ready for download.
[macOS build 1.1.0 (8a37e65)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-macos-x64-1.1.0-8a37e65.dmg) is ready for download.
[Windows x64 build 1.1.0 (8a37e65)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x64-1.1.0-8a37e65.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8a37e65)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x32-1.1.0-8a37e65.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (46c2e7f)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-linux-x64-1.1.0-46c2e7f.deb) is ready for download.
[macOS build 1.1.0 (46c2e7f)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-macos-x64-1.1.0-46c2e7f.dmg) is ready for download.
[Windows x64 build 1.1.0 (46c2e7f)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x64-1.1.0-46c2e7f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (46c2e7f)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x32-1.1.0-46c2e7f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f7ddd78)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-linux-x64-1.1.0-f7ddd78.deb) is ready for download.
[macOS build 1.1.0 (f7ddd78)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-macos-x64-1.1.0-f7ddd78.dmg) is ready for download.
[Windows x64 build 1.1.0 (f7ddd78)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x64-1.1.0-f7ddd78.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f7ddd78)](https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x32-1.1.0-f7ddd78.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5438#-:-LRhDhC5BRtGzmCact0V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Pull request merged**
