### PR TITLE
Feature - Issue #2216 - Makes FAB words clickable

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

FAB labels not being clickable

#### How to test this pull request:

Go to the projects page, click the FAB button, click the labels. Clicking the labels should do the same as clicking the icons.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3028)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3028)*

**Comment by mannycolon** [comment]
@richmahn Your code and functionality look good. However, your pull request is decreasing test coverage.

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3028)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3028#-:-KyGQOwcWFuK9OVEKbq1:bg7igk9)*

**Comment by PhotoNomad0** [comment]
Tested and worked well.

**Pull request merged**
