### PR TITLE
translationWords Rewrite (with tc-ui-toolkit)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR removes the logic from all the components in tW and uses the `tc-ui-toolkit` module to render components.

#### Please include detailed Test instructions for your pull request:
- Run `npm i` on the translationCore branch
- Pull the branch `feature-jay-4318` on translationWords branch
- Ensure all functionality is the same as before
  - Every piece of code in tW was touched so this needs to be thoroughly checked
- Ensure all component are visually the same as before.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492)*

**Comment by mannycolon** [comment]
@RoyalSix Merge with latest develop branch

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by mannycolon** [comment]
@RoyalSix Merge with latest develop branch

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by RoyalSix** [comment]
<s>Note: The tW branch has an npm install from the github branch `feature-jay-scripture-pane-fix`
After the PR https://github.com/translationCoreApps/tc-ui-toolkit/pull/22 gets merged then we can `npm publish` and use the master branch</s>

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[package.json, line 126 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj-wl4AzPLFZXQUqgO:-LDj-wl5CcP1Ye_NMVFs:b-rtidfd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/package.json#L126)):*
> ```JSON
>     "mkdirp": "0.5.1",
>     "moment": "2.19.2",
>     "natural": "^0.6.0",
> ```

is this module needed?

---

*[package.json, line 167 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj-rtE-z6fl2t2kqaH:-LDj-rtE-z6fl2t2kqaI:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/package.json#L167)):*
> ```JSON
>     "truncate-utf8-bytes": "1.0.2",
>     "usfm-js": "1.0.0-beta.30",
>     "usfm-parser": "^0.1.6",
> ```

ibid

---

*[tC_apps/translationWords, line 1 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj0CU1C0xc2LWnoAJM:-LDj0CU1C0xc2LWnoAJN:br0x4bv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/tC_apps/translationWords#L1)):*
> ```
> Subproject commit f57f7e2b853703e71421bcb45bf9db3961332a2c
> ```

do you want/need the tool commit to be here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492)*

**Comment by mannycolon** [comment]
@RoyalSix tests are failing

**Comment by RoyalSix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 126 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj-wl4AzPLFZXQUqgO:-LDrUWfh34xsKAX8NMzK:bss4a2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/package.json#L126)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this module needed?
</blockquote></details>

Removed.

---

*[package.json, line 167 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj-rtE-z6fl2t2kqaH:-LDrUXwBESSHqfHBN5o2:bss4a2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/package.json#L167)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Removed.

---

*[tC_apps/translationWords, line 1 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-LDj0CU1C0xc2LWnoAJM:-LDrU_6d3fErfSxJGJuZ:bss4a2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1910a7093b42e47887a845fb27e7c8b87d82ed24/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do you want/need the tool commit to be here?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4492#-:-LDrYCU_7ue0bujSx2so:bnfp4nl)*

**Comment by mannycolon** [comment]
Code Review: `LGTM`
Local Test: `Pending necessary changes in both wA and tW`

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (3969390)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-3969390.zip) is ready for download.
[macOS build 0.10.0 (3969390)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-3969390.dmg) is ready for download.
[Windows x64 build 0.10.0 (3969390)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-3969390.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (3969390)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-3969390.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (10368ba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-10368ba.zip) is ready for download.
[macOS build 0.10.0 (10368ba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-10368ba.dmg) is ready for download.
[Windows x64 build 0.10.0 (10368ba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-10368ba.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (10368ba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-10368ba.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (43ac2dd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-43ac2dd.zip) is ready for download.
[macOS build 0.10.0 (43ac2dd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-43ac2dd.dmg) is ready for download.
[Windows x64 build 0.10.0 (43ac2dd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-43ac2dd.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (43ac2dd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-43ac2dd.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM: Local testing - selections, navigating previous/next, invalidating, edit in check and Scripturepane, bookmarks, comments, filters

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (7cdeabf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7cdeabf.zip) is ready for download.
[macOS build 0.10.0 (7cdeabf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7cdeabf.dmg) is ready for download.
[Windows x64 build 0.10.0 (7cdeabf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-7cdeabf.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (7cdeabf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-7cdeabf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (4f5268c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-4f5268c.zip) is ready for download.
[macOS build 0.10.0 (4f5268c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-4f5268c.dmg) is ready for download.
[Windows x64 build 0.10.0 (4f5268c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-4f5268c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (4f5268c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-4f5268c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (7fe3f8c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7fe3f8c.zip) is ready for download.
[macOS build 0.10.0 (7fe3f8c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7fe3f8c.dmg) is ready for download.
[Windows x64 build 0.10.0 (7fe3f8c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-7fe3f8c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (7fe3f8c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-7fe3f8c.setup.exe) is ready for download.

**Pull request merged**
