### PR TITLE
Parsed and added new source UGNT

### PR DESCRIPTION
**Pull request by RoyalSix**
I left the parsing tool in our code as well for when resources get updated
Checks to be performed:
- [ ] Load a fresh project
- [ ] Check for "TPane finished loading in console" (If is a fresh project)
- [ ] Check TPane OL for accents
- [ ] Check OL for word definition data on click
- [ ] Check for OL in params

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/253)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 68 of 68 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Comment by mannycolon** [comment]
@RoyalSix I will be testing your branch in a few minutes

**Comment by mannycolon** [comment]
@RoyalSix sorry, I really don't have a clear understanding of what this PR is supposed to add to the app.

**Comment by mannycolon** [comment]
@RoyalSix I'm getting this output in the console, is this supposed to happened?
and the loader is just lagging there 
screen shot 2016-10-28 at 6 10 05 pm

**Comment by RoyalSix** [comment]
This is happening because we are stripping the spaces, on reading in a book name. Not sure why we are doing this but I will fixed the data to match. thanks @mannycolon 

```
function bookAbbreviationToBookPath(bookAbbr) {
  var bookName = api.convertToFullBookName(bookAbbr);
  bookName = stripSpaces(bookName) + '.json';
  return bookName;
}
```

**Comment by EllDoubleYew** [comment]
Review status: 46 of 63 files reviewed at latest revision, 2 unresolved discussions.

---

_[greek.js, line 27 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253#-KVWAwoXFigeYPDsOcwI:-KVWAwoYWT06r7phYdCS:bkzd07r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3653d5005a1035b871505bd6d982ebf6f7e06bce/greek.js#L27)):_

> ``` JavaScript
>                 var current_chapter = data[verseRef]['Reference'].split(" ")[1].split(":")[0];
>                 var current_verse = data[verseRef]['Reference'].split(" ")[1].split(":")[1];
>                 if (book[name] == undefined) book[name] = {};
> ```

Can we pretty please expand out these if statements to have code blocks below them? I have no clue what is going on at all.

---

_[greek.js, line 48 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253#-KVWB40BFNGcojv25T70:-KVWB40BFNGcojv25T71:bb6xk7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3653d5005a1035b871505bd6d982ebf6f7e06bce/greek.js#L48)):_

> ``` JavaScript
>         var folder = fs.readdirSync(path.join(window.__base, 'UGNT'));
>         for (var excel in folder) {
>             if (folder[excel][0] == '.') continue;
> ```

Ibid

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Comment by mannycolon** [comment]
@RoyalSix looks good to me
 once you address @EllDoubleYew comments and merge develop into this branch it should be good to be merge

**Comment by mannycolon** [comment]
Reviewed 34 of 34 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[greek.js, line 27 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253#-KVWAwoXFigeYPDsOcwI:-KVeqSLvCcf4YmIjdlSC:b-pd4ak2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3653d5005a1035b871505bd6d982ebf6f7e06bce/greek.js#L27)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Can we pretty please expand out these if statements to have code blocks below them? I have no clue what is going on at all.
> </details>
> @royalsix did you get this done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[greek.js, line 48 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253#-KVWB40BFNGcojv25T70:-KVeqjCbp1hI1X7DqoZV:by5loqy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3653d5005a1035b871505bd6d982ebf6f7e06bce/greek.js#L48)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Ibid
> </details>
> @royalsix 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Comment by mannycolon** [comment]
Reviewed 6 of 7 files at r3.
Review status: 68 of 69 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Comment by mannycolon** [comment]
Reviewed 1 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/253)_

**Pull request merged**
