### PR TITLE
Added Localization For Duplicate Import Dialog

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR adds localizes dialogs to the alerts related to duplicate imports

#### Please include detailed Test instructions for your pull request:
- Download and import this [project](https://github.com/unfoldingWord-dev/translationCore/files/1798445/57-TIT.usfm.zip).
- Select a license and language name(remember this for later).
- Go back to the projects tab and import the same project (from local projects)
- Ensure there is an alert saying you cannot import the same project twice including the project name

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4015)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 2 of 31 files at r1.
Review status: 2 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4015)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 31 files at r1, 29 of 29 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4015#-:-L7QUI2PhinJ6iLKGkR_:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 1 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4015)*

**Comment by mannycolon** [comment]
Reviewed 1 of 31 files at r1, 29 of 29 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4015)*

**Pull request merged**
