### PR TITLE
Refactor HomeScreen Navigation Buttons

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR makes the homescreen navigation buttons have more meaningful text, and requires all prerequisites to have been  completed before enabling the next button

#### How to test this pull request:
Try opening going through the stepper process and making sure that you can only go to the next step when all prerequisites are done.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2186)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/ProjectSelectionActions.js, line 22 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2186#-KpHGF-fk__8Wz7oO0k6:-KpHGF-fk__8Wz7oO0k7:b-5yq2af) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/963290f33dc778617598bbf5076ab657843260e0/src/js/actions/ProjectSelectionActions.js#L22)):*
> ```JavaScript
> export function selectProject(projectPath, projectLink) {
>   return ((dispatch, getState) => {
>     debugger;
> ```

can you remove the debugger?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2186)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2186)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2186#-:-KpJIXxCd-_oTp6ogcaQ:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2186)*

**Pull request merged**
