### PR TITLE
updated missing reference

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6339)

### CODE REVIEW

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6339)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6339)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6339)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b8a9ffe)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-linux-x64-2.0.0-b8a9ffe.deb) is ready for download.
[macOS build 2.0.0 (b8a9ffe)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-macos-x64-2.0.0-b8a9ffe.dmg) is ready for download.
[Windows x64 build 2.0.0 (b8a9ffe)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x64-2.0.0-b8a9ffe.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b8a9ffe)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x32-2.0.0-b8a9ffe.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (d96baf4)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-linux-x64-2.0.0-d96baf4.deb) is ready for download.
[macOS build 2.0.0 (d96baf4)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-macos-x64-2.0.0-d96baf4.dmg) is ready for download.
[Windows x64 build 2.0.0 (d96baf4)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x64-2.0.0-d96baf4.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (d96baf4)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x32-2.0.0-d96baf4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c60aada)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-linux-x64-2.0.0-c60aada.deb) is ready for download.
[macOS build 2.0.0 (c60aada)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-macos-x64-2.0.0-c60aada.dmg) is ready for download.
[Windows x64 build 2.0.0 (c60aada)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x64-2.0.0-c60aada.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c60aada)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x32-2.0.0-c60aada.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (52aaacb)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-linux-x64-2.0.0-52aaacb.deb) is ready for download.
[macOS build 2.0.0 (52aaacb)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-macos-x64-2.0.0-52aaacb.dmg) is ready for download.
[Windows x64 build 2.0.0 (52aaacb)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x64-2.0.0-52aaacb.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (52aaacb)](https://tc-builds.door43.org/build/feature-mannycolon-4102/translationCore-win-x32-2.0.0-52aaacb.setup.exe) is ready for download.

**Pull request merged**
