### PR TITLE
Feature - #4022 - Removes constraint limitations to allow wA with NT

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses story #4022 

#### Please include detailed Test instructions for your pull request:
- Pretty much just make sure it works in regular mode and developer mode (no restrictions) as the story asks for, with the correct messages in 3 places.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4105)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[__tests__/LanguageHelpers.test.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84i9N7CYn4IkMdJI4z:-L84i9N8if4NAwJlSsiR:b-eac802) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/__tests__/LanguageHelpers.test.js#L58)):*
> ```JavaScript
>   });
> 
>   test('getGLHint() should return the desired tool tip for the launch button', () => {
> ```

Do we no longer need unit tests for getGLHint()?

---

*[src/js/components/BooksOfBible.js, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84iPdzr-fdwBeLEv8p:-L84iPe-yLS8ZU5vsicm:brsf0lu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/src/js/components/BooksOfBible.js#L2)):*
> ```JavaScript
> /**
>   * @description - The mapping of the book abbreviations to the full names.
> ```

Did you make sure this file isn't being used anywhere else?

---

*[src/js/helpers/LanguageHelpers.js, line 202 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84iwZmPzvGwwa-i5Nh:-L84iwZmPzvGwwa-i5Ni:b-o4rnn1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/src/js/helpers/LanguageHelpers.js#L202)):*
> ```JavaScript
>  * @param {Function} translate
>  */
> export function getGLHint(language, translate) {
> ```

We don't need this anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by mannycolon** [comment]
**Code review**: `Done`
**Local Test**: `Pending`

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[__tests__/LanguageHelpers.test.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84i9N7CYn4IkMdJI4z:-L88PM4Yz7SV4S8ACHS7:b-34t4ly) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/__tests__/LanguageHelpers.test.js#L58)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we no longer need unit tests for getGLHint()?
</blockquote></details>

This has been changed to handle more than just a GL Hint, but the whole status of why a tool can't be launched, so moved and renamed in the new ToolCardHelpers.js file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/BooksOfBible.js, line 2 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84iPdzr-fdwBeLEv8p:-L88PXrI5AdWEFeg9hHv:bdh2eyk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/src/js/components/BooksOfBible.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Did you make sure this file isn't being used anywhere else?
</blockquote></details>

Yes, I did. We also have the BooksOfTheBible.js file, and then one that our app uses from tC_resources, so was a duplicate and was not use anywhere, in any app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/helpers/LanguageHelpers.js, line 202 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L84iwZmPzvGwwa-i5Nh:-L88PhybCmqP9KfAaeuU:b-4edxju) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61679a73c6de7389a2e03f0592ee87a74e08f717/src/js/helpers/LanguageHelpers.js#L202)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

We don't need this anymore?
</blockquote></details>

Nope. One Status to rule them all.... so it's determined in ToolCardHelpers.js.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/helpers/ToolCardHelpers.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L88Q08Xrcys2vy_3Ith:-L88Q08Xrcys2vy_3Iti:b-3i2pbh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5d55d724412b299dfbb1d21ef5a151756b09292/src/js/helpers/ToolCardHelpers.js#L12)):*
> ```JavaScript
>  * @return {String} - Reason why it can't be launched
>  */
> export function getToolCardLaunchStatus(toolName, language, bookId, developerMode, translate) {
> ```

@mannycolon What was the getGLHint() has now been moved to here because we need to look at so much more if a GL has been selected (and actually GL is always populated by default, so not likely to happen that it is empty), but to see what book they are opening.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/helpers/ToolCardHelpers.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L88Q08Xrcys2vy_3Ith:-L88QPzjUmqao8wwD06_:b-wt54cr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5d55d724412b299dfbb1d21ef5a151756b09292/src/js/helpers/ToolCardHelpers.js#L12)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

@mannycolon What was the getGLHint() has now been moved to here because we need to look at so much more if a GL has been selected (and actually GL is always populated by default, so not likely to happen that it is empty), but to see what book they are opening.
</blockquote></details>

Book or Tool that is, and if is developerMode, etc. etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by bspidel** [comment]
LGTM

---

Reviewed 14 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/ToolCardHelpers.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-L88Q08Xrcys2vy_3Ith:-L88iK2eZO1YVl1ByJL6:b-85i64v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5d55d724412b299dfbb1d21ef5a151756b09292/src/js/helpers/ToolCardHelpers.js#L12)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Book or Tool that is, and if is developerMode, etc. etc.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105#-:-L88lhE2gFRruST7Sd-y:bb6ywmx)*

**Comment by mannycolon** [comment]
DO NOT MERGE YET

**Comment by richmahn** [comment]
Let us know when we can merge this one @mannycolon

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4105)*

**Comment by mannycolon** [comment]
Waiting on travis to finish

**Comment by mannycolon** [comment]
**Code review:** `LGTM`
**Local Test:** `LGTM`
**Travis Built** `Pending`

**Pull request merged**
