### PR TITLE
Added support for generating .deb packages for linux

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Sorta related to #4960 
-  This adds a new gulp task that will generate `.deb` packages which can be distributed for linux.

#### Please include detailed Test instructions for your pull request:
On linux only:

- build tc `./node_modules/.bin/gulp build --linux`
- compile deb `./node_modules/.bin/gulp release-linux-deb --out ./release/tc.deb`
- double click `tc.deb` to install

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5095)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (a6989fc)](https://tc-builds.door43.org/build/enhancement_joel_debian_packages/translationCore-linux-x64-1.0.0-a6989fc.zip) is ready for download.
[macOS build 1.0.0 (a6989fc)](https://tc-builds.door43.org/build/enhancement_joel_debian_packages/translationCore-macos-x64-1.0.0-a6989fc.dmg) is ready for download.
[Windows x64 build 1.0.0 (a6989fc)](https://tc-builds.door43.org/build/enhancement_joel_debian_packages/translationCore-win-x64-1.0.0-a6989fc.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (a6989fc)](https://tc-builds.door43.org/build/enhancement_joel_debian_packages/translationCore-win-x32-1.0.0-a6989fc.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5095)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by mannycolon** [comment]
I do not have a Linux machine accessible at the moment. @jag3773 Do you mind testing this PR?

**Comment by da1nerd** [comment]
@mannycolon were you going to merge this in?

**Comment by mannycolon** [comment]
@neutrinog I was actually hoping someone else would test it for me since I don't have a linux machine but I will merge it in anyway

**Pull request merged**
