### PR TITLE
Fixes builds not failing if there are errors

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This fixes a critical bug with the build process where failing tests or other build related problems would not cause the build to abort.

This will allow developers to more easily see why the builds failed. 

#### How to test this pull request:

This build will fail due to failing tests that were accidentally committed.
This PR should be merged in with it's failing state so developers have an opportunity to fix their tests and to prevent additional failing tests from being added.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3529)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3529)*

**Comment by mannycolon** [comment]
@neutrinog Unit Tests are failing

**Comment by da1nerd** [comment]
@mannycolon that's the point. The tests are actually failing on develop but you don't see them because of a bug in travis. This fixes the bug so you actually see the tests are failing.

**Comment by mannycolon** [comment]
@neutrinog lmao

**Pull request merged**
