### PR TITLE
Fixes project upload

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #5534 
- Corrects a bug that prevented some projects from being uploaded.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5537)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b2088ee)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-linux-x64-1.1.0-b2088ee.deb) is ready for download.
[macOS build 1.1.0 (b2088ee)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-macos-x64-1.1.0-b2088ee.dmg) is ready for download.
[Windows x64 build 1.1.0 (b2088ee)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x64-1.1.0-b2088ee.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b2088ee)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x32-1.1.0-b2088ee.setup.exe) is ready for download.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5537)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[package.json, line 189 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5537#-LT7ylLd8bgRiM3LMf46:-LT7ylLd8bgRiM3LMf47:b-d164c5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b2088ee010b84dcebe898bcbad827699b2d4f6e1/package.json#L189)):*
> ```JSON
>     "word-aligner": "0.2.6",
>     "wordmap": "^0.4.3",
>     "wordmap-lexer": "^0.3.4",
> ```

^ can cause build problems in tCore - particularly with releases.  Please remove.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5537)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
@neutrinog - In testing, getting error when I change the Translation Identifier and selecting to Rename on D43.

**Comment by da1nerd** [comment]
@PhotoNomad0 that's a pre-existing bug not related to this update. See https://github.com/unfoldingWord-dev/translationCore/issues/5532

Please ignore that error for the purpose of this PR.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (20b0a30)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-linux-x64-1.1.0-20b0a30.deb) is ready for download.
[macOS build 1.1.0 (20b0a30)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-macos-x64-1.1.0-20b0a30.dmg) is ready for download.
[Windows x64 build 1.1.0 (20b0a30)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x64-1.1.0-20b0a30.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (20b0a30)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x32-1.1.0-20b0a30.setup.exe) is ready for download.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5537)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

**Review by PhotoNomad0 — APPROVED** [review]

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d1dfe5c)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-linux-x64-1.1.0-d1dfe5c.deb) is ready for download.
[macOS build 1.1.0 (d1dfe5c)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-macos-x64-1.1.0-d1dfe5c.dmg) is ready for download.
[Windows x64 build 1.1.0 (d1dfe5c)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x64-1.1.0-d1dfe5c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d1dfe5c)](https://tc-builds.door43.org/build/bugfix_joel_5534_git-upload/translationCore-win-x32-1.1.0-d1dfe5c.setup.exe) is ready for download.

**Pull request merged**
