### PR TITLE
Feature 3579/Add indicator when switching context in group menu

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- performance tweaks for contextId changes - removed extra validations, batched redux operations
- tweak logging to remove unnecessary warnings (such as wordmap), system info, add complete startup logs.

#### Please include detailed Test instructions for your pull request:
- use build at bottom of issue.
- open each tool and make sure you can navigate groupmenu in all the tools without problems/crashing.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6376)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (5705ed2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-5705ed2.deb) is ready for download.
[macOS build 2.0.0 (5705ed2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-5705ed2.dmg) is ready for download.
[Windows x64 build 2.0.0 (5705ed2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-5705ed2.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (5705ed2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-5705ed2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (424dae9)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-424dae9.zip) is ready for download.
[macOS build 2.0.0 (424dae9)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-424dae9.dmg) is ready for download.
[Windows x64 build 2.0.0 (424dae9)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-424dae9.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (424dae9)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-424dae9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (079972e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-079972e.deb) is ready for download.
[macOS build 2.0.0 (079972e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-079972e.dmg) is ready for download.
[Windows x64 build 2.0.0 (079972e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-079972e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (079972e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-079972e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (36aac2e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-36aac2e.deb) is ready for download.
[macOS build 2.0.0 (36aac2e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-36aac2e.dmg) is ready for download.
[Windows x64 build 2.0.0 (36aac2e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-36aac2e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (36aac2e)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-36aac2e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (3625b65)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-3625b65.deb) is ready for download.
[macOS build 2.0.0 (3625b65)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-3625b65.dmg) is ready for download.
[Windows x64 build 2.0.0 (3625b65)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-3625b65.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (3625b65)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-3625b65.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (e5e7474)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-e5e7474.deb) is ready for download.
[macOS build 2.0.0 (e5e7474)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-e5e7474.dmg) is ready for download.
[Windows x64 build 2.0.0 (e5e7474)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-e5e7474.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (e5e7474)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-e5e7474.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (140afdb)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-140afdb.deb) is ready for download.
[macOS build 2.0.0 (140afdb)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-140afdb.dmg) is ready for download.
[Windows x64 build 2.0.0 (140afdb)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-140afdb.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (140afdb)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-140afdb.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (f18aae8)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-f18aae8.deb) is ready for download.
[macOS build 2.0.0 (f18aae8)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-f18aae8.dmg) is ready for download.
[Windows x64 build 2.0.0 (f18aae8)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-f18aae8.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (f18aae8)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-f18aae8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (29cba6c)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-29cba6c.deb) is ready for download.
[macOS build 2.0.0 (29cba6c)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-29cba6c.dmg) is ready for download.
[Windows x64 build 2.0.0 (29cba6c)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-29cba6c.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (29cba6c)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-29cba6c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (2a4a668)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-2a4a668.deb) is ready for download.
[macOS build 2.0.0 (2a4a668)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-2a4a668.dmg) is ready for download.
[Windows x64 build 2.0.0 (2a4a668)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-2a4a668.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (2a4a668)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-2a4a668.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b0cce34)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-b0cce34.deb) is ready for download.
[macOS build 2.0.0 (b0cce34)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-b0cce34.dmg) is ready for download.
[Windows x64 build 2.0.0 (b0cce34)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-b0cce34.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b0cce34)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-b0cce34.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (85d2786)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-85d2786.deb) is ready for download.
[macOS build 2.0.0 (85d2786)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-85d2786.dmg) is ready for download.
[Windows x64 build 2.0.0 (85d2786)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-85d2786.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (85d2786)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-85d2786.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b7c968b)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-b7c968b.deb) is ready for download.
[macOS build 2.0.0 (b7c968b)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-b7c968b.dmg) is ready for download.
[Windows x64 build 2.0.0 (b7c968b)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-b7c968b.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b7c968b)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-b7c968b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (e2a82f2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-e2a82f2.deb) is ready for download.
[macOS build 2.0.0 (e2a82f2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-e2a82f2.dmg) is ready for download.
[Windows x64 build 2.0.0 (e2a82f2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-e2a82f2.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (e2a82f2)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-e2a82f2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b7e74cd)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-b7e74cd.deb) is ready for download.
[macOS build 2.0.0 (b7e74cd)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-b7e74cd.dmg) is ready for download.
[Windows x64 build 2.0.0 (b7e74cd)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-b7e74cd.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b7e74cd)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-b7e74cd.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (751a3f0)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-751a3f0.deb) is ready for download.
[macOS build 2.0.0 (751a3f0)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-751a3f0.dmg) is ready for download.
[Windows x64 build 2.0.0 (751a3f0)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-751a3f0.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (751a3f0)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-751a3f0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (075b75a)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-linux-x64-2.0.0-075b75a.deb) is ready for download.
[macOS build 2.0.0 (075b75a)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-macos-x64-2.0.0-075b75a.dmg) is ready for download.
[Windows x64 build 2.0.0 (075b75a)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x64-2.0.0-075b75a.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (075b75a)](https://tc-builds.door43.org/build/feature-mcleanb-3579/translationCore-win-x32-2.0.0-075b75a.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
