### PR TITLE
recovered progress and checkmarks for menu on both tN & tW

### PR DESCRIPTION
**Pull request by mannycolon**
### This pull request addresses:

- This PR makes sure that if data was generated for comments, selections, verseEdits and/ or bookmarks/reminders then the groupdata used for the menu to reflect that progress is matched with that data.

- Recover data persistence for menu glyph icons #58 https://github.com/translationCoreApps/translationNotes_Check_plugin/pull/58

### How to test this pull request:

- **you must pull feature/mc-1333 from tN**

- leave a comment then in the group data file in the filesystem change it from true to false. then reload the project.

- On tN add comments, selections, everseEdits and/or bookmarks/reminders and the menu should reflect those changes.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1387)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Tested and confirmed to work on windows 👍

**Comment by EllDoubleYew** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1387#-:-Kj8lAUFaELbr1zOY2d2:bnfp4nl)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1387#-:-Kj98xBSRtiO2kq5hH7K:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1387)*

**Pull request merged**
