### PR TITLE
Fix For Errors When Opening Non-Compliant Projects

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR addresses a bug where if you open a project that manages to get into the projects folder, the alert dialog box works based on corresponding error it was caused from.

#### How to test this pull request:
To test this try opening an usfm file by copying it to the projects folder and selecting it. You should get an error.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3384)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@cckozie  @benjore What is an appropriate error message if a user tries and open a usfm file but it didnt go through the import process (the user probably just copied and pasted the file). The error right now says 'Manifest does not exist' because technically it doesn't. 
Should the message be more informative to the user?
I can add your response to the PR.

**Comment by mannycolon** [comment]
Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3384)*

**Comment by mannycolon** [comment]
@RoyalSix It is not clear what this PR is fixing?

**Comment by mannycolon** [comment]
@RoyalSix this PR is decreasing  test coverage

**Comment by RoyalSix** [comment]
@mannycolon The PR is fixing a bug that didn't allow the user to get to the projects page.
Along with the other branches in Scripture Pane and Verse Check ```bugfix-jay-2713```

**Comment by mannycolon** [comment]
@RoyalSix Ok looks good just waiting on test coverage.

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3384)*

**Pull request merged**
