### PR TITLE
Updated tN files packaged with tC to use latest tN mappings

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Open tC and if you did not have the latest tn it should be copied over automatically 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5981)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (079778a)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-079778a.deb) is ready for download.
[macOS build 1.2.0 (079778a)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-079778a.dmg) is ready for download.
[Windows x64 build 1.2.0 (079778a)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-079778a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (079778a)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-079778a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (e031475)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-e031475.deb) is ready for download.
[macOS build 1.2.0 (e031475)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-e031475.dmg) is ready for download.
[Windows x64 build 1.2.0 (e031475)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-e031475.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (e031475)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-e031475.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (a8a802c)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-a8a802c.deb) is ready for download.
[macOS build 1.2.0 (a8a802c)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-a8a802c.dmg) is ready for download.
[Windows x64 build 1.2.0 (a8a802c)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-a8a802c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (a8a802c)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-a8a802c.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
The groups data did not get redownloaded after opening tC.
I downloaded the build and had these resources https://team43.slack.com/files/U21QK2DEZ/FHR5M79G9/resources.zip

**Comment by mannycolon** [comment]
@RoyalSix Resolved problem with new resources not being copied over to the user resources folder

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (92acc42)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-92acc42.deb) is ready for download.
[macOS build 1.2.0 (92acc42)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-92acc42.dmg) is ready for download.
[Windows x64 build 1.2.0 (92acc42)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-92acc42.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (92acc42)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-92acc42.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (ece779b)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-ece779b.deb) is ready for download.
[macOS build 1.2.0 (ece779b)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-ece779b.dmg) is ready for download.
[Windows x64 build 1.2.0 (ece779b)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-ece779b.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (ece779b)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-ece779b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (ede8289)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-linux-x64-1.2.0-ede8289.deb) is ready for download.
[macOS build 1.2.0 (ede8289)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-macos-x64-1.2.0-ede8289.dmg) is ready for download.
[Windows x64 build 1.2.0 (ede8289)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x64-1.2.0-ede8289.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (ede8289)](https://tc-builds.door43.org/build/feature-mannycolon-5920/translationCore-win-x32-1.2.0-ede8289.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix)

**Pull request merged**
