### PR TITLE
Add Close Button To Popovers

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Bring explicit closing functionality to popovers

#### How to test this pull request:
Check the popovers in the app and ensure clicking the x at the top right closes them

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2825)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2825)*

**Comment by klappy** [comment]
@royalsix: 
I see two issues:
1. There seems to be an odd shifting of the layout of the heading from what it was before.
2. The red `X`doesn't seem to fit the look and feel of the rest of the app. Can we reuse the gray `x` already used in the scripture pane for consistency?

Before:


After: 


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2825#-:-KvZDsXXbfdm7IBlncdm:b45uc9p)*

**Comment by RoyalSix** [comment]
@klappy Nice suggestions! Fixed.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2825#-:-KvbjiFeYRJLrQolxQwc:bnfp4nl)*

**Pull request merged**
