### PR TITLE
semicolon linting

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

Enforces semicolon linting and fixes preexisting semicolon lint errors.

#### How to test this pull request:

Make sure the tests pass and there are no merge conflicts!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2750)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 128 of 128 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2750)*

**Comment by da1nerd** [comment]
Resolved the merge conflicts.

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2750)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2750#-:-Kuuvm_43rx-TaHuLtfE:bnfp4nl)*

**Pull request merged**
