### PR TITLE
Adds Feedback Suport

### LINKED ISSUE #2963: User Feedback

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):

Fixes #2963 and #3700.
This adds a feedback menu item to the global menu and corresponding dialog for submitting feedback.

#### Please include detailed Test instructions for your pull request:

You'll notice a new `env.sample` file in the repo. You must create a `.env` file with the key you saw in the other file then ask me on slack for a token to use.

> Note: travis is already configured to use a token when generating builds. So you could just push a copy of this branch to `sandbox-your-branch-copy` and wait for travis to build a copy for you.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3902)

### CODE REVIEW

**Comment by da1nerd** [comment]
I need to get travis to correctly decrypt and load the helpdesk api token.
This is blocked until then.

**Comment by mannycolon** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3902)*

**Comment by da1nerd** [comment]
This is now ready to be reviewed.

> NOTE: we cannot add tests for dialogs because there's a bug in ui-material < 1.x

**Comment by RoyalSix** [comment]
Reviewed 12 of 16 files at r1, 2 of 5 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[jsdoc/jsdoc.json, line 25 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3902#-L6UQIIC78g6h4HDTWvS:-L6UQIIC78g6h4HDTWvT:b-wwsksm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9a7bef34a577c4a348685d0a7f94eeaf17bd4c40/jsdoc/jsdoc.json#L25)):*
> ```JSON
>     "referenceTitle": "translationCore",
>     "search": {
>       "apiKey": "f12d46ccb502a9c723d200abe3e3befd",
> ```

I'm guessing this is a public key

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3902)*

**Comment by RoyalSix** [comment]
I'm getting a `401 Unauthorized` After filling out the feedback details and hitting submit on the username portion.
The API is returning `Unauthorized. Invalid or expired token.`
I took the steps to get my own .env.enc from the build on a [sandbox](http://tc-sandbox.unfoldingword.surge.sh/) branch

**Comment by da1nerd** [comment]
@RoyalSix that's the public token for the documentation search :P 
I send you a token for the feedback on slack.

**Comment by RoyalSix** [comment]
So I used the key you sent me.
I entered some feedback, how do I know if it worked.
I saw a console log saying there was a 401 error but this time the dialog gave feedback as if it worked

**Comment by da1nerd** [comment]
@RoyalSix I see your feedback in the helpdesk.

image

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing: `LGTM`

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3902)*

**Comment by PhotoNomad0** [comment]
@neutrinog - need to resolve conflicts.

**Comment by PhotoNomad0** [comment]
OK, the feedback part works, but the app ran into file permission issues on Windows when it was updating the resources (rimraf failed).  I was able to test by deleting the resources folder and rerunning the app.

**Comment by da1nerd** [comment]
@PhotoNomad0 conflicts resolved!

**Pull request merged**
