### PR TITLE
Bugfix #3485/Quotes lost on USFM import

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: https://github.com/unfoldingWord-dev/translationCore/issues/3485

Update to use new usfm-js with quote fix.

#### How to test this pull request:
- `npm install`
- Import USFM file in issue. 
- Open in WordAlignment tool.  
- Go to Heb 1:5 - the whole verse should displayed (compare with ULB) and should not lock up.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3507)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507)*

**Comment by mannycolon** [comment]
@PhotoNomad0 when i run **npm install** i get `No matching version found for usfm-js@1.0.0-beta.17.2`

**Comment by PhotoNomad0** [comment]
Manny, are you sure you didn't have this other PR loaded https://github.com/unfoldingWord-dev/translationCore/pull/3512?

That's the one that will use beta.17.2.

I verified that package.json and package.lock.json have correct usfm-js versions.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507#-:-L1O09n1wr1XBoEo8G7L:b-uk3xx2)*

**Comment by PhotoNomad0** [comment]
Ready for retest - now uses all parts of a verse array, not just first part on usfm import.

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507#-:-L1OR20EIsrDFvmGeR0D:bnfp4nl)*

**Comment by klappy** [comment]
For what it's worth, we'll need to let others know that they will have to reimport the USFM to get this to work properly, since it is an issue of import and not opening.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507#-:-L1OR3UyTdVjBosgl0yG:b7ymjff)*

**Comment by klappy** [comment]
Looks like everything works as it should and problems in the issue/story are resolved. Good job!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3507#-:-L1P0syyqMXQz9OKzFH1:bofiqba)*

**Pull request merged**
