### PR TITLE
Project Import Check Container Fixes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR improves the workflow and implementation of checking actions.

#### How to test this pull request:
Test this PR by going through the normal workflow of the project import check

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2411)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrGg2dgjNoSqJHQj33V:bcw2i2g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
> ```JavaScript
>  * 'mergeConflictCheck' if check is passed
>  */
> export function validate(state) {
> ```

why are you taking the state as a parameter?

wouldnt it be better to just do


```
return ((dispatch, getState) => {

});
```
?

---

*[src/js/actions/MergeConflictActions.js, line 32 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGdxN6ScRVJlfTEJ1G:-KrGdxN7bE8gLVviZiTi:b3tddkg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L32)):*
> ```JavaScript
>       type: consts.VALIDATE_PROJECT_STEP,
>       key: 'mergeConflictCheck',
>       data: false
> ```

maybe you want to rename data to value, boolean or payload

---

*[src/js/actions/ProjectValidationActions.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgNBcV0umZp96SvKT:-KrGgNBcV0umZp96SvKU:bjkvcoi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L38)):*
> ```JavaScript
> export function validateProject() {
>   return ((dispatch, getState) => {
>     const state = getState();
> ```

maybe don't send the state as a parameter and just access it from the action

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrGgexlVFXHQMci7Swx:bbkujgs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
> ```JavaScript
>     let previousStepName = projectValidationStepIndex[stepIndex - 1];
>     return dispatch({
>       type: consts.GO_TO_PROJECT_VALIDATION_STEP,
> ```

what does this action do? and why do we need it?

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGfgzZNoySDL1R7xdD:-KrGfgz_xlWzoQZyFnp_:byvewdj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
> ```JavaScript
> const MERGE_CONFLICT_NAMESPACE = "mergeConflictCheck";
> //actions
> import * as MergeConflictActions from '../../../actions/MergeConflictActions';
> ```

why do you have actions here?? why not just put them in the projectValidationContainer??

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 69 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGf5Vmcwr5cLtUY08k:-KrGf5Vmcwr5cLtUY08l:bqop1hz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L69)):*
> ```JavaScript
> 
>   openCard(index, open) {
>     let conflictCards = JSON.parse(JSON.stringify(this.state.conflictCards))
> ```

is doing the following the same as what you did there?

this.state.conflictCards.toString()


I guess my question is why stringify it and to then parse it?

---

*[src/js/reducers/projectValidationReducer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGeQZWNhsn9ivgtGzV:-KrGeQZWNhsn9ivgtGzW:b-3atstm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/reducers/projectValidationReducer.js#L14)):*
> ```JavaScript
>     stepIndex: 1,
>     nextStepName: 'Project Information',
>     previousStepName: 'Previous',
> ```

in the first step do we want to have a previous button?

@klappy @royalsix 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrH77rY4lU-qnlIzs5R:bbo0l8z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you taking the state as a parameter?

wouldnt it be better to just do


```
return ((dispatch, getState) => {

});
```
?
</blockquote></details>

It would. I would prefer to have it asynchronous as well but because we need actions to happen (Checking for steps that need to be completed) before making a change in the UI (Showing the tools or showing the stepper), the actions need to be synchronous. I would suggest promises but those get hacky when you are using them in a redux workflow.

---

*[src/js/actions/MergeConflictActions.js, line 32 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGdxN6ScRVJlfTEJ1G:-KrH5YUGhwzaAMrCI2dt:b-ul8jrf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L32)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe you want to rename data to value, boolean or payload
</blockquote></details>

Good idea

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrH5fmpAi9zW2I2e3WS:b-k17966) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what does this action do? and why do we need it?
</blockquote></details>

Its how you go to a step. Previous, next,  specific index...When the project first loads there needs to be an action to jump to the step that did not pass

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGfgzZNoySDL1R7xdD:-KrH6Epoiv7xgGqzmKoR:bbm3f8r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do you have actions here?? why not just put them in the projectValidationContainer??
</blockquote></details>

Because these actions are specific to the components in this component 'wrapper' we made. And the action called does not require the dispatcher.

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 69 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGf5Vmcwr5cLtUY08k:-KrH6kntQT-o4jW8Q5tR:bpm8t4z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L69)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is doing the following the same as what you did there?

this.state.conflictCards.toString()


I guess my question is why stringify it and to then parse it?


</blockquote></details>

This is different than toString() We need it as an object and we need it to be an object that does not reference the old one. Basically a clone.

---

*[src/js/reducers/projectValidationReducer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGeQZWNhsn9ivgtGzV:-KrH71ceFFnTarCtLJiQ:bs1uivi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/reducers/projectValidationReducer.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

in the first step do we want to have a previous button?

@klappy @royalsix 
</blockquote></details>

Isn't it like going back? how will they go back ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrHeHH2G7wYcPUN0rVs:bvwvkt8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It would. I would prefer to have it asynchronous as well but because we need actions to happen (Checking for steps that need to be completed) before making a change in the UI (Showing the tools or showing the stepper), the actions need to be synchronous. I would suggest promises but those get hacky when you are using them in a redux workflow.
</blockquote></details>

Would it make sense to be able to validate it from a helper and pass the specific payload that does need to be validated explicitly from the state? 
That way it is easier to make tests for it later? Maybe do as Manny suggested for the Action `validate()`, but it gets the dispatch/state and calls the helper?

Just thinking out loud, don't want to take too much time on this but think it would be worth it long term.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
*[src/js/reducers/projectValidationReducer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGeQZWNhsn9ivgtGzV:-KrHfXEnsPfd2BM_iIZb:b4teom5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/reducers/projectValidationReducer.js#L14)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Isn't it like going back? how will they go back ?
</blockquote></details>

Good point, maybe we can call it "Cancel"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
Reviewed 7 of 13 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by mannycolon** [comment]
Reviewed 1 of 13 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrHfTqKPEWmD1YjrI1x:bdiz5to) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Its how you go to a step. Previous, next,  specific index...When the project first loads there needs to be an action to jump to the step that did not pass
</blockquote></details>

"When the project first loads there needs to be an action to jump to the step that did not pass"


so wouldn't it just go to the steps that indicate true in the following object
for example 

```
 projectValidationStepsObject: {
      copyrightCheck: true,
      projectInformationCheck: false,
      mergeConflictCheck: true,
      missingVersesCheck: false
  },

```

then copyrightCheck  and mergeConflictCheck are the only ones to show up as imcomplete in the project validation stepper

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGfgzZNoySDL1R7xdD:-KrHg-c8aG_4TKyHZxWK:b-xb6okl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Because these actions are specific to the components in this component 'wrapper' we made. And the action called does not require the dispatcher.
</blockquote></details>

I'm thinking this should go in the actions object inside the projectValidationContainer

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 69 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGf5Vmcwr5cLtUY08k:-KrHg88j8VgOYeus_ATN:bi4jrx0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L69)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This is different than toString() We need it as an object and we need it to be an object that does not reference the old one. Basically a clone.
</blockquote></details>

ok makes sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrM9KkbfmCnA2ehzg2v:b-ia0q9m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Would it make sense to be able to validate it from a helper and pass the specific payload that does need to be validated explicitly from the state? 
That way it is easier to make tests for it later? Maybe do as Manny suggested for the Action `validate()`, but it gets the dispatch/state and calls the helper?

Just thinking out loud, don't want to take too much time on this but think it would be worth it long term.
</blockquote></details>

This action has to be synchronous so how could we do `return ((dispatch, getState) => {

});`
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrMEJ5hd7gWZojScyy_:b-sf3q2v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This action has to be synchronous so how could we do `return ((dispatch, getState) => {

});`
?
</blockquote></details>

<code>return ((dispatch, getState) => {
});</code> **

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrMEb0VXUfbN-DOP-_U:bnfpi1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

"When the project first loads there needs to be an action to jump to the step that did not pass"


so wouldn't it just go to the steps that indicate true in the following object
for example 

```
 projectValidationStepsObject: {
      copyrightCheck: true,
      projectInformationCheck: false,
      mergeConflictCheck: true,
      missingVersesCheck: false
  },

```

then copyrightCheck  and mergeConflictCheck are the only ones to show up as imcomplete in the project validation stepper
</blockquote></details>

I'm not sure what you mean by 'just go'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrWFInPQmXKm7zKYh_C:b3zaooh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I'm not sure what you mean by 'just go'
</blockquote></details>

so you basically get an array from the object above that only includes the ones with the true value. so for instance, from the example above it could look like


['copyrightCheck', 'mergeConflictCheck' ] and those would be the steps to be accessible in the project  validation stepper

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGfgzZNoySDL1R7xdD:-KrWHO1jvj2fV2527Qp6:b-y67ug8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I'm thinking this should go in the actions object inside the projectValidationContainer
</blockquote></details>

In the past, we've tried to keep them in the containers and not have to add them into components. I couldn't find any examples contrary, but there could be some out there that don't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
*[src/js/reducers/projectValidationReducer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGeQZWNhsn9ivgtGzV:-KrWHwV4r-2xZhcOk_AX:bb7otgp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/reducers/projectValidationReducer.js#L14)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good point, maybe we can call it "Cancel"
</blockquote></details>

Big picture, they do need a way to exit the "import" or "opening" of a project, previous might be misleading for the first one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: 6 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrWf1PKRAVRIUWyq6Kn:bu1764v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

so you basically get an array from the object above that only includes the ones with the true value. so for instance, from the example above it could look like


['copyrightCheck', 'mergeConflictCheck' ] and those would be the steps to be accessible in the project  validation stepper
</blockquote></details>

Ok, I understand that. That was my initial plan of implementation but the details in implementation don't work out as clearly as they did in my head.  In order to do it this was I think what we need is a separation of the data that is in each step and the failed steps that need to be looked at

---

*[src/js/reducers/projectValidationReducer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGeQZWNhsn9ivgtGzV:-KrWabdLRETA9xrKxGGr:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/reducers/projectValidationReducer.js#L14)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Big picture, they do need a way to exit the "import" or "opening" of a project, previous might be misleading for the first one. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: 6 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ProjectValidationActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGgexlVFXHQMci7Sww:-KrWzoEnorqh6jzMH2bK:b-ng0llg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/ProjectValidationActions.js#L103)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ok, I understand that. That was my initial plan of implementation but the details in implementation don't work out as clearly as they did in my head.  In order to do it this was I think what we need is a separation of the data that is in each step and the failed steps that need to be looked at
</blockquote></details>

And making that seemed like it was more complex that the way its already implemented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: 4 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGfgzZNoySDL1R7xdD:-KrX1hT9mkNZLmBI7AVb:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

In the past, we've tried to keep them in the containers and not have to add them into components. I couldn't find any examples contrary, but there could be some out there that don't.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by mannycolon** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/projectValidationReducer.js, line 21 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkhysHQN7aBvlnjL0s:-KrkhysIkV16TVJuKMRp:b-qv3ezw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L21)):*
> ```JavaScript
>         projectValidationStepsArray: [
>           ...state.projectValidationStepsArray.slice(),
>           action.stepObject
> ```

what does action.stepObject look like?

---

*[src/js/reducers/projectValidationReducer.js, line 28 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkiK3Z5BBHw8xpncq3:-KrkiK3Z5BBHw8xpncq4:bcr7loz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L28)):*
> ```JavaScript
>         ...state,
>         projectValidationStepsArray:
>         state.projectValidationStepsArray.filter((stepObject) => stepObject.namespace !== action.stepObject.namespace)
> ```

why do we have logic here? this logic should go in the action which return the result.

---

*[src/js/reducers/projectValidationReducer.js, line 53 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkiWCTEDYSvlcOjIsf:-KrkiWCTEDYSvlcOjIsg:b-qqwpi1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L53)):*
> ```JavaScript
>         }
>       }
>     case consts.TOGGLE_PROJECT_VALIDATION_STEPPER:
> ```

what does toggle project validation stepper mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by mannycolon** [comment]
@RoyalSix merge with develop and fix merge conflicts

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/projectValidationReducer.js, line 28 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkiK3Z5BBHw8xpncq3:-KrksYBBXjjaTZz-w3wG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L28)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we have logic here? this logic should go in the action which return the result.
</blockquote></details>

Done.

---

*[src/js/reducers/projectValidationReducer.js, line 53 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkiWCTEDYSvlcOjIsf:-KrksZJnBWf1o8UFPfFl:bzcrk5a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L53)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what does toggle project validation stepper mean?
</blockquote></details>

Show or do not show the stepper 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Review status: 4 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/reducers/projectValidationReducer.js, line 21 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrkhysHQN7aBvlnjL0s:-KrlD4k7jq9LHX1BgKgB:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e20073e8beb7bba565ba0689c5f826b623664ace/src/js/reducers/projectValidationReducer.js#L21)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what does action.stepObject look like?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
I made a task for this. I wonder why I had a hard time finding it and realized it was a lonely PR without a task/story.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-:-KrlRJIBupVmcDY2QWJB:b-qgcnjy)*

**Comment by klappy** [comment]
*[src/js/actions/MergeConflictActions.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-KrGg2dgjNoSqJHQj33U:-KrlRZv-AjBymOpZaqNc:b-jshd9d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7ed145a9567a3781d1adb503393dd2907ec4375a/src/js/actions/MergeConflictActions.js#L15)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

<code>return ((dispatch, getState) => {
});</code> **
</blockquote></details>

Just confirming and documenting that we confirmed that these actions are synchronous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
Reviewed 4 of 13 files at r3, 14 of 14 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by klappy** [comment]
From what I can see, it looks good to me. I'm going to test it now. I'm not working on this part of the code, but think that Manny can give more feedback if needed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-:-KrlSKxGawN-IunHN9WJ:b-x21725)*

**Comment by klappy** [comment]
@royalsix Found something to address. The Done button doesn't finish and takes you on an infinite increment. Can you address that.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-:-KrlWHCoLZBfqdMtNCNR:b-k3mc3g)*

**Comment by klappy** [comment]
nvm, pulled latest and all is well.
:D

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-:-KrlXlp-dxdqJa61H6ST:bm8mlu9)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411#-:-KrlXqgXtvZPVT6MEYcN:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 12 of 14 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix While testing with `ema-x-ora_php_text_ulb` when i clicked cancel  in the `project validation stepper` it still shows the Tools page and allows me to load the project without fixing the merge conflicts

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 14 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2411)*

**Pull request merged**
