### PR TITLE
UI to toggle online/offline mode

### PR DESCRIPTION
**Pull request by EllDoubleYew**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/719)

### CODE REVIEW

**Comment by ihoegen** [comment]
@EllDoubleYew I think the text for the switching online status should be the opposite color

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/js/components/core/SideBar/OnlineStatus.js, line 52 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719#-Kd2RDAfR_MRtRH3dWnp:-Kd2RDAgrG-95rUIniyE:btgjvys) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cd3a476ded9ce9d6d591bd61a1c00976eba6fac1/src/js/components/core/SideBar/OnlineStatus.js#L52)):*
> ```JavaScript
>                      />
>           <div onClick={()=>{
>                   this.state.online ? this.setOffline() : this.setOnline();
> ```

what is setOffline() and setOnline() actually doing ?? and where are they located ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719)*

**Comment by mannycolon** [comment]
@EllDoubleYew Can you make it so that I don't have to click on the arrow but the whole phrase to open the drop down menu. and can you make it so that when you make your selection the drop down menu closes automatically.

**Comment by mannycolon** [comment]
Reviewed 1 of 5 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719)*

**Comment by mannycolon** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[tC_apps/TranslationHelps, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719#-Kd72Ph-PHoIwz_b0h7U:-Kd72Ph0Qn7li1N99pc9:b-232ile) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/26402b82aa400b681ed73b2e4b67a1c6739aa1e1/tC_apps/TranslationHelps#L1)):*
> ```
> Subproject commit 8e98a4e307ce8006c2e65db7d6c2ebfc6255c8e2
> ```

this is not the latest version of translationHelps you may want to merge with develop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719)*

**Comment by mannycolon** [comment]
Reviewed 3 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/719)*

**Comment by ihoegen** [comment]
@mannycolon I just merged with develop

**Comment by mannycolon** [comment]
@ihoegen it doesnt have the latest version of `translationHelps`

**Comment by ihoegen** [comment]
@mannycolon It's updated now

**Comment by EllDoubleYew** [comment]
Can you confirm this is the latest version @mannycolon ?

**Pull request merged**
