### PR TITLE
Change references from apps to .apps

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

Addresses #1614 

#### How to test this pull request:

Try the app out, make sure nothing is broken. Use Atom to make sure all apps references are .apps

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1625)

### CODE REVIEW

**Comment by cdwhitfield73** [comment]
What about existing projects?  Do we need "migration" code to rename the apps folder in those?  I don't know that it will be acceptable to tell our test users that have already done checks that they have to delete their apps folder and let the app re-create it.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1625#-:-KkT-A94gdf4z1mEiI3j:b-e4qkvw)*

**Comment by ihoegen** [comment]
@cdwhitfield73 In terms of migration, all that has to be done is rename an existing apps folder to .apps. I don't know if we should leave this up to the user or if tC can do it

**Comment by klappy** [comment]
I've talked to Ben and we can guide the few users through renaming their folder from apps to .apps to make it compatible.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1625#-:-KkVyYVPF1Xy5z5cCAaq:bnfp4nl)*

**Comment by mannycolon** [comment]
we are in a very early stage to worry about migration.

**Pull request merged**
