### PR TITLE
Fix report opening

### PR DESCRIPTION
**Pull request by ihoegen**
Fixes the issue with opening a report view after the extraction of modules

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/228)

### CODE REVIEW

**Comment by mannycolon** [comment]
This is the error im getting when i try to filter the report cards @ihoegen 

screen shot 2016-10-18 at 1 59 18 pm

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/228)_

**Comment by ihoegen** [comment]
I blame @EllDoubleYew and his requirement.js

**Comment by mannycolon** [comment]
@ihoegen so what needs to be done to fix this requirement.js issue???

**Comment by mannycolon** [comment]
@ihoegen

**Comment by ihoegen** [comment]
@mannycolon, I'm going to merge and try again

**Comment by ihoegen** [comment]
@mannycolon Should be fixed now.

**Comment by mannycolon** [comment]
@ihoegen your branch seems is not merge with develop. is your develop updated with remote develop??

**Comment by ihoegen** [comment]
@mannycolon I am up to date with develop.

**Pull request merged**
