### PR TITLE
Feature - #3677 & #3678 - Filter menu for translationWords

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses issue #3677 and #3678 to complete #1998 

#### Please include detailed Test instructions for your pull request:
- [ ] cd to your translationCore dir, `git checkout feature-richmahn-3677`, make sure all apps are updated
- [ ] Run app, load a project, go into tW
- [ ] There is now a header for the left menu (wA also has the header, but no filter). Verify it looks good collapsed on your platform, including when you resize the screen (group menu should be right below the header)
- [ ] Expand the menu by clicking the funnel icon. Verify Group menu below it moved so nothing covered. Verify all looks like in #1998 mock-ups.
- [ ] Select/Edit/Comment/Bookmark various verses with none, one or multiple changes (Status Badge should changed accordingly in the precedent order given in #1998)
- [ ] Now select filters and verify the ones you changed are showing in regards to the filters you picked.
- [ ] Verify that Selection and No Selection options can't both be selected.
- [ ] Verify closing the filter menu (clicking the funnel) shows the Bubbles that you can remove, thus removes that filter.
- [ ] Verify works with supported languages, both as target language and GL language.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4282)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `Pending...`

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 16 files at r1, 7 of 17 files at r2, 16 of 16 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4282)*

**Comment by PhotoNomad0** [comment]
:lgtm: Code
:lgtm: Local Testing

**Comment by RoyalSix** [comment]
Reviewed 3 of 16 files at r1, 8 of 17 files at r2, 16 of 16 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4282)*

**Comment by RoyalSix** [comment]
Updated Local Testing: 
- What is the expected behavior for going to next and previous when a filter is on? Its kind of wonky right now.
- Everything related to the filter seems to work as expected


@richmahn

**Comment by PhotoNomad0** [comment]
I had filter on for edited and invalidated verses.  Then edited two verses in scripture pane and got this error:

screen shot 2018-04-23 at 9 09 12 am

**Comment by PhotoNomad0** [comment]
@richmahn - also I can't scroll the right menu.  There is no scrollbar, and scroll wheel doesn't work either.

**Comment by PhotoNomad0** [comment]
[el_tit 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1938775/el_tit.2.zip)

Had filter turned on for verse edit.  Added/changed text for verses 1 & 4.

But I never see the left menu scroll.

will also see the crash if I turn filters off.

**Comment by richmahn** [comment]
@PhotoNomad0 Try now.

**Comment by PhotoNomad0** [comment]
:lgtm: testing 
:lgtm: code

**Pull request merged**
