### PR TITLE
Feature mcleanb 4403/prompt for resource id and nickname

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes details missing in previous PR: hint for resource id, project nickname displayed in tools (along with hover), invalid characters warning before length, limit input length.

#### Please include detailed Test instructions for your pull request:
- See Kos's UI differences list at end of https://github.com/unfoldingWord-dev/translationCore/issues/4403 to make sure issues are addressed.  Here is the revised list of changes after spec changes:

1. The Translation Identifier field is now vertically aligned with the Language Name field
2. The info icon with popover is now implemented for "Translation Identifier"
3. The menu bar displayed when a tool is open displays the project name and will show the nickname as hover
4. If A-B is entered in the translation id field, the warning about Latin characters should appear after  the dash is entered rather than after the B is entered.
5. The UI should limit the field length length to 4 rather that re-disabling the Continue button when the 5th character is entered.
6. removed the text "Project:" in the menu title bar between the folder icon and the project name. 
7. did not change project card as it is outside of scope (at least at the moment).

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (c5c566c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-c5c566c.zip) is ready for download.
[macOS build 0.10.0 (c5c566c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-c5c566c.dmg) is ready for download.
[Windows x64 build 0.10.0 (c5c566c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-c5c566c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (c5c566c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-c5c566c.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Reviewed 1 of 12 files at r1, 22 of 22 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

---

*[__tests__/ProjectValidationActions.test.js, line 34 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561#-LEm896O59nc15l9zKVg:-LEm896P44VE-3WUJQj-:b-u7pzs8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5c566cfa4eb1bebf4870bd219c83cb0e74d9115/__tests__/ProjectValidationActions.test.js#L34)):*
> ```JavaScript
>       },
>       resource: {
>         slug: 'ult',
> ```

are you sure you want to replace id with slug?
isn't it better to just add slug in addition to id?
this could bring so many issues a lot of the codebase relies on the key being id



anyway, why even change it to id?

based on recent ts-desktop projects that i found on git.door43.org slug isn't used as a key inside the resource object in the manifest

examples:

https://git.door43.org/VGM/vi_ezk_tq/src/branch/master/manifest.json
https://git.door43.org/VGM/vi_psa_tq/src/branch/master/manifest.json
https://git.door43.org/fubuffalo/zh_exo_tq/src/branch/master/manifest.json
https://git.door43.org/dayakjokak/xdy-x-randaujoka_1ti_text_reg/src/branch/master/manifest.json
https://git.door43.org/plateaumalagasy/plt_phm_text_ulb_L1/src/branch/master/manifest.json
https://git.door43.org/morisniknam/fa_1pe_text_ulb/src/branch/master/manifest.json
https://git.door43.org/Zeljka/hr_mat_tn/src/branch/master/manifest.json

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

---

*[__tests__/ProjectValidationActions.test.js, line 34 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561#-LEm896O59nc15l9zKVg:-LEoLaf1AobwcVWz9Ae-:b-jbh3fh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5c566cfa4eb1bebf4870bd219c83cb0e74d9115/__tests__/ProjectValidationActions.test.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

are you sure you want to replace id with slug?
isn't it better to just add slug in addition to id?
this could bring so many issues a lot of the codebase relies on the key being id



anyway, why even change it to id?

based on recent ts-desktop projects that i found on git.door43.org slug isn't used as a key inside the resource object in the manifest

examples:

https://git.door43.org/VGM/vi_ezk_tq/src/branch/master/manifest.json
https://git.door43.org/VGM/vi_psa_tq/src/branch/master/manifest.json
https://git.door43.org/fubuffalo/zh_exo_tq/src/branch/master/manifest.json
https://git.door43.org/dayakjokak/xdy-x-randaujoka_1ti_text_reg/src/branch/master/manifest.json
https://git.door43.org/plateaumalagasy/plt_phm_text_ulb_L1/src/branch/master/manifest.json
https://git.door43.org/morisniknam/fa_1pe_text_ulb/src/branch/master/manifest.json
https://git.door43.org/Zeljka/hr_mat_tn/src/branch/master/manifest.json




</blockquote></details>


Well this is a mess, the spec uses resource.slug: https://resource-container.readthedocs.io/en/v0.1/manifest.html

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (28baa15)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-28baa15.zip) is ready for download.
[macOS build 0.10.0 (28baa15)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-28baa15.dmg) is ready for download.
[Windows x64 build 0.10.0 (28baa15)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-28baa15.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (28baa15)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-28baa15.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Review status: 13 of 23 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

---

*[__tests__/ProjectValidationActions.test.js, line 34 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561#-LEm896O59nc15l9zKVg:-LEpD4or15NbbqARLNbw:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c5c566cfa4eb1bebf4870bd219c83cb0e74d9115/__tests__/ProjectValidationActions.test.js#L34)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Well this is a mess, the spec uses resource.slug: https://resource-container.readthedocs.io/en/v0.1/manifest.html
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561)*

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4561)*

**Comment by mannycolon** [comment]
After nicknaming this project the manifest nickname in project and resource fields doesnt match up.

```js
"project": {
    "id": "tit",
    "name": "Titus",
    "resourceId": "ulb",
    "nickname": "english_tit"
  },
  "resource": {
    "id": "ulb",
    "name": "nickname 123"
  }
```

**Pull request merged**
