### PR TITLE
Proposed changes for Home screen to work.

### PR DESCRIPTION
**Pull request by klappy**
Changes to the actions/reducers/containers/components to start the home screen.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1923)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/containers/home/MainContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923#-KnAFmfJZAkK565o4Wwg:-KnAFmfJZAkK565o4Wwh:b-8bm6ae) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ba6c55354d8e48c2451b3cd8756b64caa3f32adf/src/js/containers/home/MainContainer.js#L3)):*
> ```JavaScript
> import React, { Component } from 'react';
> import { connect } from 'react-redux';
> import { Grid, Row, Col } from 'react-bootstrap';
> ```

i thought we would start using flexbox when we started implementing the home screen

---

*[src/js/containers/home/MainContainer.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923#-KnAG1CQ_Uxy2tpu-ryR:-KnAG1CRbR_yxg4Q6U3l:bg8jqz6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ba6c55354d8e48c2451b3cd8756b64caa3f32adf/src/js/containers/home/MainContainer.js#L19)):*
> ```JavaScript
>     return (
>       <Grid>
>         <Row>
> ```

the steeper uses flexbox it cant go inside the grid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923#-KnAFmfJZAkK565o4Wwg:-KnAGae_x7gGY6Zklo9V:bmtl5l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ba6c55354d8e48c2451b3cd8756b64caa3f32adf/src/js/containers/home/MainContainer.js#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i thought we would start using flexbox when we started implementing the home screen
</blockquote></details>

I was only doing a dummy layout, flexbox is still the plan

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923#-KnAG1CQ_Uxy2tpu-ryR:-KnAGkhyuP32MuBCoL-f:b74d4u8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ba6c55354d8e48c2451b3cd8756b64caa3f32adf/src/js/containers/home/MainContainer.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

the steeper uses flexbox it cant go inside the grid
</blockquote></details>

That's cool. We can go ahead and move to full flexbox. It's quicker for me to mockup with Grid first. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923)*

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1923)*

**Pull request merged**
