### PR TITLE
Refactor of Upload

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/429)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 7 of 12 files at r1.
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/OnlineInput.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_Ago8MeZOIUiCMj7xY:-K_Ago8MeZOIUiCMj7xZ:bosio5j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L16)):*
> ```JavaScript
>     this.searchValue = "";
>   }
>   handleChange(e) {
> ```

This function should be passed down as a prop

---

*[src/js/components/core/OnlineInput.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_AgrqKgn-iAjPlzpRn:-K_AgrqKgn-iAjPlzpRo:bosio5j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L21)):*
> ```JavaScript
>   }
> 
>   submitViaEnter(e) {
> ```

This function should be passed down as a prop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429)*

**Comment by RoyalSix** [comment]
Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/core/OnlineInput.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_AivqIWrrHQ_qkZrGx:-K_AivqJnuA2GnpbaT5i:bi80r2o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L14)):*
> ```JavaScript
>   constructor() {
>     super();
>     this.searchValue = "";
> ```

this.searchValue should be passed down as a prop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429)*

**Comment by RoyalSix** [comment]
This PR says upload refactor, does that include the components it is directly interacting with? If not then 

---

Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-:-K_AjOWnlXu9vyZAbWFU:bkscw2s)*

**Comment by RoyalSix** [comment]
This is good to go

---

Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-:-K_AlqzMw_ynFNeXw_te:b-ekwi59)*

**Comment by ihoegen** [comment]
@RoyalSix I just fixed those suggestions, will push soon

**Comment by ihoegen** [comment]
@RoyalSix Done

**Comment by ihoegen** [comment]
@RoyalSix This last push should completely convert the code

**Comment by RoyalSix** [comment]
Reviewed 1 of 12 files at r1, 1 of 2 files at r2, 5 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/core/OnlineInput.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_AivqIWrrHQ_qkZrGx:-K_RV422ct7JMzkE9tHZ:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L14)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

this.searchValue should be passed down as a prop
</blockquote></details>

OK

---

*[src/js/components/core/OnlineInput.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_Ago8MeZOIUiCMj7xY:-K_RV-Cy4P1ePtzdBsa8:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L16)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This function should be passed down as a prop
</blockquote></details>

OK

---

*[src/js/components/core/OnlineInput.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429#-K_AgrqKgn-iAjPlzpRn:-K_RV4Z7lA5hhWNjHhzw:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4e2abc990e05d9b959854d531bd4a45b4f1afe2/src/js/components/core/OnlineInput.js#L21)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This function should be passed down as a prop
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/429)*

**Pull request merged**
