### PR TITLE
Added tN to static resources folder & fixed bug with copying missing resources to user path

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-  Before opening tC delete the en folder from your resources folder
- Open tC and after it opens tN should be in the en translationHelps folder
- now delete `en`, `hi` and `grc` and refresh tc and all the files should be back in the resources folder.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5834)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4b4cdb6)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-linux-x64-1.2.0-4b4cdb6.deb) is ready for download.
[macOS build 1.2.0 (4b4cdb6)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-macos-x64-1.2.0-4b4cdb6.dmg) is ready for download.
[Windows x64 build 1.2.0 (4b4cdb6)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-win-x64-1.2.0-4b4cdb6.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4b4cdb6)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-win-x32-1.2.0-4b4cdb6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0cc9277)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-linux-x64-1.2.0-0cc9277.deb) is ready for download.
[macOS build 1.2.0 (0cc9277)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-macos-x64-1.2.0-0cc9277.dmg) is ready for download.
[Windows x64 build 1.2.0 (0cc9277)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-win-x64-1.2.0-0cc9277.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0cc9277)](https://tc-builds.door43.org/build/feature-mannycolon-5758/translationCore-win-x32-1.2.0-0cc9277.setup.exe) is ready for download.

**Review by PhotoNomad0 — COMMENTED** [review]
It looks good, but maybe the TN resources should be zipped - 1900+ new files.

**Comment by PhotoNomad0** [comment]
LGTM - testing
But
- builds are huge (Mac 514MB)

**Review by PhotoNomad0 — APPROVED** [review]

**Comment by mannycolon** [comment]
Tested on 4b9f116 (v1.2.0)

**Pull request merged**
