### PR TITLE
Fixed Target translation not displayed in scripture pane or in Select area

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Bug where text would not render when switching tools within the same project

#### How to test this pull request:

- Download this project 
[ar_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1027801/ar_eph_text_ulb.zip)
- Delete the .apps folder
- Open the project and try switching tools within the same project. and make sure that the text in the scripture pane and Select area is rendered for both tools.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1671)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1671)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1671)*

**Comment by klappy** [comment]
This works great when switching tools, but still has the problem if I change the project but do not switch the tool. Can we add to this a way to handle that use case easily? 

In other words, if I switch from Arabic Ephesians tW to Spanish Titus tN, everything is fine because I am switching tools and this conditional logic kicks in.

If I switch from Arabic Ephesians tW to Spanish Titus tW, the bibles are overwritten because I didn't switch tools and this logic seems to only catch tool switching.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1671#-:-Kl5cQXZRnYrLupHxNbs:b7vt0s9)*

**Comment by mannycolon** [comment]
@klappy I will take a look at that additional use case.

**Comment by RoyalSix** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1671)*

**Comment by mannycolon** [comment]
@klappy this should be ready for testing

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r3.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1671)*

**Pull request merged**
