### PR TITLE
Feature bspidel 3222a

### PR DESCRIPTION
**Pull request by bspidel**
#### This pull request addresses:

changes truncation point to be 3 more characters. Adjusts hover text to be wider and lower to fit in card.

#### How to test this pull request:
1 Start tC
2 Select a project
3 Import or view project card for: ab_jhn_reg
4 Verify that language is truncated at end of second line
5 Hover over language
6 Verify that full name is displayed and that tool tip is within Project Card

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3578)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tC_apps/ScripturePane, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578#-L1wvVV4ea_oVeoGEPJv:-L1wvVV4ea_oVeoGEPJw:b-loezsw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70d9de6662169da4813b73597649423ca54ec3a0/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit bb004e92af33707fe90575c5d31634f8872b7e55
> ```

Should not commit changes to tC_apps.

---

*[tC_apps/wordAlignment, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578#-L1wveRoTWM1m11PvNLD:-L1wveRoTWM1m11PvNLE:b-loezsw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70d9de6662169da4813b73597649423ca54ec3a0/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit a33908fdcd2d25cb7dab24e285a489a73c3987f9
> ```

Should not commit changes to tC_apps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578)*

**Comment by RoyalSix** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tC_apps/ScripturePane, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578#-L1wvVV4ea_oVeoGEPJv:-L27ElJ6FHd4epoCRDDp:b-rokoqp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70d9de6662169da4813b73597649423ca54ec3a0/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Should not commit changes to tC_apps.
</blockquote></details>

^ yes, also if you don't have changes that are going to be merged you can reset your submodules with the command from my gist https://gist.github.com/RoyalSix/f5953ebd77979002b678b50fa1b7edc9

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578)*

**Comment by mannycolon** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tC_apps/wordAlignment, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578#-L1wveRoTWM1m11PvNLD:-L2QQK83jaPBYDbxQzLm:b-cstnkg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70d9de6662169da4813b73597649423ca54ec3a0/tC_apps/wordAlignment#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Should not commit changes to tC_apps.
</blockquote></details>

I agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578)*

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3578)*

**Comment by mannycolon** [comment]
you should not connect the PR to the task but to the story

**Pull request closed without merging**
