### PR TITLE
Feature 6089/Add new font for Hebrew

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- add SIL Ezra font.
- load updated tc-ui-toolkit with tweaked font sizes for Scripture Pane.

#### Please include detailed Test instructions for your pull request:
- note that this must be merged before the WA PR https://github.com/translationCoreApps/wordAlignment/pull/184.
- note that this fixes the ScripturePane part of the tools.  In wA the font size of Hebrew words in alignment area will look too large until WA PR https://github.com/translationCoreApps/wordAlignment/pull/184 is merged in.  Also lexicon popups will be too small in alignment area.
- open an Ezra project  6:10 to make sure all characters display.  Click on second word from right and make sure all characters are rendered in lemma.  Also make sure Hebrew words are larger in lexicon popup. See circled

Screen Shot 2019-06-28 at 4 46 47 PM

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6180)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f6982b0)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-linux-x64-1.2.0-f6982b0.deb) is ready for download.
[macOS build 1.2.0 (f6982b0)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-macos-x64-1.2.0-f6982b0.dmg) is ready for download.
[Windows x64 build 1.2.0 (f6982b0)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x64-1.2.0-f6982b0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f6982b0)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x32-1.2.0-f6982b0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (af6a345)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-linux-x64-1.2.0-af6a345.deb) is ready for download.
[macOS build 1.2.0 (af6a345)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-macos-x64-1.2.0-af6a345.dmg) is ready for download.
[Windows x64 build 1.2.0 (af6a345)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x64-1.2.0-af6a345.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (af6a345)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x32-1.2.0-af6a345.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
Did you add this font to the TC-ui-toolkit? It must be added to it since its codebase is compile and it's supposed to be a standalone component

**Review by PhotoNomad0 — COMMENTED** [review]
Added.

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6180#-:-LiQTmsa6h2iqsPX2VXl:bqmjwcz)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (e963bde)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-linux-x64-1.2.0-e963bde.deb) is ready for download.
[macOS build 1.2.0 (e963bde)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-macos-x64-1.2.0-e963bde.dmg) is ready for download.
[Windows x64 build 1.2.0 (e963bde)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x64-1.2.0-e963bde.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (e963bde)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x32-1.2.0-e963bde.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (170d0a6)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-linux-x64-1.2.0-170d0a6.deb) is ready for download.
[macOS build 1.2.0 (170d0a6)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-macos-x64-1.2.0-170d0a6.dmg) is ready for download.
[Windows x64 build 1.2.0 (170d0a6)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x64-1.2.0-170d0a6.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (170d0a6)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x32-1.2.0-170d0a6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (85c929c)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-linux-x64-1.2.0-85c929c.deb) is ready for download.
[macOS build 1.2.0 (85c929c)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-macos-x64-1.2.0-85c929c.dmg) is ready for download.
[Windows x64 build 1.2.0 (85c929c)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x64-1.2.0-85c929c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (85c929c)](https://tc-builds.door43.org/build/feature-mcleanb-6089/translationCore-win-x32-1.2.0-85c929c.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
