### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5369)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ef8fc29)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-ef8fc29.deb) is ready for download.
[macOS build 1.1.0 (ef8fc29)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-ef8fc29.dmg) is ready for download.
[Windows x64 build 1.1.0 (ef8fc29)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-ef8fc29.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ef8fc29)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-ef8fc29.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fae73e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fae73e8.deb) is ready for download.
[macOS build 1.1.0 (fae73e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fae73e8.dmg) is ready for download.
[Windows x64 build 1.1.0 (fae73e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fae73e8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fae73e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fae73e8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cf59b8d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-cf59b8d.deb) is ready for download.
[macOS build 1.1.0 (cf59b8d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-cf59b8d.dmg) is ready for download.
[Windows x64 build 1.1.0 (cf59b8d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-cf59b8d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cf59b8d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-cf59b8d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9563458)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9563458.deb) is ready for download.
[macOS build 1.1.0 (9563458)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9563458.dmg) is ready for download.
[Windows x64 build 1.1.0 (9563458)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9563458.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9563458)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9563458.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8497e78)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-8497e78.deb) is ready for download.
[macOS build 1.1.0 (8497e78)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-8497e78.dmg) is ready for download.
[Windows x64 build 1.1.0 (8497e78)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-8497e78.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8497e78)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-8497e78.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3a6539a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3a6539a.deb) is ready for download.
[macOS build 1.1.0 (3a6539a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3a6539a.dmg) is ready for download.
[Windows x64 build 1.1.0 (3a6539a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3a6539a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3a6539a)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3a6539a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (251dd76)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-251dd76.deb) is ready for download.
[macOS build 1.1.0 (251dd76)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-251dd76.dmg) is ready for download.
[Windows x64 build 1.1.0 (251dd76)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-251dd76.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (251dd76)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-251dd76.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f2a7939)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-f2a7939.deb) is ready for download.
[macOS build 1.1.0 (f2a7939)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-f2a7939.dmg) is ready for download.
[Windows x64 build 1.1.0 (f2a7939)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-f2a7939.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f2a7939)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-f2a7939.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (803a19f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-803a19f.deb) is ready for download.
[macOS build 1.1.0 (803a19f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-803a19f.dmg) is ready for download.
[Windows x64 build 1.1.0 (803a19f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-803a19f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (803a19f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-803a19f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6db3f51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6db3f51.deb) is ready for download.
[macOS build 1.1.0 (6db3f51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6db3f51.dmg) is ready for download.
[Windows x64 build 1.1.0 (6db3f51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6db3f51.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6db3f51)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6db3f51.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d550032)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-d550032.deb) is ready for download.
[macOS build 1.1.0 (d550032)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-d550032.dmg) is ready for download.
[Windows x64 build 1.1.0 (d550032)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-d550032.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d550032)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-d550032.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3e8fae1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3e8fae1.deb) is ready for download.
[macOS build 1.1.0 (3e8fae1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3e8fae1.dmg) is ready for download.
[Windows x64 build 1.1.0 (3e8fae1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3e8fae1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3e8fae1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3e8fae1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3a8fbf1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-3a8fbf1.deb) is ready for download.
[macOS build 1.1.0 (3a8fbf1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-3a8fbf1.dmg) is ready for download.
[Windows x64 build 1.1.0 (3a8fbf1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-3a8fbf1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3a8fbf1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-3a8fbf1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4c340d2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-4c340d2.deb) is ready for download.
[macOS build 1.1.0 (4c340d2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-4c340d2.dmg) is ready for download.
[Windows x64 build 1.1.0 (4c340d2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-4c340d2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4c340d2)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-4c340d2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fc9f890)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fc9f890.deb) is ready for download.
[macOS build 1.1.0 (fc9f890)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fc9f890.dmg) is ready for download.
[Windows x64 build 1.1.0 (fc9f890)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fc9f890.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fc9f890)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fc9f890.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a0b6cd9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-a0b6cd9.deb) is ready for download.
[macOS build 1.1.0 (a0b6cd9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-a0b6cd9.dmg) is ready for download.
[Windows x64 build 1.1.0 (a0b6cd9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-a0b6cd9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a0b6cd9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-a0b6cd9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f24c8e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-f24c8e8.deb) is ready for download.
[macOS build 1.1.0 (f24c8e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-f24c8e8.dmg) is ready for download.
[Windows x64 build 1.1.0 (f24c8e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-f24c8e8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f24c8e8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-f24c8e8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6a12932)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6a12932.deb) is ready for download.
[macOS build 1.1.0 (6a12932)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6a12932.dmg) is ready for download.
[Windows x64 build 1.1.0 (6a12932)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6a12932.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6a12932)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6a12932.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (703574f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-703574f.deb) is ready for download.
[macOS build 1.1.0 (703574f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-703574f.dmg) is ready for download.
[Windows x64 build 1.1.0 (703574f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-703574f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (703574f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-703574f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b7d5a3f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b7d5a3f.deb) is ready for download.
[macOS build 1.1.0 (b7d5a3f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b7d5a3f.dmg) is ready for download.
[Windows x64 build 1.1.0 (b7d5a3f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b7d5a3f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b7d5a3f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b7d5a3f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6a742d4.deb) is ready for download.
[macOS build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6a742d4.dmg) is ready for download.
[Windows x64 build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6a742d4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6a742d4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6a742d4.deb) is ready for download.
[macOS build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6a742d4.dmg) is ready for download.
[Windows x64 build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6a742d4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6a742d4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6a742d4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e7f2c15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e7f2c15.deb) is ready for download.
[macOS build 1.1.0 (e7f2c15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e7f2c15.dmg) is ready for download.
[Windows x64 build 1.1.0 (e7f2c15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e7f2c15.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e7f2c15)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e7f2c15.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e4c5012)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e4c5012.deb) is ready for download.
[macOS build 1.1.0 (e4c5012)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e4c5012.dmg) is ready for download.
[Windows x64 build 1.1.0 (e4c5012)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e4c5012.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e4c5012)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e4c5012.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (55a13ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-55a13ea.deb) is ready for download.
[macOS build 1.1.0 (55a13ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-55a13ea.dmg) is ready for download.
[Windows x64 build 1.1.0 (55a13ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-55a13ea.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (55a13ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-55a13ea.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8c852b9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-8c852b9.deb) is ready for download.
[macOS build 1.1.0 (8c852b9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-8c852b9.dmg) is ready for download.
[Windows x64 build 1.1.0 (8c852b9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-8c852b9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8c852b9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-8c852b9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8bdfe88)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-8bdfe88.deb) is ready for download.
[macOS build 1.1.0 (8bdfe88)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-8bdfe88.dmg) is ready for download.
[Windows x64 build 1.1.0 (8bdfe88)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-8bdfe88.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8bdfe88)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-8bdfe88.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (95df347)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-95df347.deb) is ready for download.
[macOS build 1.1.0 (95df347)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-95df347.dmg) is ready for download.
[Windows x64 build 1.1.0 (95df347)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-95df347.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (95df347)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-95df347.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (76f7cc9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-76f7cc9.deb) is ready for download.
[macOS build 1.1.0 (76f7cc9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-76f7cc9.dmg) is ready for download.
[Windows x64 build 1.1.0 (76f7cc9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-76f7cc9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (76f7cc9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-76f7cc9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9a83bc4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9a83bc4.deb) is ready for download.
[macOS build 1.1.0 (9a83bc4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9a83bc4.dmg) is ready for download.
[Windows x64 build 1.1.0 (9a83bc4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9a83bc4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9a83bc4)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9a83bc4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fee6f10)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fee6f10.deb) is ready for download.
[macOS build 1.1.0 (fee6f10)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fee6f10.dmg) is ready for download.
[Windows x64 build 1.1.0 (fee6f10)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fee6f10.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fee6f10)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fee6f10.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (50db09c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-50db09c.deb) is ready for download.
[macOS build 1.1.0 (50db09c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-50db09c.dmg) is ready for download.
[Windows x64 build 1.1.0 (50db09c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-50db09c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (50db09c)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-50db09c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e40f27d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-e40f27d.deb) is ready for download.
[macOS build 1.1.0 (e40f27d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-e40f27d.dmg) is ready for download.
[Windows x64 build 1.1.0 (e40f27d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-e40f27d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e40f27d)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-e40f27d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (516cceb)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-516cceb.deb) is ready for download.
[macOS build 1.1.0 (516cceb)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-516cceb.dmg) is ready for download.
[Windows x64 build 1.1.0 (516cceb)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-516cceb.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (516cceb)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-516cceb.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (92b2595)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-92b2595.deb) is ready for download.
[macOS build 1.1.0 (92b2595)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-92b2595.dmg) is ready for download.
[Windows x64 build 1.1.0 (92b2595)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-92b2595.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (92b2595)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-92b2595.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4543864)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-4543864.deb) is ready for download.
[macOS build 1.1.0 (4543864)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-4543864.dmg) is ready for download.
[Windows x64 build 1.1.0 (4543864)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-4543864.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4543864)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-4543864.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5369#-:-LQfcOVhERgXDSIuHFNh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (710f989)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-710f989.deb) is ready for download.
[macOS build 1.1.0 (710f989)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-710f989.dmg) is ready for download.
[Windows x64 build 1.1.0 (710f989)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-710f989.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (710f989)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-710f989.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c69d1a6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-c69d1a6.deb) is ready for download.
[macOS build 1.1.0 (c69d1a6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-c69d1a6.dmg) is ready for download.
[Windows x64 build 1.1.0 (c69d1a6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-c69d1a6.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c69d1a6)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-c69d1a6.setup.exe) is ready for download.

**Pull request merged**
