### PR TITLE
Removed unnecessary submodules from tC repo

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Pull enhancement-mannycolon-4605
- Make sure that both tools (tW & wA ) open correctly 
- **Dependencies**
   - https://github.com/translationCoreApps/translationWords/pull/133
   -  https://github.com/translationCoreApps/wordAlignment/pull/42 
#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4606)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (238d632)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-238d632.zip) is ready for download.
[macOS build 0.10.0 (238d632)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-238d632.dmg) is ready for download.
[Windows x64 build 0.10.0 (238d632)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-238d632.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (238d632)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-238d632.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4606)*

**Comment by PhotoNomad0** [comment]
@mannycolon - is this related to this PR?  Testing with windows build above.

error

**Comment by mannycolon** [comment]
@PhotoNomad0 How do you recreate that issue?

**Comment by PhotoNomad0** [comment]
@mannycolon - OK - see the errors on both the windows and mac builds.  Also see the same errors if I delete the removed tc_apps folders before I do npm start.  But the app seems to work alright.

**Comment by mannycolon** [comment]
@PhotoNomad0 It should be fixed now

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (b51c768)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-b51c768.zip) is ready for download.
Some builds failed

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r2.
Review status: 7 of 8 files reviewed, all discussions resolved (waiting on @PhotoNomad0 and @RoyalSix)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4606)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4606#-:-LEsr7eN4rkoJGtpup4I:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
@mannycolon - I would merge this, but concerned that concourse build is failing, and Travis builds are no longer happening.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (b51c768)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-b51c768.zip) is ready for download.
[macOS build 0.10.0 (b51c768)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-b51c768.dmg) is ready for download.
[Windows x64 build 0.10.0 (b51c768)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-b51c768.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (b51c768)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-b51c768.setup.exe) is ready for download.

**Pull request merged**
