### PR TITLE
Bugfix #3486/wA Tool crashes on missing alignment data for verse.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: unfoldingWord-dev/translationCore#3486

#### How to test this pull request:

Needs to be tested with: https://github.com/translationCoreApps/word-alignment-tool/pull/14

Import usfm file contained in issue.  Then open word alignment tool to 1:81 - should not see crash.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3492)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/containers/GroupMenuContainer.js, line 109 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1INpg1I5Zg2-ZBaG4M:-L1INpg1I5Zg2-ZBaG4N:b-rjwa2p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2be139f61401a92de5fa055026e23bec6c8aa620/src/js/containers/GroupMenuContainer.js#L109)):*
> ```JavaScript
>     const { chapter, verse } = contextId.reference;
>     const { alignmentData } = this.props.wordAlignmentReducer;
>     console.log("getStatusGlyph verse " + chapter + ":" + verse);
> ```

remove console log everything else looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/containers/GroupMenuContainer.js, line 109 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1INpg1I5Zg2-ZBaG4M:-L1J0Ip0AFRD3PTJma-P:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2be139f61401a92de5fa055026e23bec6c8aa620/src/js/containers/GroupMenuContainer.js#L109)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove console log everything else looks good
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-:-L1JbHoLOeGydSUdpE6u:bnfp4nl)*

**Comment by klappy** [comment]
@photonomad0: Do we just need to confirm that the broken project loads the alignment tool properly?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-:-L1Jg90gz7s_R6k3ac0A:b-7aonl5)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by mannycolon** [comment]
@PhotoNomad0 For some reason this changes are breaking tW

**Comment by klappy** [comment]
@mannycolon: tW is working for me with both of the related PRs checked out.

**Comment by mannycolon** [comment]
@klappy what project are you testing with?

**Comment by mannycolon** [comment]
@klappy try with [43-LUK.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1580048/43-LUK.usfm.zip)

**Comment by klappy** [comment]
*[src/js/containers/GroupMenuContainer.js, line 110 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1JoUvghZJlgvNPGHZf:-L1JoUvghZJlgvNPGHZg:bim024e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/df3ed8b0494181e9c068cfc81d1763cd650d1c35/src/js/containers/GroupMenuContainer.js#L110)):*
> ```JavaScript
>     const { chapter, verse } = contextId.reference;
>     const { alignmentData } = this.props.wordAlignmentReducer;
>     const wordBank = alignmentData && alignmentData[chapter] && alignmentData[chapter][verse] ? alignmentData[chapter][verse].wordBank : null;
> ```

I'm wondering if we need to return [] instead of null. The wordBank is an array, and maybe that's causing issues elsewhere. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by klappy** [comment]
*[src/js/containers/GroupMenuContainer.js, line 110 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1JoUvghZJlgvNPGHZf:-L1JsxOdKPIg-DsIvUE1:b-e1xjzj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/df3ed8b0494181e9c068cfc81d1763cd650d1c35/src/js/containers/GroupMenuContainer.js#L110)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm wondering if we need to return [] instead of null. The wordBank is an array, and maybe that's causing issues elsewhere. 
</blockquote></details>

I can confirm that this addresses the tW issue. @photonomad0: Can you update the PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by PhotoNomad0** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/containers/GroupMenuContainer.js, line 110 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1JoUvghZJlgvNPGHZf:-L1K16HMfOhHIma9NYMW:bk82k0w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/df3ed8b0494181e9c068cfc81d1763cd650d1c35/src/js/containers/GroupMenuContainer.js#L110)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I can confirm that this addresses the tW issue. @photonomad0: Can you update the PR?
</blockquote></details>

Thanks for finding that goof on my part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by klappy** [comment]
*[src/js/containers/GroupMenuContainer.js, line 110 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-L1JoUvghZJlgvNPGHZf:-L1K4CHLWXrEcyAmydb5:b-5gxixv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/df3ed8b0494181e9c068cfc81d1763cd650d1c35/src/js/containers/GroupMenuContainer.js#L110)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Thanks for finding that goof on my part.
</blockquote></details>

Np! It happens :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-:-L1K4KbVllcXHdFnToF-:bnfp4nl)*

**Comment by klappy** [comment]
@mannycolon: Can you confirm that this addresses the issues on your local?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492#-:-L1K4MS9DVKwE3_pF9Z6:b-gbu9h8)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3492)*

**Pull request merged**
