### PR TITLE
Zipped translationHelps & lexicon files in tC static resources

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Zipped translationHelps & lexicon files in tC static resources
- Added code to unzip such files
- Added code to speed up tC startup time
- Build size reduced from `429.6MB`  to `392.3MB`

#### Please include detailed Test instructions for your pull request:
- Delete your user `translationCore` folder
- Verify it takes between `28sec - 1min` to open tC compare to `6min - 11min`  on current develop branch (This numbers may vary based on your machines specs)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5894)

### CODE REVIEW

**Comment by mannycolon** [comment]
Still working on unit tests

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (54ec4d7)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-linux-x64-1.2.0-54ec4d7.deb) is ready for download.
[macOS build 1.2.0 (54ec4d7)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-macos-x64-1.2.0-54ec4d7.dmg) is ready for download.
[Windows x64 build 1.2.0 (54ec4d7)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x64-1.2.0-54ec4d7.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (54ec4d7)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x32-1.2.0-54ec4d7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f1466c5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-linux-x64-1.2.0-f1466c5.deb) is ready for download.
[macOS build 1.2.0 (f1466c5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-macos-x64-1.2.0-f1466c5.dmg) is ready for download.
[Windows x64 build 1.2.0 (f1466c5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x64-1.2.0-f1466c5.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f1466c5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x32-1.2.0-f1466c5.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (29178b5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-linux-x64-1.2.0-29178b5.deb) is ready for download.
[macOS build 1.2.0 (29178b5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-macos-x64-1.2.0-29178b5.dmg) is ready for download.
[Windows x64 build 1.2.0 (29178b5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x64-1.2.0-29178b5.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (29178b5)](https://tc-builds.door43.org/build/enhancement-mannycolon-5846/translationCore-win-x32-1.2.0-29178b5.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
LGTM

**Comment by PhotoNomad0** [comment]
Nuts - having internet issues.  Will take 45 minutes to download...

**Comment by PhotoNomad0** [comment]
LGTM - testing - wow, fast @mannycolon

**Pull request merged**
