### PR TITLE
Verse Edit

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request implements the verse edit feature. 

#### How to test this pull request:

Set the verse check branch to the branch of the same name. Use the edit feature in verse check, and look at the files that match as well.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1062)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/VerseEditActions.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSXTFBTN8tlNEhI7XP:-KhSXTFCfeJHlP9RCQWc:b-2a3q39) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L14)):*
> ```JavaScript
>  * @return {object} New state for verse Edit reducer.
>  */
> export const addVerseEdit = (before, after, tags, userName, context, saveLocation) => {
> ```

you dont need to pass context and savelocation as a parameter. you can get it directly from getState()

---

*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhSYOP0ZzzEjhULK8cf:b-yz57hr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
> ```JavaScript
> export const addVerseEdit = (before, after, tags, userName, context, saveLocation) => {
>   let chapter = context.reference.chapter; 
>   let verse = context.reference.verse;
> ```

how about you extract all the new code you added to its own function??

---

*[src/js/containers/ToolsContainer.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYDrItMd4ow192CLt:-KhSYDrItMd4ow192CLu:bf20w85) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/containers/ToolsContainer.js#L91)):*
> ```JavaScript
>         dispatch(toggleReminder(userName));
>       },
>       addVerseEdit: (before, after, tags, userName, contextId, saveLocation) => {
> ```

we dont need all of these parameters.

---

*[src/js/reducers/verseEditReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYZy-KD_Jw3s0YdTW:-KhSYZy-KD_Jw3s0YdTX:b-rz92v3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/reducers/verseEditReducer.js#L21)):*
> ```JavaScript
>         modifiedTimestamp: action.modifiedTimestamp,
>         context: action.context,
>         saveLocation: action.saveLocation
> ```

why are we saving the save location and context here???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhTiteIDqRHONQs-Cnu:b-nv8gh2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how about you extract all the new code you added to its own function??
</blockquote></details>

I would imagine that we would create a method called something like `editTargetVerseSource(contextId, verseEdit)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhTjHc8cqQXHVy3uDJq:bck5uho) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I would imagine that we would create a method called something like `editTargetVerseSource(contextId, verseEdit)`
</blockquote></details>

That way we could eventually make a switch in that method to call two different methods one for usfm and one for D43. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhTkfTXdwyHu5j0wptI:bcbgnk2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

That way we could eventually make a switch in that method to call two different methods one for usfm and one for D43. 
</blockquote></details>

Would this be something that's a Util?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhTsGH6E9L68g_nHQzC:bz2vw16) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Would this be something that's a Util?
</blockquote></details>

I could see it going either way but right now it makes sense as a VerseEditAction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhTsRP9Mo2coTpR-6oK:b-kk5pze) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I could see it going either way but right now it makes sense as a VerseEditAction.
</blockquote></details>

Long term, USFM/tS Project editing methods may need to go to Utils folder and 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/reducers/verseEditReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYZy-KD_Jw3s0YdTW:-KhUFp7iPLt7ENwWP1Fj:bh5va2s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/reducers/verseEditReducer.js#L21)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are we saving the save location and context here???
</blockquote></details>

@ihoegen: context should be contextId, and it should also be left out of this as it is only needed when stored, also saveLocation should be generated only when it is reading/writing to the fs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/containers/ToolsContainer.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYDrItMd4ow192CLt:-KhUGVKh5zhZiz8cAnJ0:bv944lr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/containers/ToolsContainer.js#L91)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont need all of these parameters.
</blockquote></details>

see my notes below in verseEditReducer.js...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/actions/VerseEditActions.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSXTFBTN8tlNEhI7XP:-KhUGeBw4E3eGmcdOJGS:b-u1294m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you dont need to pass context and savelocation as a parameter. you can get it directly from getState()
</blockquote></details>

You can reference one of the other actions files to borrow how dispatch and getState() is brought in and usable. I had to do a few times to realize I didn't need to pass as much around and just look it up from the assigned `let state = getState()`...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by EllDoubleYew** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhYOV6TvA-CWIrpvLoI:btguejc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Long term, USFM/tS Project editing methods may need to go to Utils folder and 
</blockquote></details>

I think its okay to live as an action. But I am no expert :sweat_smile: 

---

*[src/js/actions/VerseEditActions.js, line 26 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYPCuneM_zI5SrFxym:-KhYPCuneM_zI5SrFxyn:bx8znip) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L26)):*
> ```JavaScript
>     let chunk = contents[i];
>     let numChunk = parseInt(chunk.split('.txt')[0]);
>     if ((numChunk <= verse && contents[i+1] === undefined) || (numChunk <= verse && parseInt(contents[i+1].split('.txt')[0]) > verse)) {
> ```

Redundant logic. Use numChunk <= verse && (contents[i+1] === undefined || parseInt(contents[i+1].split('.txt')[0]) > verse)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by ihoegen** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/VerseEditActions.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSXTFBTN8tlNEhI7XP:-KhYs_EXWwnkpTUMQ7oD:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L14)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

You can reference one of the other actions files to borrow how dispatch and getState() is brought in and usable. I had to do a few times to realize I didn't need to pass as much around and just look it up from the assigned `let state = getState()`...
</blockquote></details>

Done.

---

*[src/js/actions/VerseEditActions.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYOP0ZzzEjhULK8ce:-KhYsaLWg3o3zactOEGV:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L16)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

I think its okay to live as an action. But I am no expert :sweat_smile: 
</blockquote></details>

Done.

---

*[src/js/actions/VerseEditActions.js, line 26 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYPCuneM_zI5SrFxym:-KhYt8yQoaGA7UpmTAQG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/actions/VerseEditActions.js#L26)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Redundant logic. Use numChunk <= verse && (contents[i+1] === undefined || parseInt(contents[i+1].split('.txt')[0]) > verse)
</blockquote></details>

Done.

---

*[src/js/containers/ToolsContainer.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYDrItMd4ow192CLt:-KhYtA33m1RzDATNOGw5:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/containers/ToolsContainer.js#L91)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

see my notes below in verseEditReducer.js...
</blockquote></details>

Done.

---

*[src/js/reducers/verseEditReducer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhSYZy-KD_Jw3s0YdTW:-KhYtBPBmgIjJ-Ualm1N:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/25ee4b4b12d6823786c368229aa560c2f1d8d43e/src/js/reducers/verseEditReducer.js#L21)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@ihoegen: context should be contextId, and it should also be left out of this as it is only needed when stored, also saveLocation should be generated only when it is reading/writing to the fs. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by ihoegen** [comment]
@mannycolon @EllDoubleYew @klappy All changes have been applied

**Comment by klappy** [comment]
*[src/js/containers/ToolsContainer.js, line 91 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYzXZ_v8-4JFlHJBx1:-KhYzXZ_v8-4JFlHJBx2:b4wa8k0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6608b319022fd9d4d586d555daeca45af8eefb2a/src/js/containers/ToolsContainer.js#L91)):*
> ```JavaScript
>         dispatch(toggleReminder(userName));
>       },
>       addVerseEdit: (before, after, tags, userName, contextId, saveLocation) => {
> ```

Looks like we need to remove the last two params since they were removed from the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by klappy** [comment]
*[src/js/containers/ToolsContainer.js, line 92 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYzdmqQiTr7-xYW2Ri:-KhYzdmqQiTr7-xYW2Rj:b-r4e3fr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6608b319022fd9d4d586d555daeca45af8eefb2a/src/js/containers/ToolsContainer.js#L92)):*
> ```JavaScript
>       },
>       addVerseEdit: (before, after, tags, userName, contextId, saveLocation) => {
>         dispatch(addVerseEdit(before, after, tags, userName, contextId, saveLocation));
> ```

remove them from here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by ihoegen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/containers/ToolsContainer.js, line 91 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYzXZ_v8-4JFlHJBx1:-KhZakN3aVL1EbDK4vnC:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6608b319022fd9d4d586d555daeca45af8eefb2a/src/js/containers/ToolsContainer.js#L91)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Looks like we need to remove the last two params since they were removed from the function.
</blockquote></details>

Done.

---

*[src/js/containers/ToolsContainer.js, line 92 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062#-KhYzdmqQiTr7-xYW2Ri:-KhZahiME4oZEniFMw7n:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6608b319022fd9d4d586d555daeca45af8eefb2a/src/js/containers/ToolsContainer.js#L92)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

remove them from here as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1062)*

**Comment by ihoegen** [comment]
@klappy Just removed the extra parameters

**Pull request merged**
