### PR TITLE
Bugfix/joel/taggedreleases

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

@klappy this fixes the builds not being deployed to github. It was a configuration issue with travis that took some time to figure out and some additional pre-processing to fix.

#### How to test this pull request:

Now when you create and push a tag up to github the builds will be successfully deployed to github (assuming all the tests pass).

> Note: you still need to manually generate and upload the compressed dmg.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3619)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@neutrinog How do I test this if its not merged?

**Comment by da1nerd** [comment]
@RoyalSix

1. pull down this branch
2. create a new branch off of this one for the test.
3. change the version in package.json to something like `0.8.9999` and commit to your test branch
4. create a tag named `v0.8.9999` then push it and the temporary branch up to this repo.
5. once the build is done on [travis](https://travis-ci.org/unfoldingWord-dev/translationCore/builds) confirm the binaries have been uploaded to the [release page](https://github.com/unfoldingWord-dev/translationCore/releases) under your tag.
6. delete the tag and the temporary branch from this repo once you've confirmed.

**Comment by RoyalSix** [comment]
@neutrinog Ok, what is the process to make the tag and push?
```git tag v0.8.9999```
```git push```
?

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3619)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3619#-:-L2MVGExmd-CMEUnOUq_:bnfp4nl)*

**Comment by klappy** [comment]
Do we have a way to test this outside of creating a tag on this branch?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3619#-:-L2MVIuhFmD-qKIXH-oA:b-cox9ud)*

**Comment by da1nerd** [comment]
@RoyalSix 

```bash
git tag v0.8.999
git push upstream --tags
```

@klappy no, the only way to test it is by creating a tag. I've already done so to test myself. Tags can be easily deleted.

**Comment by klappy** [comment]
@neutrinog: Sounds good! 
@RoyalSix, I'll create a random tag v0.8.777 and watch that one through if you want to try one as well.

**Comment by klappy** [comment]
Looks like I forgot to change the package.json version number to match. Doh!

**Comment by klappy** [comment]
All looks good to be merged from what I can tell: 
https://github.com/unfoldingWord-dev/translationCore/releases/tag/untagged-fe58f030e9645426448f

I'll leave that link active until we merge.

**Comment by RoyalSix** [comment]
@klappy nice!
@neutrinog Does it matter that those three tests failed?

**Comment by da1nerd** [comment]
@RoyalSix no. travis for some reason associated one of my old test tags with this PR (never seen that happen before). All my tagging tests must have broken travis!
And coverage did not increase because this didn't touch the code.

I'm not sure why appveyor tests are now running. We are not using appveyor anymore.

**Comment by da1nerd** [comment]
Link to @klappy 's test build (success) https://travis-ci.org/unfoldingWord-dev/translationCore/builds/326564787

**Pull request merged**
