### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
Basically you need to pull all the submodules besides tC_resources, remove the old node_modules, checkout my branch ```feature-jay-3594``` run npm install and check all subcomponent functionality

I made a script to make the process easier assuming that you have no work thats not already saved on your submodule branches.

**Testing all modules**
```npm run test-all feature-jay-3594```

**Submodule PR's**
https://github.com/translationCoreApps/translationWords/pull/106
https://github.com/translationCoreApps/ScripturePane/pull/83
https://github.com/translationCoreApps/VerseCheck/pull/87
https://github.com/translationCoreApps/translationNotes/pull/82
https://github.com/translationCoreApps/translationHelps/pull/49
https://github.com/translationCoreApps/word-alignment-tool/pull/17

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3650)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/StatusBarContainer.test.js, line 30 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650#-L2zV6mxgBO71m5jzO8N:-L2zV6mxgBO71m5jzO8O:b-9f3elk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6dfca4e240f6553a025e22857385983d2b49d590/__tests__/StatusBarContainer.test.js#L30)):*
> ```JavaScript
>   });
> 
>   test('StatusBarContainer Component on current system should render button text correctly', () => {
> ```

we dont need this tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by mannycolon** [comment]
Reviewed 2 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 6 of 9 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650#-:-L387USdYV8-W-R0usS4:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - Program runs well, but in testing I see a warning when I open word alignment.  Probably doesn't need to be addressed now, but we should come back to it soon.

`
/Users/blm/Development/Electron/testDir/translationCore/node_modules/fbjs/lib/warning.js:33 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
    in BottomWordCard
    in DragSource(BottomWordCard)
    in div
    in div
    in div
    in div
    in DropBoxItem
    in DropTarget(DropBoxItem)
    in div
    in div
    in DropBoxArea
    in div
    in div
    in Container
    in DragDropContext(Container) (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
`

**Comment by PhotoNomad0** [comment]
@RoyalSix - tested on Windows - looking good.

**Comment by mannycolon** [comment]
Reviewed 1 of 5 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test.sh, line 1 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650#-L3UL-o3-ZwcIGNKqt8J:-L3UL-o3-ZwcIGNKqt8K:b-4qdckk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d7c5698ff6b55cb5f7648795ab9d0689326b9dc/test.sh#L1)):*
> ```Shell
> git_res=$(git checkout feature-jay-3594); if [[ $git_res != *"error"* ]]; then git pull; fi;
> ```

do we need this file to be in tC repo?
I say it because i see you have feature-jay-3594 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by RoyalSix** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[test.sh, line 1 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650#-L3UL-o3-ZwcIGNKqt8J:-L3UM2nEJzKv8GNJEk_P:b-xg1b7w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1d7c5698ff6b55cb5f7648795ab9d0689326b9dc/test.sh#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need this file to be in tC repo?
I say it because i see you have feature-jay-3594 
</blockquote></details>

No. I deleted. Nice catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by mannycolon** [comment]
Reviewed 1 of 5 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 5 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3650#-:-L3ZM39NlkJ0uYFaMF1p:bnfp4nl)*

**Pull request merged**
