### PR TITLE
Non-Developer Mode Project Restrictions

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR blocks a user from loading projects other than Ephesians and Titus unless in developer mode.
Issue #769 

#### How to test this pull request:
Try loading projects of different books, in and out of developer mode.
Try to load some from local, online, user git repo projects etc.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/866)

### CODE REVIEW

**Comment by ihoegen** [comment]
@RoyalSix One feature we currently have is that you can load a USFM file just by choosing it's directory, and I get the following: 
image

**Comment by ihoegen** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/RecentProjectsActions.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV3SiHDvxm9REP_vj:-KebV3SiHDvxm9REP_vk:bhemu5u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/actions/RecentProjectsActions.js#L40)):*
> ```JavaScript
> module.exports.startLoadingNewProject = function (lastCheckModule) {
>     return ((dispatch, getState) => {
>         if (Upload.checkIfValidBetaProject(api.getDataFromCommon('tcManifest')) || getState().settingsReducer.currentSettings.developerMode) {
> ```

There are some projects that can make it into recent projects, such as those that are a USFM file inside of a folder, or even a USFM file.

---

*[src/js/components/core/UploadMethods.js, line 94 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebUwV_lgibknFE4cEc:-KebUwVaUDP5VhhwBNkK:bfh6l14) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/components/core/UploadMethods.js#L94)):*
> ```JavaScript
> 
> function checkIfValidBetaProject(manifest) {
>   return manifest.project.id == "eph" || manifest.project.id == "tit";
> ```

Add a check for undefined manifest.project, along with undefined manifest. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by ihoegen** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KebV_21pxBHetlFYLtJ:b-1sn6vt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
> ```JavaScript
> 
> const initialState = {
>   currentSettings: fs.readJsonSync(dir),
> ```

I don't think that file is guaranteed to be there 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KebWbpfbBRwhXQmRPqg:bd7bi6h) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think that file is guaranteed to be there 
</blockquote></details>

yeah why you doing that?? what was wrong with the previous implementation ??

I initliazed the setting in componentWillMount() in app.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KebXsPD6fFnSBj6O4_o:b4s1gjt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

yeah why you doing that?? what was wrong with the previous implementation ??

i initliaze the setting in componentWillMount() in app.js
</blockquote></details>

Also, are settings still in the `packages-compiled` folder? If so, why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by RoyalSix** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/RecentProjectsActions.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV3SiHDvxm9REP_vj:-Kedk9tRWxxM0_2aHV3S:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/actions/RecentProjectsActions.js#L40)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

There are some projects that can make it into recent projects, such as those that are a USFM file inside of a folder, or even a USFM file.
</blockquote></details>

Done.

---

*[src/js/components/core/UploadMethods.js, line 94 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebUwV_lgibknFE4cEc:-KedkAteVXk6Fnt5Qt0x:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/components/core/UploadMethods.js#L94)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Add a check for undefined manifest.project, along with undefined manifest. 
</blockquote></details>

Done.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KedkC3Yns9Ah3mcBuFo:b5t36dq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Also, are settings still in the `packages-compiled` folder? If so, why?
</blockquote></details>

Settings is something that may need to be referenced even before the app is displayed. Settings is currently in the packages compiled folder not sure why haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KeeJa3athzEW6RqF5tt:b-im2x5f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Settings is something that may need to be referenced even before the app is displayed. Settings is currently in the packages compiled folder not sure why haha
</blockquote></details>

that's why it's in compoenntWillMount(). why would you need it before app.js mounts???

by doing this you're doing a step twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KeePo7azZq5Zn9zmr4v:bo8aztm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

that's why it's in compoenntWillMount(). why would you need it before app.js mounts???

by doing this you're doing a step twice.
</blockquote></details>

When the store is initialized, I'm checking for developer mode in order to allow loading of a project or not. I wouldn't put it there if it wasn't needed. If you test this branch without doing this the settings json will not have been loaded before the app trys to open the last tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KeeQn8GxkBEHWKvlRA8:bgmuuw3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

When the store is initialized, I'm checking for developer mode in order to allow loading of a project or not. I wouldn't put it there if it wasn't needed. If you test this branch without doing this the settings json will not have been loaded before the app trys to open the last tool.
</blockquote></details>

And it will allow the user to use any book that last loaded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KeeQys6FDMwXYoMS1aF:b-x65ecq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

And it will allow the user to use any book that last loaded
</blockquote></details>

Its standard practice to initialize the store with actual data rather than null, if you want I can remove one in component will mount

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
@RoyalSix could you please merge with develop

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/reducers/settingsReducer.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KebV_21pxBHetlFYLtI:-KejLjJTW12xsqFtdJwD:b-mfhtog) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b25dc2735e9ce08633b947866ab3b3e99e4b2226/src/js/reducers/settingsReducer.js#L11)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Its standard practice to initialize the store with actual data rather than null, if you want I can remove one in component will mount
</blockquote></details>

yeah just remove the one in the component will mount. but I think we need to do more research about this. I don't think we can call this implementation standard yet 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 78 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866#-KekKDtgSEJFbNarowfg:-KekKDtgSEJFbNarowfh:b1yajrp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0f7d3ef1471275958cf7e7c6e5a639f2256cc6dd/src/js/pages/app.js#L78)):*
> ```JavaScript
>     api.removeEventListener('changedCheckStatus', this.changeSubMenuItemStatus);
>   },
>   
> ```

do we need this here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/866)*

**Comment by mannycolon** [comment]
@RoyalSix the only problem now is the failing test. it seems your changes are messing with the tets.

**Comment by mannycolon** [comment]
@RoyalSix Failing tests its the only thing holding me from merging your branch

**Pull request merged**
