### PR TITLE
Added tc-tool-wrapper

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Also, review https://github.com/translationCoreApps/translationWords/pull/264 & https://github.com/translationCoreApps/translationNotes/pull/98

#### Please include detailed Test instructions for your pull request:
- `rm -rf node_modules`
- `npm i`
-  `git checkout feature-mannycolon-5837` && `git pull feature-mannycolon-5837` in both tn and tw
- `npm start` to open tC
- Both tools should open without problems

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5925)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0d09d2c)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-linux-x64-1.2.0-0d09d2c.deb) is ready for download.
[macOS build 1.2.0 (0d09d2c)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-macos-x64-1.2.0-0d09d2c.dmg) is ready for download.
[Windows x64 build 1.2.0 (0d09d2c)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x64-1.2.0-0d09d2c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0d09d2c)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x32-1.2.0-0d09d2c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (645a11b)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-linux-x64-1.2.0-645a11b.deb) is ready for download.
[macOS build 1.2.0 (645a11b)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-macos-x64-1.2.0-645a11b.dmg) is ready for download.
[Windows x64 build 1.2.0 (645a11b)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x64-1.2.0-645a11b.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (645a11b)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x32-1.2.0-645a11b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (3a00443)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-linux-x64-1.2.0-3a00443.deb) is ready for download.
[macOS build 1.2.0 (3a00443)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-macos-x64-1.2.0-3a00443.dmg) is ready for download.
[Windows x64 build 1.2.0 (3a00443)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x64-1.2.0-3a00443.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (3a00443)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x32-1.2.0-3a00443.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (45752a7)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-linux-x64-1.2.0-45752a7.deb) is ready for download.
[macOS build 1.2.0 (45752a7)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-macos-x64-1.2.0-45752a7.dmg) is ready for download.
[Windows x64 build 1.2.0 (45752a7)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x64-1.2.0-45752a7.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (45752a7)](https://tc-builds.door43.org/build/feature-mannycolon-5837/translationCore-win-x32-1.2.0-45752a7.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]

**Pull request merged**
