### PR TITLE
Feature mcleanb 5388/preserve all original USFM3 markers on export without alignments

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- USFM word markers are no longer stripped out on import if there is no alignment data
- only with USFM3 export are newlines added before alignment markers.
- export dialog now has checkbox instead of radio buttons

#### Please include detailed Test instructions for your pull request:
- install the build attached at bottom of this PR.
- import test file - [usfm intro test 3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2596225/usfm.intro.test.3.usfm.zip)
- in WA, make a few alignments.
- do export to USFM and uncheck "add alignment data".
- do diff of test file with exported file - only the first line (`\id...`) should be different
- do export to USFM and check "add alignment data".
- do diff of test file with exported file - now the first line (`\id...`) should be different, then the reast of the header data should be the same until you get to chapter 1 (`\c 1`).  Then each verse should have alignment data added with the following markers on newlines:`\zaln-s`, `\w`, `\zaln-e\*` such as:

screen shot 2018-11-19 at 12 00 59 pm

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5458)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (968aff8)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-linux-x64-1.1.0-968aff8.deb) is ready for download.
[macOS build 1.1.0 (968aff8)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-macos-x64-1.1.0-968aff8.dmg) is ready for download.
[Windows x64 build 1.1.0 (968aff8)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x64-1.1.0-968aff8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (968aff8)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x32-1.1.0-968aff8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0fe82f1)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-linux-x64-1.1.0-0fe82f1.deb) is ready for download.
[macOS build 1.1.0 (0fe82f1)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-macos-x64-1.1.0-0fe82f1.dmg) is ready for download.
[Windows x64 build 1.1.0 (0fe82f1)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x64-1.1.0-0fe82f1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0fe82f1)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x32-1.1.0-0fe82f1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (dae0b11)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-linux-x64-1.1.0-dae0b11.deb) is ready for download.
[macOS build 1.1.0 (dae0b11)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-macos-x64-1.1.0-dae0b11.dmg) is ready for download.
[Windows x64 build 1.1.0 (dae0b11)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x64-1.1.0-dae0b11.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (dae0b11)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x32-1.1.0-dae0b11.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (f0199e7)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-linux-x64-1.1.0-f0199e7.deb) is ready for download.
[macOS build 1.1.0 (f0199e7)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-macos-x64-1.1.0-f0199e7.dmg) is ready for download.
[Windows x64 build 1.1.0 (f0199e7)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x64-1.1.0-f0199e7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (f0199e7)](https://tc-builds.door43.org/build/feature-mcleanb-5388/translationCore-win-x32-1.1.0-f0199e7.setup.exe) is ready for download.

**Comment by bspidel** [comment]
While ID was different, the following differences also exist. Seems like I heard these might be ok. But I include them for your examination.

57-tit-difs

**Review by bspidel — APPROVED** [review]
ignore previous comment. It would have been helpful to know to install the "last" build not the one below.

:lgtm:

> Reviewed 2 of 4 files at r1, 5 of 5 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5458#-:-LRsQc_w7behYOL6JVJ_:bdqsqi5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
