### PR TITLE
Fix Changing Tools

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
#1072 
Fixes the ability to change tools after initially choosing a tool

#### How to test this pull request:
Get a fresh project
checkout js_fixChangeProject on tW
and checkout js_fixChangeProject on VerseCheck
load a tool and try switching

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1073)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/currentToolActions.js, line 20 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhUyYZk6mZY5P_F9v6F:-KhUyYZk6mZY5P_F9v6G:b-91te7p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/be761bd98348cd84180d28b4e6481d5c9fdd1705/src/js/actions/currentToolActions.js#L20)):*
> ```JavaScript
> }
> 
> export const setDataFetched = (val) => {
> ```

please add documentation for this action

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073)*

**Comment by mannycolon** [comment]
@RoyalSix please fix merge conflicts

**Comment by RoyalSix** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/currentToolActions.js, line 20 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhUyYZk6mZY5P_F9v6F:-KhVnJUoucWYAOlfdwIt:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/be761bd98348cd84180d28b4e6481d5c9fdd1705/src/js/actions/currentToolActions.js#L20)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

please add documentation for this action
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073)*

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/CoreActionConsts.js, line 101 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYMjgYoWTij8jatz0_:-KhYMjgYoWTij8jatz0a:bwpjmsj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/actions/CoreActionConsts.js#L101)):*
> ```JavaScript
>   LOAD_MODULE_SETTINGS: "LOAD_MODULE_SETTINGS",
>   SET_PROJECT_DETAIL: "SET_PROJECT_DETAIL",
>   SET_DATA_FETCHED:"SET_DATA_FETCHED"
> ```

Could we possibly change this to SET_FETCHED_DATA rather than SET_DATA_FETCHED? It just sounds awkward the way its currently phrased.

---

*[src/js/actions/GetDataActions.js, line 255 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYN9lQwrKY1_Qv9pU3:-KhYN9lQwrKY1_Qv9pU4:bgrmyfx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/actions/GetDataActions.js#L255)):*
> ```JavaScript
>     return ((dispatch) => {
>         try {
>             dispatch(CoreActionsRedux.changeModuleView(''));
> ```

This may be intentional and necessary, but why are we passing an empty string into this action? Why does it need a parameter. Or I could say: can we just set an empty string to the default parameter for this function to avoid confusing action calls such as this one?

---

*[src/js/reducers/currentToolReducer.js, line 5 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYNcCisdr5gA04UvN0:-KhYNcCisdr5gA04UvN1:bd5ds5f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/reducers/currentToolReducer.js#L5)):*
> ```JavaScript
> const initialState = {
>   toolName: null,
>   dataFetched: false
> ```

Could we also potentially rename this to isDataFetched? Just to make it more evident that it is in fact a boolean. Since we dont explicitly declare types in JS nowhere in this file suggests that dataFetched is a boolean aside from this line. I would first assume that dataFetched is the data itself. 

---

*[src/js/reducers/currentToolReducer.js, line 15 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYNS6CglxHKavhkPvw:-KhYNS6CglxHKavhkPvx:bv2elds) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/reducers/currentToolReducer.js#L15)):*
> ```JavaScript
>         toolName: action.toolName
>       }
>     case consts.SET_DATA_FETCHED:
> ```

Ibid on naming here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073)*

**Comment by RoyalSix** [comment]
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/CoreActionConsts.js, line 101 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYMjgYoWTij8jatz0_:-KhaqzrcGSnEBO-BqfoD:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/actions/CoreActionConsts.js#L101)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Could we possibly change this to SET_FETCHED_DATA rather than SET_DATA_FETCHED? It just sounds awkward the way its currently phrased.
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 255 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYN9lQwrKY1_Qv9pU3:-KharL2zyiqL1aPoQGIv:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/actions/GetDataActions.js#L255)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

This may be intentional and necessary, but why are we passing an empty string into this action? Why does it need a parameter. Or I could say: can we just set an empty string to the default parameter for this function to avoid confusing action calls such as this one?
</blockquote></details>

Done.

---

*[src/js/reducers/currentToolReducer.js, line 5 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYNcCisdr5gA04UvN0:-KhasUZRdpeyMD5pYnyC:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/reducers/currentToolReducer.js#L5)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Could we also potentially rename this to isDataFetched? Just to make it more evident that it is in fact a boolean. Since we dont explicitly declare types in JS nowhere in this file suggests that dataFetched is a boolean aside from this line. I would first assume that dataFetched is the data itself. 
</blockquote></details>

Done.

---

*[src/js/reducers/currentToolReducer.js, line 15 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073#-KhYNS6CglxHKavhkPvw:-KhasVAMKXllskN6BeP2:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6f2015f5f540fcd430647091e2b09eaab7b9a0c7/src/js/reducers/currentToolReducer.js#L15)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Ibid on naming here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073)*

**Comment by klappy** [comment]
Reviewed 2 of 7 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1073)*

**Pull request merged**
