### PR TITLE
Added Highlighted words to Greek and ULB Pane

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added Highlighted words to Greek and GL Pane 
- **Dependency:** https://github.com/translationCoreApps/ScripturePane/pull/93

#### Please include detailed Test instructions for your pull request:
- [ ] Open a brand new/fresh project with tW
- [ ] Words should highlight in both greek (ugnt) and English (ulb)
- [ ] Open an old project with tW and it should not show Highlighted words in the scripture pane but open with no problems.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3890)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5p6i-QfeRsXYnMEdMf:b-hcg9k0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/912ab7331469c27d3b7da673b02abe74cdff80e8/src/js/actions/VerseObjectActions.js#L29)):*
> ```JavaScript
>       } else if (object.type === 'milestone') { // get children of milestone
>         // add content attibute to children
>         const newObject = object.children.map((children) => {
> ```

Will this work in the case of nested milestones?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by mannycolon** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5qm42dr3Q9nTmQWKpZ:b-apv9k1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8dc9ea12a794c3ffcc14a09929bce5b0b94611b0/src/js/actions/VerseObjectActions.js#L29)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Will this work in the case of nested milestones?
</blockquote></details>

I have not encountered any problems yet but that's maybe because the data I tested isn't as nested. At least with a Titus project I had no issues. 

Can you confirm if a Titus project may include or not nested milestones?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5tT0sq2XtJuWxnHV9F:br6i3yj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8dc9ea12a794c3ffcc14a09929bce5b0b94611b0/src/js/actions/VerseObjectActions.js#L29)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I have not encountered any problems yet but that's maybe because the data I tested isn't as nested. At least with a Titus project I had no issues. 

Can you confirm if a Titus project may include or not nested milestones?
</blockquote></details>

Yes, that can easily happen.  When a user combines two or more greek words, they are represented as nested milestones.  Here is an example from Titus 1:5 in en_ULB:

      {
        "tag": "zaln",
        "type": "milestone",
        "lemma": "ὁ",
        "morph": "Gr,RD,,,,ANP,",
        "occurrence": 1,
        "occurrences": 2,
        "strong": "G35880",
        "content": "τὰ",
        "children": [
          {
            "tag": "zaln",
            "type": "milestone",
            "lemma": "λείπω",
            "morph": "Gr,VIPPA,ANP,",
            "occurrence": 1,
            "occurrences": 1,
            "strong": "G30070",
            "content": "λείποντα",
            "children": [
              {
                "text": "things",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "not",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "yet",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "complete",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              }
            ]
          }
        ]
      },

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by klappy** [comment]
*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5tsPBZ059T5OxF_ubf:brt1bbr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8dc9ea12a794c3ffcc14a09929bce5b0b94611b0/src/js/actions/VerseObjectActions.js#L29)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Yes, that can easily happen.  When a user combines two or more greek words, they are represented as nested milestones.  Here is an example from Titus 1:5 in en_ULB:

      {
        "tag": "zaln",
        "type": "milestone",
        "lemma": "ὁ",
        "morph": "Gr,RD,,,,ANP,",
        "occurrence": 1,
        "occurrences": 2,
        "strong": "G35880",
        "content": "τὰ",
        "children": [
          {
            "tag": "zaln",
            "type": "milestone",
            "lemma": "λείπω",
            "morph": "Gr,VIPPA,ANP,",
            "occurrence": 1,
            "occurrences": 1,
            "strong": "G30070",
            "content": "λείποντα",
            "children": [
              {
                "text": "things",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "not",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "yet",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "complete",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              }
            ]
          }
        ]
      },


</blockquote></details>

It took a while to fully grasp what @photonomad0 was inferring but this could lead to false negatives. Since only the first Greek word gets propogated to the children, There doesn't seem to be a way to have the second greek word persisted here. So if there was a check in which this second word was needed and not the first, it wouldn't have the second word in the content attribute and skip right over highlighting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-:-L5uRBJ-OU2zjugolTy6:bnfp4nl)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5uT4n1KcP01aBDFOkU:beoz16c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8dc9ea12a794c3ffcc14a09929bce5b0b94611b0/src/js/actions/VerseObjectActions.js#L29)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

It took a while to fully grasp what @photonomad0 was inferring but this could lead to false negatives. Since only the first Greek word gets propogated to the children, There doesn't seem to be a way to have the second greek word persisted here. So if there was a check in which this second word was needed and not the first, it wouldn't have the second word in the content attribute and skip right over highlighting. 
</blockquote></details>

I'm working an what i believe should probably handle this use case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by mannycolon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/VerseObjectActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5p6i-QfeRsXYnMEdMe:-L5wFLLc1nSe2TYp0-jP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8dc9ea12a794c3ffcc14a09929bce5b0b94611b0/src/js/actions/VerseObjectActions.js#L29)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I'm working an what i believe should probably handle this use case
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/actions/VerseObjectActions.js, line 39 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5x4sS89K9xDOkYj1PI:-L5x4sS89K9xDOkYj1PJ:b55ra72) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/918fae3452e02df964b33a3b69397337f4407e9b/src/js/actions/VerseObjectActions.js#L39)):*
> return childrens.map((children) => {

I know this is a small quibble, but prefer renaming of variables here (children is plural).  How about renaming such as:

`return children.map((child) => {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/actions/VerseObjectActions.js, line 39 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L5x4sS89K9xDOkYj1PI:-L6337j2RSKFV_cpJ5GN:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/918fae3452e02df964b33a3b69397337f4407e9b/src/js/actions/VerseObjectActions.js#L39)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

> return childrens.map((children) => {

I know this is a small quibble, but prefer renaming of variables here (children is plural).  How about renaming such as:

`return children.map((child) => {`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by richmahn** [comment]
Reviewed 2 of 3 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tC_apps/ScripturePane, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L63on2RQ5L2DzXhlqN9:-L63on2SfuXUqEZuFXD1:bsj7akm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7fadffff44a905ea5742855b63da2b407dfd4c36/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit c77eba2ef79618bffcb5af631f53047a4f16873d
> ```

Should this be committed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tC_apps/ScripturePane, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-L63on2RQ5L2DzXhlqN9:-L63qDwvuLRgTfJJ9sm_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7fadffff44a905ea5742855b63da2b407dfd4c36/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Should this be committed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890)*

**Comment by richmahn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3890#-:-L63qpmFodBMZm-9Ztbi:bnfp4nl)*

**Pull request merged**
