### PR TITLE
TranslationNotes 

### PR DESCRIPTION
**Pull request by mannycolon**
Still pending:
1. Some optimization and UI/UX fixes.
2. Sync ConfirmDisplay.js with current Check.
3. Fixed repeated bible verses in menu view.
4. Improve data parsing for confirmDisplay.js and translationAcademy 

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/80)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 68 of 79 files at r1, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[modules/phrase_check_module/subcomponents/TargetVerseDisplay.js, line 259 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80#-KQYxTleaGj3xMR21mGO:-KQYxTleaGj3xMR21mGP:bmg2mfx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4c413a9b88d0ec91008bef425b351e0f888d754/modules/phrase_check_module/subcomponents/TargetVerseDisplay.js#L259)):_

> ``` JavaScript
>       else if (lastKey == wordObj.key - 1) {
>         var lastWord = returnArray.pop();
>         lastWord += ' ' + wordObj.word;
> ```

Maybe remove all the commented out code if we aren't going to use it. 

---

_[out/js/ModuleApi.js, line 1 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80#-KQYxddoNsJKeGxP9BIL:-KQYxddoNsJKeGxP9BIM:brbod5r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4c413a9b88d0ec91008bef425b351e0f888d754/out/js/ModuleApi.js#L1)):_

> ``` JavaScript
> //ModuleApi.js//
> ```

Delete the out folder

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80)_

**Comment by ihoegen** [comment]
@mannycolon Try running 

```
git rm -r --cached . 
git add .
git commit -m"Remove ignored files."
```

to remove any files that shouldn't be tracked with git.

**Comment by mannycolon** [comment]
@ihoegen Ok, i just fix all you suggestions please review it again and also did you try my branch to see if it works? try using at least two different projects to make sure theres nothing else to address. thanks

**Comment by mannycolon** [comment]
Review status: 20 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

_[modules/phrase_check_module/subcomponents/TargetVerseDisplay.js, line 259 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80#-KQYxTleaGj3xMR21mGO:-KQaBM0ngkRunTsSyjv1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4c413a9b88d0ec91008bef425b351e0f888d754/modules/phrase_check_module/subcomponents/TargetVerseDisplay.js#L259)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Maybe remove all the commented out code if we aren't going to use it. 
> </details>
> Done.

---

_[out/js/ModuleApi.js, line 1 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80#-KQYxddoNsJKeGxP9BIL:-KQaBL8QGa9iFakMWo4J:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e4c413a9b88d0ec91008bef425b351e0f888d754/out/js/ModuleApi.js#L1)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Delete the out folder
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/80)_

**Pull request merged**
