### PR TITLE
Feature mcleanb 3086/show invalidated selection.4

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updates UI toolkit version to 0.9.2

#### Please include detailed Test instructions for your pull request:
- uses https://github.com/translationCoreApps/translationWords/pull/125 
- uses https://github.com/translationCoreApps/tc-ui-toolkit/pull/15

- Local testing setup: 
  `git fetch`
  `git checkout feature-mcleanb-3086/ShowInvalidatedSelection.4`
  `npm i`
  `cd tC_apps/translationWords`
  `git fetch`
  `git checkout feature-mcleanb-3086/ShowInvalidatedSelection.2`
  `cd ../..`
  `npm start`

- Test steps:
  - open tw tool.  Under blameless, for vs 1:6 selected "without blame" then clicked on vs 1:7, using scripture pane editor edited 1:6 to remove space to make selection "withoutblame".  Clicked on 1:6. see invalidated icon on group menu and on verse check bar and on instructions.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (db463e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-db463e2.zip) is ready for download.
[macOS build 0.10.0 (db463e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-db463e2.dmg) is ready for download.
[Windows x64 build 0.10.0 (db463e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-db463e2.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (db463e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-db463e2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (8f9752e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-8f9752e.zip) is ready for download.
[macOS build 0.10.0 (8f9752e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-8f9752e.dmg) is ready for download.
[Windows x64 build 0.10.0 (8f9752e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-8f9752e.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (8f9752e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-8f9752e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (0d74969)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-0d74969.zip) is ready for download.
[macOS build 0.10.0 (0d74969)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-0d74969.dmg) is ready for download.
[Windows x64 build 0.10.0 (0d74969)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-0d74969.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (0d74969)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-0d74969.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

---

*[tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604#-LEmDndE7YBtPgYq9Tp-:-LEmDndF5y5wYqL00MAl:b5r56e8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0d74969eb719eef95b005f4d2b23d245574bb4e2/tC_apps/translationWords#L1)):*
> ```
> Subproject commit 40beb34de1ed61e5c63c4c74fa24e17f413b061b
> ```

you may want to remove the submodule commit

---

*[tC_apps/wordAlignment, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604#-LEmDr9wABbuJZvwD1Ib:-LEmDr9wABbuJZvwD1Ic:b5r56e8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0d74969eb719eef95b005f4d2b23d245574bb4e2/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit 1788a588e08ae4c9366efe13d4c7b5e59a0e4ac0
> ```

you may want to remove the submodule commit

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604)*

**Comment by mannycolon** [comment]
you added tc-ui-toolkit 0.8.0 here but i see youre using 0.7.9 in the PR you made in tW

**Comment by PhotoNomad0** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mannycolon and @PhotoNomad0)

---

*[tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604#-LEmDndE7YBtPgYq9Tp-:-LEpoqlhBd9_4TUVsoN2:bxnqss6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0d74969eb719eef95b005f4d2b23d245574bb4e2/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you may want to remove the submodule commit
</blockquote></details>

this has to point to latest tw for concourse to build test.

---

*[tC_apps/wordAlignment, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604#-LEmDr9wABbuJZvwD1Ib:-LEpobAB0SsAn0gtb4XA:br4zx1z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0d74969eb719eef95b005f4d2b23d245574bb4e2/tC_apps/wordAlignment#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you may want to remove the submodule commit
</blockquote></details>

this has been reverted to same commit as develop

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4604)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (8274c97)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-8274c97.zip) is ready for download.
[macOS build 0.10.0 (8274c97)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-8274c97.dmg) is ready for download.
[Windows x64 build 0.10.0 (8274c97)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-8274c97.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (8274c97)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-8274c97.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (bb6ee2e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-bb6ee2e.zip) is ready for download.
[macOS build 0.10.0 (bb6ee2e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-bb6ee2e.dmg) is ready for download.
[Windows x64 build 0.10.0 (bb6ee2e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-bb6ee2e.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (bb6ee2e)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-bb6ee2e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (934e47c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-934e47c.zip) is ready for download.
[macOS build 0.10.0 (934e47c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-934e47c.dmg) is ready for download.
[Windows x64 build 0.10.0 (934e47c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-934e47c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (934e47c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-934e47c.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
@PhotoNomad0 Shouldn't` tc-ui-toolkt` be pointing at an npm version before it gets into develop?
Same with `translationWords` repo

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (2116cba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-2116cba.zip) is ready for download.
[macOS build 0.10.0 (2116cba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-2116cba.dmg) is ready for download.
[Windows x64 build 0.10.0 (2116cba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-2116cba.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (2116cba)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-2116cba.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
@PhotoNomad0 I pulled `feature-mcleanb-3086/ShowInvalidatedSelection.2` for tW and `feature-mcleanb-3086/ShowInvalidatedSelection.4` in the core and ran NPM I to update the latest version of `tc-ui-toolkit`. However, I don't see your changes.

**Comment by PhotoNomad0** [comment]
@mannycolon - to be clear here, you are telling me that you when you have a verse that has invalidated icon on the group menu - it does not have the invalidated icon on the verseEdit bar and invalidated text on instructions.

I tried on Windows PC (different machine) the steps above.  Under blameless, for vs 1:6 selected "without blame" then clicked on vs 1:7, using scripture pane editor edited 1:6 to remove space to make selection "withoutblame".  Clicked on 1:6. see invalidated icon on group menu and on verse check bar and on instructions.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (617553b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-617553b.zip) is ready for download.
[macOS build 0.10.0 (617553b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-617553b.dmg) is ready for download.
[Windows x64 build 0.10.0 (617553b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-617553b.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (617553b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-617553b.setup.exe) is ready for download.

**Pull request closed without merging**
