### PR TITLE
Add way to close a project.

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request adds an option under file that let's users close the current project.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/640)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 2 of 5 files at r1, 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/MenuBar.js, line 7 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/640#-KcMAxTTos7tXNNYCQHW:-KcMAxTTos7tXNNYCQHX:b-p89wpa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/97f8fbc7ca7c6c808b96665271e53b18d866ac5f/src/js/components/core/MenuBar.js#L7)):*
> ```JavaScript
>  ******************************************************************************/
> const CoreActions = require('../../actions/CoreActions.js');
> const CoreActionsRedux = require('../../actions/CoreActionsRedux.js');
> ```

Are we supposed to be doing anything with CoreActionsRedux?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/640)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/640)*

**Comment by ihoegen** [comment]
@RoyalSix Just removed it

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/640)*

**Comment by RoyalSix** [comment]
Is this updated?

**Comment by ihoegen** [comment]
I may have forgotten to push

**Comment by ihoegen** [comment]
@RoyalSix Updated now

**Pull request closed without merging**
