### PR TITLE
Fixed Empty project cards

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Fixed Empty project cards

#### How to test this pull request:
- Import the following usfm project [fr_eph_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1242999/fr_eph_text_reg.usfm.zip) using the local import option.
- Cancel out of copyright screen.
- Make sure the project name shows up in the projects list.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2518)

### CODE REVIEW

**Comment by mannycolon** [comment]
#691

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2518)*

**Comment by klappy** [comment]
@mannycolon I'm not sure if it was this same issue, but check with @cckozie to see if the project should remain in the project list or if we should delete it upon cancel. I remember it being mentioned but don't think it was documented and if it was I can't find the issue that documents it.

@cckozie If we need to remove the canceled import, I feel that it will take more time than allocated and should be assessed as a separate story. That behavior will take a lot more work.

**Comment by klappy** [comment]
:lgtm: (This PR addresses the issues defined and will merge.)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2518#-:-KsG4rfRCFcjnTk3NQqa:bppt5l5)*

**Pull request merged**
