### PR TITLE
Bugfix 6424/Fix verse edits made in one tool not updating group menu state in other tools

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- clears caching problems in group menu:
  - fix for finding group data item with quote arrays when syncing external edits.
  - make sure wA group menu reducer is cleared when WA is launched.
- performance optimizations - minimize isEqual in deeply nested loops, optimize order of comparisons in loop

#### Please include detailed Test instructions for your pull request:
- use attached build at bottom of PR.
- follow steps in https://github.com/unfoldingword-dev/translationcore/issues/6424
- make sure check mark is cleared on group menu for verse.
- then test edits in the other direction:
  - in TN tool edit a different verse in chapter 2
  - go back to WA and make sure edited verse shows both edit and invalidated on group menu

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6468)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1196217)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-1196217.deb) is ready for download.
[macOS build 2.0.0 (1196217)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-1196217.dmg) is ready for download.
[Windows x64 build 2.0.0 (1196217)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-1196217.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1196217)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-1196217.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (3bc8d39)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-3bc8d39.deb) is ready for download.
[macOS build 2.0.0 (3bc8d39)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-3bc8d39.dmg) is ready for download.
[Windows x64 build 2.0.0 (3bc8d39)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-3bc8d39.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (3bc8d39)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-3bc8d39.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (066aab6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-066aab6.deb) is ready for download.
[macOS build 2.0.0 (066aab6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-066aab6.dmg) is ready for download.
[Windows x64 build 2.0.0 (066aab6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-066aab6.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (066aab6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-066aab6.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (2ace243)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-2ace243.deb) is ready for download.
[macOS build 2.0.0 (2ace243)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-2ace243.dmg) is ready for download.
[Windows x64 build 2.0.0 (2ace243)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-2ace243.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (2ace243)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-2ace243.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (61d652d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-61d652d.deb) is ready for download.
[macOS build 2.0.0 (61d652d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-61d652d.dmg) is ready for download.
[Windows x64 build 2.0.0 (61d652d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-61d652d.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (61d652d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-61d652d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (12dff91)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-linux-x64-2.0.0-12dff91.deb) is ready for download.
[macOS build 2.0.0 (12dff91)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-macos-x64-2.0.0-12dff91.dmg) is ready for download.
[Windows x64 build 2.0.0 (12dff91)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x64-2.0.0-12dff91.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (12dff91)](https://tc-builds.door43.org/build/bugfix-mcleanb-6424/translationCore-win-x32-2.0.0-12dff91.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
