### PR TITLE
Parsed Resources

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR address issue # 1833

#### How to test this pull request:
Nothing to test, assure format is as described in above issue

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1852)

### CODE REVIEW

**Comment by klappy** [comment]
:lgtm:

**Comment by klappy** [comment]
@RoyalSix: The Markdown files for tA articles look a bit wonky.

Sometimes the entire file is enclosed in double quotes, other times it's not.
The main issue is that line breaks should be interpreted and not preserved as characters.

**Comment by mannycolon** [comment]
@royalsix I thought we were goin to use the parsed format for `UGNT` bible?

**Comment by klappy** [comment]
FYI: OL stands for Other Languages as in not a Gateway Language. We don't have an abbreviation for Original Languages.

**Comment by klappy** [comment]
I can merge this but it will not be fully functional until Projects/Tools can get resources from location in core.

**Pull request merged**
