### PR TITLE
Instructions for developers

### PR DESCRIPTION
**Pull request by ihoegen**
This completes issue #14

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/38)

### CODE REVIEW

**Comment by ihoegen** [comment]
I think this one is more for @klappy but if anyone else can provide input that'd be great

**Comment by klappy** [comment]
Will check this out! Somehow I missed this was a PR.

**Comment by klappy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeemRXPGhkHE36XeMi:-KPeemRYbwi-ST84dv1W:b-6h4kr8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L1)):_

> ``` Markdown
> # Translation Core
> ```

For now we'll want to standardize on "translationCore"

---

_[README.md, line 2 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeeuJ0zVwcr4zOYQzA:-KPeeuJ0zVwcr4zOYQzB:b97g3v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L2)):_

> ``` Markdown
> # Translation Core
> Repository for the desktop application Translation Core
> ```

translationCore

---

_[README.md, line 36 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPefKMlmOP5Pcr9Wpqv:-KPefKMlmOP5Pcr9Wpqw:b-4xu5mi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L36)):_

> ``` Markdown
> 2. Run the command `git clone https://github.com/unfoldingWord-dev/translationCore.git`, or you may clone your own fork.
> 3. Change directories to the repository directory and run the command `npm install` to install all required Nodejs modules.
> 4. Create a file `.auth` in the root folder of the project.
> ```

Will this still work? There were some discussions from Jay that he fixed it to where a blank .auth file will no longer work like it use to for us. I'm okay with encouraging them to generate their own git api token but would require directions or more simply give them the option to use a blank one but let them know what the downsides are.

---

_[README.md, line 49 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeftQcbXFa4KTgmnNh:-KPeftQdHQudUdESsUJp:bym97en) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L49)):_

> ``` Markdown
> 6. Submit a Pull Request with develop.
> 7. ???
> 8. Profit
> ```

I know I was being silly with this one. We should probably remove the "profit" :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38)_

**Comment by klappy** [comment]
Overall it looks good. Just a few things to address. Sorry it took so long to get to it. Thanks for working on this!

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-:-KPeg8KxlIe8UdgTchCl:bletu6)_

**Comment by ihoegen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeemRXPGhkHE36XeMi:-KPjMxwvUzkr85XQFAIn:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L1)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> For now we'll want to standardize on "translationCore"
> </details>
> Done.

---

_[README.md, line 2 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeeuJ0zVwcr4zOYQzA:-KPjMyV_wTQcTjSNumox:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L2)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> translationCore
> </details>
> Done.

---

_[README.md, line 36 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPefKMlmOP5Pcr9Wpqv:-KPjMzz5eFwxvYOh8zZ-:b-b4o5h6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L36)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> Will this still work? There were some discussions from Jay that he fixed it to where a blank .auth file will no longer work like it use to for us. I'm okay with encouraging them to generate their own git api token but would require directions or more simply give them the option to use a blank one but let them know what the downsides are.
> </details>
> I am not entirely sure about this still working, but I could add in the downsides to this. What are the downsides I should let them know about?

---

_[README.md, line 49 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38#-KPeftQcbXFa4KTgmnNh:-KPjN9JadLJ4b3dAnyiG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9d1a5d4eb1912c9b90243f5806a04894c4d84bef/README.md#L49)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> I know I was being silly with this one. We should probably remove the "profit" :)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/38)_

**Pull request merged**
