### PR TITLE
Package manager refactor

### PR DESCRIPTION
**Pull request by ihoegen**
**Disclaimer** The funny thing with PackageManager is that it is not rendered in App, in fact, it's rendered in it's own div, overlapping App. So passing things down from the very top will not work. So PackageManagerView acts as our container

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/433)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Nice.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/433#-:-K_C9ShZqNnr_u8oKNrt:b-83sjo4)*

**Comment by RoyalSix** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/433)*

**Comment by RoyalSix** [comment]
Checking out branch, code looks good.

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/433#-:-K_C9eJMiw5Wjqiw7izN:b-51upnp)*

**Comment by ihoegen** [comment]
@RoyalSix What's the status on this?

**Comment by RoyalSix** [comment]
> ih-refactor-package-manager
Hey I just checkedout the branch opened the package manager and tried to close it and it wouldn't close

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/433#-:-K_aZNEbW9Ae4qWXVvkO:b-chfkx5)*

**Comment by ihoegen** [comment]
@RoyalSix It should close now.

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/433)*

**Pull request merged**
