### PR TITLE
WIP: Feature #3186/import alignment data with USFM import, and fix alignment export to USFM

### LINKED ISSUE #3186: GL Alignment Data Import as Target Language Project from USFM 3 File
- GL Alignment Data Import as Target Language Project from USFM 3 File
  - USFM.js: Improved USFM 3 to Verse Objects
  - tC Helpers: Split Verse Objects to Target Verse String and Alignment Data

Alignment data for target language project import will be handled in: #3559

### LINKED ISSUE #3756: Fix issues with USFM3 alignment export
See a couple problems still with USFM3 alignment export:

* verse markers are not at beginning of line 
* unaligned chapters are not included in the output

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Closed due to breaking changes in develop.  Created new: https://github.com/unfoldingWord-dev/translationCore/pull/3895

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes #3186
  - issue to import alignment data contained in USFM3 file
- Fixes #3756
  - issue on USFM export that verse markers are not at beginning of line (depends on https://github.com/translationCoreApps/usfm-js/pull/33)
  - issue on alignment export that unaligned chapters are not included in the output

#### Please include detailed Test instructions for your pull request:
- on USFM export, should see chapter and verse markers beginning on new lines.
- on USFM export of project with unaligned chapters, should see data for all chapters, even the unaligned.
- on USFM import of project with alignments, should see same alignment data in WA: unaligned words should show up in word bank and aligned words should show also.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3868)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/helpers/ResourcesHelpers.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868#-L5koNc15YMrB4y2K61X:-L5koNc15YMrB4y2K61Y:b1f9ahn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d53c52df8c634f9b59a662214704343c2d7cd801/src/js/helpers/ResourcesHelpers.js#L18)):*
> ```JavaScript
>       const STATIC_RESOURCES_BIBLES_PATH = path.join(STATIC_RESOURCES_PATH, languagesId, 'bibles');
>       const BIBLE_RESOURCES_PATH = path.join(USER_RESOURCES_PATH, languagesId, 'bibles');
>       let bibleNames = fs.readdirSync(STATIC_RESOURCES_BIBLES_PATH).filter(folder => { // filter out .DS_Store
> ```

Was this added back on purpose? These were filtered out since they weren't doing anything. There aren't any folders `.DS_Store` just files and we don't need these in this file, it happens in a few blocks below as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by klappy** [comment]
Reviewed 8 of 11 files at r1, 2 of 2 files at r2.
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by PhotoNomad0** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/helpers/ResourcesHelpers.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868#-L5koNc15YMrB4y2K61X:-L5mzUzR0wnWJ4GM6pGu:b-icl1fb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d53c52df8c634f9b59a662214704343c2d7cd801/src/js/helpers/ResourcesHelpers.js#L18)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Was this added back on purpose? These were filtered out since they weren't doing anything. There aren't any folders `.DS_Store` just files and we don't need these in this file, it happens in a few blocks below as well.
</blockquote></details>

I don't know where it was added, but I don't see any check to make sure these are folders before copying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by PhotoNomad0** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/ResourcesHelpers.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868#-L5koNc15YMrB4y2K61X:-L5n7CI3Fa4-ihYIeAqQ:b-puvei7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d53c52df8c634f9b59a662214704343c2d7cd801/src/js/helpers/ResourcesHelpers.js#L18)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

I don't know where it was added, but I don't see any check to make sure these are folders before copying.
</blockquote></details>

It looks like I hadn't merged with develop recently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by PhotoNomad0** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/ResourcesHelpers.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868#-L5koNc15YMrB4y2K61X:-L5n7JvLXyd3JLJmxUTp:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d53c52df8c634f9b59a662214704343c2d7cd801/src/js/helpers/ResourcesHelpers.js#L18)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

It looks like I hadn't merged with develop recently.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r1, 1 of 4 files at r3.
Review status: 7 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r3.
Review status: 8 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by klappy** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3868)*

**Comment by PhotoNomad0** [comment]
Closed due to breaking changes in develop.  Created new: https://github.com/unfoldingWord-dev/translationCore/pull/3895

**Pull request closed without merging**
