### PR TITLE
Check For Alignments In Project For USFM Export (Fix)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR checks if alignments have been made when doing a usfm export, as before it was checking if there was alignment data.

#### Please include detailed Test instructions for your pull request:
Test 1:
- Open a new project
- Open the Alignment Tool (Do not do alignments)
- Go back to projects page click on the export to USFM option for that same project
- It should go directly to usfm 2 export, and then ask for a save location.

Test 2:
- Open a new project
- Open the Alignment Tool and do alignments
- Go back to projects page click on the export to USFM option for that same project
- It should ask you what type of export you would like, and then ask for a save location.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4150)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4150)*

**Comment by mannycolon** [comment]
Code review :lgtm:
Local Test: :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4150#-:-L8n5SAn6hroTwLx1-DD:b-flu6g)*

**Comment by mannycolon** [comment]
@RoyalSix Merge with latest develop branch

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4150#-:-L8nMuGt-IxD9wZsDCMT:bnfp4nl)*

**Pull request merged**
