### PR TITLE
Fixes For Stepper Colors

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR makes the colors at the top when navigating through the stepper more consistent.

#### How to test this pull request:
Ensure the the following is always true no matter what step you are on.
The current step is black
The previous steps are blue
The remaining steps are grey

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3156)

### CODE REVIEW

**Comment by richmahn** [comment]
@RoyalSix I think you mean "The remaining steps are gray", right? Black is for current step.

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3156#-:-KyrS0oJUbAcUzNfyXwd:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[__tests__/BodyUIHelpers.test.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3156#-Kyv_1F20_DKqdJF4tIL:-Kyv_1F3I9IcF7SmgaCY:b-ffij65) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fb6e1e4bcd22814d2b33b5f798074b93ee81c62e/__tests__/BodyUIHelpers.test.js#L3)):*
> ```JavaScript
> /* eslint-env jest */
> import * as bodyUIHelpers from '../src/js/helpers/bodyUIHelpers';
> ```

great job writing this test. very clean and easy to follow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3156)*

**Comment by mannycolon** [comment]
It still seems to be out of order.

For example here **copyright check** is supposed to be the current step which means it should be black
screen shot 2017-11-14 at 12 37 01 pm

same here **Project information** is supposed to be the current check
screen shot 2017-11-14 at 12 37 10 pm

I used this project 
[am_1co_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1471898/am_1co_text_ulb.zip)

**Comment by RoyalSix** [comment]
@mannycolon Wow...Nice catch. I only implemented the helper for the home stepper.
Major oversight. I'll fix that.

**Comment by mannycolon** [comment]
@RoyalSix lol it's ok. still great work.

**Comment by RoyalSix** [comment]
@mannycolon Should be good.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3156#-:-Kz0RK26bhpf-Pe-txit:bnfp4nl)*

**Pull request merged**
