### PR TITLE
Feature bspidel 2640

### PR DESCRIPTION
**Pull request by bspidel**
#### This pull request addresses:

Mock drop down list for Gateway Language Selection

#### How to test this pull request:

1 Start app
2 Select a Project
3 On tool selection page
  Note "Launch" button is selectable
4 select "Gateway Language" from drop down list
  Note "Launch" button is not selectable
5 Hover over "Launch" button
  Note Hint: 'Please select the Gateway Lanugage from which you would like to check your translation.'
6 Select "Hindi" from drop down list
  Note  "Launch" button is not selectable
7 Hover  over "Launch" button
  Note Hint: 'Only English is currently supported.'

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3748)

### CODE REVIEW

**Comment by klappy** [comment]
@bspidel: I noticed that on Travis the tests weren't passing so I pulled down to my local to see why. Looks like your filesystem isn't case sensitive and your system couldn't tell the difference. Changing the usage of GL and Gl for the filenames should do the trick. Just make sure the references for the files match the ones used in the filesystem.

**Comment by mannycolon** [comment]
Reviewed 4 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[package.json, line 61 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748#-L4hTDZ2TNRdth2ZVZfc:-L4hTDZ2TNRdth2ZVZfd:b-bn8q7x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/581f921e194e69bdea08b79e84657e48ef054b10/package.json#L61)):*
> ```JSON
>     "electron-packager": "9.1.0",
>     "electron-prebuilt-compile": "1.6.11",
>     "electron-react-devtools": "^0.5.3",
> ```

do we want to remove the carrots?

---

*[src/js/components/home/toolsManagement/ToolCard.js, line 46 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748#-L4hTUdiWs1Qt_e90lZW:-L4hTUdiWs1Qt_e90lZX:b-al2h9w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/581f921e194e69bdea08b79e84657e48ef054b10/src/js/components/home/toolsManagement/ToolCard.js#L46)):*
> ```JavaScript
>     let { title, version, description, badgeImagePath, folderName, name } = this.props.metadata;
>     let { loggedInUser, currentProjectToolsProgress, translate } = this.props;
>     //let { loggedInUser, currentProjectToolsProgress, translate, manifest } = this.props;
> ```

do we still need this commented out code?

---

*[src/js/components/home/toolsManagement/ToolsCards.js, line 51 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748#-L4hT_jnvZoNMqasoj71:-L4hT_jnvZoNMqasoj72:b-ta22so) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/581f921e194e69bdea08b79e84657e48ef054b10/src/js/components/home/toolsManagement/ToolsCards.js#L51)):*
> ```JavaScript
>             return (
>               <ToolCard
>                 //manifest={manifest}
> ```

same here ? do we need to remove this code?

---

*[src/js/components/home/toolsManagement/ToolsCards.js, line 68 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748#-L4hTeb9KRLg1gwTJM-S:-L4hTeb9KRLg1gwTJM-T:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/581f921e194e69bdea08b79e84657e48ef054b10/src/js/components/home/toolsManagement/ToolsCards.js#L68)):*
> ```JavaScript
> 
> ToolsCards.propTypes = {
>   //manifest: PropTypes.object.isRequired,
> ```

ibid

---

*[src/js/containers/home/ToolsManagementContainer.js, line 28 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748#-L4hThiFe0fbzK44OaSm:-L4hThiFe0fbzK44OaSn:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/581f921e194e69bdea08b79e84657e48ef054b10/src/js/containers/home/ToolsManagementContainer.js#L28)):*
> ```JavaScript
>     } = this.props.reducers.settingsReducer;
>     const {
>       //manifest: {
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748)*

**Comment by klappy** [comment]
Reviewed 1 of 8 files at r1, 1 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748)*

**Comment by mannycolon** [comment]
Something doesn't look right. Is the card content supposed to look like this?

screen shot 2018-02-06 at 10 37 56 pm

**Comment by richmahn** [comment]
@mannycolon Yeah, that looks strange, not that they keys are missing (yet would think we'd have it for this), but that the key is now "See more" rather than something like "see_more". @neutrinog Is it suppose to look like this?

**Comment by klappy** [comment]
Reviewed 1 of 6 files at r4.
Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748)*

**Comment by mannycolon** [comment]
Reviewed 4 of 6 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748)*

**Comment by mannycolon** [comment]
Waiting on Travis

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3748)*

**Pull request merged**
