### PR TITLE
USFM Exporting Fixes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes issues with USFM exporting outlined in #1690.
This includes:
1. Using spaces for book abbreviation delimiting
2. Making id tag before h tag
other miscellaneous fixes for usfm so that exports are aligned with usfm standard format now.
also updates usfm-js version number

#### How to test this pull request:
Try exporting and importing usfm projects of any kind

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2301)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package-lock.json, line 0 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-Kq8k6pGVoOuXhSuD6Jp:-Kq8k6pGVoOuXhSuD6Jq:bnomauo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72f75fbe48b04d51e310c372475ca2b45382e2d0/package-lock.json#L0)):*
add package-lock.json to your .gitignore file.

---

*[src/js/helpers/LoadHelpers.js, line 452 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-Kq8kTsslZKmMmG9XRRQ:-Kq8kTsslZKmMmG9XRRR:bxfeto1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72f75fbe48b04d51e310c372475ca2b45382e2d0/src/js/helpers/LoadHelpers.js#L452)):*
> ```JavaScript
>     }
>     return params;
> }
> ```

maybe we should have a usfmHelpers.js, what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-:-Kq8kbwQOYqVx_RVWrcJ:bnfp4nl)*

**Comment by klappy** [comment]
*[package-lock.json, line  at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-Kq8k6pGVoOuXhSuD6Jp:-Kq8kyrgmiuKfhk2yIes:b-xg1fgc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72f75fbe48b04d51e310c372475ca2b45382e2d0/package-lock.json#L)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add package-lock.json to your .gitignore file.
</blockquote></details>

Since this continues to be a problem, if we all use the same version of npm, it will minimize the differences. Right now 5.1.0 is required for builds.
Can you both use that version? `npm i -g npm@5.1.0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 452 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-Kq8kTsslZKmMmG9XRRQ:-Kq8lGCAPLU3e1mxx0V9:b-ef268d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72f75fbe48b04d51e310c372475ca2b45382e2d0/src/js/helpers/LoadHelpers.js#L452)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe we should have a usfmHelpers.js, what do you think?
</blockquote></details>

Yeah, I think we have hit that point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Comment by klappy** [comment]
*[package-lock.json, line  at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301#-Kq8k6pGVoOuXhSuD6Jp:-Kq8nAEo6BxLePSG61DZ:b-yjvem1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/72f75fbe48b04d51e310c372475ca2b45382e2d0/package-lock.json#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Since this continues to be a problem, if we all use the same version of npm, it will minimize the differences. Right now 5.1.0 is required for builds.
Can you both use that version? `npm i -g npm@5.1.0`
</blockquote></details>

I reran this using npm 5.1.0 and get only what changed. Please upgrade/downgrade to 5.1.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Comment by klappy** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2301)*

**Pull request merged**
