### PR TITLE
Feature mcleanb 5911

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- switched tCore back from isomorphic-git to simple git for better performance.
- changed gulp build scripts to include git in windows builds.

#### Please include detailed Test instructions for your pull request:
- use test build at bottom of issue.
- uploads and downloads to door43 should still work.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5922)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Test  build 1c3e56c here:

http://tc-builds.door43.org.s3-website-us-west-2.amazonaws.com/build/release-v1.1.3-RC/

For example Mac build - https://tc-builds.door43.org/build/release-v1.1.3-RC/translationCore-macos-x64-1.1.3-1c3e56c.dmg

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 9 of 14 files at r1, 14 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5922)* status: 23 of 25 files reviewed, all discussions resolved

**Review by RoyalSix — APPROVED** [review]
> Reviewed 2 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5922)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by RoyalSix** [comment]
Not sure if this existed before but there is a problem when editing a project name and then choosing the "Create New Repo" option. The new repo is created but the content is not uploaded. 
If you manually go back and select "Upload to Door43" it works

**Review by PhotoNomad0 — COMMENTED** [review]
This has always been the case that we don't automatically push up to the new repo.  But that you see this is an improvement because rename of repos has been broken since we went to isomorphic-git.

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5922#-:-LaqMRfN7oEQFgB3S2SW:b1kiajh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — COMMENTED** [review]
Oops meant to say create new repo.

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5922#-:-LaqN4klESbQP08KRqFo:blaqsy1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by RoyalSix** [comment]
Ahh ok sounds good

**Pull request merged**
