### PR TITLE
Removing all text within footnotes (and other filtered markers)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adjusts the regex to capture all the text inclosing a filtered marker within a text.

#### How to test this pull request:
run ```npm update usfm-js```
Open a php project.
Open the tW tool. 
Look at the first check ```amen, truly``` ensure there is no text such as ```Some version keep Amen.``` in the scripture pane (This used to be here as text given from the footnote)
Try finding other examples of markers that have other text enclosed.
Related story is #1941

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3078)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@RoyalSix - I am still seeing "some versions add amen" on Phil 4:23

**Comment by RoyalSix** [comment]
@PhotoNomad0 You need to do ```npm update usfm-js```
Sorry forgot to mention this

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3078)*

**Comment by PhotoNomad0** [comment]
@RoyalSix - OK, tests fine now.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3078#-:-KyXXCeaR_e0LxwsxOx7:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
@mannycolon @RoyalSix  - not sure how to read the reviewable.  It is saying that for Manny all discussions are resolved, but it doesn't have the LGTM stamp.  So I am not sure if I should merge this.

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3078)*

**Pull request merged**
