### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5368)

### CODE REVIEW

**Comment by dsm-git** [comment]
Some builds failed

**Comment by dsm-git** [comment]
Some builds failed

**Comment by dsm-git** [comment]
Some builds failed

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5368)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (977ec9b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-977ec9b.deb) is ready for download.
[macOS build 1.1.0 (977ec9b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-977ec9b.dmg) is ready for download.
[Windows x64 build 1.1.0 (977ec9b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-977ec9b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (977ec9b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-977ec9b.setup.exe) is ready for download.

**Pull request merged**
