### PR TITLE
Fixed report generation in the build

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request fixes the issue with generating reports in the builds.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/56)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56)_

**Comment by ihoegen** [comment]
@elldoubleyew is this good to be merged in?

**Comment by RoyalSix** [comment]
> ih-fix-reports
> Hey Ian I tried pulling this branch to test it and I got an error from a require in index.html
> "out/css/styles.css"
> style.css doesn't exist there

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56#-:-KQNDryrni2whkEB6BcU:b96qhby)_

**Comment by ihoegen** [comment]
That's because in builds, our src is in out. I can switch it to src for development.

**Comment by RoyalSix** [comment]
Nice, pulled the branch again looks like you just need one more small change. Check below

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[index.html, line 21 [r3]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56#-KQNG9nsKB6l8cWHGPpm:-KQNG9nsKB6l8cWHGPpn:b37mgmp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/19851fd14df9a782ecd6e47a52fde81a6fbfc159/index.html#L21)):_

> ``` HTML
>     <script src="requirements.js"></script>
>     <script type="text/javascript">
>       require("./src/pages/index");
> ```

src/js*

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56#-:-KQNFyv8bnjPhnlFwVGV:b-3hq2h4)_

**Comment by RoyalSix** [comment]
One more thing...You need to merge with develop haha

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56#-:-KQNTGY6fs0l4bMuLJom:brv6c4f)_

**Comment by ihoegen** [comment]
@RoyalSix I gotchu

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/56)_

**Pull request merged**
