### PR TITLE
Now Copying translationHelps from Static folder to User Resources folder

### PR DESCRIPTION
**Pull request by mannycolon**
## This pull request addresses:
Now Copying translationHelps from Static folder to User Resources folder

## How to test this pull request:
- Make sure you delete the bibles from the user resources folder and then open tC.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1869)

### CODE REVIEW

**Comment by mannycolon** [comment]
@klappy @RoyalSix Now opening tC for the first time takes a long time and while the copying process is happening the user only sees a white screen. fI did not expect this to happened because I put this code in `componentDidMount()` which means it should render the interface and then run this process. But for some reason, it runs this process before it renders any UI which means the user sees a blank screen.

**Comment by klappy** [comment]
Is this worth trying to move it to it's own screen, kind of like the splash screen? 
Render splash screen everytime, then maybe a new screen that we can use for migrations could pop up between the first splash load and the app?

1) Splash Screen
2) Migration Screen
3) Application Screen

What do you think? @mannycolon @RoyalSix

**Comment by klappy** [comment]
@mannycolon: What would it take to send a loading alert before triggering the copy?

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1869)*

**Pull request merged**
