### PR TITLE
Enhancement mcleanb 5941

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- consolidate to single prompt when both alignments and selections are invalidated.
- batched group data actions so tools don't get continual notifications that properties are changing.
- updated WA to support a silent validation and fixed to return results.

#### Please include detailed Test instructions for your pull request:
- test with https://github.com/translationCoreApps/wordAlignment/pull/173
- import this USFM project [45-ACT.usfm3.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/3059172/45-ACT.usfm3.txt.zip)
- open tW tool, navigate to Apostles, and verse 1:2
- make selection `apostles` and click `save` and `save & continue` buttons
- open expanded scripture pane, and edit 1:2.  Modify word `apostles` and then click `Next`, select reason and click `save`.
- should momentarily see the Checking Prompt and then should see combined prompt for both alignments and selections invalidated.
- click OK and close  expanded scripture pane.
-  navigate to Apostles, and verse 1:25, select `apostleship` and `save`
- open WA tool, navigate to verse 1:25
- open expanded scripture pane, and edit 1:25.  Modify word `apostleship` and then click `Next`, select reason and click `save`.
- should momentarily see the Checking Prompt and then should see combined prompt for both alignments and selections invalidated.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (8425242)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-linux-x64-1.2.0-8425242.deb) is ready for download.
[macOS build 1.2.0 (8425242)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-macos-x64-1.2.0-8425242.dmg) is ready for download.
[Windows x64 build 1.2.0 (8425242)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x64-1.2.0-8425242.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (8425242)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x32-1.2.0-8425242.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4334758)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-linux-x64-1.2.0-4334758.deb) is ready for download.
[macOS build 1.2.0 (4334758)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-macos-x64-1.2.0-4334758.dmg) is ready for download.
[Windows x64 build 1.2.0 (4334758)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x64-1.2.0-4334758.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4334758)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x32-1.2.0-4334758.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (670a4ae)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-linux-x64-1.2.0-670a4ae.deb) is ready for download.
[macOS build 1.2.0 (670a4ae)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-macos-x64-1.2.0-670a4ae.dmg) is ready for download.
[Windows x64 build 1.2.0 (670a4ae)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x64-1.2.0-670a4ae.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (670a4ae)](https://tc-builds.door43.org/build/enhancement-mcleanb-5941/translationCore-win-x32-1.2.0-670a4ae.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/actions/VerseEditActions.js, line 225 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962#-LcCjhIz3A6X_Ib1pC7b:-LcCjhIz3A6X_Ib1pC7c:bo3j8mg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/670a4ae574217ced114196e77fe4dbf6cde6eff2/src/js/actions/VerseEditActions.js#L225)):*
> ```JavaScript
>       }
>     }
>     if (showSelectionInvalidated || showAlignmentsInvalidated) {
> ```

Should this be an `or` or `and` the message in the dialog says `and`

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/VerseEditActions.js, line 225 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5962#-LcCjhIz3A6X_Ib1pC7b:-LcDnf2L4eaHYTvIoSvD:bsbq6nr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/670a4ae574217ced114196e77fe4dbf6cde6eff2/src/js/actions/VerseEditActions.js#L225)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Should this be an `or` or `and` the message in the dialog says `and`
</blockquote></details>

This is correct, should be or.  If you look in the method the dialog can show one of three messages: alignments, selections, or both invalidated.

**Review by RoyalSix — APPROVED** [review]

**Pull request merged**
