### PR TITLE
QA Fail #3185/Fix USFM Export File Name

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- moved alignment name function to export helper to become a common file name function for USFM export and alignment export.

#### Please include detailed Test instructions for your pull request:
- when exporting to USFM or exporting alignment, should see filename in format such as `57-TIT.usfm`
- this only addresses the naming fix.  Line breaks are fixed in https://github.com/unfoldingWord-dev/translationCore/pull/3868

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3872)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3872)*

**Comment by RoyalSix** [comment]
@PhotoNomad0 Everything looks good, and tests passing according to PR requirements in the notes.
But I found that the [issue](https://github.com/unfoldingword-dev/translationcore/issues/3185#issuecomment-366000166) also called for fixed line breaks (on ea verse) 
```
Line breaks need to be added back into the USFM2 exports as was previously the case. Line break on each verse, chapter marker, etc. as in https://git.door43.org/Door43/en_ulb
```
Should this be included in this PR or is this a separate story?

**Comment by RoyalSix** [comment]
Project used @PhotoNomad0 
[bfz_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1738384/bfz_tit.zip)

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3872#-:-L5kWpZLjeOTf0PAeVY7:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3872)*

**Pull request merged**
