### PR TITLE
Fixes QA bugs

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- moves documentation publishing into the `before_script` so it only runs once. Also, limited publishing to the `develop` branch.
- limited publishing locale to crowdin to the `develop` branch.
- fixed style inconsistencies described in #3750 
- removed second dialog when submitting feedback, see  #2963. The user email is now used as the user name as needed.

#### Please include detailed Test instructions for your pull request:
- no special instructions.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4049)

### CODE REVIEW

**Comment by RoyalSix** [comment]
How do I test this? @neutrinog

**Comment by RoyalSix** [comment]
You might want to merge with the latest

**Comment by mannycolon** [comment]
Reviewed 5 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4049)*

**Comment by mannycolon** [comment]
`Code:` LGTM

**Comment by PhotoNomad0** [comment]
LGTM

**Pull request merged**
