### PR TITLE
Add a brand new view for projects.

### PR DESCRIPTION
**Pull request by ihoegen**
`npm install` required.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/554)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/SideBar/GitSync.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554#-KbNUFQZ9CvTWJCAmcRn:-KbNUFQZ9CvTWJCAmcRo:b3d4z3t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/97eaa83781920810a70b408932779dc5416ec8b0/src/js/components/core/SideBar/GitSync.js#L16)):*
> feature/ih-projects
console log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/SideBar/GitSync.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554#-KbNUFQZ9CvTWJCAmcRn:-KbNjaBu-Z1FHewcpR4C:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/97eaa83781920810a70b408932779dc5416ec8b0/src/js/components/core/SideBar/GitSync.js#L16)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

> feature/ih-projects
console log
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/554)*

**Pull request merged**
