### PR TITLE
Fixed project reimport bug that used to overwrite the old projects manifest

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
1. Import a USFM project. I used this one. [62-2PE.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3392555/62-2PE.usfm.zip)
2. Load the project in tN
3. Export the project to USFM without alignments
4. Import the exported project choosing the Overwrite options on the alerts
5. Attempt to load the project tN
6. It should open again without any issues.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6257)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-linux-x64-2.0.0-7f79862.deb) is ready for download.
[macOS build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-macos-x64-2.0.0-7f79862.dmg) is ready for download.
[Windows x64 build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x64-2.0.0-7f79862.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x32-2.0.0-7f79862.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-linux-x64-2.0.0-7f79862.deb) is ready for download.
[macOS build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-macos-x64-2.0.0-7f79862.dmg) is ready for download.
[Windows x64 build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x64-2.0.0-7f79862.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (7f79862)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x32-2.0.0-7f79862.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6257)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/helpers/ProjectOverwriteHelpers.js, line 58 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6257#-Lk0hAQrEUA6O_SMScTU:-Lk0hAQrEUA6O_SMScTV:b-mh1ag2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7f7986283b2f179d40f6a118834101b44501cbb1/src/js/helpers/ProjectOverwriteHelpers.js#L58)):*
> ```JavaScript
>     newManifest.translators = newManifest.translators.filter(translator => !oldManifest.translators.includes(translator));
>     const mergedManifest = {
>       "mergedManifest": "hello",
> ```

Did you forget to remove this?

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a3207cd)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-linux-x64-2.0.0-a3207cd.deb) is ready for download.
[macOS build 2.0.0 (a3207cd)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-macos-x64-2.0.0-a3207cd.dmg) is ready for download.
[Windows x64 build 2.0.0 (a3207cd)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x64-2.0.0-a3207cd.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a3207cd)](https://tc-builds.door43.org/build/bugfix-mannycolon-6168/translationCore-win-x32-2.0.0-a3207cd.setup.exe) is ready for download.

**Pull request merged**
