### PR TITLE
Added Unit Tests

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This adds unit tests for BodyUIActions and TargetLanguageActions.

#### How to test this pull request:

Tests should pass and code coverage should increase.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2960)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2960)*

**Comment by mannycolon** [comment]
@neutrinog Looks good just resolve merge conflicts and pin me on slack so I can merge your Pull request.

**Comment by RoyalSix** [comment]
I got the following errors after running npm test
screen shot 2017-10-17 at 8 07 20 pm
screen shot 2017-10-17 at 8 07 06 pm
screen shot 2017-10-17 at 8 06 54 pm

**Comment by da1nerd** [comment]
@RoyalSix could you run `npm install` and try again?

**Comment by RoyalSix** [comment]
@neutrinog I got the same result

**Comment by RoyalSix** [comment]
@neutrinog I got the same result, but its passing on Travis so it might be fine

**Comment by RoyalSix** [comment]
Reviewed 7 of 10 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/TargetLanguageActions.js, line 59 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2960#-Kwk3D1rcT4UNT4zkHAz:-Kwk3D1rcT4UNT4zkHB-:bw7sqjw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fae585a7baf5eadb22df5571018e2dcd7f8ba8/src/js/actions/TargetLanguageActions.js#L59)):*
> ```JavaScript
>     });
>    });
>   console.log(targetBible);
> ```

Should this be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2960)*

**Comment by mannycolon** [comment]
@neutrinog ^^

**Comment by da1nerd** [comment]
@RoyalSix nope! that shouldn't be there. That's left over from debugging :P

**Comment by da1nerd** [comment]
@RoyalSix and @mannycolon what OS' are you guys working on?

**Comment by mannycolon** [comment]
@neutrinog I'm using macOS Sierra

**Comment by RoyalSix** [comment]
Same OSX. 
I tried making the build using <code>npm run make</code>
And got a white screen
Going to try again, it be something on my end

**Comment by da1nerd** [comment]
I just whipped out my mac and ran the tests on OSX El Capitan. All the tests passed. This makes it hard to debug :-/

**Comment by da1nerd** [comment]
@RoyalSix @mannycolon I updated the console log output to include the path where it's expecting the manifest (in ResourceHelpers). Could you run it again check where it thinks it is?

**Comment by RoyalSix** [comment]
@neutrinog Hey sorry I made that comment on the wrong PR about the build...but I will try ```npm test``` again 👍

**Comment by RoyalSix** [comment]
I just got one error on my local machine :/
screen shot 2017-10-20 at 10 35 35 pm
but the build works

**Comment by da1nerd** [comment]
@RoyalSix perfect! that error you shared looks like it's just a timeout. Which is subjective to the computer the tests are running on. I increased the timeout so the test "should" now pass on your computer.

Generally speaking, increasing timeouts is a  hack. It would be better to mock simple-git and not hit the network, but I'd like to be sure this is the only issue.

**Comment by da1nerd** [comment]
Ok, I did end up re-writing the git tests. `simple-git` is now mocked so that we are only testing our wrapper around it (`GitApi`) not the functionality provided by `simple-git` itself.

I should do the same for some other network heavy tests, but one step at a time :)

**Comment by RoyalSix** [comment]
Looks like you forgot to save the package ```ncp``` for the targetLanguageActions test...
I added and I'm going to merge

**Pull request merged**
