### PR TITLE
Bugfix 6145/Preserve old grc and el-x-koine bibles needed by tN on upgrade

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Preserve old needed ugnt versions in grc and el-x-koine needed by tN on upgrade.

#### Please include detailed Test instructions for your pull request:
- in issue https://github.com/unfoldingword-dev/translationcore/issues/6145, Look at QA fail issues #2 and #3 
  - for issue #2: install v1.1.4, and unzip [tisch.zip](https://github.com/unfoldingWord-dev/translationCore/files/3352023/tisch.zip) into grc/bibles folder.  Then run 2.0.0 build at bottom and make sure that the grc folder is removed and make sure that tisch (Tischendorf Greek New Testament) can be added to scripture pane  in the tools.
  - for issue #3: Close tCore.  Then edit a project manifest and change `tsv_relation` line "el-x-koine/ugnt?v=0.8" to "el-x-koine/ugnt?v=0.7" and save changes.  Launch tCore and Open previous project and click tN launch.  Should see prompt: `The current tool requires a different version of the UGNT. Please click Download to retrieve this resource.`  Click download and should see ugnt `v0.7` added in resources.  Exit tCore.  Change manifest in hi tN (e.g.  ⁨resource/⁨hi⁩/translationHelps/translationNotes⁩/v13.6/manifest.json), change `dublin_core.relation` line "el-x-koine/ugnt?v=0.8" to "el-x-koine/ugnt?v=0.7" and save changes.  Then in resource folder `el-x-koine\⁨bibles\⁨ugnt` delete folder ⁨`v0.8⁩`.  Start tCore and wait for the `Get Started Button`.  Check resources and make sure that ugnt `v0.8⁩` was restored and that `v0.7` was kept, and that `tisch` is still in `el-x-koine\⁨bibles`.
- testing is now done, but you should delete `⁨resource/⁨hi⁩/translationHelps/translationNotes⁩` so that it will be restored.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6241)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (3ba5b40)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-linux-x64-1.2.0-3ba5b40.deb) is ready for download.
[macOS build 1.2.0 (3ba5b40)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-macos-x64-1.2.0-3ba5b40.dmg) is ready for download.
[Windows x64 build 1.2.0 (3ba5b40)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x64-1.2.0-3ba5b40.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (3ba5b40)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x32-1.2.0-3ba5b40.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0d12563)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-linux-x64-1.2.0-0d12563.deb) is ready for download.
[macOS build 1.2.0 (0d12563)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-macos-x64-1.2.0-0d12563.dmg) is ready for download.
[Windows x64 build 1.2.0 (0d12563)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x64-1.2.0-0d12563.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0d12563)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x32-1.2.0-0d12563.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (aa52444)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-linux-x64-1.2.0-aa52444.deb) is ready for download.
[macOS build 1.2.0 (aa52444)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-macos-x64-1.2.0-aa52444.dmg) is ready for download.
[Windows x64 build 1.2.0 (aa52444)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x64-1.2.0-aa52444.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (aa52444)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x32-1.2.0-aa52444.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (83caed7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-linux-x64-2.0.0-83caed7.deb) is ready for download.
[macOS build 2.0.0 (83caed7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-macos-x64-2.0.0-83caed7.dmg) is ready for download.
[Windows x64 build 2.0.0 (83caed7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x64-2.0.0-83caed7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (83caed7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x32-2.0.0-83caed7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (0e0f926)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-linux-x64-2.0.0-0e0f926.deb) is ready for download.
[macOS build 2.0.0 (0e0f926)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-macos-x64-2.0.0-0e0f926.dmg) is ready for download.
[Windows x64 build 2.0.0 (0e0f926)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x64-2.0.0-0e0f926.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (0e0f926)](https://tc-builds.door43.org/build/bugfix-mcleanb-6145/translationCore-win-x32-2.0.0-0e0f926.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 7 files at r2, 2 of 4 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6241#-:-LkZYN-nBUuHtUWKsRCq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
