### PR TITLE
Added an 'n' to traslation

### PR DESCRIPTION
**Pull request by bspidel**
#### This pull request addresses:

Single letter change

#### How to test this pull request:
Visual Inspection
1 run tC
2 visually inspect footer on several pages and verify correct spelling of translation

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3141)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tC_apps/translationWords, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141#-KyaVLI-P4tzp_qs9_5Z:-KyaVLI-P4tzp_qs9_5_:bt9a95j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a374b80cd71c3b717a6cfeda52788993009ede24/tC_apps/translationWords#L1)):*
> ```
> Subproject commit a27f3b79fb72e384bbdebcbde1c6c58fbe142c48
> ```

It looks like you committed a change to `tC_apps/translationWords`.  I don't think you should have done that.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141)*

**Comment by klappy** [comment]
*[tC_apps/translationWords, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141#-KyaVLI-P4tzp_qs9_5Z:-KyblWbv0ZnGHK4l6NS8:b66ki6c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a374b80cd71c3b717a6cfeda52788993009ede24/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

It looks like you committed a change to `tC_apps/translationWords`.  I don't think you should have done that.  
</blockquote></details>

@bspidel: If you can run `npm run update-apps`, it should update to what would match on develop branch. Commit that revision and it would essentially be like undoing the accidental commit. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141)*

**Comment by klappy** [comment]
@bspidel: Looks good. It appears you ran into the same problem I do all the time, accidentally committing a change in one of the git submodules. It happens all the time. Let me know if you need help getting around it :)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141#-:-KybmRuYbWbT2BtZqt34:b-nvk4er)*

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3141#-:-Kyh-FolJYOSz40JoxEZ:bnfp4nl)*

**Pull request merged**
