### PR TITLE
improved Loader modal to show progress and a spinning logo

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses: The missing verbiage and progress bar during the load of a project/tool.

#1176 
- modified the progress action for tN #55
https://github.com/translationCoreApps/translationNotes_Check_plugin/pull/55
- modified the progress action for tW #79
https://github.com/translationCoreApps/translationWords_Check_plugin/pull/79

#### How to test this pull request:
- Before testing pull the branch **bugfix/mc-1176** from both tW & tN.
- Try loading a project with both tools.

**ps. The loading modal will work better once we move the fetch data process out of componentWillMount() from the tools.**

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1293)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KihqC-Bpql6ba4j8cu6:b6m2zk1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
> ```JavaScript
>     let biblesProgress = Bibles ? parseInt(Bibles.progress, 10) : 0;
>     let tProgress = 0;
>     if (translationWords) {
> ```

This does not seem very modular. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by ihoegen** [comment]
@mannycolon When switching from one tool to the next, the progress appears to start at 100%. 
image

**Comment by klappy** [comment]
*[src/js/reducers/loaderReducer.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kij9udCO43CdOddC9SF:-Kij9udCO43CdOddC9SG:b-8f8w63) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/reducers/loaderReducer.js#L27)):*
> ```JavaScript
>       return {
>         ...state,
>         progress: 0,
> ```

In theory this should  take care of the 100% during the next load. I'm confused as to why it would still happen, unless this isn't called at the end of the previous load?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/reducers/loaderReducer.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kij9udCO43CdOddC9SF:-KijCMW62fIgdsrQWEcN:b7h3qbp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/reducers/loaderReducer.js#L27)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

In theory this should  take care of the 100% during the next load. I'm confused as to why it would still happen, unless this isn't called at the end of the previous load?
</blockquote></details>

Nvm, I found it in the container of each project chained to fetchdata with a promise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KijC_YJO3nDEHEF0bf6:bu960yz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

This does not seem very modular. 
</blockquote></details>

Ideally, anything tool specific is done there, and send an appropriate value back via callback if this function does anything for it. 

Also, could a single tool loading/progress namespace be used in the reducer? Was this added in attempt to separate the two from stomping on their prior progress? I'm not sure why we need one for each tool if that wasn't the reason? This should be an app concern of whether or not it loaded the current tool, and the current tool can check whether or not it completed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
I don't see a dispatch for DONE_LOADING, that should be fired after the loading of each tool. I see that the code exists to reset it to 0%, but not where it's called.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KijC47EpZyhN1D3eX-0:b-2yhmzp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
> ```JavaScript
>                                 allGroupsObjects[groupName] = groupObj;
>                                 setTimeout(() => {
>                                     dispatch(LoaderActions.sendProgressForKey("translationWords", i / total * 100));
> ```

Should this be in the Core? This is a specific action for one tool? 

Also, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-:-Kij9SQpJ9NliNZspn9Z:b-n927bz)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KijxC0dnFvLoL9RRksp:b-l02n1n) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should this be in the Core? This is a specific action for one tool? 

Also, 
</blockquote></details>

what do you mean klappy??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KikK-5SEockXuwqeo8x:bna9czg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what do you mean klappy??
</blockquote></details>

this happens when the fetch data doesn't run therefore we still need progress to show up.

---

*[src/js/reducers/loaderReducer.js, line 27 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kij9udCO43CdOddC9SF:-KikJuOjAWDseP3xjvRc:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/reducers/loaderReducer.js#L27)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Nvm, I found it in the container of each project chained to fetchdata with a promise.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KiqsJxC_CQnc-PNOOQr:bmnb01i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this happens when the fetch data doesn't run therefore we still need progress to show up.
</blockquote></details>

I was wondering if long term, we could look at not using tool specific keys. But it's okay for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KiqsXraO88Vr5jdd7H5:bj5lqya) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I was wondering if long term, we could look at not using tool specific keys. But it's okay for now.
</blockquote></details>

Should we leave the log here for short term debugging?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 12 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kiqu0foMkxHIPFvSsp2:-Kiqu0fp709nyhzRuHTH:b-a0uzf1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/components/core/Loader.js#L12)):*
> ```JavaScript
>     let progressCircle = [];
>     for (var toolName in toolsProgress) {
>       let progress = toolsProgress[toolName] ? parseInt(toolsProgress[toolName].progress, 10) : 0;
> ```

I replaced this with the following replaced NaN with 0:
       
`let progress = toolsProgress[toolName] && toolsProgress[toolName].progress ? parseInt(toolsProgress[toolName].progress, 10) : 0;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 12 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kiqu0foMkxHIPFvSsp2:-KiqvSSp3nJQITgfl1KY:b1pbqgt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/components/core/Loader.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I replaced this with the following replaced NaN with 0:
       
`let progress = toolsProgress[toolName] && toolsProgress[toolName].progress ? parseInt(toolsProgress[toolName].progress, 10) : 0;`

</blockquote></details>

Wrapping this whole block of code that populates the progressCircle, with a condition for the data to exists, fixes the NaN and ending with 0, by not rendering it.

`if (toolsProgress[toolName] && toolsProgress[toolName].progress) {
   ...
}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/reducers/loaderReducer.js, line 29 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KiqsyiFKXUX4PxIENVh:-KiqsyiGvqtHWaq-If_U:bhgr6oo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/reducers/loaderReducer.js#L29)):*
> ```JavaScript
>       return {
>         ...state,
>         show: false
> ```

Could the NaN rendering be due to removing progress: 0? I'm 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KiqvjWBROA8JweBhfU-:b-howx0h) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should we leave the log here for short term debugging?
</blockquote></details>

i forgot to replaced the this string name from here from here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KiqyD6Ar0oCxoQXVDbv:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Ideally, anything tool specific is done there, and send an appropriate value back via callback if this function does anything for it. 

Also, could a single tool loading/progress namespace be used in the reducer? Was this added in attempt to separate the two from stomping on their prior progress? I'm not sure why we need one for each tool if that wasn't the reason? This should be an app concern of whether or not it loaded the current tool, and the current tool can check whether or not it completed.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by mannycolon** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KiqxwqSuo8yzuPaAseE:b-z1wuc8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Ideally, anything tool specific is done there, and send an appropriate value back via callback if this function does anything for it. 

Also, could a single tool loading/progress namespace be used in the reducer? Was this added in attempt to separate the two from stomping on their prior progress? I'm not sure why we need one for each tool if that wasn't the reason? This should be an app concern of whether or not it loaded the current tool, and the current tool can check whether or not it completed.
</blockquote></details>

I don't understand your question klappy. what are you referring to?


it wasnt modular before but now it should be very modular.

---

*[src/js/components/core/Loader.js, line 12 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kiqu0foMkxHIPFvSsp2:-Kiqxvidw_oybO9oDA18:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/components/core/Loader.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Wrapping this whole block of code that populates the progressCircle, with a condition for the data to exists, fixes the NaN and ending with 0, by not rendering it.

`if (toolsProgress[toolName] && toolsProgress[toolName].progress) {
   ...
}`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 12 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kiqu0foMkxHIPFvSsp2:-KiqyFO7rkTgYy0dLulb:b-85ib5p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/components/core/Loader.js#L12)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGMT

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by mannycolon** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/reducers/loaderReducer.js, line 29 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KiqsyiFKXUX4PxIENVh:-KiqyHiZa6T0gWwV-dLb:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/reducers/loaderReducer.js#L29)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Could the NaN rendering be due to removing progress: 0? I'm 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KiqyNdYNamN8mT2sWbP:b-vu1k6p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I don't understand your question klappy. what are you referring to?


it wasnt modular before but now it should be very modular.
</blockquote></details>

The question is before you made it so modular, it addressed my concerns :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by mannycolon** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-KiqyansEGWVO0X8921l:by71xsa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The question is before you made it so modular, it addressed my concerns :D
</blockquote></details>

ok i just wasnt sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-:-KiqygcXxei7GQyYjlTf:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-KiqyjnJfuUdCHRoYvAR:bjdqvng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i forgot to replaced the this string name from here from here
</blockquote></details>

Okay, it works much better now :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 308 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KijC47EpZyhN1D3eX--:-Kir1B9qG__v9GoP-8cv:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/actions/GetDataActions.js#L308)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Okay, it works much better now :)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 12 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-Kiqu0foMkxHIPFvSsp2:-Kir1DrJF_bq0FInXS_S:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f2fa6d9a692c1e1cb26e9a05dd189143952df4c8/src/js/components/core/Loader.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

LGMT
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Comment by klappy** [comment]
*[src/js/components/core/Loader.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293#-KihqC-Bpql6ba4j8cu5:-Kir1GVijwDzbzMbz6ru:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/80c40148f151499cc794c45e76a645acb387f7b0/src/js/components/core/Loader.js#L13)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ok i just wasnt sure.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1293)*

**Pull request merged**
