### PR TITLE
Invalidate Selections if occurrences don't match current count.

### PR DESCRIPTION
**Pull request by klappy**
## This PR addresses:
Invalidate Selections if occurrences don't match current count. It alerts the user so that they know their edit invalidated the selection that was previously made.

## To test:
Checkout branch of the same name in VerseCheck where the action is called when rendering the text it validates to see if the selections are still valid. 

## TODO: 
Find a common place to check for this validation so that it doesn’t happen deep in the tool but somewhere at a higher level.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1096)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1096#-:-Ki0FD0lEIICBS4kR1Iy:bnfp4nl)*

**Comment by EllDoubleYew** [comment]
Tested and confirmed to work. I don't think it is quite up to develop though. Have you merged with the latest @klappy ?

**Comment by klappy** [comment]
Merging with develop now...

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/js/helpers/selectionHelpers.js, line 30 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1096#-Ki0KXo9ZHbcRfxmwBpE:-Ki0KXo9ZHbcRfxmwBpF:bf414u1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36451e33f2ab4945726e64f8fbb6f1cd172c2dc0/src/js/helpers/selectionHelpers.js#L30)):*
> ```JavaScript
> export const checkSelectionOccurrences = (string, selections) => {
>   selections = selections.filter( selection => {
>     let count = module.exports.occurrences(string, selection.text)
> ```

Hey coukd you try using  export default instead. However i dont think you have to edport it since it is in the same file/context  you can just call it occurences ()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1096)*

**Comment by klappy** [comment]
*[src/js/helpers/selectionHelpers.js, line 30 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1096#-Ki0KXo9ZHbcRfxmwBpE:-Ki0OGcK3W_IT5nHi13X:btyeq5o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36451e33f2ab4945726e64f8fbb6f1cd172c2dc0/src/js/helpers/selectionHelpers.js#L30)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Hey coukd you try using  export default instead. However i dont think you have to edport it since it is in the same file/context  you can just call it occurences ()
</blockquote></details>

Good thinking. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1096)*

**Pull request merged**
