### PR TITLE
Js hebrew

### PR DESCRIPTION
**Pull request by RoyalSix**
You can use any OT book, here are a few:
https://git.door43.org/streeterj/bni_exo_text_reg.git
https://git.door43.org/48E244884475/uw-gen-te.git
https://git.door43.org/qa2/en-x-demo1_jud_text_reg.git

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/212)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 48 files at r1, 42 of 50 files at r2, 14 of 20 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[hebrew.js, line 196 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTuPCoGa_2QhlaXdgbG:-KTuPCoH0gKTk_kUCOwi:b-qq6rgk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c87c8a1c446fcea5a950a166062554d76c9e5dc/hebrew.js#L196)):_

> ``` JavaScript
>       $.get( '../morphhb/wlc/' + bookFile, function( data ) {
>           var json = this.xmlToJson( data ).osis.osisText.div.chapter;
>           hebrew[ bookName ] = this.jsonToArray( json );
> ```

maybe get rid of the tabs

---

_[morph.js, line 4 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY6vMKFjZAYmq7Lnr:-KTvY6vMKFjZAYmq7Lns:bb7ozr7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L4)):_

> ``` JavaScript
> var MorphParse = function()
> {
>   var language;
> ```

tabs

---

_[morph.js, line 13 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY5zhi76QGgYE7WMA:-KTvY5zhi76QGgYE7WMB:bb7ozr7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L13)):_

> ``` JavaScript
>     (function(code)
>     {
>       language = code.charAt(0);
> ```

tabs

---

_[morph.js, line 109 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY9T2NElkJi0A7Nfz:-KTvY9T2NElkJi0A7Ng-:bb7ozr7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L109)):_

> ``` JavaScript
>         var morph;
>       if (language === 'H') {
>           morph = morphCodes.verbStemHebrew[code.charAt(1)];
> ```

tabs

---

_[morphCodes.js, line 6 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvYC2XelFmp7SWdJg7:-KTvYC2XelFmp7SWdJg8:bb7ozr7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morphCodes.js#L6)):_

> ``` JavaScript
>       'C': 'Conjunction',
>       'D': 'Adverb',
>       'N': 'Noun',
> ```

tabs

---

_[modules/translation_academy/FetchData.js, line 34 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvYYSx-x1NqoxcjiPc:-KTvYYSx-x1NqoxcjiPd:bb7ozr7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/modules/translation_academy/FetchData.js#L34)):_

> ``` JavaScript
>   // When all sections are fetched, put them in CheckStore and call the callback
>   try {
>           Promise.all(promises).then(value => {
> ```

tabs

---

_[modules/translationNotes_Check_plugin/View.js, line 83 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvYeJB0dPfRL7ikTSP:-KTvYeJCoWhOhQcmrpkJ:b-jg6ewz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/modules/translationNotes_Check_plugin/View.js#L83)):_

> ``` JavaScript
>     api.removeEventListener('goToPrevious', this.goToPreviousListener);
>     api.removeEventListener('goToCheck', this.goToCheckListener);
>     api.removeEventListener('changeCheckType', this.changeCheckTypeListener);
> ```

nice catch

---

_[modules/translationWords_Check_plugin/View.js, line 316 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvYlshwHnhEIvBdbdR:-KTvYlshwHnhEIvBdbdS:b-n6nc1z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/modules/translationWords_Check_plugin/View.js#L316)):_

> ``` JavaScript
>     }
>     } catch(e){
> ```

so nothing will happen after catching the error?

---

_[src/js/pages/app.js, line 28 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvZ8FQbIsuo22YprF_:-KTvZ8FQbIsuo22YprFa:b5fysmu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/src/js/pages/app.js#L28)):_

> ``` JavaScript
> const Popover = require('../components/core/Popover');
> const Upload = require('../components/core/Upload');
> //const parse = require("../../../hebrew.js");
> ```

will we need this at all at some point or should we just ret rid of the commented code?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by mannycolon** [comment]
@RoyalSix so just take a look at the comments I left. Im testing the branch now

**Comment by mannycolon** [comment]
@RoyalSix theres no bugs but I think the Tpane is rendering the verse incorrectly

**Comment by mannycolon** [comment]
screen shot 2016-10-12 at 9 38 11 pm

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by mannycolon** [comment]
@RoyalSix just take a look at the comments i left and then this branch should be ready to be merged

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[modules/translationWords_Check_plugin/View.js, line 316 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvYlshwHnhEIvBdbdR:-KTylvU1v_7X7_mrZ8RC:b-gsewto) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/modules/translationWords_Check_plugin/View.js#L316)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> so nothing will happen after catching the error?
> </details>
> going to change this

---

_[src/js/pages/app.js, line 28 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvZ8FQbIsuo22YprF_:-KTylzI5wVF0nvO1mt_A:bhmaogj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/src/js/pages/app.js#L28)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> will we need this at all at some point or should we just ret rid of the commented code?
> </details>
> This would be used in a case where we had to remake the Hebrew parsing, I can delete it, we shouldn't have to do that at least for a while.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by mannycolon** [comment]
Reviewed 12 of 12 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by mannycolon** [comment]
Reviewed 11 of 14 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/Usfm/ImportUSFM.js, line 139 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KU0dLIVBKnFNlMyTC3G:-KU0dLIVBKnFNlMyTC3H:b5mayy6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f6711dc97b113846dc639c79ea92811f7ec5e030/src/js/components/core/Usfm/ImportUSFM.js#L139)):_

> ``` JavaScript
>  ******************************************************************************/
>  function loadProject(saveLocation) {
>    debugger;
> ```

do you still need the debugger?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by RoyalSix** [comment]
Review status: 60 of 61 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[hebrew.js, line 196 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTuPCoGa_2QhlaXdgbG:-KU0e_q2_O4jrUoJalF6:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c87c8a1c446fcea5a950a166062554d76c9e5dc/hebrew.js#L196)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> maybe get rid of the tabs
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by RoyalSix** [comment]
Review status: 60 of 61 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[morph.js, line 4 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY6vMKFjZAYmq7Lnr:-KU0ebJQzLAgXptRanMG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L4)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[morph.js, line 13 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY5zhi76QGgYE7WMA:-KU0ebkkQM1VGa2De2gh:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L13)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_[morph.js, line 109 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KTvY9T2NElkJi0A7Nfz:-KU0ec4r0SRUUWBHxh_-:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c8b3561830753e692f4fa4ca647f72e2b2e894b3/morph.js#L109)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> tabs
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by RoyalSix** [comment]
Review status: 60 of 61 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/js/components/core/Usfm/ImportUSFM.js, line 139 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KU0dLIVBKnFNlMyTC3G:-KU0edKu_NuFN8HqJTZx:b2ni8ds) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f6711dc97b113846dc639c79ea92811f7ec5e030/src/js/components/core/Usfm/ImportUSFM.js#L139)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> do you still need the debugger?
> </details>
> nah

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/Usfm/ImportUSFM.js, line 139 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212#-KU0dLIVBKnFNlMyTC3G:-KU0fMMfpQ--nyWqJsfy:b-xv72og) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f6711dc97b113846dc639c79ea92811f7ec5e030/src/js/components/core/Usfm/ImportUSFM.js#L139)):_
<details><summary>

<i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary>



> nah
> </details>
> ok just need to remove the last debugger and then we merge

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/212)_

**Pull request merged**
