### PR TITLE
Feature/add tc version to manifest

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: https://github.com/unfoldingWord-dev/translationCore/issues/3322
Also fixes ts version 3 manifest migration: #3366

#### How to test this pull request:

Either do local import of tstudio project or online import of bible project.  After import manifest.json file should have tc_version entry of 1. 

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3367)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 45 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-L-mO1QLeLOI5Ook6Kg3:-L-mO1QMsRVHWa5Cr9wG:b-tjwi4w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4584153558643b6fe78a933f9913ca7afc776020/src/js/actions/Import/LocalImportWorkflowActions.js#L45)):*
> ```JavaScript
>       FileConversionHelpers.convert(sourceProjectPath, selectedProjectFilename);
>       const importProjectPath = path.join(IMPORTS_PATH, selectedProjectFilename);
>       convertManifestForTc(importProjectPath);
> ```

Please move this method to  ProjectMigrationActions.migrate()

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 103 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-L-mO9XF-qu0lFbx0rjc:-L-mO9XF-qu0lFbx0rjd:b9orsb3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4584153558643b6fe78a933f9913ca7afc776020/src/js/actions/Import/LocalImportWorkflowActions.js#L103)):*
> ```JavaScript
>  * @param importProjectPath
>  */
> export const convertManifestForTc = (importProjectPath) => {
> ```

move this to migrations actions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367)*

**Comment by PhotoNomad0** [comment]
@mannycolon - since the import refactor has now been merged into develop, I think this needs to be changed to a PR against develop.

**Comment by mannycolon** [comment]
@PhotoNomad0 I agree

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 5 of 75 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-:-L06lizISYJsBrUMzaEr:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 75 files at r2, 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[__tests__/ImportMigrationHelpers.test.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-L07J7U3yj4MZDKoA7PT:-L07J7U3yj4MZDKoA7PU:b-rkupb7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a963b019149b3fa04e60f2a79e3866234d2e6cef/__tests__/ImportMigrationHelpers.test.js#L8)):*
> ```JavaScript
> 'use strict';
> import migrateAppsToDotApps from '../src/js/helpers/ProjectMigration/migrateAppsToDotApps';
> import migrateToVersion1 from "../src/js/helpers/ProjectMigration/migrateToVersion1";
> ```

Should this always be the latests version and not version 1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367)*

**Comment by mannycolon** [comment]
Reviewed 4 of 75 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/ImportMigrationHelpers.test.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-L07J7U3yj4MZDKoA7PT:-L085_DbOn3f6BiV2EP7:b-cstnkg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a963b019149b3fa04e60f2a79e3866234d2e6cef/__tests__/ImportMigrationHelpers.test.js#L8)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Should this always be the latests version and not version 1?
</blockquote></details>

I agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/ImportMigrationHelpers.test.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367#-L07J7U3yj4MZDKoA7PT:-L0AaSTVo1PbDA5y-jee:b-jytawk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a963b019149b3fa04e60f2a79e3866234d2e6cef/__tests__/ImportMigrationHelpers.test.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Actually no.  We need to write a new migration function for each new manifest version.  And the migration function for version 1 should not change after this is released.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3367)*

**Pull request merged**
