### PR TITLE
added ci-test script

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- this is a one liner that simply adds an additional test script for use in ci.

#### Please include detailed Test instructions for your pull request:
- nothin'.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4558)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (a5ab173)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-a5ab173.zip) is ready for download.
[macOS build 0.10.0 (a5ab173)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-a5ab173.dmg) is ready for download.
[Windows x64 build 0.10.0 (a5ab173)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-a5ab173.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (a5ab173)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-a5ab173.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (7083e80)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7083e80.zip) is ready for download.
[macOS build 0.10.0 (7083e80)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7083e80.dmg) is ready for download.
[Windows x64 build 0.10.0 (7083e80)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-7083e80.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (7083e80)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-7083e80.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
closing this so I can test some codecov stuff.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (b1e88e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-b1e88e2.zip) is ready for download.
[macOS build 0.10.0 (b1e88e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-b1e88e2.dmg) is ready for download.
[Windows x64 build 0.10.0 (b1e88e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-b1e88e2.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (b1e88e2)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-b1e88e2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-1030ec7.zip) is ready for download.
[macOS build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-1030ec7.dmg) is ready for download.
[Windows x64 build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-1030ec7.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-1030ec7.setup.exe) is ready for download.

**Pull request closed without merging**
