### PR TITLE
AlignmentData save/load to fs

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

- Data persistence for alignmentData.
  - saves to `.apps/translationCore/alignmentData/[chapter].json`
  - loads from filesystem if exists
  - generates alignmentData if isn't in fs
    - generates at verse level for maintainability and future needs
    - empty alignments from bhp
    - wordBank from the targetLanguage

Helpers and tests to pivot alignmentData to targetLanguageVerse and back, to be used in the future for import/export to USFM 3.

#### How to test this pull request:

- Review Tests and use cases covered.
- `npm test` to ensure all tests pass
- Open any Titus project and start aligning random verses.
- Reload app and ensure that it loads the alignment data by prepopulating the UI.

- Known issues
  - There is a strange bug when clicking the top menu to switch tools and clicking on the Word Alignment tool again. It does work if you switch projects, just not tools to the same tool.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2822)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 94 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822#-KvYU-9zgjybcL9scLer:-KvYU-A-1v974k7yUn0U:bgekxf7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1078f65a5d9dadde6113cbcae3112c1dda577bf4/src/js/helpers/WordAlignmentHelpers.js#L94)):*
> ```JavaScript
>   });
>   _wordObjectArray = _wordObjectArray.sort((a, b) => {
>     return a.index - b.index;
> ```

What does a minus do instead of a less than ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822)*

**Comment by RoyalSix** [comment]
Code looks good. Checking out the branch

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822#-:-KvYjp_1eA5KIMBg7LVK:b-3c4an4)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822#-:-KvYjuf2xv_5f2FkmCuz:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 11 of 11 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/utils/localStorage.js, line 71 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822#-KvbjLP0zd9OTR-wYlLL:-KvbjLP0zd9OTR-wYlLM:b-6k0597) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2d13d2380cacf6ccea95aa34f0c0212979aeccef/src/js/utils/localStorage.js#L71)):*
> ```JavaScript
>       const alignmentDataHasData = (alignmentData && Object.keys(alignmentData).length > 0);
>       if (alignmentDataHasData && !isEqual(prevState.wordAlignmentReducer.alignmentData, alignmentData)) {
>         saveAlignmentData(newState);
> ```

are you saving the data in a different format? in other words in the usfm 3 format we spoke about before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2822)*

**Pull request merged**
