### PR TITLE
Changed CoreActionConsts.js to ActionTypes.js 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
changed redux action constants file name to ActionTypes.js and changed its syntax to ES6

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1732)

### CODE REVIEW

**Comment by RoyalSix** [comment]
I wasn't able to login with this branch, not sure why

---

Review status: 0 of 64 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1732#-:-KlnT90sbOa2Pf7uKx86:b-x4tik0)*

**Comment by mannycolon** [comment]
I just fixed the bug with the login.

---

Review status: 0 of 69 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1732#-:-KlnaUiS_5SierTDR3Rm:b-tgeay9)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: 0 of 69 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1732#-:-Klu6QWiJUVONCFWE3h-:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 70 of 70 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1732)*

**Pull request merged**
