### PR TITLE
Feature 4404/Update project naming to meet spec

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fixes QA failures in https://github.com/unfoldingWord-dev/translationCore/issues/4402
  - projects that don't match naming spec will open project details page and allow setting/changing Translation Identifier and Project Nickname
  - fix problem that it wouldn't allow imports with same lang_id/book_id but different translation identifiers.

- fixes QA failures in https://github.com/unfoldingword-dev/translationcore/issues/4404 and design changes
  - projects that don't match naming spec will open project details page and allow setting/changing Translation Identifier and Project Nickname
  - user is told that they have a new project name after rename.

#### Please include detailed Test instructions for your pull request:
- test using a build at bottom of page.
- note that spec now does not ask user if they want to rename, just prompts them that it has been renamed.
- rename an unselected project on local file system so that it doesn't match spec.  Select it in app and you should get the project details screen to open up.  After you click save, should get prompt that project has been renamed.  Note that if project has been previously saved to Door43, you will get a temporary prompt that Door43 renaming will be implemented in future PR.
- make duplicate of existing project and make sure new name does not match spec.  Select it in app and you should get the project details screen to open up.  And should get warning that conflict exists as well as save will be changed to overwrite (not overwrite is not yet implemented - will just get a temporary dialog). 
- do usfm import of project.  Then do second usfm import of same project, but this time select same translation identifier, but different language - should be allowed.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4567)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (e854b81)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-e854b81.zip) is ready for download.
[macOS build 0.10.0 (e854b81)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-e854b81.dmg) is ready for download.
[Windows x64 build 0.10.0 (e854b81)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-e854b81.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (e854b81)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-e854b81.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (27ecafd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-27ecafd.zip) is ready for download.
[macOS build 0.10.0 (27ecafd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-27ecafd.dmg) is ready for download.
[Windows x64 build 0.10.0 (27ecafd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-27ecafd.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (27ecafd)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-27ecafd.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (20e6b5b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-20e6b5b.zip) is ready for download.
[macOS build 0.10.0 (20e6b5b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-20e6b5b.dmg) is ready for download.
[Windows x64 build 0.10.0 (20e6b5b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-20e6b5b.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (20e6b5b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-20e6b5b.setup.exe) is ready for download.

**Comment by richmahn** [comment]
Local testing: :lgtm: 

Unit testing, need to use path.join to make absolute paths that work in both Windows and Linux environments:

```
FAIL __tests__\ProjectDetailsActions.test.js
  ● ProjectDetailsActions.updateProjectNameIfNecessary() › renames project if lang_id changed

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -1,8 +1,8 @@
      Array [
        Object {
    -     "pathLocation": "./translationCore/projects/am_ult_eph_book",
    +     "pathLocation": "C:\\Users\\richm\\translationCore\\projects\\am_ult_eph_book",
          "type": "SET_SAVE_PATH_LOCATION",
        },
        Object {
          "alertMessage": "projects.renamed_project",
          "button1Text": "buttons.ok_button",

      at _callee3$ (__tests__/ProjectDetailsActions.test.js:291:54)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (__tests__/ProjectDetailsActions.test.js:8:613)
      at __tests__/ProjectDetailsActions.test.js:8:773
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● ProjectDetailsActions.updateProjectNameIfNecessary() › renames project if project id changed

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -1,8 +1,8 @@
      Array [
        Object {
    -     "pathLocation": "./translationCore/projects/fr_ult_tit_book",
    +     "pathLocation": "C:\\Users\\richm\\translationCore\\projects\\fr_ult_tit_book",
          "type": "SET_SAVE_PATH_LOCATION",
        },
        Object {
          "alertMessage": "projects.renamed_project",
          "button1Text": "buttons.ok_button",

      at _callee4$ (__tests__/ProjectDetailsActions.test.js:308:54)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (__tests__/ProjectDetailsActions.test.js:8:613)
      at __tests__/ProjectDetailsActions.test.js:8:773
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● ProjectDetailsActions.updateProjectNameIfNecessary() › renames project if resource.id (resourceId) changed

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -1,8 +1,8 @@
      Array [
        Object {
    -     "pathLocation": "./translationCore/projects/fr_lib_eph_book",
    +     "pathLocation": "C:\\Users\\richm\\translationCore\\projects\\fr_lib_eph_book",
          "type": "SET_SAVE_PATH_LOCATION",
        },
        Object {
          "alertMessage": "projects.renamed_project",
          "button1Text": "buttons.ok_button",

      at _callee5$ (__tests__/ProjectDetailsActions.test.js:325:54)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (__tests__/ProjectDetailsActions.test.js:8:613)
      at __tests__/ProjectDetailsActions.test.js:8:773
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● ProjectDetailsActions.updateProjectNameIfNecessary() › renames project if new project name is different than spec

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -1,8 +1,8 @@
      Array [
        Object {
    -     "pathLocation": "./translationCore/projects/fr_ult_eph_book",
    +     "pathLocation": "C:\\Users\\richm\\translationCore\\projects\\fr_ult_eph_book",
          "type": "SET_SAVE_PATH_LOCATION",
        },
        Object {
          "alertMessage": "projects.renamed_project",
          "button1Text": "buttons.ok_button",

      at _callee6$ (__tests__/ProjectDetailsActions.test.js:344:54)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (__tests__/ProjectDetailsActions.test.js:8:613)
      at __tests__/ProjectDetailsActions.test.js:8:773
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


Snapshot Summary
 › 4 snapshot tests failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.
```

---

Review status: 0 of 30 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4567#-:-LFJJyKw62fJJxCts7Yj:bne5vmp)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (de9ae06)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-de9ae06.zip) is ready for download.
[macOS build 0.10.0 (de9ae06)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-de9ae06.dmg) is ready for download.
[Windows x64 build 0.10.0 (de9ae06)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-de9ae06.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (de9ae06)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-de9ae06.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (dd56df1)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-dd56df1.zip) is ready for download.
[macOS build 0.10.0 (dd56df1)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-dd56df1.dmg) is ready for download.
[Windows x64 build 0.10.0 (dd56df1)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-dd56df1.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (dd56df1)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-dd56df1.setup.exe) is ready for download.

**Comment by richmahn** [comment]
Reviewed 1 of 22 files at r1, 9 of 26 files at r2, 16 of 24 files at r3, 2 of 5 files at r4, 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4567)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6789140)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6789140.zip) is ready for download.
[macOS build 0.10.0 (6789140)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6789140.dmg) is ready for download.
[Windows x64 build 0.10.0 (6789140)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6789140.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6789140)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6789140.setup.exe) is ready for download.

**Pull request merged**
