### PR TITLE
Added testing for USFM import, organized helpers

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Added testing for USFM import, organized helpers.
Tests should be >10x faster, completes in 6s instead of >60s.

#### How to test this pull request:

- [ ] run `npm test` and ensure all tests pass.
- [ ] open projects and ensure all functionality works.
- [ ] perform all actions on projects like export, import,  upload.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2404)

### CODE REVIEW

**Comment by klappy** [comment]
Found issues with importing... fixing then will let you know when to review.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 31 of 35 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/helpers/bibleHelpers.js, line 37 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6b8xzxmpIUzZNaS4j:-Kr6b8xzxmpIUzZNaS4k:b4lyiuh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/bibleHelpers.js#L37)):*
> ```JavaScript
>  * @returns {Boolean} True if there is any missing verses, false if the project does not contain any
>  */
> export function projectIsMissingVerses(projectSaveLocation, bookAbbr) {
> ```

Great Job!!!

I'm wondering if this action is more related to projects than bible.

---

*[src/js/helpers/LoadHelpers.js, line 87 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6bP4agDdRgrYgR8HO:-Kr6bP4agDdRgrYgR8HP:b6bz2l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/LoadHelpers.js#L87)):*
> ```JavaScript
> }
> 
> export function migrateAppsToDotApps(projectPath) {
> ```

I know this is not part of the story but I was wondering if we may want to move the migrateAppsToDotApps() action to a MigrationActions.js file I created?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-:-Kr6dl4Wl13q_mcgMx-K:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix I still need to test this branch. @klappy is this branch ready for testing?

**Comment by RoyalSix** [comment]
I tried opening a USFM file and got the following , I think you just forgot this function 


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-:-Kr6z3Dg59UfDuY1UnTH:b-qrg4cp)*

**Comment by RoyalSix** [comment]
Nevermind I needed to pull haha

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-:-Kr6zYDJZvCxPAAsPyRF:b-ezjojv)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 35 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/helpers/bibleHelpers.js, line 37 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6b8xzxmpIUzZNaS4j:-Kr70hGLlq2Isa0Mc8wk:b4c9lyr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/bibleHelpers.js#L37)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Great Job!!!

I'm wondering if this action is more related to projects than bible.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 35 files at r1, 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/helpers/LoadHelpers.js, line 87 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6bP4agDdRgrYgR8HO:-Kr71TIclwbLXlFwpSoY:b4c9lyr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/LoadHelpers.js#L87)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I know this is not part of the story but I was wondering if we may want to move the migrateAppsToDotApps() action to a MigrationActions.js file I created?
</blockquote></details>

:thumbsup: 

---

*[src/js/helpers/LoadHelpers.js, line 502 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr71XVX1XnXXp50f7QA:-Kr71XVX1XnXXp50f7QB:bwsh7rh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c41860b140243d71fbbb758da8f5351c6d17a83/src/js/helpers/LoadHelpers.js#L502)):*
> ```JavaScript
>          */
>         let languageCodeArray = headerIDArray[index].trim().split('_');
>         if (languageCodeArray.length == 3) {
> ```

Nice job getting these out!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by RoyalSix** [comment]
Looks like this build is failing because of the Autographa submodule https://travis-ci.org/unfoldingWord-dev/translationCore/jobs/262498277#L26

**Comment by RoyalSix** [comment]
Reviewed 28 of 35 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/helpers/LoadOnlineHelpers.js, line 14 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr737X2nIiZRdTAbU-h:-Kr737X2nIiZRdTAbU-i:btod95u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3c41860b140243d71fbbb758da8f5351c6d17a83/src/js/helpers/LoadOnlineHelpers.js#L14)):*
> ```JavaScript
> const git = require('../helpers/GitApi.js');
> 
> module.exports = (function() {
> ```

Nice! This has been here for too long

---

*[tC_apps/Autographa, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr72r2808PFvalPUkrH:-Kr72r2808PFvalPUkrI:b-bmf3xl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/tC_apps/Autographa#L1)):*
> ```
> Subproject commit e1923d41594e81a6995764ad170dc608ec733ecc
> ```

New submodule? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
screen shot 2017-08-09 at 2 13 48 pm
screen shot 2017-08-09 at 2 13 58 pm

**Comment by mannycolon** [comment]
@klappy @RoyalSix Tested the branch and it seems to work fine. The only problem is the failing tests.

**Comment by klappy** [comment]
*[tC_apps/Autographa, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr72r2808PFvalPUkrH:-Kr7TZp4_Xo4ZBdqQn4c:bbcw5aq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/tC_apps/Autographa#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

New submodule? :)
</blockquote></details>

Yeah, didn't to commit it yet!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 87 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6bP4agDdRgrYgR8HO:-Kr7TkpYNp3s5vUZ9hcA:b-gu83kt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/LoadHelpers.js#L87)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Yes!  I didn't remember that you created that file, I was trying to update my branch with develop and forgot!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by klappy** [comment]
*[src/js/helpers/bibleHelpers.js, line 37 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6b8xzxmpIUzZNaS4j:-Kr7ZETZ0h8qtpkxQVNs:bifuzw1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/bibleHelpers.js#L37)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

I questioned this one too, but the bible holds verses/chapters, but just threw it in here. I can move it to projects. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
@klappy Let me know when you address the suggestions/comments so I can merge it.

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 87 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-Kr6bP4agDdRgrYgR8HO:-Kr7_8BZ0Nw8uB5R7Utj:b-3g4e01) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5890898dc7708e88f0f0a2464299519bd86f1165/src/js/helpers/LoadHelpers.js#L87)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Yes!  I didn't remember that you created that file, I was trying to update my branch with develop and forgot!
</blockquote></details>

Should we do it in actions or make a migration helpers? I like testing helpers since they don't require state. It's a clear separation of concerns to
 me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
@klappy I think an action is good for now.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
Reviewed 44 of 44 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Comment by mannycolon** [comment]
@klappy These are still failling on my local machine 

screen shot 2017-08-09 at 5 21 21 pm
screen shot 2017-08-09 at 5 21 08 pm

**Comment by klappy** [comment]
@mannycolon: Double check that you have run `npm install` and that your package-lock.json is using `usfm.js` v0.7, the old version would cause that issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-:-KrBWfMO99D1UmyoJnyk:bamq8tb)*

**Comment by klappy** [comment]
`usfm.js` v0.0.7

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404#-:-KrBX-Su-rvB-iXp36KV:b9b5x9q)*

**Comment by mannycolon** [comment]
Reviewed 1 of 44 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2404)*

**Pull request merged**
