### PR TITLE
Final fixes for USFM import and project renaming process

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:
- Load a `USFM` project from local.
- Load a .tstudio project from local.
- Load a project from door43.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3401)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/ProjectValidationActions.test.js, line 109 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-L0HBR3mQ6ZFyszbylIY:-L0HBR3mQ6ZFyszbylIZ:bgozdz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/65cf349d21790eb037b1ea29daeb181f98acb461/__tests__/ProjectValidationActions.test.js#L109)):*
> ```JavaScript
>   });
> 
>   test("updateProjectFolderToNameSpecification returns duplicate project alert if a project with the same name is found", async () => {
> ```

Do you need async here if you're not using await?

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 49 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-L0HBdFtoGvLLuV6_K0l:-L0HBdFtoGvLLuV6_K0m:beq8v1z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/65cf349d21790eb037b1ea29daeb181f98acb461/src/js/actions/Import/LocalImportWorkflowActions.js#L49)):*
> ```JavaScript
>     } catch (error) {
>       // Catch all errors in nested functions above
>       if (error.type !== 'div') console.warn(error);
> ```

What type of errors will have this? Just wondering

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401)*

**Comment by mannycolon** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/ProjectValidationActions.test.js, line 109 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-L0HBR3mQ6ZFyszbylIY:-L0HDE5f8eSjWSqNR3jT:b-pb3qz8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/65cf349d21790eb037b1ea29daeb181f98acb461/__tests__/ProjectValidationActions.test.js#L109)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do you need async here if you're not using await?
</blockquote></details>

lol I will remove it I needed before but not anymore 

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 49 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-L0HBdFtoGvLLuV6_K0l:-L0HDkA86UNQPMkpWUho:b3osakc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/65cf349d21790eb037b1ea29daeb181f98acb461/src/js/actions/Import/LocalImportWorkflowActions.js#L49)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

What type of errors will have this? Just wondering
</blockquote></details>

It was a unnesesary promise rejection that included the JSX error message for dispatch(AlertModalActions.openAlertDialog(error));
 
in this case `<div> {.error message..}</div>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401)*

**Comment by klappy** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-:-L0He1Ij9ydzhNy_NFEk:bnfp4nl)*

**Comment by klappy** [comment]
Code looks great, and the import process works as it should. Good job.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3401#-:-L0He2ubbCBJldBGr4Mo:bgfyvkt)*

**Pull request merged**
