### PR TITLE
Make USFM Opening Better

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/615)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/615)*

**Comment by mannycolon** [comment]
I get the followign error when testing your branch with a .sfm file
**requirements.js:20 Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at Git._schedule (/Users/mannycolon/tcprojects/translationCore/node_modules/simple-git/src/git.js:1037:42)
    at Git._run (/Users/mannycolon/tcprojects/translationCore/node_modules/simple-git/src/git.js:1023:12)
    at Git.init (/Users/mannycolon/tcprojects/translationCore/node_modules/simple-git/src/git.js:83:19)
    at Object.init (/Users/mannycolon/tcprojects/translationCore/src/js/components/core/GitApi.js:22:11)
    at Object.onComplete (/Users/mannycolon/tcprojects/translationCore/src/js/components/core/create_project/CheckDataGrabber.js:164:21)
    at module.exports (/Users/mannycolon/tcprojects/translationCore/tC_apps/CommentBox/FetchData.js:7:3)
    at Object.getDataFromOnline (/Users/mannycolon/tcprojects/translationCore/src/js/components/core/create_project/CheckDataGrabber.js:234:5)console.error @ requirements.js:20(anonymous function) @ CheckDataGrabber.js [sm]:43saveModules @ CheckDataGrabber.js [sm]:76fetchModules @ CheckDataGrabber.js [sm]:32(anonymous function) @ CheckDataGrabber.js [sm]:98createCheckArray @ CheckDataGrabber.js [sm]:132(anonymous function) @ CheckDataGrabber.js [sm]:96(anonymous function) @ index.js:46(anonymous function) @ graceful-fs.js:78readFileAfterClose @ fs.js:445**

**Comment by mannycolon** [comment]
here is the file

[usfm-test.sfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/748852/usfm-test.sfm.zip)

**Comment by ihoegen** [comment]
@mannycolon I could not recreate this issue. Could you try again, clearing the localStorage, and clearing all project data associated with the file?

**Comment by mannycolon** [comment]
@ihoegen Did you try opening the file above?? ^^

**Comment by mannycolon** [comment]
@ihoegen also try opening the usfm and sfm project from my **recent projects** component.

**Comment by mannycolon** [comment]
try with both tools **(iW, tN)** and make sure to test with the latest versions.

**Comment by ihoegen** [comment]
@mannycolon Tested multiple files, and multiple scenarios. Opened the file in the zip, was able to get it working. I belive this is ready to merge when you think so.

**Comment by mannycolon** [comment]
```
undefined(TypeError: Cannot read property '8' of undefined)
```

**Comment by ihoegen** [comment]
@mannycolon I just opened a PR on scripturepane that takes care of that.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/615#-:-Kc-RKpXqlZEsQGrODF2:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/615)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/615)*

**Pull request merged**
