### PR TITLE
Closing Tab When Import Local Finder Shows

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR addresses the issue where the FAB still shows in the local import options after the finder opens

#### How to test this pull request:
Try and use the FAB local import option and ensure that the FAB disappears upon clicking the options.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2710)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2710)*

**Comment by klappy** [comment]
Code looks fine, but I do get a non-blocking error in the console when I cancel an import now.


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2710#-:-KuKF83-hPxqjBdmwT3h:b-sgh1ja)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2710#-:-KuKOSuLfXtzLmEBf8zI:bnfp4nl)*

**Comment by RoyalSix** [comment]
@klappy updated

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2710#-:-KuQiuiavTXHJbSZ28E8:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2710)*

**Pull request merged**
