### PR TITLE
Feature#3780/preserve usfm markers on imports

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-  Maintain USFM markers on tstudio local imports and door43 imports.

#### Please include detailed Test instructions for your pull request:
- Import project https://git.door43.org/tc06/ar_mat_text_ulb and should see "front" in the chapter json files (1.json, etc.)

- Import project [en_php_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1797619/en_php_text_reg.tstudio.zip)  and should see "front" in the chapter json files (1.json, etc.)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4008)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 2 of 5 files at r1, 1 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r2, 3 of 7 files at r3.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r3.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r3.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
Reviewed 2 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
Once all tests are passing again, this one should be good to go.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008#-:-L7CF3mubl3n8QadQ_0W:b-cl1vyf)*

**Comment by mannycolon** [comment]
Reviewed 2 of 5 files at r1, 6 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Fix failing unit tests

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4008#-:-L7Q5FXDpW6rgUl_Mlx-:bnfp4nl)*

**Pull request merged**
