### PR TITLE
Updated Layout for Home Screen #1895

### PR DESCRIPTION
**Pull request by klappy**
Updated Layout for Home Screen #1897

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1940)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/containers/home/MainContainer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940#-KnD7uHdyFsuwh3FCdPy:-KnD7uHe0aKiMfokftLl:b-4tvg4g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c1378dcf6c4765a57a186dfb92edcc8147932a1a/src/js/containers/home/MainContainer.js#L21)):*
> ```JavaScript
>         <StepperContainer {...this.props} />
>         <div style={{ display: 'flex', flexDirection: 'row', justifyContent: 'center', height: '70%' }}>
>           <div style={{ width: '400px', padding: '0 20px' }}>
> ```

Don't mean to nitpick but the mockup has the Instructions section as having a box shadow. We are using material-ui for that in the stepper. Its a simple change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940#-KnD7uHdyFsuwh3FCdPy:-KnEb9B5TMXeaO1eVjeC:bagfks9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c1378dcf6c4765a57a186dfb92edcc8147932a1a/src/js/containers/home/MainContainer.js#L21)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Don't mean to nitpick but the mockup has the Instructions section as having a box shadow. We are using material-ui for that in the stepper. Its a simple change
</blockquote></details>

I was having weird issues with the Material-UI Card last night so I punted by simulating it by just making the background white. Once I get everything else taken care of I will circle back around and implement Material-UI/Card. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940#-KnD7uHdyFsuwh3FCdPy:-KnEhFMHa5hdTH8OxSN6:b-hiaa2s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c1378dcf6c4765a57a186dfb92edcc8147932a1a/src/js/containers/home/MainContainer.js#L21)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I was having weird issues with the Material-UI Card last night so I punted by simulating it by just making the background white. Once I get everything else taken care of I will circle back around and implement Material-UI/Card. 
</blockquote></details>

Did you get it working in your context? I get this strange error: 
`Warning: Failed context type: The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940#-KnD7uHdyFsuwh3FCdPy:-KnEl5fsk1gntXej9Re6:b-abpt0y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c1378dcf6c4765a57a186dfb92edcc8147932a1a/src/js/containers/home/MainContainer.js#L21)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Did you get it working in your context? I get this strange error: 
`Warning: Failed context type: The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.`
</blockquote></details>

Okay, I've got it updated with Material-UI Cards. The cards show up in the components not here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940)*

**Comment by klappy** [comment]
*[src/js/containers/home/MainContainer.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940#-KnD7uHdyFsuwh3FCdPy:-KnElNWoQATXLB8Qo-tG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c1378dcf6c4765a57a186dfb92edcc8147932a1a/src/js/containers/home/MainContainer.js#L21)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Okay, I've got it updated with Material-UI Cards. The cards show up in the components not here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1940)*

**Pull request merged**
