### PR TITLE
Alignment Tool implementation

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

This PR brings in what's so far completed of the word alignment tool.

#### How to test this pull request:

- Use the following project to open the word alignment tool
[bes_tit_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1292672/bes_tit_text_reg.zip)
- Try dragging words from the left side panel to the Greek words boxes on the right side.
- Feel free to go to https://github.com/translationCoreApps/word-alignment-tool and review the code.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2646)

### CODE REVIEW

**Comment by mannycolon** [comment]
word bank

**Comment by RoyalSix** [comment]
@mannycolon What should I expect to work, and not to work?

**Comment by klappy** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2646)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2646#-:-Ktvsz-7LHTKs_YbrRk-:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix you should be able to drag words from the word bank to the Greek word boxes on the right side

**Comment by klappy** [comment]
That seems to work well on your project you provided. @royalsix Did you try the zip file that was in the original comment in the PR?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2646#-:-Ktx7L2_PhiVnHZin4q9:bcgug8l)*

**Comment by RoyalSix** [comment]
@klappy Yes it works, well we can merge

**Pull request merged**
