### PR TITLE
Missing Verse Check Update To New Structure

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes the old implementation of missing verses in a project

#### How to test this pull request:
Open projects that you know do and do not have missing verses
This [project](https://github.com/unfoldingWord-dev/translationCore/files/1118373/id_-co_text_reg.zip) has no missing verses for example

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2034)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 395 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7fU2dsk1JRLAsf-Rp:-Ko7fU2e4oWlYLtjyLYt:b89jvkm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c73d4852735cd34ec642c66019d6257063a14edd/src/js/helpers/LoadHelpers.js#L395)):*
> ```JavaScript
> export function projectIsMissingVerses(bookAbbr, projectSaveLocation) {
>     try {
>     let expectedVerses = fs.readJSONSync(Path.join(USER_RESOURCES_DIR, 'bibles', 'ulb-en', 'v6', 'index.json'));
> ```

Very clever. Good job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 395 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7fU2dsk1JRLAsf-Rp:-Ko7fdh7bn5oNBmZkiIe:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c73d4852735cd34ec642c66019d6257063a14edd/src/js/helpers/LoadHelpers.js#L395)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Very clever. Good job.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko7flsnWvnGkyJjGxIh:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 407 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7gwgO5SfA_V_HMvWW:-Ko7gwgPDzDWY9sLmKsq:b-nzhzkl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f8c84d7738870d6cd1dd7b700912e56210602514/src/js/helpers/LoadHelpers.js#L407)):*
> ```JavaScript
>         let verseLength = 0;
>         for (var verse in currentChapterObject) {
>             verseLength++;
> ```

After testing, this doesn't seem to detect the missing verses when they are blank, just if the count doesn't match the array/object between this chapter and the ULB. There are a couple of use cases that can cause issues. Removing one verse, adding another. Removing a verse but adding other content not in a verse tag, but gets a -1 or something (i've seen this). We need to actually check every verse for an empty string and make sure there are no gaps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
After testing, this doesn't seem to detect the missing verses when they are blank, just if the count doesn't match the array/object between this chapter and the ULB. There are a couple of use cases that can cause issues. Removing one verse, adding another. Removing a verse but adding other content not in a verse tag, but gets a -1 or something (i've seen this). We need to actually check every verse for an empty string and make sure there are no gaps.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko7hTuTt4rijqW2S4Jp:b-x9d2yp)*

**Comment by klappy** [comment]
I merged latest develop, hope that doesn't cause an issue, I thought it was good to go but tested deeper and came across the above issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko7hWCOOoltI7z3xHLJ:bl9tna2)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by RoyalSix** [comment]
The above issue is fixed, nice catch

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko82mfVizki8F8f57ZE:b-33zijc)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/helpers/LoadHelpers.js, line 395 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7fU2dsk1JRLAsf-Rp:-Ko8HbKg55zbJm0apgLc:b8h68v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f8c84d7738870d6cd1dd7b700912e56210602514/src/js/helpers/LoadHelpers.js#L395)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

good job

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by mannycolon** [comment]
@klappy this PR seems to be good to go. What do you think?

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 407 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7gwgO5SfA_V_HMvWW:-Ko9LpLDTbZ_e1eype7m:bb7k0qh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f8c84d7738870d6cd1dd7b700912e56210602514/src/js/helpers/LoadHelpers.js#L407)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

After testing, this doesn't seem to detect the missing verses when they are blank, just if the count doesn't match the array/object between this chapter and the ULB. There are a couple of use cases that can cause issues. Removing one verse, adding another. Removing a verse but adding other content not in a verse tag, but gets a -1 or something (i've seen this). We need to actually check every verse for an empty string and make sure there are no gaps.
</blockquote></details>

lgtm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
@royalsix: I deleted all the text out of a verse and reloaded the project and I didn't get the warning for missing verses.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko9MVmskmtWCQ7BLV9W:b-bfmxtv)*

**Comment by klappy** [comment]
*[src/js/helpers/LoadHelpers.js, line 407 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7gwgO5SfA_V_HMvWW:-Ko9MhPyQci9iRAPHT2_:b-z17ppn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f8c84d7738870d6cd1dd7b700912e56210602514/src/js/helpers/LoadHelpers.js#L407)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

 I deleted all the text out of a verse and reloaded the project and I didn't get the warning for missing verses. I'm not sure what exactly is going on because this should catch it as `''` should be false, using console `!!''` results in false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
This may be a good use case for writing tests, and use real test cases.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-Ko9NARudZZK_5nd604J:brout2z)*

**Comment by RoyalSix** [comment]
True, I can do that.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-KoJdZC3OWI9n8lNfzBt:b-60adj4)*

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/LoadHelpers.js, line 118 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-KoLSzA4-GfvbITbGavo:-KoLSzA4-GfvbITbGavp:b-tyt2k1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5ba228bfc63fad6b46266ab95eaa244c1f7a7291/src/js/helpers/LoadHelpers.js#L118)):*
> ```JavaScript
> export function setUpManifest(projectPath, projectLink, manifest, currentUser) {
>     const verifiedManifest = verifyChunks(projectPath, manifest);
>     console.log('verified chunks')
> ```

remove console logs

---

*[src/js/helpers/ProjectSelectionHelpers.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-KoLT5fHS3NNAHqSWF2u:-KoLT5fHS3NNAHqSWF2v:b5wnuas) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5ba228bfc63fad6b46266ab95eaa244c1f7a7291/src/js/helpers/ProjectSelectionHelpers.js#L8)):*
> ```JavaScript
>   manifest = manifest || tCManifest;
>   if (!manifest || !manifest.tcInitialized) {
>     console.log('setting up manifest')
> ```

remove console log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by RoyalSix** [comment]
Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/helpers/LoadHelpers.js, line 407 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-Ko7gwgO5SfA_V_HMvWW:-KoOZwseKgCtWjXa9U1y:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f8c84d7738870d6cd1dd7b700912e56210602514/src/js/helpers/LoadHelpers.js#L407)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

 I deleted all the text out of a verse and reloaded the project and I didn't get the warning for missing verses. I'm not sure what exactly is going on because this should catch it as `''` should be false, using console `!!''` results in false.
</blockquote></details>

Done.

---

*[src/js/helpers/LoadHelpers.js, line 118 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-KoLSzA4-GfvbITbGavo:-KoOZvnGRL35TLGmWD5x:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5ba228bfc63fad6b46266ab95eaa244c1f7a7291/src/js/helpers/LoadHelpers.js#L118)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove console logs
</blockquote></details>

Done.

---

*[src/js/helpers/ProjectSelectionHelpers.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-KoLT5fHS3NNAHqSWF2u:-KoOZxZkJ_AUhcnTv_lp:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5ba228bfc63fad6b46266ab95eaa244c1f7a7291/src/js/helpers/ProjectSelectionHelpers.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove console log
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
Reviewed 2 of 7 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2034#-:-KoOxcp7SIrnOkBS3l9M:bnfp4nl)*

**Pull request merged**
