### PR TITLE
Stable Build Branch

### PR DESCRIPTION
**Pull request by ihoegen**
This branch is stable enough for a build, but not perfect for builds. That being said, it contains all the setup that's needed for a build to work, and should therefore be merged into develop.
#11 is completed by this pull request.

`window.electron` is removed and replaced with the `electron` module. 

Scripts have been written to replace `electron .` That command still works, but `npm run start` is the new preferred. Scripts have also been written to create builds.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/40)

### CODE REVIEW

**Comment by ihoegen** [comment]
Also @RoyalSix and @therealsamf may or may not like this, but I changed .auth to Auth.json. Dot files get ignored by the electron-builder.

**Comment by klappy** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

_[.gitignore, line 196 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPehL-VNfjxSwVt0afw:-KPehL-VNfjxSwVt0afx:b-pxw6rz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/.gitignore#L196)):_

> ```
> $RECYCLE.BIN/
> 
> # Mac crap
> ```

Should eventually get rid of the word crap :)

---

_[index.html, line 8 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPehY3EZYlFBCUqUO2c:-KPehY3EZYlFBCUqUO2d:bbhu1py) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/index.html#L8)):_

> ``` HTML
> 
>     
>     <link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.min.css" >
> ```

Thanks for pulling these files locally for the build to make it run offline.

---

_[main.js, line 16 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPehh03a1WIoFi92ty6:-KPehh03a1WIoFi92ty7:bxxijub) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/main.js#L16)):_

> ``` JavaScript
> function createWindow () {
>   // Create the browser window.
>   mainWindow = new BrowserWindow({icon: 'images/TC_Icon.png', useContentSize: true, show: false});
> ```

Is there a way to use this same icon for the app icon?

---

_[scripts/build-win.js, line 7 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPeiY_uuypXtrqKBe8y:-KPeiY_uuypXtrqKBe8z:b9ht9tb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/scripts/build-win.js#L7)):_

> ``` JavaScript
> resultPromise = electronInstaller.createWindowsInstaller({
>     appDirectory: './dist/win-unpacked/',
>     exe: 'Translation Core.exe',
> ```

translationCore.exe

---

_[scripts/build-win.js, line 11 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPeicg6Crn_Hd_0bmZ1:-KPeicg6Crn_Hd_0bmZ2:b97g3v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/scripts/build-win.js#L11)):_

> ``` JavaScript
>     loadingGif: './images/TC_ANIMATED_Logo.gif',
>     setupIcon: './build/icon.ico',
>     setupExe: 'TranslationCoreSetup-0.1.0.exe'
> ```

translationCore

---

_[src/js/ModuleApi.js, line 303 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPeilzdeXzn7iny8CUm:-KPeilzdeXzn7iny8CUn:b-x361ic) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/src/js/ModuleApi.js#L303)):_

> ``` JavaScript
>   getAuthToken(type) {
>     if (this.authToken == undefined) {
>       var obj = fs.readJsonSync(window.__base + 'Auth.json', { throws: false })
> ```

Is this a shift for all .auth files to become Auth.json?

---

_[src/js/components/core/MenuBar.js, line 132 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPej2GQbCd9OPpMHTbl:-KPej2GQbCd9OPpMHTbm:boabbb6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/src/js/components/core/MenuBar.js#L132)):_

> ``` JavaScript
>         label: 'Learn More',
>         click: function() {
>           require('electron').shell.openExternal('https://github.com/WycliffeAssociates/8woc/');
> ```

Is this less efficient to require electron each time instead of once and calling it like before with window.electron? I have no idea but it seems like it could be a potential issue.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40)_

**Comment by ihoegen** [comment]
Review status: 0 of 21 files reviewed at latest revision, 5 unresolved discussions.

---

_[.gitignore, line 196 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPehL-VNfjxSwVt0afw:-KPjNiE6xHAal_QzHcPs:b-ux0yyw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/.gitignore#L196)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> Should eventually get rid of the word crap :)
> </details>
> Most of this is default from git, but I'll go ahead and remove it.

---

_[main.js, line 16 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPehh03a1WIoFi92ty6:-KPjNvFVMQOzZSlkVOoW:b-oo65in) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/main.js#L16)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> Is there a way to use this same icon for the app icon?
> </details>
> For Mac, the build would break when we tried to include an app icon. I'm trying out a new build system that is more customization, so we'll see.

---

_[src/js/ModuleApi.js, line 303 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPeilzdeXzn7iny8CUm:-KPjO59W0YxQI7YelTdx:b-ieiw3j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/src/js/ModuleApi.js#L303)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> Is this a shift for all .auth files to become Auth.json?
> </details>
> Yes it is. `electron-builder` and `electron-packager` both ignore dot files, so a .json had to be used. 

---

_[src/js/components/core/MenuBar.js, line 132 [r2]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40#-KPej2GQbCd9OPpMHTbl:-KPjOG3WpBwO_MUEt1Z6:b-nmawts) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4457d5103f0f0e68e60e90e1a61e31a30589800/src/js/components/core/MenuBar.js#L132)):_
<details><summary>

<i>Previously, klappy (Christopher Klapp) wrote…</i></summary>



> Is this less efficient to require electron each time instead of once and calling it like before with window.electron? I have no idea but it seems like it could be a potential issue.
> </details>
> The way require works is it loads the module once, and any other time it is required, it is just pulled from memory. It isn't more or less efficient than `window.electron`, it's just good practice.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40)_

**Comment by EllDoubleYew** [comment]
Outside of the Reviewable I have some issues with the build this branch gives me. When I try a load a project locally it just wont load at all and when I load a project from online that I have never loaded before I get weird errors. I am going to try and doccument these issues as specifically as possible so that we can work towards a patch because I really like everything else about this branch.

**Comment by EllDoubleYew** [comment]
This is working really well on my machine now, Are we clear for merge? I think that we should before we build from this branch.

**Comment by klappy** [comment]
Looks like there is a .auth file that may not need to be in here.

**Comment by EllDoubleYew** [comment]
Reviewed 15 of 24 files at r1, 1 of 3 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/40)_

**Pull request merged**
