### PR TITLE
Added scripture tooltip to bible references in the check info card

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- `rm -rf node_modules`
- `npm i`
-  Download [this file](https://github.com/translationCoreApps/translationNotes/files/3022120/tit.zip)
- Unzip the file and put it n the following location `Users⁩ ▸ {you} ▸ ⁨translationCore⁩ ▸ ⁨resources⁩ ▸ ⁨en⁩ ▸ ⁨translationHelps⁩ ▸ ⁨translationNotes⁩ ▸ ⁨v14⁩ ▸ ⁨figures⁩ ▸ ⁨groups⁩` (This file hasn't been fixed in the door43 catalog)

- Open the following [Titus project ](https://github.com/unfoldingWord-dev/translationCore/files/3040808/en_ulb_tit_book.zip)
- Select all tN categories and hit launch
- Open `Personification check` in `Titus 2:12`
- if you hover over the Titus 2:11 reference a tooltip should pop up with the scripture reference 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5950)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-linux-x64-1.2.0-b613d7c.deb) is ready for download.
[macOS build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-macos-x64-1.2.0-b613d7c.dmg) is ready for download.
[Windows x64 build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x64-1.2.0-b613d7c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x32-1.2.0-b613d7c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-linux-x64-1.2.0-b613d7c.deb) is ready for download.
[macOS build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-macos-x64-1.2.0-b613d7c.dmg) is ready for download.
[Windows x64 build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x64-1.2.0-b613d7c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (b613d7c)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x32-1.2.0-b613d7c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (6d223ff)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-linux-x64-1.2.0-6d223ff.deb) is ready for download.
[macOS build 1.2.0 (6d223ff)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-macos-x64-1.2.0-6d223ff.dmg) is ready for download.
[Windows x64 build 1.2.0 (6d223ff)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x64-1.2.0-6d223ff.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (6d223ff)](https://tc-builds.door43.org/build/bugfix-mannycolon-5760/translationCore-win-x32-1.2.0-6d223ff.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5950)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
@mannycolon - The concourse build is not showing a tooltip for me - copied over the figures files, and using your project

**Comment by PhotoNomad0** [comment]
Working now, was hovering over the wrong 2:11 reference,

**Pull request merged**
