### PR TITLE
Refactor group menu

### PR DESCRIPTION
**Pull request by klappy**
## This PR Addresses:
Group Menu Navigation and Actions to support previous and next.

## To Test:
Checkout VerseCheck branch with name `feature/refactor-navigation`

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1010)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/navigation_menu/Group.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQUM1CTLBBac2Yo6y:-KgeQUM2N-XdT41I4CcJ:bnzewdq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/Group.js#L1)):*
> ```JavaScript
> // MenuItem.js//
> ```

could we removed this comments and add proper JSdocs documentation

---

*[src/js/components/core/navigation_menu/GroupItem.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQaLrbq5x3AbO5XHO:-KgeQaLrbq5x3AbO5XHP:bnzewdq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/GroupItem.js#L1)):*
> ```JavaScript
> // SubMenuItem.js//
> ```

could we removed this comments and add proper JSdocs documentation

---

*[src/js/components/core/navigation_menu/Groups.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQbdRrMmCogBISKZf:-KgeQbdRrMmCogBISKZg:bnzewdq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/Groups.js#L1)):*
> ```JavaScript
> // SubMenu.js//
> ```

could we removed this comments and add proper JSdocs documentation

---

*[src/js/pages/app.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQip45MUDibMS40tm:-KgeQip45MUDibMS40tn:bou0ciy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L41)):*
> ```JavaScript
> import PopoverContainer from '../containers/PopoverContainer';
> import ModalContainer from '../containers/ModalContainer.js';
> import {changeCurrentContextId} from '../actions/ContextIdActions.js'
> ```

adding actions to app.js is a no no. lol

---

*[src/js/pages/app.js, line 134 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQmgO47Sa3rTBZ08b:-KgeQmgO47Sa3rTBZ08c:b-8899fh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L134)):*
> ```JavaScript
>           </Row>
>           <Col className="col-fluid" xs={1} sm={2} md={2} lg={3} style={{ padding: 0, width: "250px" }}>
>             <SideBarContainer {...this.props} />
> ```

please use sidebarContainer do not send props from app.js. if need to add an action or a prop to this container add it directly to the container. that's how we do it in redux.

---

*[src/js/pages/app.js, line 159 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeR-c6mzMMgajS6S2E:-KgeR-c6mzMMgajS6S2F:b-fpe3wg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L159)):*
> ```JavaScript
>       dispatch(recentProjectActions.startLoadingNewProject(lastCheckModule));
>     },
>     actions: {
> ```

move this action to the appropriate container that is going to use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Review by mannycolon — CHANGES_REQUESTED** [review]
please address suggested changes in app.js

**Comment by klappy** [comment]
*[src/js/components/core/navigation_menu/Group.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQUM1CTLBBac2Yo6y:-KgnUMqoEEsrnWjBGoX6:bwok6gj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/Group.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we removed this comments and add proper JSdocs documentation
</blockquote></details>

I need to get in the habit of doing that. You can see that I started by copy/pasting the old menu code too :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/components/core/navigation_menu/GroupItem.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQaLrbq5x3AbO5XHO:-KgnUWunCS_ZMjFQd4ur:bhj2z4b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/GroupItem.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we removed this comments and add proper JSdocs documentation
</blockquote></details>

I'll get this one too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/components/core/navigation_menu/Groups.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQbdRrMmCogBISKZf:-KgnUZpERpyBULcaT3Pt:b-rkz2jj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/Groups.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we removed this comments and add proper JSdocs documentation
</blockquote></details>

same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQip45MUDibMS40tm:-KgnUcGV8wJIXeaRY2hP:bmxlxx3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L41)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

adding actions to app.js is a no no. lol
</blockquote></details>

Thanks for sharing where to put that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 134 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQmgO47Sa3rTBZ08b:-KgnUjxcI5E_fzmn--Qa:b-np9ww4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L134)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

please use sidebarContainer do not send props from app.js. if need to add an action or a prop to this container add it directly to the container. that's how we do it in redux.
</blockquote></details>

good to know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 159 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeR-c6mzMMgajS6S2E:-KgnUneCL9Vnp6S_x0XO:bgvs52y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L159)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

move this action to the appropriate container that is going to use it.
</blockquote></details>

will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/components/core/groupMenu/Groups.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQbdRrMmCogBISKZf:-KgnwwOuoFBWmSLgDz0_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/groupMenu/Groups.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 41 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQip45MUDibMS40tm:-KgnwyWcc4Nxph8KUdjU:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L41)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Thanks for sharing where to put that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 134 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQmgO47Sa3rTBZ08b:-KgnxGM-6Kl3HnVzo_PM:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L134)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

good to know.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/pages/app.js, line 159 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeR-c6mzMMgajS6S2E:-KgnxIVahAgJDHmU0bgv:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/pages/app.js#L159)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

will do.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/components/core/navigation_menu/Group.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQUM1CTLBBac2Yo6y:-KgnxLQopMHGRHQ7im3R:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/Group.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I need to get in the habit of doing that. You can see that I started by copy/pasting the old menu code too :/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by klappy** [comment]
*[src/js/components/core/navigation_menu/GroupItem.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-KgeQaLrbq5x3AbO5XHO:-KgnxMwhHBj8zjLaPNGG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6b7570cff543857441b48de0451a45f8c912a799/src/js/components/core/navigation_menu/GroupItem.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'll get this one too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-:-KgoPTuPhY7K2vZzeCVe:bnfp4nl)*

**Review by mannycolon — APPROVED** [review]

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r2, 3 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1010#-:-Kgp47r4q_ytfrB5wxlW:bnfp4nl)*

**Pull request merged**
