### PR TITLE
Bug fix/#2955 windows menu bar shows full path of the current project

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: https://github.com/unfoldingWord-dev/translationCore/issues/2955

#### How to test this pull request:

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3088)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/StatusBarContainer.test.js, line 31 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW4A8Z51ux5EgvOFtT:-KyW4A8_j2Lh9vCMp5do:bblfe34) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L31)):*
> ```JavaScript
> 
>   afterEach(() => {
>     delete window._mock_path;
> ```

Do we need to use the window object in this test? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[__tests__/StatusBarContainer.test.js, line 142 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW4UfTxSB-GLn8-2gN:-KyW4UfTxSB-GLn8-2gO:b-uj0z2m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L142)):*
> ```JavaScript
>       let text = "";
>       if (typeof item === 'string') {
>        if ((item.length) && ((item !== " ") && (item !== "\xA0"))) { // ignore " " whitespace
> ```

It looks like the helpers might be getting on the more complex side. Does this take away from the tests legitimacy? Because if you make an error in this logic, the test could pass but it may be a false positive.
Or if you make an error in this logic the test could fail when it really should be passing.

---

*[src/js/containers/StatusBarContainer.js, line 41 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW6KpWFTTcYAxSQ9iy:-KyW6KpWFTTcYAxSQ9iz:bm7pdp5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/src/js/containers/StatusBarContainer.js#L41)):*
> ```JavaScript
> 
> function getProjectName(projectPath) {
>   let usePath = window._mock_path || path;
> ```

Do we need to use the window object here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by RoyalSix** [comment]
Its also worth noting that you may not need the store for this test. If the action (to get back a path) is using an input/output abstracted from redux and the workflow of how its being used in the app then you shouldn't need to use/setup the store.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-:-KyW6swhdltKnSsbsrMz:b5jcgdu)*

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/StatusBarContainer.test.js, line 17 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW7h_uxcMq2ksX0sLY:-KyW7h_uxcMq2ksX0sLZ:b4ayz3b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L17)):*
> ```JavaScript
> const os = require('os');
> 
> require('jest');
> ```

I believe you don't need to require jest here, thats what the eslint comment does at the top for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by PhotoNomad0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/StatusBarContainer.test.js, line 31 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW4A8Z51ux5EgvOFtT:-KyWl4dx0Ig-tg633viu:bs67u4e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L31)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we need to use the window object in this test? 
</blockquote></details>

Think I may have an alternative to this.  

---

*[__tests__/StatusBarContainer.test.js, line 142 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW4UfTxSB-GLn8-2gN:-KyWi2fMQ12FMmTPnydO:b-fqwafp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L142)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It looks like the helpers might be getting on the more complex side. Does this take away from the tests legitimacy? Because if you make an error in this logic, the test could pass but it may be a false positive.
Or if you make an error in this logic the test could fail when it really should be passing.
</blockquote></details>

I think it's a long shot that the test would incorrectly pass since we are matching text on buttons, and if the test failed then I would have to rework the test.  I suppose I tend to be very thorough in wanting to verify the layout changes with code, since that is what we have always done.  I'm not a big fan of snapshots since then next person that touches the UI may break something else and not realize it since he had to update the snapshot anyway.  But if we want to go with snapshot testing, I can go along with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/StatusBarContainer.test.js, line 17 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW7h_uxcMq2ksX0sLY:-KyX1CHvtgLtLOFSrskZ:byhmmfv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L17)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I believe you don't need to require jest here, thats what the eslint comment does at the top for us.
</blockquote></details>

I was wondering the same thing but wasn't sure.

---

*[__tests__/StatusBarContainer.test.js, line 31 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW4A8Z51ux5EgvOFtT:-KyX04E4DkJWDRbp9bHO:bfaixrm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/__tests__/StatusBarContainer.test.js#L31)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Think I may have an alternative to this.  
</blockquote></details>

Yes, I agree I don't feel comfortable doing that.

---

*[src/js/containers/StatusBarContainer.js, line 41 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW6KpWFTTcYAxSQ9iy:-KyX0aq4Hc3xaYc8n2_Y:b-dta0lx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/src/js/containers/StatusBarContainer.js#L41)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we need to use the window object here?
</blockquote></details>

I feel the same way as Jay about using the window object. Another thing if the projectSaveLocation string is being saved in the reducer why don't we parse it how we want it before saving it in the reducer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by PhotoNomad0** [comment]
> Its also worth noting that you may not need the store for this test. If the action (to get back a path) is using an input/output abstracted from redux and the workflow of how its being used in the app then you shouldn't need to use/setup the store.

Jay, I am not following this.  Can you give an example?

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-:-KyX7bYdxhbz3LgjFrOu:bt0ktj7)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/containers/StatusBarContainer.js, line 41 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088#-KyW6KpWFTTcYAxSQ9iy:-KyX8GQLWJYFhNWZ9GDO:b-gpspjh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6ef0a76997c6e546ff8de4945674b9b8e45946a2/src/js/containers/StatusBarContainer.js#L41)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I feel the same way as Jay about using the window object. Another thing if the projectSaveLocation string is being saved in the reducer why don't we parse it how we want it before saving it in the reducer.
</blockquote></details>

Thanks Manny, like that suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by PhotoNomad0** [comment]
@RoyalSix @mannycolon - have updated the test and component to address concerns.  Still do not understand how I can remove the store.  My attempts to remove have resulted in render crashing.

**Comment by richmahn** [comment]
Just FYI, I have tested this on my Windows machine and looks good in that sense, but am lost when it comes to the test case comments!

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3088)*

**Comment by PhotoNomad0** [comment]
sorry merge with develop went wrong.  will retry later.

**Pull request closed without merging**
