### PR TITLE
Allow inclusion of submodules in packages

### PR DESCRIPTION
**Pull request by ihoegen**
@RoyalSix You may find interest in this, it'll make the whole resource packaging nicer.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/278)

### CODE REVIEW

**Comment by RoyalSix** [comment]
What exactly is this doing?? haha

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/278#-:-KVwMPNtKkvgKyQVUED8:b-qg19wu)_

**Comment by ihoegen** [comment]
So I don't know if you know this or not @RoyalSix but in your PR for both tools, you have a git submodule (See https://git-scm.com/docs/git-submodule) included, and in order for tC to download the contents of that submodule, a recursive clone needs to be run.

**Comment by RoyalSix** [comment]
Oh I see. Looks good then, does this always happen now? Is there a side effect if the flag is not used? (there are no submodules)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/278#-:-KW0ObkYAUX6-vpck7TR:b-6w81l4)_

**Comment by ihoegen** [comment]
It allows for submodules, it's a future case kind of use, and I think submodules would be a great way to manage resources on checking apps.

**Comment by RoyalSix** [comment]
I wanna merge this, but I'm not exactly sure if we need this just yet, might be preoptimization

**Comment by ihoegen** [comment]
It's pretty much a preoptimization, for the not so distant future.

**Comment by RoyalSix** [comment]
Ok. @klappy do you have any input on this? If not I will merge it.

**Comment by klappy** [comment]
I agree that it is both pre-optimization but definitely needed soon.
Thanks for addressing this @ihoegen.

Go ahead and pull @RoyalSix.

**Pull request merged**
