### PR TITLE
Added Reload Button On Hanging Project Loading

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR makes a reload button show up after 3 seconds for projects that may have crash during the loading process.

#### How to test this pull request:
You will need to test a project that hangs or you can comment out the lines that make a tool show in 
```ProjectLoadingActions.js``` lines 33-34

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2617)

### CODE REVIEW

**Comment by klappy** [comment]
@RoyalSix This works well. 

I was wondering if we want to notify the user that the project couldn't be loaded?

The reload is helpful, but they may keep trying to load the same project if they don't know why it gives them the reload button.

**Comment by klappy** [comment]
I'm just not sure I know what to expect when the reload button appears. Could it appear too soon when the app is functioning well? If so, should it wait longer?

Maybe change the "Loading..." text to something like, "Waiting too long? There may be a problem with this project."

I'd check with Ben and Koz before changing the text though.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-:-Ksz169KYJUJ0xMx0QR6:b-833f8v)*

**Comment by klappy** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Also, how do I recreate the cannot clone repository alert? I know the text has changed, but I can't find a way to bring it up to test it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-:-Ksz1mfrKotgi20Rz3gp:b-wmb18k)*

**Comment by RoyalSix** [comment]
@klappy I'm not exactly sure how to re-create the cannot clone repository either, but I figured logically that has to be the place to fix it.

**Comment by RoyalSix** [comment]
@benjore @cckozie Thoughts on having a reload button ? After how long should it appear ? Should we have verbiage on the reload button itself to let the user know something not usual happened?

**Comment by cckozie** [comment]
@RoyalSix @klappy @benjore : I am not a fan of arbitrarily throwing up a reload button after some timeout because we think something might have gone wrong. It seems to me that there should be a way to throw and trap the errors that cause the project to be unloadable. In the project referenced in the related issue, I'm seeing this error in the console when trying to load it:
image
Also, I've noticed that if I try to import that project from Door43 using the URL, I get an alert indicating the it is not a valid project. So it seems that in this case, there must be something observable that we should be able to catch.

**Comment by mannycolon** [comment]
Reviewed 2 of 7 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/LoaderActions.js, line 5 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-Ktl8Nf99KDEEyWyb9zE:-Ktl8Nf99KDEEyWyb9zF:b-eujmil) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/869ac68c6ccc4c67cb08239871c30e5c0162431b/src/js/actions/LoaderActions.js#L5)):*
> ```JavaScript
> export function toggleLoader(val) {
>   return ((dispatch) => {
>     if (val === true) window.setTimeout(() => dispatch(toggleWaitingTooLongButton(true)), 3000)
> ```

I was wondering, do we want to make the cancel project loading option available all the time while the project loading process is happening instead of using a timeout. what do you think?

---

*[src/js/actions/ProjectLoadingActions.js, line 161 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-Ktl8kNgPLktd01ytnrp:-Ktl8kNgPLktd01ytnrq:b-1snv6s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/869ac68c6ccc4c67cb08239871c30e5c0162431b/src/js/actions/ProjectLoadingActions.js#L161)):*
> ```JavaScript
> 
> export function cancelLoadingProject() {
>   dispatch(ProjectSelectionActions.clearLastProject())
> ```

how do you have access to the `dispatch` function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by mannycolon** [comment]
dispatch is undefined in the `cancelLoadingProject() ` action in ProjectLoadingActions.js

**Comment by mannycolon** [comment]
I tested this branch and couldn't get it to work

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/LoaderActions.js, line 5 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-Ktl8Nf99KDEEyWyb9zE:-Ktqlsv9U_lRGVvVPM5r:b-n8j3ma) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/869ac68c6ccc4c67cb08239871c30e5c0162431b/src/js/actions/LoaderActions.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I was wondering, do we want to make the cancel project loading option available all the time while the project loading process is happening instead of using a timeout. what do you think?
</blockquote></details>

I guess thats more of a question for @cckozie. But my reasoning was we don't want users to think their project is broken and keep pressing the cancel button after an unreasonable amount of time

---

*[src/js/actions/ProjectLoadingActions.js, line 161 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617#-Ktl8kNgPLktd01ytnrp:-KtqlsRL_gT0jNinL1yj:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/869ac68c6ccc4c67cb08239871c30e5c0162431b/src/js/actions/ProjectLoadingActions.js#L161)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how do you have access to the `dispatch` function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
@RoyalSix: Were you able to handle the error that Koz encountered in the original story? According to his latest comments all we have to do is remove the cancel button, I know we spent a lot of time on it but it isn't worth the effort right now on this PR. If you can remove it and ensure we handle his error, we can merge this and move on.

**Comment by RoyalSix** [comment]
@klappy yes this should be good to go

**Comment by klappy** [comment]
Reviewed 1 of 1476 files at r8.
Review status: 1 of 766 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r7, 1 of 1476 files at r8.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r7.
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r7, 1 of 1476 files at r8.
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Reviewed 1 of 1476 files at r8.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Comment by klappy** [comment]
Reviewed 2 of 11 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2617)*

**Pull request closed without merging**
