### PR TITLE
Project Validation Stepper Main Container (Import Check)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR contains the basic containers, components, actions and reducers for handling project validation elements.

#### How to test this pull request:
Try and open a project and make sure the stepper shows, and you should be able to go through each step until the end.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2386)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 13 of 16 files at r1.
Review status: 13 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
*[src/js/reducers/projectValidationReducer.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-KqdtCq4esnDL4qxwWPs:-KqdtCq4esnDL4qxwWPt:b-qe1tl9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/reducers/projectValidationReducer.js#L31)):*
> ```JavaScript
>       return {
>         ...state,
>         homeInstructions: action.instructions
> ```

should we call this something other than home instructions? that's what we call it on the home screen and I don't want us to get confused.
calling it `projectValidationInstructions` or just `instructions` would be better. It's in the namespace of the reducer, so it shouldn't be confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
*[src/js/components/projectValidation/ProjectValidationInstructions.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-Kqdtw4TqMpnK5RECion:-Kqdtw4TqMpnK5RECioo:b5fzxqe) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/components/projectValidation/ProjectValidationInstructions.js#L9)):*
> ```JavaScript
> 
>   render() {
>     let { instructions } = this.props.reducers.projectValidationReducer || <div></div>;
> ```

I think the reducer calls this homeInstructions, but should be updated to match this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
*[src/js/reducers/projectValidationReducer.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-KqdtCq4esnDL4qxwWPs:-Kqdu2JVm4Kkj3GRR7zN:b-29htie) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/reducers/projectValidationReducer.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

should we call this something other than home instructions? that's what we call it on the home screen and I don't want us to get confused.
calling it `projectValidationInstructions` or just `instructions` would be better. It's in the namespace of the reducer, so it shouldn't be confusing.
</blockquote></details>

looks like the component already uses `instructions`. We should fix that here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
*[src/js/reducers/projectValidationReducer.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-KqdtCq4esnDL4qxwWPs:-KqduAbKs92FZfTjEzt6:b-78o736) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/reducers/projectValidationReducer.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

looks like the component already uses `instructions`. We should fix that here.
</blockquote></details>

Oh, and the default is... guess it was just missed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
Reviewed 3 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by RoyalSix** [comment]
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/projectValidation/ProjectValidationInstructions.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-Kqdtw4TqMpnK5RECion:-KqeCXmL_JDctnp-q59r:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/components/projectValidation/ProjectValidationInstructions.js#L9)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I think the reducer calls this homeInstructions, but should be updated to match this.
</blockquote></details>

Done.

---

*[src/js/reducers/projectValidationReducer.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-KqdtCq4esnDL4qxwWPs:-KqeCd1eWbOKQs7LbJ_b:bi4ue99) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/95a4a80d44675c07af0b50c27b355b1f71fd2f13/src/js/reducers/projectValidationReducer.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Oh, and the default is... guess it was just missed :)
</blockquote></details>

Yep, missed that. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2386#-:-KqiH2VBAb7nDmNwj6TG:bnfp4nl)*

**Pull request merged**
