### PR TITLE
Feature 5407: Update tc-ui-toolkit with latest VerseDialog

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6635)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (844bfcc)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-844bfcc.deb) is ready for download.
[macOS build 2.1.0 (844bfcc)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-844bfcc.dmg) is ready for download.
[Windows x64 build 2.1.0 (844bfcc)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-844bfcc.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (844bfcc)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-844bfcc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (7fbb0fa)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-7fbb0fa.deb) is ready for download.
[macOS build 2.1.0 (7fbb0fa)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-7fbb0fa.dmg) is ready for download.
[Windows x64 build 2.1.0 (7fbb0fa)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-7fbb0fa.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (7fbb0fa)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-7fbb0fa.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (efe73e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-efe73e7.deb) is ready for download.
[macOS build 2.1.0 (efe73e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-efe73e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (efe73e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-efe73e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (efe73e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-efe73e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (579ac7d)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-579ac7d.deb) is ready for download.
[macOS build 2.1.0 (579ac7d)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-579ac7d.dmg) is ready for download.
[Windows x64 build 2.1.0 (579ac7d)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-579ac7d.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (579ac7d)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-579ac7d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-25adf7a.deb) is ready for download.
[macOS build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-25adf7a.dmg) is ready for download.
[Windows x64 build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-25adf7a.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (25adf7a)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-25adf7a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-3719b8c.deb) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-3719b8c.deb) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-3719b8c.deb) is ready for download.
[macOS build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-3719b8c.dmg) is ready for download.
[Windows x64 build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-3719b8c.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3719b8c)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-3719b8c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3b626e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-3b626e7.deb) is ready for download.
[macOS build 2.1.0 (3b626e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-3b626e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (3b626e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-3b626e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3b626e7)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-3b626e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-a1cd196.deb) is ready for download.
[macOS build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-a1cd196.dmg) is ready for download.
[Windows x64 build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-a1cd196.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (a1cd196)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-a1cd196.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (dce1204)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-dce1204.deb) is ready for download.
[macOS build 2.1.0 (dce1204)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-dce1204.dmg) is ready for download.
[Windows x64 build 2.1.0 (dce1204)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-dce1204.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (dce1204)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-dce1204.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
@PhotoNomad0 Why are you manually adding the tools commit hash?

**Comment by mannycolon** [comment]
Is this ready for review?
@PhotoNomad0

**Comment by PhotoNomad0** [comment]
For now this was for creating test builds, still in process waiting on your changes to wA and then my changes to wA. @mannycolon

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (71a4f74)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-linux-x64-2.1.0-71a4f74.deb) is ready for download.
[macOS build 2.1.0 (71a4f74)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-macos-x64-2.1.0-71a4f74.dmg) is ready for download.
[Windows x64 build 2.1.0 (71a4f74)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x64-2.1.0-71a4f74.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (71a4f74)](https://tc-builds.door43.org/build/feature-mcleanb-5407/translationCore-win-x32-2.1.0-71a4f74.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
