### PR TITLE
Feature 6193/Allow other books under Greek and Hebrew as references but not as tC reference original

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- removed hard coding that mapped all bibles under original language to be treated as original source.  We only have the ugnt and uhb that are to be used as originals in tCore.
- moved magic strings into constants.js

#### Please include detailed Test instructions for your pull request:
- unzip these bibles into folder ⁨`resources/el-x-koine⁩/⁨bibles⁩`: [maj-rp.zip](https://github.com/unfoldingWord-dev/translationCore/files/3352022/maj-rp.zip)
[tisch.zip](https://github.com/unfoldingWord-dev/translationCore/files/3352023/tisch.zip)
- open a NT project and in WA try adding the new bibles under original language.  Then go into TW an TN tools to make sure they show up.
- open a OT project in WA - should not see the Greek bibles in Scripture Pane

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6208)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (3608a16)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-3608a16.deb) is ready for download.
[macOS build 1.2.0 (3608a16)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-3608a16.dmg) is ready for download.
[Windows x64 build 1.2.0 (3608a16)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-3608a16.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (3608a16)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-3608a16.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (1899ea9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-1899ea9.deb) is ready for download.
[macOS build 1.2.0 (1899ea9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-1899ea9.dmg) is ready for download.
[Windows x64 build 1.2.0 (1899ea9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-1899ea9.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (1899ea9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-1899ea9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (e870d00)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-e870d00.deb) is ready for download.
[macOS build 1.2.0 (e870d00)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-e870d00.dmg) is ready for download.
[Windows x64 build 1.2.0 (e870d00)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-e870d00.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (e870d00)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-e870d00.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (82372a9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-82372a9.deb) is ready for download.
[macOS build 1.2.0 (82372a9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-82372a9.dmg) is ready for download.
[Windows x64 build 1.2.0 (82372a9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-82372a9.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (82372a9)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-82372a9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (824e862)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-824e862.deb) is ready for download.
[macOS build 1.2.0 (824e862)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-824e862.dmg) is ready for download.
[Windows x64 build 1.2.0 (824e862)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-824e862.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (824e862)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-824e862.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (27a0669)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-27a0669.deb) is ready for download.
[macOS build 1.2.0 (27a0669)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-27a0669.dmg) is ready for download.
[Windows x64 build 1.2.0 (27a0669)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-27a0669.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (27a0669)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-27a0669.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (58a9243)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-linux-x64-1.2.0-58a9243.deb) is ready for download.
[macOS build 1.2.0 (58a9243)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-macos-x64-1.2.0-58a9243.dmg) is ready for download.
[Windows x64 build 1.2.0 (58a9243)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x64-1.2.0-58a9243.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (58a9243)](https://tc-builds.door43.org/build/feature-mcleanb-6193/translationCore-win-x32-1.2.0-58a9243.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 49 of 52 files at r2, 1 of 2 files at r3, 6 of 6 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6208#-:-LjH5rEJ91z9dikQwOED:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
