### PR TITLE
Updated resources to latest & included hbo (Hebrew)

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Pude relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Impor and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5535)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c62ea86)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-c62ea86.deb) is ready for download.
[macOS build 1.1.0 (c62ea86)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-c62ea86.dmg) is ready for download.
[Windows x64 build 1.1.0 (c62ea86)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-c62ea86.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c62ea86)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-c62ea86.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
See error in WA: Lexicon is blank on in the word details popup for NT books:
- deleted resources folder
- ran app
- opened titus in WA
- clicked on greek word and popup had missing lexicon entry.

It looks like in resource folder, that en/lexicons folder is missing.

**Review by PhotoNomad0 — DISMISSED** [review]

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c1606b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-c1606b5.deb) is ready for download.
[macOS build 1.1.0 (c1606b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-c1606b5.dmg) is ready for download.
[Windows x64 build 1.1.0 (c1606b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-c1606b5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c1606b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-c1606b5.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@mannycolon - Getting error when I just delete hbo folder and run the app.

screen shot 2018-12-06 at 3 47 32 pm

Looks like the problem is with MacOs and the hidden files.

**Comment by mannycolon** [comment]
forgot about that added filter for `.DS_Store`

**Review by PhotoNomad0 — DISMISSED** [review]

**Comment by PhotoNomad0** [comment]
One more error:

screen shot 2018-12-06 at 4 11 17 pm

Looks like your code is creating the `imports_processed` folder and then it's crashing.

**Comment by mannycolon** [comment]
what the heck is the `imports_processed `?

**Comment by mannycolon** [comment]
I never created that

**Comment by mannycolon** [comment]
I added code to exclude both imports and imported_processed folders

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (390d329)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-390d329.deb) is ready for download.
[macOS build 1.1.0 (390d329)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-390d329.dmg) is ready for download.
[Windows x64 build 1.1.0 (390d329)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-390d329.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (390d329)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-390d329.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (330281f)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-330281f.deb) is ready for download.
[macOS build 1.1.0 (330281f)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-330281f.dmg) is ready for download.
[Windows x64 build 1.1.0 (330281f)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-330281f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (330281f)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-330281f.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Still a problem - it looks like the hbo folder is being created, but cannot open OT books in WA.

the UHB is not being completely unpacked  into the resources: 

screen shot 2018-12-07 at 6 48 56 am

Then I look into app's tcResources and see:

screen shot 2018-12-07 at 6 53 01 am

something doesn't look right - books.zip is very small and I get an error when I try to expand it.  

I don't see an error in the console when it recreates hbo.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0c903b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-0c903b5.deb) is ready for download.
[macOS build 1.1.0 (0c903b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-0c903b5.dmg) is ready for download.
[Windows x64 build 1.1.0 (0c903b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-0c903b5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0c903b5)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-0c903b5.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1b1f6a9)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-linux-x64-1.1.0-1b1f6a9.deb) is ready for download.
[macOS build 1.1.0 (1b1f6a9)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-macos-x64-1.1.0-1b1f6a9.dmg) is ready for download.
[Windows x64 build 1.1.0 (1b1f6a9)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x64-1.1.0-1b1f6a9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1b1f6a9)](https://tc-builds.door43.org/build/feature-mannycolon-5475/translationCore-win-x32-1.1.0-1b1f6a9.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]

**Pull request merged**
