### PR TITLE
Chevron Menu Structure

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/336)

### CODE REVIEW

**Comment by mannycolon** [comment]
#318

**Comment by mannycolon** [comment]
#323

**Comment by ihoegen** [comment]
Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/336)*

**Comment by ihoegen** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/336)*

**Pull request merged**
