### PR TITLE
Js redux

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/431)

### CODE REVIEW

**Comment by ihoegen** [comment]
@RoyalSix Merge with develop and I can do a review for you

**Comment by RoyalSix** [comment]
Merged 👍

**Comment by ihoegen** [comment]
The code looks good to me, I'm gonna give a functionality test, and merge tomorrow after Story Time, unless anyone has something to say for it. 

---

Reviewed 11 of 21 files at r1, 8 of 9 files at r3, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/core/Loader.js, line 31 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431#-K_XoV8HDsWSvvKuoi7k:-K_XoV8HDsWSvvKuoi7l:b-33s2uj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d4208a8760eb8fd0c854a7d31fbb1bc813e62c1/src/js/components/core/Loader.js#L31)):*
> ```JavaScript
> 
>   update: function() {
>     ;
> ```

Is there a purpose to this semicolon here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431#-:-K_Xp2QCqawhk5qAVxQY:bbhcx8o)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/pages/app.js, line 452 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431#-K_XqMdmH0-FpAQpNbC7:-K_XqMdmH0-FpAQpNbC8:b-1tf8fh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d4208a8760eb8fd0c854a7d31fbb1bc813e62c1/src/js/pages/app.js#L452)):*
> ```JavaScript
>           <SettingsModal />
>           <LoginModal loginProps={this.state.loginProps} profileProps={this.state.profileProps} profileProjectsProps={this.state.profileProjectsProps} {...this.state.loginModalProps} />
>           <ProjectModal {...this.props.loginModalReducer} {...this.state.projectModalProps} uploadProps={this.state.uploadProps} importUsfmProps={this.state.importUsfmProps} dragDropProps={this.state.dragDropProps} profileProjectsProps={this.state.profileProjectsProps}/>
> ```

Is there a reason to why the loginModalReducer is being passed to ProjectModal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/Loader.js, line 31 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431#-K_XoV8HDsWSvvKuoi7k:-K__h6wtEL05pYDs-Dcw:b49s4kd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d4208a8760eb8fd0c854a7d31fbb1bc813e62c1/src/js/components/core/Loader.js#L31)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Is there a purpose to this semicolon here?
</blockquote></details>

No that shouldn't be there haha my bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/pages/app.js, line 452 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431#-K_XqMdmH0-FpAQpNbC7:-K__hYXNA7uCPq7MYzT4:b4qlvc8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d4208a8760eb8fd0c854a7d31fbb1bc813e62c1/src/js/pages/app.js#L452)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Is there a reason to why the loginModalReducer is being passed to ProjectModal?
</blockquote></details>

Yea this will eventually take place for all the props were passing, it will just be one prop that contains all the functions/states from the reducer. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431)*

**Comment by ihoegen** [comment]
@EllDoubleYew @mannycolon Could you guys post your input to this PR?

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/431)*

**Comment by mannycolon** [comment]
@RoyalSix @ihoegen this looks really good for now

**Comment by ihoegen** [comment]
@RoyalSix Merge with develop and I'll merge

**Pull request merged**
