### PR TITLE
Bugfix 5832/Fix verse edit Indication in tW when edit made in WA

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixed loading of external verse edits into tW
- also some performance tweaks to make sure we don't try to set edits if already set.

#### Please include detailed Test instructions for your pull request:
- Import this clean Titus project: [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3029509/57-TIT.usfm.zip)
- open tw tool and filter for verse edits - should be none.
- open wa tool, open Expanded SP, and make any change to Titus 1:1
- should see pencil icon on Titus 1:1
- open tw tool and select apostle.
- should see pencil icon on Titus 1:1
- do filter for verse edits - should see a bunch of categories that have Titus 1:1 (I count 11), and their verses should have the pencil icon.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5933)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.3 (fcbe5df)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-linux-x64-1.1.3-fcbe5df.deb) is ready for download.
[macOS build 1.1.3 (fcbe5df)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-macos-x64-1.1.3-fcbe5df.dmg) is ready for download.
[Windows x64 build 1.1.3 (fcbe5df)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x64-1.1.3-fcbe5df.setup.exe) is ready for download.
[Windows x32 build 1.1.3 (fcbe5df)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x32-1.1.3-fcbe5df.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by mannycolon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by mannycolon — DISMISSED** [review]

**Review by mannycolon — DISMISSED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (56bf118)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-linux-x64-1.2.0-56bf118.deb) is ready for download.
[macOS build 1.2.0 (56bf118)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-macos-x64-1.2.0-56bf118.dmg) is ready for download.
[Windows x64 build 1.2.0 (56bf118)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x64-1.2.0-56bf118.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (56bf118)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x32-1.2.0-56bf118.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (188806a)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-linux-x64-1.2.0-188806a.deb) is ready for download.
[macOS build 1.2.0 (188806a)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-macos-x64-1.2.0-188806a.dmg) is ready for download.
[Windows x64 build 1.2.0 (188806a)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x64-1.2.0-188806a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (188806a)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x32-1.2.0-188806a.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0b64cff)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-linux-x64-1.2.0-0b64cff.deb) is ready for download.
[macOS build 1.2.0 (0b64cff)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-macos-x64-1.2.0-0b64cff.dmg) is ready for download.
[Windows x64 build 1.2.0 (0b64cff)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x64-1.2.0-0b64cff.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0b64cff)](https://tc-builds.door43.org/build/bugfix_mcleanb_5832/translationCore-win-x32-1.2.0-0b64cff.setup.exe) is ready for download.

**Pull request merged**
