### PR TITLE
Support for wordAlignment Rewrite

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4319

- This PR brings a number of updates to tC that are required for the re-written wA tool.
- Fixes tests that were leaving files behind every time they were run.
- Removes a LOT of the wordAlignment code. The export functionality will remain in tC until #2258 and the subsequent USFM export rewrite is complete.
- Adds the latest version of tc-tool (`1.5.0`) which brings a new tool api.
- Organizes some tool initialization code so that required data is loaded first (e.g. `contextId`)

#### Please include detailed Test instructions for your pull request:
- **this breaks the current wA** if you want to perform a complete review you'll need to also check out the PR for wA at https://github.com/translationCoreApps/wordAlignment/pull/35)
- check that tW and wA open without any trouble.

Here is a full list of PRs you'll want to test with
* https://github.com/translationCoreApps/ScripturePane/pull/118
* https://github.com/translationCoreApps/wordAlignment/pull/35
* https://github.com/translationCoreApps/VerseCheck/pull/104
* https://github.com/translationCoreApps/translationWords/pull/124

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - failing unit tests

**Comment by PhotoNomad0** [comment]
@neutrinog - testing these two PRs together, but seeing this error about missing translate when I open WA tool.  And ScripturePane just shows "error".

screen shot 2018-05-15 at 10 41 54 am

**Comment by da1nerd** [comment]
@PhotoNomad0 did you run npm install?

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 did you run npm install?

Yes for both tCore and the WA tool

**Comment by da1nerd** [comment]
@PhotoNomad0 I've tried everything I can think of and cannot reproduce this error. What version of the ScripturePane do you have under `tC_apps`?

**Comment by RoyalSix** [comment]
Reviewed 5 of 281 files at r1.
Review status: 5 of 284 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[__tests__/CSVExportActions.test.js, line 52 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCa4Re38SqrKD-MXSSY:-LCa4Re38SqrKD-MXSSZ:b3e1low) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/__tests__/CSVExportActions.test.js#L52)):*
> ```JavaScript
> 
>     test('should resolve true for checksPerformedPath', () => {
>       if(fs.existsSync('/home/joel/git/unfoldingWord-dev/translationCore/tC_resources/resources/en/translationHelps/translationNotes/v0/index.json')) {
> ```

Should your name be here? haha

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Reviewed 256 of 281 files at r1, 2 of 2 files at r3.
Review status: 263 of 284 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/WordAlignmentActions.js, line 3 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaEQFfCazBMXxaXfR6:-LCaEQFfCazBMXxaXfR7:b-ul03h3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ddb7090a963c237d167221a6609d72dcbcad9c89/src/js/actions/WordAlignmentActions.js#L3)):*
> ```JavaScript
> /* eslint-disable no-console */
> import stringHelpers from 'string-punctuation-tokenizer';
> import consts from './ActionTypes';
> ```

Do we still need this file still?

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Reviewed 11 of 281 files at r1, 2 of 2 files at r2.
Review status: 276 of 284 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ToolContainer.js, line 142 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaJQNG5C1rqJvHkfSp:-LCaJQNG5C1rqJvHkfSq:b-eruhom) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L142)):*
> ```JavaScript
>     try {
>       const data = await fs.readFile(readPath);
>       return data.toString();
> ```

should this return a Promise like it does when it fails?

---

*[src/js/containers/ToolContainer.js, line 157 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaJd8v9ISeRCN-7i-r:-LCaJd8v9ISeRCN-7i-s:bvwnbdp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L157)):*
> ```JavaScript
>     const readPath = path.join(projectSaveLocation,
>       '.apps/translationCore/', filePath);
>     const data = fs.readFileSync(readPath);
> ```

In the above function it checks if the file path exists, but in this one its not?

---

*[src/js/reducers/resourcesReducer.js, line 79 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaPdN3BVgWcVKvdGYK:-LCaPdN3BVgWcVKvdGYL:b-4ji7nw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/reducers/resourcesReducer.js#L79)):*
> ```JavaScript
>   const targetChapter = getTargetChapter(state, chapter);
>   if (targetChapter) {
>     return targetChapter[verse + ''];
> ```

Do you need this ? because`object[Number(propertyName)]` is the same as `object[String(propertyName)]` right?

---

*[src/js/reducers/resourcesReducer.js, line 91 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaQRVX0ppV611hZfxv:-LCaQRVX0ppV611hZfxw:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/reducers/resourcesReducer.js#L91)):*
> ```JavaScript
>  */
> export const getTargetChapter = (state, chapter) => {
>   return state.bibles.targetLanguage.targetBible[chapter + ''];
> ```

Same as above

---

*[src/js/reducers/resourcesReducer.js, line 104 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaQSqY1JTg4BlJ7B7D:-LCaQSqY1JTg4BlJ7B7E:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/reducers/resourcesReducer.js#L104)):*
> ```JavaScript
>   const originalChapter = getOriginalChapter(state, chapter);
>   if (originalChapter) {
>     return originalChapter[verse + ''];
> ```

Same as above

---

*[src/js/reducers/resourcesReducer.js, line 117 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaQU314p8SME2EUg6M:-LCaQU314p8SME2EUg6N:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/reducers/resourcesReducer.js#L117)):*
> ```JavaScript
>  */
> export const getOriginalChapter = (state, chapter) => {
>   return state.bibles.originalLanguage.ugnt[chapter + ''];
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Reviewed 5 of 281 files at r1.
Review status: 281 of 284 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 I've tried everything I can think of and cannot reproduce this error. What version of the ScripturePane do you have under tC_apps?

 @neutrinog - using the commit you have in tC PR (and WA).  I will do a sandbox build to make sure it is not my configuration.

**Comment by PhotoNomad0** [comment]
@neutrinog - Made a sandbox build and still seeing errors, maybe you can look and see if there is anything missing here.  https://github.com/unfoldingWord-dev/translationCore/tree/sandbox-joels_wa_rewrite

Seeing same error on both Windows and Mac sandbox builds:

screen shot 2018-05-16 at 8 36 58 am

**Comment by da1nerd** [comment]
Review status: 281 of 284 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[__tests__/CSVExportActions.test.js, line 52 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCa4Re38SqrKD-MXSSY:-LCdva0X2GLPhoJjsd_H:b-we5v1p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/__tests__/CSVExportActions.test.js#L52)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Should your name be here? haha
</blockquote></details>

I just thought it would be nice for posterity :P

---

*[src/js/actions/WordAlignmentActions.js, line 3 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaEQFfCazBMXxaXfR6:-LCdxUxw9svupFCDgZDz:b-zf95cu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ddb7090a963c237d167221a6609d72dcbcad9c89/src/js/actions/WordAlignmentActions.js#L3)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do we still need this file still?
</blockquote></details>

For now yes. This will eventually be replaced, but that depends on some other things like the word map.
We are going to move the usfm3 generation into a new module that will convert alignment data (from word map) to usfm3. However, we're still working out the new file format for alignment data.

---

*[src/js/containers/ToolContainer.js, line 142 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaJQNG5C1rqJvHkfSp:-LCdyIue2CrBSeICOTRe:b-635jmp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L142)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

should this return a Promise like it does when it fails?
</blockquote></details>

No, this is an `async` function and will automatically resolve as a promise.
I can actually simplify this further by removing the try-catch's since async methods will automatically capture exceptions/rejections and handle them like `Promise.reject()`.

This was first not async so I must have forgotten to remove the redundant extra try-catch.

---

*[src/js/containers/ToolContainer.js, line 157 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaJd8v9ISeRCN-7i-r:-LCe0ZhG6VKasyVAVucB:b-g30hn6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L157)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

In the above function it checks if the file path exists, but in this one its not?
</blockquote></details>

I've removed the file check in the previous method. Checking if the file exists in the reading method is not a good practice since throwing an error will not give you any extra information. Instead we'll use the `onProjectFileExistsSync` (and possibly an async version in the future) to check if a file exists.

---

*[src/js/reducers/resourcesReducer.js, line 79 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCaPdN3BVgWcVKvdGYK:-LCe1QeiCqqYrxxr5oAb:bc0uriu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/reducers/resourcesReducer.js#L79)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do you need this ? because`object[Number(propertyName)]` is the same as `object[String(propertyName)]` right?
</blockquote></details>

Technically yes, however casting as a string is more descriptive since it's clear we are accessing an object key not an array index.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by da1nerd** [comment]
@PhotoNomad0 reiterating for posterity.
I checked out the sandbox build and confirmed it's not using my wA changes. It's still using the current version. This makes sense since travis pulls the current version of all the tools before building.

**Comment by mannycolon** [comment]
Reviewed 29 of 281 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ToolContainer.js, line 122 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCe9GSA1Q4hUo88PInx:-LCe9GSA1Q4hUo88PIny:b-1gihqe) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L122)):*
> ```JavaScript
>     const {projectSaveLocation} = this.props;
>     const writePath = path.join(projectSaveLocation,
>       '.apps/translationCore/', filePath);
> ```

we may want to do path.join(projectSaveLocation, '.apps', 'translationCore', filePath) to avoid issues on windows machines

---

*[src/js/containers/ToolContainer.js, line 135 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCe9_K9CNMYci5Tmhej:-LCe9_K9CNMYci5Tmhek:bb6wvp5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L135)):*
> ```JavaScript
>     const {projectSaveLocation} = this.props;
>     const readPath = path.join(projectSaveLocation,
>       '.apps/translationCore/', filePath);
> ```

IBID

---

*[src/js/containers/ToolContainer.js, line 169 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCe9qTK2YEMiWUMbk9f:-LCe9qTK2YEMiWUMbk9g:bb6wvp5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L169)):*
> ```JavaScript
>     const {projectSaveLocation} = this.props;
>     const readPath = path.join(projectSaveLocation,
>       '.apps/translationCore/', filePath);
> ```

IBID

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by da1nerd** [comment]
*[src/js/containers/ToolContainer.js, line 122 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCe9GSA1Q4hUo88PInx:-LCeBFce-rOGMEcositv:b-22t6fp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4fefb36d241f4ae35638705e1c68765efa02669f/src/js/containers/ToolContainer.js#L122)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we may want to do path.join(projectSaveLocation, '.apps', 'translationCore', filePath) to avoid issues on windows machines
</blockquote></details>

fs implicitly converts folder path separators. https://shapeshed.com/writing-cross-platform-node

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by mannycolon** [comment]
@neutrinog SO how come in the past we have encounter problems with it ?

**Comment by da1nerd** [comment]
@mannycolon I'd need to know more about the situation.

Depending on how the file paths were joined you may have needed to normalize them (e.g. if the path contained `/../`).
`fs.join` will automatically normalize the path, but if the paths were manually concatenated and then passed to `fs` for writing/reading it's likely there would have been issues cross platform.

**Comment by mannycolon** [comment]
Code Review: `LGTM`
Local Test: `Found a Bug`*
*See below

**Comment by mannycolon** [comment]
screen shot 2018-05-16 at 2 34 29 pm

**Comment by da1nerd** [comment]
@mannycolon are you testing this with https://github.com/translationCoreApps/wordAlignment/pull/35 ?

**Comment by mannycolon** [comment]
Yes

**Comment by mannycolon** [comment]
This is the wA branch Im using `enhancement/joel/4319/rewrite`

**Comment by mannycolon** [comment]
[en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/2010400/en_tit.zip)
This is the project I loaded

**Comment by RoyalSix** [comment]
Review status: 280 of 284 files reviewed at latest revision, 7 unresolved discussions.

---

*[__tests__/CSVExportActions.test.js, line 52 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCa4Re38SqrKD-MXSSY:-LCeKd3VBpdIDtq5ZfxO:b-l0itmu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ceb2e8b45f67700a7c784b6c9a6e92f3dad56a36/__tests__/CSVExportActions.test.js#L52)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

I just thought it would be nice for posterity :P
</blockquote></details>

Haha ok, and what is being found?

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Reviewed 3 of 281 files at r1, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: 283 of 284 files reviewed at latest revision, 7 unresolved discussions.

---

*[__tests__/CSVExportActions.test.js, line 52 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489#-LCa4Re38SqrKD-MXSSY:-LCeMpLXBftCAzcFXZFP:b-fqduua) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ceb2e8b45f67700a7c784b6c9a6e92f3dad56a36/__tests__/CSVExportActions.test.js#L52)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Haha ok, and what is being found?
</blockquote></details>

Nevermind its gone now haha

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`

**Comment by RoyalSix** [comment]
Got the same error as above

**Comment by mannycolon** [comment]
I got the following error now
```
/Users/mannycolon/dev/translationCore/src/js/actions/ToolSelectionActions.js:74 TypeError: Cannot use 'in' operator to search for 'container' in undefined
    at /Users/mannycolon/dev/translationCore/src/js/actions/ToolSelectionActions.js:74:10
    at /Users/mannycolon/dev/translationCore/node_modules/redux-thunk/lib/index.js:11:18
    at dispatch (/Users/mannycolon/dev/translationCore/node_modules/redux/lib/applyMiddleware.js:45:18)
    at /Users/mannycolon/dev/translationCore/src/js/actions/ToolSelectionActions.js:36:9
```

**Comment by mannycolon** [comment]
I loaded [en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/2010400/en_tit.zip) and launched the wA tool. I also get stuck on the loading modal screen.
screen shot 2018-05-16 at 4 07 56 pm

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4489)*

**Comment by mannycolon** [comment]
screen shot 2018-05-17 at 3 29 40 pm

**Comment by mannycolon** [comment]
screen shot 2018-05-17 at 3 29 49 pm
screen shot 2018-05-17 at 3 29 57 pm

**Comment by mannycolon** [comment]
@neutrinog I got the errors above when I load a project with translationWords

**Comment by mannycolon** [comment]
@neutrinog wA works fine.

**Pull request merged**
