### PR TITLE
Feature #3273 /Update to use UGNT resources

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Update app to use UGNT resources.

##### Merge order: 
ScripturePane: https://github.com/translationCoreApps/ScripturePane/pull/82
translationCore: https://github.com/unfoldingWord-dev/translationCore/pull/3639
usfm-js: https://github.com/translationCoreApps/usfm-js/pull/26
tC_Resources: https://github.com/translationCoreApps/tC_Resources/pull/15

#### How to test this pull request:

Need these parts loaded:
ScripturePane: https://github.com/translationCoreApps/ScripturePane/pull/82
tC_Resources: https://github.com/translationCoreApps/tC_Resources/pull/15

Import a new project from USFM.  When you open the WA and TW tools, they will initialize alignment using UGNT and should work fine (greek words shown).  Should see UGNT as option for source. Add it as a source language and compare to BHP.  All the words should be there.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3639)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 3 of 5 files at r1, 46 of 46 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3639)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3639#-:-L2g09pl1NaA2BFuXUFY:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 46 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3639#-:-L34YUAmaQAo8xQpOuEw:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3639)*

**Pull request merged**
