### PR TITLE
Feature 4885/Improve performance of Project Import and selection

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated to latest usfm-js with Joel's performance tweak
- modified app to just parse USFM header data to get project details.

#### Please include detailed Test instructions for your pull request:
-  Should see noticeable speed up to USFM3 import and project selection.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (842ed9d)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-842ed9d.zip) is ready for download.
[macOS build 1.0.0 (842ed9d)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-842ed9d.dmg) is ready for download.
[Windows x64 build 1.0.0 (842ed9d)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-842ed9d.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (842ed9d)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-842ed9d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (eedeadd)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-eedeadd.zip) is ready for download.
[macOS build 1.0.0 (eedeadd)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-eedeadd.dmg) is ready for download.
[Windows x64 build 1.0.0 (eedeadd)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-eedeadd.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (eedeadd)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-eedeadd.setup.exe) is ready for download.

**Comment by cckozie** [comment]
Current timings importing/selecting fully aligned Acts on macOS build 1.0.0 (eedeadd)
Import: 10 seconds
Select: 4 seconds

**Comment by da1nerd** [comment]
___
*[src/js/helpers/usfmHelpers.js, line 6 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-LJzWU8GEeSo3qUPTIf4:-LJzWU8GEeSo3qUPTIf5:b724yz4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eedeadd01c6455cd154a86979f9d0ce0b84c410e/src/js/helpers/usfmHelpers.js#L6)):*
> ```JavaScript
> // helpers
> import * as bibleHelpers from './bibleHelpers';
> import * as usfmHelpers from './usfmHelpers';
> ```

Why is this module importing itself?

**Review by da1nerd — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

___
*[src/js/helpers/usfmHelpers.js, line 61 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-LJzX6se9MuIdFMbIZAK:-LJzX6se9MuIdFMbIZAL:b-189ytf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eedeadd01c6455cd154a86979f9d0ce0b84c410e/src/js/helpers/usfmHelpers.js#L61)):*
> ```JavaScript
>   const pos = usfmData.indexOf('\\c ');
>   const header = (pos >= 0) ? usfmData.substr(0, pos) : usfmData; // if chapter marker is found, process only that part
>   return usfmHelpers.getParsedUSFM(header);
> ```

This method is in the same file. There's no need to import itself to use the function.
Doing so is a circular import.

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0 and @neutrinog)

___
*[src/js/helpers/usfmHelpers.js, line 6 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-LJzWU8GEeSo3qUPTIf4:-LJzwakZC2IroWOFALFU:b5qq3ys) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eedeadd01c6455cd154a86979f9d0ce0b84c410e/src/js/helpers/usfmHelpers.js#L6)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Why is this module importing itself?
</blockquote></details>

InteliJ copy/paste artifact?
___
*[src/js/helpers/usfmHelpers.js, line 61 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-LJzX6se9MuIdFMbIZAK:-LJzwhIu2tWkjBBiM2Id:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eedeadd01c6455cd154a86979f9d0ce0b84c410e/src/js/helpers/usfmHelpers.js#L61)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

This method is in the same file. There's no need to import itself to use the function.
Doing so is a circular import.
</blockquote></details>

Done.

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @neutrinog)

___
*[src/js/helpers/usfmHelpers.js, line 6 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-LJzWU8GEeSo3qUPTIf4:-LJzwxekBMBkluM0HfKk:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eedeadd01c6455cd154a86979f9d0ce0b84c410e/src/js/helpers/usfmHelpers.js#L6)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

InteliJ copy/paste artifact?
</blockquote></details>

Done.

**Review by da1nerd — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (9c564ae)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-9c564ae.zip) is ready for download.
[macOS build 1.0.0 (9c564ae)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-9c564ae.dmg) is ready for download.
[Windows x64 build 1.0.0 (9c564ae)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-9c564ae.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (9c564ae)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-9c564ae.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4896#-:-LK7LjuVALSnRxQCW58j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Pull request merged**
