### PR TITLE
Bugfix 6430/User is not warned when Create New Repo or Rename repo functions fail

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated version to 2.1.0
- cleanup - moved actions out of ProjectDetailsHelpers to ProjectDetailsActions and updated unit tests
- added await while error message displayed - this fixes race condition that import just continued on after error clobbering error messages.
- refactored - removed recursive calls on repo failures
- fixes for git creating new repo

#### Please include detailed Test instructions for your pull request:
- checkout branch, do `npm run load-apps`, `npm ci`, and `npm start`
- do tests in https://github.com/unfoldingWord/translationCore/issues/6430

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6494)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (ecb9550)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.0.0-ecb9550.deb) is ready for download.
[macOS build 2.0.0 (ecb9550)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.0.0-ecb9550.dmg) is ready for download.
[Windows x64 build 2.0.0 (ecb9550)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.0.0-ecb9550.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (ecb9550)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.0.0-ecb9550.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (85ac15c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.0.0-85ac15c.deb) is ready for download.
[macOS build 2.0.0 (85ac15c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.0.0-85ac15c.dmg) is ready for download.
[Windows x64 build 2.0.0 (85ac15c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.0.0-85ac15c.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (85ac15c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.0.0-85ac15c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (f5c40ed)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.0.0-f5c40ed.deb) is ready for download.
[macOS build 2.0.0 (f5c40ed)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.0.0-f5c40ed.dmg) is ready for download.
[Windows x64 build 2.0.0 (f5c40ed)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.0.0-f5c40ed.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (f5c40ed)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.0.0-f5c40ed.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (3879b1c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.0.0-3879b1c.deb) is ready for download.
[macOS build 2.0.0 (3879b1c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.0.0-3879b1c.dmg) is ready for download.
[Windows x64 build 2.0.0 (3879b1c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.0.0-3879b1c.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (3879b1c)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.0.0-3879b1c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (52c56f7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.0.0-52c56f7.deb) is ready for download.
[macOS build 2.0.0 (52c56f7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.0.0-52c56f7.dmg) is ready for download.
[Windows x64 build 2.0.0 (52c56f7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.0.0-52c56f7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (52c56f7)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.0.0-52c56f7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d6115e4)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-linux-x64-2.1.0-d6115e4.deb) is ready for download.
[macOS build 2.1.0 (d6115e4)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-macos-x64-2.1.0-d6115e4.dmg) is ready for download.
[Windows x64 build 2.1.0 (d6115e4)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x64-2.1.0-d6115e4.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d6115e4)](https://tc-builds.door43.org/build/bugfix-mcleanb-6430/translationCore-win-x32-2.1.0-d6115e4.setup.exe) is ready for download.

**Comment by cckozie** [comment]
Tests run importing this project without changing the translation id: https://git.door43.org/tc01/fr_tit_ulb 
This worked without errors using the 2.0 release build.

Running 2.0.0 (52c56f7) - After clicking the Create New Repo button on the project renamed alert, I get this message: Create new repository failed because a repository with this name already exists.

Running 2.1.0 (d6115e4) - The initial startup after installing this build took a long time. Is it doing some additional migrations or installing new resources?
While importing the referenced project I received this error after clicking Continue on the Missing Verses screen, although the project does appear in my project list:
Error occurred while importing your project.
Could not download the project from https://git.door43.org/tc01/fr_tit_ulb to /Users/cckozie/translationCore/imports/fr_tit_ulb

**Comment by PhotoNomad0** [comment]
@cckozie - thanks for looking at this and testing the builds.  Yes when I changed the version to 2.1.0, it triggers resource updates.

**Comment by PhotoNomad0** [comment]
@cckozie - are you logged in as tc01 when running these tests?

**Comment by cckozie** [comment]
@PhotoNomad0 - Yes, logged in as tc01

**Comment by PhotoNomad0** [comment]
@cckozie - new build for testing.  I think I found fix for issue you saw in 2.1.0 (d6115e4).  If you still see the problem you saw in 2.0.0 (52c56f7), suggest you double check that project does not exist in tc01 on D43.  If still is problem, I'll probably need to look at the logs.
 
From the release-v2.1.0-test branch:
[macOS build 62c63ca (v2.1.0)](https://tc-builds.door43.org/build/release-v2.1.0-test/translationCore-macos-x64-2.1.0-62c63ca.dmg) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 
The two issues noted are both fixed in 2.1.0 (62c63ca). BTW: The fr_ulb_tit_book project does exists in tc01's repos. The fact that tC didn't catch that probably is a bug, but since we no longer use the fr_ulb_tit naming convention, I don't think it's worth dealing with. Looks like the problem I pointed out in 2.0.0 (52c56f7) really wasn't one.
It now passes all of my tests which specifically test imports. I'll continue testing with my other scripts, most of which do imports too.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
