### PR TITLE
Clear Local Storage When App Is Caught In Restart Loop

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/282)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/pages/app.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282#-KWAqTCCHN_PsfKXOrZf:-KWAqTCCHN_PsfKXOrZg:b-h51c7a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/acee7e7288f49c3d96e577004979340bde296f50/src/js/pages/app.js#L33)):_

> ``` JavaScript
>   getInitialState() {
>     var tutorialState = api.getSettings('showTutorial');
>     debugger;
> ```

Gotta remove the debugger. Otherwise, it looks good. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282)_

**Comment by ihoegen** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282)_

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282)_

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/pages/app.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282#-KWAqTCCHN_PsfKXOrZf:-KWFTsMNuyUxu0dR8vsW:b2ni9ah) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/acee7e7288f49c3d96e577004979340bde296f50/src/js/pages/app.js#L33)):_
<details><summary>

<i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary>



> Gotta remove the debugger. Otherwise, it looks good. 
> </details>
> ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282)_

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/282)_

**Pull request merged**
