### PR TITLE
Made changes to improve the scripture pane and expanded scripture pane performance

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Made changes to improve the scripture pane and expanded scripture pane performance

#### Please include detailed Test instructions for your pull request:
- **Dependencies:**
   - https://github.com/translationCoreApps/ScripturePane/pull/107
   -  https://github.com/translationCoreApps/wordAlignment/pull/29
- Open a project with **tW** and verify that if you click on a Greek word it opens a pop-up that includes the word's lexicon details.
- Click the icon to open the expanded scripture pane and it should open in less than 3 seconds.
- Also, verify that all Greek words have the lexicon details in the expanded scripture pane.

#### Standard Test Instructions for PR Review Process:

- [x] Double check unit tests that have been written
- [x] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [x] Checkout the branch locally and ensure that app runs as expected
  - [x] Ensure tests pass
  - [x] Open and watch the console for errors
  - [x] Make sure all actions perform as expected
  - [x] Import and Load a new Project
  - [x] Load a tool and perform basic actions
  - [x] Switch tools and perform basic actions
  - [x] Switch project to an existing project
  - [x] Load a tool and perform basic actions
  - [x] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4098)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM` except for negative test coverage
(edited)

**Comment by RoyalSix** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4098)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4098)*

**Comment by PhotoNomad0** [comment]
~testing LGTM~
code review looks good other than test coverage in Resource.* files.

**Comment by PhotoNomad0** [comment]
Also probably should remove this also:  https://github.com/translationCoreApps/wordAlignment/blob/a5cd5fe6d49d90ce80bc11da1dfc2e7899139f7e/src/components/PrimaryWord.js#L47

**Comment by PhotoNomad0** [comment]
Testing in WA tool.  See some issues clicking on the greek in word cards after changing verses.  I can see the lexicon for  the greek word cards when I first open WA, but then I change the verse and many of the greek word cards don't have lexicon entries.

**Comment by mannycolon** [comment]
> Testing in WA tool. See some issues clicking on the greek in word cards after changing verses. I can see the lexicon for the greek word cards when I first open WA, but then I change the verse and many of the greek word cards don't have lexicon entries.

@PhotoNomad0 I cant recreate this problem.

**Comment by mannycolon** [comment]
> Testing in WA tool. See some issues clicking on the greek in word cards after changing verses. I can see the lexicon for the greek word cards when I first open WA, but then I change the verse and many of the greek word cards don't have lexicon entries.

Fixed

**Comment by richmahn** [comment]
Reviewed 1 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4098)*

**Comment by richmahn** [comment]
Code: LGTM
Local Testing: In Progress

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4098#-:-L88xq9cDqUkDIfWal7w:bcipd8l)*

**Comment by bspidel** [comment]
Reviewed 1 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4098)*

**Comment by richmahn** [comment]
Guess it was merged, but local testing passed.

**Pull request merged**
