### PR TITLE
Feature 4550/rename project on dcs

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-  all DCS renaming issues.  At this point all of issue https://github.com/unfoldingWord-dev/translationCore/issues/3421 should be working.

#### Please include detailed Test instructions for your pull request:
- in tCore test all kinds of import, project renaming to make sure it follows the chart.  There is an change to a prompt at the bottom of the issue, and we added an exception that if the project does not belong to current logged in user we will not rename on DCS.  There will just be a local renaming prompt.
- have a table of expected actions for various project types on the team drive https://drive.google.com/drive/folders/1H9-Yo0Vgow9XW0MyPQZfmyzqJCkforYm, document "Testing Imports - Workflow"

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4669)

### CODE REVIEW

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r4, 5 of 14 files at r5, 22 of 22 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4669)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[tC_apps/wordAlignment, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4669#-LHZFE1W-3SkaMi60w44:-LHZFE1W-3SkaMi60w45:bko0c5g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bf0759722659d5e7bf28b1793a03187caf0447f5/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit 3fed27359c0a3a8d38f556a608a7cfa3764283ff
> ```

should this be here? maybe merge w/ latest develop branch.

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Comment by mannycolon** [comment]
**When loading a project from DCS I get to the following modal**

screen shot 2018-07-17 at 2 40 14 pm

**When I click continue the following happens (Look at top part of the modal).
After clicking continue again multiple seconds go by and I do not get a loading screen but it just lags  for like 30-45 seconds and then goes to the next page.**


screen shot 2018-07-17 at 2 40 21 pm

**This is the next page and the modal its still not rendering properly.**


screen shot 2018-07-17 at 2 40 32 pm

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-19406a9.zip) is ready for download.
[macOS build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-19406a9.dmg) is ready for download.
[Windows x64 build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-19406a9.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-19406a9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-19406a9.zip) is ready for download.
[macOS build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-19406a9.dmg) is ready for download.
[Windows x64 build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-19406a9.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (19406a9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-19406a9.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
Is it ok if the string is missing?
screen shot 2018-07-17 at 6 11 01 pm

**Comment by RoyalSix** [comment]
I tried importing this [project](https://git.door43.org/royalsix/en_jay_tit_book)
I use online import.
I press cancel on the project details screen but the project still gets imported when it shouldn't
Note: I'm using the build

**Comment by PhotoNomad0** [comment]
> Is it ok if the string is missing?

Good catch - not OK for English

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (79fb6f7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-79fb6f7.zip) is ready for download.
[macOS build 0.10.1 (79fb6f7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-79fb6f7.dmg) is ready for download.
[Windows x64 build 0.10.1 (79fb6f7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-79fb6f7.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (79fb6f7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-79fb6f7.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
> I tried importing this project
> I use online import.
> I press cancel on the project details screen but the project still gets imported when it shouldn't
> Note: I'm using the build

@RoyalSix - did you see the cancel confirmation prompt?  Cancelling worked fine for me with local build, and worked fine on the latest build (Windows x64 build 0.10.1 (79fb6f7)) on another PC.  Are you sure you didn't have a project with the same name already loaded?

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (be412c0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-be412c0.zip) is ready for download.
[macOS build 0.10.1 (be412c0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-be412c0.dmg) is ready for download.
[Windows x64 build 0.10.1 (be412c0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-be412c0.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (be412c0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-be412c0.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Code Review: `LGTM`
Both local and Online import: `LGTM`

**Comment by RoyalSix** [comment]
`LGTM`

**Pull request merged**
