### PR TITLE
Updated UDB reference to UDT

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated UDB reference to UDT

#### Please include detailed Test instructions for your pull request:
- [ ] Verify that all **UDB** and **Unlocked Dynamic Bible** references were removed from the UI and replaced with **UDT** and **unfoldingWord Dynamic Text** respectively.
- [ ] Verify highlights appear correctly for the UDT, except for Titus 2:10 in the UDT because it hasn't been aligned to the greek.

- **Dependencies:**
  - https://github.com/translationCoreApps/tC_Resources/pull/36
  - https://github.com/translationCoreApps/ScripturePane/pull/106
  - https://github.com/translationCoreApps/VerseCheck/pull/95

- **Recommended merge order:**
  - Merge this PR and then the rest.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4089)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 25 of 26 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4089)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 25 of 25 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4089#-:-L7ylfUf3KBQOi5MOqN3:bnfp4nl)*

**Comment by richmahn** [comment]
Needs to be changed to version alpha.26 due to changes in tC_resources.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4089#-:-L7zELxkjxVJPHTJUQ6N:b-qmmp3r)*

**Comment by richmahn** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4089#-:-L7zqYLtkMIWqlLas5-r:b-uwkowd)*

**Pull request merged**
