### PR TITLE
sortWordObjectsByString

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Adds function and tests for sortWordObjectsByString in wordAlignmentHelpers

#### How to test this pull request:

Review and run tests.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2805)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Code looks, good. 
Should this be in the tools repo?
And the tests are failing from ```Cannot find module '../helpers/WordAlignmentHelpers' from 'WordAlignmentActions.js'```

**Comment by klappy** [comment]
Okay, there were some mixed capitalization issues that I can fix. Our convention use to be only use first capitalization on react components not helpers/util files.

I fixed one reference but missed that one.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2805#-:-Kv7qCKaKYdzCIwmPzO0:b-8o0iy4)*

**Comment by klappy** [comment]
These helpers are used primarily by the actions that feed the reducer. So in the core closest to the use case makes sense here. We may create a module for these as they are 90% the same as selection helpers in VerseCheck. Refactoring and sharing that code would keep it DRY. That's another reason I wanted to put those in the core and share them with the tools as they will be shared more and more over time. It would have also saved time and effort in this implementation as we would have already had some of the building blocks and just adapted to them, instead, we had to copy/paste them and modify them to meet our needs. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2805#-:-Kv7qUegnBTDkzbGzF2Z:bjntqqg)*

**Comment by klappy** [comment]
@royalsix Done

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2805#-:-Kv7s0C9P9qSUp02A5Hh:bu7dcmk)*

**Comment by klappy** [comment]
@neutrinog @RoyalSix: The errors causing this PR to fail are due to timeouts. We need to either set higher timeouts or rewrite the tests so that they don't take too long. One is quicker, the other is the right long-term answer :)

**Comment by klappy** [comment]
@RoyalSix @neutrinog: I got tests to pass by asking travis to rebuild multiple times. Sometimes tests timeout, that's why they were failing. But if I ask Travis really nicely, it builds and passes :)

**Comment by da1nerd** [comment]
I've noticed that too. It hasn't been happening consistently so I haven't done anything about it. But I agree the tests need to be rewritten. :)

**Pull request merged**
