### PR TITLE
Fixed Styling On Menu Buttons After Making Report

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/678)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/login/Login.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678#-KcZcxhpugcc8LaxKIQP:-KcZcxhpugcc8LaxKIQQ:b-qqiaxy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ac8fa7f23095aba486ed0c08d268edf6c126c8e2/src/js/components/core/login/Login.js#L23)):*
> ```JavaScript
>       return (
>         <div>
>           <style type="text/css">
> ```

Thanks for removing this.

---

*[src/js/components/core/login/Login.js, line 36 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678#-KcZcsFBBboS5zbygFgn:-KcZcsFBBboS5zbygFgo:b-n2uafa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a9c197a1a8eab459e0f0949dd7337fb710078c0/src/js/components/core/login/Login.js#L36)):*
> ```JavaScript
>     }
>   }
>   render() {
> ```

Do we have to set these constants in render? It would be better if we could do that somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678)*

**Comment by EllDoubleYew** [comment]
I just tested and can confirm that it addresses the issue very well. Nice work @RoyalSix 👍

**Comment by mannycolon** [comment]
@RoyalSix why did you have to remove the way the styling was being structured??? it is a react bootstrap custom styling introduced by React. so I wonder why you took it off?? and why was this causing it to re-arrange???

**Comment by mannycolon** [comment]
@EllDoubleYew dont merge this yet

**Comment by mannycolon** [comment]
@RoyalSix another question where are you using the `style-it` module ?

**Comment by RoyalSix** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/login/Login.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678#-KcZcxhpugcc8LaxKIQP:-KcZsbGJMo2O9ENX1Fti:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ac8fa7f23095aba486ed0c08d268edf6c126c8e2/src/js/components/core/login/Login.js#L23)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Thanks for removing this.
</blockquote></details>

Done.

---

*[src/js/components/core/login/Login.js, line 36 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678#-KcZcsFBBboS5zbygFgn:-KcZsbwDCuKg8gzLD3sL:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a9c197a1a8eab459e0f0949dd7337fb710078c0/src/js/components/core/login/Login.js#L36)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Do we have to set these constants in render? It would be better if we could do that somewhere else.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/678)*

**Pull request merged**
