### PR TITLE
Duplicate Name Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- There was an issue with the name showing twice in the project upload successful dialog

#### Please include detailed Test instructions for your pull request:
- Upload a project and ensure the text for the name only shows once.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6187)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (2b12cf7)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-linux-x64-1.2.0-2b12cf7.deb) is ready for download.
[macOS build 1.2.0 (2b12cf7)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-macos-x64-1.2.0-2b12cf7.dmg) is ready for download.
[Windows x64 build 1.2.0 (2b12cf7)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-win-x64-1.2.0-2b12cf7.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (2b12cf7)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-win-x32-1.2.0-2b12cf7.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6187)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
Tested with build above and have wrong text: 

Screen Shot 2019-06-28 at 7 53 16 AM

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/ProjectUploadActions.js, line 133 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6187#-LiSwS0s3ItDPqptkh6f:-LiSwS0s3ItDPqptkh6g:b-apych7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b12cf71e7de3da505dd8f0b915b29b9bc4d6b07/src/js/actions/ProjectUploadActions.js#L133)):*
> ```JavaScript
>                   <div>
>                     <span>
>                       {translate("projects.upload_successful_alert")}&nbsp;
> ```

You probably shouldn't have modified this line - the translation is expecting a username.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (eb8278a)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-linux-x64-1.2.0-eb8278a.deb) is ready for download.
[macOS build 1.2.0 (eb8278a)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-macos-x64-1.2.0-eb8278a.dmg) is ready for download.
[Windows x64 build 1.2.0 (eb8278a)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-win-x64-1.2.0-eb8278a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (eb8278a)](https://tc-builds.door43.org/build/bugfix-jay-4577/translationCore-win-x32-1.2.0-eb8278a.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
@PhotoNomad0 This should be fixed, tested.

**Pull request merged**
