### PR TITLE
Added React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR changes dependencies to enable react 16

#### How to test this pull request:
Make sure tests pass and the app functions as normal

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3626)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3626)*

**Comment by klappy** [comment]
Shouldn't there be a commit to the package.json as well?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3626#-:-L2QSyQDxvcrWonKUZ7F:b-a05hgb)*

**Comment by RoyalSix** [comment]
### todo:
- <s>Update jest tests param in package.json</s>
- <s>Update status bar test</s>
- <s>bring back the latest version of fs-extra</s>
- <s>ChapterViewModal test, View test</s>
- <s>THelps fs-extra, remove extra dependencies</s>
- <s>VerseCheck remove extra dependencies<s/>
- <s>Popup positioning</s>

**Comment by RoyalSix** [comment]
Terms and conditions does not work anymore

**Pull request closed without merging**
