### PR TITLE
Merge latest v1.1.4

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- update develop with latest v1.1.4 changes

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6066)

### CODE REVIEW

**Comment by mannycolon** [comment]
`FYI: WHEN TESTING THIS BRANCH PLEASE MAKE SURE ALL FUNCTIONALITIES OF THE SOURCE CONTENT UPDATER WORK PROPERLY IN TC`

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f718188)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-f718188.deb) is ready for download.
[macOS build 1.2.0 (f718188)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-f718188.dmg) is ready for download.
[Windows x64 build 1.2.0 (f718188)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-f718188.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f718188)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-f718188.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
> FYI: WHEN TESTING THIS BRANCH PLEASE MAKE SURE ALL FUNCTIONALITIES OF THE SOURCE CONTENT UPDATER WORK PROPERLY IN TC

@mannycolon - not sure why you are focused on the source content updater, it is the same one as already in develop branch.

But we should update the resources so the date is newer than 1.1.4

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (26da57f)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-26da57f.deb) is ready for download.
[macOS build 1.2.0 (26da57f)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-26da57f.dmg) is ready for download.
[Windows x64 build 1.2.0 (26da57f)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-26da57f.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (26da57f)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-26da57f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0d5f725)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-0d5f725.deb) is ready for download.
[macOS build 1.2.0 (0d5f725)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-0d5f725.dmg) is ready for download.
[Windows x64 build 1.2.0 (0d5f725)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-0d5f725.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0d5f725)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-0d5f725.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0602227)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-0602227.deb) is ready for download.
[macOS build 1.2.0 (0602227)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-0602227.dmg) is ready for download.
[Windows x64 build 1.2.0 (0602227)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-0602227.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0602227)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-0602227.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (88a26ac)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-88a26ac.deb) is ready for download.
[macOS build 1.2.0 (88a26ac)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-88a26ac.dmg) is ready for download.
[Windows x64 build 1.2.0 (88a26ac)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-88a26ac.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (88a26ac)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-88a26ac.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (5ca2399)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-linux-x64-1.2.0-5ca2399.deb) is ready for download.
[macOS build 1.2.0 (5ca2399)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-macos-x64-1.2.0-5ca2399.dmg) is ready for download.
[Windows x64 build 1.2.0 (5ca2399)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x64-1.2.0-5ca2399.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (5ca2399)](https://tc-builds.door43.org/build/merge-latest-v1.1.4/translationCore-win-x32-1.2.0-5ca2399.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
In 1.1.3 loaded https://git.door43.org/lrsallee/en_ult_rut_book, and then ran 1.1.4 which updated the timestamp in .categories, and then ran this PR and noticed that hasNewGroupsData() did not flag resources as updated since the time stamp is newer than the resource time in these resources.  This left .categories as:

`{"current":["kt","other","names"],"loaded":["kt","names","other","almighty","anoint","bless","brother","children","clean","command","covenantfaith","falsegod","favor","fear","forsake","god","good","heart","hope","inherit","israel","judge","life","lord","love","moab","name","peopleofgod","redeem","rest","restore","son","testimony","true","witness","work","yahweh","bethlehem","boaz","david","ephrathah","jesse","judah","judea","leah","rachel","ruth","tamar","afflict","barley","bow","bread","bury","comfort","conceive","confirm","death","elder","family","famine","father","foreigner","gate","generation","glean","grain","hand","harvest","house","kind","offspring","peoplegroup","prosper","reap","rebuke","refuge","reproach","reward","sandal","servant","thresh","wheat","winnow"],"timestamp":"2019-05-10T12:41:22.132Z"}`

Note: this is a pre-existing condition in develop branch.  Recommend not changing time stamp to current time, but to resources update time and regenerate resources whenever times are different.

**Comment by PhotoNomad0** [comment]
See another issue in 1.2.0:

Loaded https://git.door43.org/lrsallee/en_ult_rut_book, and turn off all selections.  If you turn on kt, then "names" also comes up selected as indeterminate.  Looks like a data error that "moab" is both in kt and names category.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6066)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
