### PR TITLE
Feature - #3296 - Has Home ToolCard use same progress bar as Tool page

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Addresses #3296 

Also fixes how paths in tests were not done right for running jest on Windows. Made path separator agnostic by using path.join()

#### How to test this pull request:

Login, pick project, pick tool, then go back to "Home". The progress bar there should display the same as on the Tool page: If percentage is < 25% it is in black in the middle, else white and in the middle of the filled part of the bar.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3615)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L275X2qAq3QDq2cEAcy:brsnwzo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
> ```JavaScript
>       actions: {}
>     };
>     state.reducers.toolsReducer.currentToolTitle = 'Current Tool Title';
> ```

I guess it might not matter because its a test, but the store object should be mutated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
@richmahn I was testing this with a project that had no checks to begin with (tW).
I did a few checks, went back to the home screen and the progress did not show.
After reloading the app the progress showed

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L27ANcOJ0Mg3uC3DW4s:b-s1lgkh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I guess it might not matter because its a test, but the store object should be mutated.
</blockquote></details>

should not*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2L_HSwFEyKMc4WTM5_:b-6ntf0a) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

should not*
</blockquote></details>

So how could this get set for a test then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by richmahn** [comment]
@RoyalSix It appears in my testing in this that the old way (develop branch) doesn't get an update of the percentage either. Trying to figure out how the projectDetailsReducer gets updated. Seems to get updated when I go to the Tools page, but not the Home page. Any ideas, or should leave it as is?

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r1, 2 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by klappy** [comment]
*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2MR1K3QRbMFK1l5hL9:bc0rwgs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

So how could this get set for a test then?
</blockquote></details>

We should have full access to all actions, but the bigger question is do we have an existing action for changing the Title? Or do you have to create a new one just for this test? If it's a major work around we need to weigh the time it takes to do it right vs the value of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by klappy** [comment]
Reviewed 6 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2W1zF6lqM4w4aHKoyj:bhlgiys) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We should have full access to all actions, but the bigger question is do we have an existing action for changing the Title? Or do you have to create a new one just for this test? If it's a major work around we need to weigh the time it takes to do it right vs the value of it.
</blockquote></details>

@klappy So are you saying I should try to emulate the calling of actions to set up the state before calling the actual function being tested? Is there a good example of that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by klappy** [comment]
*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2W2aBMlXM78KnxiScj:b-i9h9t1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

@klappy So are you saying I should try to emulate the calling of actions to set up the state before calling the actual function being tested? Is there a good example of that?
</blockquote></details>

Not sure exactly, Maybe @royalsix or @mannycolon can help you out here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2a3epxFz2zZluEWdm_:bg85b5v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Not sure exactly, Maybe @royalsix or @mannycolon can help you out here.
</blockquote></details>

you can dispatch the action ```        
dispatch({
          type: consts.SET_CURRENT_TOOL_TITLE,
          currentToolTitle: dataObject.title
        });
```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
You can dispatch an action like this @richmahn 
```
store.dispatch({
  type: consts.SET_CURRENT_TOOL_TITLE,
   currentToolTitle: title
});
```

**Comment by RoyalSix** [comment]
You can look at ```ProjectValidationActions.test``` for an example of how to get access to the dispatcher

**Comment by RoyalSix** [comment]
As to why its not updating when go back to the home screen, I couldn't figure that one out. If it wasn't introduced in this PR then it won't stop it from getting merged.

**Comment by klappy** [comment]
*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2g0Tq6Pa7jZHf8J7Ew:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

you can dispatch the action ```        
dispatch({
          type: consts.SET_CURRENT_TOOL_TITLE,
          currentToolTitle: dataObject.title
        });
```
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*
<!-- Sent from Reviewable.io -->

**Comment by klappy** [comment]
:lgtm:x

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-:-L2g0rJZu5NbXohEOMJo:bg7ignb)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2gBgRVK_rMcHbv5KlN:ba2by0e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Instead of dispatching actions to populate data in the mock store why dont you just fill in the data inside the reducers in the mock store?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Review by bspidel — APPROVED** [review]
LGTM

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-:-L2gFmEbWsfQHg5hymID:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/OverviewToolCard.test.js, line 60 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-L275X2qAq3QDq2cEAcx:-L2gFos7zwSOdwHXbTXk:b-dyyo8w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a9e6c8adf1be6b3e85d59dc6e4cf048d9bb90615/__tests__/OverviewToolCard.test.js#L60)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Instead of dispatching actions to populate data in the mock store why dont you just fill in the data inside the reducers in the mock store?
</blockquote></details>

@manny we have examples of both in out tests, and both mimic actual function behavior well LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
Reviewed 3 of 17 files at r6, 2 of 4 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 13 of 13 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3615#-:-L3UvgyReIylRaBzpi6R:bnfp4nl)*

**Pull request merged**
