### PR TITLE
Hides Example Check Module For Non Developers

### PR DESCRIPTION
**Pull request by RoyalSix**
via renaming

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/126)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126)_

**Comment by EllDoubleYew** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/js/components/core/MenuBar.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126#-KRdSh0eQFyDjImA_Kor:-KRdSh0fE-gXD2yJvSSM:b-58io6l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/892b1fc58f130cbe2b34863c47cbb436fbfeca1b/src/js/components/core/MenuBar.js#L80)):_

> ``` JavaScript
>            }
>          },
>          accelerator: 'CmdOrCtrl+C'
> ```

This command is most frequently used to copy, I dont know how good of an idea it is to block it off for this. May be best to just remove the hot key for this one.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126)_

**Comment by RoyalSix** [comment]
I need to make another push I actually changed that to "H" for Harambe, but either way works

**Comment by ihoegen** [comment]
H

**Comment by EllDoubleYew** [comment]
Do we need a hotkey for this feature? It seems like it would be used by a pretty small group to begin with. I wonder if there is a more discrete implementation without a hotkey.

**Comment by mannycolon** [comment]
@RoyalSix  what is missing in this branch in order to merge with develop?

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/js/components/core/MenuBar.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126#-KRj3kNtoXzrUYBaXENY:-KRj3kNu_iS9Vj3duLZy:b-14t3xh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/892b1fc58f130cbe2b34863c47cbb436fbfeca1b/src/js/components/core/MenuBar.js#L80)):_

> ``` JavaScript
>            }
>          },
>          accelerator: 'CmdOrCtrl+C'
> ```

did you already updated the cmdorctrl + c to H?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126)_

**Comment by mannycolon** [comment]
@RoyalSix when can you push to update this branch and merge with develop?

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/126)_

**Pull request merged**
