### PR TITLE
Fix - updates SCU to 0.2.16

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updates SCU so that tW group data only has one version when doing an update-resources

#### Please include detailed Test instructions for your pull request:
- `git checkout fix-richmahn-update-scu-to-0.2.14`
- `npm i`
- rename `tcResources/grc/translationHelps/translationWords/v0.4` to `v0.2`
- remove `grc/bibles/ugnt/v0.4`
- Run `npm run update-resources`
- See that transltionWords/v0.2 is not there, v0.4 is there.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5090)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (b869b0f)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-linux-x64-1.0.0-b869b0f.zip) is ready for download.
[macOS build 1.0.0 (b869b0f)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-macos-x64-1.0.0-b869b0f.dmg) is ready for download.
[Windows x64 build 1.0.0 (b869b0f)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-win-x64-1.0.0-b869b0f.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (b869b0f)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-win-x32-1.0.0-b869b0f.setup.exe) is ready for download.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5090)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @richmahn)

___
*[package.json, line 173 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5090#-LMs_IYZ45yp9BTbjOlg:-LMs_IYZ45yp9BTbjOlh:b-oc3wyc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b869b0fe5e209245b74f401d7826304ca3beaf27/package.json#L173)):*
> ```JSON
>     "string-punctuation-tokenizer": "0.8.0",
>     "sudo-prompt": "6.2.1",
>     "tc-source-content-updater": "^0.2.14",
> ```

Make this "tc-source-content-updater": "0.2.14"

Safer for release work when develop is also being worked.

In theory it could prematurely build with 0.2.15 if that is being worked on for develop

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (e225bd4)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-linux-x64-1.0.0-e225bd4.zip) is ready for download.
[macOS build 1.0.0 (e225bd4)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-macos-x64-1.0.0-e225bd4.dmg) is ready for download.
[Windows x64 build 1.0.0 (e225bd4)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-win-x64-1.0.0-e225bd4.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (e225bd4)](https://tc-builds.door43.org/build/fix-richmahn-update-scu-to-0.2.14/translationCore-win-x32-1.0.0-e225bd4.setup.exe) is ready for download.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5090)* status: 1 of 2 files reviewed, all discussions resolved

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5090)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
