### PR TITLE
adds a build number to the app

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4355
- Adds a build number (commit hash) next to the version number in the app
- This also correct's the missing helpdesk token in concourse.

#### Please include detailed Test instructions for your pull request:
- Look for a build number in the app.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4546)

### CODE REVIEW

**Comment by da1nerd** [comment]
[Linux build 3966771 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-3966771.zip) is ready for download.
[macOS build 3966771 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-3966771.dmg) is ready for download.
[Windows x64 build 3966771 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-3966771.setup.exe) is ready for download.
[Windows x32 build 3966771 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-3966771.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
doh! it's actually not working yet.

**Comment by da1nerd** [comment]
ok **now** it should be good to go. Helps if I spell things correctly.

**Comment by da1nerd** [comment]
[Linux build 0.10.0 (3966771)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-3966771.zip) is ready for download.
[macOS build 0.10.0 (3966771)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-3966771.dmg) is ready for download.
[Windows x64 build 0.10.0 (3966771)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-3966771.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (3966771)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-3966771.setup.exe) is ready for download.

**Comment by da1nerd** [comment]
[Linux build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-29f6d51.zip) is ready for download.
[macOS build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-29f6d51.dmg) is ready for download.
[Windows x64 build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-29f6d51.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-29f6d51.setup.exe) is ready for download.

**Comment by richmahn** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4546#-:-LDmlLtc0LZUG1Fm4VZI:bnfp4nl)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-29f6d51.zip) is ready for download.
[macOS build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-29f6d51.dmg) is ready for download.
[Windows x64 build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-29f6d51.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (29f6d51)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-29f6d51.setup.exe) is ready for download.

**Pull request merged**
