### PR TITLE
Fixed issues switching between tools

### PR DESCRIPTION
**Pull request by klappy**
## This PR addresses:
Switching back and forth between tools.

## To Test:
- [ ] Open a project and a tool.
- [ ] Switch Tool
- [ ] Switch Tool
- [ ] Repeat…

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1151)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/GetDataActions.js, line 254 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151#-KiIF8gKgtW-9BFJx6e9:-KiIF8gKgtW-9BFJx6eA:b-8e2j9m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b900617b22770cdc6c86b0ea15b4b362a962bf3f/src/js/actions/GetDataActions.js#L254)):*
> ```JavaScript
>             dispatch({ type: consts.CLEAR_CONTEXT_ID });
>             dispatch(CoreActionsRedux.changeModuleView());
>             console.log('cleared data', getState())
> ```

do we still need this console log???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151#-:-KiIFMriHri6Knvagn4P:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 254 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151#-KiIF8gKgtW-9BFJx6e9:-KiIGzj-KepXq8oPgggM:b-7rl0jd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b900617b22770cdc6c86b0ea15b4b362a962bf3f/src/js/actions/GetDataActions.js#L254)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we still need this console log???
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1151#-:-KiIHCZGz9kXnVY7MR_H:bnfp4nl)*

**Pull request merged**
