### PR TITLE
Fixed Group Menu Hover Colors

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- The group menu should not have any on hover effects

#### Please include detailed Test instructions for your pull request:
- Try moving your cursor on both the group menu header, as well as the checks underneath. The tiles should stay the same color

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6048)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (61795d1)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-linux-x64-1.2.0-61795d1.deb) is ready for download.
[macOS build 1.2.0 (61795d1)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-macos-x64-1.2.0-61795d1.dmg) is ready for download.
[Windows x64 build 1.2.0 (61795d1)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x64-1.2.0-61795d1.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (61795d1)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x32-1.2.0-61795d1.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Comment by mannycolon** [comment]
> The goup menu tile turns blue as expected when it is selected, but when the cursor is moved away from the tile, its background turns to black.

This's still happening

**Comment by mannycolon** [comment]
@RoyalSix Did you make the respective changes in the `checking-tool-wrapper`?

**Comment by mannycolon** [comment]
Only works on `wA tool`

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (94155d8)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-linux-x64-1.2.0-94155d8.deb) is ready for download.
[macOS build 1.2.0 (94155d8)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-macos-x64-1.2.0-94155d8.dmg) is ready for download.
[Windows x64 build 1.2.0 (94155d8)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x64-1.2.0-94155d8.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (94155d8)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x32-1.2.0-94155d8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (070b258)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-linux-x64-1.2.0-070b258.deb) is ready for download.
[macOS build 1.2.0 (070b258)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-macos-x64-1.2.0-070b258.dmg) is ready for download.
[Windows x64 build 1.2.0 (070b258)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x64-1.2.0-070b258.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (070b258)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x32-1.2.0-070b258.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
When merging w/ develop and fixing merge conflict the following npm module versions were wrongly changed:
- tc-source-content-updater from 0.4.6 to 0.4.5
- tsv-groupdata-parser from 0.8.4 to 0.8.3

**Comment by mannycolon** [comment]
@RoyalSix Looks good, waiting on concourse build

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (20eaad0)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-linux-x64-1.2.0-20eaad0.deb) is ready for download.
[macOS build 1.2.0 (20eaad0)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-macos-x64-1.2.0-20eaad0.dmg) is ready for download.
[Windows x64 build 1.2.0 (20eaad0)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x64-1.2.0-20eaad0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (20eaad0)](https://tc-builds.door43.org/build/feature-jay-6000/translationCore-win-x32-1.2.0-20eaad0.setup.exe) is ready for download.

**Pull request merged**
