### PR TITLE
Enabled Linting Rules

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This fixes linting errors and enables the following linting rules:

* no-cond-assign
* react/jsx-key
* no-empty

#### How to test this pull request:

Make sure  the tests pass.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2804)

### CODE REVIEW

**Comment by da1nerd** [comment]
@klappy This is the second to the last linting PR until our existing linting rules are fully implemented.

I'd like to propose additional rules in the future but perhaps we can discuss that later.

**Comment by da1nerd** [comment]
@klappy you mentioned wanting to allow quotes and single quotes because it makes translation easier. However the lint rule pertaining to that is only complaining that html entities are used within the JSX.

You aren't going to have anyone translate directly within the code, so I think this rule should remain intact. If you want to translate text in the UI you'll first need to abstract all text out of the code so it can be properly localized. Doing so will satisfy this linting rule.

I'm ready to revert the text changes if you still want to do that, but I want to confirm the end goal.

**Comment by klappy** [comment]
@neutrinog: Right, we do need to have all of the text extracted out of the code for localization.
At this point, It's probably okay to merge in, as it at least conforms to the linting rules.

Depending on how we have these strings translated, my experience cautions against html entities in the text strings once we extract them. If we merge this in, will we remember to parse the entities to utf8 representation?

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2804#-:-KvMiAUzTcmWFKT5HzDk:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2804)*

**Pull request merged**
