### PR TITLE
Setup app to use rollbar instead of HockeyApp

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/729)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/729)*

**Comment by RoyalSix** [comment]
> feature/ih-647-rollbar
How can I test this branch ?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/729#-:-Kd7PLxxwGhc9FhCbayR:b-3aplb2)*

**Comment by ihoegen** [comment]
@RoyalSix Check your email for an email sent from Rollbar, to join my team. From there, just send feedback, or console error and click reload

**Comment by mannycolon** [comment]
@ihoegen could i also get access to rollbar ?

**Comment by mannycolon** [comment]
@ihoegen this PR seems to be good to go

**Pull request merged**
