### PR TITLE
Project Loading Performance Improvements

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR removes a lot of unnecessary re-renders while loading a project

#### Please include detailed Test instructions for your pull request:
- Download this project https://github.com/unfoldingWord-dev/translationCore/files/3443756/41-MAT.usfm.zip
- Time how long it takes to open project on this build as well as latest develop.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332)* status: 1 of 16 files reviewed, 3 unresolved discussions (waiting on @RoyalSix)

___
*[src/main.js, line 73 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332#-Llg0uXs1WYpc3RtOgYI:-Llg0uXs1WYpc3RtOgYJ:b-vouq40) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fdbac3f93f4ea908145dccd547b49ab1f4ed947b/src/main.js#L73)):*
> ```JavaScript
>   });
> 
>   // if (process.env.NODE_ENV === 'development') {
> ```

Don't we need this for local testing?
___
*[src/js/actions/VerseEditActions.js, line 178 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332#-Llg1JsQ7NM7TSKcSpO6:-Llg1JsQ7NM7TSKcSpO7:b-b7g42b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/13c98cd7f963d946170a24c86bee044c62cd8411/src/js/actions/VerseEditActions.js#L178)):*
> ```JavaScript
>                                               currentCheckContextId, batchGroupData) => {
>   return async(dispatch, getState) => {
>     await delay(1000); // wait till before updating
> ```

I think this was in there to not  block UI - this was to run as a background task.
___
*[src/js/actions/VerseEditActions.js, line 270 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332#-Llg1tVA966upt255F_e:-Llg1tVA966upt255F_f:b-g5cshc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fdbac3f93f4ea908145dccd547b49ab1f4ed947b/src/js/actions/VerseEditActions.js#L270)):*
> ```JavaScript
>     }
>     var t8 = performance.now();
>     await dispatch(doBackgroundVerseEditsUpdates(verseEdit, contextIdWithVerseEdit,
> ```

Don't want to wait for this, supposed to be background operation.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a1f14ff)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-linux-x64-2.0.0-a1f14ff.deb) is ready for download.
[macOS build 2.0.0 (a1f14ff)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-macos-x64-2.0.0-a1f14ff.dmg) is ready for download.
[Windows x64 build 2.0.0 (a1f14ff)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x64-2.0.0-a1f14ff.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a1f14ff)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x32-2.0.0-a1f14ff.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (22a98d5)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-linux-x64-2.0.0-22a98d5.deb) is ready for download.
[macOS build 2.0.0 (22a98d5)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-macos-x64-2.0.0-22a98d5.dmg) is ready for download.
[Windows x64 build 2.0.0 (22a98d5)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x64-2.0.0-22a98d5.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (22a98d5)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x32-2.0.0-22a98d5.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (cf75ffd)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-linux-x64-2.0.0-cf75ffd.deb) is ready for download.
[macOS build 2.0.0 (cf75ffd)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-macos-x64-2.0.0-cf75ffd.dmg) is ready for download.
[Windows x64 build 2.0.0 (cf75ffd)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x64-2.0.0-cf75ffd.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (cf75ffd)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x32-2.0.0-cf75ffd.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 9 of 16 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6332)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-linux-x64-2.0.0-b5b2f99.deb) is ready for download.
[macOS build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-macos-x64-2.0.0-b5b2f99.dmg) is ready for download.
[Windows x64 build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x64-2.0.0-b5b2f99.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x32-2.0.0-b5b2f99.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-linux-x64-2.0.0-b5b2f99.deb) is ready for download.
[macOS build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-macos-x64-2.0.0-b5b2f99.dmg) is ready for download.
[Windows x64 build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x64-2.0.0-b5b2f99.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b5b2f99)](https://tc-builds.door43.org/build/feature-jay-6282-2/translationCore-win-x32-2.0.0-b5b2f99.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM - saw about 20% performance boost.

**Pull request merged**
