### PR TITLE
Implement group data, groupIndex & context Id reducers/actions and add data persistence

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

This PR brings a redux implementation that handles the group data based on the new data structure

#### How to test this pull request:

inside the tool's container.js  type `this.props.addGroupData('figs_metaphor', {property: 'data'})`

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/954)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/GroupDataActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgF2kiA3Xds27i12FsS:-KgF2kiBnkcl0p_U_YI8:b-h4i14x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2f3f15864f9123765049fe76feb44614f2960f/src/js/actions/GroupDataActions.js#L10)):*
> ```JavaScript
>  * @return {object} action object.
>  */
> export const addGroupData = (groupName, payload) => {
> ```

would renaming payload to groupData make more sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by klappy** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/GroupDataActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgF2kiA3Xds27i12FsS:-KgF3Fpi0r5mo0cj8gQt:bxhdigj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2f3f15864f9123765049fe76feb44614f2960f/src/js/actions/GroupDataActions.js#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

would renaming payload to groupData make more sense?
</blockquote></details>

It seems like it would be consistent since we're implying that we are adding group data, we can call it that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by mannycolon** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/actions/GroupDataActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgF2kiA3Xds27i12FsS:-KgFIll04gslgka5ifb7:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2f3f15864f9123765049fe76feb44614f2960f/src/js/actions/GroupDataActions.js#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

It seems like it would be consistent since we're implying that we are adding group data, we can call it that. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by mannycolon** [comment]
@RoyalSix

**Review by ihoegen — APPROVED** [review]

**Comment by EllDoubleYew** [comment]
Reviewed 1 of 9 files at r2, 3 of 8 files at r3, 7 of 13 files at r5, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ToolsContainer.js, line 84 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKVR8lV31gAcHPquRN:-KgKVR8lV31gAcHPquRO:b5o0vqo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/containers/ToolsContainer.js#L84)):*
> ```JavaScript
>         dispatch(changeCurrentContextId(contextId));
>       },
>       addGroupData: (groupName, payload) => {
> ```

Could we use a parameter name other than "payload" here that might be a little bit more descriptive? This just feels confusing reading it out of context.

---

*[src/js/pages/app.js, line 171 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKVZcurSXiIayPa5CZ:-KgKVZcurSXiIayPa5C_:b3d2tpn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/pages/app.js#L171)):*
> ```JavaScript
>   render: function () {
>     // logging the store for testing.
>     console.log(this.props);
> ```

Is everyone cool with leaving this in?

---

*[src/js/utils/localStorage.js, line 5 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKWBSUp8YmiZRSGmxr:-KgKWBSVb6UyYeA6TJ6I:bxbw9f4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/utils/localStorage.js#L5)):*
> ```JavaScript
> 
> /**
>  * @description loads state needed to set up reducers with preloaded data
> ```

This is very useful :+1: kudos!

---

*[tests/d.Upload.js, line 43 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKWMeBT1u1w8M_Ohpv:-KgKWMeBT1u1w8M_Ohpw:b-1c0i8n) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/tests/d.Upload.js#L43)):*
> ```JavaScript
>                     assert.isNotOk(data);
>                 }
>                 api.outputJson(noTCManifestProject + '/tc-manifest.json', null, function () {
> ```

I am pretty sure this was addressed in another pr but just wanted to make sure, we are leaving this intentionally as 'tc-manifest' correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by mannycolon** [comment]
Reviewed 2 of 7 files at r9.
Review status: 12 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/containers/ToolsContainer.js, line 84 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKVR8lV31gAcHPquRN:-KgKb71JIIuJT1zD5TSl:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/containers/ToolsContainer.js#L84)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Could we use a parameter name other than "payload" here that might be a little bit more descriptive? This just feels confusing reading it out of context.
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 171 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKVZcurSXiIayPa5CZ:-KgKap5zuSTi6y1C9ZfJ:b-2vsrtg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/pages/app.js#L171)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Is everyone cool with leaving this in?
</blockquote></details>

yeah at least for now lol

---

*[src/js/utils/localStorage.js, line 5 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKWBSUp8YmiZRSGmxr:-KgKb89Ko9oLaV--IiQO:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/src/js/utils/localStorage.js#L5)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

This is very useful :+1: kudos!
</blockquote></details>

Done.

---

*[tests/d.Upload.js, line 43 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKWMeBT1u1w8M_Ohpv:-KgKb3-vytLJrGDKlyzE:b-lvhmxz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/tests/d.Upload.js#L43)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

I am pretty sure this was addressed in another pr but just wanted to make sure, we are leaving this intentionally as 'tc-manifest' correct?
</blockquote></details>

im not sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by EllDoubleYew** [comment]
Reviewed 6 of 9 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[tests/d.Upload.js, line 43 at r8](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-KgKWMeBT1u1w8M_Ohpv:-KgKv7mfoZ8-nEu2aAQY:blwrhyr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ec64d936464310fe8d2ca55196569d0f924cefe9/tests/d.Upload.js#L43)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

im not sure
</blockquote></details>

its okay to leave it like this for now considering it is a test. We can address it later if it starts failing :joy: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2, 4 of 13 files at r5, 2 of 6 files at r8, 6 of 9 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by klappy** [comment]
Reviewed 1 of 6 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/954#-:-KgLBDP1w_u__YU6qQPz:bnfp4nl)*

**Pull request merged**
