### PR TITLE
User Card Home Screen

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Adds user section to The stepper

#### How to test this pull request:
Test out the functionality in the user portion

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1946)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/containers/home/UsersManagementContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnKSZt8Ih37Yb8qmJxC:-KnKSZt8Ih37Yb8qmJxD:b-g46gsr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/containers/home/UsersManagementContainer.js#L3)):*
> ```JavaScript
> import React, { Component } from 'react'
> import { connect } from 'react-redux'
> // components
> ```

why are you removing the labels? 
i think is helpful to have the imports organized by 
//components 
//actions
//helpers

---

*[src/js/containers/home/UsersManagementContainer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnKSyKAyIclE47e0Qis:-KnKSyKAyIclE47e0Qit:bi4278o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/de1ee39e73c4f6b721be34c9e51c16d161fa0eea/src/js/containers/home/UsersManagementContainer.js#L14)):*
> ```JavaScript
>         <div style={{ margin: 15 }}>Please login with you Door43 Account</div>
>         <div style={{ margin: 15 }}>If you do not have an account already, you may create an account.</div>
>         <div style={{ margin: 15 }}>If you would rather work offline, you may select continue offline.</div>
> ```

do we still have the local user option??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by mannycolon** [comment]
Never mind about the local user. I realized it's a different story.

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/containers/home/UsersManagementContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnKSZt8Ih37Yb8qmJxC:-KnK_uWGTrG-v_HQIisX:bmp1zam) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/containers/home/UsersManagementContainer.js#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you removing the labels? 
i think is helpful to have the imports organized by 
//components 
//actions
//helpers
</blockquote></details>

My b haha I can add back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/containers/home/UsersManagementContainer.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnKSyKAyIclE47e0Qis:-KnKa2azdotb46cR4AOX:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/de1ee39e73c4f6b721be34c9e51c16d161fa0eea/src/js/containers/home/UsersManagementContainer.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we still have the local user option??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by mannycolon** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-:-KnL0_VIQ8PLqBc_Bv0Z:bg7igkv)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 21 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnM5ANO03pLWjRDUcJ6:-KnM5ANPpMeUvig983w8:b-5s294q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L21)):*
> ```JavaScript
>     let positionCoord = e.target;
>     let title = <strong>Door43 Information</strong>
>     let text =
> ```

This may be minor but it seems more common to move the ( up to the line with the assignment and the closing ) on a line by itself. Then the code in between can be nested and indented normally.
let text = (
  ...
);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 8 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnM5iw0fRmXN-EB20zj:-KnM5iw0fRmXN-EB20zk:bnwlbs1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/970cbc87268743c48e64e6b5c9126d2784d3f6e2/src/js/components/home/usersManagement/Login.js#L8)):*
> ```JavaScript
>       <div>
>         Login
>       </div>
> ```

The white space looks very odd here. This whole section appears to be off as far as indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 20 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMADBWhdE2wB1oHkhj:-KnMADBWhdE2wB1oHkhk:b-bwlxxv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/containers/home/UsersManagementContainer.js#L20)):*
> ```JavaScript
>   handleLoginSubmit(){
>     this.props.loginUser();
>     dispatch(this.props.goToNextStep());
> ```

I don't think dispatch is available here is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 38 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMAV3A3TIpH5Vz0F1T:-KnMAV3A3TIpH5Vz0F1U:bfddzdp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/containers/home/UsersManagementContainer.js#L38)):*
> ```JavaScript
>     );
>   }
> };
> ```

I don't think the semicolon is needed here. I know you didn't add it but a good time to remove it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 12 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMCblFhRCWJtZq7WpF:-KnMCblFhRCWJtZq7WpG:b-dg5nxp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L12)):*
> ```JavaScript
>   constructor(props) {
>     super(props);
>     this.state = {
> ```

Should we have state in  components or should we move this to the UserManagementContainer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMDKeLL8HrykiF0sPV:-KnMDKeLL8HrykiF0sPW:b-j1zsbq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L9)):*
> ```JavaScript
> import { Glyphicon } from 'react-bootstrap';
> 
> class Login extends Component {
> ```

I feel like this file should be LoginD43.js not Login.js.  All of the logic is specific to Door43 accounts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMDKeLL8HrykiF0sPV:-KnMDkeQd2jKRGjb2ckG:beocwxt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L9)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I feel like this file should be LoginD43.js not Login.js.  All of the logic is specific to Door43 accounts.
</blockquote></details>

Login.js is suppose to be a lightweight parent component for D43 and Offline login components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMDKeLL8HrykiF0sPV:-KnMG03IXgYrp-RTy1EH:b8qyqw0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L9)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Login.js is suppose to be a lightweight parent component for D43 and Offline login components.
</blockquote></details>

```
      <UsersManagementContainer>
        <Login>
          <LoginD43>
            <CreateDialog />
          </LoginD43>
          <LoginOffline />
        </Login>
      </UsersManagementContainer>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/Login.js, line 43 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMIgfQX26Npdh58LvX:-KnMIgfQX26Npdh58LvY:bc53lib) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/components/home/usersManagement/Login.js#L43)):*
> ```JavaScript
>     let u = this.state.username
>     let p = this.state.password
>     let disabledButton = (u == null || u == "") || (p == null || p == "")
> ```

Try to avoid abbreviations, especially one character vars. It's a nightmare to debug and search for occurrences of where they are used. 
These three lines can be accomplished with this: 
```
    let { username, password } = this.state;
    let disabledButton = !username || !password;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 47 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946#-KnMJiervUh4UxFPrlmf:-KnMJiervUh4UxFPrlmg:bonhvaa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/139ac3dfa3a00c8a8f04d0c13d0916ee9e7ea0cf/src/js/containers/home/UsersManagementContainer.js#L47)):*
> ```JavaScript
> const mapDispatchToProps = (dispatch, ownProps) => {
>   return {
>     loginUser: (userDataSumbit) => {
> ```

Can we nest all of these inside actions? It gets confusing when their not nested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1946)*

**Pull request closed without merging**
