### PR TITLE
Feature 5943/Make resource update script more robust for running in build

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated tc-source-content-updater with better error handling and recovery.
- updated updateResources script with better error handling and reporting.
- make resource update script more robust for running in concourse build ,and added return of error

#### Please include detailed Test instructions for your pull request:
- update script already is running in concourse
- using this branch, do npm ci and npm run update-resources
- it should finish and should see Updating Succeeded!!! at end

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6615)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d362c3c)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-d362c3c.deb) is ready for download.
[macOS build 2.1.0 (d362c3c)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-d362c3c.dmg) is ready for download.
[Windows x64 build 2.1.0 (d362c3c)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-d362c3c.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d362c3c)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-d362c3c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (957cadd)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-957cadd.deb) is ready for download.
[macOS build 2.1.0 (957cadd)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-957cadd.dmg) is ready for download.
[Windows x64 build 2.1.0 (957cadd)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-957cadd.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (957cadd)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-957cadd.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-536b7e7.deb) is ready for download.
[macOS build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-536b7e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-536b7e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-536b7e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (74c50c0)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-74c50c0.deb) is ready for download.
[macOS build 2.1.0 (74c50c0)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-74c50c0.dmg) is ready for download.
[Windows x64 build 2.1.0 (74c50c0)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-74c50c0.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (74c50c0)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-74c50c0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-5139231.deb) is ready for download.
[macOS build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-5139231.dmg) is ready for download.
[Windows x64 build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-5139231.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-5139231.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-5139231.deb) is ready for download.
[macOS build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-5139231.dmg) is ready for download.
[Windows x64 build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-5139231.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (5139231)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-5139231.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-d2e10e7.deb) is ready for download.
[macOS build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-d2e10e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-d2e10e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-d2e10e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-d2e10e7.deb) is ready for download.
[macOS build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-d2e10e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-d2e10e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-d2e10e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-d2e10e7.deb) is ready for download.
[macOS build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-d2e10e7.dmg) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-d2e10e7.deb) is ready for download.
[macOS build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-d2e10e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-d2e10e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (d2e10e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-d2e10e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-c6f260b.deb) is ready for download.
[macOS build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-c6f260b.dmg) is ready for download.
[Windows x64 build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-c6f260b.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-c6f260b.setup.exe) is ready for download.

**Review by richmahn — COMMENTED** [review]
> Reviewed 5 of 10 files at r1, 4 of 7 files at r2, 1 of 46 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6615)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @richmahn)

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (0b8a20d)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-0b8a20d.deb) is ready for download.
[macOS build 2.1.0 (0b8a20d)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-0b8a20d.dmg) is ready for download.
[Windows x64 build 2.1.0 (0b8a20d)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-0b8a20d.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (0b8a20d)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-0b8a20d.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]

**Pull request merged**
