### PR TITLE
Global alignment memory integration

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5662
- Made some minor adjustments to support using alignment memory across a whole language.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (bd038e0)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-linux-x64-1.2.0-bd038e0.deb) is ready for download.
[macOS build 1.2.0 (bd038e0)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-macos-x64-1.2.0-bd038e0.dmg) is ready for download.
[Windows x64 build 1.2.0 (bd038e0)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-win-x64-1.2.0-bd038e0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (bd038e0)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-win-x32-1.2.0-bd038e0.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog)

___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 217 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195#-LinW7DTB-Nz2aLLKyfu:-LinW7DTB-Nz2aLLKyfv:b-aubefl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bd038e04e7a6b2aed7eb73c9299fbe1c6a571a08/src/js/actions/MyProjects/ProjectLoadingActions.js#L217)):*
> ```JavaScript
>     showIgnorableAlert: coreApi.showIgnorableAlert,
>     appLanguage: code,
>     // TODO: add list of projects for tool to access
> ```

I think this is left over

**Comment by da1nerd** [comment]
___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 217 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195#-LinW7DTB-Nz2aLLKyfu:-LinpoB2E7zPqrK7jmv4:bh75082) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bd038e04e7a6b2aed7eb73c9299fbe1c6a571a08/src/js/actions/MyProjects/ProjectLoadingActions.js#L217)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I think this is left over
</blockquote></details>

or did we just forget to complete that?

**Comment by da1nerd** [comment]
___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 217 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195#-LinW7DTB-Nz2aLLKyfu:-Lio3sT15tTXmz0D95Y5:b-sn2zwa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bd038e04e7a6b2aed7eb73c9299fbe1c6a571a08/src/js/actions/MyProjects/ProjectLoadingActions.js#L217)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

or did we just forget to complete that? 
</blockquote></details>

ok I added this. This is not critical for now, but we'll need it later if other tools begin to provide their own global alignment memory.

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6195)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0ba9f34)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-linux-x64-1.2.0-0ba9f34.deb) is ready for download.
[macOS build 1.2.0 (0ba9f34)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-macos-x64-1.2.0-0ba9f34.dmg) is ready for download.
[Windows x64 build 1.2.0 (0ba9f34)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-win-x64-1.2.0-0ba9f34.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0ba9f34)](https://tc-builds.door43.org/build/enhancement_joeljay_5662_walang/translationCore-win-x32-1.2.0-0ba9f34.setup.exe) is ready for download.

**Pull request merged**
