### PR TITLE
Implement ContextId Actions/Reducers #951

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/953)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ContextIdActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953#-Kg5f_77aKrFUG_xlV-x:-Kg5f_77aKrFUG_xlV-y:b-xcbqr9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9e6ecfbd196d07052b5113c7e45a29e05cc35f24/src/js/actions/ContextIdActions.js#L8)):*
> ```JavaScript
>  * @return {object} New state for contextId reducer.
>  */
> export const changeContextId = (contextId) => {
> ```

could we renamed this to changeCurrentContextId ???

---

*[src/js/actions/CoreActionConsts.js, line 73 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953#-Kg5ffYgAWx2IR-RT56h:-Kg5ffYgAWx2IR-RT56i:b-j9gqtf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9e6ecfbd196d07052b5113c7e45a29e05cc35f24/src/js/actions/CoreActionConsts.js#L73)):*
> ```JavaScript
>   LINK_MODULE_DATA: "LINK_MODULE_DATA",
>   TOGGLE_REMINDER: "TOGGLE_REMINDER",
>   CHANGE_CONTEXT_ID: "CHANGE_CONTEXT_ID",
> ```

MAYBE CHANGE_CURRENT_CONTEXT_ID ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953)*

**Comment by klappy** [comment]
*[src/js/actions/CoreActionConsts.js, line 73 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953#-Kg5ffYgAWx2IR-RT56h:-KgF65_MfhHcTrGkuMcD:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9e6ecfbd196d07052b5113c7e45a29e05cc35f24/src/js/actions/CoreActionConsts.js#L73)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

MAYBE CHANGE_CURRENT_CONTEXT_ID ??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953)*

**Comment by klappy** [comment]
*[src/js/actions/ContextIdActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953#-Kg5f_77aKrFUG_xlV-x:-KgF66praMJU0EUyS9Q-:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9e6ecfbd196d07052b5113c7e45a29e05cc35f24/src/js/actions/ContextIdActions.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we renamed this to changeCurrentContextId ???
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/953#-:-KgFLBRqCyURU3frx1ul:bnfp4nl)*

**Pull request merged**
