### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5350)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (fb3cce1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-fb3cce1.deb) is ready for download.
[macOS build 1.1.0 (fb3cce1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-fb3cce1.dmg) is ready for download.
[Windows x64 build 1.1.0 (fb3cce1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-fb3cce1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fb3cce1)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-fb3cce1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d45b843)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-d45b843.deb) is ready for download.
[macOS build 1.1.0 (d45b843)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-d45b843.dmg) is ready for download.
[Windows x64 build 1.1.0 (d45b843)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-d45b843.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d45b843)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-d45b843.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1b9fe77)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-1b9fe77.deb) is ready for download.
[macOS build 1.1.0 (1b9fe77)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-1b9fe77.dmg) is ready for download.
[Windows x64 build 1.1.0 (1b9fe77)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-1b9fe77.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1b9fe77)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-1b9fe77.setup.exe) is ready for download.

**Review by bspidel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5350)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bspidel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5350#-:-LQAWFqZDN90eaba1vF2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
