### PR TITLE
Fix - #3977 - Find articles for both tW & tA for GL & English

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses https://github.com/unfoldingWord-dev/translationCore/issues/3977

#### Please include detailed Test instructions for your pull request:
- [ ] This requires three repos to have the `fix-richmahn-3977` branch checked out for them: `translationCore`, `tC_resources`, `translationHelps`
  - `runGitCommands() { git checkout fix-richmahn-3977 && git pull; }; runGitCommands; cd tC_apps/translationHelps; runGitCommands; cd ../../tC_resources; runGitCommands; cd ../;`
- [ ] Start the app.
- [ ] Verify that your user resources have been updated, mainly by seeing there is a `~/translationCore/resources/en/translationHelps/translationAcademy/v9` now.
- [ ] In the app, open a Titus project and go into tW. Before the links in the article pane on the right, when they opened a modal, it was blank (couldn't find the article). Now you should be able to click a link, get a modal, and click to your hearts content on any link as only tW and tA links should show up.
- [ ] What were tN links in the tW articles should now just show the Bible reference, no link. OBS tN links are also now just bold `Open Bible Stories - <story>:<frame>` text.
- [ ] Any http:// links, if you can find any, should warn the user they will be going online (standard feature of the whole app)
- [ ] Go back to the Tool selection page and change the tW GL to Hindi. Do the same, but now should see Hindi articles but if it is a tA article, which we don't have Hindi for, will use the English instead.
- [ ] Now go back to the Tool selection page. Remove the Apostle article on disk with `rm ~/translationCore/resources/en/translationHelps/translationWords/v8/kt/articles/apostle.md` (or rename it and then rename it back later), then select English as the GL and go into the Tool. You should get an message in the tHelps pane. Play with this, including switching to Hindi, removing an article file and try to view it (should show the English instead), and then remove the English article and you should get the error message.
- [ ] Review the code. Keep in mind I made it so we not only look at language, but also an article category (if available). This is just in case an articleId happens to be used more than one time in multiple directories...thus we get the category from the rc:// or relative link in the article. Example of a category is `kt, names, other` for tW, or `intro, checking, process, translate` for tA. This makes it easier to find the article without having to search, but if a link in an article doesn't specify the category, we then loop through known categories. You will see this used in ResourcesActions.js (tC) and Container.js and tHelpsHelpers.js (translationHelps)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4001)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 13 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__mocks__/fs-extra.js, line 95 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-L7COvTGkW8DoZuJUm_Y:-L7COvTH8zI1cTpefDqP:b-gn5r4w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4193d7753a36b90c1baaea2a6b34592455b9401/__mocks__/fs-extra.js#L95)):*
> ```JavaScript
> }
> 
> function pathExistsSync(path) {
> ```

I know we probably have not documented well the functions in this file but could you please document this function and describe what it does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by mannycolon** [comment]
@richmahn Fix failing Unit tests.

**Comment by richmahn** [comment]
@mannycolon Thanks. I just realized pathExistsSync is not a function that tests if a dir exists, but should just be a alias for existsSync, and since we use it in ResourcesHandler.js which I now test with a mocked file system, I am just going to alias it, not make a new function. Hope that gets me out of documentation, haha. We should just adopt the documentation form the actual module. https://github.com/jprichardson/node-fs-extra/blob/master/docs/pathExists.md

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__mocks__/fs-extra.js, line 95 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-L7COvTGkW8DoZuJUm_Y:-L7DV1cLOBNFD3JDif6i:b-dhqk2q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4193d7753a36b90c1baaea2a6b34592455b9401/__mocks__/fs-extra.js#L95)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I know we probably have not documented well the functions in this file but could you please document this function and describe what it does.
</blockquote></details>

I'm actually going to do away with this, just realizing it is the same as existsSync but just make an alias for it. We should have documents, but of course they should mirror the actual fs-extra package....at least have links to it from our mock file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by richmahn** [comment]
@mannycolon Fixed tests.

**Comment by PhotoNomad0** [comment]
@richmahn - you need to increment the app version so that resources will be automatically updated.

**Comment by PhotoNomad0** [comment]
Functions correctly except couldn't find way to test http links.  Now looking at code.

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by richmahn** [comment]
Only way I know to test an http:// link is to add one yourself, because we never actually get to the tA articles that have them from the tW->tA links (they pretty much refer to translationCore/translate/*.md articles.). You'd have to edit a .md file in your ~/translationCore/resources directory that you know it will load and add something like `[Click Here](https://unfoldingword.org)`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-:-L7Q6NCqp71HCfB16rgt:bsw6xe1)*

**Comment by richmahn** [comment]
@photonomad0 Incremented again, now alpha-23

---

Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-:-L7Q7Ec7BZ3-jrXVzmaz:b-gsoirw)*

**Comment by RoyalSix** [comment]
Reviewed 12 of 14 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/ProjectDetailsHelpers.js, line 18 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-L7QCkpkK54cC6oMaOHo:-L7QCkplHckhWfwMD8c3:b-k7hegc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89b5cb5f432b1b3f5fcb36016c893d17f5f8fff2/src/js/helpers/ProjectDetailsHelpers.js#L18)):*
> ```JavaScript
>     let allGroupDataObjects = {};
>     groupDataFiles.map((groupDataFileName) => {
>       console.log(pathToCheckDataFiles, groupDataFileName);
> ```

Is this still useful information?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: One comment

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/ProjectDetailsHelpers.js, line 18 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-L7QCkpkK54cC6oMaOHo:-L7QI1hTL3YijYzmWqLs:b-eamjc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89b5cb5f432b1b3f5fcb36016c893d17f5f8fff2/src/js/helpers/ProjectDetailsHelpers.js#L18)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is this still useful information?
</blockquote></details>

Good catch...not used. Was for debugging. Removing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/ProjectDetailsHelpers.js, line 18 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001#-L7QCkpkK54cC6oMaOHo:-L7QIiQk2zgZBoxSf_Yc:bss4a2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/89b5cb5f432b1b3f5fcb36016c893d17f5f8fff2/src/js/helpers/ProjectDetailsHelpers.js#L18)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Good catch...not used. Was for debugging. Removing.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4001)*

**Pull request merged**
