### PR TITLE
Enhancement - #3305 - CheckCard uses Gateway Language resources index.json

### PR DESCRIPTION
**Pull request by richmahn**
NOTE: Dependent on https://github.com/translationCoreApps/translationWords/pull/110 also being merged.

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Gets the Group Index from the resources directory based on the Gateway language (currently hard coded as 'en' due to there not being a Gateway Language reducer, to be fixed in #3858) rather than from the project directory, thus no longer copies in the group index.json file. This causes the Check Info card to properly show the title of the selected tW word.

#### Please include detailed Test instructions for your pull request:
- Checkout enhancement-3305-tw-check-info in the main tC repo AND in the tC_apps/translationWords repo (https://github.com/translationCoreApps/translationWords/pull/110), load a new project, go into tW. Words should be properly show up as English on the left menu and in the Check Info card. In the `<user>/translationCore/projects/<project>/.apps/translationCore/index/translationWords` directory there should NO LONGER be a index.json file, as we now read it from `<user>/translationCore/resources/en/translationHelps/translationWords/v6/kt`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3859)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tC_resources, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5R7rKU4vFrLQEDPPHT:b-ry7duh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
> ```
> Subproject commit 10495055b15ffc000b3f68fd10a9735d2ec5fe56
> ```

Accidental commit?

---

*[src/js/actions/ProjectDataLoadingActions.js, line 29 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R8-q_veBKsW5h01Aj:-L5R8-q_veBKsW5h01Ak:b4oyp0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/src/js/actions/ProjectDataLoadingActions.js#L29)):*
> ```JavaScript
>       let bookAbbreviation = manifest.project.id;
>       const dataDirectory = path.join(projectSaveLocation, '.apps', 'translationCore', 'index', currentToolName);
>       const gatewayLanguage = 'en';  // TODO: Get gateway language from state
> ```

It says ```TODO```. Is this functionality a requirement of the story?

---

*[src/js/actions/ResourcesActions.js, line 134 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R8gNZtx0UDpH0n5PO:-L5R8gNZtx0UDpH0n5PP:b-ws7b6o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/src/js/actions/ResourcesActions.js#L134)):*
> ```JavaScript
> export const loadResourceArticle = (resourceType, articleId) => {
>   return ((dispatch) => {
>     let languageId = 'en';  // TODO: Get gateway language from state
> ```

Is this functionality a requirement of the story?

---

*[src/js/helpers/ResourcesHelpers.js, line 20 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R8m-d0GfC7fZhHe5R:-L5R8m-d0GfC7fZhHe5S:b9b8wf2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b69cc9b75ad994d7eeb80fc5189c982ab8334b42/src/js/helpers/ResourcesHelpers.js#L20)):*
> ```JavaScript
>       let bibleNames = fs.readdirSync(STATIC_RESOURCES_BIBLES_PATH).filter(folder => { // filter out .DS_Store
>         return folder !== '.DS_Store';
>       });
> ```

Isn't it important to filter ```.DS_Store``` ?

---

*[src/js/helpers/ResourcesHelpers.js, line 44 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R8yulmcDYaO9URD0J:-L5R8yumkSLv1JXVtf41:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b69cc9b75ad994d7eeb80fc5189c982ab8334b42/src/js/helpers/ResourcesHelpers.js#L44)):*
> ```JavaScript
>     const tHelpsNames = fs.readdirSync(staticTranslationHelpsPath).filter(folder => { // filter out .DS_Store
>       return folder !== '.DS_Store';
>     });
> ```

Same as above

---

*[src/js/helpers/ResourcesHelpers.js, line 67 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859#-L5R901jjMlecgrAqh9O:-L5R901jjMlecgrAqh9P:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b69cc9b75ad994d7eeb80fc5189c982ab8334b42/src/js/helpers/ResourcesHelpers.js#L67)):*
> ```JavaScript
>     const folders = fs.readdirSync(staticPath).filter(folder => { // filter out .DS_Store
>       return folder !== '.DS_Store';
>     });
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
*[src/js/helpers/ResourcesHelpers.js, line 20 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R8m-d0GfC7fZhHe5R:-L5UQZjs5XRTt7SZ-oCx:b-nozhk6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b69cc9b75ad994d7eeb80fc5189c982ab8334b42/src/js/helpers/ResourcesHelpers.js#L20)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Isn't it important to filter ```.DS_Store``` ?
</blockquote></details>

This was removed in a branch this was based on. It's already merged.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
@richmahn Can you update with latest develop? That will help address some comments below that were discussed in your last PR that was merged.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-:-L5URLk6-kVsuRTaqBKR:b-sf62p0)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ProjectDataLoadingActions.js, line 29 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R8-q_veBKsW5h01Aj:-L5UfNj35krJZ_De7Rxa:biquw81) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/src/js/actions/ProjectDataLoadingActions.js#L29)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It says ```TODO```. Is this functionality a requirement of the story?
</blockquote></details>

There is no way to get the Gateway Language at the moment. That will be addressed in another story.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/actions/ResourcesActions.js, line 134 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R8gNZtx0UDpH0n5PO:-L5UfV8W61CVFs8U7FPP:b-cj2hjw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/src/js/actions/ResourcesActions.js#L134)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is this functionality a requirement of the story?
</blockquote></details>

Not of this story.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/js/helpers/ResourcesHelpers.js, line 20 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R8m-d0GfC7fZhHe5R:-L5Ufd6M2_HeQEf9g8id:bto2ste) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b69cc9b75ad994d7eeb80fc5189c982ab8334b42/src/js/helpers/ResourcesHelpers.js#L20)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This was removed in a branch this was based on. It's already merged.
</blockquote></details>

Merged in the updates to the develop branch into this one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tC_resources, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5UPpJ51Co45Gry78ii:btop70t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Accidental commit?
</blockquote></details>

@richmahn I can help fix having this commit in here

---

*[src/js/actions/ProjectDataLoadingActions.js, line 29 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R8-q_veBKsW5h01Aj:-L5UPx41AoaTHcF1JV8W:b-f4q9x3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/src/js/actions/ProjectDataLoadingActions.js#L29)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It says ```TODO```. Is this functionality a requirement of the story?
</blockquote></details>

Not exactly, the full resolution of this is to add a reducer and actions that needs to be a separate story.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tC_resources, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5Ugw1n5bLv9vJwMmRL:b-a4cly8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@richmahn I can help fix having this commit in here
</blockquote></details>

Not even sure what you mean, but I guess this was fixed by merging develop into this branch. I previously was working off another branch due to it needed for this story but that one got put into develop.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
*[tC_resources, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5V9mTbEm_fGp7Xg9Vq:b-39pc0g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Not even sure what you mean, but I guess this was fixed by merging develop into this branch. I previously was working off another branch due to it needed for this story but that one got put into develop.
</blockquote></details>

The problem is that none of our submodules should show up in a commit like this. The checklist mentions it as tC_apps even though it should include tC_resources: 

- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
*[tC_resources, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5VADveAgbvzWnz9RSu:b-yc9rhs) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The problem is that none of our submodules should show up in a commit like this. The checklist mentions it as tC_apps even though it should include tC_resources: 

- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
</blockquote></details>

The quickest way I know how to fix it is to make this commit match latest develop branch. It was updated via an automated script. 
We can do the same by running `npm run update-apps`, that should update your checked out version to latest commit on master.
Then commit that update, keep in mind only commit the updated `tC_resources`and no other submodule. 
In the future, try to double check before committing to prevent the steps above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tC_resources, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-L5R7rKU4vFrLQEDPPHS:-L5VL0FFBswWbHi3cTMg:b-t1bkqa) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7104bda4653a992a5b3a0d541e49d90f9c9c6e3b/tC_resources#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The quickest way I know how to fix it is to make this commit match latest develop branch. It was updated via an automated script. 
We can do the same by running `npm run update-apps`, that should update your checked out version to latest commit on master.
Then commit that update, keep in mind only commit the updated `tC_resources`and no other submodule. 
In the future, try to double check before committing to prevent the steps above.

</blockquote></details>

Guess I fixed this. Commit ID is the same as the current develop commit for tC_resources.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859#-:-L5VLGWN4VoHwCEFBPIB:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3859)*

**Pull request merged**
