### PR TITLE
Fix 7096 duplicate snippets

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #7096 

Includes some updates to a few dependencies in order to fix displaying multiple notes for the same verse.
* [Added checkId to tsv-groupdata-parser](https://github.com/unfoldingWord/tsv-groupdata-parser/commit/1c3c3bb82130e96539cfe043a435c9fa30f7a790)
* Updated checking-tool-wrapper https://github.com/unfoldingWord/checking-tool-wrapper/pull/135

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@da1nerd Windows build is failing and 1ti 6:19 example does not work.

**Comment by da1nerd** [comment]
@PhotoNomad0 this is ready

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 0 of 113 files reviewed, 1 unresolved discussion (waiting on @da1nerd)

___
*[package.json, line 126 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMUr8NBWJdyj_7NdUV:-MdMUr8NBWJdyj_7NdUW:bk0b5p4) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/package.json#L126)):*
> ```JSON
>     "axios": "0.19.1",
>     "babel-polyfill": "6.26.0",
>     "checking-tool-wrapper": "^6.0.0-alpha.3",
> ```

We have several alpha's here - need to release these packages.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 10 of 105 files at r1, 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 18 of 113 files reviewed, 1 unresolved discussion (waiting on @da1nerd)

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 17 of 113 files reviewed, 2 unresolved discussions (waiting on @da1nerd)

___
*[src/tC_apps/translationNotes, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMdi739Bn7cAeY20jG:-MdMdi7495D7waS1Gbfp:b7u7s5e) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/translationNotes#L1)):*
> ```
> Subproject commit b53a2935069508e08898b608bea0cf9991db74ad
> ```

This does not seem right.  The latest commit is https://github.com/unfoldingWord/translationNotes/commit/a80025fcdccf71f76d14ef453c5160bfef38d5bb

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 17 of 113 files reviewed, 1 unresolved discussion (waiting on @da1nerd)

___
*[src/tC_apps/translationNotes, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMdi739Bn7cAeY20jG:-MdMe9SXCLh7E_8ZX5DV:bdloaej) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/translationNotes#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This does not seem right.  The latest commit is https://github.com/unfoldingWord/translationNotes/commit/a80025fcdccf71f76d14ef453c5160bfef38d5bb
</blockquote></details>

Normally we don't commit the submodules, but depend on the automation to apply the latest develop commit.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 16 of 113 files reviewed, 3 unresolved discussions (waiting on @da1nerd)

___
*[src/tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMfTrWD97VIAfZB2_n:-MdMfTrWD97VIAfZB2_o:b-p7j2g3) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/translationWords#L1)):*
> ```
> Subproject commit 6651d84c0ac02f5ff5fb3813cb485c750284ce3e
> ```

This also looks like you have clobbered the latest commit
___
*[src/tC_apps/wordAlignment, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMfaas26ZTkjqYN8pH:-MdMfaas26ZTkjqYN8pI:b-p7j2g3) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/wordAlignment#L1)):*
> ```
> Subproject commit b33909123c287bcbfd1f256fbb268cfdf464da62
> ```

This also looks like you have clobbered the latest commit

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 16 of 113 files reviewed, 3 unresolved discussions (waiting on @da1nerd)

___
*[src/tC_apps/translationNotes, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMdi739Bn7cAeY20jG:-MdMg_-HC0y-_d5MBk8N:bbn4vzg) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/translationNotes#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Normally we don't commit the submodules, but depend on the automation to apply the latest develop commit.
</blockquote></details>

You Need to do `npm run update-apps` to get latest submodules from develop branch

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 16 of 113 files reviewed, 6 unresolved discussions (waiting on @da1nerd)

___
*[tcResources/en/lexicons/ugl/v0/contents.zip, line 0 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0_KN3jFLIF-zrBTj:-MdN0_KP9FMYbnEBsNGr:b-oaajqf) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/ugl/v0/contents.zip#L0)):*
This should not be deleted
___
*[tcResources/en/lexicons/uhl/v0.1/contents.zip, line 0 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0mAn6ypL0gLlk_sj:-MdN0mAn6ypL0gLlk_sk:b-oaajqf) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/uhl/v0.1/contents.zip#L0)):*
This should not be deleted
___
*[tcResources/en/lexicons/uhl/v0.1/index.json, line 0 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0pmk-W0NvcKP1pVa:-MdN0pmk-W0NvcKP1pVb:b-oaajqf) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/uhl/v0.1/index.json#L0)):*
This should not be deleted

**Comment by PhotoNomad0** [comment]
@da1nerd There are some merge conflicts to resolve.

**Comment by PhotoNomad0** [comment]
@da1nerd Seeing this error where two items are selected together: 
Screen Shot 2021-06-29 at 2 11 21 PM

Using project https://git.door43.org/lrsallee/en_ult_1ti_book

**Comment by PhotoNomad0** [comment]
@da1nerd It looks like the there is still a problem in the ~tc-source-content-updater~ `tsv-groupdata-parser` - it is still stripping out the `checkId` property when it is downloading the tN tHelps.

**Comment by da1nerd** [comment]
@photonomad0 I fixed those accidental deletes and commits. 
Regarding your screen shot above, did you make sure to download the latest content?  those two checks work fine when I run the app.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 5 of 114 files reviewed, 6 unresolved discussions (waiting on @PhotoNomad0)

___
*[package.json, line 126 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMUr8NBWJdyj_7NdUV:-MdOoyMHE7ptOuQnTnAo:b-uj9ak4) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/package.json#L126)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

We have several alpha's here - need to release these packages.
</blockquote></details>

done except for the content updater since I didn't change that.
___
*[src/tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMfTrWD97VIAfZB2_n:-MdOjDsK6xxABj0MzHbB:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This also looks like you have clobbered the latest commit
</blockquote></details>

Done.
___
*[src/tC_apps/wordAlignment, line 1 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdMfaas26ZTkjqYN8pH:-MdOjDfR3Z87guIav5lL:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/src/tC_apps/wordAlignment#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This also looks like you have clobbered the latest commit
</blockquote></details>

Done.
___
*[tcResources/en/lexicons/ugl/v0/contents.zip, line  at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0_KN3jFLIF-zrBTj:-MdOjEvh5z29r0cIJ8Ej:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/ugl/v0/contents.zip#L)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This should not be deleted
</blockquote></details>

Done.
___
*[tcResources/en/lexicons/uhl/v0.1/contents.zip, line  at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0mAn6ypL0gLlk_sj:-MdOjFaF8mBOTvy8FxJv:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/uhl/v0.1/contents.zip#L)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This should not be deleted
</blockquote></details>

Done.
___
*[tcResources/en/lexicons/uhl/v0.1/index.json, line  at r2](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdN0pmk-W0NvcKP1pVa:-MdOjGQ2A4TTxCyUMAK6:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/8bf44c3d778cabd011f7abd652a64c93d4710f35/tcResources/en/lexicons/uhl/v0.1/index.json#L)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This should not be deleted
</blockquote></details>

Done.

**Comment by da1nerd** [comment]
for some unknown reason the action will no longer write the `.env` file while building linux :disappointed:

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 4 of 114 files reviewed, 8 unresolved discussions (waiting on @da1nerd and @PhotoNomad0)

___
*[package.json, line 126 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRok_j1UQlJZRrh61o:-MdRok_j1UQlJZRrh61p:bnv1ycn) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L126)):*
> ```
> ^6.0.0
> ```
Need to remove the up caret
___
*[package.json, line 183 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRoyQ39rUcdLwNobH1:-MdRoyQ39rUcdLwNobH2:bpwip10) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L183)):*
> ```
> ^0.9.20
> ```
Need to remove the up caret

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 5 of 114 files reviewed, 9 unresolved discussions (waiting on @da1nerd and @PhotoNomad0)

___
*[package.json, line 178 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRrCVm3ghfsFkiZF_O:-MdRrCVn5zdZQ2YFdkvj:b-o0n08m) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L178)):*
> ```
> 0.8.2-alpha
> ```
Looks like this is a feature update I was working on, probably best to use 0.8.1 for now.

**Comment by PhotoNomad0** [comment]
@da1nerd  It looks like the github notifications are broken when the Zulip stream was renamed from `SOFTWARE/github` to `SOFTWARE - UR/github`. Could you fix the name in the main.yml of your tCore PR?  That we we can see if that will fix it before we merge the PR.

**Comment by PhotoNomad0** [comment]
**Notes:**
tested with macos github build at https://github.com/unfoldingWord/translationCore/pull/7128/checks?check_run_id=2947465331.
- removed translationCore/resources folder
- launched tCore
- archived old `en_ult_1ti` project (https://git.door43.org/lrsallee/en_ult_1ti_book)
- checked tN resource file (~/translationCore/resources/en/translationHelps/translationNotes/v49/figures/groups/1ti/figs-metaphor.json) and now see the checkId is loaded as noteId:
```
    "contextId": {
      "noteId": "pyi6",
```

So that is now working, but name is not consistent with tCore which is using checkId.

Next:
- deleted hbo, en, greek resources and then updated content in app, and see the same results as above in the tN file.
- restarted the app
- downloaded project `https://git.door43.org/lrsallee/en_ult_1ti_book`
- opened project in tN and still see the problem listed above:
- 
Screen Shot 2021-06-29 at 2 11 21 PM

**Comment by da1nerd** [comment]
oddly I followed your steps to the letter and still do not see any problems.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 4 of 114 files reviewed, 9 unresolved discussions (waiting on @PhotoNomad0)

___
*[package.json, line 126 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRok_j1UQlJZRrh61o:-MdTit7K7asAeyorhhNc:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L126)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

> ```
> ^6.0.0
> ```
Need to remove the up caret
</blockquote></details>

Done.
___
*[package.json, line 178 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRrCVm3ghfsFkiZF_O:-MdTiuId7QgFtTJUcfYk:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L178)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

> ```
> 0.8.2-alpha
> ```
Looks like this is a feature update I was working on, probably best to use 0.8.1 for now.
</blockquote></details>

Done.
___
*[package.json, line 183 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRoyQ39rUcdLwNobH1:-MdTivjc-seM_bURO3qx:bj6pd9) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L183)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

> ```
> ^0.9.20
> ```
Need to remove the up caret
</blockquote></details>

Done. also updated it to use `checkId` instead of `noteId`

**Comment by PhotoNomad0** [comment]
> oddly I followed your steps to the letter and still do not see any problems.

Just in case there is an issue with my PC, I installed on a Win10 laptop.  There I am also seeing issue in tNotes/Metaphors on verse 6:19 two of the items highlight together when selected.

**Comment by PhotoNomad0** [comment]
I see you started a new build, will try again with that one after it finishes.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/7128)* status: 5 of 114 files reviewed, 6 unresolved discussions (waiting on @da1nerd and @PhotoNomad0)

___
*[package.json, line 183 at r5](https://reviewable.io/reviews/unfoldingword/translationcore/7128#-MdRoyQ39rUcdLwNobH1:-MdXKwSKAiDlMXI9vYhs:b9hnsd9) ([raw file](https://github.com/unfoldingword/translationcore/blob/4ee968b32267bd127e77c0847af8765eeec01579/package.json#L183)):*
<details><summary><i>Previously, da1nerd (Joel) wrote…</i></summary><blockquote>

Done. also updated it to use `checkId` instead of `noteId`
</blockquote></details>

This is now fixed.

**Comment by PhotoNomad0** [comment]
> for some unknown reason the action will no longer write the `.env` file while building linux 😞

Yes - it looks like a linux environment change in github actions.  It looks like `./scripts/update_env.js` throws an exception when there is no .env file.  But the .env file should be there since that is how we initialize the email token.

**Comment by PhotoNomad0** [comment]
@da1nerd - Any progress figuring out why Linux does not build?

**Comment by PhotoNomad0** [comment]
> @da1nerd - Any progress figuring out why Linux does not build?

Nevermind, found a work-around to the permissions problem in Linux

**Pull request merged**
