### PR TITLE
Fixed not loaded list of contributors for project details modal

### PR DESCRIPTION
**Pull request by mannycolon**
### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixed bug where the list of contributors wasn't loading for the project details modal

### Please include detailed Test instructions for your pull request:
- Go to the projects list page and click the three dot icon.
- Select **Edit Project Details** in the pop-up and the contributors' should match the translators' list in the projects manifest.
- Click the `Cancel` button in the `Project Details modal` and open it back up again and the contributors' list should still match the translators' list in the projects manifest.
##### Additional testing
- Now should not be allowed to add extra empty text fields in the contributor and/or checkers sections.
- If you click the `add contributor` or the `add checker` buttons and you already have an empty text field an error message saying `This field is required` should show up. And if all text fields are filled then clicking the `add contributor` or the `add checker` buttons should add a new empty text field.  

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4120)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4120)*

**Comment by RoyalSix** [comment]
Local Testing: There is a weird bug that happens when I click on the edit project details button, click cancel, open another project, and keep doing that a few times.
screen shot 2018-03-23 at 1 06 51 am

**Comment by RoyalSix** [comment]
Reviewed 11 of 12 files at r2.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4120)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4120)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4120#-:-L8X8VzXDIlwmXbOS_ip:bnfp4nl)*

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `Pending...`

**Comment by RoyalSix** [comment]
Reviewed 1 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4120)*

**Pull request merged**
