### PR TITLE
add additional file APIs to support sharing tool alignment memory

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4946 

- This adds some additional methods for interacting with files within a tool.
- Updates the wordMAP dependency

See related PR's attached below.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4956)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-9b9c5fa.zip) is ready for download.
[macOS build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-9b9c5fa.dmg) is ready for download.
[Windows x64 build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-9b9c5fa.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-9b9c5fa.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-9b9c5fa.zip) is ready for download.
[macOS build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-9b9c5fa.dmg) is ready for download.
[Windows x64 build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-9b9c5fa.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (9b9c5fa)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-9b9c5fa.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (239db0b)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-239db0b.zip) is ready for download.
[macOS build 1.0.0 (239db0b)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-239db0b.dmg) is ready for download.
[Windows x64 build 1.0.0 (239db0b)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-239db0b.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (239db0b)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-239db0b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (f5df115)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-f5df115.zip) is ready for download.
[macOS build 1.0.0 (f5df115)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-f5df115.dmg) is ready for download.
[Windows x64 build 1.0.0 (f5df115)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-f5df115.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (f5df115)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-f5df115.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-8d2a8bc.zip) is ready for download.
[macOS build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-8d2a8bc.dmg) is ready for download.
[Windows x64 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-8d2a8bc.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-8d2a8bc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-8d2a8bc.zip) is ready for download.
[macOS build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-8d2a8bc.dmg) is ready for download.
[Windows x64 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-8d2a8bc.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-8d2a8bc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/build/enhancement_joel_4946_use_tw_alignment_memory/translationCore-linux-x64-1.0.0-8d2a8bc.zip) is ready for download.
[macOS build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/build/enhancement_joel_4946_use_tw_alignment_memory/translationCore-macos-x64-1.0.0-8d2a8bc.dmg) is ready for download.
[Windows x64 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/build/enhancement_joel_4946_use_tw_alignment_memory/translationCore-win-x64-1.0.0-8d2a8bc.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (8d2a8bc)](https://tc-builds.door43.org/build/enhancement_joel_4946_use_tw_alignment_memory/translationCore-win-x32-1.0.0-8d2a8bc.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4956)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Pull request merged**
