### PR TITLE
updated wordmap to fix wrong occurrence suggestion

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/6237
* Updates the wordmap dependency to fix issues with incorrect occurrences being suggested.

#### Please include detailed Test instructions for your pull request:
- Import this project https://git.door43.org/joel/en_ust_1sa_book
- Open the project in the wordAlignment tool
- Navigate to chapter 14 verse 21.
- Ensure that the occurrences of "with" are correctly suggested to the appropriate occurrence in Hebrew. See example below.
image

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6502)

### CODE REVIEW

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6502)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (17eb272)](https://tc-builds.door43.org/build/bugfix_joel_6237_wrong-occurrence-prediction/translationCore-linux-x64-2.0.0-17eb272.deb) is ready for download.
[macOS build 2.0.0 (17eb272)](https://tc-builds.door43.org/build/bugfix_joel_6237_wrong-occurrence-prediction/translationCore-macos-x64-2.0.0-17eb272.dmg) is ready for download.
[Windows x64 build 2.0.0 (17eb272)](https://tc-builds.door43.org/build/bugfix_joel_6237_wrong-occurrence-prediction/translationCore-win-x64-2.0.0-17eb272.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (17eb272)](https://tc-builds.door43.org/build/bugfix_joel_6237_wrong-occurrence-prediction/translationCore-win-x32-2.0.0-17eb272.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
so far the testing LGTM following the steps in the issue.  Just uncertain how to test that Greek is not broken.

**Comment by PhotoNomad0** [comment]
@neutrinog - the suggestions don't look right here:

Screen Shot 2019-10-21 at 8 49 14 AM

project https://git.door43.org/photonomad1/en_ult_mrk_book

testing with develop to see if this is an existing issue

**Comment by PhotoNomad0** [comment]
By comparison in the latest develop branch, see these suggestions:

Screen Shot 2019-10-21 at 9 01 19 AM

**Comment by PhotoNomad0** [comment]
@neutrinog - I don't have any other ult books loaded, so no other book alignments are impacting suggestions.

**Comment by da1nerd** [comment]
The situation above isn't covered by the algorithm here https://github.com/unfoldingWord-dev/translationCore/issues/6237#issuecomment-543592604, because that algorithm relies on both the target and source n-gram having multiple occurrences.

The algorithm will need to be extended, or a new one created all together. I'm inclined to create a separate algorithm since this really a completely different situation even though it looks similar.
Rather than needing to calculate the relative occurrence between the source and target n-gram occurrence, we must look just at the target n-gram occurrence.

**Comment by da1nerd** [comment]
Ok I think I've discovered a solution for the above situation. Details are explained here https://github.com/unfoldingWord/wordMAP/issues/50#issuecomment-545253883.

I should have this fully implemented later today.

**Comment by PhotoNomad0** [comment]
LGTM - fixes the stated issue.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Pull request merged**
