### PR TITLE
Feature klappy 3185 Merge Alignment into VerseObjects for USFM3 Export

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

This is the bulk of the work to get USFM 3 exported by merging alignment data into the target language verse string as verseObject array.

This is a breaking change that causes many other features to break associated with USFM since it upgrades the library USFM.js to beta.21 that is not compatible. Fixing these will require completing other stories.

#### How to test this pull request:

Test the exisiting tests suites with jest:
- `jest __tests__/PivotAlignmentHelpers.test.js`
- `jest __tests__/VerseObjectHelpers.test.js`
- `jest __tests__/ArrayHelpers.test.js`

Review the associated helpers and the code.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3640)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/PivotAlignmentHelpers.js, line 60 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azh9UmpbItiASZ-c8:-L2azh9UmpbItiASZ-c9:b-de1ffj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/PivotAlignmentHelpers.js#L60)):*
> ```JavaScript
>       //     wordVerseObjects: [wordVerseObject]
>       //   });
>       // });
> ```

Test code?  

---

*[src/js/helpers/stringHelpers.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azO523Wy07OknTt70:-L2azO523Wy07OknTt71:b-j7wxye) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/stringHelpers.js#L31)):*
> ```JavaScript
>   if (typeof string !== 'string')
>     throw 'tokenizer.tokenize() string is not String: ' + string;
>   let tokens = string.replace(/[^\w\s]|_/g, ($1) => ' ' + $1 + ' ')
> ```

Likely not unicode safe.

---

*[src/js/helpers/VerseObjectHelpers.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azXEjoa8CQlQmtuLv:-L2azXEjoa8CQlQmtuLw:b-g44xby) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/VerseObjectHelpers.js#L19)):*
> ```JavaScript
>       stringHelpers.tokenizeWithPunctuation(_verseObject.text).map( text => {
>         let verseObject;
>         if ((/\w/).test(text)) { // if the text has word characters, its a word object
> ```

Not unicode safe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by PhotoNomad0** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/VerseObjectHelpers.js, line 19 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L3UaM_-AreyJNl3Mchh:-L3UaM_-AreyJNl3Mchi:byhzwer) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4dc5502de5e900ca2ebd445d773da94bb9c8d8fe/src/js/helpers/VerseObjectHelpers.js#L19)):*
> ```JavaScript
>       stringHelpers.tokenizeWithPunctuation(_verseObject.text).map( text => {
>         let verseObject;
>         if ((/\w/).test(text)) { // if the text has word characters, its a word object
> ```

Still not sure that this will properly detect words in unicode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by RoyalSix** [comment]
Reviewed 12 of 18 files at r1, 6 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/PivotAlignmentHelpers.js, line 60 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azh9UmpbItiASZ-c8:-L3V-ka3H_PgGzwtq55y:b9epl22) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/PivotAlignmentHelpers.js#L60)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Test code?  
</blockquote></details>

Are you saying he's missing testing for this function? 

---

*[src/js/helpers/VerseObjectHelpers.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azXEjoa8CQlQmtuLv:-L3V0DTTi8--Oi4m4fCC:bb5s544) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/VerseObjectHelpers.js#L19)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Not unicode safe
</blockquote></details>

Is this tested / testable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/PivotAlignmentHelpers.js, line 60 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640#-L2azh9UmpbItiASZ-c8:-L3Y1hzLWptIvLfZt6p-:bs51khv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4f8513769beae6a5d9e3808ca7b686b9c8c2386/src/js/helpers/PivotAlignmentHelpers.js#L60)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Are you saying he's missing testing for this function? 
</blockquote></details>

There was some commented out code that he removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3640)*

**Comment by klappy** [comment]
Will create a new PR into #sandbox-feature-usfm3

**Pull request closed without merging**
