### PR TITLE
Added Back USFM project import support

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Added Back USFM project import support 

#### How to test this pull request:
- Try importing a `USFM` project

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3369)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 27 of 29 files at r1.
Review status: 27 of 29 files reviewed at latest revision, 7 unresolved discussions.

---

*[__tests__/UsfmFileConversionHelpers.test.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BejAMTpbTdWz7Sv1N:-L0BejAMTpbTdWz7Sv1O:bt46slo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/__tests__/UsfmFileConversionHelpers.test.js#L23)):*
> ```JavaScript
> const moveUsfmRejectionMessage = (
>   <div>
>     Something went wrong when importing ({null}).
> ```

Why is there null in an error message?

---

*[src/js/actions/Import/ProjectValidationActions.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BgHcU_vtXy2PexlnR:-L0BgHcU_vtXy2PexlnS:b-q7yr1e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L80)):*
> ```JavaScript
>     let newFilename = `${manifest.target_language.id}_${manifest.project.id}`;
>     newFilename = manifest.resource && manifest.resource.id ? newFilename + `_${manifest.resource.id}` : newFilename;
>     const oldProjectNamePath = projectPath && projectPath.includes('projects') ? projectPath : path.join(IMPORTS_PATH, selectedProjectFilename);
> ```

Could possibly lead to false positives if the user creates a project folder with ```projects``` in the name.

---

*[src/js/actions/Import/ProjectValidationActions.js, line 81 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BhbXdndR1G3n1IGc6:-L0BhbXdndR1G3n1IGc7:b-i9a9gd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L81)):*
> ```JavaScript
>     newFilename = manifest.resource && manifest.resource.id ? newFilename + `_${manifest.resource.id}` : newFilename;
>     const oldProjectNamePath = projectPath && projectPath.includes('projects') ? projectPath : path.join(IMPORTS_PATH, selectedProjectFilename);
>     const newProjectNamePath = path.join(projectPath && projectPath.includes('projects') ? PROJECTS_PATH : IMPORTS_PATH, newFilename);
> ```

In what cases would the newProjectPath still be in the imports folder?x

---

*[src/js/actions/Import/ProjectValidationActions.js, line 86 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0Bh9OeN8THmehM6yaG:-L0Bh9OeN8THmehM6yaH:b-nuf5lk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L86)):*
> ```JavaScript
>       // Avoid duplicate project
>       if (fs.existsSync(newProjectNamePath)) {
>         console.log('this happened');
> ```

Console.log

---

*[src/js/helpers/bibleHelpers.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0Bi50I8kttMhjkjBnb:-L0Bi50I8kttMhjkjBnc:b-drikw5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/bibleHelpers.js#L40)):*
> ```JavaScript
> 	try {
> 		let languageId = 'en';
> 		let indexLocation = Path.join(
> ```

Is the spacing on this file correct?

---

*[src/js/helpers/FileConversionHelpers/index.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BjwHa6gmqGlqKXyHl:-L0BjwHa6gmqGlqKXyHm:bq9jvf9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/FileConversionHelpers/index.js#L12)):*
> ```JavaScript
>         await UsfmFileConversionHelpers.convertToProjectFormat(sourceProjectPath, selectedProjectFilename);
>       } else {
>         // project's extension name is either .tstudio or .tcore
> ```

Are you checking that it is in fact a .tstudio or .tcore file, like how you are for .usfm?

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 64 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BkePnGaVU8G1xdsof:-L0BkePnGaVU8G1xdsog:bca811c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L64)):*
> ```JavaScript
>       const usfmData = fs.readFileSync(sourceProjectPath);
>       const projectId = manifest && manifest.project && manifest.project.id ? manifest.project.id : undefined;
>       const usfmFilename = projectId ? projectId + '.usfm' : selectedProjectFilename + '.usfm';
> ```

Does this limit us to having one type of book in the imports folder at a time?
i.e. The user cannot start an import for a en tit project and then cancel it and start one for hi tit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369)*

**Comment by mannycolon** [comment]
Review status: 26 of 29 files reviewed at latest revision, 7 unresolved discussions.

---

*[__tests__/UsfmFileConversionHelpers.test.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BejAMTpbTdWz7Sv1N:-L0FtDaoyTcORjO4DsIK:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/__tests__/UsfmFileConversionHelpers.test.js#L23)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Why is there null in an error message?
</blockquote></details>

Done.

---

*[src/js/actions/Import/ProjectValidationActions.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BgHcU_vtXy2PexlnR:-L0FsINsz0kaONWAZCay:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L80)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Could possibly lead to false positives if the user creates a project folder with ```projects``` in the name.
</blockquote></details>

Done.

---

*[src/js/actions/Import/ProjectValidationActions.js, line 81 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BhbXdndR1G3n1IGc6:-L0FjGVnTYsAdztnl3O5:b7r19f3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L81)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

In what cases would the newProjectPath still be in the imports folder?x
</blockquote></details>

This function is not moving the file is rename it the fil so it could be in the projects folder or the imports folder

---

*[src/js/actions/Import/ProjectValidationActions.js, line 86 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0Bh9OeN8THmehM6yaG:-L0FjPP8YQL43OfuZ7BG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/actions/Import/ProjectValidationActions.js#L86)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Console.log
</blockquote></details>

Done.

---

*[src/js/helpers/bibleHelpers.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0Bi50I8kttMhjkjBnb:-L0FjprX3M0D6XW-YBjm:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/bibleHelpers.js#L40)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is the spacing on this file correct?
</blockquote></details>

Done.

---

*[src/js/helpers/FileConversionHelpers/index.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BjwHa6gmqGlqKXyHl:-L0Fn2qtbMPtNotnKg7S:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/FileConversionHelpers/index.js#L12)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Are you checking that it is in fact a .tstudio or .tcore file, like how you are for .usfm?
</blockquote></details>

Done.

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 64 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369#-L0BkePnGaVU8G1xdsof:-L0FqLzXXBF3x8wjrHWn:b32wsm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/06f219ab8c2bb95c58e2f12d2db997c98d3d02ac/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L64)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Does this limit us to having one type of book in the imports folder at a time?
i.e. The user cannot start an import for a en tit project and then cancel it and start one for hi tit
</blockquote></details>

no

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369)*

**Comment by PhotoNomad0** [comment]
Tested program - works for USFM import.  Starting code review.

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3369)*

**Pull request merged**
