### PR TITLE
Added Redux implementation to send down to tools 

### PR DESCRIPTION
**Pull request by mannycolon**
**This PR introduces a new implementation of Redux to be used by tools:**

**New additions:**
- Unselect Correct or Flag on check #584
- Implement Redux for the Tools #608
- Fix: Correct and Flagged reset data #583
- Clicking Flag for Review, auto selects Propose Change Tab #585
- Default to the first tab when Navigating to new check #586
- Missing Target Verse renders oddly #565
- Save on edit/action/blur #587

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/607)

### CODE REVIEW

**Comment by mannycolon** [comment]
#608 #583 #585 #584

**Comment by RoyalSix** [comment]
Reviewed 7 of 9 files at r1, 2 of 4 files at r2.
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/CheckStoreActions.js, line 79 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbumC8sya16kVk8-gEd:-KbumC8sya16kVk8-gEe:b-3oznb3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/actions/CheckStoreActions.js#L79)):*
> ```JavaScript
>     dispatch({
>       type: "UPDATE_CURRENT_CHECK",
>       val: currentCheck,
> ```

Possibly combine these actions (GO_TO_NEXT, UPDATE_CURRENT_CHECK) into one in the future, would result in one less dispatch, and also looks like go_to_check can be levereged here instead of creating a new const go_to_next

---

*[src/js/actions/CheckStoreActions.js, line 111 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbunnO1UoRQb_aomWs3:-KbunnO1UoRQb_aomWs4:b-ya81ng) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/actions/CheckStoreActions.js#L111)):*
> ```JavaScript
>       currentCheckIndex: newCheckIndex,
>     });
>     dispatch({
> ```

Same as above

---

*[src/js/reducers/checkStoreReducer.js, line 42 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbuoymjNZMZUrlUBInw:-KbuoymjNZMZUrlUBInx:b-4yccte) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/reducers/checkStoreReducer.js#L42)):*
> ```JavaScript
>       });
>       break;
>     case "GO_TO_PREVIOUS":
> ```

Lol don't need merge anymore, but we can factor that out later

---

*[tC_apps/translationNotes, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbupYlByRAgkJP1xXUr:-KbupYlByRAgkJP1xXUs:befeb0c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/tC_apps/translationNotes#L1)):*
> ```
> Subproject commit d3d9c21bbe43cbe0c54dc2b3f4cc1d0215a5624b
> ```

This is purposely pushed right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607)*

**Comment by mannycolon** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/CheckStoreActions.js, line 79 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbumC8sya16kVk8-gEd:-Kbupz5X3pmDAUbIVFVb:bxmff97) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/actions/CheckStoreActions.js#L79)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Possibly combine these actions (GO_TO_NEXT, UPDATE_CURRENT_CHECK) into one in the future, would result in one less dispatch, and also looks like go_to_check can be levereged here instead of creating a new const go_to_next
</blockquote></details>

there are two different use cases for GO_TO_NEXT and UPDATE_CURRENT_CHECK that's why I did not combined them. for instance, in app.js I use UPDATE_CURRENT_CHECK differently just to initialize its data. once we have fully implemented redux we can definitely do that. its just a workaround for now .

---

*[src/js/actions/CheckStoreActions.js, line 111 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbunnO1UoRQb_aomWs3:-KbuqXIY_NhxppBfZFEW:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/actions/CheckStoreActions.js#L111)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/js/reducers/checkStoreReducer.js, line 42 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbuoymjNZMZUrlUBInw:-KbuqZWlZ5lGAA1GaGdi:b-ab0mno) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/src/js/reducers/checkStoreReducer.js#L42)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Lol don't need merge anymore, but we can factor that out later
</blockquote></details>

yeah now that we have ES6 we can use ...state (the spread operator). i just wanted to keep it consistent for now.

---

*[tC_apps/translationNotes, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbupYlByRAgkJP1xXUr:-Kbuqjr4gGEbrPCmMh8V:b-pyy9ci) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/tC_apps/translationNotes#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This is purposely pushed right?
</blockquote></details>

Done. yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607)*

**Comment by mannycolon** [comment]
Review status: 8 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[tC_apps/translationNotes, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607#-KbupYlByRAgkJP1xXUr:-KbvJDyR2-eurOvmMUrs:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b195a1ab6e1f8ecaf8f1182b8bd380ace7c50389/tC_apps/translationNotes#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Done. yes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 9 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607)*

**Comment by ihoegen** [comment]
Reviewed 6 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/607)*

**Pull request merged**
