### PR TITLE
Projects With Merge Conflicts Cannot Be Exported

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
- Blocking merge conflict projects from being exported.
- Fixing a bug with merging a project which difference was merely a verse being deleted.
- Updating the usfm-js version.
- Fixing a bug which led to falsely identify duplicate projects by book/language code combination

#### How to test this pull request:
Run ```npm update usfm-js``` to get new usfm-js module
Try opening a project that has the same language code / book combination and ensure you get an alert to that re-importing the same project is not allowed.
Try exporting a project with merge conflicts (USFM/tS) and ensure you get an alert that you must resolve them first 
- There are merge conflict projects in the tests folder ```__tests__/fixtures/project/mergeConflicts/```

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3056)

### CODE REVIEW

**Comment by RoyalSix** [comment]
#3030

**Comment by mannycolon** [comment]
@RoyalSix 
Tried exporting the following project [two_merge_conflicts_usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1447046/two_merge_conflicts_usfm.zip) and got the following alert `Cannot read property 'project' of null` instead of `Try exporting a project with merge conflicts (USFM/tS) and ensure you get an alert that you must resolve them first`

**Comment by mannycolon** [comment]
[one_merge_conflict_usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1447064/one_merge_conflict_usfm.zip)
same with this one

**Comment by mannycolon** [comment]
btw im exporting to usfm is that what we want to test?

**Comment by RoyalSix** [comment]
@mannycolon What is the workflow you are doing? I cannot replicate this error.

**Comment by mannycolon** [comment]
@RoyalSix Im exporting the projects to usfm

**Comment by RoyalSix** [comment]
@mannycolon Please try clearing the projects folder, pulling the branch and everything to have a fresh test. I am not getting this error.
Heres what I'm doing.
Downloaded the zip file you specified.
Selected the file from the ```import local project``` button
Import the project (without resolving the merge conflicts, so I pressed cancel after the license page)
Then try to export both ```usfm``` and ```csv```.
I get the dialog saying ```This project has merge conflicts and cannot be exported. Select the project to resolve merge conflicts, then try again.```

**Comment by klappy** [comment]
@mannycolon @RoyalSix This appears to work as intended when I test it.

**Comment by klappy** [comment]
Something to note, that in our new architected workflow, if we keep partially imported projects in `imports` instead of `projects` they won't be available to export until all validations are addressed.

**Comment by klappy** [comment]
Reviewed 7 of 12 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3056)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3056#-:-KyYQ9TqOZVvWOn5sggl:bnfp4nl)*

**Comment by mannycolon** [comment]
@klappy I forgot to comment that it worked for me lol (I posted it on slack)
Just missing resolving merge conflicts

**Comment by PhotoNomad0** [comment]
@mannycolon - ~~has merge conflicts to resolve here.~~  Has conflicting files, otherwise looks good to me.

**Comment by mannycolon** [comment]
Reviewed 6 of 12 files at r1, 2 of 2 files at r5, 3 of 3 files at r6, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3056)*

**Pull request merged**
