### PR TITLE
Triggering tool data reload when the tool GL is changed

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Open a Hindi project, with English as GL.
- Go Back to Tools page and select Hindi as GL.
- Note that the left menu bar and the Occurrence Notes are now displaying correctly in Hindi.
- The same should happen vice-versa.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (6bab094)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-linux-x64-2.0.0-6bab094.deb) is ready for download.
[macOS build 2.0.0 (6bab094)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-macos-x64-2.0.0-6bab094.dmg) is ready for download.
[Windows x64 build 2.0.0 (6bab094)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-win-x64-2.0.0-6bab094.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (6bab094)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-win-x32-2.0.0-6bab094.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (d0d5740)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-linux-x64-2.0.0-d0d5740.deb) is ready for download.
[macOS build 2.0.0 (d0d5740)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-macos-x64-2.0.0-d0d5740.dmg) is ready for download.
[Windows x64 build 2.0.0 (d0d5740)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-win-x64-2.0.0-d0d5740.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (d0d5740)](https://tc-builds.door43.org/build/bugfix-mannycolon-6253/translationCore-win-x32-2.0.0-d0d5740.setup.exe) is ready for download.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/containers/home/HomeContainer.js, line 51 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278#-LkeI-PvE4VEtYTdR4hj:-LkeI-PvE4VEtYTdR4hk:b-nbceff) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d0d5740ba5c819708784eb128ddbd1731137e1e2/src/js/containers/home/HomeContainer.js#L51)):*
> ```
> prevCurrentProjectToolsSelectedGL
> ```
Can't find where this is defined.

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/containers/home/HomeContainer.js, line 51 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278#-LkeI-PvE4VEtYTdR4hj:-LkeMS6CBpjVi-lVf2BC:b-7kq96i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d0d5740ba5c819708784eb128ddbd1731137e1e2/src/js/containers/home/HomeContainer.js#L51)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

> ```
> prevCurrentProjectToolsSelectedGL
> ```
Can't find where this is defined.
</blockquote></details>

This is called object destructuring rename.  Basically I'm destructuring currentProjectToolsSelectedGL from the object and renaming it prevCurrentProjectToolsSelectedGL. 

https://wesbos.com/destructuring-renaming/

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/containers/home/HomeContainer.js, line 51 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278#-LkeI-PvE4VEtYTdR4hj:-LkeOfDQ93w2u3-XrpFf:b-m7kowj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d0d5740ba5c819708784eb128ddbd1731137e1e2/src/js/containers/home/HomeContainer.js#L51)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

This is called object destructuring rename.  Basically I'm destructuring currentProjectToolsSelectedGL from the object and renaming it prevCurrentProjectToolsSelectedGL. 

https://wesbos.com/destructuring-renaming/
</blockquote></details>

See the link for more info

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6278)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
Screen Shot 2019-07-25 at 2 55 07 PM

See this in tN.  Is this part of this issue?

**Comment by PhotoNomad0** [comment]
tW looks good,

**Comment by PhotoNomad0** [comment]
there is a separate issue for English in Tn

**Pull request merged**
