### PR TITLE
node csv - #2434

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

- Refactored CSV Export to address a bunch of csv issues. 
- Updated to use node-csv library.
- Added tests for most of the stack.
- Improved error handling to catch more issues.
- Should handle bogus files in project data folder where it didn't before.
- Handles Autographa data where it didn't before.
- Looks up proper groupNames where many times they weren't found.
- Fixes issue where checkdata was exported twice both with partial data. 
- Fixes issues where csv exported  files were corrupted and malformed.

#### How to test this pull request:

- `npm install`
- `npm test`
- Go to projects page and exporting to CSV should work on all projects now.
- If you find a project that doesn't succeed document it so we can add it to the tests and fix it.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2553)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 510 of 510 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/fixtures/projects/csv/checks_performed/fr_eph_text_ulb/.apps/translationCore/resources/bibles/ULB.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553#-KsdZDa5b5_ZlKca4oNO:-KsdZDa5b5_ZlKca4oNP:bwixvo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aab1a04f587f763113dc3fc24a9fff66847ab6d3/test/fixtures/projects/csv/checks_performed/fr_eph_text_ulb/.apps/translationCore/resources/bibles/ULB.json#L3)):*
> ```JSON
> {
>   "1": {
>     "1": "Paul, an apostle of Christ Jesus through the will of God, to God's holy people in Ephesus, who are faithful in Christ Jesus.\n",
> ```

do we need another copy of the bibles here in this folder? or can we use it from the static folder?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553)*

**Comment by klappy** [comment]
*[test/fixtures/projects/csv/checks_performed/fr_eph_text_ulb/.apps/translationCore/resources/bibles/ULB.json, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553#-KsdZDa5b5_ZlKca4oNO:-KsdjxFtxYnQS6o1XwXo:bohnv2i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aab1a04f587f763113dc3fc24a9fff66847ab6d3/test/fixtures/projects/csv/checks_performed/fr_eph_text_ulb/.apps/translationCore/resources/bibles/ULB.json#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need another copy of the bibles here in this folder? or can we use it from the static folder?
</blockquote></details>

Great catch! I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553)*

**Comment by mannycolon** [comment]
Reviewed 2 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553)*

**Comment by mannycolon** [comment]
With the following project [abu_3jn_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1257864/abu_3jn_text_reg.zip)

I got the following warnings when exporting to `CSV`

screen shot 2017-08-28 at 2 56 47 pm

@klappy I was wondering if this is expected behavior?

**Comment by klappy** [comment]
@mannycolon: Issue above has been addressed and tests added to ensure it works as expected now.
Great catch! Thanks again.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553#-:-Ksewk5M9OWtSeNT4LkS:be7wmse)*

**Comment by klappy** [comment]
Just merged with develop.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553#-:-Ksf-cyyO1GwthfGiZPv:b-k0ozei)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 245 of 245 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2553#-:-Ksf8ATfHbpyFZ0KfCpw:bnfp4nl)*

**Pull request merged**
