### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

Linting is now configured to run before tests.
I've also linted a number of files that have not been touched for at least 3 weeks.

* Rules that **have not** been fully implemented will display warnings.
* Rules that **have** been fully implemented will throw errors

#### How to test this pull request:

make sure all the tests pass!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2738)

### CODE REVIEW

**Comment by klappy** [comment]
What's the codecov/patch fail that's above?

**Comment by da1nerd** [comment]
I think coverage also gives a coverage snapshot of just the files you touched in addition to the whole project. hence the `codecov/patch` and `codecov/project` reports.

Because I touched some files that didn't have sufficient coverage  (and I didn't add any tests for them) the patch report is failing.

Right now **most** of the project does not have coverage so we can ignore the patch report for now. It will be helpful later on though.

**Comment by klappy** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2738)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2738#-:-KugVrxowT0pbHltAdoe:bnfp4nl)*

**Comment by da1nerd** [comment]
@klappy for example. If I add a brand new module to the project but forget to add tests the overall coverage will probably only drop a negligible amount and won't throw any flags. However, the patch coverage will fail big time! This will help to ensure developers are writing sufficient tests and not just riding on the overall project's mostly-good-coverage rating.

**Pull request merged**
