### PR TITLE
Created commentsReducer, verseEditReducer, modulesReducer and remindersReducer

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Reducers modeled after New Data Structure #911
- create commentsReducer and commentsActions #944

#### How to test this pull request:

Test all functionalities that use redux actions

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/946)

### CODE REVIEW

**Comment by ihoegen** [comment]
@mannycolon Can we squash those commits together?

**Review by ihoegen — APPROVED** [review]
Looks good to me.

**Comment by klappy** [comment]
*[src/js/reducers/remindersReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946#-Kg-k-my6-Hj_4bL_rKn:-Kg-k-my6-Hj_4bL_rKo:bjel8qc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/34c10c566cff8e6d3073563e130004dd38ae26a3/src/js/reducers/remindersReducer.js#L13)):*
> ```JavaScript
>         case consts.TOGGLE_REMINDER:
>             return Object.assign({}, state, {
>                 enabled: !state.enabled,
> ```

We have to keep in mind that since we have a "flat" state, we can't use "enabled" for anything else.  Don't worry about it yet, but we need to consider nesting the state attributes so that we don't have name collisions or have to use long verbose attribute names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946)*

**Comment by klappy** [comment]
*[src/js/reducers/selectionsReducer.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946#-Kg-kUlKZutdG_3_oTlM:-Kg-kUlKZutdG_3_oTlN:b-tahlk5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/34c10c566cff8e6d3073563e130004dd38ae26a3/src/js/reducers/selectionsReducer.js#L17)):*
> ```JavaScript
>         modifiedTimestamp: action.modifiedTimestamp
>       });
>     case consts.REMOVE_SELECTION:
> ```

I'm wondering if REMOVE_SELECTION is the same as setting state to default values. When would we call this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946)*

**Comment by klappy** [comment]
Reviewed 17 of 19 files at r1.
Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946)*

**Comment by mannycolon** [comment]
Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/reducers/remindersReducer.js, line 13 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946#-Kg-k-my6-Hj_4bL_rKn:-Kg-w1sV76xwm8IZruk7:bgxandd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/34c10c566cff8e6d3073563e130004dd38ae26a3/src/js/reducers/remindersReducer.js#L13)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We have to keep in mind that since we have a "flat" state, we can't use "enabled" for anything else.  Don't worry about it yet, but we need to consider nesting the state attributes so that we don't have name collisions or have to use long verbose attribute names.
</blockquote></details>

I'm probably going to work on a story to address that issue.

---

*[src/js/reducers/selectionsReducer.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946#-Kg-kUlKZutdG_3_oTlM:-Kg-wDsk6ObZ1LUJSUpr:b6yxr7h) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/34c10c566cff8e6d3073563e130004dd38ae26a3/src/js/reducers/selectionsReducer.js#L17)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm wondering if REMOVE_SELECTION is the same as setting state to default values. When would we call this?
</blockquote></details>

I think it's not. because when you click on a selection its supposed to de-select.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946)*

**Comment by mannycolon** [comment]
Reviewed 1 of 19 files at r1.
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/946)*

**Pull request merged**
