### PR TITLE
Updated to tc-ui-toolkit 0.10.9 that fixes more bugs w/ missing text in the scripture pane

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Verify the following verse isn't missing words (Titus 1:3 & Titus 1:12)

image
image

image

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5238)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5238)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @neutrinog)

___
*[tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5238#-LP25DtS2cvKh9ih6NRU:-LP25DtS2cvKh9ih6NRV:b6y2c1t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/90fc5f6b7f73aece9ade6f974accb6805356dd51/tC_apps/translationWords#L1)):*
> ```
> Subproject commit a755223eba9a8007d6b2f6bca406e71fe521fa21
> ```

Are you sure about this tw commit?

**Comment by PhotoNomad0** [comment]
@mannycolon - how do I test the updated tc-ui-toolkit?

**Comment by da1nerd** [comment]
@mannycolon @PhotoNomad0 this PR is now deprecated (except for the dependency update).
@PhotoNomad0 yesterday a commit of yours was merged in that corrected the tW submodule commit reference and subsequently fixed the concourse builds.

@mannycolon tC is currently pointing to the correct tW commit (1.0.2) so you can close this PR and open a new one with just your update to the toolkit dependency.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by mannycolon** [comment]
@neutrinog I'm not surprised another PR made it first it took you too long to review this PR LMAO

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Pull request merged**
