### PR TITLE
Feature 6029/Add versioning

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- added check that app meets the minimum version requirements in project manifest.
- added error message when the app does not meet the minimum version requirements in project manifest.  Error message has button for updating app.
- when project is opened, then edit version and compatibility versions are updated in manifest.

#### Please include detailed Test instructions for your pull request:
- checkout branch, do `npm run load-apps`, `npm ci`, `npm start`
- find a loaded project and edit the manifest and add `"tc_min_compatible_version": "1.1.5"`
- select project and should get error message about compatibility.  Click cancel.  Project should not be selected.
- edit the manifest and set `"tc_min_compatible_version": "1.1.4"`
- select project and it should load normally.
- try to download from door43 this project `https://git.door43.org/photonomad1/en_zzz_luk_book`
- should get error about compatibility.  Click update app and should see message app is up to date.  Project should not be downloaded.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@PhotoNomad0 Can you merge this one with develop

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 9 of 13 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 252 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041#-Ldyh--3CVwuI3tJAzHc:-Ldyh--500FWeYjbB-ME:b-vcsfse) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387d4c29dcda33df444d22c9f5541b600dbd8bed/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L252)):*
> ```JavaScript
> 
>     const minVersion = manifest[tc_MIN_COMPATIBLE_VERSION_KEY];
>     if (minVersion && (versionCompare(APP_VERSION, minVersion) < 0)) {
> ```

If the minimum version does not exist should this also reject?

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @RoyalSix)

___
*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 252 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041#-Ldyh--3CVwuI3tJAzHc:-LeDfb8u5e4JBZI9T_oe:bjkdogn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387d4c29dcda33df444d22c9f5541b600dbd8bed/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L252)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

If the minimum version does not exist should this also reject?
</blockquote></details>

No, the thought is that if this version does not have a version number, then it is a project edited in an older version of the app that we can migrate forward.  We only reject if someone edited this project in a newer version of the app.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by RoyalSix** [comment]
I am testing the second part when upgrading a project from door43 and after selecting "Update app" it says the app is on the latest version and then nothing happens. Is this expected behavior? @PhotoNomad0

**Comment by PhotoNomad0** [comment]
Yes, this is expected.  The last published version was 1.1.3, so there is not yet a new version published. @royalsix

**Review by RoyalSix — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6041)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
