### PR TITLE
Added new radio buttons and fix Username/Alias saving in metadata for Reports 

### PR DESCRIPTION
**Pull request by mannycolon**
**This Pull request adds the following changes:**
- Refactored translationCore code in order to change RETAINED to CORRECT, WRONG to FLAGGED.
- Changed the way the store handles status to accommodate a new question for each check. Therefore, Added retained/replaced to the store.
- Added radio buttons to UI for retained and replaced.
- Edited/maintained the API documentation in order to maintain consistency.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/133)

### CODE REVIEW

**Comment by mannycolon** [comment]
#117

**Comment by mannycolon** [comment]
#106

**Comment by mannycolon** [comment]
#116

**Comment by ihoegen** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/133)_

**Pull request merged**
