### PR TITLE
Alignment tool backend implementation 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Alignment tool backend implementation

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2721)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2721)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2721#-:-KuWp-tgO0AUDUS-Q6Os:bnfp4nl)*

**Comment by klappy** [comment]
@mannycolon Can you merge with latest develop branch?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2721#-:-KuWpPjtESMUf-YDeqXd:b-ta58ix)*

**Comment by RoyalSix** [comment]
@mannycolon can I get the project for testing this

**Comment by mannycolon** [comment]
[bes_tit_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1322340/bes_tit_text_reg.zip)
@RoyalSix

**Pull request merged**
