### PR TITLE
Load recent projects on demand

### PR DESCRIPTION
**Pull request by EllDoubleYew**
Adds a menu option in the load modal to load a recent project whenever you want.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/267)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/267)_

**Comment by mannycolon** [comment]
@EllDoubleYew @ihoegen 
so line 30 through 33 in RecentProjects.js (31 to be exact is returning  `Uncaught TypeError: Cannot read property 'bind' of undefined`

```
loadProject(filePath) {
    this.refs.TargetLanguage.sendFilePath(filePath, null, this.props.onLoad.bind(this));
    api.putDataInCommon('saveLocation', filePath);
  }
```

**Comment by mannycolon** [comment]
@EllDoubleYew @ihoegen I don't think that hidden files should be display here, this is probably a mac only issue

screen shot 2016-11-02 at 11 33 10 am

**Comment by mannycolon** [comment]
when i click `Load project` it doesn't work

**Comment by ihoegen** [comment]
@mannycolon I fixed the issue with .DS_Store showing as a recent project.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/267)_

**Comment by mannycolon** [comment]
@EllDoubleYew @ihoegen 
`Im getting this error **Uncaught TypeError: Cannot read property 'bind' of undefined on RecentProjects.js**`

**Comment by EllDoubleYew** [comment]
@mannycolon can you see which line is throwing that error?

**Comment by mannycolon** [comment]
@EllDoubleYew did you get to fix the bugs????

**Comment by EllDoubleYew** [comment]
The problem is not necessarily the function binding but that we are looking for a `meta.json` when we load one of these recent projects. Has that changed @ihoegen?

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/267)_

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/js/components/core/RecentProjects.js, line 32 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/267#-KWJjpZCDAPOwgs9pYyO:-KWJjpZCDAPOwgs9pYyP:blo1gy7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e8a5cd20408e97d1c9070f5f09b6563e37d3aed5/src/js/components/core/RecentProjects.js#L32)):_

> ``` JavaScript
>   loadProject(filePath) {
>     console.log(this.refs.TargetLanguage);
>     console.log(this.props);
> ```

when you can just remove the console.logs

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/267)_

**Comment by ihoegen** [comment]
@elldoubleyew I have never seen a meta.json file before.

**Comment by mannycolon** [comment]
@EllDoubleYew what else do we need to merge this PR with develop????

**Comment by EllDoubleYew** [comment]
Require the component in the render method rather than at global scope

**Comment by mannycolon** [comment]
@EllDoubleYew is this ready for testing???

**Pull request closed without merging**
