### PR TITLE
bugfix 5832/fix multiple prompts for invalidation on tool launch

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fix to detect if invalidations alert message is already displayed before showing.

#### Please include detailed Test instructions for your pull request:
- unzip and open this project [en_new_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3474268/en_new_phm_book.zip)
- launch tN and should only see one invalidation alert.
- launch tW and should only see one invalidation alert.
- launch WA and should only see one invalidation alert.
- now we change the order with tW first:
  - unzip and open this project [en_new_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3474268/en_new_phm_book.zip)
  - launch tW and should only see one invalidation alert.
  - launch tN and should only see one invalidation alert.
  - launch WA and should only see one invalidation alert.
- Verify that problem is fixed mentioned at bottom of issue https://github.com/unfoldingword-dev/translationcore/issues/5832 - editing `gospel` in https://git.door43.org/TC_SAVE/en_new_phm_book

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6344)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (80ed240)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-linux-x64-2.0.0-80ed240.deb) is ready for download.
[macOS build 2.0.0 (80ed240)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-macos-x64-2.0.0-80ed240.dmg) is ready for download.
[Windows x64 build 2.0.0 (80ed240)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x64-2.0.0-80ed240.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (80ed240)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x32-2.0.0-80ed240.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (9dcc7e7)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-linux-x64-2.0.0-9dcc7e7.deb) is ready for download.
[macOS build 2.0.0 (9dcc7e7)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-macos-x64-2.0.0-9dcc7e7.dmg) is ready for download.
[Windows x64 build 2.0.0 (9dcc7e7)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x64-2.0.0-9dcc7e7.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (9dcc7e7)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x32-2.0.0-9dcc7e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (70ad977)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-linux-x64-2.0.0-70ad977.deb) is ready for download.
[macOS build 2.0.0 (70ad977)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-macos-x64-2.0.0-70ad977.dmg) is ready for download.
[Windows x64 build 2.0.0 (70ad977)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x64-2.0.0-70ad977.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (70ad977)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x32-2.0.0-70ad977.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (8670972)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-linux-x64-2.0.0-8670972.deb) is ready for download.
[macOS build 2.0.0 (8670972)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-macos-x64-2.0.0-8670972.dmg) is ready for download.
[Windows x64 build 2.0.0 (8670972)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x64-2.0.0-8670972.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (8670972)](https://tc-builds.door43.org/build/bugfix-mcleanb-5832.2/translationCore-win-x32-2.0.0-8670972.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6344)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
