### PR TITLE
Now alerting the user if there is no Internet connection when searching for Door43 projects.

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Now alerting the user if there is no Internet connection when searching for Door43 projects.
- Fixed multiple bugs with online import failing to delete projects folder when project online import fails.
- Fixed failing OnlineImportWorkflowActions and LocalImportWorkflowActions unit tests.

#### How to test this pull request:
- Turn off your internet connection.
- Go to **Import Online project** and click access internet. An alert should show up saying **Unable to connect to the server. Please check your Internet connection.**
- Try searching door43 project with different search criteria and the alert should be displayed.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3426)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/ImportOnlineSearchActions.js, line 39 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426#-L0fP6NI3NX_jc3VTz8J:-L0fP6NI3NX_jc3VTz8K:b-59hxqp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/61ac1a4d31c45316112260d8668d1a2093859f4f/src/js/actions/ImportOnlineSearchActions.js#L39)):*
> ```JavaScript
> export const searchReposByUser = (user, firstFilter, secondFilter) => {
>   return async (dispatch) => {
>     if (navigator.onLine) {
> ```

Good find, didn't realize this was available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426#-:-L0fWsZHcG02bMZwP7aE:bnfp4nl)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426#-:-L0fbYCrRvL_kstkUVgP:bnfp4nl)*

**Comment by richmahn** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426)*

**Comment by richmahn** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3426#-:-L0fjXPrG3uhjg_NGZa6:bnfp4nl)*

**Pull request merged**
