### PR TITLE
Feature - #3676 - Status badges with chips and mouse-over tooltip

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses first task of epic #1998 - showing multiple status badges for invalidation (still waiting on its implementation in #3086 but doesn't block this PR), reminders, verse edits, selections and comments.

#### Please include detailed Test instructions for your pull request:
NOTE: This does NOT have the filter menu at the top like you see in the images in #1998. It should however have the icons next to the Bible references like you see in those images, minus the ability to see invalidated verses.

- [ ] Check out this branch, `feature-richmahn-3676` in your main tC repo
- [ ] Run `npm i && npm run update-apps` in tC root directory
- [ ] Run the app, load a project
- [ ] For tW, in the left sidebar, you should see no badge, one badge, or a badge with a chip with 2 - 5 (5 if invalidation is implemented [#3086], 4 if not). So try bookmarking the active verse, making  a comment, selecting text, and editing the verse.
- [ ] For wA, when the word bank is empty, a check box should appear. This is how it used to behave, but it also uses the new status badge implementation to make it happen, so test it.
- [ ] Note that in tW, because there was already a tool tip to show the full selected text when you hover over the Bible reference in the left sidebar, I had to separate the tool tip for the status badge and the tool tip for the Bible reference/selected text. They both use the new 3rd party react-tooltip now. Please check for any oddities. The tool tip SHOULD change position (float right instead of bottom) if there isn't room below to show the whole tool tip. This is expected. 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4264)

### CODE REVIEW

**Comment by richmahn** [comment]
Just so you can see, here is a screen shot of me forcing an invalidated = true for some items (you can do it too by changing `glyphs = [];` to `glyphs = ['invalidated'];` on line 118 of `GroupMenuContainer.js`:

**Comment by PhotoNomad0** [comment]
Reviewed 5 of 16 files at r1, 11 of 17 files at r2, 5 of 9 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[__tests__/CSVExportActions.test.js, line 29 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264#-L9MHoIA9qPZmKfYNlrl:-L9MHoIA9qPZmKfYNlrm:bhn12a2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/944a6e614dd79447ef93d7258f51ab982542db2e/__tests__/CSVExportActions.test.js#L29)):*
> ```JavaScript
> 
> // data
> const noChecksPerformedPath = path.join('__tests__', 'fixtures', 'project', 'csv', 'no_checks_performed', 'fr_eph_text_ulb');
> ```

Rich - this is overkill. The path.join will convert to the appropriate separators.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[__tests__/CSVExportActions.test.js, line 29 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264#-L9MHoIA9qPZmKfYNlrl:-L9MJQ4wE95oOdPSaOlB:bcijier) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/944a6e614dd79447ef93d7258f51ab982542db2e/__tests__/CSVExportActions.test.js#L29)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Rich - this is overkill. The path.join will convert to the appropriate separators.
</blockquote></details>

Ok, sometimes it does get it wrong. Not sure when though. I'll use slashes but make sure it is fed through path.join()

---

*[__tests__/GroupMenuContainer.test.js, line 191 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264#-L9M9xuR4s7l6KE_ubat:-L9M9xuSD_G7v0lAwJcl:b-l0eltn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/944a6e614dd79447ef93d7258f51ab982542db2e/__tests__/GroupMenuContainer.test.js#L191)):*
> ```
> groupsDataReducer.groupsData
> ```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264)*

**Comment by RoyalSix** [comment]
I was able to get the `svg` to render normally by just using an `` tag
Heres the gist https://gist.github.com/RoyalSix/161297e0446e7e75b967f3d1a4eda161
The svg you have is black, but the mockup is white. [Here](https://github.com/unfoldingWord-dev/translationCore/files/1881590/unlink-symbol.svg.zip) is one that is white internally in the `svg`
This way you do not need an external library
@richmahn

**Comment by PhotoNomad0** [comment]
:lgtm: - Code Review
:lgtm: - Program Testing

---

Reviewed 3 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264#-:-L9MSXAV7aqy0qPbCGkD:bcl1pim)*

**Comment by richmahn** [comment]
Review status: 16 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/CSVExportActions.test.js, line 29 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264#-L9MHoIA9qPZmKfYNlrl:-L9PtT9FByZibI3FWCqx:b2qx9ei) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/944a6e614dd79447ef93d7258f51ab982542db2e/__tests__/CSVExportActions.test.js#L29)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Ok, sometimes it does get it wrong. Not sure when though. I'll use slashes but make sure it is fed through path.join()
</blockquote></details>

Ok, changed back and done propertly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 9 files at r8, 3 of 6 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4264)*

**Pull request merged**
