### PR TITLE
restructure redux data persistence implementation

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/922)

### CODE REVIEW

**Comment by klappy** [comment]
Overall this looks good, wondering if the filenames for loadMethods.js and saveMethods.js should be changed to match exactly what it does unless we plan on adding more methods to these files, right now they are only for settings/localstorage.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-:-KfbCCiKywbl5xPA1As4:bjex8wb)*

**Comment by mannycolon** [comment]
@klappy loadMethods.js and saveMethods.js will hold all load and save methods for different data.

**Comment by mannycolon** [comment]
@klappy added comments to describe what is the purpose of the different files as well as description for all methods

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/utils/loadMethods.js, line 11 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjCrYinV3n3vNgTdrq:-KfjCrYinV3n3vNgTdrr:b-nw4041) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/loadMethods.js#L11)):*
> ```JavaScript
> const PARENT = pathex.datadir('translationCore')
> const SETTINGS_DIRECTORY = pathex.join(PARENT, 'settings.json')
> const RESOURCES_DATA_DIR = pathex.join('apps', 'translationCore', 'resources')
> ```

I don't think this will work on Windows. Maybe do `PARENT` instead of `apps`

---

*[src/js/utils/localStorage.js, line 3 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjD34BfoA_p3hoAeEe:-KfjD34BfoA_p3hoAeEf:b-uy86vh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/localStorage.js#L3)):*
> ```JavaScript
> import fs from 'fs-extra'
> import path from 'path'
> import pathex from 'path-extra'
> ```

`path-extra` has the same methods as path, I would let path reference `path-extra` instead, maybe we should move the rest of the app towards that. 

---

*[src/js/utils/saveMethods.js, line 11 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjDI5mttJJQorisyPM:-KfjDI5mttJJQorisyPN:bvq3jac) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/saveMethods.js#L11)):*
> ```JavaScript
> const PARENT = pathex.datadir('translationCore')
> const SETTINGS_DIRECTORY = pathex.join(PARENT, 'settings.json')
> const RESOURCES_DATA_DIR = pathex.join('apps', 'translationCore', 'resources')
> ```

Same as loadMethods.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922)*

**Comment by EllDoubleYew** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/utils/loadMethods.js, line 11 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjCrYinV3n3vNgTdrq:-KflPM_KsV9IPWEuuZe8:bsmhems) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/loadMethods.js#L11)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think this will work on Windows. Maybe do `PARENT` instead of `apps`
</blockquote></details>

From my testing it appears to work on windows. Have you tested it yet?

---

*[src/js/utils/loadMethods.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KflPXhpCqvnO6GPshBO:-KflPXhpCqvnO6GPshBP:b47rz9c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/loadMethods.js#L18)):*
> ```JavaScript
>     settings = fs.readJsonSync(SETTINGS_DIRECTORY)
>   } catch (err) {
>     console.warn(err)
> ```

would losing the settings constitute refreshing the app? If so lets use console.error so it can prompt the user for a reboot. If not do we have some kind of fallback default settings that would still make things run on some settings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/utils/loadMethods.js, line 11 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjCrYinV3n3vNgTdrq:-KflT-xAY26N5Szi36J9:byypksx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/loadMethods.js#L11)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

From my testing it appears to work on windows. Have you tested it yet?
</blockquote></details>

apps is just a folder name thus a directory path. that's base on the new data structure.

---

*[src/js/utils/loadMethods.js, line 18 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KflPXhpCqvnO6GPshBO:-KflTBIRrzEAJoHCV9OX:b-826dw9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/loadMethods.js#L18)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

would losing the settings constitute refreshing the app? If so lets use console.error so it can prompt the user for a reboot. If not do we have some kind of fallback default settings that would still make things run on some settings?
</blockquote></details>

i need to use warn because if the there's any error i still want the app to keep going and the settings will be the default settings in the settings reducer. this is how it is supposed to be based on the data persistence imlementation.

---

*[src/js/utils/localStorage.js, line 3 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjD34BfoA_p3hoAeEe:-KflTcN99x6Hw19_FDpH:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/localStorage.js#L3)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

`path-extra` has the same methods as path, I would let path reference `path-extra` instead, maybe we should move the rest of the app towards that. 
</blockquote></details>

Done.

---

*[src/js/utils/saveMethods.js, line 11 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922#-KfjDI5mttJJQorisyPM:-KflTgdGYgoJ-yemOjc8:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5da9ed224ad93e1b4017a3672541c8c44e736d20/src/js/utils/saveMethods.js#L11)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Same as loadMethods.js
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/922)*

**Pull request merged**
