### PR TITLE
Package Manager

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request removes the modules folder, and implements a beta version of a package manager.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/179)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Files look good, just going to pull branch now

---

Reviewed 5 of 14 files at r2, 1 of 3 files at r3, 3 of 5 files at r4, 80 of 80 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179#-:-KTNvX3c_6QFumCd3zWd:b8656lg)_

**Comment by RoyalSix** [comment]
What exactly should I be looking for?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179#-:-KTNxvW4L_HCJip3BE8I:bnxridv)_

**Comment by ihoegen** [comment]
Pretty much you need to open the package manage, download a package, and
wait for the notification saying it was completely installed.  Then you
just want to do some checks.

**Comment by mannycolon** [comment]
#159  #160 #161 #162 #165

**Comment by mannycolon** [comment]
wow this is a mazamune type of merge conflict
@ihoegen @RoyalSix @EllDoubleYew

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r7.
Review status: 88 of 89 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
screen shot 2016-10-08 at 6 27 54 pm
this is what happened when i tested the branch

**Comment by ihoegen** [comment]
@mannycolon From the console, you need to run `localStorage.clear()`

**Comment by mannycolon** [comment]
screen shot 2016-10-09 at 10 32 55 am
so when I clicked download this error modal popped  up
@ihoegen

**Comment by ihoegen** [comment]
@mannycolon try `npm install npm` to install npm locally, I wonder if npm
ignores itself when it's on the package.json @elldoubleyew

**Comment by EllDoubleYew** [comment]
@ihoegen `npm install npm` does successfully install npm in my node_modules directory but I get the same error.

**Comment by ihoegen** [comment]
Does it show in the bin folder too, under node_modules?

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r8.
Review status: 87 of 89 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r8.
Review status: 88 of 89 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by ihoegen** [comment]
Can we please call this done?

**Comment by mannycolon** [comment]
@ihoegen @EllDoubleYew what is holding this back??? yesterday i tested this branch and it work fine, what else do we need?? anything i can do to help??

**Comment by ihoegen** [comment]
It should be good to go now

**Comment by mannycolon** [comment]
@ihoegen ok, how about you pull from develop and then i will merge the PR

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r9.
Review status: 87 of 89 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r9.
Review status: 88 of 89 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Comment by ihoegen** [comment]
Let's see what @elldoubleyew has for us in terms of issues but I think I
merged last night, unless there's new things on develop

**Comment by mannycolon** [comment]
@ihoegen There are a few new PR's that were merged this morning

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/179)_

**Pull request merged**
