### PR TITLE
Bugfix 5970/fix rendering of multiple greek words in tW

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- changes to support array of quote words in place of multiple word strings:
  - updated tc-source-content-updater, tc-ui-toolkit, and translationWords to support quote arrays
  - Regenerated resources to support array of quote words
  - updated tCore with @RoyalSix 's fixes to update index cache.

#### Please include detailed Test instructions for your pull request:
- checkout tCore branch and run `npm run load-apps`  and `npm ci` 
- download https://git.door43.org/lrsallee/en_ult_luk_book
- select `other words` on tW card and launch
- select 12 tribes and should see:
Screen Shot 2019-04-22 at 4 32 42 PM
- note that in the ULT that the word `the` between `judging` and `twelve` is NOT highlighted.  It is associated with `τὰς` which is not part of the key phrase in the Greek (English word order is different than Greek).

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@PhotoNomad0 For some reason tN isn't showing. tW wasn't showing either until I checked out the branch `bugfix-mcleanb-5970`. Not sure if that is expected behavior.

Other than that the functionality is working in the test outlined.

**Comment by PhotoNomad0** [comment]
@RoyalSix  - note that this is for v1.1.4, there is no tN.  I'll need to know what commit of tW you were using to reproduce what you saw.  I should have put `npm run load-apps` in the test steps, updating.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 350 of 353 files at r1, 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983)* status: 360 of 361 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 100 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983#-LdA8C9o2_eBBPg8ua9c:-LdA8C9pCp8hyn3EfeVF:b-e9twrb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9a66441446f6a371c4c9e90878e17c317220896c/src/js/actions/MyProjects/ProjectLoadingActions.js#L100)):*
> ```JavaScript
>         // select default categories
>         const language = getToolGatewayLanguage(getState(), t.name);
>         if (t.name !== "translationWords") {
> ```

How come we only set the default if its not tW?

**Review by RoyalSix — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983)* status: 360 of 361 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

___
*[tC_apps/translationWords, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983#-LdABMkO7q2ztqOh9cjq:-LdABMkP1u_YKIHS8Xr8:byquu61) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9a66441446f6a371c4c9e90878e17c317220896c/tC_apps/translationWords#L1)):*
> ```
> Subproject commit c56f2c8949635def447d76e8f9e8faa3e8ba4ab3
> ```

Do we need this?

**Comment by PhotoNomad0** [comment]
Yes we need the commit, just double chech that it is latest for 1.1.4

**Comment by PhotoNomad0** [comment]
I just copied from your PR, presume tN needs it. It breaks tW so excluded it.

**Comment by mannycolon** [comment]
@PhotoNomad0 You added code from Jays PR when it wasn't completed and not even merged with develop branch. You may want to update this PR with his latest fixes to that PR which was just recently merged.

**Review by mannycolon — DISMISSED** [review]
> Reviewed 3 of 11 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983)* status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5983)* status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

**Comment by mannycolon** [comment]
`LGTM`

**Pull request merged**
