### PR TITLE
Improves builds

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This changes the build process to use electron-packager directly instead of via electron-forge.
Doing so allows us to have more control over compiling installers.

In addition to changes in the build process:

* the windows installer now uses a native looking installation dialog with prompts.
* the macOS application is now distributed in a .dmg archive. However, the dmg is currently uncompressed. I hope to figure out a way to compress it later.
* the macOS app closes down completely when the window is closed. Previously it would remain running with no way to re-display the window, requiring the user to force shut down the app.

This also includes some fixes to `myProjectsHelpers` which was breaking the CSVExportActions tests.

#### How to test this pull request:

The generated installers for Windows and macOS should run properly.

The easiest way to generate *all* installers is on linux. On windows you can generate the windows installers by first installing [Inno Setup](http://www.jrsoftware.org/isdl.php). You need this software on linux as well, however there's a script to install it automatically in `scripts/innosetup/setup.sh`

Generating the installers is a two step process: build (packages code), then release (prepares installer/distributable). See the travis config file for examples.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3146)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
LGTM

But of course all of this is over my head.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-:-KypSwC0do61TOKigY2Y:b65a01o)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-:-KypTGekXKnQJnNCfzbb:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
@neutrinog - got my Linux vm configured to build releases.  Wow there is a lot of work in this build!  I'm impressed.

I was able to build the installers, and install worked on mac and windows (64-bit version).

**Review by PhotoNomad0 — APPROVED** [review]

**Comment by PhotoNomad0** [comment]
Reviewed 10 of 18 files at r1, 1 of 2 files at r2, 1 of 5 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 4 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-:-KyvK4HD0ng6L4zCwY_U:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 10 of 18 files at r1, 1 of 2 files at r2, 1 of 5 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 4 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tC_apps/translationWords, line 1 at r9](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-KyvNZjvMdCKVYVBtx7s:-KyvNZjwqTW9-lB4Iz1L:b-poeb1g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cbf3556f82365ab895bf72e52a5242d661d79b83/tC_apps/translationWords#L1)):*
> ```
> Subproject commit 5395a72c684cdd543a915aff9c26195399f3b2e6
> ```

Is this an intended change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146)*

**Comment by mannycolon** [comment]
Reviewed 9 of 18 files at r1, 1 of 2 files at r2, 1 of 5 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 4 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 20 at r9](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-KyvWpi62pfZxEKIaIU2:-KyvWpi62pfZxEKIaIU3:b-l3djsg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dfb4ff46f81ddea7916114e096f2357541315a04/.gitignore#L20)):*
> ```
> 
> # just in case people are lazy while writing tests
> __tests__/output
> ```

lol I really like this one. I hate having to delete files after running `npm test`

---

*[tC_apps/translationWords, line 1 at r9](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-KyvNZjvMdCKVYVBtx7s:-KyvYbbOxA5yW5nzJaA-:b-aqvtjr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cbf3556f82365ab895bf72e52a5242d661d79b83/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is this an intended change?
</blockquote></details>

I believe this isn't the correct commit of this tool. the Latest commit is **5395a72**

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146)*

**Comment by RoyalSix** [comment]
Just finished testing on Linux! The build works and tC works, nice job! @neutrinog 
...now on to windows which should be easier because I already have a local env set up

**Comment by PhotoNomad0** [comment]
@RoyalSix - I was able to build and install on windows and mac.  Looks good.

**Comment by RoyalSix** [comment]
When building on windows I had to install module ```agentkeepalive```
Its building right now I'll update when done @PhotoNomad0 
** Update **
All the builds work...Just waiting for a reply to the tools commit comment, and then we should be able to merge 👍

**Comment by da1nerd** [comment]
*[tC_apps/translationWords, line 1 at r9](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146#-KyvNZjvMdCKVYVBtx7s:-KyvwoL7ubompOD5N84v:b36wsym) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cbf3556f82365ab895bf72e52a5242d661d79b83/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I believe this isn't the correct commit of this tool. the Latest commit is **5395a72**
</blockquote></details>

That change was unintended. I try to remember to run `npm run load-apps` before committing things but apparently forgot this time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3146)*

**Pull request merged**
