### PR TITLE
Clean App on Version Change

### PR DESCRIPTION
**Pull request by ihoegen**
This commit keeps track of versions, and if the previous version opened
is different from the current, it will remove the last opened project
and module from `localStorage`, preventing a load that could potentially fail.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/635)

### CODE REVIEW

**Comment by mannycolon** [comment]
@ihoegen Cannot merge your PR yet its messing with my recent Projects component. It isnt showing when it actually should show in the white screen

**Comment by ihoegen** [comment]
@mannycolon Fixed it

**Comment by ihoegen** [comment]
@mannycolon What's the status on this PR

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/pages/app.js, line 713 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/635#-KcJ_lqGi9yfWs53Ly1p:-KcJ_lqGi9yfWs53Ly1q:b-vecajx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1089359b1096f9324a5dbe67dcd0395b5f3a22bc/src/js/pages/app.js#L713)):*
> ```JavaScript
>       localStorage.removeItem('lastProject');
>       localStorage.removeItem('lastCheckModule');
>       localStorage.setItem('version', packageJson.version);
> ```

do you ever set version on first ever app installed??

---

*[src/js/pages/app.js, line 805 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/635#-KcJ_v-N7cOO1MMedYs0:-KcJ_v-N7cOO1MMedYs1:bizngn3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1089359b1096f9324a5dbe67dcd0395b5f3a22bc/src/js/pages/app.js#L805)):*
> ```JavaScript
>               <StatusBarContainer />
>             </Row>
>             <Col className="col-fluid" md={3} style={{ padding: 0, width: "300px" }}>
> ```

why did you remove the Col different sizes??

---

*[src/js/pages/app.js, line 811 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/635#-KcJ_zvBSF2-lBhnQnAh:-KcJ_zvBSF2-lBhnQnAi:bo3yhpi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1089359b1096f9324a5dbe67dcd0395b5f3a22bc/src/js/pages/app.js#L811)):*
> ```JavaScript
>               />
>             </Col>
>             <Col style={RootStyles.ScrollableSection} md={9}>
> ```

same here why di you remove the different Col screen sizes ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/635)*

**Pull request merged**
