### PR TITLE
Completed Tool Main Page (HomeScreen)

### PR DESCRIPTION
**Pull request by mannycolon**
### This pull request addresses:

- Created ToolCard Component.
- Now when selecting a project it automatically takes you to the next step (Tools main page).
- Now when you click the Home button in the Status bar it takes you to the HomeScreen.

### How to test this pull request:

- Pull `feature/manny/tool-main-page/976` branch from both `tN` and `tW`.
- Select a project. 
    (The toolCards page should automatically open and all tool cards should have accurate progress in the progress bar)
- Try loading a project with both tools using the tool cards in the Tool Main Page.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2119)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 1 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 2 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 3 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 4 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 5 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 6 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 9 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
1. The spacing between the cards and the scroll bar could be improved to match the Project Management screen cards, to show the shadow of the cards. (paddingRight: 10px on the container that has the scrollbar)
2. I know it matches the mockups, but the padding/margins don't match the other screens. Can we re-evaluate the look we like from all cards, on all screens, and normalize them? (don't have to do anything before merging just think about it)
3. After selecting a tool, then going home to the overview page, click next to get to the tools selection since a project is already selected,  the tools come up empty.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-:-KohJ1UtKedJZMZ4OTIw:btgkmpa)*

**Comment by klappy** [comment]
Overall, good job, it's exciting to have the full functionality!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-:-KohLBtNH3PhopfPW5rt:bbcyk5n)*

**Comment by klappy** [comment]
*[src/js/components/home/toolsManagement/ToolsCards.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-KohLVlW7ysIb_NyUEx2:-KohLVlW7ysIb_NyUEx3:bqzsxo2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5fe00f5fa34ecb54b439171c83895e8f11032d41/src/js/components/home/toolsManagement/ToolsCards.js#L46)):*
> ```JavaScript
>     } else {
>       return (
>         <div style={{ height: '100%', overflowY: 'auto' }}>
> ```

Add `, paddingRight: '10px' ` here to match the Project page's scrolling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by RoyalSix** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by RoyalSix** [comment]
Looks good. Theres a weird workflow issue if you choose a project, tool, and then launch it. And then you try and go back and do the same thing the tool page will say no default tC modules found, don't know if its an issue for this task or if we need to create a new one.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-:-Kohhrz7PTksLyp01YBx:b-izr0ki)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/home/toolsManagement/ToolsCards.js, line 46 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-KohLVlW7ysIb_NyUEx2:-Koi-P_ZZd0u9O3PIw27:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5fe00f5fa34ecb54b439171c83895e8f11032d41/src/js/components/home/toolsManagement/ToolsCards.js#L46)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Add `, paddingRight: '10px' ` here to match the Project page's scrolling.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Looks good. I tried to debug to find out why the loading spinner doesn't show up before it does the work. It feels like it does the work then changes screens and the quickly shows the loading spinner once it is too late to do any good. Can you figure it out? 

Also, I thought the desired workflow from Ben and Koz was to take you back to the overview. We agreed that it was an extra step but was what the stakeholders asked for. Let me know if the plan changed. I also think that may go back to the workflow that we had before this where the spinner worked in time and not came in too late.

Once those are addressed, I think we're good to go. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-:-Kom-k5oMYeLWKbkYE6o:bmruru0)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119#-:-Komrp6NpZOja8UpMrSK:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2119)*

**Pull request merged**
