### PR TITLE
Removed Username As Default Checker

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR removed the current logged in user from being added as a user in the project information check

#### How to test this pull request:
Load a new project that doesn't have all the manifest data fulfilled. (usfm project). and Make sure there is no default checker

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2709)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709#-:-Ku7RjMxOttZ-pW4nDHR:bnfp4nl)*

**Comment by klappy** [comment]
Tested and works.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709#-:-Ku7UA6cT62Vd9HSQJb7:b-1q5yld)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/js/components/projectValidation/ProjectInformationCheck/index.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709#-KuKI-qkVzV0l6HfFdeL:-KuKI-qkVzV0l6HfFdeM:by1qtdo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3f3fb4e9a4a982ea7dae0679c218497f06629d37/src/js/components/projectValidation/ProjectInformationCheck/index.js#L16)):*
> ```JavaScript
>     let {
>       translators,
>       checkers,
> ```

I don't think this what the story asked for. it needs to be removed from USFM manifest generation not from here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709)*

**Comment by mannycolon** [comment]
Based on the code this doesn't seem to meet the story

**Comment by klappy** [comment]
*[src/js/components/projectValidation/ProjectInformationCheck/index.js, line 16 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709#-KuKI-qkVzV0l6HfFdeL:-KuKOrQVmisKSSfsnp_Q:bl5ii9u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3f3fb4e9a4a982ea7dae0679c218497f06629d37/src/js/components/projectValidation/ProjectInformationCheck/index.js#L16)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I don't think this what the story asked for. it needs to be removed from USFM manifest generation not from here.
</blockquote></details>

Oh, so there should still be checkers at this point, but only if they persist from an imported project?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2709)*

**Comment by RoyalSix** [comment]
@mannycolon I see. I can update that.

**Pull request closed without merging**
