### PR TITLE
Coverage Support

### PR DESCRIPTION
**Pull request by da1nerd**
# What's include in this Pull Request

1. Adds support for generating and submitting coverage data.
2. Migrates tests to Jest instead of Mocha
3. Mostly decouples tests from the production environment (enforced proper unit testing paradigm).
4. Added Codecov integration just so we can try it out for coverage reporting.
5. Deprecated the use of global variable `window.__base`, enabled asar, and fixed paths. See notes below

## File Paths
With this update we now have several forms of file paths. We no longer need to keep global variables for the application path. Just follow these rules and everything will just work.

1. anything and everything imported with a `require` or equivalent statement should have it's path written according to what is common in node. In other words, nothing special is required. Just enter the relative path and you'll do fine.
2. external files (for example in the user's home directory) must be written as an absolute path. In most cases your absolute path should begin with `path.homedir()`.
3. internal files (files or scripts loaded dynamically from the code base. e.g. `src/assets/projectLicenses/...`) must be written as paths relative to the project root directory and pre-pended with the `__dirname` global object.

There is one exception to all of this. File paths in tests do not need to follow these guidelines since they will obviously not be part of the running application. Instead all file paths in tests should simply use relative file paths.

### Examples
These examples are in order of rules stated above.

1. `import books from '../../../tC_resources/resources/books';`
2. `path.join(path.homedir(), 'translationCore/resources');`
3. `path.join(__dirname, '../../../tC_apps');`

# How to test this Pull Request

1. make sure all the tests pass!
2. Get an up to date coverage report!

## Squash ME!
The commits in this PR are pretty noisy so you should probably squash *and* merge instead of just merging.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2718)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 31 of 2397 files at r1, 6 of 27 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: 32 of 1246 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2718)*

**Comment by klappy** [comment]
@neutrinog So far, so good! Can you update with latest develop branch and convert any of the new tests that were added since you did this?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2718#-:-KuWuGhfcfY5G50nzW8p:b-z5hkwd)*

**Comment by klappy** [comment]
Reviewed 2357 of 2397 files at r1, 18 of 27 files at r2, 1 of 1 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2718)*

**Comment by RoyalSix** [comment]
@neutrinog Could you resolve the merge conlficts

**Comment by da1nerd** [comment]
working on the conflicts now actually :)

**Comment by RoyalSix** [comment]
@neutrinog Nice! reviewing now!

**Comment by da1nerd** [comment]
Don't merge it in quiet yet. I found an issue.

**Comment by da1nerd** [comment]
ok! I've fixed all the things!
I've tested on Linux, macOS, and Windows. We are good to go!

**Comment by da1nerd** [comment]
@klappy does this need to be reviewed again? It would be good to get this merged in soon since it involves so many potential merge conflicts.

**Comment by mannycolon** [comment]
Reviewed 285 of 286 files at r6, 6 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2718)*

**Comment by mannycolon** [comment]
Looks good to go. I was just wondering why is saying `codecov/project — No report found to compare against` Is that because this is the first report?

**Comment by da1nerd** [comment]
Correct.
It gives a fancy coverage diff if the base commit also had a coverage report. e.g. if the develop branch had a coverage report on codecov.

**Pull request merged**
