### PR TITLE
Feature/2528/upgrade language selection

### LINKED ISSUE #3240: Project Import: Missing verses check

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: #2528
Also fixes: https://github.com/unfoldingWord-dev/translationCore/issues/3240

#### How to test this pull request:

Go into Projects, and for one of the project cards, click on menu and select  'Edit Project Details'.
For both Language Name and Language Code: when you start typing letters you should see a drop down menu with partial matches.  If the Language name or Language code does not match an entry in langnames.json, you should see an error.  Once you select a valid value (by either typing an entry and hitting enter, or by selecting from menu), all the language entries will be updated.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3394)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 7 files at r1, 8 of 9 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by richmahn** [comment]
Is there any way to not have the language field say "Language Name is not valid" for the second or so after you select a language from the drop down?   It is a valid language, but I guess because it has the language code with it, it is considered invalid. Kind of misleading and ugly to see.

---

Review status: 3 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-:-L0MHk42cAP9fqsTXmdb:b-w7v1m7)*

**Comment by richmahn** [comment]
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0MIM8kOwWkcgADjy0P:b-5o7stb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
> ```JavaScript
>     const language = LangHelpers.getLanguageByName(languageName);
>     if (!language) {
>       message = "Language Name is not valid";
> ```

This is appearing right after selecting a valid language from the drop down. Anyway to not have it appear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 7 files at r1, 2 of 9 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js, line 61 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PcY2JsopCDft_XpWY:-L0PcY2JsopCDft_XpWZ:b-p5icfg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js#L61)):*
> ```JavaScript
>  */
> export const getErrorMessage = (languageID) => {
>   languageID = languageID || "";
> ```

You don't have to change it but another way to achieve the same thing is by doing ```export const getErrorMessage = (languageID = "") => {```

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 41 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PdMZqXE9m_VvQNbG5:-L0PdMZqXE9m_VvQNbG6:b4m19fg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L41)):*
> ```JavaScript
>           }
>         }
>         // autoFocus={languageName.length === 0}
> ```

If this is a comment, you should comment out jsx with the ```/** */``` method

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0PdnKMLixR8rUx43hP:b-zfdjg9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

This is appearing right after selecting a valid language from the drop down. Anyway to not have it appear?
</blockquote></details>

Yes, it kind of confused me aswell. Maybe use an isSearching flag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js, line 61 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PcY2JsopCDft_XpWY:-L0Q2YHy_1GmX2jALONJ:b-orumjy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js#L61)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

You don't have to change it but another way to achieve the same thing is by doing ```export const getErrorMessage = (languageID = "") => {```
</blockquote></details>

Good point

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 41 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PdMZqXE9m_VvQNbG5:-L0Q2dOGIZPgAsTfRGRm:blz9v67) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L41)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

If this is a comment, you should comment out jsx with the ```/** */``` method
</blockquote></details>

really ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
@PhotoNomad0 I tested this branch and it looks really good. Great Job!! 

However, I found a few user experience issues:

- I typed french and a bunch of languages show in the drop-down menu but there's so many and I cant scroll down to find the one I'm looking for.
- Longer language names are truncated in the drop-down menu.

**Comment by mannycolon** [comment]
@PhotoNomad0 
Another problem, when importing this project [fr_eph_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1563448/fr_eph_text_reg.usfm.zip) after filling out the language name and id and clicking continue it goes to the next step (Missing verses) and the continue button is disable not allowing me to continue with the import process.

**Comment by PhotoNomad0** [comment]
Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 41 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PdMZqXE9m_VvQNbG5:-L0UO7AcXfSBqruUz0zv:bcn8gyw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L41)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

really ?
</blockquote></details>

sorry, leftovers from old code

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0UOLE_k2I7efIqoeQ2:b-pmncjx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes, it kind of confused me aswell. Maybe use an isSearching flag
</blockquote></details>

Found a solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
@PhotoNomad0 It looks a lot better now. However, I'm still experiencing issues with scrolling all the way down. I cant see the items on the very bottom as shown in the pictures below.

- The language name dropdown doesn't show the items on the bottom no matter the size of the window.

- The Language Code drop-down works better than the language name dropdown but if I resize the window it will hide the items in the bottom.

screen shot 2017-12-16 at 1 03 44 pm
screen shot 2017-12-16 at 1 03 06 pm

**Comment by mannycolon** [comment]
@PhotoNomad0 I can confirm the disabled `Continue` button bug is fixed.

**Comment by PhotoNomad0** [comment]
Think I have this fixed now.

---

Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-:-L0eBm87opjUFrJEJv58:bc3grq0)*

**Comment by PhotoNomad0** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js, line 61 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PcY2JsopCDft_XpWY:-L0eBtuzc_HyMJZCjId6:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageIdTextBox.js#L61)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Good point
</blockquote></details>

Done.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 41 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0PdMZqXE9m_VvQNbG5:-L0eBwAgD9TI3l6ZRqKw:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L41)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

sorry, leftovers from old code
</blockquote></details>

Done.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0eBy0It6v5hxJq3Eua:b-ok73s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Found a solution.
</blockquote></details>

There is still a delay clearing this.  Still don't have any solution for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by PhotoNomad0** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0eD6PrHy-t7VpjD7Ok:bow4jto) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

There is still a delay clearing this.  Still don't have any solution for this.
</blockquote></details>

Related to the time it takes to search list of 10000 languages for match on error message. Will try another index.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 2 of 9 files at r2, 7 of 7 files at r4, 1 of 7 files at r5, 5 of 6 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-:-L0f-hymBS1FPt8yx6-E:bnfp4nl)*

**Comment by richmahn** [comment]
*[src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js, line 68 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-L0MIM8kOwWkcgADjy0O:-L0f-nZ5mCRrytyZvxbI:b-ld63rc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/633467a65cb57999f5a016d3464b231921ed570a/src/js/components/projectValidation/ProjectInformationCheck/LanguageNameTextBox.js#L68)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Related to the time it takes to search list of 10000 languages for match on error message. Will try another index.
</blockquote></details>

I didn't see this happening any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r1, 2 of 9 files at r2, 1 of 7 files at r5, 5 of 6 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394#-:-L0fHY_hK8Ih8_JqTZ_M:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3394)*

**Pull request merged**
