### PR TITLE
Garhwali Support

### PR DESCRIPTION
**Pull request by ihoegen**
This brings in support for .sfm files and the importation of Garhwali.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/227)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/227)_

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/227#-:-KUNydhj0GMUE0GEaXzb:bnfp4nl)_

**Comment by mannycolon** [comment]
@ihoegen so when I load an .usfm file project it doesnt allow me to select a tool it keeps opening the load a project modal

**Comment by ihoegen** [comment]
@mannycolon Did you run npm install first? That was the cause of most of the issues

**Comment by mannycolon** [comment]
@ihoegen I did. however, there's a bug that was fixed on @RoyalSix PR that I just approved. i would suggest you merge develop into this branch so I can test it properly.

**Comment by mannycolon** [comment]
@ihoegen still getting this error @RoyalSix's feature should've fixed this. idk why its still happeing.
screen shot 2016-10-20 at 9 43 57 pm

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/227)_

**Comment by mannycolon** [comment]
@ihoegen so this are the two errors I'm getting in your branch. 
I fixed the bug with the `language_id`. you just need to download the tpane again (update)

`Warning: flattenChildren(...): Encountered two children with the same key,`1:$NaN`. Child keys must be unique; when two children share a key, only the first child will be used. requirements.js:20`

`Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. invariant.js:39`

**Comment by ihoegen** [comment]
@mannycolon I think I've fixed it, it was another issue with T-Pane but I've resolved it

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/Usfm/ImportUSFM.js, line 52 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/227#-KUqxcOkSREoEZ1Y_Wb-:-KUqxcOkSREoEZ1Y_Wb0:b-7ye6w0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/aebee53b70be73fd14eae94b15a806dd5a82414e/src/js/components/core/Usfm/ImportUSFM.js#L52)):_

> ``` JavaScript
>       var targetLanguage = {};
>       targetLanguage.title = parsedUSFM.book;
>       // targetLanguage.header = parsedUSFM.headers;
> ```

I'm guessing we will not need the commented code??

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/227)_

**Comment by mannycolon** [comment]
@ihoegen Tested branch multiple times with multiple .usfm files and everything worked perfectly

**Pull request merged**
