### PR TITLE
Fixed Non-working build on Mac 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Fixed Non-working build on Mac 

#### How to test this pull request:

- Run `npm run release-osx`
- After the mac build is done then open `translationCore/release/macos-x64/translationCore-macos-x64-0.8.1-alpha.14.dmg` to install the build
- The app should open with no problems

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3692)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by PhotoNomad0** [comment]
Built and tested both windows 64 and osx build.  Both seem to work fine.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692#-:-L3t7hEYxpf9FPzQN-iZ:bj3vef5)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692#-:-L3t7uJqBWnFuKf7NSrb:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[package.json, line 110 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692#-L40JCVDdgb40AUrlam1:-L40JCVDdgb40AUrlam2:b-377zo2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/62ff4d85a8472d59e0a2558401e2e4e202ed87d4/package.json#L110)):*
> ```JSON
>     "path-extra": "3.0.0",
>     "prop-types": "15.6.0",
>     "react": "^16.2.0",
> ```

reason for carrot?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by RoyalSix** [comment]
@mannycolon Does this upload the mac build to [http://tc-sandbox.unfoldingword.surge.sh/](url) like normal?

**Comment by richmahn** [comment]
@RoyalSix Doesn't the branch have to have a prefix of `sandbox-` for that to happen? Maybe would have been a good candidate for that, but I assume only one sandbox build can exist at a time?

**Comment by mannycolon** [comment]
Review status: 35 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 110 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692#-L40JCVDdgb40AUrlam1:-L41wFEjdHG3g6aF9a87:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/62ff4d85a8472d59e0a2558401e2e4e202ed87d4/package.json#L110)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

reason for carrot?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by mannycolon** [comment]
@RoyalSix No, sorry it doesn't upload to http://tc-sandbox.unfoldingword.surge.sh/

**Comment by RoyalSix** [comment]
I'm getting an error 
screen shot 2018-01-29 at 9 50 12 am

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by klappy** [comment]
Reviewed 1 of 36 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by da1nerd** [comment]
I've confirmed the app now runs correctly on El Capitan.

**Comment by klappy** [comment]
Reviewed 33 of 36 files at r1, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3692#-:-L43e-dlq8cgG1_DTJXa:bnfp4nl)*

**Pull request merged**
