### PR TITLE
ProjectCardMenu

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Added menu on projectCard with functioning upload and export to CSV.

#### How to test this pull request:

Navigate to Project Management in Home Screen and test menu functions.
- Export to CSV
- Upload to D43

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2051)

### CODE REVIEW

**Comment by mannycolon** [comment]
Project Cards overflow at the bottom


screen shot 2017-07-05 at 12 19 47 pm

**Comment by mannycolon** [comment]
Maybe add `cursor: pointer;` to the buttons in the popover

screen shot 2017-07-05 at 12 21 34 pm

**Comment by mannycolon** [comment]
@klappy could you also merge with develop

**Comment by klappy** [comment]
@mannycolon: Scroll was added, cursor was updated, and select button is now disabled when it is selected.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2051#-:-KoJ_d-Q6KcKQinOksqF:b-zfqnmy)*

**Pull request merged**
