### PR TITLE
Fixed bug with wrong values for the selections field in the context id 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Should be able to Import this project and load it in tW (https://git.door43.org/qa99/en_prct_tit_book)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/helpers/ProjectAPI.js, line 111 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986#-LccHbALEO7_Wep1YC-V:-LccHbALEO7_Wep1YC-W:b-42igit) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1b7e763de4639c9d4ad15a7a8ff897554599930a/src/js/helpers/ProjectAPI.js#L111)):*
> ```JavaScript
>               );
> 
>               const { selections } = loadCheckData(loadPath, groupDataItem.contextId);
> ```

Probably best to add check if loadCheckData returns null and set selections to false.

**Review by mannycolon — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/helpers/ProjectAPI.js, line 111 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986#-LccHbALEO7_Wep1YC-V:-LccO1Mo6TDOth2mm6UR:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1b7e763de4639c9d4ad15a7a8ff897554599930a/src/js/helpers/ProjectAPI.js#L111)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Probably best to add check if loadCheckData returns null and set selections to false.
</blockquote></details>

Done.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: all files reviewed, 2 unresolved discussions (waiting on @mannycolon and @PhotoNomad0)

___
*[src/js/helpers/ProjectAPI.js, line 112 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986#-Lccs5hp4DyUixrpnNj2:-Lccs5hp4DyUixrpnNj3:b-kxzzqi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/45478876d829ec191c7e4984524ad14f06f74c1b/src/js/helpers/ProjectAPI.js#L112)):*
> ```JavaScript
> 
>               const { selections } = loadCheckData(loadPath, groupDataItem.contextId);
>               groupDataItem.selections = selections || false;
> ```

Still think this would throw an exception if loadCheckData returns null.

 const checkData  = loadCheckData(loadPath, groupDataItem.contextId);
 groupDataItem.selections = checkData ? checkData.selections : false;

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: all files reviewed, 2 unresolved discussions (waiting on @mannycolon and @PhotoNomad0)

___
*[src/js/helpers/ProjectAPI.js, line 112 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986#-Lccs5hp4DyUixrpnNj2:-Lccsylw5ZHFgXk59--f:bdh153g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/45478876d829ec191c7e4984524ad14f06f74c1b/src/js/helpers/ProjectAPI.js#L112)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Still think this would throw an exception if loadCheckData returns null.

 const checkData  = loadCheckData(loadPath, groupDataItem.contextId);
 groupDataItem.selections = checkData ? checkData.selections : false;

</blockquote></details>

Maybe needs to be more like this ^^^^

**Review by PhotoNomad0 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5986)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
