### PR TITLE
Normal projects are copied to working directory

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/747)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/747)*

**Comment by mannycolon** [comment]
what does this PR address??
it's not clear what i should test 
@ihoegen

**Comment by mannycolon** [comment]
some instructions on how to test this branch would be very helpful

**Comment by ihoegen** [comment]
@mannycolon Copy a project from the projects folder to another location on your computer. Remove that project from the projects folder. Open the project from the new location. Delete the project from the new location. Try to open the project from the projects folder

**Comment by ihoegen** [comment]
What this does is when you open a project, it copies it to the translationCore directory. It does all data saving in there, and does not touch the original load location. This is useful for users on thumbdrives

**Pull request merged**
