### PR TITLE
Feature - #3858 - GL Selection Action/Reducer

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This PR is to be checked along with the corresponding PR in translationWords repo

- This PR addresses each project and each tool having its own selected Gateway Language, where the selector on the tool card will save itself to the card's state as well as to the projectDetailsReducer. This allows the tool to have access to its gateway language to show content for that GL, such as tW article headers and content.

#### Please include detailed Test instructions for your pull request:
- [ ] Checkout the corresponding branch name, feature-richmahn-3858, in the translationCore repo, the translationWords repo, and the tC_resources repo (the tC_ressources repo branch was made for testing, not as a PR, just to have Hindi tW content)
- [ ] Delete the ~/translationCore/resources/hi directory if exists
- [ ] Run `npm i` in the root directory of your trancationCore repo. 
- [ ] Run the app and go to a project's tool page. You should be able to pick between English and Hindi in each tool's GL selection. 
- [ ] Select English (already selected) for tW and go into the tool. All should be in English. 
- [ ] Go back to the tool card page and select Hindi for tW, go into the tool, it should now show text in Hindi on the left (tW group indexes), in the blue check card into in the middle (tW group index and the first paragraph of the group article), and in the article on the right.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3910)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by PhotoNomad0** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6He_YwYOTsQ4ure25o:bnvnkcf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
> ```JavaScript
> import Enzyme from 'enzyme';
> ```

Confused here, since this is being added by package.json, this should not be checked into git (.gitignore).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6HfYLAbd8O_hruyCZE:b-rie5xp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Confused here, since this is being added by package.json, this should not be checked into git (.gitignore).
</blockquote></details>

Will check...I was just trying to make it like translationWords which has the same thing in its package.json file and a testSetUp/ dir, added by @royalsix on January 12. I was using testing techniques like used in translationWords.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6HggSNOPXDzAbwcBzV:b4faeds) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Will check...I was just trying to make it like translationWords which has the same thing in its package.json file and a testSetUp/ dir, added by @royalsix on January 12. I was using testing techniques like used in translationWords.
</blockquote></details>

Sorry my mistake here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by PhotoNomad0** [comment]
In testing I get error:

ResourcesHelpers.js [sm]:49 Error: ENOENT: no such file or directory, scandir ‘/Users/blm/Development/Electron/testDir/translationCore/tC_resources/resources/hi/translationHelps

What do I do to setup up tc_resources?

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-:-L6Hq1q5SXFd2R4brxhr:bnfp4nl)*

**Comment by richmahn** [comment]
Updated testing procedure to include deleting ~/transationCore/resources/hi to make sure it copies in a new hi resource dir when you start up the app.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-:-L6ID50JZPkscBjM_PGV:bnfp4nl)*

**Comment by klappy** [comment]
*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6IhlENCXljVVrbsooN:-L6IhlENCXljVVrbsooO:b-wwupcw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/package.json#L4)):*
> ```JSON
>   "name": "translationCore",
>   "productName": "translationCore",
>   "version": "0.8.1-alpha.17",
> ```

@richmahn: Since you are updating the tC_resources submodule, you'll need to increment the alpha version to 18 so that starting the app can automatically update the user's resouces path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by mannycolon** [comment]
@rich that is not needed. by changing the tC repo version number  there is a migration that does it for you (edited)

**Review by mannycolon — CHANGES_REQUESTED** [review]
@rich that is not needed. by changing the tC repo version number  there is a migration that does it for you (edited)

**Comment by mannycolon** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/LanguageHelpers.test.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6IiPkcIhxAPacrTqeZ:-L6IiPkcIhxAPacrTqe_:bc11v3r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/__tests__/LanguageHelpers.test.js#L57)):*
> ```JavaScript
>     }
>   });
> ```

can we be more specific about whats happening here

---

*[src/js/helpers/LanguageHelpers.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6Iivrr-nxa_BbzlkW8:-L6Iivrr-nxa_BbzlkW9:b-d7ital) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/src/js/helpers/LanguageHelpers.js#L11)):*
> ```JavaScript
> 
> export const DEFAULT_GATEWAY_LANGUAGE = 'en';
> export const gatewayLanguages = [{lc: 'en', name: 'English'}, {lc: 'hi', name: 'Hindi'}];
> ```

shouldn't this be more dynamic?

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6IjBA-ZI0UNNwTC9ZR:b-yrb4l6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Sorry my mistake here.
</blockquote></details>

did you verify if this file is really needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by richmahn** [comment]
Review status: 18 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/LanguageHelpers.test.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6IiPkcIhxAPacrTqeZ:-L6Itd0931VR9sOtdEcb:buib5f5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/__tests__/LanguageHelpers.test.js#L57)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we be more specific about whats happening here
</blockquote></details>

Honestly this isn't really needed any more as this something that Spidel added to make sure someone a) picked a GL and b) could only use English (text when Launch button is disabled). Yet now you can go into Hindi and defaults to English. Anyway, will improve the test description

---

*[src/js/helpers/LanguageHelpers.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6Iivrr-nxa_BbzlkW8:-L6IsxgQuvRLzjNCH1tH:b-1hx9zz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/src/js/helpers/LanguageHelpers.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

shouldn't this be more dynamic?
</blockquote></details>

I believe doing this is another story, to determine what GL's are fully available from the resource directory. Currently how we have it, "grc" Greek would get considered as a GL, but it isn't. @klappy Do you know what story handles this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by richmahn** [comment]
Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6IuU6df4wDzc9dkPIJ:b2j48) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

did you verify if this file is really needed?
</blockquote></details>

Yes, enzyme requires this for the shallow() function in the ToolCard.test.js test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by richmahn** [comment]
Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6IuyJxLsMhGrM8UXKv:btks57k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Yes, enzyme requires this for the shallow() function in the ToolCard.test.js test.
</blockquote></details>

If it doesn't exist you get an error message like this:

```$ jest ToolCard
FAIL __tests__\ToolCard.test.js
  ● Test ToolCard component › Test GL Selection Change


          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by klappy** [comment]
*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6IhlENCXljVVrbsooN:-L6JEGOorPpg-5D-E-E4:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/package.json#L4)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@richmahn: Since you are updating the tC_resources submodule, you'll need to increment the alpha version to 18 so that starting the app can automatically update the user's resouces path.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Comment by klappy** [comment]
*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6JEUqsTP3NOju19hrj:bde383k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

If it doesn't exist you get an error message like this:

```$ jest ToolCard
FAIL __tests__\ToolCard.test.js
  ● Test ToolCard component › Test GL Selection Change


          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html```
</blockquote></details>

Is this discussion resolved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*
<!-- Sent from Reviewable.io -->

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[testSetUp/enzyme.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910#-L6He_YwYOTsQ4ure25n:-L6JWohGru1JH1h1SQaK:b2nign6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9ecde0bb736f545db68b786e01050d2a6963b0ef/testSetUp/enzyme.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is this discussion resolved?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3910)*

**Pull request merged**
