### PR TITLE
Separates the groups data loading into two separate steps.

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4884 

Groups data loading has been refactored to
- copy data into the project when the project is selected
- load group data from the project when the tool is selected
- load group index from the global resources when the tool is selected.
- some general cleanup to tests output was also performed to reduce console noise when running tests.
- corrects invalid count not displaying immediately after an import. See https://github.com/unfoldingWord-dev/translationCore/issues/4672

The visible functionality should remain unchanged.

> NOTE: 40% of the changed files in this PR are related to tests.

#### Please include detailed Test instructions for your pull request:
This change affects everything using the groups data or index. A list of items to test are
- selecting a project
- opening a tool
- navigating with the groups menu
- importing a project (online and locally)
- exporting a project (csv and usfm)
- renaming a project

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5636)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e5e4bcf)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-e5e4bcf.deb) is ready for download.
[macOS build 1.1.0 (e5e4bcf)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-e5e4bcf.dmg) is ready for download.
[Windows x64 build 1.1.0 (e5e4bcf)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-e5e4bcf.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e5e4bcf)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-e5e4bcf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cda3c6e)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-cda3c6e.deb) is ready for download.
[macOS build 1.1.0 (cda3c6e)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-cda3c6e.dmg) is ready for download.
[Windows x64 build 1.1.0 (cda3c6e)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-cda3c6e.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cda3c6e)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-cda3c6e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8d93af4)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-8d93af4.deb) is ready for download.
[macOS build 1.1.0 (8d93af4)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-8d93af4.dmg) is ready for download.
[Windows x64 build 1.1.0 (8d93af4)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-8d93af4.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8d93af4)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-8d93af4.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
[en_zzzx_gal_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2725437/en_zzzx_gal_book.zip)

Failed on export.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (54e3d3d)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-54e3d3d.deb) is ready for download.
[macOS build 1.1.0 (54e3d3d)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-54e3d3d.dmg) is ready for download.
[Windows x64 build 1.1.0 (54e3d3d)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-54e3d3d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (54e3d3d)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-54e3d3d.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@neutrinog - Seeing problem with opening project.  If the project name did not match spec, I do not see the renamed prompt at end.  This works fine in develop.

[es-419_tit_no_git.zip](https://github.com/unfoldingWord-dev/translationCore/files/2726822/es-419_tit_no_git.zip)

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 4 of 40 files at r1, 1 of 10 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5636)* status: 6 of 48 files reviewed, all discussions resolved (waiting on @neutrinog)

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 14 of 40 files at r1, 3 of 10 files at r2, 1 of 2 files at r3, 2 of 4 files at r4, 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5636)* status: 28 of 48 files reviewed, all discussions resolved (waiting on @neutrinog)

**Review by RoyalSix — DISMISSED** [review]
> Reviewed 13 of 40 files at r1, 4 of 10 files at r2, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5636)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
@neutrinog  - also notice that in your PR we no longer get the message that tools have not been loaded when you try to do an immediate export to CSV.

**Comment by da1nerd** [comment]
Fixed the bug with the renamed prompt. I neglected to fetch the updated project path after the project validation occurs which threw an error and killed the dialog.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b931ff1)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-b931ff1.deb) is ready for download.
[macOS build 1.1.0 (b931ff1)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-b931ff1.dmg) is ready for download.
[Windows x64 build 1.1.0 (b931ff1)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-b931ff1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b931ff1)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-b931ff1.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@neutrinog - seeing issue when I import a modified USFM file and select overwrite, it removes all the alignments. 

using project https://git.door43.org/lrsallee/en_ult_tit_book and then overwriting with mods
[en_ult_tit_book.2.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2728485/en_ult_tit_book.2.usfm.zip)

Only expect to see changes in verse 1 and 4 (see that in develop branch).

**Comment by da1nerd** [comment]
@PhotoNomad0 for the exporting it appears I accidentally added support for exporting a project before a tool has been opened.
Cheers.

**Comment by da1nerd** [comment]
I also noticed the usfm and especially the csv export is using a lot of duplicate code compared to how projects are now loaded. A lot of that can be cleaned up so we aren't maintaining logic in three different places. I'm inclined to wait on that since it's not required for this PR.

**Comment by da1nerd** [comment]
@PhotoNomad0 I tested importing the usfm file above and it correctly kept the alignments except for verses 1 and 4. Did you test that before or after my commit https://github.com/unfoldingWord-dev/translationCore/pull/5636/commits/b931ff197e64c0cb1ed980e56f2819704565958e?

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (a3f4d30)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-linux-x64-1.1.0-a3f4d30.deb) is ready for download.
[macOS build 1.1.0 (a3f4d30)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-macos-x64-1.1.0-a3f4d30.dmg) is ready for download.
[Windows x64 build 1.1.0 (a3f4d30)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x64-1.1.0-a3f4d30.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (a3f4d30)](https://tc-builds.door43.org/build/enhancement_joel_4884_load-project-data/translationCore-win-x32-1.1.0-a3f4d30.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5636)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Pull request merged**
