### PR TITLE
Project Information Check 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Added `Project Information Check`  to `Project Validation Stepper`

##### Test multiple use cases such as:
- Project manifest is missing  `project.id` or `project: { id: "" }`
- Project manifest is missing `project.name` or `project: { name: "" }`
- Project manifest is missing `target_language.id` or `target_language: { id: "" }`
- Project manifest is missing `target_language.name` or `target_language: { name: "" }`
- Project manifest is missing `checkers: []`

##### Note: 
- As you update the fields and click save, it should save in the project manifest file.
- In the project information step, it should not go to the next step unless all the required fields are completed.

Sample project to test with: [ar_mat_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1235955/ar_mat_text_ulb.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2489)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2489)*

**Comment by klappy** [comment]
After I complete the form, there seems to be an issue where it doesn't take me to the Tools page, it takes me to the project page again, and it doesn't show the project as selected but it does show me that I can go to tools. Navigating away and back shows that its selected.

**Comment by klappy** [comment]
Is it just me or does this look like I'm on the wrong step? The copyright check looked like I was on the  Project Information Check as well.
screen shot 2017-08-18 at 8 48 26 pm

**Comment by klappy** [comment]
It's looking really good. I think it needs a little more refinement to the layout to look more structured. I know we don't have a mockup to accommodate for the new fields you added, so maybe we move forward with what we have until there is more direction from @benjore and @cckozie.

screen shot 2017-08-18 at 8 59 15 pm

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2489)*

**Comment by mannycolon** [comment]
@RoyalSix 

```
Try opening a fresh project.
When the copyright check comes up select anything
Then click cancel
Then try selecting any project
The selection check box should be reset at that point but its not
- Jay
```

**Comment by mannycolon** [comment]
Fixed and addressed all issues from PR review. @klappy @RoyalSix

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2489)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2489#-:-Ks0prV_3DxV0_8HV1gT:bnfp4nl)*

**Pull request merged**
