### PR TITLE
Added Export To CSV Feature

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR allows a user to see the checking data, comments, selections, verse edits, and reminders in csv form.

#### How to test this pull request:
To test try exporting on various projects and seeing if there is data in {projectPath}/apps/{toolName}/output

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1359)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix i have some concerns that you're duplicating actions that were previously created.

**Comment by cdwhitfield73** [comment]
@RoyalSix Manny is right.  It would be best if you waited for my PR to be merged and then use it to wire up your export function to the button that I already created when I re-did the entire modal layout.

**Comment by mannycolon** [comment]
@RoyalSix I was referring to loadGroupData and loadGroupIndex (actions)

**Comment by RoyalSix** [comment]
@mannycolon The functions I created has a different purpose and different functionality. I did try and just use the same one but it seems better two not make one function so modular that it looses its simplicity in order to combine two functionalities. 
Unless you have a different approach of loading the groupsData.

**Comment by EllDoubleYew** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/utils/loadMethods.js, line 84 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj3tsJgRUfDs7jfLN1I:-Kj3tsJgRUfDs7jfLN1J:b-mdcyla) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/189c3ecf55e1e3e4be0c1487332700835149be44/src/js/utils/loadMethods.js#L84)):*
> ```JavaScript
> }
> 
> export function loadCheckDataData(dataFolder, params, type) {
> ```

This name please lets do anything else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by RoyalSix** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/utils/loadMethods.js, line 84 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj3tsJgRUfDs7jfLN1I:-Kj4lHkZqjugo2JlPxd4:b2nhjic) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/189c3ecf55e1e3e4be0c1487332700835149be44/src/js/utils/loadMethods.js#L84)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

This name please lets do anything else.
</blockquote></details>

Lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by mannycolon** [comment]
please document your code (functions, actions)

---

Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 132 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj8paYlghCkLB3Go90H:-Kj8paYlghCkLB3Go90I:b-9ab6lb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f65eefe1a21093d8ac56a727816990c0b6782d07/src/js/actions/GetDataActions.js#L132)):*
> ```JavaScript
>             //No USFM detected, initiating 'standard' loading process
>             let manifest = setUpManifestAndParams(projectPath, projectLink, currentUser);
>             dispatch(addLoadedProjectToStore(projectPath, manifest));
> ```

just for my information and knowledge. what made you make this changes?

---

*[src/js/actions/RecentProjectsActions.js, line 40 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj8pxDEC7L2PiWWTub7:-Kj8pxDEC7L2PiWWTub8:bu75i30) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f65eefe1a21093d8ac56a727816990c0b6782d07/src/js/actions/RecentProjectsActions.js#L40)):*
> ```JavaScript
>     let manifest = getDataActions.setUpManifestAndParams(projectPath);
>     dispatch(getDataActions.addLoadedProjectToStore(projectPath, manifest));
>     const params = getState().projectDetailsReducer.params;
> ```

I think you could do `projectDetailsReducer.params;` instead since you already imported it above.

---

*[src/js/utils/loadMethods.js, line 49 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj8qZSLnHu7YiQThucJ:-Kj8qZSMfcvBqZkWx23R:bkzn4iy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f65eefe1a21093d8ac56a727816990c0b6782d07/src/js/utils/loadMethods.js#L49)):*
> ```JavaScript
> }
> 
> export function loadGroupsData(tool, dataFolder, params) {
> ```

would it be possible to rename this function since there is another function with the same name. maybe loadGroupsDataToExport idk something like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-:-Kj8qwxKB0kilI0T_xEb:b-4nl777)*

**Comment by mannycolon** [comment]
@RoyalSix when you get a chance please address the comments and merge conflicts and then this PR should be good to go.

**Comment by RoyalSix** [comment]
@mannycolon done.

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tC_apps/TranslationHelps, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJMM0WWoitonnMGjmn:-KjJMM0WWoitonnMGjmo:bb541kl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c5bc069eab66327508bdc54a87928f4045eb024/tC_apps/TranslationHelps#L1)):*
> ```
> Subproject commit d9ada6beb242de410d2cc47046f653f3bf939aef
> ```

do we want this commit ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by RoyalSix** [comment]
Review status: 5 of 53 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/actions/GetDataActions.js, line 132 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj8paYlghCkLB3Go90H:-KjJPOWaB6uGXj69Ea3M:bhwahhy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f65eefe1a21093d8ac56a727816990c0b6782d07/src/js/actions/GetDataActions.js#L132)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

just for my information and knowledge. what made you make this changes?
</blockquote></details>

Yea, I'm using it in my exportToCSV function in RecentProjectActions because there was no other way to get a manifest and params in the store without going through the entire load process

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by mannycolon** [comment]
Reviewed 2 of 51 files at r5.
Review status: 5 of 53 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/css/BodyContainer.css, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJQcuAp1GNu6jfuzzD:-KjJQcuAp1GNu6jfuzzE:bjve60) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/608fb1983e924110c334277d47c4da1178086af5/src/css/BodyContainer.css#L1)):*
> ```CSS
>   #scrollableSection {
> ```

why did you deleted this file??

---

*[src/css/styles.css, line 3 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJQg_auUQ5bqKiKfxE:-KjJQg_auUQ5bqKiKfxF:b-6ybzv4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/608fb1983e924110c334277d47c4da1178086af5/src/css/styles.css#L3)):*
> ```CSS
> 
> @import 'colorscheme.css';
> @import 'BodyContainer.css';
> ```

why are you removing this file from here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by mannycolon** [comment]
Reviewed 3 of 51 files at r5, 3 of 50 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by mannycolon** [comment]
@RoyalSix let me know when this PR is ready to be reviewed again.

**Comment by RoyalSix** [comment]
Reviewed 1 of 10 files at r7.
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/js/utils/loadMethods.js, line 49 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-Kj8qZSLnHu7YiQThucJ:-KjLi0BLK0DRzS9vSQ81:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f65eefe1a21093d8ac56a727816990c0b6782d07/src/js/utils/loadMethods.js#L49)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

would it be possible to rename this function since there is another function with the same name. maybe loadGroupsDataToExport idk something like that.
</blockquote></details>

Done.

---

*[src/css/BodyContainer.css, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJQcuAp1GNu6jfuzzD:-KjLpbdS9WOUf-VaLoBF:b-703gx5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/608fb1983e924110c334277d47c4da1178086af5/src/css/BodyContainer.css#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you deleted this file??
</blockquote></details>

check the commit on github, this is outdated

---

*[src/css/styles.css, line 3 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJQg_auUQ5bqKiKfxE:-KjLpflKPd5yjr45Ypty:b-fshhnv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/608fb1983e924110c334277d47c4da1178086af5/src/css/styles.css#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you removing this file from here?
</blockquote></details>

check the commit on github this is outdated

---

*[tC_apps/TranslationHelps, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359#-KjJMM0WWoitonnMGjmn:-KjLpiOI7Qh5z51OpvmG:b-fshhnv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c5bc069eab66327508bdc54a87928f4045eb024/tC_apps/TranslationHelps#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we want this commit ??
</blockquote></details>

check the commit on github this is outdated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1359)*

**Comment by RoyalSix** [comment]
@mannycolon This PR should be ready

**Pull request closed without merging**
