### PR TITLE
Should fix issues with local tests failling

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/426)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/426)*

**Comment by RoyalSix** [comment]
Merge with develop and its good

**Comment by ihoegen** [comment]
@RoyalSix Done

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/426)*

**Pull request merged**
