### PR TITLE
Sandbox feature usfm3

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Lots of USFM changes from importing to exporting to alignment data, and usage in tools.

#### How to test this pull request:

Requires checking out branches from `translationCore`, `ScripturePane` and `WordAlignmentTool`.
Test the entire app make sure all works as intended.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3764)

### CODE REVIEW

**Comment by klappy** [comment]
Addressing merge conflicts now.

**Comment by PhotoNomad0** [comment]
Review status: 0 of 70 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3764#-L4zYJ2nSmPPMa4hYt_Z:-L4zYJ2ov2FNK7fOiv-d:b3nyyeb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3070ff6c5f1cccabe83b7b9bbceb9da32dd7af74/package.json#L4)):*
> ```JSON
>   "name": "translationCore",
>   "productName": "translationCore",
>   "version": "0.8.1-alpha.15",
> ```

Should we bump the product version here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3764)*

**Comment by PhotoNomad0** [comment]
Reviewed 45 of 70 files at r1.
Review status: 45 of 70 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3764)*

**Comment by PhotoNomad0** [comment]
Reviewed 25 of 70 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3764)*

**Comment by PhotoNomad0** [comment]
Seeing this strange warning.  Not sure what the issue is, but I have seen it before.

```
/Users/blm/Development/Electron/translationCore/node_modules/fbjs/lib/warning.js:33 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
    in WordBankArea
    in DropTarget(WordBankArea)
    in div
    in Container
    in DragDropContext(Container) (created by ToolsContainer)
    in ToolsContainer (created by Connect(ToolsContainer))
    in Connect(ToolsContainer) (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in div (created by BodyContainer)
    in BodyContainer (created by Connect(BodyContainer))
    in Connect(BodyContainer) (created by Main)
    in div (created by Grid)
    in Grid (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
```

**Comment by PhotoNomad0** [comment]
@klappy - I do see a bug that if in WA you change to new verse, the Lexicon entries are not populated on the words new to the next verse, but if you exit and reopen WA it opens to that verse and all words have lexicon entries.  Looks like a bug in SP that Verse. componentWillReceiveProps() is checking for an array in verseText and ignoring verseObjects.

Suggest fixing this in a separate PR.  

Let's merge this one first.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3764#-:-L4zeWLgMhCXDLxqmcpo:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
@klappy - Have PR for missing Lexicon entries on verse change:
https://github.com/translationCoreApps/ScripturePane/pull/89

Your call if you want to merge in before or after this PR.

**Pull request merged**
