### PR TITLE
USFM3 Export

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Ability to export alignment data from tC WordAlignment tool

#### How to test this pull request:
Make sure you have the latest usfm-js branch: ```1.0.0-beta.21``` (at the moment)
If you don't just run ```npm i```
Start the app
Make sure you have a working project in my projects.
You can try a project with or without alignments.
On the projects screen click on the three dot button for project you want to export.
Click on ```Export Alignments``` option.
Once finished you should see an alert saying it saved.
Open it and ensure the metadata for the alignments matches the alignments you actually made on the app.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3747)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
In testing, I see that it exports the file as alignments.usfm, but the prompt says it's en_1j.usfm.

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 199 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0WmCyNKnAV43R37G:-L4h0WmCyNKnAV43R37H:bzfk1s6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/46b2adee3d3acc76793c8f6a4bbc5b1303775af1/src/js/helpers/WordAlignmentHelpers.js#L199)):*
> ```JavaScript
>     }
>     let usfmToJSONObject = { chapters: {} };
>     for (var chapterFile of chapters) {
> ```

shouldn't these be left as 'let'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 115 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0wZWZ_BS1Oh33iH2:-L4h0wZWZ_BS1Oh33iH3:b-xdsxjl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0fa4b5c8bf4e5108435f5e2216f3e64bb4cdf312/src/js/helpers/WordAlignmentHelpers.js#L115)):*
> ```JavaScript
> 
> /**
>  * @description - Method to fetch a target language chapter JSON and source/target language
> ```

Are we now not using @description?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by RoyalSix** [comment]
@PhotoNomad0 It shouldn't be saving as ```alignments.usfm``` unless you've previously set that yourself. Can you make sure you're up to date on the branch.

**Comment by RoyalSix** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 115 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0wZWZ_BS1Oh33iH2:-L4h4BifRJPqBse0KA-5:b-l9h2ep) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0fa4b5c8bf4e5108435f5e2216f3e64bb4cdf312/src/js/helpers/WordAlignmentHelpers.js#L115)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Are we now not using @description?
</blockquote></details>

Its not required. I see it used on and off in the code. http://usejsdoc.org/tags-description.html We should probably pick one as a team. My vote would be not to have it.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 199 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0WmCyNKnAV43R37G:-L4h5DXrAPgBGOiz3SE5:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/46b2adee3d3acc76793c8f6a4bbc5b1303775af1/src/js/helpers/WordAlignmentHelpers.js#L199)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

shouldn't these be left as 'let'?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
*[src/js/helpers/WordAlignmentHelpers.js, line 115 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0wZWZ_BS1Oh33iH2:-L4hSqS6dBV9emasSMdR:bm7diwj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0fa4b5c8bf4e5108435f5e2216f3e64bb4cdf312/src/js/helpers/WordAlignmentHelpers.js#L115)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Its not required. I see it used on and off in the code. http://usejsdoc.org/tags-description.html We should probably pick one as a team. My vote would be not to have it.
</blockquote></details>

I'm used to seeing it but realize it's more work to type it out and it just takes up space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by mannycolon** [comment]
Reviewed 3 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by mannycolon** [comment]
@RoyalSix Please resolve merge conflicts

**Comment by RoyalSix** [comment]
@mannycolon Done.

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
I'm getting the same as above with alignments.usfm and I haven't manually set that either. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4kxSsu6nMrSas3e9yW:b6fn9ap)*

**Comment by PhotoNomad0** [comment]
OK, now getting prompt where to save and out is being saved there.

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4l1mGs0yz38DzFt3HR:b-hxxdq1)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4l2ONiRQC_hN0OQMco:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 106 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4l8meTNVGOCHLxTwCR:-L4l8meTNVGOCHLxTwCS:b-z7zxkb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d66e9a74641af351953dfb482e539241d9faf965/src/js/helpers/WordAlignmentHelpers.js#L106)):*
> ```JavaScript
>     projectTargetLanguagePath = path.join(projectSaveLocation, project.id);
>     if (fs.existsSync(wordAlignmentDataPath) && fs.existsSync(projectTargetLanguagePath)) {
>       chapters = fs.readdirSync(wordAlignmentDataPath);
> ```

Need to filter out '.DS_Store'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
Reviewed 2 of 7 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 196 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4lCOfGp8vLdxY97Kg3:-L4lCOfGp8vLdxY97Kg4:b-s9462u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d66e9a74641af351953dfb482e539241d9faf965/src/js/helpers/WordAlignmentHelpers.js#L196)):*
> ```JavaScript
>       const chapterNumber = path.parse(chapterFile).name;
>       const { chapterAlignmentJSON, targetLanguageChapterJSON } = getAlignmentDataFromPath(wordAlignmentDataPath, projectTargetLanguagePath, chapterFile);
>       for (let verseNumber in chapterAlignmentJSON) {
> ```

Need to filter out 'front'.  This is where the front matter is preserved from USFM import, but not verse data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by RoyalSix** [comment]
@klappy Did you pull the latest?

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 115 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4h0wZWZ_BS1Oh33iH2:-L4lEkJKGbIqHJlhiQuJ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0fa4b5c8bf4e5108435f5e2216f3e64bb4cdf312/src/js/helpers/WordAlignmentHelpers.js#L115)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm used to seeing it but realize it's more work to type it out and it just takes up space.
</blockquote></details>

Done.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 106 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4l8meTNVGOCHLxTwCR:-L4lIcPGvP6THBC3-Nwn:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d66e9a74641af351953dfb482e539241d9faf965/src/js/helpers/WordAlignmentHelpers.js#L106)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to filter out '.DS_Store'
</blockquote></details>

Done.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 196 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4lCOfGp8vLdxY97Kg3:-L4lIcoYQTpN7AU2eSNX:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d66e9a74641af351953dfb482e539241d9faf965/src/js/helpers/WordAlignmentHelpers.js#L196)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to filter out 'front'.  This is where the front matter is preserved from USFM import, but not verse data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4lFE4My8xycvgxVvBN:b3krf)*

**Comment by klappy** [comment]
Let me pull the latest and see if I get the same errors.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4lLj0fNaC6Frm-_MYb:b-f1jb47)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
@royalsix: Looks like the output usfm file doesn't including any headers and the first line is `\c 1`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-:-L4lMjOjd3cfRIX4Xbte:b-ua604n)*

**Comment by PhotoNomad0** [comment]
The app seems to be working well now.  We probably should open a separate issue to preserve the rest of the header information on USFM import.

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r4, 1 of 4 files at r5.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r2, 1 of 4 files at r5.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r5.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 204 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4lmr3tqPShNVuWA78m:-L4lmr3tqPShNVuWA78n:b-4kht5n) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1bfb4f53bf864f16067ccfbdd37993b91395010f/src/js/helpers/WordAlignmentHelpers.js#L204)):*
> ```JavaScript
>       const { chapterAlignmentJSON, targetLanguageChapterJSON } = getAlignmentDataFromPath(wordAlignmentDataPath, projectTargetLanguagePath, chapterFile);
>       for (let verseNumber in chapterAlignmentJSON) {
>         if (!parseInt(verseNumber)) continue; // only import integer based data, there are other files
> ```

Technically these are not files, but keys in the chapter object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3747#-:-L4lq9K89tTm7iwa0YiS:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/WordAlignmentHelpers.js, line 204 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747#-L4lmr3tqPShNVuWA78m:-L4lpTlniAIQyvzTy39O:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1bfb4f53bf864f16067ccfbdd37993b91395010f/src/js/helpers/WordAlignmentHelpers.js#L204)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Technically these are not files, but keys in the chapter object.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3747)*

**Pull request merged**
