### PR TITLE
Fix 3396/delete project on cancel or import error.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Issue: #3396

#### How to test this pull request:

On Import error, project will be deleted.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3419)

### CODE REVIEW

**Comment by mannycolon** [comment]
@PhotoNomad0 We no longer need this PR. it should be already happening after my last PR.

**Comment by mannycolon** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[__tests__/LocalImportWorkflowActions.test.js, line 6 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q665hnQA10LPN57Nh:-L0Q665hnQA10LPN57Ni:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/__tests__/LocalImportWorkflowActions.test.js#L6)):*
> ```JavaScript
> import * as LocalImportWorkflowActions from '../src/js/actions/Import/LocalImportWorkflowActions';
> import path from 'path';
> import * as fs from "fs-extra";
> ```

ibid

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5XgmhPVDgiK1ykoN:-L0Q5XgnUDwDlFLeFk9a:b-yvw8cx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L16)):*
> ```JavaScript
> // helpers
> import * as FileConversionHelpers from '../../helpers/FileConversionHelpers';
> import * as fs from "fs-extra";
> ```

Please don't use * as with fs
import fs from 'fs-extra' instead

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 27 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5eJrJgrtVWdDIhUv:-L0Q5eJrJgrtVWdDIhUw:b-q6cymx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L27)):*
> ```JavaScript
>   </div>
> );
> export const IMPORTS_PATH = path.join(path.homedir(), 'translationCore', 'imports');
> ```

dont think we need to export this variable

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 56 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5iVp0JpqWAS5kON1:-L0Q5iVp0JpqWAS5kON2:brwj7wc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L56)):*
> ```JavaScript
>       dispatch(AlertModalActions.openAlertDialog(error));
>       dispatch(ProjectImportStepperActions.cancelProjectValidationStepper());
>       // remove failed project import
> ```

We should probably move this logic to its own function to ProjectFilesystemActions.js

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 14 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5tlhfVgKNfeusrWQ:-L0Q5tlhfVgKNfeusrWR:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L14)):*
> ```JavaScript
> // helpers
> import * as OnlineImportWorkflowHelpers from '../../helpers/Import/OnlineImportWorkflowHelpers';
> import * as fs from "fs-extra";
> ```

ibid

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5yXaMNOS9_T7uHy2:-L0Q5yXaMNOS9_T7uHy3:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L16)):*
> ```JavaScript
> import * as fs from "fs-extra";
> //consts
> export const IMPORTS_PATH = path.join(path.homedir(), 'translationCore', 'imports');
> ```

ibid

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 47 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q60KEEqdqrkOiNisi:-L0Q60KFtLdMe1u81leb:brwj7wc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L47)):*
> ```JavaScript
>         dispatch({ type: "LOADED_ONLINE_FAILED" });
>         // remove failed project import
>         const link = getState().importOnlineReducer.importLink;
> ```

We should probably move this logic to its own function to ProjectFilesystemActions.js

---

*[tC_apps/ScripturePane, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q61KTPKpXoKHk1pBN:-L0Q61KTPKpXoKHk1pBO:bzfhjea) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit 055516b3116e24760d928ad62365c59f7a6e5d38
> ```

is this the latest commit for scripture pane

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[__tests__/LocalImportWorkflowActions.test.js, line 6 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q665hnQA10LPN57Nh:-L0QHz7FExmMVTDkSbz7:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/__tests__/LocalImportWorkflowActions.test.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Done.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5XgmhPVDgiK1ykoN:-L0QI-D7PEozvgpBxKMP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L16)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Please don't use * as with fs
import fs from 'fs-extra' instead
</blockquote></details>

Done.

---

*[tC_apps/ScripturePane, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q61KTPKpXoKHk1pBN:-L0Q7cPlmBSMQp9A8gn1:b-8ooq60) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this the latest commit for scripture pane
</blockquote></details>

Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419)*

**Comment by PhotoNomad0** [comment]
Still needed

---

Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 27 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5eJrJgrtVWdDIhUv:-L0QTABAuct7Mid4dgwN:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L27)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

dont think we need to export this variable
</blockquote></details>

Done.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 56 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5iVp0JpqWAS5kON1:-L0QTBrdDa3A5wX0VYOZ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/LocalImportWorkflowActions.js#L56)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

We should probably move this logic to its own function to ProjectFilesystemActions.js
</blockquote></details>

Done.

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 14 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5tlhfVgKNfeusrWQ:-L0QTDCIpt2sxhAeD7KM:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L14)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Done.

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 16 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q5yXaMNOS9_T7uHy2:-L0QTDYulTOatX_eJhr0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L16)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

Done.

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 47 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0Q60KEEqdqrkOiNisi:-L0QTEDJDZ4CZ2IyqvNP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4410d5f2ef4305ec19e348bd2bdcaa26b7d4f4f4/src/js/actions/Import/OnlineImportWorkflowActions.js#L47)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

We should probably move this logic to its own function to ProjectFilesystemActions.js
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-:-L0QTO8ku5dt5GKGLZaO:blshpea)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Does this PR handle #3393?

**Comment by mannycolon** [comment]
Reviewed 6 of 7 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[__tests__/OnlineImportWorkflowActions2.test.js, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419#-L0VXbONkPGMGU9Y74_r:-L0VXbONkPGMGU9Y74_s:b-473jul) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bfb419ad88a33c6a2be98fe5779727246d0e1f65/__tests__/OnlineImportWorkflowActions2.test.js#L1)):*
> ```JavaScript
> import configureMockStore from 'redux-mock-store';
> ```

why do we need a second TEST file FOR OnlineImportWorkflowActions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3419)*

**Pull request merged**
