### PR TITLE
Added custom test script for concourse

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- this is a one liner that simply adds an additional test script for use in ci.

#### Please include detailed Test instructions for your pull request:
- nothin'

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4560)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-1030ec7.zip) is ready for download.
[macOS build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-1030ec7.dmg) is ready for download.
[Windows x64 build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-1030ec7.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (1030ec7)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-1030ec7.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4560#-:-LEBHa9X6K8ZR_SsB1lW:bnfp4nl)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (3733b5f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-3733b5f.zip) is ready for download.
[macOS build 0.10.0 (3733b5f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-3733b5f.dmg) is ready for download.
[Windows x64 build 0.10.0 (3733b5f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-3733b5f.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (3733b5f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-3733b5f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (81f4978)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-81f4978.zip) is ready for download.
[macOS build 0.10.0 (81f4978)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-81f4978.dmg) is ready for download.
[Windows x64 build 0.10.0 (81f4978)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-81f4978.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (81f4978)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-81f4978.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4560)*

**Pull request merged**
