### PR TITLE
Redux Implementation 

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request brings in a redux approach to the API, and changes the Settings modal to a dummy component.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/425)

### CODE REVIEW

**Comment by mannycolon** [comment]
This is similar to redux but it is not 100% redux

**Comment by mannycolon** [comment]
@ihoegen

**Comment by mannycolon** [comment]
react-redux-introduction-33-638

**Comment by mannycolon** [comment]
@ihoegen i don't think redux uses event emitters

**Comment by ihoegen** [comment]
@mannycolon In redux, an action is portrayed as an event that is emitted. It's the only way to signal that the action has happened, so it has to use the Event Emitter class.

**Comment by mannycolon** [comment]
@ihoegen components change based on state change so when you click a button it updates the store which is the central state for the app and then that state change trickles down dump components through the provider components which is this case should be **app.js** and then containers components and finally dump components.

**Comment by mannycolon** [comment]
Unlike Flux, Redux does not have the concept of a Dispatcher. This is because it relies on pure functions instead of **event emitters**, and pure functions are easy to compose and don't need an additional entity managing them. Depending on how you view Flux, you may see this as either a deviation or an implementation detail. Flux has often been described as (state, action) => state. In this sense, Redux is true to the Flux architecture, but makes it simpler thanks to pure functions.

https://github.com/reactjs/redux/blob/master/docs/introduction/PriorArt.md

**Comment by ihoegen** [comment]
@mannycolon So the state, in my implementation, is the store, which is located inside of the actions class. And according to the document you posted in slack, The only way to change the state is to emit an action, an object describing what happened. An event is required to signal and reflect a change in the store.

**Comment by ihoegen** [comment]
How are we supposed to pick up and listen for events without EventEmitters? @t3hpr1m3  @mannycolon

**Comment by mannycolon** [comment]
I believe that instead of immitting its dispatching an action, which could mean the same but as far as I know they're not the same. However, to be honest, this implementation it's similar to redux but it is not redux. even the branch name implies that lol **ih-not-redux**

**Comment by ihoegen** [comment]
Yeah by ih-not-redux I meant not using the Redux npm module. If the only thing we are doing different is emitting an event instead of an action, I don't see much harm. However, we should get some other input on this

**Comment by mannycolon** [comment]
If we are doing redux, didnt we say we were going to follow the right patterns??? and didnt we say we would use the redux npm module??

**Comment by mannycolon** [comment]
And emitting an event instead of an action its not the only thing we are doing different. @ihoegen

**Comment by ihoegen** [comment]
Yes, but not using the module was later deemed okay, and from what I understand, the right patterns are being followed.

**Comment by mannycolon** [comment]
@ihoegen sorry i dont think you are. the store and the actions index.js are not supposed to be the same thing

**Comment by mannycolon** [comment]
the store and the actions are separate things

**Comment by ihoegen** [comment]
I mean they basically are separate, it's just in the same file. The store could easily be exported to somewhere else. I really want to wait until Jdubz can give some input

**Comment by mannycolon** [comment]
alright, just wanted to let you know. i would strongly suggest reading more about redux.

**Comment by ihoegen** [comment]
Thanks

**Comment by RoyalSix** [comment]
I think we should require the npm module redux, this implementation does seem very close to redux, but we shouldn't be trying to abstract redux, it looks like you sort of made a wrapper / api for its actual implementation. This is also not using reducers. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/425#-:-KZghJJyxiH_rYevDN-X:b-n4io9o)*

**Comment by RoyalSix** [comment]
It will also be easier for developers to jump on board if they already know redux, and don't have to figure out how we implemented it our own way

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/425#-:-KZgkLQELCdAE7x1gQY_:b-7gxcn3)*

**Comment by ihoegen** [comment]
@RoyalSix @mannycolon I'm having trouble with the NPM redux, so if you guys want to implement that, I'll hand it over to you

**Comment by RoyalSix** [comment]
Ok, I'll give it a shot, I'll update in a few

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/425#-:-KZh8qbc7QA3PrT1_k8o:bwssqj7)*

**Pull request closed without merging**
