### PR TITLE
QA Fail Fixes (Percentage Complete, Persistence, Default Selected Categories)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes a bug in the new check category implementation

#### Please include detailed Test instructions for your pull request:
- Open a project that already has checks completed, but has not yet been opened with the new check category implementation. Here is one if you do not have one. 
[en_reg_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2646626/en_reg_tit_book.zip)
- Note the project shows 97% complete before opening with tW.
- Open the project with tW and go back to the tools page
- Ensure that the progress is still at 97%
- Please try different combinations of opening the project to ensure the percent complete does not change.
- Please checkout the issue #2010 and make sure all the requirements are met

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-dfae7e7.deb) is ready for download.
[macOS build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-dfae7e7.dmg) is ready for download.
[Windows x64 build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-dfae7e7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-dfae7e7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-dfae7e7.deb) is ready for download.
[macOS build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-dfae7e7.dmg) is ready for download.
[Windows x64 build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-dfae7e7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (dfae7e7)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-dfae7e7.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
**NOTE: Still need to write more tests**

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-ff6a05b.deb) is ready for download.
[macOS build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-ff6a05b.dmg) is ready for download.
[Windows x64 build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-ff6a05b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-ff6a05b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-ff6a05b.deb) is ready for download.
[macOS build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-ff6a05b.dmg) is ready for download.
[Windows x64 build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-ff6a05b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ff6a05b)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-ff6a05b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (253a943)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-253a943.deb) is ready for download.
[macOS build 1.1.0 (253a943)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-253a943.dmg) is ready for download.
[Windows x64 build 1.1.0 (253a943)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-253a943.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (253a943)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-253a943.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (429a527)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-429a527.deb) is ready for download.
[macOS build 1.1.0 (429a527)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-429a527.dmg) is ready for download.
[Windows x64 build 1.1.0 (429a527)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-429a527.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (429a527)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-429a527.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-7e33962.deb) is ready for download.
[macOS build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-7e33962.dmg) is ready for download.
[Windows x64 build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-7e33962.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-7e33962.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-7e33962.deb) is ready for download.
[macOS build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-7e33962.dmg) is ready for download.
[Windows x64 build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-7e33962.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (7e33962)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-7e33962.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r3, 4 of 6 files at r4, 2 of 3 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/ProjectDetailsActions.js, line 39 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525#-LTBDQq0-bgQNB30MUYv:-LTBDQq1-GBMjj45cuaj:buypw50) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7e339620858b04e2d8655638ffe785aebba8101b/src/js/actions/ProjectDetailsActions.js#L39)):*
> ```JavaScript
>      * false it will be deleted from the array
>     */
>     const update = (array) => {
> ```

can we make this a helper function and abstract it out

**Comment by mannycolon** [comment]
Local test: `LGTM`
Please merge with the latest develop branch & resolve merge conflicts

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (cb221c5)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-cb221c5.deb) is ready for download.
[macOS build 1.1.0 (cb221c5)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-cb221c5.dmg) is ready for download.
[Windows x64 build 1.1.0 (cb221c5)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-cb221c5.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (cb221c5)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-cb221c5.setup.exe) is ready for download.

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/actions/ProjectDetailsActions.js, line 39 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525#-LTBDQq0-bgQNB30MUYv:-LTO2Rp49YUrkDeZfACJ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7e339620858b04e2d8655638ffe785aebba8101b/src/js/actions/ProjectDetailsActions.js#L39)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we make this a helper function and abstract it out 
</blockquote></details>

Done.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (2c13382)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-linux-x64-1.1.0-2c13382.deb) is ready for download.
[macOS build 1.1.0 (2c13382)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-macos-x64-1.1.0-2c13382.dmg) is ready for download.
[Windows x64 build 1.1.0 (2c13382)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x64-1.1.0-2c13382.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2c13382)](https://tc-builds.door43.org/build/bugfix-jay-5191/translationCore-win-x32-1.1.0-2c13382.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r7, 4 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5525#-:-LTOMNj02GFcFYR4tAnl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
