### PR TITLE
Offline Mode For TC

### PR DESCRIPTION
**Pull request by RoyalSix**
There was no proposed UI, so simply click the online button to enable/disable online functionality.
npm install to test

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/730)

### CODE REVIEW

**Comment by ihoegen** [comment]
@RoyalSix This does not work on Windows 10. Clicking it still allows me to sign in, and sync projects.

**Comment by ihoegen** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/CoreActionsRedux.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730#-Kd6u8JagY8R1MwzQg3X:-Kd6u8JagY8R1MwzQg3Y:bcbko7l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c35f312647889f0755df43ec8849e66384fed35c/src/js/actions/CoreActionsRedux.js#L57)):*
> ```JavaScript
>         })
>       } else {
>         const electronDir = window.__base + "\\node_modules\\electron\\dist\\electron.exe";
> ```

This could be problematic on builds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730)*

**Comment by RoyalSix** [comment]
Fixed.

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/CoreActionsRedux.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730#-Kd6u8JagY8R1MwzQg3X:-Kd7EloSpzEK1Fmvs_kv:b3txja4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c35f312647889f0755df43ec8849e66384fed35c/src/js/actions/CoreActionsRedux.js#L57)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

This could be problematic on builds
</blockquote></details>

How could I test this with a practice build?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730#-:-Kd7EsF7NeMX5LeK5iLk:bt2vr1b)*

**Comment by EllDoubleYew** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/js/components/core/SideBar/OnlineStatus.js, line 52 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730#-KdBv65KJnV6aie5RoAO:-KdBv65KJnV6aie5RoAP:bmx4l0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/53d91c91d2cdab169e941d9ea3000f6ebad60c69/src/js/components/core/SideBar/OnlineStatus.js#L52)):*
> ```JavaScript
> 
>   onPress() {
>     this.props.changeOnlineStatus(!this.props.online);
> ```

For this entire file, merge my branch I wrote that does this. You will just need to use this callback in my component and should not have any problems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/730)*

**Pull request merged**
