### PR TITLE
Feature - #2010 - TranslationWords Category Checkboxes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR adds new functionality of choosing which checks you would like to use by selecting that category

#### Please include detailed Test instructions for your pull request:
- Open the app and select the categories for the checks you would like to use. 
- Ensure the appropriate checks were loaded base on the category you chose 
- Make selections
- Go back to the tool card views, ensure that the correct progress for the checks selected is showing
- Try different combinations of different checks selected on the tool card
- If no checks are selected then the launch button should be disabled

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5447)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@RoyalSix - Works well for me, except tW crashes when opened and nothing is selected.  The launch button should probably be disabled when nothing is selected.  You probably should ask @benjore  what hint text to show on launch button if nothing is selected.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (099cc34)](https://tc-builds.door43.org/build/feature-2010/translationCore-linux-x64-1.1.0-099cc34.deb) is ready for download.
[macOS build 1.1.0 (099cc34)](https://tc-builds.door43.org/build/feature-2010/translationCore-macos-x64-1.1.0-099cc34.dmg) is ready for download.
[Windows x64 build 1.1.0 (099cc34)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x64-1.1.0-099cc34.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (099cc34)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x32-1.1.0-099cc34.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ef15de3)](https://tc-builds.door43.org/build/feature-2010/translationCore-linux-x64-1.1.0-ef15de3.deb) is ready for download.
[macOS build 1.1.0 (ef15de3)](https://tc-builds.door43.org/build/feature-2010/translationCore-macos-x64-1.1.0-ef15de3.dmg) is ready for download.
[Windows x64 build 1.1.0 (ef15de3)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x64-1.1.0-ef15de3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ef15de3)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x32-1.1.0-ef15de3.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (49f5b7b)](https://tc-builds.door43.org/build/feature-2010/translationCore-linux-x64-1.1.0-49f5b7b.deb) is ready for download.
[macOS build 1.1.0 (49f5b7b)](https://tc-builds.door43.org/build/feature-2010/translationCore-macos-x64-1.1.0-49f5b7b.dmg) is ready for download.
[Windows x64 build 1.1.0 (49f5b7b)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x64-1.1.0-49f5b7b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (49f5b7b)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x32-1.1.0-49f5b7b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e053e63)](https://tc-builds.door43.org/build/feature-2010/translationCore-linux-x64-1.1.0-e053e63.deb) is ready for download.
[macOS build 1.1.0 (e053e63)](https://tc-builds.door43.org/build/feature-2010/translationCore-macos-x64-1.1.0-e053e63.dmg) is ready for download.
[Windows x64 build 1.1.0 (e053e63)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x64-1.1.0-e053e63.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e053e63)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x32-1.1.0-e053e63.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3a6a132)](https://tc-builds.door43.org/build/feature-2010/translationCore-linux-x64-1.1.0-3a6a132.deb) is ready for download.
[macOS build 1.1.0 (3a6a132)](https://tc-builds.door43.org/build/feature-2010/translationCore-macos-x64-1.1.0-3a6a132.dmg) is ready for download.
[Windows x64 build 1.1.0 (3a6a132)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x64-1.1.0-3a6a132.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3a6a132)](https://tc-builds.door43.org/build/feature-2010/translationCore-win-x32-1.1.0-3a6a132.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
Local test: passed
Code review: :lgtm: 

> Reviewed 6 of 17 files at r1, 12 of 136 files at r2, 4 of 4 files at r3, 1 of 122 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5447#-:-LSGHZdV8RET1zyMnBLD:b-jqusyd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
