### PR TITLE
feature 1717/Add Old Hebrew support

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- changed Hebrew language code from 'he' to 'hbo'

#### Please include detailed Test instructions for your pull request:
-  test with branch in https://github.com/translationCoreApps/wordAlignment/pull/102
- Switch to developer mode.
- will need to do check for content updates.  Select "Ancient Hebrew (hbo)" and download.
- Open an OT book in WA, the OL in the scripturePane should now be Hebrew UHB. Should look like: screen shot 2018-11-15 at 5 37 25 am

- Open an NT book in WA, the OL in the scripturePane should now be Greek UGNT. 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5421)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (05ddf71)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-linux-x64-1.1.0-05ddf71.deb) is ready for download.
[macOS build 1.1.0 (05ddf71)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-macos-x64-1.1.0-05ddf71.dmg) is ready for download.
[Windows x64 build 1.1.0 (05ddf71)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x64-1.1.0-05ddf71.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (05ddf71)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x32-1.1.0-05ddf71.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0007bf8)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-linux-x64-1.1.0-0007bf8.deb) is ready for download.
[macOS build 1.1.0 (0007bf8)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-macos-x64-1.1.0-0007bf8.dmg) is ready for download.
[Windows x64 build 1.1.0 (0007bf8)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x64-1.1.0-0007bf8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0007bf8)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x32-1.1.0-0007bf8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (17ae095)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-linux-x64-1.1.0-17ae095.deb) is ready for download.
[macOS build 1.1.0 (17ae095)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-macos-x64-1.1.0-17ae095.dmg) is ready for download.
[Windows x64 build 1.1.0 (17ae095)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x64-1.1.0-17ae095.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (17ae095)](https://tc-builds.door43.org/build/feature-mcleanb-1717/translationCore-win-x32-1.1.0-17ae095.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5421)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by richmahn — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5421#-:-LRPqaid6N8SmmG1rhBL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Pull request merged**
