### PR TITLE
DragDropActions.js bug fixed and renamed Snackbar component 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/867)

### CODE REVIEW

**Comment by ihoegen** [comment]
@mannycolon What does this PR do?

**Comment by mannycolon** [comment]
@ihoegen it changes the name for the snack bar component to avoid confusion with the material-ui snackbar component

**Comment by mannycolon** [comment]
@ihoegen also fixes a bug with draganddrog actions

**Comment by ihoegen** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/867)*

**Comment by ihoegen** [comment]
@mannycolon I will wait on tests, then merge

**Pull request merged**
