### PR TITLE
Addressed all QA issues on 5756

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Please see [issue comment](https://github.com/unfoldingword-dev/translationcore/issues/5756#issuecomment-486289919)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6046)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (7cfe637)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-linux-x64-1.2.0-7cfe637.deb) is ready for download.
[macOS build 1.2.0 (7cfe637)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-macos-x64-1.2.0-7cfe637.dmg) is ready for download.
[Windows x64 build 1.2.0 (7cfe637)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-win-x64-1.2.0-7cfe637.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (7cfe637)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-win-x32-1.2.0-7cfe637.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4cee2bd)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-linux-x64-1.2.0-4cee2bd.deb) is ready for download.
[macOS build 1.2.0 (4cee2bd)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-macos-x64-1.2.0-4cee2bd.dmg) is ready for download.
[Windows x64 build 1.2.0 (4cee2bd)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-win-x64-1.2.0-4cee2bd.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4cee2bd)](https://tc-builds.door43.org/build/bugfix-mannycolon-5756/translationCore-win-x32-1.2.0-4cee2bd.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6046)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
Checking:

- [x] ISSUE 1:
The Load button should be disabled when no categories are selected. (May be fixed when #5920 is fixed)

- [x] ISSUE 2:
The top level checkbox should show the indeterminate state when only one or some of the child categories are checked. 

- [x] ISSUE 3:
"Translating Father and Son" does not show up as a category on the tN card, but appears as a group menu item when the tool is open with a book that has that check. (Should be fixed when #5920 is fixed)

- [x] ISSUE 4:
There are inconsistencies in what a category is named on the tN card and what it is named in the group menu. (Some examples follow)

- [x] ISSUE 5:
There are inconsistencies between the subcategory name and the title on the popup card. For example:

- [x] ISSUE 6:
It appears that all subcategories are loaded for a category if any of them are selected.

~- [ ] ISSUE 7:~
~Missing translation keys on tool card (locale specific problem)~  Looks like language was removed.

- [x] ISSUE 8:
Some subcategories are not capitalized. For example:

- [x] ISSUE 9:
The subcategories are sometimes not in alphabetical order. For example:

**Comment by PhotoNomad0** [comment]
@mannycolon - testing the app I see strange spacing issues.  Is this expected (this is with build macOS build 1.2.0 (4cee2bd))?

Screen Shot 2019-05-06 at 7 47 42 AM

**Comment by PhotoNomad0** [comment]
@mannycolon - in testing, the issues seem to be addressed.  Just waiting determination of UI layout question.

**Comment by mannycolon** [comment]
Verified on cc9c5b5

**Pull request merged**
