### PR TITLE
Bugfix 5985/Add git save before project migration

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Add git save before project migration so that old project content is preserved before changes are made.  This should work on project selection, local import, project import, project export, upload to D43.

#### Please include detailed Test instructions for your pull request:
- checkout branch, do `npm run load-apps`, `npm ci`, `npm start`
- open console log.
- open a project:
  - in console log should see `migrateOldProjects.shouldRun(...) - saved project version of '' does not match APP version '1.1.4'` and `migrateSaveChangesInOldProjects.run() - git save complete` and no error.
  - select a different project, and then go back and select original project.  This time should NOT see `migrateOldProjects.shouldRun...` message since it has already been migrated.
- import a new USFM project:
  - in console log should see `migrateOldProjects.shouldRun(...) - saved project version of '' does not match APP version '1.1.4'` and `migrateSaveChangesInOldProjects.run() - git save complete` and no error.
  - open a terminal window and cd the project folder.
  - do `git log` and should see entry with comment `Migrating Old Project`
- import a project from D43:
  - in console log should see `migrateOldProjects.shouldRun(...) - saved project version of '' does not match APP version '1.1.4'` and `migrateSaveChangesInOldProjects.run() - git save complete` and no error.
- export an old project:
  - unzip this project into projects folder but do not select it: [en_test_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3113199/en_test_tit_book.zip)
  - do USFM export and include alignment data
  - in console log should see `migrateOldProjects.shouldRun(...) - saved project version of '' does not match APP version '1.1.4'` and `migrateSaveChangesInOldProjects.run() - git save complete` and no error.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.4 (6f9eeb2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-linux-x64-1.1.4-6f9eeb2.deb) is ready for download.
[macOS build 1.1.4 (6f9eeb2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-macos-x64-1.1.4-6f9eeb2.dmg) is ready for download.
[Windows x64 build 1.1.4 (6f9eeb2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x64-1.1.4-6f9eeb2.setup.exe) is ready for download.
[Windows x32 build 1.1.4 (6f9eeb2)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x32-1.1.4-6f9eeb2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.4 (d561f70)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-linux-x64-1.1.4-d561f70.deb) is ready for download.
[macOS build 1.1.4 (d561f70)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-macos-x64-1.1.4-d561f70.dmg) is ready for download.
[Windows x64 build 1.1.4 (d561f70)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x64-1.1.4-d561f70.setup.exe) is ready for download.
[Windows x32 build 1.1.4 (d561f70)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x32-1.1.4-d561f70.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.4 (4054012)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-linux-x64-1.1.4-4054012.deb) is ready for download.
[macOS build 1.1.4 (4054012)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-macos-x64-1.1.4-4054012.dmg) is ready for download.
[Windows x64 build 1.1.4 (4054012)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x64-1.1.4-4054012.setup.exe) is ready for download.
[Windows x32 build 1.1.4 (4054012)](https://tc-builds.door43.org/build/bugfix-mcleanb-5985/translationCore-win-x32-1.1.4-4054012.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

___
*[src/js/actions/ProjectUploadActions.js, line 70 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051#-LeI-FqE3kYcGbr9K5aQ:-LeI-FqE3kYcGbr9K5aR:b4ch5f6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a83d660a16d4aac486c3dd72198d0976c355815/src/js/actions/ProjectUploadActions.js#L70)):*
> ```JavaScript
>  * @return {Promise<void>}
>  */
> async function archiveOldProjects(projectPath) {
> ```

What does it mean to archive a project?
___
*[src/js/helpers/ProjectMigration/migrateOldProjects.js, line 7 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051#-LeI-iI5D8kveEuVL3ji:-LeI-iI68mQn-kCQKioa:b-ehpq2v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a83d660a16d4aac486c3dd72198d0976c355815/src/js/helpers/ProjectMigration/migrateOldProjects.js#L7)):*
> ```JavaScript
> import Repo from "../Repo";
> 
> export const tc_EDIT_VERSION_KEY = "tc_edit_version";
> ```

In a nut shell what does this being used for?

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051)* status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/actions/ProjectUploadActions.js, line 70 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051#-LeI-FqE3kYcGbr9K5aQ:-LeINGi8Dk6ZdYzGbRAH:bq9l109) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a83d660a16d4aac486c3dd72198d0976c355815/src/js/actions/ProjectUploadActions.js#L70)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

What does it mean to archive a project?
</blockquote></details>

Changed method name and updated JSDocs
___
*[src/js/helpers/ProjectMigration/migrateOldProjects.js, line 7 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051#-LeI-iI5D8kveEuVL3ji:-LeINSqf4lTIO0yJmu4L:bz1pubj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5a83d660a16d4aac486c3dd72198d0976c355815/src/js/helpers/ProjectMigration/migrateOldProjects.js#L7)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

In a nut shell what does this being used for?
</blockquote></details>

Added comment and changed method name.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6051)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
