### PR TITLE
Added Recent Project To Modal w/ Redux

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/561)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ToolsActions.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_HIvvJclSdqtpbJ-:-KbQ_HIvvJclSdqtpbJ0:b79of64) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/actions/ToolsActions.js#L24)):*
> ```JavaScript
>           val: true
>         });
>         dispatch({ type: consts.SHOW_SWITCH_CHECK_MODAL, val: false });
> ```

just had a question what exactly does show_switch_check_modal do??

---

*[src/js/pages/app.js, line 1012 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_sfUwDqfr_C1R4XL:-KbQ_sfV2quoiPcY3sJJ:b-sn6fih) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/pages/app.js#L1012)):*
> ```JavaScript
>         },
>         onHandleUserName: (e) => {
>             dispatch(ToolsActions.setUserName(e.target.value));
> ```

sorry i left this in my code base but this is actually not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
@RoyalSix  Now that you've moved all project related components to the new modal. its time to remove all functionality from the old modal. also your my recent projects isn't working fine in the white screen

**Comment by RoyalSix** [comment]
Review status: 8 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ToolsActions.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_HIvvJclSdqtpbJ-:-KbSTGWENTHHnRqgvyYo:b-leto8j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/actions/ToolsActions.js#L24)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

just had a question what exactly does show_switch_check_modal do??
</blockquote></details>

It shows the apps modal depending on the value passed

---

*[src/js/pages/app.js, line 1012 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_sfUwDqfr_C1R4XL:-KbSTLgE9gc_mpVBB6zG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/pages/app.js#L1012)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

sorry i left this in my code base but this is actually not needed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/ToolsActions.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_HIvvJclSdqtpbJ-:-KbSVxIll8KyVraO05wj:b-uo06rw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/actions/ToolsActions.js#L24)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It shows the apps modal depending on the value passed
</blockquote></details>

we may want to remove the old modal functionality and this seems to be a great opportunity to do so

---

*[src/js/components/core/RecentProjects.js, line 11 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbSUBb7rDHVu840RI6U:-KbSUBb7rDHVu840RI6V:b5wws46) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/64ee3917bacb6441bc4eefa3dad71507051f00f4/src/js/components/core/RecentProjects.js#L11)):*
> ```JavaScript
> class RecentProjects extends React.Component {
>   render() {
>     console.log(this.props)
> ```

remove console.log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ToolsActions.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561#-KbQ_HIvvJclSdqtpbJ-:-KbSXitzdcjjJoyfwdwJ:bmkv6b5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fbd3bcef0bcc8c3b5b4048d4325f79dd2aab0881/src/js/actions/ToolsActions.js#L24)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we may want to remove the old modal functionality and this seems to be a great opportunity to do so
</blockquote></details>

do we still need this???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Comment by mannycolon** [comment]
Reviewed 1 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/561)*

**Pull request merged**
