### PR TITLE
Archive projects

### PR DESCRIPTION
**Pull request by da1nerd**
> This is a draft until some [questions](https://github.com/unfoldingWord/translationCore/issues/975#issuecomment-618142589) get answered.

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Related to #975 
- Adds archive option to project menu. Once the user acknowledges the confirmation dialog the project will be archived.
- In my tests, archiving happens very fast so I did not bother putting in a loader.

Instead of adding yet another reducer to handle the confirmation dialog I added a middleware that provides some generic confirmation functionality. This will make future confirmations easier to set up. 

```js
dispatch(confirmAction({
    message: "Are you sure?",
    confirmButtonText: "Of course I'm sure",
  }, someActionToExecute));

// where someActionToExecute is an action (regular, thunk, or promise) that will be executed if approved.
```

Below is a demo of the archiving.

Canceling
archive_cancel

Error
archive_fail

Success
archive_success

Archive folder
archive_folder

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6868)

### CODE REVIEW

**Review by mannycolon — DISMISSED** [review]

**Comment by mannycolon** [comment]
The archive button is missing the border/divider above
Screen Shot 2020-04-27 at 11 55 19 AM

Screen Shot 2020-04-27 at 11 55 19 AM


I think the text "Archive Project" should bold. (Thats how we've done it in the past when we reference a button)
Screen Shot 2020-04-27 at 11 55 52 AM

Weird-looking timestamp on mac, we usually use the following format: `2020-04-15T21_15_47.518Z` to make sure it works on windows. I think we use `modifiedTimestamp.replace(/[:"]/g, '_')`
Screen Shot 2020-04-27 at 11 56 18 AM

**Comment by da1nerd** [comment]
ok I made those changes.

**Comment by da1nerd** [comment]
@mannycolon it turns out mac cannot use `:` in file names. So we can't use the standard timestamp format `2020-03-20T02:40:25Z`. We could use `2020-03-20T02-40-25Z` which would work on all OS's.

Update: the latest code does the above.

**Comment by mannycolon** [comment]
@neutrinog We use  _ (`2020-04-15T21_15_47.518Z`) not - (`2020-03-20T02-40-25Z`).
That's what I explained in my comment above.

**Comment by da1nerd** [comment]
Oops I definitely did not see your comment between the screenshots.

**Comment by da1nerd** [comment]
@mannycolon timestamps updated.

**Comment by mannycolon** [comment]
@neutrinog Great job!

**Pull request merged**
