### PR TITLE
Refactored VerseCheckWrapper, GroupMenuWrapper & ScripturePaneWrapper

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Checkout `feature-mannycolon-6443-6446` and run `npm i`
- All tools should open and work properly 
- All annotations functionality should work properly. (Verse check component: Comments, selections, verse edits, bookmarks)
- Make sure the scripture pane, group menu work properly. (Change checks and make sure everything updates as needed) 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6470)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (0aac1d8)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-linux-x64-2.0.0-0aac1d8.deb) is ready for download.
[macOS build 2.0.0 (0aac1d8)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-macos-x64-2.0.0-0aac1d8.dmg) is ready for download.
[Windows x64 build 2.0.0 (0aac1d8)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x64-2.0.0-0aac1d8.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (0aac1d8)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x32-2.0.0-0aac1d8.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6470)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
@mannycolon - Everything is working except Lexicon popups in WA verse alignment area.  But popups are working in Scripture Pane.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1f78b84)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-linux-x64-2.0.0-1f78b84.deb) is ready for download.
[macOS build 2.0.0 (1f78b84)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-macos-x64-2.0.0-1f78b84.dmg) is ready for download.
[Windows x64 build 2.0.0 (1f78b84)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x64-2.0.0-1f78b84.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1f78b84)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x32-2.0.0-1f78b84.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (a042e72)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-linux-x64-2.0.0-a042e72.deb) is ready for download.
[macOS build 2.0.0 (a042e72)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-macos-x64-2.0.0-a042e72.dmg) is ready for download.
[Windows x64 build 2.0.0 (a042e72)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x64-2.0.0-a042e72.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (a042e72)](https://tc-builds.door43.org/build/feature-mannycolon-6443-6446/translationCore-win-x32-2.0.0-a042e72.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6470)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
