### PR TITLE
Attempt to batch toggleGroupDataItems with redux-batched-actions

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
https://github.com/unfoldingWord-dev/translationCore/issues/4842
Addresses slow loading of the book of Acts in the Alignment tool.

#### Please include detailed Test instructions for your pull request:
- unfortunately Concourse does not build PRs against releases.  Build manually using correct submodules  (do `git submodule deinit -f . && git submodule update --init`)
- Load the book of Acts from this project: https://git.door43.org/lrsallee/en_act.git
- Load the wordAlignment tool and ensure it loads both under 20s and menu acts as expected.
- Other projects, tools, loading might be addressable in a similar way.
- Load other projects and tools and ensure all works well.

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Performance issues with drag and drop in large books in wA tool. https://github.com/unfoldingWord-dev/translationCore/issues/4842
- Joel's refactor of wA already triggers the menu update and the workaround that was there is no longer necessary.
- Long term: The whole caching of the menu and refresh counter needs to be removed as it would be nearly as performant to just batch the actions to populate the reducer that feeds the menu. Cache invalidation is one of the hardest things and it is recommended to remove the caching and optimize the code.
https://twitter.com/codinghorror/status/506010907021828096?lang=en

#### Please include detailed Test instructions for your pull request:
- Load a large book with alignment such as Acts from: https://git.door43.org/lrsallee/en_act.git
- Drag and drop words and it should respond in less than 2 seconds instead of 20-30s.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4882)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Replaces PR https://github.com/unfoldingword-dev/translationcore/pull/4874

**Comment by PhotoNomad0** [comment]
@klappy - Unfortunately Concourse does not build PRs against releases.  Build manually using correct submodules (do `git submodule deinit -f . && git submodule update --init`)

**Comment by PhotoNomad0** [comment]
LGTM but someone else needs to test to make sure I got everything.

**Comment by bspidel** [comment]
Results:     
   3ghz win10
   load acts 44s
   launch wA 23s
   menu verse to verse 1.5s
   menu chapter to chapter 1.5s
   drag word to wordbank subsecond
   drag wordbank to verse subsecond-1 second

   load titus 4 seconds
   launch wA 3 seconds

Unit tests clean
Console clean but redux log is on. should that be true?

**Pull request merged**
