### PR TITLE
Added Check For Stale Groups Data and Groups Index After Update

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR addresses an issue with caching previously loaded groups data but never checking if that cache is still valid after updating the source.

#### Please include detailed Test instructions for your pull request:
1. Checkout the branch
2. Open a new project (everything should work per usual)
3. Note that in tN the parent category `Cultural` only has one nested item `Implicit and Explicit Information`
4. Restart tC
5. Download the following [folder](https://github.com/unfoldingWord-dev/translationCore/files/3068164/translationNotes.zip)
6. Replace the the tN folder with the one in the resources under Users⁩ ▸ ⁨{user} ▸ ⁨translationCore⁩ ▸ ⁨resources⁩ ▸ ⁨en⁩ ▸ ⁨translationHelps⁩ ▸ translationNotes
7. Open the same project you should now see the `Cultural` parent category unchecked and a new category nested inside called `Unknowns`
8. Open the tN tool and ensure that it loads the groups data correctly

Note: This test was the closest I could find to replicating a source content update that results in changed tN groups data

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f41070c)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-f41070c.deb) is ready for download.
[macOS build 1.2.0 (f41070c)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-f41070c.dmg) is ready for download.
[Windows x64 build 1.2.0 (f41070c)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-f41070c.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f41070c)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-f41070c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4b20fa9)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-4b20fa9.deb) is ready for download.
[macOS build 1.2.0 (4b20fa9)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-4b20fa9.dmg) is ready for download.
[Windows x64 build 1.2.0 (4b20fa9)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-4b20fa9.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4b20fa9)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-4b20fa9.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
Before opening a Titus project I edited the`occurrenceNote` for the following file (figs-personification.json) located in `resources/en/translationHelps/translationNotes/v14/figures/groups/tit/figs-personification.json` and I did not see the change after opening the tN tool in the check personification 2:12

**Comment by mannycolon** [comment]
Also, I deleted a group data file (figs-doublenegatives.json) from the same folder path as above (`resources/en/translationHelps/translationNotes/v14/figures/groups/tit/`) It did not show up in the tool card boxes which is the correct behavior. However, the check for `Double Negatives` (doublenegatives) still showed up in the tN tool's menu.

**Comment by RoyalSix** [comment]
Making a fix for that

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (8540681)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-8540681.deb) is ready for download.
[macOS build 1.2.0 (8540681)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-8540681.dmg) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f3be9a7)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-f3be9a7.deb) is ready for download.
[macOS build 1.2.0 (f3be9a7)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-f3be9a7.dmg) is ready for download.
[Windows x64 build 1.2.0 (f3be9a7)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-f3be9a7.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f3be9a7)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-f3be9a7.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/SourceContentUpdatesActions.js, line 103 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-LcXKteZEiVUAa8mzwA7:-LcXKteZEiVUAa8mzwA8:bby8azf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3be9a7fed4061bd761631cc4810d32171f7fc39/src/js/actions/SourceContentUpdatesActions.js#L103)):*
> ```JavaScript
>           // if tool currently opened then load new bible resources
>           if (toolName) {
>             //groups data only becomes stale when the tool is open
> ```

What if you update tN while the tN tool is open?

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/actions/SourceContentUpdatesActions.js, line 103 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-LcXKteZEiVUAa8mzwA7:-LcXO0pq1cYozwQ1BhBW:b3s0rge) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3be9a7fed4061bd761631cc4810d32171f7fc39/src/js/actions/SourceContentUpdatesActions.js#L103)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

What if you update tN while the tN tool is open?
</blockquote></details>

The comment might be misleading. If the tool is open then the toolName will be defined and the processing will happen to update the data. That is the purpose of the block

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/actions/SourceContentUpdatesActions.js, line 103 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-LcXKteZEiVUAa8mzwA7:-LcXPArWC1HaDAm0Sach:b30yklh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3be9a7fed4061bd761631cc4810d32171f7fc39/src/js/actions/SourceContentUpdatesActions.js#L103)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

The comment might be misleading. If the tool is open then the toolName will be defined and the processing will happen to update the data. That is the purpose of the block
</blockquote></details>

Should we update the comment then to avoid confusion ?

**Comment by mannycolon** [comment]
After the latest update to the tN. The categories names were changed and it seems the cache is not being clear when categories are deleted. Therefore, I get the following error:

Open tC after merging with develop branch and select tN. However, it won't open the tool and I get the following warning/error. 


Screen Shot 2019-04-15 at 3 11 29 PM

**Comment by mannycolon** [comment]
However, If I manually delete cultural.json, lexical.json & morphological.json from the projects index folder for tN it opens fine

This path `/Users/mannycolon/translationCore/projects/en_ulb_tit_book/.apps/translationCore/index/translationNotes/tit/`

**Comment by mannycolon** [comment]
I opened a tit project with tN and got the following error
Screen Shot 2019-04-15 at 3 19 44 PM

**Comment by mannycolon** [comment]
> Also, I deleted a group data file (figs-doublenegatives.json) from the same folder path as above (`resources/en/translationHelps/translationNotes/v14/figures/groups/tit/`) It did not show up in the tool card boxes which is the correct behavior. However, the check for `Double Negatives` (doublenegatives) still showed up in the tN tool's menu.

This is still broken

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (9156568)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-9156568.deb) is ready for download.
[macOS build 1.2.0 (9156568)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-9156568.dmg) is ready for download.
[Windows x64 build 1.2.0 (9156568)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-9156568.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (9156568)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-9156568.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
@mannycolon Ok. Can you send your resource folder and project? For some reason, the tN data under translation helps is not the same hierarchy as the one in the `tsv-groupdata-parser` and I cannot reproduce the error

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (8b1482d)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-8b1482d.deb) is ready for download.
[macOS build 1.2.0 (8b1482d)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-8b1482d.dmg) is ready for download.
[Windows x64 build 1.2.0 (8b1482d)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-8b1482d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (8b1482d)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-8b1482d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (52b800b)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-52b800b.deb) is ready for download.
[macOS build 1.2.0 (52b800b)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-52b800b.dmg) is ready for download.
[Windows x64 build 1.2.0 (52b800b)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-52b800b.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (52b800b)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-52b800b.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
> > Also, I deleted a group data file (figs-doublenegatives.json) from the same folder path as above (`resources/en/translationHelps/translationNotes/v14/figures/groups/tit/`) It did not show up in the tool card boxes which is the correct behavior. However, the check for `Double Negatives` (doublenegatives) still showed up in the tN tool's menu.
> 
> This is still broken

@mannycolon 
This test you performed was intentionally not accounted for in my implementation.
There is no indication to the app that something has changed. The only way for that to be accounted for is if we copied from the groups data resource on each new project open. That would make project opening a lot slower, especially with bigger books.

**Comment by mannycolon** [comment]
@RoyalSix Please merge with latest develop branch and resolve merge conflicts so I can retest

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (7a77fd3)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-7a77fd3.deb) is ready for download.
[macOS build 1.2.0 (7a77fd3)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-7a77fd3.dmg) is ready for download.
[Windows x64 build 1.2.0 (7a77fd3)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-7a77fd3.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (7a77fd3)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-7a77fd3.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
@mannycolon Merged w/ develop

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r6, 1 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-:-LcimWjd6sl5CmMaeg_i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
Pending local test

**Comment by mannycolon** [comment]
Merge with latest dev branch again and fix unit tests

**Comment by mannycolon** [comment]
I opened this project [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3095734/en_ulb_tit_book.zip)  and the `tN` categories didn't show up. (Only figures show up)

See image below:
Screen Shot 2019-04-18 at 2 26 33 PM

**Comment by RoyalSix** [comment]
They should show after the latest merge @mannycolon

**Comment by mannycolon** [comment]
Also fix the tools commit

**Comment by mannycolon** [comment]
@RoyalSix I tested it again and it doesnt show up

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @RoyalSix)

___
*[src/js/actions/SourceContentUpdatesActions.js, line 106 at r11](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-Lclj7NU9JkNoSqh-hF0:-Lclj7NV6LJXGfEz4mho:bkf0vij) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e313561f11725b22787cb6334b1408d038476f91/src/js/actions/SourceContentUpdatesActions.js#L106)):*
> ```
> Bible.NT_ORIG_LANG
> ```
Is what you now want to use

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @PhotoNomad0)

___
*[src/js/actions/SourceContentUpdatesActions.js, line 103 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-LcXKteZEiVUAa8mzwA7:-Lc_jhGhAL-CKuTEhxx-:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f3be9a7fed4061bd761631cc4810d32171f7fc39/src/js/actions/SourceContentUpdatesActions.js#L103)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Should we update the comment then to avoid confusion ? 
</blockquote></details>

Done.
___
*[src/js/actions/SourceContentUpdatesActions.js, line 106 at r11](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-Lclj7NU9JkNoSqh-hF0:-LclkGNKDbJyy8idS_YR:b-rq5eyj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e313561f11725b22787cb6334b1408d038476f91/src/js/actions/SourceContentUpdatesActions.js#L106)):*
> Bible.NT_ORIG_LANG
Updated

**Comment by RoyalSix** [comment]
@mannycolon can you send your project

**Comment by mannycolon** [comment]
@RoyalSix If you read my comment you will notice the project attached

**Comment by mannycolon** [comment]
Modified the `source-content-updater-manifest.json` and the `manifest.json` for tN. Deleted `figs-doublenegatives.json` from the project's index folder opened this project [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3095734/en_ulb_tit_book.zip)  with tN and still see `Double Negatives` in the menu.

**Comment by mannycolon** [comment]
@RoyalSix You added the wrong tool's commits again

**Comment by RoyalSix** [comment]
Did you modify the timestamp to something newer than before?

**Comment by mannycolon** [comment]
@RoyalSix Yes

**Comment by RoyalSix** [comment]
@mannycolon Should be fixed

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (461a673)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-461a673.deb) is ready for download.
[macOS build 1.2.0 (461a673)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-461a673.dmg) is ready for download.
[Windows x64 build 1.2.0 (461a673)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-461a673.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (461a673)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-461a673.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
> I opened this project [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3095734/en_ulb_tit_book.zip) and the `tN` categories didn't show up. (Only figures show up)
> 
> See image below:
> Screen Shot 2019-04-18 at 2 26 33 PM

@RoyalSix This is still not fixed

**Comment by mannycolon** [comment]
Double negatives no longer show up in the menu but the app does open in the double negative check. Seems to be related to the `currentContextId.json` file not being updated

**Comment by mannycolon** [comment]
Here's the project again 
[en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3096041/en_ulb_tit_book.zip)

**Review by PhotoNomad0 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @RoyalSix)

___
*[src/js/helpers/ProjectAPI.js, line 353 at r13](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-Ld5EPk73frY43jlJeRq:-Ld5EPk73frY43jlJeRr:b-h2y32c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/461a673dc027b4675d7fb9b690a519d000fda81a/src/js/helpers/ProjectAPI.js#L353)):*
> ```JavaScript
>       ".categoryIndex");
>     fs.removeSync(indexPath);
>     fs.mkdirSync(indexPath);
> ```

Should make this call ensureDirSync().  Otherwise will throw an exception when loading a new project from USFM.

**Comment by RoyalSix** [comment]
@PhotoNomad0 I need to empty the directory. Ensure only see if it exists. Are you suggesting I should call `fs.existsSync` before I remove?

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (20d5582)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-20d5582.deb) is ready for download.
[macOS build 1.2.0 (20d5582)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-20d5582.dmg) is ready for download.
[Windows x64 build 1.2.0 (20d5582)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-20d5582.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (20d5582)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-20d5582.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
> Double negatives no longer show up in the menu but the app does open in the double negative check. Seems to be related to the `currentContextId.json` file not being updated

@RoyalSix This isn't fixed yet. 

Steps:
1. Deleted `figs-doublenegatives.json` from `(resources/en/translationHelps/translationNotes/v14/figures/groups/tit/)` 
1. Open this Project [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3096041/en_ulb_tit_book.zip) (Please if you have an old version of this project delete it before importing it)
1. The project opens in the `Double Negatives` (doublenegatives)

This seems to happen because the `currentContextId.json` file is not being updated when a group data item is removed.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (6781732)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-linux-x64-1.2.0-6781732.deb) is ready for download.
[macOS build 1.2.0 (6781732)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-macos-x64-1.2.0-6781732.dmg) is ready for download.
[Windows x64 build 1.2.0 (6781732)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x64-1.2.0-6781732.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (6781732)](https://tc-builds.door43.org/build/feature-jay-5951/translationCore-win-x32-1.2.0-6781732.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
@mannycolon Fixed the issue can retest

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 2 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 3 of 3 files at r14, 1 of 2 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

**Review by mannycolon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5968#-:-LdFPrZJ0XbMzy-qdf0G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

**Pull request merged**
