### PR TITLE
Prep for adding Basic MAP, and disabled builds

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This is related to #2258 and required for https://github.com/translationCoreApps/wordAlignment/pull/43
- Updates the `word-map` dependency.
- Disables travis builds for the `develop` branch (now handled by concourse).

#### Please include detailed Test instructions for your pull request:
- nothing to test, just configuration changes.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4621)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-57fc3bf.zip) is ready for download.
[macOS build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-57fc3bf.dmg) is ready for download.
[Windows x64 build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-57fc3bf.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-57fc3bf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-57fc3bf.zip) is ready for download.
[macOS build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-57fc3bf.dmg) is ready for download.
[Windows x64 build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-57fc3bf.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (57fc3bf)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-57fc3bf.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4621)*

**Comment by PhotoNomad0** [comment]
:lgtm: - need to resolve conflict

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4621#-:-LFXfGdT99ntvHopU0ip:b6j466b)*

**Comment by PhotoNomad0** [comment]
@neutrinog ^^^

**Comment by da1nerd** [comment]
thanks @PhotoNomad0. conflicts resolved.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (5fcb7a8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-5fcb7a8.zip) is ready for download.
[macOS build 0.10.0 (5fcb7a8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-5fcb7a8.dmg) is ready for download.
[Windows x64 build 0.10.0 (5fcb7a8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-5fcb7a8.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (5fcb7a8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-5fcb7a8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (a9f224f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-a9f224f.zip) is ready for download.
[macOS build 0.10.0 (a9f224f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-a9f224f.dmg) is ready for download.
[Windows x64 build 0.10.0 (a9f224f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-a9f224f.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (a9f224f)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-a9f224f.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 5 files at r2, 1 of 2 files at r3, 2 of 3 files at r4, 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4621)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4621#-:-LFg4a7y8UFMlAYAOMVD:bnfp4nl)*

**Pull request merged**
