### PR TITLE
Translation Notes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR adds the tN Tool to tC

#### Please include detailed Test instructions for your pull request:
- Test tN and ensure you can do the same basic checking process as tW

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (dd1a225)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-linux-x64-1.2.0-dd1a225.deb) is ready for download.
[macOS build 1.2.0 (dd1a225)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-macos-x64-1.2.0-dd1a225.dmg) is ready for download.
[Windows x64 build 1.2.0 (dd1a225)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x64-1.2.0-dd1a225.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (dd1a225)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x32-1.2.0-dd1a225.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923#-LasmsWq2WA6duPX-asc:-LasmsWq2WA6duPX-asd:b-z2zcy7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dd1a225afdea6b7f7b7e589a2bb3adc265e006d6/src/js/reducers/projectDetailsReducer.js#L17)):*
> ```JavaScript
>     translationWords: ['kt', 'other', 'names'],
>     translationNotes: ['cultural', 
>                          'cultural-symAct', 'cultural-symLang', 'cultural-cultInfo', 'cultural-unknown', 'cultural-plicit',
> ```

is this dynamic?

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923)* status: 21 of 24 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923#-LasmsWq2WA6duPX-asc:-LatthLO3kpUpJdtjnc7:bh0fw77) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dd1a225afdea6b7f7b7e589a2bb3adc265e006d6/src/js/reducers/projectDetailsReducer.js#L17)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this dynamic?
</blockquote></details>

Good catch, it is actually legacy code. It is being dynamically made

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (dba298d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-linux-x64-1.2.0-dba298d.deb) is ready for download.
[macOS build 1.2.0 (dba298d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-macos-x64-1.2.0-dba298d.dmg) is ready for download.
[Windows x64 build 1.2.0 (dba298d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x64-1.2.0-dba298d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (dba298d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x32-1.2.0-dba298d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (753136d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-linux-x64-1.2.0-753136d.deb) is ready for download.
[macOS build 1.2.0 (753136d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-macos-x64-1.2.0-753136d.dmg) is ready for download.
[Windows x64 build 1.2.0 (753136d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x64-1.2.0-753136d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (753136d)](https://tc-builds.door43.org/build/feature-bspidel-5756-2/translationCore-win-x32-1.2.0-753136d.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5923)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
Github is still saying `This branch has conflicts that must be resolved`

**Comment by RoyalSix** [comment]
@mannycolon Not on mine
image

**Comment by mannycolon** [comment]
@RoyalSix Idk why it showed that before

**Pull request merged**
