### PR TITLE
Feature 3643/detect supported GLs

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- selectable Gateway languages on tool cards are now determined dynamically from languages in resource folder.

#### Please include detailed Test instructions for your pull request:
- depend on https://github.com/translationCoreApps/tC_Resources/pull/39
- select a Titus project should see both Hindi and  English as selectable languages (no Greek or Hebrew) on tool cards.
- select a non-Titus project should see only English as selectable language (no Hindi, Greek or Hebrew) on tool cards.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4210)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`
Edit: Your JavaScript has improved so much, very nice implementation! @PhotoNomad0

**Comment by RoyalSix** [comment]
Reviewed 16 of 20 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[__tests__/gatewayLanguageHelpers.test.js, line 235 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4210#-L9HTdqW146cxNM4t1c4:-L9HTdqXDXut3KScEgrt:b-mkvxmp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/600b1a01008037487ccd54ae52baf642ec764a2d/__tests__/gatewayLanguageHelpers.test.js#L235)):*
> ```JavaScript
>   const sourcePath = path.join(resourcePath_, sourceBook);
>   const destPath = path.join(resourcePath_, destBook);
>   fs.copySync(sourcePath, destPath);
> ```

Nice job writing these tests

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4210)*

**Comment by mannycolon** [comment]
Reviewed 16 of 20 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4210)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Is this story supposed to be part of 0.9 or 0.10 (next release)?

**Comment by RoyalSix** [comment]
Merge conflicts

**Pull request merged**
