### PR TITLE
Refactor - #3234 & #3228 - Online Import 

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Handles both the refactoring of issues #3234  and #3228  

#### How to test this pull request:

Will clone either a URL from git.door43.org or a URL from www.door43.org or live.door43.org as a git repo in the ~/translationCore/imports directory. 

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3318)

### CODE REVIEW

**Comment by mannycolon** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 29 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318#-L-DSK6L5UUJS1erJGP-:-L-DSK6L5UUJS1erJGP0:b-g0f22x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/509b075210c853d043ab238f4fefd51a95891e57/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L29)):*
> ```JavaScript
>       fs.ensureDirSync(savePath);
>     } else {
>       return reject("Project has already been imported.");
> ```

'Project has already been imported.'
is this the error message we want or do we want
```
 The project you selected ({projectName}) already exists.
          Reimporting existing projects is not currently supported.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318)*

**Comment by mannycolon** [comment]
Reviewed 1 of 13 files at r6.
Review status: 1 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318)*

**Comment by mannycolon** [comment]
Reviewed 9 of 13 files at r1, 1 of 3 files at r4, 4 of 13 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[__tests__/ImportMigrationHelpers.test.js, line 3 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318#-L-DSs2be41Z8HGKHfdI:-L-DSs2be41Z8HGKHfdJ:b-aqawd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/509b075210c853d043ab238f4fefd51a95891e57/__tests__/ImportMigrationHelpers.test.js#L3)):*
> ```JavaScript
> import path from 'path';
> import pathex from 'path-extra';
> import * as fs from 'fs-extra';
> ```

lets use this instead 
```
import fs from 'fs-extra';
```

---

*[tC_apps/ScripturePane, line 1 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318#-L-DTkgTIsQFZPTzbyyB:-L-DTkgTIsQFZPTzbyyC:b-e0iy68) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/509b075210c853d043ab238f4fefd51a95891e57/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit 919c5198c36ced48e6c3763e9ca3e61ed5050d59
> ```

should this be included?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318)*

**Comment by richmahn** [comment]
*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 29 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318#-L-DSK6L5UUJS1erJGP-:-L-DXBdOja_e8yPD8txg:bb2etiv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/509b075210c853d043ab238f4fefd51a95891e57/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L29)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

'Project has already been imported.'
is this the error message we want or do we want
```
 The project you selected ({projectName}) already exists.
          Reimporting existing projects is not currently supported.
```
</blockquote></details>

This error message is a bit tricky in that it is just saying the project has been imported (a directory with the project name exists) in the imports/ directory, but hasn't been moved to the projects directory yet. So should we display something about how an import was started but failed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3318)*

**Pull request closed without merging**
