### PR TITLE
Add version to welcome and splash

### PR DESCRIPTION
**Pull request by cdwhitfield73**
#### This pull request addresses:

fixes Issue #1454 and the fail on #963 

#### How to test this pull request:

Confirm version number shows up on splash screen and welcome page

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1467)

### CODE REVIEW

**Comment by cdwhitfield73** [comment]
Added a quick fix to this PR for the fail on issue #1283

**Comment by cdwhitfield73** [comment]
Added error handling to import to fix fails in issue #1384

**Comment by klappy** [comment]
@cdwhitfield73: For future PR's can we make smaller PR's for each task? It may be easier for the submitter to roll them up into one but it's a pain for the reviewer to track down all the tasks and switch contexts. It's also easier to track on the board, so that we have direct links from issue to PR. Having this one cover so many is not preferred. I'd rather merge 4 PR's than have 1 PR that addresses 4 issues. To make it easier to manage this time, I added a # before each issue number so that I could click on them instead of searching for each issue to know what it's suppose to do.

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1467#-:-KjPmQa3pDzymyi1bQ6C:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1467)*

**Pull request merged**
