### PR TITLE
Overhaul of importing functions

### PR DESCRIPTION
**Pull request by cdwhitfield73**
#### This pull request addresses:

Several fixes to importing projects, error handling, messages, cleanup, etc.  Addresses QA Fails in issues #1373, #1368, and #1384

#### How to test this pull request:

Import bad projects or bad URL's

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1492)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by ihoegen** [comment]
@cdwhitfield73 I'm pretty sure we want users to be logged in before even cloning a project from git. @klappy could I have some clarification on that?

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/actions/ImportOnlineActions.js, line 9 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfW8DfhWc--gszSMDb:-KjfW8DfhWc--gszSMDc:b-4og5wz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L9)):*
> ```JavaScript
> // constant declaration
> const loadOnline = require('../components/core/LoadOnline');
> var rimraf = require('rimraf');
> ```

you want to use ES6 for this

import rimraf from 'rimraf'

btw whats the usage for this module??

---

*[src/js/actions/ImportOnlineActions.js, line 45 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWK2S_uhKNMlAUvGu:-KjfWK2S_uhKNMlAUvGv:b-52nuit) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L45)):*
> ```JavaScript
> }
> 
> export function importOnlineProject(link) {
> ```

why are you making changes to this action??

---

*[src/js/actions/ImportOnlineActions.js, line 61 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWOZfNn_iXcHd5I2B:-KjfWOZfNn_iXcHd5I2C:b-nga41r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L61)):*
> ```JavaScript
> 
>                 try {
>                     rimraf(savePath, function () {});
> ```

could you explain whats happening here and maybe leave some comments as well

---

*[src/js/actions/ImportOnlineActions.js, line 71 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWVxIT5NCJvbQCBzw:-KjfWVxIT5NCJvbQCBzx:b1yxxlu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/actions/ImportOnlineActions.js#L71)):*
> ```JavaScript
> }
> /**
>  * @description loads/doanloads a project repo using a door43 link.
> ```

why did you delete this action??

---

*[src/js/components/core/OnlineInput.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWqlB9KY6PqdlRyfM:-KjfWqlB9KY6PqdlRyfN:b-ldike7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/components/core/OnlineInput.js#L24)):*
> ```JavaScript
>               onChange={onChange}
>             />
>             <div style={{width: "60px", display: "flex", justifyContent: "center"}}>
> ```

what did you do with the loading circle???
why did you remove it??????

---

*[src/js/containers/ImportOnlineContainer.js, line 19 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfXC_XbYAk-yH7samM:-KjfXC_XbYAk-yH7samN:b-unjje4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/containers/ImportOnlineContainer.js#L19)):*
> ```JavaScript
>             {projectName}
>             <Button bsStyle="prime"
>                     onClick={() => this.props.actions.openOnlineProject(repoName, this.props.importOnlineReducer.loggedIn)}>
> ```

we dont want users to open projects if they're not logged in

---

*[src/js/containers/ImportOnlineContainer.js, line 117 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfXTHDVQPGWiXgxioC:-KjfXTHDVQPGWiXgxioD:b-scex6p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/containers/ImportOnlineContainer.js#L117)):*
> ```JavaScript
>         if (!loggedInUser) {
>           dispatch(ModalActions.selectModalTab(1, 1, true));
>           dispatch(NotificationActions.showNotification("Please login before loading a project", 5));
> ```

we have stories asking for this. why are you removing it??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by RoyalSix** [comment]
Looks good Chris!

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-:-Kjfo4wP-ALGyFn4QrRR:b-dqc42s)*

**Comment by klappy** [comment]
*[src/js/actions/ImportOnlineActions.js, line 9 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfW8DfhWc--gszSMDb:-KjhY8ZJJh_NrcooZMZz:b-5ju0fh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L9)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you want to use ES6 for this

import rimraf from 'rimraf'

btw whats the usage for this module??
</blockquote></details>

He walked me through it yesterday. There is an issue with failed imports preventing the user from importing the same project after the issue is resolved. In the catch portion of the try/catch it removes the directory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[src/js/actions/ImportOnlineActions.js, line 9 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfW8DfhWc--gszSMDb:-KjhYSyKl0RYul_gTO3c:bw3pixf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L9)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

He walked me through it yesterday. There is an issue with failed imports preventing the user from importing the same project after the issue is resolved. In the catch portion of the try/catch it removes the directory.
</blockquote></details>

I didn't see this portion and think it should be updated to: 
`import rimraf from 'rimraf'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[src/js/actions/ImportOnlineActions.js, line 45 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWK2S_uhKNMlAUvGu:-KjhYn9bLjuFE-rsZPPB:bwaew7c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L45)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you making changes to this action??
</blockquote></details>

He also walked me through this one. There are two actions doing nearly the same thing so he abstracted the common code to this one. Import your projects and import URL should use the same logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[src/js/actions/ImportOnlineActions.js, line 71 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWVxIT5NCJvbQCBzw:-KjhZ4Lon6Xp3DmObeL7:bma25go) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/actions/ImportOnlineActions.js#L71)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you delete this action??
</blockquote></details>

It got abstracted and uses the same as the other action

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[src/js/components/core/OnlineInput.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWqlB9KY6PqdlRyfM:-KjhZKVwW9y9mTmhW0Qb:bjo88d5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/components/core/OnlineInput.js#L24)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what did you do with the loading circle???
why did you remove it??????
</blockquote></details>

I'm not sure why this one got removed either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[src/js/components/core/OnlineInput.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWqlB9KY6PqdlRyfM:-KjhZVJyBQ01sezYWmDg:b6mgehx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/components/core/OnlineInput.js#L24)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm not sure why this one got removed either.
</blockquote></details>

ah, loading circle got moved to projects.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
Reviewed 1 of 6 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r3.
Review status: 5 of 9 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by RoyalSix** [comment]
Review status: 5 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/actions/ImportOnlineActions.js, line 9 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfW8DfhWc--gszSMDb:-KjhdNELuOmfncECqT_d:bp4vh7q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L9)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I didn't see this portion and think it should be updated to: 
`import rimraf from 'rimraf'`
</blockquote></details>

You can remove directories with fs.remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by EllDoubleYew** [comment]
Reviewed 4 of 6 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/js/actions/ImportOnlineActions.js, line 61 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWOZfNn_iXcHd5I2B:-Kjhgts0vQUSd93apzey:b-54evdz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L61)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could you explain whats happening here and maybe leave some comments as well
</blockquote></details>

@mannycolon check https://www.npmjs.com/package/rimraf it is basically `rm -rf` for node.

---

*[src/js/actions/ImportOnlineActions.js, line 71 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWVxIT5NCJvbQCBzw:-Kjhh2CoPHYgpX4MvppF:b-mu8p9f) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/actions/ImportOnlineActions.js#L71)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

It got abstracted and uses the same as the other action
</blockquote></details>

^ Consolidated into one action now. I think its a good thing but if this causes any conflicts we should probably re-evaluate

---

*[src/js/components/core/login/Projects.js, line 16 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjhhJo56E1VQvX8cXAB:-KjhhJo56E1VQvX8cXAC:bokfdhr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6d7f069a9a5862d28e786964561906f056f1ab1b/src/js/components/core/login/Projects.js#L16)):*
> ```JavaScript
>                     <div style={{width: "60px", display: "flex", justifyContent: "center"}}>
>                         {showLoadingCircle ?
>                             (<CircularProgress size={30} thickness={4} color={"var(--accent-color-dark)"} />) : ""
> ```

Hey I found the loading circle! :)

---

*[tC_apps/translationWords, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-Kjhh_1mesOFDznnqkX-:-Kjhh_1mesOFDznnqkX0:b-76xoql) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6d7f069a9a5862d28e786964561906f056f1ab1b/tC_apps/translationWords#L1)):*
> ```
> Subproject commit 5808f7f695fcf06c3a8a0d635292231b96256851
> ```

Please remove tool commits from PRs. We have a script that handles this whenever a PR is completed in a tool repo!

---

*[tC_apps/VerseCheck, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjhhgFWzm1g2rg50-fV:-KjhhgFWzm1g2rg50-fW:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6d7f069a9a5862d28e786964561906f056f1ab1b/tC_apps/VerseCheck#L1)):*
> ```
> Subproject commit f31e902cf00b784187ff52fd53854b8ca4631758
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by mannycolon** [comment]
@klappy @cdwhitfield73 so do we want to remove the directory ??? I could be wrong. if we remove the directory aren't we also get rid of/overwriting data that may be in the project folder.

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/js/actions/ImportOnlineActions.js, line 9 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfW8DfhWc--gszSMDb:-Kjhm3tkllvHy9DUKNK1:bl4xcnt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L9)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

You can remove directories with fs.remove
</blockquote></details>

yeah i rather we use fs.remove. and also do we want to remove/delete the directory? what if there was project data there that we needed to keep??

---

*[src/js/actions/ImportOnlineActions.js, line 61 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWOZfNn_iXcHd5I2B:-KjhmNJVAkUVbB9sKIw2:b2o8kzo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4c31959193d439c388fb90b51f06fe5be23bdfd8/src/js/actions/ImportOnlineActions.js#L61)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

@mannycolon check https://www.npmjs.com/package/rimraf it is basically `rm -rf` for node.
</blockquote></details>

yeah i understand i can google it but i think comments are alway helpful

---

*[src/js/actions/ImportOnlineActions.js, line 71 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWVxIT5NCJvbQCBzw:-KjhmUqXFN0FQSFkIZfK:bg9yqts) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/actions/ImportOnlineActions.js#L71)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

^ Consolidated into one action now. I think its a good thing but if this causes any conflicts we should probably re-evaluate
</blockquote></details>

yeah i realize that

---

*[src/js/components/core/OnlineInput.js, line 24 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfWqlB9KY6PqdlRyfM:-KjhmZat6suDW23DnlhF:bb7f2mf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/components/core/OnlineInput.js#L24)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

ah, loading circle got moved to projects.js
</blockquote></details>

done

---

*[src/js/containers/ImportOnlineContainer.js, line 19 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfXC_XbYAk-yH7samM:-KjhlfyhwxzWkz56YHC4:btgtcgq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/containers/ImportOnlineContainer.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont want users to open projects if they're not logged in
</blockquote></details>

after testing seems to be ok.

---

*[src/js/containers/ImportOnlineContainer.js, line 117 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-KjfXTHDVQPGWiXgxioC:-Kjhlkl1KRBEKEIZlc5x:b-8vf7ka) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c374742e3d14187cdc83565e9fa3bf72bce6d41a/src/js/containers/ImportOnlineContainer.js#L117)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we have stories asking for this. why are you removing it??
</blockquote></details>

after further review realized it was moved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[tC_apps/translationWords, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-Kjhh_1mesOFDznnqkX-:-KjhnKXxNS_aqC6tDXeY:b-25c997) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6d7f069a9a5862d28e786964561906f056f1ab1b/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary><blockquote>

Please remove tool commits from PRs. We have a script that handles this whenever a PR is completed in a tool repo!
</blockquote></details>

sorry that was me
when I merged develop in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Comment by klappy** [comment]
*[tC_apps/translationWords, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492#-Kjhh_1mesOFDznnqkX-:-KjhoV--eozk4NrluytM:bbvwcud) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6d7f069a9a5862d28e786964561906f056f1ab1b/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

sorry that was me
when I merged develop in.
</blockquote></details>

actually that wasn't me and I don't want to revert back 3 commits to undo it.
Since it's apart of the history, it should be fine in the merge moving forward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1492)*

**Pull request closed without merging**
