### PR TITLE
Change the non-English ULT back to ULB (In this case Hindi ULT back to ULB)

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Change the non-English ULT back to ULB (In this case Hindi ULT back to ULB)

#### Please include detailed Test instructions for your pull request:
- **Dependencies:**
  https://github.com/translationCoreApps/tC_Resources/pull/40
  https://github.com/translationCoreApps/translationWords/pull/122
  https://github.com/translationCoreApps/ScripturePane/pull/116
- **PLEASE WHEN YOU MERGE THIS PR DO NOT DELETE THE BRANCHES AS I WILL MAKE ANOTHER PR FOR `release-v0.9.0`**
- Open a project with English as a GL. 
- Add English to the scripture pane if it's not already there.
- Then switch the GL language to Hindi. 
- The English ULT should be replaced by the Hindi ULB.
- The Hindi bible should say ULB instead of ULT and its description should be Unlock Literal Bible.
- Delete or remove all the bibles from the scripture pane. Then load the project again with tW and select English as the GL 
(Now the scripture pane should include ENGLISH ULT AND THE TARGET LANGUAGE BIBLE)
- Remove all the bibles from the scripture pane again and load tW with Hindi as the GL 
(Now the scripture pane should include HINDI ULB AND THE TARGET LANGUAGE BIBLE)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4236)

### CODE REVIEW

**Comment by RoyalSix** [comment]
`runGitCommands() { git checkout enhancement-mannycolon-4140 && git pull; }; runGitCommands; cd tC_apps/ScripturePane; runGitCommands;  cd ../translationWords; runGitCommands; cd ../../tC_resources; runGitCommands; cd ../;`

**Comment by RoyalSix** [comment]
@mannycolon How do I test this?

**Comment by mannycolon** [comment]
@RoyalSix Sorry completely forgot to leave testing instructions. let me add them now.

**Comment by RoyalSix** [comment]
Local Testing: Nothing looks wrong, not sure exactly what to test
Code Review: `LGTM`

**Comment by mannycolon** [comment]
@RoyalSix I just added testing instructions. BTW if you dont merge. dont forget to delete your settings.json file

**Comment by RoyalSix** [comment]
@mannycolon Thanks for reminder, testing right now

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Note: I think one more reviewer on this would be good, because it touches so much stuff

**Comment by mannycolon** [comment]
@RoyalSix Thanks Jay

**Comment by bspidel** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4236#-:-L9Iow2e-rihfbW53zyX:bg7igkv)*

**Pull request merged**
