### PR TITLE
Feature mcleanb #3186/use verse objects

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Update to be compatible with verse objects and change strongs to strong.

#### How to test this pull request:

First pull in Dependencies:
https://github.com/translationCoreApps/ScripturePane/pull/85
https://github.com/translationCoreApps/word-alignment-tool/pull/19

`npm i`

Should see greek punctuation in scripture pane, greek pop ups should work, drag and drop should work.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3738)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
*[src/js/actions/ResourcesActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738#-L4NWiDkpdNnjb0WaQi8:-L4NWiDkpdNnjb0WaQi9:bn6ogwv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5f261bbf7d33196449936d0dce3748dc9cd49957/src/js/actions/ResourcesActions.js#L31)):*
> ```JavaScript
>  * @description copy words out of verse array into words array
>  * @param {array} verse
>  * @param {array} words
> ```

Do you mind adding documentation to describe what the output will be? I know it's in the code but would be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
*[src/js/actions/ResourcesActions.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738#-L4NX3qvMylDryd28fBi:-L4NX3qvMylDryd28fBj:b-7ovcy3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5f261bbf7d33196449936d0dce3748dc9cd49957/src/js/actions/ResourcesActions.js#L37)):*
> ```JavaScript
>     if (object) {
>       if (object.type === 'word') {
>         object.strongs = object.strong; //TODO: remove later, current tools use strongs
> ```

Which tool still uses strongs? should we keep working until we update the references including adding it to the migrations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ResourcesActions.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738#-L4NX3qvMylDryd28fBi:-L4QUXU9ASu6OBaTZisf:b-3r350o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5f261bbf7d33196449936d0dce3748dc9cd49957/src/js/actions/ResourcesActions.js#L37)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Which tool still uses strongs? should we keep working until we update the references including adding it to the migrations?
</blockquote></details>

Oops, forgot to take this out.  Thanks for catching this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ResourcesActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738#-L4NWiDkpdNnjb0WaQi8:-L4QVWyDjZgKWlI-xR6F:b2m4qtg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5f261bbf7d33196449936d0dce3748dc9cd49957/src/js/actions/ResourcesActions.js#L31)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do you mind adding documentation to describe what the output will be? I know it's in the code but would be useful.
</blockquote></details>

Good idea, probably shouldn't have this here anyway.  This was here because UGNT has nested milestones, but scripture pane and wa worked with a list of words.  But this strips out the milestone attributes which will be needed in future.  Think I will rename this to get word list move this into VerseObjectHelpers.  Then can pass this function into the apps.

---

*[src/js/actions/ResourcesActions.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738#-L4NX3qvMylDryd28fBi:-L4QX0_toi5Fa9WWX2Up:b-99omrm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5f261bbf7d33196449936d0dce3748dc9cd49957/src/js/actions/ResourcesActions.js#L37)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Oops, forgot to take this out.  Thanks for catching this.
</blockquote></details>

On second look, It looks like I forgot to push up the strongs to strong fix for the app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 1 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 2 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 2 of 9 files at r2.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3738)*

**Pull request merged**
