### PR TITLE
Now invalidating checks when editing verses in the wordAlignment tool

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Now invalidating checks when editing verses in the wordAlignment tool

#### Please include detailed Test instructions for your pull request:
[en_tit 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1976059/en_tit.2.zip)
1. Open project in tW
2. Select 'an apostle' for the apostle check in 1:1
3. Switch to the alignment tool
4. Edit 1:1 to change 'an apostle' to 'a apostle' (delete the 'n' in 'an')
5. Click the tool icon to go to the tools page

**The tW card should now show that a check has been invalidated**

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4536)

### CODE REVIEW

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by RoyalSix** [comment]
I did something weird and I'm not sure of the expected behavior.
1. Open project in tW
2. Select 'a servant' and 'an apostle' for the apostle check in 1:1
3. Switch to the alignment tool
4. Edit 1:1 to change `an apostle` to `a apostle` and change `a servant` to `an servant`
The wA tool shows the resetting error but noting gets changed.
@benjore @cckozie 
So my question is what should happen if a user switches two words in the TL? i.e. `a` and `an`

Just tying to test more thoroughly than usual.

**Comment by cckozie** [comment]
@RoyalSix - It may be that the work @neutrinog is doing on #4429 is the cause of this unexpected behavior. I added 3 scenarios that were not working correctly to that issue, and I'll add this one too. (I like the more thorough testing!)

**Comment by mannycolon** [comment]
@RoyalSix The issues you found seem to be unrelated to the scope of my story. Should those new issues be addressed somewhere else?

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by da1nerd** [comment]
Some builds failed

**Comment by RoyalSix** [comment]
@mannycolon I think that is a question for @benjore
I will continue testing until then

**Comment by mannycolon** [comment]
@RoyalSix Did you read what @cckozie wrote. I thought he said that those bugs you found are accounted for in another issue/story?

BTW did you test if those bugs you found are happening in develop?

**Comment by RoyalSix** [comment]
@mannycolon Ok. I see. I will finish reviewing

**Comment by mannycolon** [comment]
@RoyalSix I think @PhotoNomad0 was going to finish reviewing

**Comment by RoyalSix** [comment]
Ok

**Comment by da1nerd** [comment]
Some builds failed

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/js/actions/SelectionsActions.js, line 102 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4536#-LDqCll365y-nAnSHm4Q:-LDqCll365y-nAnSHm4R:bt2q2gn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4591bc5a3f95a95d38ce84594bdbc445444a4a0e/src/js/actions/SelectionsActions.js#L102)):*
> ```JavaScript
>       const { projectSaveLocation, manifest: { project } } = state.projectDetailsReducer;
>       const bibleId = project.id;
>       const selectionsPath = path.join(projectSaveLocation, '.apps', 'translationCore', 'checkData', 'selections', bibleId, chapter.toString(), verse.toString());
> ```

FYI - this is overkill.  path.join normalizes separators for operating system.  You could just do '.apps/translationCore/checkData/selections'.  We verified that this works on Windows also.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4536)*

**Comment by PhotoNomad0** [comment]
**LTGM**

**Pull request merged**
