### PR TITLE
Re-enable redux-logger functionality & made console logger only work on production builds 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Checkout bugfix-mannycolon-6830
- Open tC 
- Make sure you see redux-logger working without crashing in the console
- Open all 3 tools and make sure they work correctly and their respective actions are properly logged in the console

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6851)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6851)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6851)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[electron/index.js, line 105 at r1](https://reviewable.io/reviews/unfoldingword/translationcore/6851#-M51UX0aDQjnr0PER24j:-M51UX0aDQjnr0PER24k:b-sjj35) ([raw file](https://github.com/unfoldingword/translationcore/blob/b933c718a9f862a25ba1526e78c00326c02e1bc2/electron/index.js#L105)):*
> ```JavaScript
> 
>       [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS].forEach(extension => {
>         installExtension(extension)
> ```

Sorry, I should have removed this comment, but dev tools are already installed (see https://github.com/unfoldingWord/translationCore/blob/bugfix-mannycolon-6830/electron/electronWindows.js#L106).  Maybe you should just add the REDUX_DEVTOOLS there.

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6851)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[electron/index.js, line 105 at r1](https://reviewable.io/reviews/unfoldingword/translationcore/6851#-M51UX0aDQjnr0PER24j:-M52CEqhDFgFNdlctjm_:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/b933c718a9f862a25ba1526e78c00326c02e1bc2/electron/index.js#L105)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Sorry, I should have removed this comment, but dev tools are already installed (see https://github.com/unfoldingWord/translationCore/blob/bugfix-mannycolon-6830/electron/electronWindows.js#L106).  Maybe you should just add the REDUX_DEVTOOLS there.
</blockquote></details>

Done.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6851)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
