### PR TITLE
Refactored some of the project selection code

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This is related to #4672 and #4915
- This cleans up a few things and sets the stage for further refactoring of the project selection to also include project loading.

- [x] @PhotoNomad0 has a PR https://github.com/unfoldingWord-dev/translationCore/pull/4896 that should probably be merged in before this.

#### Please include detailed Test instructions for your pull request:
- This just contains some code refactoring. Make sure tests pass and the project selection continues to work as it has.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (057519d)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-057519d.zip) is ready for download.
[macOS build 1.0.0 (057519d)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-057519d.dmg) is ready for download.
[Windows x64 build 1.0.0 (057519d)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-057519d.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (057519d)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-057519d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (c739036)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-c739036.zip) is ready for download.
[macOS build 1.0.0 (c739036)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-c739036.dmg) is ready for download.
[Windows x64 build 1.0.0 (c739036)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-c739036.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (c739036)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-c739036.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (96b5658)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-96b5658.zip) is ready for download.
[macOS build 1.0.0 (96b5658)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-96b5658.dmg) is ready for download.
[Windows x64 build 1.0.0 (96b5658)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-96b5658.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (96b5658)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-96b5658.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (632ccb1)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-632ccb1.zip) is ready for download.
[macOS build 1.0.0 (632ccb1)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-632ccb1.dmg) is ready for download.
[Windows x64 build 1.0.0 (632ccb1)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-632ccb1.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (632ccb1)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-632ccb1.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Please create an issue and attach it to this PR @neutrinog

**Comment by da1nerd** [comment]
@mannycolon issue attached.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 29 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898)* status: 7 of 28 files reviewed, 2 unresolved discussions (waiting on @neutrinog)

___
*[__tests__/__snapshots__/MyProjects.test.js.snap, line 7 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898#-LKX4AkM71C6FL8YY9g1:-LKX4AkM71C6FL8YY9g2:b-qtlj0t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/632ccb1667379283468b12758d6ba3ac34d6ec63/__tests__/__snapshots__/MyProjects.test.js.snap#L7)):*
> ```
>   "length": 1,
>   Symbol(enzyme.__root__): [Circular],
>   Symbol(enzyme.__unrendered__): <MyProjects
> ```

Don't think this snapshot will alert us to inadvertent layout changes
___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 32 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898#-LKX53fBDzfnQ5OUtUyL:-LKX53fBDzfnQ5OUtUyM:b-4031u4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/632ccb1667379283468b12758d6ba3ac34d6ec63/src/js/actions/MyProjects/ProjectLoadingActions.js#L32)):*
> ```JavaScript
>  */
> export const openProject = (name) => {
>   return async (dispatch, getState) => {
> ```

Need to think about this change.  Trying to understand if it offers the same protections against side-loaded projects as well as version upgrades.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898)* status: 7 of 28 files reviewed, 2 unresolved discussions (waiting on @neutrinog)

___
*[__tests__/__snapshots__/MyProjects.test.js.snap, line 7 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898#-LKX4AkM71C6FL8YY9g1:-LKZq-YYAiCZCEO8mOFm:b-7lj87b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/632ccb1667379283468b12758d6ba3ac34d6ec63/__tests__/__snapshots__/MyProjects.test.js.snap#L7)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Don't think this snapshot will alert us to inadvertent layout changes
</blockquote></details>

oops!
___
*[src/js/actions/MyProjects/ProjectLoadingActions.js, line 32 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898#-LKX53fBDzfnQ5OUtUyL:-LKZpPXPBlKZfKXh_6fY:bp78f6t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/632ccb1667379283468b12758d6ba3ac34d6ec63/src/js/actions/MyProjects/ProjectLoadingActions.js#L32)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to think about this change.  Trying to understand if it offers the same protections against side-loaded projects as well as version upgrades.
</blockquote></details>

This function is functionally equivalent to to `migrateValidateLoadProject`. I just renamed it and cleaned up some variable usage.
This is where I'll be adding extra code to load the entire project when it's selected.  In the mean time `migrateValidateLoadProject` will stick around and continue to be used until we can safely switch everything over to this method.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 29 files at r1, 2 of 2 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898)* status: all files reviewed, 3 unresolved discussions (waiting on @PhotoNomad0 and @neutrinog)

___
*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 248 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4898#-LKapcF84zzvyarQduul:-LKapcF920be-a5YGGqu:by6k3ov) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/632ccb1667379283468b12758d6ba3ac34d6ec63/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L248)):*
> ```JavaScript
>   // return new Promise((resolve, reject) => {
>   //   const manifest = getProjectManifest(projectPath);
>   //
> ```

Probably don't want to keep these comments

**Comment by PhotoNomad0** [comment]
@neutrinog - with all the refactoring.  It looks like we need to do some import testing.

**Comment by da1nerd** [comment]
I didn't expect you to merge this in until I fixed some things. I'll fix that snapshot and clean up that commented code in a new PR.

**Pull request merged**
