### PR TITLE
Feature 5204/OT support any unlocked book for tW tool

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Allow tW to open OT books with marked tW words and Original Language Alignments

#### Please include detailed Test instructions for your pull request:
- make sure developer mode is OFF
- currently no OT books have alignments in the OL, so delete `resources/⁨en⁩/⁨bibles⁩/⁨ult⁩/⁨v1⁩/rut` and unzip this into `resources/⁨en⁩/⁨bibles⁩/⁨ult⁩/⁨v1⁩`: [rut.zip](https://github.com/unfoldingWord-dev/translationCore/files/2855614/rut.zip).  This will add alignment for Ruth 1:1 in en
- import this file to create a new Ruth project:  [08-RUT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2841692/08-RUT.usfm.zip)
- open this project in TW and should only see one check for `famine` since that is the only word in the OT that is currently marked.  Select `a famine` and do save.
- now open in WA and should see a suggestion for `a famine` in Ruth 1:1

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5763)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (78c8fa2)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-linux-x64-1.1.0-78c8fa2.deb) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (78c8fa2)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-linux-x64-1.1.0-78c8fa2.deb) is ready for download.
[macOS build 1.1.0 (78c8fa2)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-macos-x64-1.1.0-78c8fa2.dmg) is ready for download.
[Windows x64 build 1.1.0 (78c8fa2)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-win-x64-1.1.0-78c8fa2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (78c8fa2)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-win-x32-1.1.0-78c8fa2.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
screen shot 2019-02-11 at 11 13 05 am
With developer mode disabled

**Comment by PhotoNomad0** [comment]
It's strange that when I test the build, it is working for me:

screen shot 2019-02-12 at 6 34 21 am

Oh, it looks like I sent the wrong resource file...needed to sent the gateway resource instead of the Original Language.  Will update test steps.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (9f83605)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-linux-x64-1.2.0-9f83605.deb) is ready for download.
[macOS build 1.2.0 (9f83605)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-macos-x64-1.2.0-9f83605.dmg) is ready for download.
[Windows x64 build 1.2.0 (9f83605)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-win-x64-1.2.0-9f83605.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (9f83605)](https://tc-builds.door43.org/build/feature-mcleanb-5204/translationCore-win-x32-1.2.0-9f83605.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Pull request merged**
