### PR TITLE
Bugfix - #3968 - Makes it so an error doesn't occur when no aligned data and moving Word List word around

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes an error in the console when in wA you have no aligned data and grab a word from the word list and move it around into the alignment area but don't drop it and then move it back to the word list. It gets all confused. I noticed this when working with #3968 and don't want to be accused of this bug!

#### Please include detailed Test instructions for your pull request:
- Open the app, go into wA, open the console, go to a verse that doesn't have any alignment data, grab a word from the word list and move it around but do NOT drop it in an alignment space. Drop it back in the word list. Shouldn't see any errors now.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4123)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`
expect for testing in negative

**Comment by mannycolon** [comment]
@richmahn Please Address the unit test coverage on this PR.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4123#-:-L8K0rz41OL9bUWEDJn2:bnfp4nl)*

**Comment by mannycolon** [comment]
Local Testing: `LGTM`
Code Review: `LGTM`

**Comment by richmahn** [comment]
@mannycolon  this should have still been "In Progress" when you reviewed it, but of course not much changed. I did have it on my to-do list to write tests and got those in. Now status is in-review

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4123)*

**Comment by mannycolon** [comment]
**Dependencies:**
https://github.com/translationCoreApps/wordAlignment/pull/30

@richmahn  
Please make it a habit of including dependencies

**Comment by mannycolon** [comment]
Local Testing: `LGTM`
Code Review: `PENDING REQUESTED CHANGES ON https://github.com/translationCoreApps/wordAlignment/pull/30`

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4123#-:-L8bDPGu2DZve7Bm-zaT:bnfp4nl)*

**Pull request merged**
