### PR TITLE
Added welcome splash and re-work the structure and order of rendering containers

### PR DESCRIPTION
**Pull request by mannycolon**
### This pull request addresses:

added welcome screen as main/base screen.
#1345

### How to test this pull request:

- open app welcome screen should show.
- click get started then modal should open at user tab and if you click away or close the modal the welcome screen should render behind.
- try switching tools.
- try switching projects. (which should render the welcome screen again with the modal because the tools data is cleared when switching projects)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1420)

### CODE REVIEW

**Comment by mannycolon** [comment]
@EllDoubleYew @RoyalSix when you guys get a chance please review my PR

**Comment by RoyalSix** [comment]
Reviewed 1 of 48 files at r1.
Review status: 1 of 48 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1420)*

**Comment by RoyalSix** [comment]
The functionality of the splash screen works as expected, the new stepper files obviously are not finished yet. Im guessing these will be fixed as we continue working on the stepper. Going to merge.

---

Reviewed 47 of 48 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1420#-:-KjJCXXagbHRUd9hbriF:bejwn2x)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1420#-:-KjJDH_4TxoUtAuIwPld:bnfp4nl)*

**Pull request merged**
