### PR TITLE
Door 43 Projects on Load Menu

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/237)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/237)_

**Comment by mannycolon** [comment]
@ihoegen How can I test your branch???

**Comment by ihoegen** [comment]
@mannycolon Login, and go to load projects

**Comment by mannycolon** [comment]
@ihoegen so maybe when the user clicks `load project` from door 43 it should close the modal just like the `load` button

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/237)_

**Comment by mannycolon** [comment]
@ihoegen so did you get to add the code to satisfied what was suggested??

**Comment by ihoegen** [comment]
@mannycolon Good to go

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/237#-:-KUsRspwPPXTevRJDeKX:bnfp4nl)_

**Comment by mannycolon** [comment]
@ihoegen did you make it close the modal on load project??

**Comment by ihoegen** [comment]
@mannycolon I'm having trouble closing the modal because a state is being
changed upon closing.

**Pull request merged**
