### PR TITLE
Enhancement/joel/localization/2003

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This adds localization support to the application.
Fixes (or deprecates) #2266, #2267, #2270.

This sets the stage for #2265.

* I've localized a few strings on the overview page for testing and illustration purposes.
* Users can change the app locale from the user card on the overview page.
* Updates to the English locale are automatically uploaded to Crowdin when merging into Github.

> For now localized strings will be manually added. Later we could sync those while merging as well.

In addition to the locale feature I also tweaked travis so we're not running any of the builds scripts for Pull Requests since:
1. we can't use those builds anyway (no environment keys available)
2. it slows down CI for PRs.

Now travis will finish in about 2 minutes instead of 20 minutes. Woot!

#### How to test this pull request:

Run the app and try selecting a different locale from the overview screen.

> Note: the instructions on the overview screen won't update with the chosen locale until you restart the app. This will require re-engineering how the overview instructions are updated first.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3684)

### CODE REVIEW

**Comment by da1nerd** [comment]
After this is merged into the codebase we'll begin extracting the rest of the strings. That will touch a LOT of files however, and will require rewriting some components so we'll take it in stages to keep merge conflicts to a minimum.

**Comment by da1nerd** [comment]
codecov doesn't like class decorators :(
looking for a solution.

> Edit: I'm just removing the class decorators for now. sadness.

**Comment by da1nerd** [comment]
## There's a lot of noisy commits in this PR. please perform a **squash** when this is merged in.

**Comment by mannycolon** [comment]
Reviewed 10 of 57 files at r1, 3 of 12 files at r2, 8 of 9 files at r4.
Review status: 21 of 68 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
Ok! finally finished updating tests and docs. Also coverage is no longer decreasing.

**Comment by richmahn** [comment]
Changing language looks good; able to localize a string; removing a string for the localization file shows proper error message in app. :lgtm:

---

Reviewed 8 of 57 files at r1, 3 of 12 files at r2, 5 of 10 files at r4, 9 of 14 files at r5.
Review status: 24 of 71 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-:-L3kowSxB-IoiOG65maZ:b1cpuv6)*

**Comment by richmahn** [comment]
Reviewed 5 of 57 files at r1, 2 of 3 files at r3, 4 of 14 files at r5.
Review status: 35 of 71 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by RoyalSix** [comment]
Reviewed 30 of 57 files at r1, 1 of 12 files at r2, 5 of 14 files at r5.
Review status: 66 of 71 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_apps/ScripturePane, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nWoqiqwtppkARPcB7:-L3nWoqiqwtppkARPcB8:bllvxz4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2a042e6d68ffd5e2f79530b7f90fd06de44153/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit 1b89f2219a97a53a7204c7d2d4088440a9149fb6
> ```

Accidental?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by RoyalSix** [comment]
Review status: 66 of 71 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/LocaleActions.js, line 42 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3n_PWLGznMX0aArUch:-L3n_PWLGznMX0aArUci:br3zimf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L42)):*
> ```JavaScript
>   return {
>     ...translation,
>     '_': {
> ```

Interesting using hyphen as a key :thinking: 

---

*[src/js/actions/LocaleActions.js, line 113 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nZqCAgEyxzYMOTGhJ:-L3nZqCAgEyxzYMOTGhK:b-7ypnl4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L113)):*
> ```JavaScript
>         const localeFile = path.join(localeDir, file);
>         try {
>           let translation = JSON.parse(fs.readFileSync(localeFile));
> ```

Same implementation as line 35 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[tC_apps/ScripturePane, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nWoqiqwtppkARPcB7:-L3ng4kTJmOjKZsWL4sd:baswqmt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2a042e6d68ffd5e2f79530b7f90fd06de44153/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Accidental?
</blockquote></details>

Always. lol. I should configure my local repo to automatically call `npm run load-apps` any time I change branches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[src/js/actions/LocaleActions.js, line 42 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3n_PWLGznMX0aArUch:-L3ngLfNqdWLBWBhf4nQ:bn0cw6d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L42)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Interesting using hyphen as a key :thinking: 
</blockquote></details>

to avoid  collisions with actual translations. the `_` namespace contains strings that are not translated. Those are injected when the translations are loaded from the disk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[src/js/actions/LocaleActions.js, line 113 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nZqCAgEyxzYMOTGhJ:-L3ngnKkAqLzXNCnwGDO:bfs35bf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L113)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Same implementation as line 35 ?
</blockquote></details>

I'm not sure what you mean. Line 35 is the `enhanceTranslation` function (this injects the non-translatable strings).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[src/js/actions/LocaleActions.js, line 113 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nZqCAgEyxzYMOTGhJ:-L3nhBdJd7yEGavuiQzG:b-5m81x7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L113)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

I'm not sure what you mean. Line 35 is the `enhanceTranslation` function (this injects the non-translatable strings).
</blockquote></details>

oh ha! I must be blind :) It is mildly redundant. I was conflicted between wanting to keep `enhanceTranslation` simple vs reducing string manipulation.  The code there was so simple I decided to keep the function simple. I'm not apposed to changing it though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by RoyalSix** [comment]
Review status: 65 of 70 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/LocaleActions.js, line 42 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3n_PWLGznMX0aArUch:-L3nmFJTRwM0IstB8wZ_:b-4ylkjl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L42)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

to avoid  collisions with actual translations. the `_` namespace contains strings that are not translated. Those are injected when the translations are loaded from the disk.
</blockquote></details>

Oh ok nice

---

*[src/js/actions/LocaleActions.js, line 113 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nZqCAgEyxzYMOTGhJ:-L3nmPZVUOuzJa-nseIk:bjkrxs8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L113)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

oh ha! I must be blind :) It is mildly redundant. I was conflicted between wanting to keep `enhanceTranslation` simple vs reducing string manipulation.  The code there was so simple I decided to keep the function simple. I'm not apposed to changing it though.
</blockquote></details>

Ohhh I see. All good

---

*[tC_apps/ScripturePane, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nWoqiqwtppkARPcB7:-L3nm0Dd-pfvZiYV1-Rb:b-3svvmt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2a042e6d68ffd5e2f79530b7f90fd06de44153/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Always. lol. I should configure my local repo to automatically call `npm run load-apps` any time I change branches.
</blockquote></details>

Haha no worries. Did you updated it? You could fix with first command here https://gist.github.com/RoyalSix/f5953ebd77979002b678b50fa1b7edc9

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[src/js/actions/LocaleActions.js, line 113 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nZqCAgEyxzYMOTGhJ:-L3nmQ8I4QUbzbPPcUzF:b-byfje2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4a66d50db3b578c979bf292c21e83f65edb98782/src/js/actions/LocaleActions.js#L113)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ohhh I see. All good
</blockquote></details>

I went ahead and abstracted this out. It's still mildly redundant because we're still parsing the string twice, but it serves to keep things loosely coupled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
*[tC_apps/ScripturePane, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nWoqiqwtppkARPcB7:-L3nn4ia6oRgZmu4Kj2z:bsdqe5g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2a042e6d68ffd5e2f79530b7f90fd06de44153/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Haha no worries. Did you updated it? You could fix with first command here https://gist.github.com/RoyalSix/f5953ebd77979002b678b50fa1b7edc9
</blockquote></details>

yes I did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
I just realized you can store up all your comments on reviewable and publish them all at once. lol

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r6.
Review status: 65 of 70 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_apps/ScripturePane, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3nWoqiqwtppkARPcB7:-L3npjPm-PfVPRMC1Ou-:b76quyw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3a2a042e6d68ffd5e2f79530b7f90fd06de44153/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

yes I did.
</blockquote></details>

Lol I meant like all the submodules have a different commit. Sorry didn't make that clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by RoyalSix** [comment]
Reviewed 13 of 57 files at r1, 7 of 12 files at r2, 2 of 3 files at r3, 5 of 10 files at r4, 8 of 14 files at r5, 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 23 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3vY3yFNkdeStequpIU:-L3vY3yFNkdeStequpIV:bgeqxvj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e499eb8f31333fe35fcc33a47f96e3d6cc8d35f6/src/js/pages/app.js#L23)):*
> ```JavaScript
> import * as OnlineModeActions from '../actions/OnlineModeActions';
> import * as MigrationActions from '../actions/MigrationActions';
> import { loadLocalization, APP_LOCALE_SETTING } from '../actions/LocaleActions';
> ```

APP_LOCALE_SETTING is a const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 23 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-L3vY3yFNkdeStequpIU:-L3vlB52-PQQbAAqNN7r:bv1yerp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e499eb8f31333fe35fcc33a47f96e3d6cc8d35f6/src/js/pages/app.js#L23)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

APP_LOCALE_SETTING is a const?
</blockquote></details>

Yes, because that's the key for setting/retrieving the user's chosen locale. So when the app is restarted the user has the same locale loaded. Making the key a const and exporting it from LocaleActions ensures the key isn't accidentally miss-typed when used elsewhere in the app, and makes changing the key later (if necessary) a one line change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by da1nerd** [comment]
bump

**Comment by RoyalSix** [comment]
Reviewed 6 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 57 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3684#-:-L46hH51C2YbAQRCv6mO:bnfp4nl)*

**Pull request merged**
