### PR TITLE
Show all words in Menu from the tW article title #699

### PR DESCRIPTION
**Pull request by mannycolon**
**In order to test this PR you need to follow the next steps:**

- Make sure you have the latest versions of tN, iW and scripture pane.
- Load in a fresh project (This PR changes how we handle the =data structure so an old project won't work well with this PR)

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/717)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/717)*

**Comment by mannycolon** [comment]
@ihoegen @RoyalSix Can any of you test this branch please???

**Comment by ihoegen** [comment]
@mannycolon Testing now

**Comment by ihoegen** [comment]
@mannycolon Looks good to me

**Pull request merged**
