### PR TITLE
Add merge conflict checking for project chunks

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This PR addresses #1586. It looks for merge conflict markers in the verse chunk files, and if one is found, it quits loading, and clears data.

#### How to test this pull request:
 
Try loading a project with merge conflict markers: "<<<<<<<" is what starts a marker, and is the only thing being sought. Try loading a project that does not have these markers.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1599)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 137 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-KkO7_3w_IsjTrS-7xl_:-KkO7_3xS-Q-TCrepq3Z:bkbx5vy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e0a3b4c05f5a1c9fd4fffcb21325c679d4789b26/src/js/actions/GetDataActions.js#L137)):*
> ```JavaScript
>             let manifest = LoadHelpers.loadFile(projectPath, 'manifest.json');
>             manifest = LoadHelpers.verifyChunks(projectPath, manifest);
>             let conflictsFound = LoadHelpers.findMergeConflicts(manifest.finished_chunks, projectPath);
> ```

I have a few projects that don't have any finished chunks but still supported in tC.

If you loop through the fs for all /\d+/ folders and /\d+.txt/ files, that might let you get all chunk files, since there are others that are commonly in there.

What other approaches might not require using the finished chunks list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Comment by ihoegen** [comment]
This finished chunks list is the one that is generated by the verify chunks
method, so it reads the folders and figures out what's a finished chunk
before sending it to the conflicts detection method

**Comment by klappy** [comment]
Ah! That sounds promising. I'll try creating chunk conflicts with git by branching a couple times and merging after I edit the same line.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-:-KkOG70GqzaPG3C7Un8a:bm2rn3e)*

**Comment by mannycolon** [comment]
@klappy @ihoegen I have concerns about this PR. as I mentioned in the meeting on Tuesday Im working with GetDataActions.js, therefore, this PR is going to have major merge conflicts with my work. That's why I said to hold on this issue.

**Comment by mannycolon** [comment]
I would suggest mergin my PR first then adding this changes after my PR is merged since this PR is smaller.

**Comment by klappy** [comment]
That shouldn't be a problem. That's what I was expecting. He does have a working version of this that we can just adapt once your PR is merged. Depending on timing, if you PR is going to be a while before it can be merged we may have to reverse the order.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-:-KkQXxkSOyAx7lrTfqH7:b-oe5c8e)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 137 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-KkO7_3w_IsjTrS-7xl_:-KkQZWFDyhf1fqsTh5aA:b-o94rof) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e0a3b4c05f5a1c9fd4fffcb21325c679d4789b26/src/js/actions/GetDataActions.js#L137)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I have a few projects that don't have any finished chunks but still supported in tC.

If you loop through the fs for all /\d+/ folders and /\d+.txt/ files, that might let you get all chunk files, since there are others that are commonly in there.

What other approaches might not require using the finished chunks list?
</blockquote></details>

Good job, confirmed to work (alert and project open) on a merge conflict and no finished chunks in manifest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Comment by klappy** [comment]
*[src/js/actions/GetDataActions.js, line 137 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-KkO7_3w_IsjTrS-7xl_:-KkQZlqx--1LLJ-p4fTH:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e0a3b4c05f5a1c9fd4fffcb21325c679d4789b26/src/js/actions/GetDataActions.js#L137)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good job, confirmed to work (alert and project open) on a merge conflict and no finished chunks in manifest.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599#-:-KkQZpOoiRARSF1c39sW:bnfp4nl)*

**Comment by mannycolon** [comment]
@ihoegen your PR should be good to go now i fixed the merge conflicts.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1599)*

**Pull request merged**
