### PR TITLE
Feature mcleanb 4951/Problems opening OT books

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Adding OT support for project details in developer mode
- blocks opening OT project in developer mode if no aligned he.

#### Please include detailed Test instructions for your pull request:
- in developer mode should be able to do USFM import OT book and project details page should show OT books in the bible drop down.  Hit cancel
- now switch off developer mode and do USFM import OT book and project details page should show empty for book name.  Also should not show any OT books in the bible drop down.  Also make sure that continue is disabled.
- on tools card both WA and TW should have launch button disabled for OT books (since we do not have aligned he in resources) in both developer and non-developer mode.  Full Hebrew support is another issue for future.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5056)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (5cb9267)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-5cb9267.zip) is ready for download.
[macOS build 1.0.0 (5cb9267)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-5cb9267.dmg) is ready for download.
[Windows x64 build 1.0.0 (5cb9267)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-5cb9267.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (5cb9267)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-5cb9267.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (39df3a8)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-39df3a8.zip) is ready for download.
[macOS build 1.0.0 (39df3a8)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-39df3a8.dmg) is ready for download.
[Windows x64 build 1.0.0 (39df3a8)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-39df3a8.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (39df3a8)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-39df3a8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (6d9e0ed)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-6d9e0ed.zip) is ready for download.
[macOS build 1.0.0 (6d9e0ed)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-6d9e0ed.dmg) is ready for download.
[Windows x64 build 1.0.0 (6d9e0ed)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-6d9e0ed.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (6d9e0ed)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-6d9e0ed.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 14 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5056#-:-LMs09hkEqDn7G2Gxf4g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
