### PR TITLE
Not Showing Dialog of Alignment Errors if No Alignments

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR makes it so if there are errors in your alignment data but you did not make any previous alignments, the data will be reset still. But you will not get a dialog telling you. (Happens silently).

#### Please include detailed Test instructions for your pull request:
- First make sure you are on the latests tC_resources, node modules, and tC_apps.
- You can run the following script (save your changes first!)
`git stash; git checkout bugfix-jay-3193; git reset HEAD --hard; git pull; git submodule deinit -f . && git submodule update --init;`
- Do some alignments (remember the verse!)
- Open the tW tool, edit that same verse in the target language. Save.
- Open the word alignment tool, the alignments should now be reset, and you should be presented with a dialog.
- Now open the tW tool again, and edit a verse that you know has no alignments.
- Open the word alignment tool, the alignments should now be reset, and you should *NOT* be presented with a dialog.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4004)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Please assign yourself to the PR Review if you start reviewing
https://github.com/unfoldingWord-dev/translationCore/issues/4006

**Comment by klappy** [comment]
*[src/js/actions/WordAlignmentLoadActions.js, line 71 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004#-L7BcMkMJWcvNoB_lmTd:-L7BcMkMJWcvNoB_lmTe:b-va3fas) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/93bc110f302b352bd525b2a36e56db5ee207a753/src/js/actions/WordAlignmentLoadActions.js#L71)):*
> ```JavaScript
>       dispatch(AlertModalActions.openOptionDialog(
>         <div>
>           <div>There have been changes to the current verse which interfere with your alignments.</div>
> ```

Can you add this to the localization file? We should avoid user-visible text in the codebase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004)*

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004)*

**Comment by RoyalSix** [comment]
Review status: 3 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/WordAlignmentLoadActions.js, line 71 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004#-L7BcMkMJWcvNoB_lmTd:-L7CIHSqpXPDX4cBnu78:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/93bc110f302b352bd525b2a36e56db5ee207a753/src/js/actions/WordAlignmentLoadActions.js#L71)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you add this to the localization file? We should avoid user-visible text in the codebase.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004)*

**Comment by mannycolon** [comment]
Reviewed 30 of 30 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/locale/Afrikaans-af_ZA.json, line 235 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004#-L7CQoOsrNCKubB563SU:-L7CQoOsrNCKubB563SV:b-u5yvz3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/39f6c08eb97aecc65bdca88028801194807d1bc4/src/locale/Afrikaans-af_ZA.json#L235)):*
> ```JSON
>   },
>   "wordAlignment":{
>     "reset_alignments":"There have been changes to the current verse which interfere with your alignments.<br/>The alignments for the current verse have been reset."
> ```

Just wondering, was this text approved by Ben and coz and I wanted to suggest the following change to the text.

"There have been changes to the current verse that interfere with your alignments.<br/>Therefore, the alignments for the current verse have been reset."

---

*[src/locale/Arabic-ar_SA.json, line 236 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004#-L7CR53x5NVkINRrWr63:-L7CR53x5NVkINRrWr64:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/39f6c08eb97aecc65bdca88028801194807d1bc4/src/locale/Arabic-ar_SA.json#L236)):*
> ```JSON
>   ,
>   "wordAlignment":{
>     "reset_alignments":"There have been changes to the current verse which interfere with your alignments.<br/>The alignments for the current verse have been reset."
> ```

ibid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/4004)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/locale/Afrikaans-af_ZA.json, line 235 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4004#-L7CQoOsrNCKubB563SU:-L7PbYMj147VhZNtdccu:bimggk2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/39f6c08eb97aecc65bdca88028801194807d1bc4/src/locale/Afrikaans-af_ZA.json#L235)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Just wondering, was this text approved by Ben and coz and I wanted to suggest the following change to the text.

"There have been changes to the current verse that interfere with your alignments.<br/>Therefore, the alignments for the current verse have been reset."
</blockquote></details>

I think there is a problem with the tense here.  Since when the dialog is shown, the verse has not been reset, we should be warning that the alignments "will be" reset.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4004)*

**Pull request merged**
