### PR TITLE
Added Dispatcher to Root.js, Removed Extra Code

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/758)

### CODE REVIEW

**Comment by ihoegen** [comment]
@RoyalSix There's quite a few merge conflicts with this one

**Comment by RoyalSix** [comment]
@ihoegen fixed

**Comment by RoyalSix** [comment]
I will be making this in the template @ihoegen

**Comment by mannycolon** [comment]
@RoyalSix you need to merge with develop

**Comment by mannycolon** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-KdfynpUkw1FgHyAvVBW:-KdfynpUkw1FgHyAvVBX:b-s8wfv3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00c8f9c4c0d39968588d54d7b129baf2906881cf/src/js/actions/SettingsActions.js#L11)):*
> ```JavaScript
> module.exports.setSettings = function(field, value) {
>   return ((dispatch) => {
>     var dir = pathex.join(PACKAGE_COMPILE_LOCATION, 'settings.json');
> ```

this should not be here anymore

---

*[src/js/actions/SettingsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-KdfysTMhQslsAjB_44F:-KdfysTMhQslsAjB_44G:b-uxzc3s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00c8f9c4c0d39968588d54d7b129baf2906881cf/src/js/actions/SettingsActions.js#L31)):*
> ```JavaScript
> module.exports.toggleSettings = function(field) {
>   return ((dispatch) => {
>     var dir = pathex.join(PACKAGE_COMPILE_LOCATION, 'settings.json');
> ```

same above 

---

*[src/js/components/core/AccessProject.js, line 14 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-KdfyyB4twb1hnEmX2ux:-KdfyyB4twb1hnEmX2uy:bkcxml6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbd8734aa65c4a578c4a277507b8dc9d0dd14a8a/src/js/components/core/AccessProject.js#L14)):*
> ```JavaScript
> const PACKAGE_SUBMODULE_LOCATION = pathex.join(window.__base, 'tC_apps');
> const CheckDataGrabber = require('./create_project/CheckDataGrabber.js');
> const dispatch = require('../../utils/reduxActionDispatcher.js').dispatch;
> ```

any reason why you removed this

---

*[src/js/components/core/AccessProject.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-Kdfz-ePmOhfyUAqspJQ:-Kdfz-ePmOhfyUAqspJR:bkcxml6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbd8734aa65c4a578c4a277507b8dc9d0dd14a8a/src/js/components/core/AccessProject.js#L91)):*
> ```JavaScript
>           _this.putModulesInCheckstore(arrayOfChecks, checkDataFolderPath, () => {
>             api.putDataInCommon('saveLocation', folderpath);
>             dispatch(SettingsActions.setSettings('showTutorial', false));
> ```

any reason why you removed this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758)*

**Comment by mannycolon** [comment]
Reviewed 2 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/components/core/AccessProject.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-Kdfz-ePmOhfyUAqspJQ:-KdgQTYRSKR5Ig5_KvSq:b-fr2uue) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbd8734aa65c4a578c4a277507b8dc9d0dd14a8a/src/js/components/core/AccessProject.js#L91)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

any reason why you removed this
</blockquote></details>

It can be placed in the action

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-KdfynpUkw1FgHyAvVBW:-KdgQXdTqKmz7m1-14c0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00c8f9c4c0d39968588d54d7b129baf2906881cf/src/js/actions/SettingsActions.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should not be here anymore
</blockquote></details>

Done.

---

*[src/js/actions/SettingsActions.js, line 31 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-KdfysTMhQslsAjB_44F:-KdgQX1g0WUuW92SpyxF:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/00c8f9c4c0d39968588d54d7b129baf2906881cf/src/js/actions/SettingsActions.js#L31)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same above 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/AccessProject.js, line 91 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758#-Kdfz-ePmOhfyUAqspJQ:-KdglIxHcxF2P7SetT_s:bwsomap) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bbd8734aa65c4a578c4a277507b8dc9d0dd14a8a/src/js/components/core/AccessProject.js#L91)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

It can be placed in the action
</blockquote></details>

so it doesn't need to be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/758)*

**Pull request merged**
