### PR TITLE
Bugfix #3758/preserve header info on USFM import

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Preserve USFM header data on USFM import in headers.json
- Include data in headers.json on USFM export.

#### Please include detailed Test instructions for your pull request:
- import local USFM project and verify that `headers.json` is created in project data folder for book (e.g. `projects/en_tit/tit/headers.json`)
- export project to USFM and verify that attributes in `headers.json` are added to USFM file before first chapter marker.  Exception is that id tag (`\id`) will be overwritten with latest data.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3797)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 6 files at r2.
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by klappy** [comment]
Reviewed 4 of 6 files at r2.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r1, 1 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 3 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 105 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797#-L5R75T_uIKJG6mDGPvj:-L5R75T_uIKJG6mDGPvk:b-zilvl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c360500237f3911dabf6911c2012f3686abb068a/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L105)):*
> ```JavaScript
>       });
>       const projectBibleDataPath = path.join(IMPORTS_PATH, selectedProjectFilename, bibleDataFolderName, 'headers.json');
>       fs.outputJsonSync(projectBibleDataPath, importObject.headers);
> ```

Maybe use ```chaptersObject``` here? Since you already accessed the ```.chapters``` property above on line 90

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 105 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797#-L5R75T_uIKJG6mDGPvj:-L5Ua1xcSVTHmwI3PXNw:b-mlf61r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c360500237f3911dabf6911c2012f3686abb068a/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L105)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Maybe use ```chaptersObject``` here? Since you already accessed the ```.chapters``` property above on line 90
</blockquote></details>

I don't understand.  I don't want the `chaptersObject` here.  I want the headers info here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 105 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797#-L5R75T_uIKJG6mDGPvj:-L5Ub28figVFLoth4g6z:bhanr0w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c360500237f3911dabf6911c2012f3686abb068a/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L105)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

I don't understand.  I don't want the `chaptersObject` here.  I want the headers info here.
</blockquote></details>

Oh sorry I was tired when I was doing this, I mis read haha all good :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3797)*

**Comment by RoyalSix** [comment]
Code review: ```LGTM```
In-app testing: ```LGTM```

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3797#-:-L5W6SADBdJVOBnw_wrv:bnfp4nl)*

**Pull request merged**
