### PR TITLE
Only allow Titus projects in non-developer mode

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Only allow Titus projects in non-developer mode 

#### How to test this pull request:
- Make sure to disable developer mode.
- Try loading a non-Titus project.
- Should see an alert saying "You can only load Titus projects for now.".

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2239)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239#-:-KpQ_PirrRtl31dYqSa0:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2239#-:-KpQ_e-EIlid1Q_RCHrn:bnfp4nl)*

**Pull request merged**
