### PR TITLE
Updated tc-tool version

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):

This is a dependency update that is required for PR https://github.com/translationCoreApps/wordAlignment/pull/60

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4723)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.1 (b18eb6b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.1-b18eb6b.zip) is ready for download.
[macOS build 0.10.1 (b18eb6b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-b18eb6b.dmg) is ready for download.
[Windows x64 build 0.10.1 (b18eb6b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.1-b18eb6b.setup.exe) is ready for download.
[Windows x32 build 0.10.1 (b18eb6b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.1-b18eb6b.setup.exe) is ready for download.

**Review by RoyalSix — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RoyalSix — APPROVED** [review]
Pending comment on https://github.com/translationcoreapps/wordalignment/pull/60

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4723#-:-LHenBAn2avuonfj7HkX:b3bfhl5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
@neutrinog You'll also need to upgrade to `tc-ui-toolkit@0.9.17`

**Comment by da1nerd** [comment]
@mannycolon done!

**Review by mannycolon — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
