### PR TITLE
Move Settings to the Application Modal 

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/550)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMOgDLRWycCYuIU2w9:-KbMOgDLRWycCYuIU2wA:bxyzti5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c3b107309052e1f426c240b5501c6cfb3e21351/src/js/actions/SettingsActions.js#L5)):*
> ```JavaScript
> 
> module.exports.onSettingsChange = function (field) {
>   api.setSettings(field.name, field.value);
> ```

why are we still using the api here?

---

*[src/js/containers/ApplicationModalContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMPGJxVWZ02f8F-OfL:-KbMPGJxVWZ02f8F-OfM:b-7jse07) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c3b107309052e1f426c240b5501c6cfb3e21351/src/js/containers/ApplicationModalContainer.js#L3)):*
> ```JavaScript
> const React = require('react');
> const api = window.ModuleApi;
> const CoreActionsRedux = require('../actions/CoreActionsRedux.js');
> ```

any reason why your requiring coreActionsRedux???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Comment by ihoegen** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMOgDLRWycCYuIU2w9:-KbMQKpE-ydi-IaeJhZ_:b-1qvfrk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c3b107309052e1f426c240b5501c6cfb3e21351/src/js/actions/SettingsActions.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are we still using the api here?
</blockquote></details>

Because it updates it with localStorage. I removed the getSettings call. 

---

*[src/js/containers/ApplicationModalContainer.js, line 3 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMPGJxVWZ02f8F-OfL:-KbMS26UtTqlLE8et3DR:b-4n9hi9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c3b107309052e1f426c240b5501c6cfb3e21351/src/js/containers/ApplicationModalContainer.js#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

any reason why your requiring coreActionsRedux???
</blockquote></details>

No, just fixed that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/reducers/settingsReducer.js, line 13 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMSiONUgw5xcHV2eTA:-KbMSiOOuCuUBD9qCEeB:b-dhi1kd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/bb161f0c8032866503b606be5df41f69804e8f49/src/js/reducers/settingsReducer.js#L13)):*
> ```JavaScript
>     case consts.CHANGE_SETTINGS:
>       return merge({}, state, {
>         currentSettings: merge(state.currentSettings, action.val)
> ```

why are you merging twice??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Comment by RoyalSix** [comment]
Reviewed 6 of 10 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/js/containers/ApplicationModalContainer.js, line 39 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550#-KbMcHSvR80LTIKalheY:-KbMcHSvR80LTIKalheZ:bhgghka) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/248079c3011f08bfdd13c1e632a2ff3c79b400c1/src/js/containers/ApplicationModalContainer.js#L39)):*
> ```JavaScript
> 
> function mapStateToProps(state) {
>     return Object.assign({}, state, state.loginReducer, state.settingsReducer);
> ```

Are you using state other than loginReducer, and settingsReducer? If not you can remove "state". 

i.e. Object.assign({}, state.loginReducer, state.settingsReducer);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Comment by mannycolon** [comment]
@ihoegen i agree with Jay this way below its better

return Object.assign({}, state.loginReducer, state.settingsReducer);

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/550)*

**Pull request merged**
