### PR TITLE
Updates to project loading

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to #4884 and #4672.
- Lots of refactoring to the project loading so we can begin connect tools when a project is selected.
- I added some deprecation warnings as well to help begin the migration process away from some old methods.

#### Please include detailed Test instructions for your pull request:
- No functionality has been changed.
- Just try opening the tools and ensure things are still working.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-0940dc7.deb) is ready for download.
[macOS build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-0940dc7.dmg) is ready for download.
[Windows x64 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-0940dc7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-0940dc7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-0940dc7.deb) is ready for download.
[macOS build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-0940dc7.dmg) is ready for download.
[Windows x64 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-0940dc7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-0940dc7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-0940dc7.deb) is ready for download.
[macOS build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-0940dc7.dmg) is ready for download.
[Windows x64 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-0940dc7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0940dc7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-0940dc7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (1db1b35)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-1db1b35.deb) is ready for download.
[macOS build 1.1.0 (1db1b35)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-1db1b35.dmg) is ready for download.
[Windows x64 build 1.1.0 (1db1b35)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-1db1b35.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1db1b35)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-1db1b35.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 3 of 26 files at r1, 1 of 3 files at r3, 1 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 5 of 33 files reviewed, 2 unresolved discussions (waiting on @neutrinog)

___
*[__tests__/ProjectStructureValidationHelpers.test.js, line 46 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTZEkr9Kg_0GlIs7tV:-LTTZEkr9Kg_0GlIs7tW:bwdzmwv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4d068422f155cd6bb5a3acd00fd0f63a4cc7b4a3/__tests__/ProjectStructureValidationHelpers.test.js#L46)):*
> ```JavaScript
>   test('(legacy) should allow import of 0.8.1 project with checking', () => {
>     const projectPath = path.join(PROJECTS_PATH, projectName);
>     return expect(ProjectStructureValidationHelpers.ensureSupportedVersion(projectPath)).resolves.toBeUndefined();
> ```

Any reason we are removing these tests?
___
*[src/js/actions/ToolActions.js, line 68 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTaYxk8Nxh0geDqxv5:-LTTaYxl2nqG6g-v-25R:b-sl5lt2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/actions/ToolActions.js#L68)):*
> ```JavaScript
>   }, 100);
> };
> ```

Not sure how adding these changes to this file get closer to a refactor that makes it easier to load tools at project selection. I know its difficult to explain changes in the middle of a refactor. Just wondering if you could provide some context on this

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 5 of 33 files reviewed, 2 unresolved discussions (waiting on @RoyalSix and @neutrinog)

___
*[__tests__/ProjectStructureValidationHelpers.test.js, line 46 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTZEkr9Kg_0GlIs7tV:-LTU5Dp98FG0yK8wRlOD:b-5mxltu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4d068422f155cd6bb5a3acd00fd0f63a4cc7b4a3/__tests__/ProjectStructureValidationHelpers.test.js#L46)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Any reason we are removing these tests?
</blockquote></details>

because they were duplicates for the old project validation method.
___
*[src/js/actions/ToolActions.js, line 68 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTaYxk8Nxh0geDqxv5:-LTU5aZSEyU6AxjGOu77:btep66y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/actions/ToolActions.js#L68)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Not sure how adding these changes to this file get closer to a refactor that makes it easier to load tools at project selection. I know its difficult to explain changes in the middle of a refactor. Just wondering if you could provide some context on this
</blockquote></details>

Moving all the tool loading into this file and all the project loading into another. Before, things were spread over a number of different files and it was confusing what was going on.

**Comment by da1nerd** [comment]
I just discovered a bug in this code. Please hold off merging this until I've applied a fix.

**Comment by da1nerd** [comment]
this ready to go

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-ce337a1.deb) is ready for download.
[macOS build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-ce337a1.dmg) is ready for download.
[Windows x64 build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-ce337a1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-ce337a1.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 14 of 26 files at r1, 2 of 6 files at r2, 9 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 30 of 33 files reviewed, 3 unresolved discussions (waiting on @neutrinog)

___
*[src/js/actions/ToolActions.js, line 68 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTaYxk8Nxh0geDqxv5:-LTZGobJBgLpgxj6dZWg:b-mlj8kt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/actions/ToolActions.js#L68)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

Moving all the tool loading into this file and all the project loading into another. Before, things were spread over a number of different files and it was confusing what was going on.
</blockquote></details>

Ok. I think one of the reasons we had it split up was to make it less cluttered for just one file.
___
*[src/js/containers/home/ToolsManagementContainer.js, line 42 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZJTyoEMCxXwqpe-C0:-LTZJTyoEMCxXwqpe-C1:b5xqnrl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01790533b5379017689db45dbbbc8d76b9654482/src/js/containers/home/ToolsManagementContainer.js#L42)):*
> ```JavaScript
>       </div>
>     );
>     const availableCategories = ResourcesHelpers.getAvailableToolCategories(currentProjectToolsSelectedGL, selectedToolName);
> ```

I'm not opposed just wondering what's the point of moving this helper function into the container?
___
*[src/js/helpers/CoreAPI.js, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZKixt2SK00YU4KyxR:-LTZKixt2SK00YU4KyxS:bhbrj63) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/helpers/CoreAPI.js#L1)):*
> ```JavaScript
> import {
> ```

What type of functionality should go here?
It seems like a lot of code in tC should be considered apart of an API like this.
___
*[src/js/reducers/loaderReducer.js, line 7 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZLrou8HZiukmCgTwD:-LTZLrou8HZiukmCgTwE:b-xunfvb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/reducers/loaderReducer.js#L7)):*
> ```JavaScript
> };
> 
> // TODO: this is so small, the loading state should be moved into another reducer.
> ```

I don't think a small reducer necessarily facilitates combining it with another. Are we no longer using loading progess?

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 30 of 33 files reviewed, 3 unresolved discussions (waiting on @RoyalSix and @neutrinog)

___
*[src/js/actions/ToolActions.js, line 68 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTaYxk8Nxh0geDqxv5:-LTZhoxT0Lazaq8ia2rk:b-6n6ymx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/actions/ToolActions.js#L68)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Ok. I think one of the reasons we had it split up was to make it less cluttered for just one file.
</blockquote></details>

I'm in the process of distilling these down even further. There will be more changes in here in my next PR.
At any rate, it's better to keep related code grouped together. I'm moving some things from tool loading to project loading and vice versa so it makes sense to reorganize it.
___
*[src/js/containers/home/ToolsManagementContainer.js, line 42 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZJTyoEMCxXwqpe-C0:-LTZiUiN6QBfc7lVsykj:b-8k5bes) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01790533b5379017689db45dbbbc8d76b9654482/src/js/containers/home/ToolsManagementContainer.js#L42)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I'm not opposed just wondering what's the point of moving this helper function into the container?
</blockquote></details>

because it's not used anywhere else.
___
*[src/js/helpers/CoreAPI.js, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZKixt2SK00YU4KyxR:-LTZidizCtWQW-0ayTw1:b-z6arv3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/helpers/CoreAPI.js#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

What type of functionality should go here?
It seems like a lot of code in tC should be considered apart of an API like this.
</blockquote></details>

This is a work in progress. This expose a specific set of operations to tools. We don't tools to be able to see everything. And it make is very difficult to refactor if everything is tightly coupled together.

Instead tools will receive an api to the core and the project. Both are just wrappers around functionality in tC.
___
*[src/js/reducers/loaderReducer.js, line 7 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZLrou8HZiukmCgTwD:-LTZj7n82wvjBzCfU0of:b6jzou4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/reducers/loaderReducer.js#L7)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I don't think a small reducer necessarily facilitates combining it with another. Are we no longer using loading progess?
</blockquote></details>

This is only used when a tool is being opened. It would make sense to put it in the tools reducer since the state is related.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: all files reviewed, 4 unresolved discussions (waiting on @RoyalSix and @neutrinog)

___
*[__tests__/ProjectStructureValidationHelpers.test.js, line 44 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTdBVxZ0zulJE7YLIKt:-LTdBVxZ0zulJE7YLIKu:byjqykl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01790533b5379017689db45dbbbc8d76b9654482/__tests__/ProjectStructureValidationHelpers.test.js#L44)):*
> ```JavaScript
>     return expect(ProjectStructureValidationHelpers.isProjectSupported(projectPath, translate)).resolves.toEqual(true);
>   });
>   test('(legacy) should allow import of 0.8.1 project with checking', () => {
> ```

Don't we need this tests anymore? Why is it being removed?
___
*[src/js/helpers/CoreAPI.js, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZKixt2SK00YU4KyxR:-LTdB6e76c6xmJJ41Zu4:b74hfsf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/helpers/CoreAPI.js#L1)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

This is a work in progress. This expose a specific set of operations to tools. We don't tools to be able to see everything. And it make is very difficult to refactor if everything is tightly coupled together.

Instead tools will receive an api to the core and the project. Both are just wrappers around functionality in tC.
</blockquote></details>

I agree with Jay here, I dont see why we would want to have an API like this. Why not put this logic in a container? like the toolContainer?

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: all files reviewed, 3 unresolved discussions (waiting on @neutrinog and @RoyalSix)

___
*[src/js/actions/ToolActions.js, line 68 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTTaYxk8Nxh0geDqxv5:-LTd9lkP9ttjnKRgDmVR:b-8fx2u7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/actions/ToolActions.js#L68)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

I'm in the process of distilling these down even further. There will be more changes in here in my next PR.
At any rate, it's better to keep related code grouped together. I'm moving some things from tool loading to project loading and vice versa so it makes sense to reorganize it.
</blockquote></details>

:+1: 
___
*[src/js/containers/home/ToolsManagementContainer.js, line 42 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZJTyoEMCxXwqpe-C0:-LTd9qxG5Gw_u_sYv-fC:b-hfghm4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01790533b5379017689db45dbbbc8d76b9654482/src/js/containers/home/ToolsManagementContainer.js#L42)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

because it's not used anywhere else.
</blockquote></details>

Sounds good
___
*[src/js/reducers/loaderReducer.js, line 7 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZLrou8HZiukmCgTwD:-LTdBHljD5UNhOXSQ3lF:bb74x83) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/reducers/loaderReducer.js#L7)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

This is only used when a tool is being opened. It would make sense to put it in the tools reducer since the state is related.
</blockquote></details>

True

**Comment by PhotoNomad0** [comment]
@neutrinog - found problem importing from D43 and then clicking cancel.  Project detail dialog stays on screen.  Project was https://git.door43.org/tCore-test-data/AlignedUlt_en, but it probably doesn't matter.

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: all files reviewed, 3 unresolved discussions (waiting on @neutrinog, @RoyalSix, and @mannycolon)

___
*[__tests__/ProjectStructureValidationHelpers.test.js, line 44 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTdBVxZ0zulJE7YLIKt:-LTdYky34cMLE5kypA5M:bgjw9y4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01790533b5379017689db45dbbbc8d76b9654482/__tests__/ProjectStructureValidationHelpers.test.js#L44)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Don't we need this tests anymore? Why is it being removed?
</blockquote></details>

The test is still there. If you look at the commit history you'll see I created duplicate tests for a refactored version of the method in question. This PR simply removes the old method (and tests) but leaves the new one. These test are identical to the original ones.
___
*[src/js/helpers/CoreAPI.js, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZKixt2SK00YU4KyxR:-LTdZD1e2khs0xmPZvTY:bdzr539) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/helpers/CoreAPI.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I agree with Jay here, I dont see why we would want to have an API like this. Why not put this logic in a container? like the toolContainer?
</blockquote></details>

Because it is being used in multiple locations. Once when the project is selected so we can connect all the tools and then also when a tool is opened. I needed to pull it out to a central location to avoid duplicate code. See ProjectLoadingActions.js and ToolContainer.js

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-ce337a1.deb) is ready for download.
[macOS build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-ce337a1.dmg) is ready for download.
[Windows x64 build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-ce337a1.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ce337a1)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-ce337a1.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (e3416b7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-linux-x64-1.1.0-e3416b7.deb) is ready for download.
[macOS build 1.1.0 (e3416b7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-macos-x64-1.1.0-e3416b7.dmg) is ready for download.
[Windows x64 build 1.1.0 (e3416b7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x64-1.1.0-e3416b7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e3416b7)](https://tc-builds.door43.org/build/enhancement_joel_4884_project-loading/translationCore-win-x32-1.1.0-e3416b7.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @RoyalSix, @neutrinog, and @mannycolon)

___
*[src/js/helpers/CoreAPI.js, line 1 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTZKixt2SK00YU4KyxR:-LTiZ-Dc3TLfhMCTl9Yj:b-8fx2u7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ce337a1f4cbe1c5fb3ef0f0c534bcf8ae1fe67dc/src/js/helpers/CoreAPI.js#L1)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

Because it is being used in multiple locations. Once when the project is selected so we can connect all the tools and then also when a tool is opened. I needed to pull it out to a central location to avoid duplicate code. See ProjectLoadingActions.js and ToolContainer.js
</blockquote></details>

:+1:

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 32 of 33 files reviewed, 4 unresolved discussions (waiting on @RoyalSix, @neutrinog, and @mannycolon)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTiZUnvAfqkqKnoyg3N:-LTiZUnvAfqkqKnoyg3O:b-5xasl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/reducers/projectDetailsReducer.js#L17)):*
> ```JavaScript
> const projectDetailsReducer = (state = initialState, action) => {
>   switch (action.type) {
>     case consts.SET_PROJECT_CATEGORIES: {
> ```

I did some work on the categories functionality. Will be interesting to see how this merges

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 32 of 33 files reviewed, 4 unresolved discussions (waiting on @RoyalSix, @neutrinog, and @mannycolon)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTiZUnvAfqkqKnoyg3N:-LTiZc_J7DR1B8lz70QN:b-7od25t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/reducers/projectDetailsReducer.js#L17)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I did some work on the categories functionality. Will be interesting to see how this merges
</blockquote></details>

Also, are you moving this somewhere else? Isn't this reducer still needed?

**Review by da1nerd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 32 of 33 files reviewed, 4 unresolved discussions (waiting on @RoyalSix, @neutrinog, and @mannycolon)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTiZUnvAfqkqKnoyg3N:-LTiiqJ47ckmdVwxGH8c:b2chsf6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/reducers/projectDetailsReducer.js#L17)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Also, are you moving this somewhere else? Isn't this reducer still needed?
</blockquote></details>

That SET_PROJECT_CATEGORIES case was an accident. I pushed a commit the other day to remove it. The only changes I actually made were to add some selectors to the reducer so there shouldn't be any conflicts. Sorry for the confusion.

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @RoyalSix, @neutrinog, and @mannycolon)

___
*[src/js/reducers/projectDetailsReducer.js, line 17 at r4](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-LTiZUnvAfqkqKnoyg3N:-LTikAqqAEymHneXEDJv:bazxzds) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1db1b352e4f82cbaf52ebb115b09363e20dcda1e/src/js/reducers/projectDetailsReducer.js#L17)):*
<details><summary><i>Previously, neutrinog (Joel) wrote…</i></summary><blockquote>

That SET_PROJECT_CATEGORIES case was an accident. I pushed a commit the other day to remove it. The only changes I actually made were to add some selectors to the reducer so there shouldn't be any conflicts. Sorry for the confusion.
</blockquote></details>

Ahh ok I see now. All good

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541)* status: all files reviewed, 3 unresolved discussions (waiting on @neutrinog and @mannycolon)

**Review by RoyalSix — COMMENTED** [review]
I am doing local testing now

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5541#-:-LTikQqi37xV-lrlHluD:b-j4766o)* status: all files reviewed, 3 unresolved discussions (waiting on @neutrinog and @mannycolon)

**Comment by RoyalSix** [comment]
Local testing LGTM

**Pull request merged**
