### PR TITLE
Support For translationNotes

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR brings in the base functionality of the tN tool.
- It should be usable as a checking tool after this update.

#### Please include detailed Test instructions for your pull request:
Will also need to review this PR https://github.com/translationCoreApps/translationNotes/pull/93
- Checkout `feature-jay-5753` branch on tC
- run `npm run load-apps`
- Start tC and then open any project
- You should see translationNotes as a listed tool
   - You may have to update the resources if you haven't already in order to use the tool
- The tool should function just as tW
- Everything should work besides the functionality of nested tool categories which is covered in another issue
Note: It says there are changes to the tW tool but it is actually the correct hash check here: https://github.com/unfoldingWord-dev/translationCore/tree/develop/tC_apps

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (dc79469)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-linux-x64-1.2.0-dc79469.deb) is ready for download.
[macOS build 1.2.0 (dc79469)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-dc79469.dmg) is ready for download.
[Windows x64 build 1.2.0 (dc79469)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x64-1.2.0-dc79469.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (dc79469)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x32-1.2.0-dc79469.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (ccf49f1)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-linux-x64-1.2.0-ccf49f1.deb) is ready for download.
[macOS build 1.2.0 (ccf49f1)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-ccf49f1.dmg) is ready for download.
[Windows x64 build 1.2.0 (ccf49f1)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x64-1.2.0-ccf49f1.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (ccf49f1)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x32-1.2.0-ccf49f1.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)* status: all files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefIUL8c5fDzdZG0Up:-LZefIUM1rqxWU_3s0Jh:b-w6ohzb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/helpers/gatewayLanguageHelpers.js#L80)):*
> ```JavaScript
>       requirements.gl.helpsChecks = [
>         {
>           path: 'translationHelps/translationAcademy',
> ```

Should we use path.join('translationHelps', 'translationAcademy') to avoid issues with windows machines?
___
*[src/js/reducers/projectDetailsReducer.js, line 15 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefr2z3JXsA1cAyIkq:-LZefr2z3JXsA1cAyIkr:bbo39g8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/reducers/projectDetailsReducer.js#L15)):*
> ```JavaScript
>   toolsCategories: {
>     translationWords: ['kt', 'other', 'names'],
>     translationNotes: ['other']
> ```

why is other here? is it being excluded? other should be excluded and only the other categories should be available in tc

**Comment by mannycolon** [comment]
@RoyalSix  
The launch button for tN should not be enabled if the `translationNotes` resources aren't found in the user's resources folder

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)* status: all files reviewed, 2 unresolved discussions (waiting on @mannycolon)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefIUL8c5fDzdZG0Up:-LZg8gpX52ob0tmK3UTQ:b-rxkqj5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/helpers/gatewayLanguageHelpers.js#L80)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Should we use path.join('translationHelps', 'translationAcademy') to avoid issues with windows machines?
</blockquote></details>

Doesn't hurt. Although `path.join` it is being used where its actually being used for reading
___
*[src/js/reducers/projectDetailsReducer.js, line 15 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefr2z3JXsA1cAyIkq:-LZg8sT82YrdUvoHH8K0:b-mufnln) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/reducers/projectDetailsReducer.js#L15)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why is other here? is it being excluded? other should be excluded and only the other categories should be available in tc
</blockquote></details>

This is not actually being used anymore.  Bruce Spidels PR addresses this legacy code.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (31a202d)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-linux-x64-1.2.0-31a202d.deb) is ready for download.
[macOS build 1.2.0 (31a202d)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-31a202d.dmg) is ready for download.
[Windows x64 build 1.2.0 (31a202d)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x64-1.2.0-31a202d.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (31a202d)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x32-1.2.0-31a202d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (e7db710)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-linux-x64-1.2.0-e7db710.deb) is ready for download.
[macOS build 1.2.0 (e7db710)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-e7db710.dmg) is ready for download.
[Windows x64 build 1.2.0 (e7db710)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x64-1.2.0-e7db710.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (e7db710)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x32-1.2.0-e7db710.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefIUL8c5fDzdZG0Up:-LZl-4auAZkacuIBcmu4:b-qhqfz6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/helpers/gatewayLanguageHelpers.js#L80)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Doesn't hurt. Although `path.join` it is being used where its actually being used for reading
</blockquote></details>

It should be path.join('translationHelps', 'translationAcademy')

the idea is avoiding the usage of forward slashes that isn't supported on some windows machines
___
*[src/js/reducers/projectDetailsReducer.js, line 15 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefr2z3JXsA1cAyIkq:-LZl-Maw40GQsgcETM_c:b32wtd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/reducers/projectDetailsReducer.js#L15)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This is not actually being used anymore.  Bruce Spidels PR addresses this legacy code.
</blockquote></details>

ok

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/helpers/gatewayLanguageHelpers.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-LZefIUL8c5fDzdZG0Up:-LZl5tyS6NdCTE7Jp6vT:bt2vr1b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ccf49f104ed07025ee99715f939d21d11ea37454/src/js/helpers/gatewayLanguageHelpers.js#L80)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

It should be path.join('translationHelps', 'translationAcademy')

the idea is avoiding the usage of forward slashes that isn't supported on some windows machines
</blockquote></details>

Fixed.

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5831#-:-LZl9yEy7X174iGDt7e_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (4f42f46)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-linux-x64-1.2.0-4f42f46.deb) is ready for download.
[macOS build 1.2.0 (4f42f46)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-macos-x64-1.2.0-4f42f46.dmg) is ready for download.
[Windows x64 build 1.2.0 (4f42f46)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x64-1.2.0-4f42f46.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (4f42f46)](https://tc-builds.door43.org/build/feature-jay-5753/translationCore-win-x32-1.2.0-4f42f46.setup.exe) is ready for download.

**Pull request merged**
