### PR TITLE
Feature 3579/Speeding up navigation of checks with cached data and delayed loading.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added async loading of translation helps data.
- modified group data reducer to store comment as text rather than boolean
- changeCurrentContextId() changed to load check data from group data reducer if found rather than from file system.

#### Please include detailed Test instructions for your pull request:
- test with the latest build at bottom
- should be able to launch and navigate in all tools.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6482)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (fbef03d)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-fbef03d.deb) is ready for download.
[macOS build 2.0.0 (fbef03d)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-fbef03d.dmg) is ready for download.
[Windows x64 build 2.0.0 (fbef03d)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-fbef03d.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (fbef03d)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-fbef03d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (91c1b8f)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-91c1b8f.deb) is ready for download.
[macOS build 2.0.0 (91c1b8f)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-91c1b8f.dmg) is ready for download.
[Windows x64 build 2.0.0 (91c1b8f)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-91c1b8f.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (91c1b8f)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-91c1b8f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (368f41e)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-368f41e.deb) is ready for download.
[macOS build 2.0.0 (368f41e)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-368f41e.dmg) is ready for download.
[Windows x64 build 2.0.0 (368f41e)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-368f41e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (368f41e)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-368f41e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (1c28c52)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-1c28c52.deb) is ready for download.
[macOS build 2.0.0 (1c28c52)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-1c28c52.dmg) is ready for download.
[Windows x64 build 2.0.0 (1c28c52)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-1c28c52.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (1c28c52)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-1c28c52.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (47c0516)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-47c0516.deb) is ready for download.
[macOS build 2.0.0 (47c0516)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-47c0516.dmg) is ready for download.
[Windows x64 build 2.0.0 (47c0516)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-47c0516.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (47c0516)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-47c0516.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (59987db)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-59987db.deb) is ready for download.
[macOS build 2.0.0 (59987db)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-59987db.dmg) is ready for download.
[Windows x64 build 2.0.0 (59987db)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-59987db.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (59987db)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-59987db.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (2527b45)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-2527b45.deb) is ready for download.
[macOS build 2.0.0 (2527b45)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-2527b45.dmg) is ready for download.
[Windows x64 build 2.0.0 (2527b45)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-2527b45.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (2527b45)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-2527b45.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (3818291)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-linux-x64-2.0.0-3818291.deb) is ready for download.
[macOS build 2.0.0 (3818291)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-macos-x64-2.0.0-3818291.dmg) is ready for download.
[Windows x64 build 2.0.0 (3818291)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x64-2.0.0-3818291.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (3818291)](https://tc-builds.door43.org/build/feature-mcleanb-3579.3/translationCore-win-x32-2.0.0-3818291.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Pull request merged**
