### PR TITLE
Bugfix 6050/Fix bug that tN selection prompt was sometimes in English.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fixed bug in loadBiblesByLanguageId() that would not load hi_irv if there were already hi bibles loaded.  Sometimes it would just have hi_ulb loaded which does not have alignments.

#### Please include detailed Test instructions for your pull request:
1. in tCore, update to latest en and hi resources.
2. import [58-PHM-hi.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/3383567/58-PHM-hi.usfm.txt), select en GL for tN, and launch.  Then change tN GL to hi and launch.  should see selection prompts in hi and not en.
3. select a different project, set GL for tN to en and launch.
4. reselect project from step 2, select en GL for tN, and launch.  Then change tN GL to hi and launch.  should see selection prompts in hi and not en.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6269)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (44c7cfc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-linux-x64-2.0.0-44c7cfc.deb) is ready for download.
[macOS build 2.0.0 (44c7cfc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-macos-x64-2.0.0-44c7cfc.dmg) is ready for download.
[Windows x64 build 2.0.0 (44c7cfc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-win-x64-2.0.0-44c7cfc.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (44c7cfc)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-win-x32-2.0.0-44c7cfc.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c0206ae)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-linux-x64-2.0.0-c0206ae.deb) is ready for download.
[macOS build 2.0.0 (c0206ae)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-macos-x64-2.0.0-c0206ae.dmg) is ready for download.
[Windows x64 build 2.0.0 (c0206ae)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-win-x64-2.0.0-c0206ae.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c0206ae)](https://tc-builds.door43.org/build/bugfix-mcleanb-6050/translationCore-win-x32-2.0.0-c0206ae.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
I am not seeing the selection warning after changing the GL to hindi

**Comment by PhotoNomad0** [comment]
> I am not seeing the selection warning after changing the GL to hindi

That's a good thing isn't it?

**Comment by RoyalSix** [comment]
I also opened the tool in tN, I mean. I never saw a selection warning as the instructions indicate.

**Pull request merged**
