### PR TITLE
Project Viewer

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request allows a user to go to their profile page and view their Door43 projects.
It also gives them the ability to load those projects.

---

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/88)

### CODE REVIEW

**Comment by EllDoubleYew** [comment]
Is there any reason to take on the Lodash library? I see its utility but was it necessary to accomplish UI browser for git?

**Comment by EllDoubleYew** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[package.json, line 58 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcM7QhqNpXZnOo5ca2:-KQcM7QhqNpXZnOo5ca3:bqpgn0z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/package.json#L58)):_

> ``` JSON
>     "gogs-client": "^0.5.2",
>     "http": "0.0.0",
>     "lodash": "^4.15.0",
> ```

Is this a necessary dependancy? I get that it is cool but do we really need it to accomplish what we need? Just something to discuss.

---

_[src/js/components/core/login/GogsApi.js, line 44 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMSN-FpfYQDmaSJqS:-KQcMSN-FpfYQDmaSJqT:b-l146cc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L44)):_

> ``` JavaScript
>       });
>     },
> ```

Since this is an API function (even if its not the top level API its not out of the question for it to be implemented there) lets get some kind of contract on this function so it is easier to reference.

---

_[src/js/components/core/login/GogsApi.js, line 46 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMEfQeSdBTxrrvGiP:-KQcMEfQeSdBTxrrvGiQ:br6a1xx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L46)):_

> ``` JavaScript
> 
>     retrieveRepos: function (u, q) {
>            u = u === '*' ? '' : (u || '');
> ```

Could we be a little more verbose with variable names than u and q here? I have no idea what we are comparing.

---

_[src/js/components/core/login/GogsApi.js, line 72 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMjautOJjIQfl6sR6:-KQcMjautOJjIQfl6sR7:b-ivwcu4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L72)):_

> ``` JavaScript
>            var p = u ? searchUsers(searchRepos) : searchRepos();
> 
>            return p.then(_.flatten).then(function (repos) {
> ```

I am assuming this is lodash, if we do decide this is a necessary dependency to take on lets just comment what this is doing because new devs on the project may have less experience with it.

---

_[src/js/components/core/login/GogsApi.js, line 76 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMzQtDtrWE-Hiym5j:-KQcMzQtDtrWE-Hiym5k:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L76)):_

> ``` JavaScript
>            })
>            .then(function (repos) {
>                return _.map(repos, function (repo) {
> ```

ibid

---

_[src/js/components/core/login/Projects.js, line 18 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcO_Pd3_eG-6m8ayld:-KQcO_PeTjWe7o4SJ-ZF:b4jnk1t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L18)):_

> ``` JavaScript
>     var user = api.getLoggedInUser();
>     if (user) {
> ```

Is something supposed to be here? Or should this wrap around the remainder of the function body?

---

_[src/js/components/core/login/Projects.js, line 21 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcNcr1dZx0SxMPdu_j:-KQcNcr1dZx0SxMPdu_k:boj01f8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L21)):_

> ``` JavaScript
>     }
>     var _this = this;
>     return Gogs.retrieveRepos('royalsix').then(function(repos){
> ```

Why is this hardcoded to royalsix? If its arbitrary lets name it something that implies arbitration or remove the parameter all together. Also I like the way you used promises between these two :+1: 

---

_[src/js/components/core/login/Projects.js, line 40 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcOgC4rM3xZshU5Krp:-KQcOgC4rM3xZshU5Krq:b-6rgbca) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L40)):_

> ``` JavaScript
>       projectList.push(
>         <div key={p} style={{width: '100%', marginBottom: '15px'}}>
>           {projectName} &nbsp;
> ```

Lets try and avoid non breaking spaces wherever possible please! If you need space between the name and the button either wrap it in its own div and apply a right margin or let it sit on the button if you don't want to mess with it. It will just give us more control over the UI later on.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88)_

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[package.json, line 58 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcM7QhqNpXZnOo5ca2:-KQcrTn-zVOrtYCTA5aj:ba3dfob) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/package.json#L58)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Is this a necessary dependancy? I get that it is cool but do we really need it to accomplish what we need? Just something to discuss.
> </details>
> Removed

---

_[src/js/components/core/login/GogsApi.js, line 44 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMSN-FpfYQDmaSJqS:-KQcu1Aeo-bqTk-sGrlu:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L44)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Since this is an API function (even if its not the top level API its not out of the question for it to be implemented there) lets get some kind of contract on this function so it is easier to reference.
> </details>
> Done.

---

_[src/js/components/core/login/GogsApi.js, line 46 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMEfQeSdBTxrrvGiP:-KQcu20tFjPIYFn9NWBl:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L46)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Could we be a little more verbose with variable names than u and q here? I have no idea what we are comparing.
> </details>
> Done.

---

_[src/js/components/core/login/GogsApi.js, line 72 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMjautOJjIQfl6sR6:-KQcu2kw5kdvxYhSHKhA:borniwz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L72)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> I am assuming this is lodash, if we do decide this is a necessary dependency to take on lets just comment what this is doing because new devs on the project may have less experience with it.
> </details>
> I've removed lodash

---

_[src/js/components/core/login/GogsApi.js, line 76 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcMzQtDtrWE-Hiym5j:-KQcu4W5ESZ7taQ1rSoz:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/GogsApi.js#L76)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> ibid
> </details>
> Done.

---

_[src/js/components/core/login/Projects.js, line 18 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcO_Pd3_eG-6m8ayld:-KQcxDyDfndS75OTymSS:bc48n4b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L18)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Is something supposed to be here? Or should this wrap around the remainder of the function body?
> </details>
> Forgot about this one haha.

---

_[src/js/components/core/login/Projects.js, line 21 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcNcr1dZx0SxMPdu_j:-KQcxHc9OUFO8Yo13JOS:b-mklmwy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L21)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Why is this hardcoded to royalsix? If its arbitrary lets name it something that implies arbitration or remove the parameter all together. Also I like the way you used promises between these two :+1: 
> </details>
> Fixed it to where it's dynamic.

---

_[src/js/components/core/login/Projects.js, line 40 [r1]](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-KQcOgC4rM3xZshU5Krp:-KQcxP1lqMERDnrptiYY:bkqmz4s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/52cfa2b27200e958d3b886af3cb6fb927e3e8b4f/src/js/components/core/login/Projects.js#L40)):_
<details><summary>

<i>Previously, EllDoubleYew (Luke Wilson) wrote…</i></summary>



> Lets try and avoid non breaking spaces wherever possible please! If you need space between the name and the button either wrap it in its own div and apply a right margin or let it sit on the button if you don't want to mess with it. It will just give us more control over the UI later on.
> </details>
> Removed non breaking spaces.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88)_

**Comment by RoyalSix** [comment]
Pulling branch for testing then merging

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-:-KR-C9jA6eLg7MBKP3Xg:b-9vut2p)_

**Comment by RoyalSix** [comment]
I am trying to load in a project from the viewer, with that has this url: https://git.door43.org/royalsix/ilo_luk_text_ulb.git
In LoadOnline.js on line 45, the callback is missing a parameter (which happens to be another callback), which should be called in Access Project but its coming up as undefined and throwing an error. Not sure whats going on. You got it tho! :)

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/88#-:-KR-GESftIBYiP43Jdue:b-uk9zrw)_

**Comment by ihoegen** [comment]
That should fix it.

**Comment by EllDoubleYew** [comment]
Ran the same tests as before and this looks finished from an issue description standpoint. Merged.

**Pull request merged**
