### PR TITLE
QA fail 4404/Project Details Page continue button enable.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fix to initialize project details save button to enabled if fields are valid.
- fix to make sure project details page is shown on project import.

#### Please include detailed Test instructions for your pull request:
- import project [es-419_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115519/es-419_tit_text_reg.tstudio.zip)
- should see copyright page, project details page (continue button enabled), and missing verse page

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694)

### CODE REVIEW

**Review by mannycolon — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix)

**Comment by RoyalSix** [comment]
The missing verses page showed but it kind of lagged and shows the stepper like an inch higher than normal. Not sure if that will get QA failed again
screen shot 2018-07-09 at 11 24 50 am
From experience I know this can be fixed by setting a timeout between showing the next page

**Comment by mannycolon** [comment]
@PhotoNomad0 Why even close the modal if you will open it back up again?

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/locale/Hindi-hi_IN.json, line 132 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694#-LH-Pc6k21VjUMxMs6Jo:-LH-Pc6k21VjUMxMs6Jp:b-lv5gao) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f43aa52d5943c273c24e725e145a8dcb6b396829/src/locale/Hindi-hi_IN.json#L132)):*
> ```JSON
>     "upload_to_d43": "${door43} पर अपलोड करें",
>     "edit_project_details": "प्रोजेक्ट विवरण संपादित करें",
>     "reimport_project": "Reimport Project",
> ```

Is this going to mess anything up?

**Review by PhotoNomad0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/locale/Hindi-hi_IN.json, line 132 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4694#-LH-Pc6k21VjUMxMs6Jo:-LH-SNg2EPw6WRrD02In:b-l3im6k) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f43aa52d5943c273c24e725e145a8dcb6b396829/src/locale/Hindi-hi_IN.json#L132)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Is this going to mess anything up?
</blockquote></details>

Probably should have left this broken, but I removed duplicate entries in crowdin caused by someone committing changes to Hindi.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 Why even close the modal if you will open it back up again?

@mannycolon - I didn't, that is pre-existing code.  Looks like it was put there because we needed to first have a valid book name on USFM import, then we parse the USFM, and then called validate() again to find missing verses and merge conflicts.

**Comment by RoyalSix** [comment]
Local Testing:`LGTM` (In order to get the loading screen to go away would most likely have to do a small refactor)
Code Review: `LGTM`

**Pull request merged**
