### PR TITLE
Add Group Data/Index Actions

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds group data from the tools on load in the fetch data.

#### How to test this pull request:
To test this PR you will need to checkout the tools
ScripturePane: js_groupDataActions
translationWords: js_groupDataActions

Load a tool and see if the groupDataReducer, and groupIndexReducer have the right data

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1008)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/js/actions/GetDataActions.js, line 234 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-Kg_uTmew9ouTCF1_ubh:-Kg_uTmew9ouTCF1_ubi:bnmtgc6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/413ea4a8a8ab43dc1b779025af77574943228005/src/js/actions/GetDataActions.js#L234)):*
> ```JavaScript
>         let manifest = LoadHelpers.loadFile(projectSaveLocation, 'manifest.json');
>         if (!manifest) {
>             var defaultManifest = setUpDefaultUSFMManifest(parsedUSFM, direction, currentUser);
> ```

could we use let instead??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008)*

**Comment by klappy** [comment]
I've got a PR in that addresses some issues with our naming of these actions/reducers/etc... 

So reducers are plural as they are managing a collection of groups, so groupsData and groupsIndex.

For consistency, when adding something, it is adding a single item to a collection, so what is added is singular, and what it is added to is plural. 

When setting the entire collection, like the index, all at once, we just name it setGroupsIndex, since we are setting the plural collection.

All these were required for navigation/group menu to work:
https://github.com/unfoldingWord-dev/translationCore/pull/1010

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-:-Kgav7jAeDmTkfU6wub5:bsxjgvh)*

**Comment by klappy** [comment]
All this looks good, but just wanted to share the changes I made to make the menu/navigation work.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-:-Kgawb1rMEYJem_FgqYa:b-4xi0ac)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-:-KgawhAqVMdhzhsKmTyj:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/pages/app.js, line 120 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-KgezRZv6oii35sOJC6R:-KgezRZv6oii35sOJC6S:buaumf9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dd31f413682e2b4fa380ae012d7cd3695088eaf9/src/js/pages/app.js#L120)):*
> ```JavaScript
> 
>   render: function () {
>     // logging the store for testing.
> ```

maybe removed the comments as well lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GetDataActions.js, line 234 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-Kg_uTmew9ouTCF1_ubh:-KgllEqjjQ98arN4UUx5:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/413ea4a8a8ab43dc1b779025af77574943228005/src/js/actions/GetDataActions.js#L234)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we use let instead??
</blockquote></details>

Done.

---

*[src/js/pages/app.js, line 120 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008#-KgezRZv6oii35sOJC6R:-KgllEPuupaEAJ7CTET9:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/dd31f413682e2b4fa380ae012d7cd3695088eaf9/src/js/pages/app.js#L120)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe removed the comments as well lol
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1008)*

**Pull request merged**
