### PR TITLE
Added correct instructions for tools main page and login main page

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Added correct instructions for tools main page. #976 
- Added correct instructions for user main page. #1985 
- Update grammar on the `log out button` #2173

#### How to test this pull request:
- Go to the tools Main page and verify the instructions read as **Select a tool from the list**.

- Login with your `door43` and `local user` act and see how the instructions update accordingly.
- Log out with from both `door43` and `local user`

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2241)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/CreateLocalAccount.js, line 70 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8ExhlBpk3lB_lMJC:-Kpp8ExhlBpk3lB_lMJD:bqobz4e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/components/home/usersManagement/CreateLocalAccount.js#L70)):*
> ```JavaScript
>     const loginEnabled = this.state.localUsername && this.state.checkBoxChecked ? true : false;
>     const callback = (result) => {
>       if (result == "Create Account") this.props.loginLocalUser(this.state.localUsername);
> ```

Why is this no longer nested under actions? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/LoginDoor43Account.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8MbK26Q_cS2jXc2F:-Kpp8MbK26Q_cS2jXc2G:bu3i6gj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/components/home/usersManagement/LoginDoor43Account.js#L80)):*
> ```JavaScript
>           disabled={disabledButton}
>           style={{ width: "100%", margin: "40px 0px 10px" }}
>           onClick={() => this.props.loginUser(this.state)}>
> ```

Is there a reason to not keep this under actions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 84 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8bjuDR5tCTXmVPcO:-Kpp8bjuDR5tCTXmVPcP:bfsh2t0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/containers/home/UsersManagementContainer.js#L84)):*
> ```JavaScript
>                 {...this.props}
>                 loginUser={(loginCredentials) => {
>                   this.props.actions.loginUser(loginCredentials);
> ```

Here this uses actions namespace, but see some of the other files don't, is there a reason that I'm missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by mannycolon** [comment]
@klappy they are not under actions because the call another function inside the reducer to update the instructions.

**Comment by mannycolon** [comment]
@klappy see UsersManagementContainer.js line 83 for example

**Comment by klappy** [comment]
Reviewed 5 of 6 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-:-KppaGPcbHKo-8iJLuZ9:bnfp4nl)*

**Comment by klappy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/components/home/usersManagement/CreateLocalAccount.js, line 70 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8ExhlBpk3lB_lMJC:-KppaJKC-GW8KzCvX12j:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/components/home/usersManagement/CreateLocalAccount.js#L70)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Why is this no longer nested under actions? 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
*[src/js/components/home/usersManagement/LoginDoor43Account.js, line 80 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8MbK26Q_cS2jXc2F:-KppaM442JNGHJYpw4Ns:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/components/home/usersManagement/LoginDoor43Account.js#L80)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Is there a reason to not keep this under actions?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Comment by klappy** [comment]
*[src/js/containers/home/UsersManagementContainer.js, line 84 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241#-Kpp8bjuDR5tCTXmVPcO:-KppaO2OOvXZkShuXMKA:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea6104d97461594189f18d286b89831e84d60f4/src/js/containers/home/UsersManagementContainer.js#L84)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Here this uses actions namespace, but see some of the other files don't, is there a reason that I'm missing?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2241)*

**Pull request merged**
