### PR TITLE
Improved Book Name Change Workflow

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR will change the user experience when changing the book name(id) from the project details screen. The project book can be changed at any time as long as it does not interfere with a project name already in the user's git repository.

#### Please include detailed Test instructions for your pull request:
- Sign into your door43 account and import a project from your repo.
- Try and change the name from the project details screen. 
- Ensure that after confirming all changes the new project id reflects in the door43 repo
- Remove the project from the local directory and try importing it again from your repo
- Ensure that the new book id given is correctly identified.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5227)

### CODE REVIEW

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5227)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @RoyalSix and @bspidel)

___
*[src/js/actions/ProjectDetailsActions.js, line 15 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5227#-LP0bVqWEO6rRgQPPFAp:-LP0bVqWEO6rRgQPPFAq:b-k01dna) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/99b7df33f13e5de5f8388d7c54941d5796efe68b/src/js/actions/ProjectDetailsActions.js#L15)):*
> ```JavaScript
> import * as ProjectOverwriteHelpers from "../helpers/ProjectOverwriteHelpers";
> import * as GogsApiHelpers from "../helpers/GogsApiHelpers";
> import git from '../helpers/GitApi.js';
> ```

Importing gitApi here after GogsApiHelpers has imported it will cause problem.  Probably should make your git().save() a function in GogsApiHelpers (there may already be one).

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5227)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @RoyalSix and @bspidel)

**Comment by RoyalSix** [comment]
@PhotoNomad0 What problem will it cause? 
The two files have separate responsibilities. I don't need to use gogs just git so I imported it

**Comment by PhotoNomad0** [comment]
@RoyalSix - I suppose I was just seeing warnings in Intelij, I guess if you can get this to work this way then it's OK.

**Comment by mannycolon** [comment]
Local Test: `LGTM`

**Review by mannycolon — APPROVED** [review]
> Reviewed 6 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5227)* status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix and @bspidel)

**Pull request merged**
