### PR TITLE
Updates From QA Fail 4318

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- The issues brought up in the comment by koz at the end should be resolved expect for the 10th one
https://github.com/unfoldingWord-dev/translationCore/issues/4318

You will need the checkout `feature-jay-4318` on translationWords repo
#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (ae5f020)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-ae5f020.zip) is ready for download.
[macOS build 0.10.0 (ae5f020)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-ae5f020.dmg) is ready for download.
[Windows x64 build 0.10.0 (ae5f020)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-ae5f020.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (ae5f020)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-ae5f020.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (02cab55)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-02cab55.zip) is ready for download.
[macOS build 0.10.0 (02cab55)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-02cab55.dmg) is ready for download.
[Windows x64 build 0.10.0 (02cab55)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-02cab55.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (02cab55)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-02cab55.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@RoyalSix - still seeing QA issue:

~The thelps panel no longer is automatically displayed when the tool is opened.~

had wrong tw branch.

**Comment by RoyalSix** [comment]
@PhotoNomad0 Do you see blue progress bars for the Group Menu?

**Comment by PhotoNomad0** [comment]
@RoyalSix - sorry I didn't notice problem checking out tw - you have a typo in the branch name.  problem went away.

**Comment by RoyalSix** [comment]
Oh shoot! [bitmoji](https://render.bitstrips.com/v2/cpanel/27c34645-4e03-42a5-bb21-c48c76fcacfe-d401e257-9857-4c27-b494-6ef332b054a7-v1.png?transparent=1&palette=1&width=246)

**Comment by RoyalSix** [comment]
Oh no! bitmoji

**Comment by PhotoNomad0** [comment]
@RoyalSix - still seeing QA fail number 7 : When the text in the check pane is expanded, the book name appears above the close ‘X’ rather than in the center of the title bar.

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617#-:-LF-1St81i9owmlK9TQB:bnfp4nl)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (81adbec)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-81adbec.zip) is ready for download.
[macOS build 0.10.0 (81adbec)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-81adbec.dmg) is ready for download.
[Windows x64 build 0.10.0 (81adbec)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-81adbec.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (81adbec)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-81adbec.setup.exe) is ready for download.

**Comment by richmahn** [comment]
Ah, the branch typo name was talked about a few hours ago! Wish I had seen that...threw me off.

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617#-:-LF-_Q3pDpe_BKey1P_i:b52o5jr)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (45adf57)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-45adf57.zip) is ready for download.
[macOS build 0.10.0 (45adf57)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-45adf57.dmg) is ready for download.
[Windows x64 build 0.10.0 (45adf57)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-45adf57.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (45adf57)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-45adf57.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617)*

**Comment by PhotoNomad0** [comment]
@RoyalSix  - I checked again with 0.9.2, but I still see the issue in tw that 0 is next to filter icon when minimized.

**Comment by PhotoNomad0** [comment]
@RoyalSix - never-mind, the concourse build is working.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4617#-:-LF28rNO5Xu6TftpcmLK:bnfp4nl)*

**Pull request merged**
