### PR TITLE
Remove Highlighting From Verse Check When Not Applicable

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR makes the select mode area the only place where a user can select/highlight when using the checking tool.

#### How to test this pull request:
`git checkout enhancement/jay/remove-highlight/2295` in Verse Check
Try highlighting the areas specified in #2295 and make sure they are not selectable/highlightable

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2306)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/css/styles.css, line 267 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306#-Kq8iIzqoHxs7PaAmqq1:-Kq8iIzqoHxs7PaAmqq2:b-bzie5l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9556a18a5f0a77e2f8b2fda6337335308f5bf62a/src/css/styles.css#L267)):*
> ```CSS
>     -moz-user-select: none;
>     -ms-user-select: none;
>     user-select: none;
> ```

We only need the one for Chrome. There's no need for cross browser compatibility.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306)*

**Comment by klappy** [comment]
*[src/css/styles.css, line 267 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306#-Kq8iIzqoHxs7PaAmqq1:-Kq8iQWDBO5Vk_a4ewq0:b-1q9dkn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9556a18a5f0a77e2f8b2fda6337335308f5bf62a/src/css/styles.css#L267)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We only need the one for Chrome. There's no need for cross browser compatibility.
</blockquote></details>

Also, this is a concern of the tool. This shouldn't be done here in the core.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306)*

**Comment by klappy** [comment]
*[tC_apps/VerseCheck, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306#-Kq8iZjgvhjt6sDQOzzw:-Kq8iZjgvhjt6sDQOzzx:bnabb5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c07f6782b23569eac5abeb28e5abb0a0f2a95595/tC_apps/VerseCheck#L1)):*
> ```
> Subproject commit 0a678d15172893e94c7b13224199c0c633f66090
> ```

We shouldn't commit these, just ignore them in PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306)*

**Comment by klappy** [comment]
@royalsix: When I fixed this a few weeks ago, it was a simple fix in the tool without a lot of changes, and no changes to the core.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306#-:-Kq8iejvr6kyo39Xlmy_:b-hl77ki)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/css/styles.css, line 267 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306#-Kq8iIzqoHxs7PaAmqq1:-Kq8krpPcnBpjwj0ZstP:bi6n0b5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9556a18a5f0a77e2f8b2fda6337335308f5bf62a/src/css/styles.css#L267)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Also, this is a concern of the tool. This shouldn't be done here in the core.
</blockquote></details>

agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2306)*

**Pull request closed without merging**
