### PR TITLE
Edit Verse Checking Performance Imporovement

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- These changes reduce the number of re-renders and also reduce the time of re-renders for components involved in the verse checking lifecycle. From performance testing, it seems that the overall time spent when waiting for a verse edit change is spent on unnecessary react/redux operations.

#### Please include detailed Test instructions for your pull request:
To test this PR you will need to ensure the performance change is prevalent.
NOTE: to exaggerate performance improvements please throttle CPU or use a slow machine.
1. Grab the latest tC build 
2. Open a project such as [this](https://github.com/unfoldingWord-dev/translationCore/files/3709325/en_ult_mrk_book.zip) one
3. Open tW or tN
4. Make a verse edit from the check pane and scripture pane. **Record the time it takes for both**
5. Repeat steps 2 - 4 with the build at the bottom of this PR and ensure the new time is faster.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6480)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (420bda8)](https://tc-builds.door43.org/build/feature-jay-6472/translationCore-linux-x64-2.0.0-420bda8.deb) is ready for download.
[macOS build 2.0.0 (420bda8)](https://tc-builds.door43.org/build/feature-jay-6472/translationCore-macos-x64-2.0.0-420bda8.dmg) is ready for download.
[Windows x64 build 2.0.0 (420bda8)](https://tc-builds.door43.org/build/feature-jay-6472/translationCore-win-x64-2.0.0-420bda8.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (420bda8)](https://tc-builds.door43.org/build/feature-jay-6472/translationCore-win-x32-2.0.0-420bda8.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Tested - Jay's changes, build 420bda8: 
- tW amazed:
  - Mac: check edit - Mk 1:27 - 3 sec, SP edit - Mk 2:12 - 3 s 
  - Win: check edit- Mk 1:27 - 7 sec, SP edit - Mk 2:12 - 8 s 

Tested - 28ba6a8 build: 
- tW amazed:
  - Mac: check edit - Mk 1:27 - 5 sec, SP edit - Mk 2:12 - 6 s 
  - Win: check edit- Mk 1:27 - 13.5 sec, SP edit - Mk 2:12 - 17.5 s

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6480)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
**Notes:**

Builds:
- Jay's changes, build 420bda8: 
- Latest develop,  28ba6a8 build

Testing in tW amazed using [ULT Mat](https://github.com/unfoldingWord-dev/translationCore/files/3709325/en_ult_mrk_book.zip) 

**Timing of edit and validation checking:**

Mac: 
- **Jays changes:** check edit - Mk 1:27 - 3 sec, SP edit - Mk 2:12 - 3 s 
- **develop branch:** check edit - Mk 1:27 - 5 sec, SP edit - Mk 2:12 - 6 s 

Win 64:
  - **Jays changes:** check edit- Mk 1:27 - 7 sec, SP edit - Mk 2:12 - 8 s 
  - **develop branch:** check edit- Mk 1:27 - 13.5 sec, SP edit - Mk 2:12 - 17.5 s

**Pull request merged**
