### PR TITLE
Added collapsible submenu to Group Menu

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Added collapsible submenu to Group Menu

#### How to test this pull request:

NOTICE: 
There is a data issue in tW, where the entire header is in the quote, and it should be the quote only.
This is a separate issue and needs to be addressed.

- Open a project and tool.
- Expand/Collapse submenu in the Group Menu.
- CAUTION: Only use headers with single words until data issue is resolved.
- Click on another menu to ensure that it opens as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2490)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/groupMenu/Group.js, line 36 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks2QM2RmsdL2ig2j2E3:-Ks2QM2RmsdL2ig2j2E4:b-g262rh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/components/groupMenu/Group.js#L36)):*
> ```JavaScript
>           </div>
>         </div>
>         {this.props.active && isSubMenuExpanded ? this.props.getGroupItems(this) : null}
> ```

just wondering if its necessary to know if the check is both active and expanded. Couldn't they be consolidated to just one check (active of isSubMenuExpanded)? Same with the logic above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GroupMenuActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks4AggzwmakjktUSoAa:-Ks4AggzwmakjktUSoAb:b-uni5c9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/actions/GroupMenuActions.js#L8)):*
> ```JavaScript
>  */
> 
> export const groupMenuExpandSubMenu = (isSubMenuExpanded) => {
> ```

can we just call this action expandSubmenu or is toggleSubMenu more descriptive? assuming it actually expands and closes it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by mannycolon** [comment]
@klappy Please merge with develop and resolve merge conflicts

**Comment by mannycolon** [comment]
@klappy @RoyalSix Tests passed on my end.

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/components/groupMenu/Group.js, line 36 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks2QM2RmsdL2ig2j2E3:-Ks5Fgw8JIrqpm2l5uLs:b2ni9he) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/components/groupMenu/Group.js#L36)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

just wondering if its necessary to know if the check is both active and expanded. Couldn't they be consolidated to just one check (active of isSubMenuExpanded)? Same with the logic above
</blockquote></details>

or*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by klappy** [comment]
*[src/js/actions/GroupMenuActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks4AggzwmakjktUSoAa:-Ks5M2-Cg6loxEJqsdVx:btscl0d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/actions/GroupMenuActions.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we just call this action expandSubmenu or is toggleSubMenu more descriptive? assuming it actually expands and closes it.
</blockquote></details>

I struggled with the name of this one. I still don't have the right name, but here was my thinking:

We have so many actions, that I made this one namespaced to be less confusing.
We basically have top level action that would say toggle submenu, but we don't have context to know what submenu. Is it top menu across the top? is it the submenu of the FAB or the 3 dot button?

It doesn't toggle because I needed more control over toggling. 
There are only explicit times when we collapse and explicit times where we expand. 
I almost made two actions, one for expand, one for collapse to be explicit, in fact its less confusing.

What about `GroupSubMenuExpand` and `GroupSubMenuCollapse`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by klappy** [comment]
*[src/js/components/groupMenu/Group.js, line 36 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks2QM2RmsdL2ig2j2E3:-Ks5NChMQHDtRv0KSK38:b-sf90p0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/components/groupMenu/Group.js#L36)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

or*
</blockquote></details>

I combined the logic at first and then realized we need a way to show what the active Group or Main Group Menu item is even when it is collapsed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/actions/GroupMenuActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks4AggzwmakjktUSoAa:-Ks5ZjP9azq9n0g6c_DN:bcqsbbo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/actions/GroupMenuActions.js#L8)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I struggled with the name of this one. I still don't have the right name, but here was my thinking:

We have so many actions, that I made this one namespaced to be less confusing.
We basically have top level action that would say toggle submenu, but we don't have context to know what submenu. Is it top menu across the top? is it the submenu of the FAB or the 3 dot button?

It doesn't toggle because I needed more control over toggling. 
There are only explicit times when we collapse and explicit times where we expand. 
I almost made two actions, one for expand, one for collapse to be explicit, in fact its less confusing.

What about `GroupSubMenuExpand` and `GroupSubMenuCollapse`?
</blockquote></details>

when you call this action you should do it as follow which gives you more context

```
GroupMenuActions.ExpandSubMenu()

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by klappy** [comment]
*[src/js/actions/GroupMenuActions.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-Ks4AggzwmakjktUSoAa:-Ks5_ssmfnxPVC1dV-PJ:b2nhksp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/cdb26314f1f00cbaf8675d74c08c595d9ff5386f/src/js/actions/GroupMenuActions.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

when you call this action you should do it as follow which gives you more context

```
GroupMenuActions.ExpandSubMenu()

```
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2490#-:-Ks5dk-0djl1O6jcGIcp:bnfp4nl)*

**Pull request merged**
