### PR TITLE
Local Import (without USFM support)

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

.tstudio and .tcore projects are imported into the imports folder

#### How to test this pull request:

This PR can be merged to allow project migrations and project validation development.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3313)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 74 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dk9TtmIBGq0ET8U0F:-L-Dk9TtmIBGq0ET8U0G:b-efg5da) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/actions/Import/LocalImportWorkflowActions.js#L74)):*
> ```JavaScript
>     // dispatch(migrate());
>     // dispatch(validate());
>     // dispatch(move());
> ```

Can these comments can be removed?

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 8 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dkgb5eUJShB15wWHI:-L-Dkgb5eUJShB15wWHJ:bivis71) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L8)):*
> ```JavaScript
> export const convertToProjectFormat = () => {
> 
> };
> ```

Is this for future code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313)*

**Comment by richmahn** [comment]
*[src/js/actions/Import/LocalImportWorkflowActions.js, line 74 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dk9TtmIBGq0ET8U0F:-L-FJ2-lfTyyBSVTYiFK:b-r41jpc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/actions/Import/LocalImportWorkflowActions.js#L74)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Can these comments can be removed?
</blockquote></details>

They aren't comments, they are place holders since we are doing this in parts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313)*

**Comment by richmahn** [comment]
*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 8 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dkgb5eUJShB15wWHI:-L-FJGzjPpXgTOUDV5HQ:b-3ndewu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L8)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Is this for future code?
</blockquote></details>

Also wondering what this is for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-:-L-FIpQ0QM0uSgCN8ID4:bnfp4nl)*

**Comment by mannycolon** [comment]
Review status: 12 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 74 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dk9TtmIBGq0ET8U0F:-L-HtS3fmkXGTz8V8374:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/actions/Import/LocalImportWorkflowActions.js#L74)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

They aren't comments, they are place holders since we are doing this in parts.
</blockquote></details>

Done.

---

*[src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js, line 8 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-L-Dkgb5eUJShB15wWHI:-L-HtAz9h-Sy8tu6bZXY:b-99rs2c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/36240b0c64e16669e16ad9221e94a6c43f325d4d/src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js#L8)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Also wondering what this is for.
</blockquote></details>

future code. remember we build a skeleton where we want to have the code.
USFM conversion occurs here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3313#-:-L-J6R7b1CSUH0bQ1lzY:bnfp4nl)*

**Pull request merged**
