### PR TITLE
Removed static folder and added resources submodule

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR removes the old static folder and brings in the resources as a self contained module

#### How to test this pull request:
Make sure everything in the app works the same as far as data is concerned (tN, tW)
Note: The scripture pane is not functional due to another issue on develop

Also make sure that the submodule looks as expected, folder structure/configuration wise

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2630)

### CODE REVIEW

**Comment by mannycolon** [comment]
Please merge with develop & resolve merge conflicts

**Comment by mannycolon** [comment]
- Pull this branch and the `tC_resources` folder was empty.
- Also `tC_resources`  should include the resources updater script.

**Comment by RoyalSix** [comment]
@mannycolon you have to run ```npm run install-apps``` just like how we do tC_apps

**Comment by mannycolon** [comment]
@RoyalSix 
The script in the package.json should not look as follow
It should be updated.
```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "update-resource": "babel-node scripts/resources/index.js",
    "update-en-resource": "babel-node scripts/resources/index.js en",
    "prettier-resource": "prettier --single-quote --print-width 80 --trailing-comma all --write 'static/**/*.json'"
  }
```

**Comment by RoyalSix** [comment]
@mannycolon what should it be updated to ?

**Comment by mannycolon** [comment]
@RoyalSix it should point to the index.js inside `tC_resources` folder, not the index.js in `scripts/resources/`

and 

```
    "prettier-resource": "prettier --single-quote --print-width 80 --trailing-comma all --write 'static/**/*.json'"
```
 should be


```
    "prettier-resource": "prettier --single-quote --print-width 80 --trailing-comma all --write 'resources/**/*.json'"
```

**Comment by klappy** [comment]
The scripts still don't work in this submodule.
I should be able to switch to this directory, then: 
run the `npm run ...` commands and they should work like they did before.

Although I'm not sure the right commands and how the scripts work, I think the package.json should have scripts that look more like:
```js
    "update-resource": "babel-node ./index.js",
    "update-en-resource": "babel-node ./index.js en",
```

**Comment by RoyalSix** [comment]
@klappy  after running ```npm run pull-apps``` the scripts should be updated

**Pull request merged**
