### PR TITLE
Fix github action uploads

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Related to https://github.com/unfoldingword/translationcore/issues/6892
- Updated the upload artifact action version. Hopefully that fixes the problem.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6896)

### CODE REVIEW

**Comment by da1nerd** [comment]
I guess updating the artifact uploader broke some other things instead of fixing anything.

**Comment by da1nerd** [comment]
@PhotoNomad0 are you still seeing this issue? Do we need to keep pursuing a solution?

**Comment by PhotoNomad0** [comment]
@neutrinog - haven't seen the problem again.

@birchamp - Let's discuss what to do with the issue.

**Comment by da1nerd** [comment]
I'm closing this for now since there's been no activity.

**Pull request closed without merging**
