### PR TITLE
QA_Fail-4949/Fixes for two and three button dialogs.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated alert container to call callback if callback2 not defined to support original behavior.
- Reverted changes to dialogs with two and three buttons.

#### Please include detailed Test instructions for your pull request:
- test build at bottom of PR.  It should fix behavior listed in issue where dialog actions were reversed.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4958)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (cbf5ea5)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-cbf5ea5.zip) is ready for download.
[macOS build 1.0.0 (cbf5ea5)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-cbf5ea5.dmg) is ready for download.
[Windows x64 build 1.0.0 (cbf5ea5)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-cbf5ea5.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (cbf5ea5)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-cbf5ea5.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (3c54f76)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-3c54f76.zip) is ready for download.
[macOS build 1.0.0 (3c54f76)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-3c54f76.dmg) is ready for download.
[Windows x64 build 1.0.0 (3c54f76)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-3c54f76.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (3c54f76)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-3c54f76.setup.exe) is ready for download.

**Review by mannycolon — CHANGES_REQUESTED** [review]
should not go back to the previous version of openOptionDialog

**Review by mannycolon — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4958)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]

**Comment by mannycolon** [comment]
Pending Local Testing

**Pull request merged**
