### PR TITLE
Resetting alignment reducer data

### PR DESCRIPTION
**Pull request by mannycolon**
# This pull request addresses:
- #2881 
- #2827 

# How to test this pull request:
- Open a Titus project with the `wordAlignment` tool
- Drag a word to the dropped zone.
- Then go to the home screen page and click on until you get to the `tools`  page again and click launch on the `wordAlignment` tool. 
(You should not get any errors)

# Other test
- Open a Titus project with the `wordAlignment` tool
- Drag a word to the dropped zone.
- Then go to the home screen page and import a different project. 
(You should not get any errors)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2894)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@mannycolon For the first test it looks good. I got this error. Not sure if its related. 
screen shot 2017-10-10 at 2 17 43 pm
It happens when dragging

**Comment by RoyalSix** [comment]
@mannycolon The second test passes great 👍

**Comment by RoyalSix** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2894)*

**Comment by mannycolon** [comment]
@RoyalSix that is unrelated and has been happening before.

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2894)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2894#-:-KwBE1zK0GLWyVxfERR6:bnfp4nl)*

**Pull request merged**
