### PR TITLE
Refactored CheckdataGrabber

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/236)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236#-:-KUXeAwD30pbP3mZYS1C:bnfp4nl)_

**Comment by mannycolon** [comment]
@RoyalSix 
screen shot 2016-10-20 at 11 29 04 am

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236)_

**Comment by mannycolon** [comment]
screen shot 2016-10-20 at 11 46 58 am

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/GitApi.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236#-KUY47cDpov_zxpw_xbd:-KUY47cDpov_zxpw_xbe:b-ed67gw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d69e54208272bffdc2927033f358af3ee934ffa/src/js/components/core/GitApi.js#L9)):_

> ``` JavaScript
>  **/
> function GitApi(directory) {
>   debugger;
> ```

do we still need the debugger here??

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236)_

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236#-:-KUY4MfJOy2TYJruX0yk:bnfp4nl)_

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/js/components/core/GitApi.js, line 9 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236#-KUY47cDpov_zxpw_xbd:-KUYAYI2AJYA7oFjq0T8:bb6un1j) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8d69e54208272bffdc2927033f358af3ee934ffa/src/js/components/core/GitApi.js#L9)):_
<details><summary>

<i>Previously, mannycolon (Manny Colon) wrote…</i></summary>



> do we still need the debugger here??
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236)_

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/236)_

**Pull request merged**
