### PR TITLE
USFM Import

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR allows user to import usfm files to start tC projects.
User can choose the usfm file or the containing folder.
Import USFM functionality can be accessed through import local project FAB button or copying and pasting an already imported project folder into ~/tC
Once imported from the FAB button the project folder with be visible from the projects screen.

#### How to test this pull request:
Use some of these usfm [projects](https://github.com/unfoldingWord-dev/translationCore/files/1147163/LDH.tCore.training.-.USFM.files.1.zip) and test importing them

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2151)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/ProjectSelectionActions.js, line 83 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1SQ5DJZSg6ORqVhmI:-Kp1SQ5EBPiSNKQTWKYy:b-dohzmc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/570d45bcbfa0ece1e731197fb3136509372ba2b5/src/js/actions/ProjectSelectionActions.js#L83)):*
> ```JavaScript
>  * @description loads and set the projects details into the projectDetailsReducer.
>  * @param {string} projectPath - path location in the filesystem for the project.
>  * @param {object} manifest - project manifest.
> ```

can you add documentation for the changed params?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
*[src/js/actions/ProjectSelectionActions.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1SWuXe6CZVPcAsAPd:-Kp1SWuXe6CZVPcAsAPe:b-3axdpc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4785df54048895edacb50f3a76aa0c64d6ce1c40/src/js/actions/ProjectSelectionActions.js#L75)):*
> ```JavaScript
>     dispatch(ProjectDetailsActions.setProjectManifest(manifest));
>     dispatch(ProjectDetailsActions.setProjectDetail("bookName", manifest.project.name));
>     const params = LoadHelpers.getParams(projectPath, manifest);
> ```

params appear to be set in the params, but then in this new context created. Is this on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
*[src/js/helpers/ProjectSelectionHelpers.js, line 35 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1T_k7wMovieMdZWfo:-Kp1T_k7wMovieMdZWfp:bud4pd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/570d45bcbfa0ece1e731197fb3136509372ba2b5/src/js/helpers/ProjectSelectionHelpers.js#L35)):*
> ```JavaScript
>  * @param {string} username - Current username of user logged in.
>  */
> export function getUSFMProjectManifest(projectPath, projectLink, parsedUSFM, direction, username) {
> ```

Since these are explicitly USFM functions, should we move these to USFMProjectHelpers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
*[src/js/helpers/ProjectSelectionHelpers.js, line 35 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1T_k7wMovieMdZWfo:-Kp1TmV4Qh6iQC8hwvnN:btvohat) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/570d45bcbfa0ece1e731197fb3136509372ba2b5/src/js/helpers/ProjectSelectionHelpers.js#L35)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Since these are explicitly USFM functions, should we move these to USFMProjectHelpers?
</blockquote></details>

Or not. After reading I see how these functions make sense here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
*[src/js/actions/TargetLanguageActions.js, line 133 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1UGZ6vf4dQvjNtBow:-Kp1UGZ6vf4dQvjNtBox:b-jt1lnl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4785df54048895edacb50f3a76aa0c64d6ce1c40/src/js/actions/TargetLanguageActions.js#L133)):*
> ```JavaScript
>  */
> function archiveSourceFiles(finishedChunks, projectPath) {
>   finishedChunks.forEach((element, index) => {
> ```

At some point, we need to remove the dependency on Finished Chunks. This was removed and then added back. 0.7.0 Did not require it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
Can you add support for the projects you attached? They have `.SFM` extensions and our code requires changing all filenames to `.usfm`.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-:-Kp1UfXDqSEs0EW0b1jO:b-vraw2s)*

**Comment by RoyalSix** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectSelectionActions.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1SWuXe6CZVPcAsAPd:-Kp1mGRwfc7TuEoGuY-D:b-uqqshf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4785df54048895edacb50f3a76aa0c64d6ce1c40/src/js/actions/ProjectSelectionActions.js#L75)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

params appear to be set in the params, but then in this new context created. Is this on purpose?
</blockquote></details>

The params are coming from the selectProject function and then are being set here later on after everything project details related is loaded

---

*[src/js/actions/ProjectSelectionActions.js, line 83 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1SQ5DJZSg6ORqVhmI:-Kp1mBaWS_Oz2m8IPnWu:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/570d45bcbfa0ece1e731197fb3136509372ba2b5/src/js/actions/ProjectSelectionActions.js#L83)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

can you add documentation for the changed params?
</blockquote></details>

Done.

---

*[src/js/actions/TargetLanguageActions.js, line 133 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1UGZ6vf4dQvjNtBow:-Kp1mVauWEmlH-3zG9iJ:bt09k3d) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4785df54048895edacb50f3a76aa0c64d6ce1c40/src/js/actions/TargetLanguageActions.js#L133)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

At some point, we need to remove the dependency on Finished Chunks. This was removed and then added back. 0.7.0 Did not require it.
</blockquote></details>

I agree. this story didn't require it but its not something we should continue to use.

---

*[src/js/helpers/ProjectSelectionHelpers.js, line 35 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151#-Kp1T_k7wMovieMdZWfo:-Kp1md6uujR7DYmU4s6-:b-2s2wa6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/570d45bcbfa0ece1e731197fb3136509372ba2b5/src/js/helpers/ProjectSelectionHelpers.js#L35)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Or not. After reading I see how these functions make sense here.
</blockquote></details>

I was something I thought about. I could have created to entirely separate file for loading USFM verses a standard project. They would have shared about 90% of code though so didn't think it was necessary. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
Reviewed 5 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2151)*

**Pull request merged**
