### PR TITLE
Fix macOS and Windows builds in Github Actions

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This fixes the macOS builds in the Github Actions. See #6648 
- Fixes problem with cloning the repository in the windows environment. See #6650 

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6649)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (b597e67)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-b597e67.deb) is ready for download.
[macOS build 2.1.0 (b597e67)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-b597e67.dmg) is ready for download.
[Windows x64 build 2.1.0 (b597e67)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-b597e67.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (b597e67)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-b597e67.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (c551791)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-c551791.deb) is ready for download.
[macOS build 2.1.0 (c551791)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-c551791.dmg) is ready for download.
[Windows x64 build 2.1.0 (c551791)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-c551791.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (c551791)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-c551791.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (3e1f6bf)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-3e1f6bf.deb) is ready for download.
[macOS build 2.1.0 (3e1f6bf)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-3e1f6bf.dmg) is ready for download.
[Windows x64 build 2.1.0 (3e1f6bf)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-3e1f6bf.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3e1f6bf)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-3e1f6bf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (aebb07e)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-aebb07e.deb) is ready for download.
[macOS build 2.1.0 (aebb07e)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-aebb07e.dmg) is ready for download.
[Windows x64 build 2.1.0 (aebb07e)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-aebb07e.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (aebb07e)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-aebb07e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (e0b3864)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-e0b3864.deb) is ready for download.
[macOS build 2.1.0 (e0b3864)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-e0b3864.dmg) is ready for download.
[Windows x64 build 2.1.0 (e0b3864)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-e0b3864.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (e0b3864)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-e0b3864.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (62c8595)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-62c8595.deb) is ready for download.
Some builds failed

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (56674be)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-56674be.deb) is ready for download.
[macOS build 2.1.0 (56674be)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-56674be.dmg) is ready for download.
[Windows x64 build 2.1.0 (56674be)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-56674be.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (56674be)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-56674be.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
Some builds failed

**Comment by da1nerd** [comment]
@birchamp I'm not sure if you want to include this in the current sprint, but this fixes problems with github actions.

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (75ae321)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-75ae321.deb) is ready for download.
[macOS build 2.1.0 (75ae321)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-75ae321.dmg) is ready for download.
[Windows x64 build 2.1.0 (75ae321)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-75ae321.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (75ae321)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-75ae321.setup.exe) is ready for download.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6649)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by dsm-git** [comment]
[Linux build 2.1.0 (8abf69c)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-linux-x64-2.1.0-8abf69c.deb) is ready for download.
[macOS build 2.1.0 (8abf69c)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-macos-x64-2.1.0-8abf69c.dmg) is ready for download.
[Windows x64 build 2.1.0 (8abf69c)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x64-2.1.0-8abf69c.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (8abf69c)](https://tc-builds.door43.org/build/bugfix-joel-github-actions/translationCore-win-x32-2.1.0-8abf69c.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@neutrinog - well, it builds.  Concerned about all the changes in package-lock just because dependency changes have caused us much grief in the past.  Trying to think through how to verify the builds in the absence of integration testing.  It looks like most are related to babel and http communication.  So maybe just need to validate that tCore runs, and verify that Door43 uploads and downloads still work?

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @neutrinog)

**Comment by PhotoNomad0** [comment]
LGTM - testing Windows and Mac builds

**Pull request merged**
