### PR TITLE
Optimized Initial start up of tC

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-  Optimized Initial startup time of tC

#### Please include detailed Test instructions for your pull request:
- Start up the app w/ `npm start`
- tC should open within 9-30 sec compared to 1-1:30 mins in the past or currently in develop branch (stats may defer based on your laptops specs)
- Do the same test on the build created by `DSM BOT`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5539)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (94ed7fa)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-94ed7fa.deb) is ready for download.
[macOS build 1.1.0 (94ed7fa)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-94ed7fa.dmg) is ready for download.
[Windows x64 build 1.1.0 (94ed7fa)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-94ed7fa.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (94ed7fa)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-94ed7fa.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (110c2a0)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-110c2a0.deb) is ready for download.
[macOS build 1.1.0 (110c2a0)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-110c2a0.dmg) is ready for download.
[Windows x64 build 1.1.0 (110c2a0)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-110c2a0.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (110c2a0)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-110c2a0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d3a54d2)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-d3a54d2.deb) is ready for download.
[macOS build 1.1.0 (d3a54d2)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-d3a54d2.dmg) is ready for download.
[Windows x64 build 1.1.0 (d3a54d2)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-d3a54d2.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d3a54d2)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-d3a54d2.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0a8f936)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-0a8f936.deb) is ready for download.
[macOS build 1.1.0 (0a8f936)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-0a8f936.dmg) is ready for download.
[Windows x64 build 1.1.0 (0a8f936)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-0a8f936.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0a8f936)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-0a8f936.setup.exe) is ready for download.

**Review by da1nerd — DISMISSED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5539)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by da1nerd** [comment]
@mannycolon update your branch and this will be good to go.

**Review by da1nerd — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5539)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
