### PR TITLE
CheckData Grabber Tests

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/423)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/h.CheckDataGrabber.js, line 96 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423#-KZZ0FLTrDBVMNq5xx-2:-KZZ0FLUcOJAEClblwgd:b5snqm1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a344625ea1cd37d58bbac775b2b94d5582120d1c/tests/h.CheckDataGrabber.js#L96)):*
> ```JavaScript
> };
> 
> describe('CheckDataGrabber.saveModules', function () {
> ```

Try including a test for missing/null parameters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423)*

**Comment by ihoegen** [comment]
Also checkout: https://travis-ci.org/unfoldingWord-dev/translationCore/builds/185699987#L1624

**Comment by RoyalSix** [comment]
fixed

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423#-:-K_12pdaGOAovVHM5T27:b-7ql1td)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/h.CheckDataGrabber.js, line 96 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423#-KZZ0FLTrDBVMNq5xx-2:-K_12rlGum9fDB0sCxio:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/a344625ea1cd37d58bbac775b2b94d5582120d1c/tests/h.CheckDataGrabber.js#L96)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Try including a test for missing/null parameters
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423)*

**Comment by ihoegen** [comment]
@RoyalSix Did you push this fix? I'm not seeing it

**Comment by ihoegen** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/h.CheckDataGrabber.js, line 139 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423#-K_55jJDb8dtOrHWUKBg:-K_55jJDb8dtOrHWUKBh:btsj6li) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d48ce43bbc7f899c1b69a974398d70b1f9a36c10/tests/h.CheckDataGrabber.js#L139)):*
> ```JavaScript
>     it('should load a tool', function (done) {
>         CheckDataGrabber.loadModuleAndDependencies(testTool, (err, success) => {
>             console.log(err)
> ```

I think you should remove these logs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423)*

**Comment by RoyalSix** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/h.CheckDataGrabber.js, line 139 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423#-K_55jJDb8dtOrHWUKBg:-K_5JE4yy6-AdC-LYX3x:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d48ce43bbc7f899c1b69a974398d70b1f9a36c10/tests/h.CheckDataGrabber.js#L139)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I think you should remove these logs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423)*

**Comment by ihoegen** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/423)*

**Pull request merged**
