### PR TITLE
fixed multiple bugs in containers and change them to es6 syntax

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:
test all functionality related to containers

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1140)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/containers/ImportOnlineContainer.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEAx2-EKEAMprQhgwS:-KiEAx20ypI-2-t5rr5Y:b91vohp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/ImportOnlineContainer.js#L8)):*
> ```JavaScript
> import OnlineInput from '../components/core/OnlineInput';
> // Actions
> import * as importOnlineActions from '../actions/ImportOnlineActions.js';
> ```

I don't believe an * import is necessary 

---

*[src/js/containers/LoaderContainer.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB1nztk451YH6bShP:-KiEB1nztk451YH6bShQ:budwf7v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/LoaderContainer.js#L6)):*
> ```JavaScript
> import Loader from '../components/core/Loader';
> // Actions
> import * as LoaderActions from '../actions/LoaderActions.js';
> ```

Ibid. 

---

*[src/js/containers/LoadModalContainer.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB5E1UNYClfhrAnBt:-KiEB5E1UNYClfhrAnBu:bb6xk7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/LoadModalContainer.js#L15)):*
> ```JavaScript
> import * as ReportsActions from '../actions/ReportsActions.js';
> import * as recentProjectsActions from '../actions/RecentProjectsActions.js';
> import * as ModalActions from '../actions/ModalActions';
> ```

Ibid

---

*[src/js/containers/ModalContainer.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB92fj0KVycCD-15j:-KiEB92fj0KVycCD-15k:b-86nv4b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/ModalContainer.js#L12)):*
> ```JavaScript
> import packageJson from '../../../package.json';
> // actions
> import * as modalActions from '../actions/ModalActions.js';
> ```

Ibid.

---

*[src/js/containers/RecentProjectsContainer.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBBmWL7PwSLT2LiXY:-KiEBBmWL7PwSLT2LiXZ:b-86nv4b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/RecentProjectsContainer.js#L9)):*
> ```JavaScript
> import RecentProjects from '../components/core/RecentProjects';
> // actions
> import * as recentProjectsActions from '../actions/RecentProjectsActions.js';
> ```

Ibid.

---

*[src/js/containers/RecentProjectsContainer.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBQSku8RSfjax32Yq:-KiEBQSku8RSfjax32Yr:b2nhji7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/RecentProjectsContainer.js#L75)):*
> ```JavaScript
> 
>   render() {
>     console.log(this.props.manifest)
> ```

Log

---

*[src/js/utils/loadMethods.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBINln_zwNKxbI_-Q:-KiEBINln_zwNKxbI_-R:b-hc5x5p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/utils/loadMethods.js#L21)):*
> ```JavaScript
>       settings = fs.readJsonSync(SETTINGS_DIRECTORY);
>     } else {
>       console.log("No settings file found therefore it will be created when the settings reducer is fully loaded");
> ```

I don't think this is something that has to be logged. This seems more of a comment than anything. 

---

*[src/js/utils/loadMethods.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBFdP6qXGzwmmy6Qn:-KiEBFdP6qXGzwmmy6Qo:bxx7k7i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/utils/loadMethods.js#L38)):*
> ```JavaScript
>     if (fs.existsSync(MODULES_SETTINGS_DIRECTORY)) {
>       let modulesSettings = fs.readJsonSync(MODULES_SETTINGS_DIRECTORY);
>       console.log(modulesSettings)
> ```

Do we want to log this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/js/containers/AlertModalContainer.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEC3lu3-REJmoZwyf8:-KiEC3lu3-REJmoZwyf9:bemrr7t) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/AlertModalContainer.js#L1)):*
> ```JavaScript
> import React from 'react';
> ```

Also, is there anything that triggers AlertModals anymore? I know the console.error function no longer opens an error modal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/js/containers/AlertModalContainer.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEC3lu3-REJmoZwyf8:-KiFuWdVLr95Wqw8JQcu:b-vwz62z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/AlertModalContainer.js#L1)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Also, is there anything that triggers AlertModals anymore? I know the console.error function no longer opens an error modal
</blockquote></details>

it is not being triggered anymore but we may need to make it work again in the future. it is disabled because it was using the API and was causing bugs.

---

*[src/js/containers/ImportOnlineContainer.js, line 8 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEAx2-EKEAMprQhgwS:-KiFugkXN3NAl8D-cc5i:b-kxdc9w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/ImportOnlineContainer.js#L8)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't believe an * import is necessary 
</blockquote></details>

Actually, it is necessary. For example,  * import allows the following

```
 importOnlineActions.openOnlineProject(projectPath)

```
The other option would be 

```
import {openOnlineProject} from '../actions/ImportOnlineActions.js';

openOnlineProject(projectPath)

```
however, I don't necessarily need to do that.

---

*[src/js/containers/LoaderContainer.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB1nztk451YH6bShP:-KiFw7E-nf0nexYr_9SJ:bsilkm9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/LoaderContainer.js#L6)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Ibid. 
</blockquote></details>

look above

---

*[src/js/containers/LoadModalContainer.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB5E1UNYClfhrAnBt:-KiFvPJDGseau5KMRLhQ:b-9jnm0v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/LoadModalContainer.js#L15)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Ibid
</blockquote></details>

Look above

---

*[src/js/containers/ModalContainer.js, line 12 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEB92fj0KVycCD-15j:-KiFvQrHrxzWtjMCxyTO:b-9jnm0v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/ModalContainer.js#L12)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Ibid.
</blockquote></details>

Look above

---

*[src/js/containers/RecentProjectsContainer.js, line 9 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBBmWL7PwSLT2LiXY:-KiFvRcVYCXQRXQsxvaR:b-9jnm0v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/RecentProjectsContainer.js#L9)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Ibid.
</blockquote></details>

Look above

---

*[src/js/containers/RecentProjectsContainer.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBQSku8RSfjax32Yq:-KiFvTAI6f0U-nCDAVuA:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/containers/RecentProjectsContainer.js#L75)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Log
</blockquote></details>

Done.

---

*[src/js/utils/loadMethods.js, line 21 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBINln_zwNKxbI_-Q:-KiFvegyCL4H9QZvYm8j:b-1k658i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/utils/loadMethods.js#L21)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think this is something that has to be logged. This seems more of a comment than anything. 
</blockquote></details>

the reason for logging this msg is to ease future debugging of this function

---

*[src/js/utils/loadMethods.js, line 38 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-KiEBFdP6qXGzwmmy6Qn:-KiFw5BRo55WrcD8YRdf:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/387688e77fe30e949edcbd8404887a41b09d22bf/src/js/utils/loadMethods.js#L38)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Do we want to log this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140)*

**Comment by klappy** [comment]
Reviewed 16 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1140#-:-KiGB2a-nJKGxpHz36u5:bnfp4nl)*

**Pull request merged**
