### PR TITLE
Implemented data persistence for Groups Index and Groups Data

### PR DESCRIPTION
**Pull request by mannycolon**
…ta peristence

#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1014)

### CODE REVIEW

**Comment by ihoegen** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/utils/localStorage.js, line 161 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgpltRGXKy3f9sFgUOl:-KgpltRGXKy3f9sFgUOm:b-a2h5fo) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8df7ae02f07a4ddcc346d704a4d946746a58f5a1/src/js/utils/localStorage.js#L161)):*
> ```JavaScript
> export const saveState = state => {
>   try {
>     saveSettings(state);
> ```

Would this cause a crash before any of the following items can be updated? I think removing the if statements will cause issues. For example, settingsReducer does not exist, but all the other do. So nothing else gets saved.

---

*[src/js/utils/saveMethods.js, line 171 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgpmEf1JOJNyxMe02kU:-KgpmEf1JOJNyxMe02kV:bmh9fua) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8df7ae02f07a4ddcc346d704a4d946746a58f5a1/src/js/utils/saveMethods.js#L171)):*
> ```JavaScript
>     const PROJECT_SAVE_LOCATION = state.projectDetailsReducer.projectSaveLocation;
>     let tool = state.contextIdReducer.contextId ?
>                state.contextIdReducer.contextId.tool : undefined;
> ```

Style would call for null instead I believe. 

---

*[src/js/utils/saveMethods.js, line 177 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgpmOELTaeR_KNDPzex:-KgpmOELTaeR_KNDPzey:b-5pf97r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8df7ae02f07a4ddcc346d704a4d946746a58f5a1/src/js/utils/saveMethods.js#L177)):*
> console.log(savePath);
>       console.log(groupsIndex);
Do we want the logs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by ihoegen** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by klappy** [comment]
*[src/js/utils/localStorage.js, line 161 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgpltRGXKy3f9sFgUOl:-KgrSedPb5Hoq75Bcg95:bcdkvay) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8df7ae02f07a4ddcc346d704a4d946746a58f5a1/src/js/utils/localStorage.js#L161)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Would this cause a crash before any of the following items can be updated? I think removing the if statements will cause issues. For example, settingsReducer does not exist, but all the other do. So nothing else gets saved.
</blockquote></details>

I think the way we have it setup, they all exists all the time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/utils/localStorage.js, line 161 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgpltRGXKy3f9sFgUOl:-KgrU4tmsZ5ju-IscV-4:b-mg0jco) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8df7ae02f07a4ddcc346d704a4d946746a58f5a1/src/js/utils/localStorage.js#L161)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I think the way we have it setup, they all exists all the time.
</blockquote></details>

Alright then, disregard

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-:-KgtbldR7B3X6wO34bLx:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/reducers/groupsIndexReducer.js, line 10 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-KgteWqX-rWRvWbXkMmw:-KgteWqX-rWRvWbXkMmx:bd49y8m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d32468286d671d4196fe9b3fc2ce7287e30e6db8/src/js/reducers/groupsIndexReducer.js#L10)):*
> ```JavaScript
>   switch (action.type) {
>     case consts.SET_GROUPS_INDEX: {
>       console.log(action.groupsIndex);
> ```

logging here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1014#-:-KgthGv5-tN7XuOasscm:bnfp4nl)*

**Pull request merged**
