### PR TITLE
Add Missing Module For Word Alignment Tool

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5183)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5183)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[tC_apps/translationWords, line 1 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5183#-LOJep2aDQZ_zHjJkF8K:-LOJep2b8qYf-kc13Coj:bmbqupc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7109d250fe57b32c3485ad90bfd27df1f82abd9c/tC_apps/translationWords#L1)):*
> ```
> Subproject commit 5e27484dd650d6ce1a3ec5bdf3306a78f9102e98
> ```

Did you intend to commit this?

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5183)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[package.json, line 182 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5183#-LOJfeA71OSVnVd3iGna:-LOJfeA8B4qzfPsYMNN8:biqmrz9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7109d250fe57b32c3485ad90bfd27df1f82abd9c/package.json#L182)):*
> ```JSON
>     "uuid": "3.2.1",
>     "word-aligner": "0.1.3",
>     "word-map": "^0.1.9",
> ```

Why did you add the up-carrot instead of incrementing the word-map?  Don't know that we always want to pick up the latest, especially when we are doing release builds.

**Comment by PhotoNomad0** [comment]
@RoyalSix - Think this should not be merged to v1.0.0 since that is already released.

**Comment by da1nerd** [comment]
@RoyalSix `word-map` is deprecated. Also why are we making commits to release `1.0.0` that release has already been closed.

**Pull request closed without merging**
