### PR TITLE
Bug fix 4822/Fix to prevent import of non tStudio/tCore Projects

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added verify on import that project is supported.

#### Please include detailed Test instructions for your pull request:
- project in issue (https://git.door43.org/tCore-test-data/AlignedUlb_hi) should fail to import and give error message. 
- supported tCore and tStudio projects should still succeed.  If you are feeling adventurous, you can try the PROTOTYPE Integration test at https://github.com/PhotoNomad0/tCoreIntegrationTest.  See the readme.md.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5103)

### CODE REVIEW

**Comment by dsm-git** [comment]
Some builds failed

**Comment by dsm-git** [comment]
Some builds failed

**Comment by PhotoNomad0** [comment]
Hmm...concourse is broken.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (240322e)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-linux-x64-1.0.0-240322e.deb) is ready for download.
[macOS build 1.0.0 (240322e)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-macos-x64-1.0.0-240322e.dmg) is ready for download.
[Windows x64 build 1.0.0 (240322e)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-win-x64-1.0.0-240322e.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (240322e)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-win-x32-1.0.0-240322e.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
@PhotoNomad0 Please merge the latest changes from `develop` into this branch.

**Review by mannycolon — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by mannycolon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5103#-:-LO-4QRF4qlf9iTQRCBN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5103)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (33099fd)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-linux-x64-1.0.0-33099fd.deb) is ready for download.
[macOS build 1.0.0 (33099fd)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-macos-x64-1.0.0-33099fd.dmg) is ready for download.
[Windows x64 build 1.0.0 (33099fd)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-win-x64-1.0.0-33099fd.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (33099fd)](https://tc-builds.door43.org/build/bugFix-mcleanb-4822/translationCore-win-x32-1.0.0-33099fd.setup.exe) is ready for download.

**Pull request merged**
