### PR TITLE
App updates and Localization Menu

### LINKED ISSUE #3662: Search for Update (for tC)
Note: Could possibly be implemented to update content as well as the app ( #3175 ).

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):

This fixes #3662 and #3750.
Most of #2963 was also completed in this PR, however it has been disabled until it can be completed.

#### Please include detailed Test instructions for your pull request:
- #3622 can be tested by setting the version in package.json to something like `0.0.0`. This will allow it to pick up the last public release (which was quite some time ago). Go to the new app menu and check for app updates. If you are on linux this won't work since the last public release only had builds for windows and macos.
- #3750 can be tested by visiting the login screen and logging in as a guest. You can also change the locale by opening the new app menu and selecting the menu item.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3782)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Should this be connected to an issue?

**Comment by RoyalSix** [comment]
@neutrinog I'm wondering about the double nesting of components in the folder structure.
i.e. 
```src/js/components/SoftwareUpdatesDialog/components/{componentName}```
```src/js/components/SoftwareUpdatesDialog/containers/{componentName}```
Was this purposeful? It kind of tricked me haha

**Comment by RoyalSix** [comment]
Reviewed 8 of 39 files at r1, 1 of 8 files at r2.
Review status: 9 of 41 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 64 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5H7IFeawz9F0ymDZ0X:-L5H7IFeawz9F0ymDZ0Y:b-zcjvte) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/package.json#L64)):*
> ```JSON
>     "electron-prebuilt-compile": "1.6.11",
>     "electron-react-devtools": "0.5.3",
>     "enzyme": "3.3.0",
> ```

Thanks

---

*[src/js/components/AppMenu.js, line 34 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HBJr-Z-LIP-1Ulbj8:-L5HBJr-Z-LIP-1Ulbj9:b-uea04q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/components/AppMenu.js#L34)):*
> ```JavaScript
>   }
> 
>   componentDidCatch(error, info) {
> ```

I'm wondering if we should make this type of behavior on all our components in the future. Even by overriding the prototype function of reacts Component

---

*[src/js/components/AppMenu.js, line 47 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HCndaY3TNc_toyCXn:-L5HCndaY3TNc_toyCXo:b-9i3vr2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/components/AppMenu.js#L47)):*
> ```JavaScript
>     return () => {
>       this.setState({
>         ...this.state,
> ```

Do you have to explicitly add the previous state here?, React already does a shallow merge.
Same with below.

---

*[src/js/components/FeedbackDialog.js, line 121 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HmR32Fnor28f9_-zE:-L5HmR32Fnor28f9_-zF:b-89uqri) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/components/FeedbackDialog.js#L121)):*
> ```JavaScript
>       });
> 
>       this.setState({
> ```

equivalent of ```this.setState(this.initialState)``` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by RoyalSix** [comment]
Reviewed 5 of 39 files at r1, 4 of 8 files at r2.
Review status: 18 of 41 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[__tests__/PopoverMenu.js, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HmtxCVp7CDWNtx_C9:-L5HmtxCVp7CDWNtx_CA:b-r5mrrg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/__tests__/PopoverMenu.js#L1)):*
> ```JavaScript
> /* eslint-env jest */
> ```

Should this file be called ```PopoverMenu.test.js``` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by da1nerd** [comment]
Making sure you are awake! I agree not well thought out.  I've just reorganized a lot of those components. For the most part components should now be under `components` and containers should be under `containers`.

---

Review status: 12 of 70 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[__tests__/PopoverMenu.test.js, line 1 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HmtxCVp7CDWNtx_C9:-L5LdmAc-2TuKo8xmLsP:bkq0npz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/__tests__/PopoverMenu.test.js#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Should this file be called ```PopoverMenu.test.js``` ?
</blockquote></details>

Yes it should!

---

*[src/js/containers/AppMenu.js, line 47 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HCndaY3TNc_toyCXn:-L5LeF5AxQvvStZ15A1b:b-dmxza8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/containers/AppMenu.js#L47)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Do you have to explicitly add the previous state here?, React already does a shallow merge.
Same with below.
</blockquote></details>

ah yes. Thanks.

---

*[src/js/containers/FeedbackDialogContainer.js, line 121 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HmR32Fnor28f9_-zE:-L5LeIlC50U92HLl0JNC:b-3cslek) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/containers/FeedbackDialogContainer.js#L121)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

equivalent of ```this.setState(this.initialState)``` ?
</blockquote></details>

indeed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-:-L5LdKCwpswWTFIRMacd:bayw21h)*

**Comment by da1nerd** [comment]
Review status: 12 of 70 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[package.json, line 64 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5H7IFeawz9F0ymDZ0X:-L5LeRykQH3tSeea7rC8:b56ptj3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/package.json#L64)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

you're welcome!

---

*[src/js/containers/AppMenu.js, line 34 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5HBJr-Z-LIP-1Ulbj8:-L5LeUdqolbUngCH59Bq:bg77faq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8afa165bce2d57c2dc0e00f0a4096a305a788526/src/js/containers/AppMenu.js#L34)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I'm wondering if we should make this type of behavior on all our components in the future. Even by overriding the prototype function of reacts Component
</blockquote></details>

Maybe. Some times we may want an entire branch of components to fail rendering if an important sub-component breaks. It might be safer to continue explicitly set the error boundary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by mannycolon** [comment]
Reviewed 11 of 49 files at r1, 64 of 64 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by mannycolon** [comment]
@neutrinog Is this normal?
I just opened the app and this alert poped up then when i clicked `ok` it restarted the app,
screen shot 2018-02-15 at 3 26 44 pm

**Comment by mannycolon** [comment]
@neutrinog so when I clicked `Check for software updates` it says `You are running the latest version of translationCore.` but down below it still says I'm running **translationCore 0.0.0**

**Comment by RoyalSix** [comment]
Reviewed 2 of 49 files at r1, 22 of 73 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/components/PopoverMenu.js, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5PwDPuCsIsIyjGO_C9:-L5PwDPuCsIsIyjGO_CA:bcyc53p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/PopoverMenu.js#L1)):*
> ```JavaScript
> import React from 'react';
> ```

Component functions well and looks well. A bit more intricate implementation that I would have expected.

---

*[src/js/components/PopoverMenu.js, line 170 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5Pv6YwwmcykdlEEPHj:-L5Pv6YwwmcykdlEEPHk:bkqeixv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/PopoverMenu.js#L170)):*
> ```JavaScript
>     return (
>       <React.Fragment>
>         <button onClick={this._handleClick}
> ```

Hey just wondering why you didn't choose to use the material-ui Button with the default styling

---

*[src/js/components/dialogComponents/SoftwareUpdateDialog.js, line 10 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5PxYYaEW5MvRGb_Xtj:-L5PxYYaEW5MvRGb_Xtk:b-su5she) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/dialogComponents/SoftwareUpdateDialog.js#L10)):*
> ```JavaScript
> export const STATUS_OK = 'ok';
> 
> const makeMessage = (properties) => {
> ```

Would this function be better placed in the container?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by da1nerd** [comment]
@mannycolon not sure what's with that crash. The only addition I made to main.js was to add a few ipc event handlers. I've never seen that error before. Can you reproduce it?

As for checking for updates. The older releases didn't include the os and architecture in the file name so it wasn't finding the correct  build. However, I just added some backwards compatibility, not that we'd need it except for testing purposes.

**Comment by da1nerd** [comment]
Review status: 65 of 72 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/js/components/PopoverMenu.js, line 1 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5PwDPuCsIsIyjGO_C9:-L5QwHLT3jauDZrBTsRe:b-egzgjp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/PopoverMenu.js#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Component functions well and looks well. A bit more intricate implementation that I would have expected.
</blockquote></details>

I designed it to be a reusable component. All the state, events, and styling are set up to handle a generic use case where you'd have a primary/secondary button with some text and maybe an icon.

Now, if we need another menu like this we have all the boiler plate abstracted away into this component.

---

*[src/js/components/PopoverMenu.js, line 170 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5Pv6YwwmcykdlEEPHj:-L5QvgMJ0dkpPOlQhKjX:bj9s3hb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/PopoverMenu.js#L170)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Hey just wondering why you didn't choose to use the material-ui Button with the default styling
</blockquote></details>

Because it was messing with the styles. Originally I was using a material-ui button, but since the styles weren't working out well I just went with what I saw other parts of the app were using.

---

*[src/js/components/dialogComponents/SoftwareUpdateDialog.js, line 10 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5PxYYaEW5MvRGb_Xtj:-L5QwkLA7oxlDUoojiCb:b-yivdmi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b32624ba189ed48dfc1ceb3335579f073cf2f3f2/src/js/components/dialogComponents/SoftwareUpdateDialog.js#L10)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Would this function be better placed in the container?
</blockquote></details>

An argument could be made for that but I feel like it could go either way. I'm not particularly swayed either way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by RoyalSix** [comment]
Reviewed 9 of 49 files at r1, 43 of 73 files at r3, 6 of 9 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tC_resources, line 1 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5R07t0BgMIpa5VLQ7X:-L5R07t0BgMIpa5VLQ7Y:bcmhzif) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c6151ef21e38eb4b923c6bdcd080b04aad21e09/tC_resources#L1)):*
> ```
> Subproject commit 10495055b15ffc000b3f68fd10a9735d2ec5fe56
> ```

accidental commit?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by RoyalSix** [comment]
Code Review: ```LGTM```
Testing locally now!

**Comment by da1nerd** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_resources, line 1 at r5](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782#-L5R07t0BgMIpa5VLQ7X:-L5UmyR1AGdJCmo0RRQu:b-w1m7px) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c6151ef21e38eb4b923c6bdcd080b04aad21e09/tC_resources#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

accidental commit?
</blockquote></details>

Arrrrg!!! Always. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 64 files at r3, 1 of 6 files at r4, 25 of 26 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by PhotoNomad0** [comment]
:lgtm:

Works on Mac

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-:-L5iJdKsI1EIi4on1sog:bddvwot)*

**Comment by mannycolon** [comment]
@neutrinog is it expected behavior to change the package.json version number to **0.0.0** and click `Check for software updates` and receive the alert `You are running the latest version of translationCore.` but down below it still says I'm running **translationCore 0.0.0**

**Comment by da1nerd** [comment]
@mannycolon what os are you running on? I pushed an update last week that would provide backwards compatibility with the super old releases on Github.
It should show an update is available if you are running on windows or mac (not linux because there's no public linux release on github).

**Comment by RoyalSix** [comment]
I think the app may be grabbing the wrong version number with ```0.0.0```.
When i put ```0.0.0``` and upgraded, that works fine but the alert dialog showed ```0.0..```

screen shot 2018-02-20 at 8 13 40 am

And then when I ran ```npm test``` after the download the following resulted 
```
npm ERR! Invalid version: "0.0."

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jay/.npm/_logs/2018-02-20T16_15_06_344Z-debug.log
```

I know having that version number is a small use case but it may I thought I should address it.

**Comment by RoyalSix** [comment]
Reviewed 1 of 64 files at r3, 26 of 26 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_resources, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5R07t0BgMIpa5VLQ7X:-L5o75eDosM220DuVOGx:bcmhzif) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c6151ef21e38eb4b923c6bdcd080b04aad21e09/tC_resources#L1)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

Arrrrg!!! Always. 
</blockquote></details>

accidental commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Comment by da1nerd** [comment]
I cannot reproduce this on linux, mac, or windows. The error message shown above indicates that the version in package.json was actually set to "0.0." which is invalid. Make sure your version number is properly formatted in package.json.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_resources, line 1 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-L5R07t0BgMIpa5VLQ7X:-L5p-29tyZD7Ls2mpddB:btajich) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2c6151ef21e38eb4b923c6bdcd080b04aad21e09/tC_resources#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

accidental commit?
</blockquote></details>

yes, it should already be fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782#-:-L5ozVBdliAXNu0Zqgax:b-kgejdr)*

**Comment by RoyalSix** [comment]
@neutrinog Nice its working, I think I did enter it wrong, sorry about that.

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3782)*

**Pull request merged**
