### PR TITLE
QA fail 4402/fix local project behavior opening and details edit

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fix QA fails for https://github.com/unfoldingword-dev/translationcore/issues/4402 where opening project with missing verses or merge conflicts not show details page.
- Fix QA fails for https://github.com/unfoldingword-dev/translationcore/issues/4404

#### Please include detailed Test instructions for your pull request:
- ~use build at bottom of page.~  Will have to build local since concourse is no longer running.
- using QA fail projects at bottom of page https://github.com/unfoldingword-dev/translationcore/issues/4402 (Local tstudio import [es-419_tit_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115875/es-419_tit_reg.zip) and Imported from Door43 [fr_eph_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/2115876/fr_eph_reg.zip)) , open projects and make sure that project details pages are loaded.  Should see:
  - project details prompt
  - after you enter details and click continue, should see missing verse prompt
  - click continue and should see prompt that project has been renamed (note: projects that have a git history will show a temporary dialog until DCS rename is implemented).
- QA fails for https://github.com/unfoldingword-dev/translationcore/issues/4404
  - item 1 - start import of USFM project, then click cancel.  Should see an alert box about cancelling the import.  Click cancel import and make sure that if does not leave project in import folder.
  - item 2 - this is the same error as in 4402 failure covered above.
  - item 3
    - open project details for local project - make sure save button says save changes
    - import usfm project and make sure continue button says 'continue'
    - enter project details, click 'continue'
    - import same usfm project and enter same project details.  Should see error that 'Translation Identifier' already exists and save button should change to overrite

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (8733670)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-8733670.zip) is ready for download.
[macOS build 0.10.0 (8733670)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-8733670.dmg) is ready for download.
[Windows x64 build 0.10.0 (8733670)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-8733670.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (8733670)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-8733670.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (707a002)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-707a002.zip) is ready for download.
[macOS build 0.10.0 (707a002)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-707a002.dmg) is ready for download.
[Windows x64 build 0.10.0 (707a002)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-707a002.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (707a002)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-707a002.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (973b90b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-973b90b.zip) is ready for download.
[macOS build 0.10.0 (973b90b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-973b90b.dmg) is ready for download.
[Windows x64 build 0.10.0 (973b90b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-973b90b.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (973b90b)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-973b90b.setup.exe) is ready for download.

**Comment by richmahn** [comment]
Reviewed 1 of 13 files at r2, 3 of 19 files at r3, 1 of 6 files at r4, 1 of 6 files at r5, 1 of 9 files at r6.
Review status: 7 of 22 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @richmahn)

---

*[src/js/selectors/index.js, line 220 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642#-LGRcat3ArwX-rvIGwve:-LGRcat3ArwX-rvIGwvf:b-qcwfvf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a34f547b7bc6cb51fc455eab3a5c48396985078/src/js/selectors/index.js#L220)):*
> ```JavaScript
>  * @return {boolean}
>  */
> export const getIsOverWritePermitted = (state) =>
> ```

Lower case "Write" to be like other cases.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642)*

**Comment by richmahn** [comment]
Review status: 7 of 22 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0 and @richmahn)

---

*[src/js/helpers/ProjectInformationCheckHelpers.js, line 4 at r6](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642#-LGRcwaq1fFZ3Ijy7UwP:-LGRcwaq1fFZ3Ijy7UwQ:bq8lliu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7a34f547b7bc6cb51fc455eab3a5c48396985078/src/js/helpers/ProjectInformationCheckHelpers.js#L4)):*
> ```JavaScript
> import * as LangHelpers from "./LanguageHelpers";
> import * as ProjectImportFilesystemHelpers from "./Import/ProjectImportFilesystemHelpers";
> import {getIsOverWritePermitted} from "../selectors";
> ```

Lowercase the W here as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642)*

**Comment by richmahn** [comment]
Reviewed 1 of 13 files at r2, 2 of 19 files at r3, 1 of 6 files at r5, 3 of 9 files at r6.
Review status: 14 of 22 files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0 and @richmahn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642)*

**Comment by richmahn** [comment]
Reviewed 2 of 19 files at r3, 1 of 6 files at r5, 5 of 9 files at r6.
Review status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642)*

**Comment by richmahn** [comment]
:lgtm: 

---

Reviewed 9 of 9 files at r7.
Review status: all files reviewed, 2 unresolved discussions (waiting on @PhotoNomad0)

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4642#-:-LGW7Ra_2T7x86ud0XSj:bg7igkv)*

**Pull request merged**
