### PR TITLE
Moved contextIdReducer, groupsDataReducer, groupsIndexReducer, commentsReducer, VerseEditsReducer, BookmarksReducer, SelectionsReducer to tools codebase

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- ##### Pending: https://github.com/unfoldingWord/wordAlignment/pull/245, https://github.com/unfoldingWord/checking-tool-wrapper/pull/79, https://github.com/unfoldingWord/translationNotes/pull/134 & https://github.com/unfoldingWord/translationWords/pull/311

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @PhotoNomad0)

___
*[src/js/localStorage/saveMethods.js, line 304 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/6668#-M-upD2sBzHo0ZAxcIEP:-M-upD2sBzHo0ZAxcIEQ:bxx207z) ([raw file](https://github.com/unfoldingword/translationcore/blob/537283a1581fb173f7608dea305c1b2111fed955/src/js/localStorage/saveMethods.js#L304)):*
> ```JavaScript
> * @param {Object} contextId
> */
> export const saveSelectionsForOtherContext = (state, gatewayLanguageCode, gatewayLanguageQuote, selections, invalidated, userName, contextId) => {
> ```

Can't removed this.  Still being used in SelectionsActions.js line 70

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 31 of 38 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)* status: 36 of 40 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Review by mannycolon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)* status: 34 of 39 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[src/js/localStorage/saveMethods.js, line 304 at r2](https://reviewable.io/reviews/unfoldingword/translationcore/6668#-M-upD2sBzHo0ZAxcIEP:-M-wjB-F6X9RGAcrIgL2:b-896fix) ([raw file](https://github.com/unfoldingword/translationcore/blob/9620a2d4e7a19d59db8c257b2b13c45b09ec5e70/src/js/localStorage/saveMethods.js#L304)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Can't removed this.  Still being used in SelectionsActions.js line 70
</blockquote></details>

Done.

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)* status: 38 of 39 files reviewed, all discussions resolved

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/translationcore/6668)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
