### PR TITLE
Fix Git Installer In Builds

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request fixes an issue with the git installer on builds. Previously, trying to run an .exe inside of an .asar file would cause an error. This pull request addresses that by copying the .exe file to a new folder, and executing from there.

Testing instructions: 

Load branch from a windows computer without git

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/756)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/756)*

**Comment by mannycolon** [comment]
code review looks good but I dont have a Windows computer so maybe @klappy is the best guy to test this PR

**Comment by ihoegen** [comment]
@mannycolon Klappy mentioned that a Windows 10 VM is free

**Comment by mannycolon** [comment]
@ihoegen what do you mean when you say `free`??

**Comment by klappy** [comment]
How do I test it without a Windows build?

I have a vanilla Win10 VM but not a dev machine ready to make builds from this branch :)

Do we get a build via a Tag using this branch that isn't "released" but just tagged for testing?

**Comment by ihoegen** [comment]
@klappy I'm building one right now, designed just for the git installer

**Comment by ihoegen** [comment]
@klappy Here's an installer: https://drive.google.com/open?id=0Bxaf4ZxVpTQkZVYzcmI2YS1WWm8

**Comment by RoyalSix** [comment]
Testing...

**Pull request merged**
