### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5394)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (621be2b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-621be2b.deb) is ready for download.
[macOS build 1.1.0 (621be2b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-621be2b.dmg) is ready for download.
[Windows x64 build 1.1.0 (621be2b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-621be2b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (621be2b)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-621be2b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (72ee515)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-72ee515.deb) is ready for download.
[macOS build 1.1.0 (72ee515)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-72ee515.dmg) is ready for download.
[Windows x64 build 1.1.0 (72ee515)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-72ee515.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (72ee515)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-72ee515.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (0b67ff8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-0b67ff8.deb) is ready for download.
[macOS build 1.1.0 (0b67ff8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-0b67ff8.dmg) is ready for download.
[Windows x64 build 1.1.0 (0b67ff8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-0b67ff8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0b67ff8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-0b67ff8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (9d2b796)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-9d2b796.deb) is ready for download.
[macOS build 1.1.0 (9d2b796)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-9d2b796.dmg) is ready for download.
[Windows x64 build 1.1.0 (9d2b796)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-9d2b796.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9d2b796)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-9d2b796.setup.exe) is ready for download.

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5394#-:-LQoOyHbEge5mK-8Zihi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (97b51a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-97b51a8.deb) is ready for download.
[macOS build 1.1.0 (97b51a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-97b51a8.dmg) is ready for download.
[Windows x64 build 1.1.0 (97b51a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-97b51a8.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (97b51a8)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-97b51a8.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
**Hold on until all Spanish translations are completed on Crowdin before merging this PR**

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (bcaa534)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-bcaa534.deb) is ready for download.
[macOS build 1.1.0 (bcaa534)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-bcaa534.dmg) is ready for download.
[Windows x64 build 1.1.0 (bcaa534)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-bcaa534.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (bcaa534)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-bcaa534.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b6140ea.deb) is ready for download.
[macOS build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b6140ea.dmg) is ready for download.
[Windows x64 build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b6140ea.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b6140ea.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-b6140ea.deb) is ready for download.
[macOS build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-b6140ea.dmg) is ready for download.
[Windows x64 build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-b6140ea.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b6140ea)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-b6140ea.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (6c09241)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-6c09241.deb) is ready for download.
[macOS build 1.1.0 (6c09241)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-6c09241.dmg) is ready for download.
[Windows x64 build 1.1.0 (6c09241)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-6c09241.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (6c09241)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-6c09241.setup.exe) is ready for download.

**Review by bspidel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5394#-:-LQtNDgSDrl1hNLFZMJj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
