### PR TITLE
Finished Localization

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This finishes #2265.
The updates in this PR mostly involve reducers and actions. A number of these were refactored to eliminate dead code and add support for localization.

* All localization has been moved outside of the reducers.
* Where convenient, or where necessary for the reducers' sake, localization was moved outside of actions.
* Where inconvenient, localization has been left inside actions. It is my opinion that localization should be restricted to the components/containers however, for the sake of time and not rewriting to many things I exposed a method for using locale within actions (thunks). I did label it as `@deprecated` and it's use should be discouraged. I would suggest slowly migrating away from it's use.

> Note:
> * Names for books of the Bible have **not** been configured for localization.
> * Support for localizing tools has **not** been added yet.

#### How to test this pull request:

Make sure everything still works!

Of particular note please double check:

* The home and project steppers. To say these were changed would be an understatement. They were radically overhauled to support localization.
* As part of the above point, the home screen navigation and stepper components were heavily refactored.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3742)

### CODE REVIEW

**Comment by richmahn** [comment]
Review status: 0 of 72 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/home/overview/ProjectCard.js, line 128 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4RrTdGobaV__q9THVQ:-L4RrTdGobaV__q9THVR:b-9ygjqn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/71a3ed15e74b4680beb84886339e5433fad15ac5/src/js/components/home/overview/ProjectCard.js#L128)):*
> ```JavaScript
>     const {translate} = this.props;
>     const emptyMessage = translate('home.overview.select_project');
>     const emptyButtonLabel = translate('project');
> ```

This causes a message that this key doesn't exist in the locale file. Shouldn't it be home.project? Others have this issue too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by da1nerd** [comment]
Review status: 0 of 100 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/components/home/overview/ProjectCard.js, line 128 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4RrTdGobaV__q9THVQ:-L4b4Z2jFNwo66kGk29_:b-qx121c) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/71a3ed15e74b4680beb84886339e5433fad15ac5/src/js/components/home/overview/ProjectCard.js#L128)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

This causes a message that this key doesn't exist in the locale file. Shouldn't it be home.project? Others have this issue too.
</blockquote></details>

It doesn't matter if any of the languages are not structured the same way as English. Because those are automatically generated based on the English file. So you can tweak things, move things around, and basically render the other locale's useless, then when you push your changes up they will get deployed to Crowdin where the locales will get re-translated (re-using words and phrases as available). Then when someone downloads the latest locale from Crowdin everything will be fixed.

It's all just part of the locale development cycle. No one should ever manually touch any of the locale files except for English. If someone wanted to help translate one of those files they should do so on Crowdin.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by mannycolon** [comment]
Reviewed 6 of 71 files at r1, 1 of 3 files at r2.
Review status: 7 of 100 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by mannycolon** [comment]
Reviewed 38 of 71 files at r1, 2 of 3 files at r2.
Review status: 47 of 100 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/ProjectValidationActions.test.js, line 65 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4bJoFn-5jCGFN2qXrv:-L4bJoFn-5jCGFN2qXrw:b-9plj2g) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0452b15716a5d2ae9d3356739ba06ad650594243/__tests__/ProjectValidationActions.test.js#L65)):*
> ```JavaScript
>     const expectedActions = [
>       { type: consts.SET_SAVE_PATH_LOCATION, pathLocation },
>       { type: consts.UPDATE_STEPPER_LABEL, index: 2, label: 'fr_eph_ulb' },
> ```

Do we no longer need to dispatch this action?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by da1nerd** [comment]
*[__tests__/ProjectValidationActions.test.js, line 65 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4bJoFn-5jCGFN2qXrv:-L4bR-5pCD79UgnCcdHo:bbx4cs7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/0452b15716a5d2ae9d3356739ba06ad650594243/__tests__/ProjectValidationActions.test.js#L65)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we no longer need to dispatch this action?
</blockquote></details>

Correct.  Stepper labels are no longer stored in the state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by da1nerd** [comment]
The last commit fixes the bug shown in https://github.com/unfoldingWord-dev/translationCore/issues/2003#issuecomment-363478907

**Comment by mannycolon** [comment]
Reviewed 25 of 71 files at r1, 28 of 28 files at r3, 145 of 145 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/translationCore/0.8.1-alpha.15/actions_AlertModalActions.js.html, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4hIcIuALJWAIzO42zT:-L4hIcIuALJWAIzO42zU:b-jr2twx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/86e7270044ce88e787c480e0b2091951652f09d1/docs/translationCore/0.8.1-alpha.15/actions_AlertModalActions.js.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

never seem this file before, just wondering what it is needed for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by mannycolon** [comment]
The `Do not show this warning again`check box in the internet access alert isnt checkable.

screen shot 2018-02-06 at 6 13 00 pm

**Comment by da1nerd** [comment]
@mannycolon good catch. Fixed.

**Comment by da1nerd** [comment]
*[docs/translationCore/0.8.1-alpha.15/actions_AlertModalActions.js.html, line 1 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4hIcIuALJWAIzO42zT:-L4hg-JfdxR63Q2igVmK:bn3zpk1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/86e7270044ce88e787c480e0b2091951652f09d1/docs/translationCore/0.8.1-alpha.15/actions_AlertModalActions.js.html#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

never seem this file before, just wondering what it is needed for?
</blockquote></details>

That was an accident. I added a documentation generator in a different branch and accidentally committed the output here because the gitignore didn't account for it. All of these doc files have been removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
Reviewed 8 of 71 files at r1, 1 of 146 files at r5.
Review status: 100 of 102 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
Reviewed 144 of 146 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-:-L4iALD0GfNqaU7lBZi4:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 72 files at r1, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 72 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
Reviewed 13 of 72 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/homeScreenReducer.js, line 72 at r6](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742#-L4mhta39ekw73eB7Ct8:-L4mhta39ekw73eB7Ct9:b-giam74) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5366b1856403214c36b7f94d27c26656ee1ab12d/src/js/reducers/homeScreenReducer.js#L72)):*
> ```JavaScript
> export default homeScreenReducer;
> 
> /**
> ```

Just now seeing some changes from reviewable what was the reason for adding these functions to the reducer?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by da1nerd** [comment]
*[src/js/reducers/homeScreenReducer.js, line 72 at r6](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742#-L4mhta39ekw73eB7Ct8:-L4nZzwV7wyHufY2dl_v:b-w4wg2p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5366b1856403214c36b7f94d27c26656ee1ab12d/src/js/reducers/homeScreenReducer.js#L72)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Just now seeing some changes from reviewable what was the reason for adding these functions to the reducer?
</blockquote></details>

These are selectors. This is the pattern suggested by the authors of redux. Here's a really good video explaining the motivation behind this pattern https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers.

There are a number of benefits to this pattern:

1. keeps business logic and business state in a single location for better clarity.
2. if you make changes to the state structure you only have to update the reducer.
3. makes business logic easier to test
4. make reducers easier to test
5. makes components easier to test

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/reducers/homeScreenReducer.js, line 72 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-L4mhta39ekw73eB7Ct8:-L4qPNhSmQlGVJzfdYQ3:byq66lp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5366b1856403214c36b7f94d27c26656ee1ab12d/src/js/reducers/homeScreenReducer.js#L72)):*
<details><summary><i>Previously, neutrinog (Joel Lonbeck) wrote…</i></summary><blockquote>

These are selectors. This is the pattern suggested by the authors of redux. Here's a really good video explaining the motivation behind this pattern https://egghead.io/lessons/javascript-redux-colocating-selectors-with-reducers.

There are a number of benefits to this pattern:

1. keeps business logic and business state in a single location for better clarity.
2. if you make changes to the state structure you only have to update the reducer.
3. makes business logic easier to test
4. make reducers easier to test
5. makes components easier to test
</blockquote></details>

Nice makes sense :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 65 of 71 files at r1, 3 of 3 files at r2, 28 of 28 files at r3, 2 of 145 files at r4, 4 of 146 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3742#-:-L4q_k7PtNF_Vvap--a-:bnfp4nl)*

**Pull request merged**
