### PR TITLE
Added Support For tStudio Single Chunks

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR handles what happens when an import source contains no verse marker.

#### How to test this pull request:
Ensure tests are passing
Try loading the project described in #2642 , and ensure that checks 3:3, and 3:8 are present.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3128)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3128)*

**Comment by mannycolon** [comment]
I would suggest @klappy is the best fit to test this PR

**Comment by klappy** [comment]
Reviewed 21 of 21 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3128)*

**Comment by klappy** [comment]
@royalsix Good job, this looks like it takes care of some weird behavior we've had for a while.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3128#-:-KyYHVvUOEaqs4xL5era:b-l7b4xt)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3128#-:-KyYHhKc22azGDhD8ag-:bnfp4nl)*

**Pull request merged**
