### PR TITLE
Word Alignment Helpers NPM Module

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Took out all the logic from the word alignment helpers in tC and moved them to a separate module.
- Everything is in the github repo https://github.com/translationCoreApps/word-aligner right now, but I can make it a npm module once its reviewed and everything looks good. 
Also wanted to make sure the repo name was good before making it permanent.

#### Please include detailed Test instructions for your pull request:
- Just run `npm i` and make sure everything works as expected, especially related to word alignment.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338)

### CODE REVIEW

**Comment by da1nerd** [comment]
@RoyalSix fyi the word bank data is currently generated directly within the wordAlignment tool. We stopped pulling that data from tC earlier this year.

**Comment by RoyalSix** [comment]
@neutrinog True, they are also being used here for testing invalidated alignments.
I will make a PR for switching out the methods in the wA tool that are also in this module after this one is good.

**Comment by PhotoNomad0** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4338)*

**Comment by PhotoNomad0** [comment]
:lgtm: ~Local Testing~
:lgtm: Code after the conflicts are resolved.

**Comment by PhotoNomad0** [comment]
@RoyalSix - sorry Jay, some strangeness here.  Every time I click on the edited verse in WA, it warns that alignments will be reset, but the alignments are not actually reset.  Every time I click on it I get the same warning

**Comment by PhotoNomad0** [comment]
Also if I edit an unaligned verse, I will get a warning of invalid alignments when uploading to door43.  It looks like recent fixes have been clobbered.  Do you need to update the npm module where code has been moved to?

**Comment by RoyalSix** [comment]
@PhotoNomad0 I added some fixes!

**Comment by mannycolon** [comment]
Reviewed 9 of 14 files at r1, 3 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 161 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-LAxUzGz2WfIODTxVRFo:-LAxUzH-DCe_inh_4NHx:b-osmd60) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/465cf463754211c9c15d90e3b4327666c51de7b3/package.json#L161)):*
> ```JSON
>     "usfm-js": "1.0.0-beta.30",
>     "uuid": "3.2.1",
>     "word-aligner": "0.0.1",
> ```

usually, you start with 0.1.0

---

*[tC_resources, line 1 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-LAxX61S-1irYcUPEnjR:-LAxX61T5918A7Az7_a2:b-xuobad) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/465cf463754211c9c15d90e3b4327666c51de7b3/tC_resources#L1)):*
> ```
> Subproject commit 86d475febec31d0141d6f5f5bcbb561f62b31e7c
> ```

do we want this here?

---

*[__tests__/WordAlignmentHelpers.test.js, line 6 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-LAxXLrjAjO800J8_yOP:-LAxXLrjAjO800J8_yOQ:b-umb328) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/465cf463754211c9c15d90e3b4327666c51de7b3/__tests__/WordAlignmentHelpers.test.js#L6)):*
> ```JavaScript
> //helpers
> import * as WordAlignmentHelpers from '../src/js/helpers/WordAlignmentHelpers';
> import wordaligner, {VerseObjectUtils} from 'word-aligner';
> ```

where is this needed?

---

*[tC_apps/ScripturePane, line 1 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-LAxXVHL6i84a54_Ywbx:-LAxXVHL6i84a54_Ywby:bl82j9v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/465cf463754211c9c15d90e3b4327666c51de7b3/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit bccd5f9fbdeee6fa1669a9273c3859774fea1337
> ```

do you need to merge with latest develop branch ?

---

*[tC_apps/translationWords, line 1 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-LAxXZMB2notn0lGaCXR:-LAxXZMB2notn0lGaCXS:bl82j9v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/465cf463754211c9c15d90e3b4327666c51de7b3/tC_apps/translationWords#L1)):*
> ```
> Subproject commit f3d9d71c654234112acc35011ed29edaf2c4bc95
> ```

do you need to merge with latest develop branch ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338)*

**Comment by RoyalSix** [comment]
https://github.com/unfoldingWord-dev/translationCore/tree/develop/tC_apps `719327f`
https://github.com/translationCoreApps/VerseCheck `719327f`

@mannycolon For some reason it is showing a change on github but you can verify that the commit hash is the same on both branches so there is not really a change. It is a bug.

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338)*

**Comment by richmahn** [comment]
Code review: :lgtm:
Local test: :lgtm:

---

Reviewed 8 of 14 files at r1, 1 of 5 files at r2, 3 of 6 files at r3, 7 of 7 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4338#-:-LAyDNvN7jwXlPBHd9fl:b9pku97)*

**Pull request merged**
