### PR TITLE
Updated TSV Parser with changes (5920, 5998)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- The following issues should be fixed from this PR
https://github.com/unfoldingWord-dev/translationCore/issues/5920#issuecomment-487302922
https://github.com/unfoldingWord-dev/translationCore/issues/5998

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6040)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0c8752a)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-linux-x64-1.2.0-0c8752a.deb) is ready for download.
[macOS build 1.2.0 (0c8752a)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-macos-x64-1.2.0-0c8752a.dmg) is ready for download.
[Windows x64 build 1.2.0 (0c8752a)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-win-x64-1.2.0-0c8752a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0c8752a)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-win-x32-1.2.0-0c8752a.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]

**Review by mannycolon — CHANGES_REQUESTED** [review]
In order for your fixes to make into tc you have to also update the new `tsv-groupdata-parser` version in the `tc-source-content-updater`

**Comment by mannycolon** [comment]
@RoyalSix I did it myself since I need it as well for my PR

**Review by mannycolon — APPROVED** [review]

**Comment by mannycolon** [comment]
waiting on builds

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (00ab4a2)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-linux-x64-1.2.0-00ab4a2.deb) is ready for download.
[macOS build 1.2.0 (00ab4a2)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-macos-x64-1.2.0-00ab4a2.dmg) is ready for download.
[Windows x64 build 1.2.0 (00ab4a2)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-win-x64-1.2.0-00ab4a2.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (00ab4a2)](https://tc-builds.door43.org/build/feature-jay-5998/translationCore-win-x32-1.2.0-00ab4a2.setup.exe) is ready for download.

**Pull request merged**
