### PR TITLE
Store Settings somewhere other than LocalStorage

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/746)

### CODE REVIEW

**Comment by ihoegen** [comment]
Should we update the API to also write to the file? 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746#-KdTRk7yXs4bTf9RtRcE:-KdTRk7zgqpd7rXJwH80:bha10c1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4f41373fe158111cbdbf8e20480c43cc5fd003d/src/js/actions/SettingsActions.js#L10)):*
> ```JavaScript
> module.exports.setSettings = function(field, value) {
>   return ((dispatch) => {
>     var dir = pathex.join(PACKAGE_COMPILE_LOCATION, 'settings/settings.json');
> ```

We should have settings on the same level as packages-compiled, not inside of it. 

---

*[src/js/components/core/AccessProject.js, line 92 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746#-KdTRxzB29TushyLjOwU:-KdTRxzB29TushyLjOwV:b-brhjcc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4f41373fe158111cbdbf8e20480c43cc5fd003d/src/js/components/core/AccessProject.js#L92)):*
> ```JavaScript
>             api.putDataInCommon('saveLocation', folderpath);
>             //TODO: find a way to use the new setSettings() from SettingsActions
>             //api.setSettings('showTutorial', false);
> ```

This removes persistence, should we leave it in until we have a permanent solution?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746#-:-KdTSHwG9Rn-8XLsyfls:b-qi5peu)*

**Comment by mannycolon** [comment]
@ihoegen no we should stay away from using the API as much as possible. I'm actually going write a redux implementation to handle this API calls.

**Comment by RoyalSix** [comment]
@mannycolon persistence, is key. Maybe we should repeal and replace when we can

**Comment by ihoegen** [comment]
I agree with @RoyalSix

**Comment by mannycolon** [comment]
@RoyalSix @ihoegen if you take a look at the code i do have data persistence without using the API

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746#-KdTRk7yXs4bTf9RtRcE:-KdZKl4XOBIr2Ic5WWvQ:bll7klk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4f41373fe158111cbdbf8e20480c43cc5fd003d/src/js/actions/SettingsActions.js#L10)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

We should have settings on the same level as packages-compiled, not inside of it. 
</blockquote></details>

and why is that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746)*

**Comment by ihoegen** [comment]
@mannycolon because our settings file right now would have a location of `translationCore/packages-compiled/settings/settings.json` which does not make sense

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/core/AccessProject.js, line 92 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746#-KdTRxzB29TushyLjOwU:-KdZQtxMLXzWAStyWL8z:b-wfdlq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f4f41373fe158111cbdbf8e20480c43cc5fd003d/src/js/components/core/AccessProject.js#L92)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

This removes persistence, should we leave it in until we have a permanent solution?
</blockquote></details>

I'm an idiot, you're absolutely right. I confused the tutorial and persistance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746)*

**Comment by RoyalSix** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/746)*

**Pull request merged**
