### PR TITLE
Feature - #3912 - tC Changes - get tW version dynamic; remove group index sorting

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This removes the hardcoding of tW versions for construction the path since now we have different version numbers for different languages of tW
- It properly fixes and utilizes the ResourcesHandlers' getLastestVersionInPath() function to get the latest version in a directory, even if there are other directories and files, sorting properly by numeric values of the version
- Bumps up the version in package.json since tC_resources for the new import of tW articles and index.json files
- Removes sorting of the groups index.json file in the app since we now sort it when it is generated.

#### Please include detailed Test instructions for your pull request:
- Tests were written for the getLatestVersionInPath() function, test by running `jest ResourcesHandlers`. You can see the directory it runs the last test on in the `__tests__/fixtures/latestVersion` directory
- Run the app and test that tW properly loads now that they get their version directory dynamically with the function mentioned above. This shouldn't require getting the same branch, `feature-richmahn-3912` of the tC_resoures repo, but you can test with that branch as well.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3966)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@richmahn You haven't assigned anyone to review yet, is this ready for review?

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 4 files at r1, 12 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/ResourcesHelpers.test.js, line 47 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966#-L6b-UetvX0-4LPMdwZb:-L6b-UetvX0-4LPMdwZc:b-2s0886) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c0417529386f476f133bfa86eafde62f529f17f9/__tests__/ResourcesHelpers.test.js#L47)):*
> ```JavaScript
>       [path.join('en', 'bibles', 'ulb')]: 'v11',
>       [path.join('grc', 'bibles', 'ugnt')]: 'v0'
>     };
> ```

Maybe add a few test cases for the sorting to make sure versions are sorted in order such as "v1","v1.1", "v1.1a","v1.1b","v1.2","v1a","v1a.1"

---

*[src/js/helpers/ResourcesHelpers.js, line 204 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966#-L6azAl2yv4VuKc0tS5z:-L6azAl2yv4VuKc0tS6-:b-jh2qp4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c0417529386f476f133bfa86eafde62f529f17f9/src/js/helpers/ResourcesHelpers.js#L204)):*
> ```JavaScript
>     // by masking all numbers with 100000, sorting the strings, and then removing the mask
>     versions = versions.map( a => a.replace(/\d+/g, n => +n+100000) ).sort()
>       .map( a => a.replace(/\d+/g, n => +n-100000) );
> ```

Creative solution here.  Not sure about all cases.  Maybe need to add more test cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/ResourcesHelpers.test.js, line 47 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966#-L6b-UetvX0-4LPMdwZb:-L6b0q6qtiIGv0fhOWSL:b-71qgi4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c0417529386f476f133bfa86eafde62f529f17f9/__tests__/ResourcesHelpers.test.js#L47)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Maybe add a few test cases for the sorting to make sure versions are sorted in order such as "v1","v1.1", "v1.1a","v1.1b","v1.2","v1a","v1a.1"
</blockquote></details>

Maybe extract the version sorting to a separate method to make easier to test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966)*

**Comment by richmahn** [comment]
@RoyalSix Not really, was trying to fix it up and make sure it was looking right since it has 3 different repos to review.

**Comment by richmahn** [comment]
And still working on some tests.

**Comment by RoyalSix** [comment]
Reviewed 9 of 13 files at r2, 3 of 6 files at r4, 8 of 9 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing: `Pending...`

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966#-:-L6qSBkFfoJC-XECJhCA:bnfp4nl)*

**Comment by richmahn** [comment]
NOTE: Do NOT merge until https://github.com/translationCoreApps/tC_Resources/pull/29 is merged. While not dependent on each other, the alpha.20 increase in package.json is necessary, otherwise the new tW files won't be copied in for anyone that runs alpha.20 before the merge.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3966#-:-L6rQfArxfCIal_ELK8_:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix @PhotoNomad0 It looks like this PR was only tested once. we need to be more diligent when testing PRs locally. especially when we are making major changes like this one.

**Pull request merged**
