### PR TITLE
Fixed Item Status Re-render

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/653)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/653)*

**Comment by ihoegen** [comment]
Looks good to me, just merge with develop and I can merge it

**Comment by RoyalSix** [comment]
Merged @ihoegen

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/653)*

**Pull request merged**
