### PR TITLE
Fixed project upload/sync and added successful upload dialog

### PR DESCRIPTION
**Pull request by mannycolon**
## This pull request addresses:

- Fixed project upload/sync and added successful upload dialog
- Changed error alerts to the new alert dialog component.

## How to test this pull request:

- Try uploading a project from the `my recent projects tab` without opening a project. 
- Open a project and Make changes to it. then upload.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1451)

### CODE REVIEW

**Comment by klappy** [comment]
Are we committing to the repo as we persist data to the file system?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1451#-:-KjL1Q9Ea06nxtcJLS3t:b-ey5hoy)*

**Comment by klappy** [comment]
It seems like we need to add git commits to all functions in the saveMethods.js where the file system is directly written to in order to truly sync with D43. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1451#-:-KjL2PVLHDorJ1JL8wCT:b-4015bq)*

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1451)*

**Comment by RoyalSix** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1451)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1451#-:-KjOHyXDxQ0pBYPj7XIG:bnfp4nl)*

**Pull request merged**
