### PR TITLE
Move Non-Redux Functions

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Move methods that were Non-Redux to helper methods

#### How to test this pull request:
No real way to test

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1001)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix could you try to avoid putting all your changes into one commit. that could be problematic since if you want to go back to one specific change (commit) then you have to options but lose all the other changes you made.

**Comment by mannycolon** [comment]
@RoyalSix can you try to organize your changes in different commits. Having all your changes in one commit is not a good idea because if you need to go back to one specific part of your changes then it becomes a mess.

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/js/helpers/LoadHelpers.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001#-Kg_tU77ZLcmglUWPHLo:-Kg_tU78Pg-YuIksS0Cb:b-oxjz5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1da6dd0d89c913d28cf3f708d347f49a8d215316/src/js/helpers/LoadHelpers.js#L5)):*
> ```JavaScript
> import ManifestGenerator from '../components/core/create_project/ProjectManifest';
> import BooksOfBible from '../components/core/BooksOfBible';
> import pathex from 'path-extra';
> ```

could we only use path-extra and make it path instead of pathex since 'path-extra' contains all `path` methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001#-:-KgaxBryzv_E7bWqRPAU:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001)*

**Comment by klappy** [comment]
@mannycolon: I typically make commits at task level then incremental improvements. Most of the time starting with most if not all of the work done, then each fix as a new commit. I have a hard time committing WIP when it's not functional.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001#-:-KgaxG0XNfX4tU8hiwtp:b-9wdanj)*

**Comment by mannycolon** [comment]
@klappy I believe having too many changes in just one commit is a bad idea. isn't the purpose of git  to able to come back to one specific part of your work just in case you need to make changes or go back to a functioning version of the app.

**Comment by klappy** [comment]
@mannycolon: There are many approaches to maximizing usage of git history. I vary on what I feel the balance is but believe it is somewhere in the center of micro and macro. In fact most recommended workflows of large teams include commit squashing when feature complete before merging into develop branch. This keeps the git history clean and not cluttered with commits that are useless apart from each other. I have rarely if ever found use for commits so granular, but feature commits have been a good balance. I don't typically take the time to squash all patch commits to the feature branch before merging into develop though. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001#-:-KgoOsmS4ZPZ2eQ_ZR1r:b-woxu2f)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001)*

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/js/helpers/LoadHelpers.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001#-Kg_tU77ZLcmglUWPHLo:-KgoVPk_hA2G_eRL78bf:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1da6dd0d89c913d28cf3f708d347f49a8d215316/src/js/helpers/LoadHelpers.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we only use path-extra and make it path instead of pathex since 'path-extra' contains all `path` methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1001)*

**Comment by mannycolon** [comment]
@klappy good to know. thanks.

**Pull request merged**
