### PR TITLE
Online Import Modal

### PR DESCRIPTION
**Pull request by mannycolon**
### This pull request addresses:

- Created Online Import Modal 

### How to test this pull request:
- Try to import a project using the url link 

     `- OR - `

- Go to the projects page and click on the FAB and select Import Online then search by user, language ID and book name. see how the projects fill projects area.

     `- Then -`

- Click the import button

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2217)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 19 of 23 files at r1.
Review status: 19 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 1 of 23 files at r1.
Review status: 20 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 1 of 23 files at r1.
Review status: 21 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 2 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
The code looks nice and clean but I have some blocking issues preventing the testing of the new functionality.
Does it work on your branch and have you committed and pushed all the code?

1. The Project screen renders the modal as soon as I visit that step.
2. Using this feature should alert the user about internet usage since the API search is using the internet.
3. Pasting a project URL renders an error and doesn't let me click import.
4. Searching looks good but I understand the API doesn't line up with the mockups. In that, you may not be able to search on two criteria, but it is an either/or scenario. 
5. Every project, including working ones that I have used in the other mode, result in, "Cannot read project files
" error.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217#-:-KpKySY0hkX-pVWMQlaY:b-v0l5i)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix should be working fine now. Actually better than I anticipated.

**Comment by mannycolon** [comment]
@klappy I feel like I addressed all the issues you previously mentioned above.

**Comment by RoyalSix** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by RoyalSix** [comment]
Good job manny! Theres just one thing that I found. I did a search for 'hi' as the languageId and 'Titus' as the book. I am getting the results of different projects that are not matching that criteria. I looked into and left a comment on the ImportOnlineActions file where I found its fix.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217#-:-KpPvqyz0Fu_zFHtSyBV:b-upv92n)*

**Comment by RoyalSix** [comment]
*[src/js/actions/ImportOnlineActions.js, line 165 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217#-KpPwWtsSfXeMr0z715z:-KpPwWtsSfXeMr0z716-:b7uk1s7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/35bf3f98abfe47d162d5a630688c412167d93258/src/js/actions/ImportOnlineActions.js#L165)):*
> ```JavaScript
>       let filteredRepos = repos.filter((repo) => {
>         if (!secondFilter) {
>           return repo.full_name.includes(filterBy);
> ```

repo.full_name = something like `cdwhitfield73/aa_tit_text_ulb` and if you do an include for the book name 'hi' it will return true although as we know this is not a hindi project.
So maybe a `repo.full_name.split('/')[1].includes(filterBy);` will work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by mannycolon** [comment]
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/ImportOnlineActions.js, line 165 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217#-KpPwWtsSfXeMr0z715z:-KpQ2D-lUuTLuMsXC19O:bomerh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/35bf3f98abfe47d162d5a630688c412167d93258/src/js/actions/ImportOnlineActions.js#L165)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

repo.full_name = something like `cdwhitfield73/aa_tit_text_ulb` and if you do an include for the book name 'hi' it will return true although as we know this is not a hindi project.
So maybe a `repo.full_name.split('/')[1].includes(filterBy);` will work
</blockquote></details>

Good catch. I was actually using the wrong object key.  I forgot to update it.

now it's `repo.name.includes(filterBy)` which is the project name ex. `aa_tit_text_ulb`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 6 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 1 of 12 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
Reviewed 4 of 12 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2217#-:-KpQRsipUL9L7tIBNaSD:bnfp4nl)*

**Pull request merged**
