### PR TITLE
Bugfix 4418/fix WA progress calculations 

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- getWordAlignmentProgressForGroupIndex - fix verse count to tool card progress if some verses alignments not present in chapter alignment.
- in WA tool group circles should change as verse alignments are completed or unaligned.

#### Please include detailed Test instructions for your pull request:
- Test with https://github.com/translationCoreApps/wordAlignment/pull/44
- NOTE: currently there will be no progress shown on progress circles in WA until a chapter is selected and the data is loaded.  But there will be a future fix to WA tool by Joel to load all the chapter data.
- select project (preferably Titus for exact verse progress comparison) and note progress on WA tool card.  In the case of a Titus this percentage should equal the number of aligned verses divided by 46.
- open WA tool card and align verse - after check mark is added should see chapter progress circle increase.  
- exit tool and verify tool progress as increased.  In the case of a Titus
- open WA tool card and unalign a word in the verse - after check mark is removed should see chapter progress circle decrease.  
- exit tool and verify tool progress as decreased.

#### Standard Test Instructions for PR Review Process:
- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4565)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (e7d52de)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-e7d52de.zip) is ready for download.
[macOS build 0.10.0 (e7d52de)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-e7d52de.dmg) is ready for download.
[Windows x64 build 0.10.0 (e7d52de)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-e7d52de.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (e7d52de)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-e7d52de.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6271373)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6271373.zip) is ready for download.
[macOS build 0.10.0 (6271373)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6271373.dmg) is ready for download.
[Windows x64 build 0.10.0 (6271373)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6271373.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6271373)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6271373.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (eabaee8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-eabaee8.zip) is ready for download.
[macOS build 0.10.0 (eabaee8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-eabaee8.dmg) is ready for download.
[Windows x64 build 0.10.0 (eabaee8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-eabaee8.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (eabaee8)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-eabaee8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (e8aac4c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-e8aac4c.zip) is ready for download.
[macOS build 0.10.0 (e8aac4c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-e8aac4c.dmg) is ready for download.
[Windows x64 build 0.10.0 (e8aac4c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-e8aac4c.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (e8aac4c)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-e8aac4c.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Reviewed 1 of 5 files at r3, 3 of 5 files at r4, 2 of 5 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4565)*

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (bc9e980)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-bc9e980.zip) is ready for download.
[macOS build 0.10.0 (bc9e980)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-bc9e980.dmg) is ready for download.
[Windows x64 build 0.10.0 (bc9e980)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-bc9e980.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (bc9e980)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-bc9e980.setup.exe) is ready for download.

**Pull request merged**
