### PR TITLE
MyProjects Actions/Reducers

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Adds Actions and Reducers required to populate the MyProjects section of Home Screen.
This moves all of the logic out of components into the action, including access time.

#### How to test this pull request:

Navigate to the Projects Management on the home screen and it should populate.
No actions work yet... that is next PR

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2026)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/MyProjectsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-Knuptf7cEsCadPp6N2W:-Knuptf7cEsCadPp6N2X:b-fkoujb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L10)):*
> ```JavaScript
> 
> 
> export function getDirectories(directory) {
> ```

should we add comments explaining what this does. and should it be called getProjectsDirectories()?

---

*[src/js/actions/MyProjectsActions.js, line 24 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-KnuqG6yD3wKb921BqhZ:-KnuqG6yD3wKb921Bqh_:b-fi13ld) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L24)):*
> ```JavaScript
>   const projectFolders = folders.filter( folder => {
>     const manifestPath = path.join(DEFAULT_SAVE, folder, 'manifest.json');
>     return fs.existsSync(manifestPath);
> ```

nice job filtering the folders.

---

*[src/js/actions/MyProjectsActions.js, line 32 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-KnuqMOi77txCMgTZbDa:-KnuqMOi77txCMgTZbDb:b-kirck0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L32)):*
> ```JavaScript
>     const projectDataLocation = path.join(projectSaveLocation, '.apps', 'translationCore');
>     const accessTime = fs.statSync(projectDataLocation).atime;
>     const accessTimeAgo = moment().to(accessTime);
> ```

how are you handling projects that were never opened before?

---

*[src/js/components/home/projectsManagement/ProjectCard.js, line 11 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-Knuq_NfXUs04ziOv3rC:-Knuq_NfXUs04ziOv3rD:bkqe47s) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/components/home/projectsManagement/ProjectCard.js#L11)):*
> ```JavaScript
>   let content = <div />;
> 
>   if (projectName && projectDataLocation && accessTimeAgo && bookAbbr && bookName && target_language) {
> ```

do we still need this condition here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-:-Knuqv7l2mFRsPe5Ym4k:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 1 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026)*

**Comment by mannycolon** [comment]
@klappy Tests passed

**Comment by klappy** [comment]
*[src/js/actions/MyProjectsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-Knuptf7cEsCadPp6N2W:-Knut_Xmmh3HinXGmLRk:bh90wku) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

should we add comments explaining what this does. and should it be called getProjectsDirectories()?
</blockquote></details>

Good point, will do!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026)*

**Comment by klappy** [comment]
*[src/js/actions/MyProjectsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-Knuptf7cEsCadPp6N2W:-KnutgfcSUxLebwSYlll:boearwk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good point, will do!
</blockquote></details>

Technically this is a helper as it will get the list of directories inside any directory given.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026)*

**Comment by klappy** [comment]
*[src/js/actions/MyProjectsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-Knuptf7cEsCadPp6N2W:-KnutyncDP5PHJDqyWmw:bet5zx1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fddbbe59d57896a4394dbf48ebf5ec2ecbe07833/src/js/actions/MyProjectsActions.js#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Technically this is a helper as it will get the list of directories inside any directory given.
</blockquote></details>

I'll go ahead and refactor the directory code out of the other funciton and make this one specific to our use case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2026#-:-KnvJHD2tMkGTACgDCpD:bnfp4nl)*

**Pull request merged**
