### PR TITLE
QAFail - Fixes #5708 - Preserves checks with GL code and removes dead code

### LINKED ISSUE #5708: Add data to CSV export with additional information
(Former title: A column for the tW type (Key terms, Other terms, Names) should be added to the translationWords_CheckInformation.csv and selections.csv files)

Since we allow distinguishing between them in the app, it makes sense to do the same in the related csv files. It also may be important for those who would want to check manually using the spreadsheet.

## Specs 
- [x] tW export 
  - [x] Add `Type` column on tW export. Fill with `Key terms`, `Other terms`, and `Names`
- [x] tN export
  - [x] Add Priority 1 to all checks
  - [x] Add `Type` column, fill with the `Head Category`
  - [x] Add `GL Quote` column
  - [x] Add `Occurrence Note` column

image

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Another QA Fail Fix for #5708 
- This issue was found by me, noticing that Selections, Comments and Reminders, the GL language and quote at the time of the event were not being put in the CSV file, they were being ignored and was getting the GL info in English like we do for the CheckInformation.csv files
- I also removed code that is no longer needed. This old code was getting group index just for translationWord for the `kt` category (from back when we only had one tool and one category). We now get groupName and groupCategory more dynamically in the functions you can see called in the flattenContextId() function
- Standardized the GL variables to be the same as what we get from the JSON files (`gatewayLanguageCode` and `gatewayLanguageQuote`)

#### Please include detailed Test instructions for your pull request:
- Unit tests should pass
- Run the build
- Open a project and go into tW and tN in both English and Hindi as the GL, making selections, comments, verse edits and reminders in both GL languages.
- Go back to the projects list page, export your project to CSV, extract files
- Verify that Comments.csv, Reminders.csv, Selections.csv, and VerseEdits.csv the following:
  - `groupName` is in the GL you were in when you made it
  - `gatewayLanguageCode` is for the GL you were in when yo made it
  - `gatewayLanguageQuote` is in the GL you were in when you made it
- Verify that the CheckInformation.csv files for tW and tN have the above data in English as before, as that is the only GL we currently support for those files

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6266)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (e2b24de)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-linux-x64-2.0.0-e2b24de.deb) is ready for download.
[macOS build 2.0.0 (e2b24de)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-macos-x64-2.0.0-e2b24de.dmg) is ready for download.
[Windows x64 build 2.0.0 (e2b24de)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x64-2.0.0-e2b24de.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (e2b24de)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x32-2.0.0-e2b24de.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (4ae8fce)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-linux-x64-2.0.0-4ae8fce.deb) is ready for download.
[macOS build 2.0.0 (4ae8fce)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-macos-x64-2.0.0-4ae8fce.dmg) is ready for download.
[Windows x64 build 2.0.0 (4ae8fce)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x64-2.0.0-4ae8fce.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (4ae8fce)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x32-2.0.0-4ae8fce.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (4519b56)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-linux-x64-2.0.0-4519b56.deb) is ready for download.
[macOS build 2.0.0 (4519b56)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-macos-x64-2.0.0-4519b56.dmg) is ready for download.
[Windows x64 build 2.0.0 (4519b56)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x64-2.0.0-4519b56.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (4519b56)](https://tc-builds.door43.org/build/qafail-richmahn-5708.2/translationCore-win-x32-2.0.0-4519b56.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6266)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
