### PR TITLE
Feature bspidel 5755

### PR DESCRIPTION
**Pull request by bspidel**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Add Popover (click category) to each sub-category (or group) to show first introductory paragraph of tA.
- Some tA articles have introduction and some do not. this code shows introduction and stops at description if there is an introduction. It displays 1st 500 characters of description if there is no introduction. 
- It is quite slow and may need refactored if it is too slow.

#### Please include detailed Test instructions for your pull request:
- Test with 2 or more projects. Each will have distinct set of categories.
- Launch tool
- Use chevrons to expose sub-categories
- Click on text of category to see tA content

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)

### CODE REVIEW

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: all files reviewed, 9 unresolved discussions (waiting on @bspidel)

___
*[src/css/styles.css, line 366 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbPZi0LEUnQXAhmucbA:-LbPZi0M9pJ49t3QOaNY:b-yt1qgg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/css/styles.css#L366)):*
> ```CSS
> }
> 
> .popover-root > div:nth-child(1) { /* removes scrollbar from popover-roots child set by material-ui */
> ```

why are we removing the scrollbar? Should we also add the reason in the comment ?
___
*[src/js/components/Popover.js, line 7 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbPZr7R321ROOuFr2ck:-LbPZr7R321ROOuFr2cl:b-e7fsrw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/Popover.js#L7)):*
> ```JavaScript
> import { Glyphicon } from 'react-bootstrap';
> 
> // overflow-y: hidden !important; 
> ```

do we need this comment here?
___
*[src/js/components/Popover.js, line 10 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_181DisJa5r_rK6p:-LbP_181DisJa5r_rK6q:b-ynb26r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ef7047af4e033b6b29a3c3168f3484ae1a8d60ff/src/js/components/Popover.js#L10)):*
> ```JavaScript
>   render() {
>     let { popoverVisibility, title, bodyText, positionCoord, onClosePopover } = this.props;
>     if (!popoverVisibility) {
> ```

why did you remove this code?
___
*[src/js/components/Popover.js, line 48 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_7v6C-aErlqPQ8rg:-LbP_7v6C-aErlqPQ8rh:b-go6d08) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/Popover.js#L48)):*
> ```JavaScript
> }
> 
> // all style  padding: '20px',
> ```

do we need these comments here?
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 110 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_HBHCMDdUFDTAn6i:-LbP_HBHCMDdUFDTAn6j:bzd5a76) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L110)):*
> ```JavaScript
> 
>     console.log( "availableCategories: ", this.props.availableCategories );  
>     //const keys = this.props.availableCategories.keys;
> ```

do we need this console.log here?
And the commented out code as well?
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 117 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_N-64efzjBrotAbS:-LbP_N-64efzjBrotAbT:b-2guby3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L117)):*
> ```JavaScript
> 
>       for(var group in category ) {
>         //let groups = this.props.availableCategories[category];
> ```

same here
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 131 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_SnkBLiaN-oAa-Yw:-LbP_SnkBLiaN-oAa-Yx:bb7hzsp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L131)):*
> ```JavaScript
> 
>     this.setState( {"articles": articles} );
> console.log( "articles: ", articles );    
> ```

ibid
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 148 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_twV6qOT6FrLveb5:-LbP_twV6qOT6FrLveb6:b5bpqm7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ef7047af4e033b6b29a3c3168f3484ae1a8d60ff/src/js/components/home/toolsManagement/ToolCardBoxes.js#L148)):*
> ```JavaScript
>                             <div style={{marginLeft: '36px', width: '38px'}}>
>                               {localCheckBox(selectedCategories, subcategory, toolName, onChecked)}</div>
>                             <div>{translate(lookupNames[postPart(subcategory)])}</div>
> ```

it looks like we used to have the translate function handling locales and in your new code it doesn't look like we are doing that anymore?
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 149 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_aGN-iJ4FgnwG7T1:-LbP_aGN-iJ4FgnwG7T2:b-x24x92) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L149)):*
> ```JavaScript
>     const positionCoord = event.target;
>     const fullText = this.state.articles[category];
> ```

should the code that parses the definition be a helper function outside this component so that it is testable?

**Review by mannycolon — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @bspidel and @mannycolon)

**Review by mannycolon — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @bspidel and @mannycolon)

**Review by mannycolon — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: all files reviewed, 3 unresolved discussions (waiting on @bspidel)

**Comment by mannycolon** [comment]
Still getting `Cannot find module '../../../helpers/toolCardHelpers' from 'ToolCardBoxes.js'`

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (0c88b3a)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-linux-x64-1.2.0-0c88b3a.deb) is ready for download.
[macOS build 1.2.0 (0c88b3a)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-macos-x64-1.2.0-0c88b3a.dmg) is ready for download.
[Windows x64 build 1.2.0 (0c88b3a)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-win-x64-1.2.0-0c88b3a.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (0c88b3a)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-win-x32-1.2.0-0c88b3a.setup.exe) is ready for download.

**Review by bspidel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @mannycolon)

___
*[src/css/styles.css, line 366 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbPZi0LEUnQXAhmucbA:-LbPd4gaA7hOORra-XQd:b3fuove) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/css/styles.css#L366)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are we removing the scrollbar? Should we also add the reason in the comment ?
</blockquote></details>

unhelpfull scrollbars were added automatically by material-ui.  I just suppressed them. added detail to comment
___
*[src/js/components/Popover.js, line 7 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbPZr7R321ROOuFr2ck:-LbPywXVAEkiPXu3zrhl:b-hfpv0l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/Popover.js#L7)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need this comment here?
</blockquote></details>

removed
___
*[src/js/components/Popover.js, line 10 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_181DisJa5r_rK6p:-LbPdXWt1Ki9mFdgIOAd:bbc7snd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ef7047af4e033b6b29a3c3168f3484ae1a8d60ff/src/js/components/Popover.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you remove this code?
</blockquote></details>

Jay said it is redundant as popover has same test.
___
*[src/js/components/Popover.js, line 48 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_7v6C-aErlqPQ8rg:-LbPe-6u5CVOxssLkECG:b-hfpv0l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/Popover.js#L48)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need these comments here?
</blockquote></details>

removed
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 110 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_HBHCMDdUFDTAn6i:-LbPeUWJ-lfZt_s1n_Fj:b-hfpv0l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L110)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we need this console.log here?
And the commented out code as well?
</blockquote></details>

removed
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 117 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_N-64efzjBrotAbS:-LbPeXg_D9B2HarlLXrG:b-hfpv0l) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L117)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here
</blockquote></details>

removed
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 131 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_SnkBLiaN-oAa-Yw:-LbPepZnAIEmfrq7_n_M:b-7ropln) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L131)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ibid
</blockquote></details>

ditto
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 148 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_twV6qOT6FrLveb5:-LbPf_02BKo-r6VtYrnH:b-p7p2x0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/ef7047af4e033b6b29a3c3168f3484ae1a8d60ff/src/js/components/home/toolsManagement/ToolCardBoxes.js#L148)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

it looks like we used to have the translate function handling locales and in your new code it doesn't look like we are doing that anymore?
</blockquote></details>

it still localizes category but the tA content is already in the gateway language. Change is from div to span for formatting.
___
*[src/js/components/home/toolsManagement/ToolCardBoxes.js, line 149 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936#-LbP_aGN-iJ4FgnwG7T1:-LbPlnVUAtOm-srpRhNa:b48dwbb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eb7e6248f0d26f7367a8ba8af1211caf632ac77e/src/js/components/home/toolsManagement/ToolCardBoxes.js#L149)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

should the code that parses the definition be a helper function outside this component so that it is testable?
</blockquote></details>

Moved to helpers/toolCardHelpers.js

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (924979f)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-linux-x64-1.2.0-924979f.deb) is ready for download.
[macOS build 1.2.0 (924979f)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-macos-x64-1.2.0-924979f.dmg) is ready for download.
[Windows x64 build 1.2.0 (924979f)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-win-x64-1.2.0-924979f.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (924979f)](https://tc-builds.door43.org/build/feature-bspidel-5755/translationCore-win-x32-1.2.0-924979f.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5936)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mannycolon** [comment]
CODE REVIEW:`LGTM`
LOCAL TEST: `PENDING`

**Pull request merged**
