### PR TITLE
Bugfix mcleanb 6192/Add feedback prompt for broken tn checks

### LINKED ISSUE #5990: The actual application log (from the file system) is not attached to the Trello card on the  Door43 Helpdesk
1.1.3 (cf7905c) 
Dup of #5836? - yes @PhotoNomad0 
Here is a link to the Trello card: https://trello.com/c/2TqJm73R/77-tc-general-feedback
Here is the log file: [https://app.zenhub.com/files/65028237/5b85b03e-d520-417d-9d75-2d6e7f27e02f/download](https://app.zenhub.com/files/65028237/5b85b03e-d520-417d-9d75-2d6e7f27e02f/download)

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Add feedback prompt for broken tn checks 
- fixes for sending feedback so server doesn't choke on large reducer data.
- switched to using sendmail module instead of axios
- removed reducer data, and added log data as zip attachment (this should also fix https://github.com/unfoldingword-dev/translationcore/issues/5990)

#### Please include detailed Test instructions for your pull request:
- open this project: [en_ult_rut_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3369269/en_ult_rut_book.zip)
- launch tN and select Category> Assumed Knowledge and Implicit Information> Ruth 1:1
- should see this alert:

Screen Shot 2019-07-26 at 8 13 30 AM
- click ignore and you should return to next check.
- again select Category> Assumed Knowledge and Implicit Information> Ruth 1:1
- at alert click "Send Feedback"
- should see new dialog pre-populated with error info, category of "Content...", and logs selected:

Screen Shot 2019-07-26 at 8 17 44 AM
- add your email (in case Jesse wants to track you down) and click submit
- it should pop up a success message.
- click OK and it should return you to next check.
- if you want to know if the feedback went through, you have two options:
  - ask Jesse to add you to the notification list.  Then you can look at the messages here: https://forum.door43.org/t/tc-content-and-resources-feedback
  - let me know and I can check.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (dc7430f)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-dc7430f.deb) is ready for download.
[macOS build 2.0.0 (dc7430f)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-dc7430f.dmg) is ready for download.
[Windows x64 build 2.0.0 (dc7430f)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-dc7430f.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (dc7430f)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-dc7430f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (b21204e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-b21204e.deb) is ready for download.
[macOS build 2.0.0 (b21204e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-b21204e.dmg) is ready for download.
[Windows x64 build 2.0.0 (b21204e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-b21204e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (b21204e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-b21204e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (045d967)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-045d967.deb) is ready for download.
[macOS build 2.0.0 (045d967)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-045d967.dmg) is ready for download.
[Windows x64 build 2.0.0 (045d967)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-045d967.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (045d967)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-045d967.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (7c30458)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-7c30458.deb) is ready for download.
[macOS build 2.0.0 (7c30458)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-7c30458.dmg) is ready for download.
[Windows x64 build 2.0.0 (7c30458)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-7c30458.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (7c30458)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-7c30458.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (af0cc8e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-af0cc8e.deb) is ready for download.
[macOS build 2.0.0 (af0cc8e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-af0cc8e.dmg) is ready for download.
[Windows x64 build 2.0.0 (af0cc8e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-af0cc8e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (af0cc8e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-af0cc8e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (cc0a884)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-cc0a884.deb) is ready for download.
[macOS build 2.0.0 (cc0a884)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-cc0a884.dmg) is ready for download.
[Windows x64 build 2.0.0 (cc0a884)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-cc0a884.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (cc0a884)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-cc0a884.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c6c4b9b)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-c6c4b9b.deb) is ready for download.
[macOS build 2.0.0 (c6c4b9b)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-c6c4b9b.dmg) is ready for download.
[Windows x64 build 2.0.0 (c6c4b9b)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-c6c4b9b.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c6c4b9b)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-c6c4b9b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (5c6133d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-5c6133d.deb) is ready for download.
[macOS build 2.0.0 (5c6133d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-5c6133d.dmg) is ready for download.
[Windows x64 build 2.0.0 (5c6133d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-5c6133d.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (5c6133d)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-5c6133d.setup.exe) is ready for download.

**Review by richmahn — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 4 files at r2, 2 of 4 files at r7, 3 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0 and @richmahn)

___
*[src/js/helpers/FeedbackHelpers.js, line 33 at r9](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274#-LkizTm29xY037DUN_Br:-LkizTm29xY037DUN_Bs:b-pq8bd9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5c6133d06c6cbbeec8dc17d7ecd54461a6d9ec22/src/js/helpers/FeedbackHelpers.js#L33)):*
> ```JavaScript
>     }
>   };
>   // TODO:
> ```

A TODO: comment without anything TO DO.

**Review by richmahn — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 4 files at r2, 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Review by richmahn — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Review by richmahn — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274#-:-LkjGJ4U8YuQvFy69_YN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Review by richmahn — COMMENTED** [review]
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Review by richmahn — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6274#-:-LkjIY-L6vedDa6KQE1A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (c8f7c3e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-c8f7c3e.deb) is ready for download.
[macOS build 2.0.0 (c8f7c3e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-c8f7c3e.dmg) is ready for download.
[Windows x64 build 2.0.0 (c8f7c3e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-c8f7c3e.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c8f7c3e)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-c8f7c3e.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (4f43df6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-linux-x64-2.0.0-4f43df6.deb) is ready for download.
[macOS build 2.0.0 (4f43df6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-macos-x64-2.0.0-4f43df6.dmg) is ready for download.
[Windows x64 build 2.0.0 (4f43df6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x64-2.0.0-4f43df6.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (4f43df6)](https://tc-builds.door43.org/build/bugfix-mcleanb-6192/translationCore-win-x32-2.0.0-4f43df6.setup.exe) is ready for download.

**Pull request merged**
