### PR TITLE
Bugfix 4418/fix WA progress calculations

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Fixes progress calculation issues in:  https://github.com/unfoldingWord-dev/translationCore/issues/4418

- Fixes issues with calculating WA progress:
  - fixes issue in WA that unaligned chapters show progress when chapter group is opened.
  - fixes bug that empty verses are counted as 100% done.
  - fixes bug that fully aligned chapters are not counted as 100% done.
- Speed up progress calculations by removing unnecessary loops.

#### Please include detailed Test instructions for your pull request:
- follow steps in issue: https://github.com/unfoldingWord-dev/translationCore/issues/4418

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4503)

### CODE REVIEW

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by da1nerd** [comment]
Concourse just ran all your tests! Woohoo!

**Comment by mannycolon** [comment]
@PhotoNomad0 Shouldn't these changes be made in the `tc-ui-toolkit` as well?

**Comment by PhotoNomad0** [comment]
This is ready to review.

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4503#-:-LDrWhCr4RUrcdl7Uafk:bnfp4nl)*

**Pull request merged**
