### PR TITLE
Automated builds, includes desktop icons

### PR DESCRIPTION
**Pull request by ihoegen**
This commit allows for creation of desktop and start menu icons, and makes the build process a lot easier for me.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/333)

### CODE REVIEW

**Comment by mannycolon** [comment]
@EllDoubleYew were you able to test this branch??

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[main.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/333#-KXhZhQ53nFs5Ygtlc2J:-KXhZhQ53nFs5Ygtlc2K:bndpl94) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/b52df51ec16c010bf2ae44be6d2b85500ac4263f/main.js#L17)):*
> ```JavaScript
>   var createShortcut = updateDotExe + ' --createShortcut translationCore.exe';
>   console.log (createShortcut);
>   exec(createShortcut);
> ```

Theres two console logs in this file, do those need to be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/333)*

**Comment by ihoegen** [comment]
@RoyalSix Yes, I'll fix that

**Comment by ihoegen** [comment]
@RoyalSix Ready to go

**Comment by ihoegen** [comment]
@RoyalSix Ignore what travis-ci says on this for now

**Comment by RoyalSix** [comment]
Ok, sounds good.

**Comment by RoyalSix** [comment]
Reviewed 2 of 4 files at r2, 31 of 31 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/333)*

**Pull request merged**
