### PR TITLE
Preserving Original ID Header Content

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR address the issue with original `\id` content being removed on export.

#### Please include detailed Test instructions for your pull request:
- Import this project: [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2664176/57-TIT.usfm.zip)
- Export the project to usfm and ensure that the `\id` tag still contains the original conent. In this case you should see `unfoldingWord Literal Text` right before the date.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5545)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-8fb5739.deb) is ready for download.
[macOS build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-8fb5739.dmg) is ready for download.
[Windows x64 build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-8fb5739.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-8fb5739.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-8fb5739.deb) is ready for download.
[macOS build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-8fb5739.dmg) is ready for download.
[Windows x64 build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-8fb5739.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8fb5739)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-8fb5739.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (35c1320)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-35c1320.deb) is ready for download.
[macOS build 1.1.0 (35c1320)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-35c1320.dmg) is ready for download.
[Windows x64 build 1.1.0 (35c1320)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-35c1320.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (35c1320)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-35c1320.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-8993bef.deb) is ready for download.
[macOS build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-8993bef.dmg) is ready for download.
[Windows x64 build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-8993bef.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-8993bef.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-8993bef.deb) is ready for download.
[macOS build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-8993bef.dmg) is ready for download.
[Windows x64 build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-8993bef.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8993bef)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-8993bef.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (427495c)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-427495c.deb) is ready for download.
[macOS build 1.1.0 (427495c)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-427495c.dmg) is ready for download.
[Windows x64 build 1.1.0 (427495c)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-427495c.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (427495c)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-427495c.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3f4021a)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-linux-x64-1.1.0-3f4021a.deb) is ready for download.
[macOS build 1.1.0 (3f4021a)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-macos-x64-1.1.0-3f4021a.dmg) is ready for download.
[Windows x64 build 1.1.0 (3f4021a)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x64-1.1.0-3f4021a.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3f4021a)](https://tc-builds.door43.org/build/feature-jay-4918/translationCore-win-x32-1.1.0-3f4021a.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5545)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
