### PR TITLE
Bugfix 5119

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- made fixes to scripture pane dropdown:
  - add target language to list
  - correct language id for grc and hbo to original language to be compatible with how we store scripture pane selections.

#### Please include detailed Test instructions for your pull request:
- should be able to delete and re-add target language and OL to scripture Pane in both tW and wA

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5693)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (ffbb27b)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-linux-x64-1.1.0-ffbb27b.deb) is ready for download.
[macOS build 1.1.0 (ffbb27b)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-macos-x64-1.1.0-ffbb27b.dmg) is ready for download.
[Windows x64 build 1.1.0 (ffbb27b)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x64-1.1.0-ffbb27b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ffbb27b)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x32-1.1.0-ffbb27b.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c5110b9)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-linux-x64-1.1.0-c5110b9.deb) is ready for download.
[macOS build 1.1.0 (c5110b9)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-macos-x64-1.1.0-c5110b9.dmg) is ready for download.
[Windows x64 build 1.1.0 (c5110b9)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x64-1.1.0-c5110b9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c5110b9)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x32-1.1.0-c5110b9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-linux-x64-1.1.0-c9a4814.deb) is ready for download.
[macOS build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-macos-x64-1.1.0-c9a4814.dmg) is ready for download.
[Windows x64 build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x64-1.1.0-c9a4814.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x32-1.1.0-c9a4814.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-linux-x64-1.1.0-c9a4814.deb) is ready for download.
[macOS build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-macos-x64-1.1.0-c9a4814.dmg) is ready for download.
[Windows x64 build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x64-1.1.0-c9a4814.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c9a4814)](https://tc-builds.door43.org/build/bugfix-mcleanb-5119/translationCore-win-x32-1.1.0-c9a4814.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5693#-:-LWUKKeu2rgf1Rbu7eB8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
