### PR TITLE
QA Fail/Fix - #3559 - Removes 'Reimport Project' from project context menu

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses the last comment in #3559 by @cckozie on removing the "Reimport Project" option from the Project context menu. Not able to reproduce bug on Mac or Windows in regards to not being able to open wA after a reimport.

#### Please include detailed Test instructions for your pull request:
- Verify Reimport Project option is gone from the project card context menu
- See if it ever fails for you when reimporting a project and going into a tool

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4760)

### CODE REVIEW

**Review by mannycolon — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4760)* status: all files reviewed, 1 unresolved discussion (waiting on @richmahn, @RoyalSix, and @bspidel)

___
*[src/locale/Hindi-hi_IN.json, line 132 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4760#-LI80c6XDCHlr7YMQ51-:-LI80c6YEs6iAPu26Sld:b-nk3876) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/db8cd5389d9b8ef397fccf3800405886f28a45c2/src/locale/Hindi-hi_IN.json#L132)):*
> ```JSON
>     "upload_to_d43": "${door43} पर अपलोड करें",
>     "edit_project_details": "प्रोजेक्ट विवरण संपादित करें",
>     "reimport_project": "परियोजना आयात करें",
> ```

Don't delete the string from here let crowd in dod that automatically we should never touch the Hindi locale file only the English

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix and @bspidel)

**Review by mannycolon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RoyalSix and @bspidel)

**Comment by mannycolon** [comment]
@richmahn Fixed unit tests

**Comment by mannycolon** [comment]
Local Test: `LGTM`

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (ef29783)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-ef29783.zip) is ready for download.
[macOS build 0.10.0 (ef29783)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-ef29783.dmg) is ready for download.
[Windows x64 build 0.10.0 (ef29783)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-ef29783.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (ef29783)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-ef29783.setup.exe) is ready for download.

**Pull request merged**
