### PR TITLE
Now displaying the GL for the subcategories text in the tool cards 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Verify that subcategories on the tN tool cards are displayed in the language of the selected GL
- Change the GL in the tool card to Hindi and verify the subcategories are displayed in Hindi

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (161c7f3)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-linux-x64-2.0.0-161c7f3.deb) is ready for download.
[macOS build 2.0.0 (161c7f3)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-macos-x64-2.0.0-161c7f3.dmg) is ready for download.
[Windows x64 build 2.0.0 (161c7f3)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-win-x64-2.0.0-161c7f3.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (161c7f3)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-win-x32-2.0.0-161c7f3.setup.exe) is ready for download.

**Review by RoyalSix — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/actions/ProjectDetailsActions.js, line 78 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277#-Lk_mghG7G33jXf4AAWk:-Lk_mghHEpNofZwO2s_v:bs1c1t1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/161c7f3674af47085696c8c32c149ba1d611a3ec/src/js/actions/ProjectDetailsActions.js#L78)):*
> ```JavaScript
>  * @param {bool} isChecked - Is the subcategory checkbox checked or uncheked.
>  */
> export const updateSubcategorySelection = (subcategory, toolName, isChecked) => {
> ```

Could you briefly explain the need for 2 different functions `updateSubcategorySelection` and `updateCategorySelection`?
As opposed to one like before?

**Comment by mannycolon** [comment]
@RoyalSix 
```
Functions
Here's a nice starter quote about functions:

"The first rule of functions is that they should be small."

As you've probably read elsewhere, a function should do one thing, and only one thing.
 

"Functions should do something, or answer something, but not both."

As he states, a function should change the state of an object, or return some information about that object, but not both. I've run into many functions over the years where a function was named "setSomething", and then when I looked at the source for that function, I found that it did several other things besides the "set" it claimed to do
```
https://alvinalexander.com/programming/clean-code-quotes-robert-c-martin


Basically the previous versión was setting the category and the subcategories. The new two functions decouple both into two to clearly imply what they do.

**Review by RoyalSix — COMMENTED** [review]
I thought it was just doing one thing. Setting the subcategories. We never kept track of the parent categories before. It was just fetched we needed based on the mapping.


In the screenshot below I was selecting the parent category for culture and the following happened.

.png)

I am not saying either implementation is better, I just did not understand the reasoning so that's why I asked. It seemed simpler/clean to me before but maybe it was not.

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277#-:-Lka5DZP1HA8TTpGRIYH:b-yfndw2)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Review by RoyalSix — COMMENTED** [review]
It was about 20 lines of code before, now it's about twice as much to do the same thing. I didn't know if it was needed now though given the new requirement of localization

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277#-:-Lka6lm06bbgN2gTZIWQ:b-fh00kc)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Comment by mannycolon** [comment]
It looks like your testing the wrong branch. are you sure you're testing `bugfix-mannycolon-6056`?

**Comment by dsm-git** [comment]
[Linux build 2.0.0 (79ea148)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-linux-x64-2.0.0-79ea148.deb) is ready for download.
[macOS build 2.0.0 (79ea148)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-macos-x64-2.0.0-79ea148.dmg) is ready for download.
[Windows x64 build 2.0.0 (79ea148)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-win-x64-2.0.0-79ea148.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (79ea148)](https://tc-builds.door43.org/build/bugfix-mannycolon-6056/translationCore-win-x32-2.0.0-79ea148.setup.exe) is ready for download.

**Comment by RoyalSix** [comment]
Yes, it was the correct branch that I tested. The screenshot I shared was comparing the current develop branch. I trust your decision to make that method into two functions. I think both have pros and cons and we can adjust later if we need to.

**Review by RoyalSix — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6277)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

**Pull request merged**
