### PR TITLE
Feature - #3676 - Status badges with chips and mouse-over

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses first task of epic #1998 - showing multiple status badges for invalidation (still waiting on its implementation in #3086 but doesn't block this PR), reminders, verse edits, selections and comments.

#### Please include detailed Test instructions for your pull request:
NOTE: This does NOT have the filter menu at the top like you see in the images in #1998. It should however have the icons next to the Bible references like you see in those images, minus the ability to see invalidated verses.

- [ ] Check out this branch, `feature-richmahn-3676` in your main tC repo
- [ ] Run `npm i && npm run update-apps` in tC root directory
- [ ] Run the app, load a project
- [ ] For tW, in the left sidebar, you should see no badge, one badge, or a badge with a chip with 2 - 5 (5 if invalidation is implemented [#3086], 4 if not). So try bookmarking the active verse, making  a comment, selecting text, and editing the verse.
- [ ] For wA, when the word bank is empty, a check box should appear. This is how it used to behave, but it also uses the new status badge implementation to make it happen, so test it.
- [ ] Note that in tW, because there was already a tool tip to show the full selected text when you hover over the Bible reference in the left sidebar, I had to separate the tool tip for the status badge and the tool tip for the Bible reference/selected text. They both use the new 3rd party react-tooltip now. Please check for any oddities. The tool tip SHOULD change position (float right instead of bottom) if there isn't room below to show the whole tool tip. This is expected. 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4211)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@richmahn 
Local Testing: 
- There is an issue with the progress on the specific check.
  - If you make a selection, and then bookmark it, then unbookmark it the progress goes back to zero. 
  - The progress should be greater than one at this point because it has a selection.
- I had a question if it matters which icon is last showing? Because I was able to make not the last one used.

Code Review: `Pending...`

**Comment by richmahn** [comment]
@RoyalSix It always goes by the precedence that Ben gave:

```
That order has already been set (minus Invalidated which is new). But to make it explicit. 
1. Invalidated
2. Bookmark
3. Selected
4. Verse Edit
5. Comment
```
So you'll never see (at this point since there is no invalidation boolean in the contextId) a bookmark icon in the tooltip because it is always first. You will also never see a comment badge as the main glyph when there are other badges.

**Comment by richmahn** [comment]
@RoyalSix Not sure if I'm following as my fix has nothing to do with progress, only what things have been done to the given verse. Please check if it did that before I added the ability to see all the status badges. That's all this enhancement does.

**Comment by richmahn** [comment]
@RoyalSix That bookmark bug(?) was already how tC works. Not sure if bug or feature. @benjore ?

**Comment by RoyalSix** [comment]
@richmahn Ok sounds good. Doing a code review now

**Comment by mannycolon** [comment]
@richmahn Shouldn't this PR be made against a sandbox branch since it belongs to the next release?

**Comment by RoyalSix** [comment]
Reviewed 3 of 10 files at r1, 4 of 13 files at r2, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/js/helpers/statusBadgeHelpers.js, line 61 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211#-L9I3Z2X49txoif-Vq3T:-L9I3Z2X49txoif-Vq3U:b-83ywsm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/4484662dab8af5befb5861d9f0f96c8c86287f76/src/js/helpers/statusBadgeHelpers.js#L61)):*
> ```JavaScript
>  */
> export function getInvalidatedIcon() {
>   return (
> ```

Any reason you did not want to put this `svg` in assets or images and then require it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211)*

**Comment by RoyalSix** [comment]
@mannycolon That is true

**Comment by richmahn** [comment]
@mannycolon Ok, didn't know we were doing sandbox branches. Not clear how any of that works. What sandbox branch do I make this to?

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/statusBadgeHelpers.js, line 61 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211#-L9I3Z2X49txoif-Vq3T:-L9IQp37EbfrNYmQglPi:b-ccb3g4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e462878fbec8fa461724436905ad2039530f3b09/src/js/helpers/statusBadgeHelpers.js#L61)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Any reason you did not want to put this `svg` in assets or images and then require it?
</blockquote></details>

Would love to but never could figure out how. I saved it originally as a .svg but every time I read it, it was just a string and wasn't able to style it.

If you could show me how I could import it as an React element that would be great. Any example I could follow?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211)*

**Comment by mannycolon** [comment]
@richmahn Heres the documentation https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#

Search for sandbox and the next release is 0.10

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/statusBadgeHelpers.js, line 61 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211#-L9I3Z2X49txoif-Vq3T:-L9ImBgX5ezaYyKxtZU-:bsgj4k7) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e462878fbec8fa461724436905ad2039530f3b09/src/js/helpers/statusBadgeHelpers.js#L61)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

Would love to but never could figure out how. I saved it originally as a .svg but every time I read it, it was just a string and wasn't able to style it.

If you could show me how I could import it as an React element that would be great. Any example I could follow?
</blockquote></details>

I tried an  tag but you can't change their colors. <svg> tags you can.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/statusBadgeHelpers.js, line 61 at r3](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211#-L9I3Z2X49txoif-Vq3T:-L9ImNh2DtVwn47uqfhL:b-8sxmxb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/e462878fbec8fa461724436905ad2039530f3b09/src/js/helpers/statusBadgeHelpers.js#L61)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

I tried an  tag but you can't change their colors. <svg> tags you can.
</blockquote></details>

Oops. Can't write html. 
```
I tried an <img> tag but you can't change their colors. <svg> tags you can.
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4211)*

**Comment by richmahn** [comment]
@RoyalSix Took some more tries at the svg file, including using the `<object data="./images/invalidated.svg" ...>` tag, but no luck on being able to style it based on placement (needs to be white when the main glyph, black when in the tooltip). The only way to actually style a svg object is for it to be inline and not read from a file by the html interpreter. I still stand by making it React component like I did so it will be rendered inline and can add styling easily.

**Pull request closed without merging**
