### PR TITLE
Optimized Initial startup time of tC

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-  Optimized Initial startup time of tC

#### Please include detailed Test instructions for your pull request:
- Start up the app w/ `npm start`
- tC should open within 9-30 sec compared to 1-1:30 mins in the past or currently in develop branch (stats may defer based on your laptops specs)
- Do the same test on the build created by `DSM BOT`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5498)

### CODE REVIEW

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5498)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
LGTM - but cannot merge since unit tests are failing.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (063c0be)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-063c0be.deb) is ready for download.
[macOS build 1.1.0 (063c0be)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-063c0be.dmg) is ready for download.
[Windows x64 build 1.1.0 (063c0be)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-063c0be.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (063c0be)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-063c0be.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (068e694)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-068e694.deb) is ready for download.
[macOS build 1.1.0 (068e694)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-068e694.dmg) is ready for download.
[Windows x64 build 1.1.0 (068e694)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-068e694.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (068e694)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-068e694.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (3f20646)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-3f20646.deb) is ready for download.
[macOS build 1.1.0 (3f20646)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-3f20646.dmg) is ready for download.
[Windows x64 build 1.1.0 (3f20646)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-3f20646.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (3f20646)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-3f20646.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Tried running Concourse build on windows and got an error:

screen shot 2018-12-05 at 7 27 00 am

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Comment by PhotoNomad0** [comment]
@mannycolon - I get same error as above on mac.  Will try a local build now.

**Comment by PhotoNomad0** [comment]
@mannycolon - it also fails locally.  Did:
```
git fetch --all
git checkout feature-mannycolon-5234
git pull
npm run update-apps
npm ci
```

Suspect issue with package-lock.json, because if I remove node_modules and package-lock.json, and do `npm i`, it runs correctly.

**Review by mannycolon — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5498)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (4617b09)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-4617b09.deb) is ready for download.
[macOS build 1.1.0 (4617b09)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-4617b09.dmg) is ready for download.
[Windows x64 build 1.1.0 (4617b09)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-4617b09.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4617b09)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-4617b09.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Concourse build Still not working.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5498)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (60edcb9)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-60edcb9.deb) is ready for download.
[macOS build 1.1.0 (60edcb9)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-60edcb9.dmg) is ready for download.
[Windows x64 build 1.1.0 (60edcb9)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-60edcb9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (60edcb9)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-60edcb9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (049e300)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-049e300.deb) is ready for download.
[macOS build 1.1.0 (049e300)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-049e300.dmg) is ready for download.
[Windows x64 build 1.1.0 (049e300)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-049e300.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (049e300)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-049e300.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (260a122)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-linux-x64-1.1.0-260a122.deb) is ready for download.
[macOS build 1.1.0 (260a122)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-macos-x64-1.1.0-260a122.dmg) is ready for download.
[Windows x64 build 1.1.0 (260a122)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x64-1.1.0-260a122.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (260a122)](https://tc-builds.door43.org/build/feature-mannycolon-5234/translationCore-win-x32-1.1.0-260a122.setup.exe) is ready for download.

**Pull request closed without merging**
