### PR TITLE
tW Invalidation Loading At Project Load fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR fixes tW invalidations not showing up for external edits

#### Please include detailed Test instructions for your pull request:
- Checkout branch `bugfix-jay-5686-2` on tW
- Open any project and make a selection (Not the word and verse you select)
- Export the project to USFM not including the alignment data
- Make edits to the USFM file that wil break the selections.
- Import the USFM file giving it the same translation ID as the original, and choose the Overwrite options
- When the project opens you should see the broken link on the tool card from the verse you invalidated.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5822)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (793aecf)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-linux-x64-1.2.0-793aecf.deb) is ready for download.
[macOS build 1.2.0 (793aecf)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-macos-x64-1.2.0-793aecf.dmg) is ready for download.
[Windows x64 build 1.2.0 (793aecf)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x64-1.2.0-793aecf.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (793aecf)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x32-1.2.0-793aecf.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-linux-x64-1.2.0-ea825c0.deb) is ready for download.
[macOS build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-macos-x64-1.2.0-ea825c0.dmg) is ready for download.
[Windows x64 build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x64-1.2.0-ea825c0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x32-1.2.0-ea825c0.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5822#-:-LZGmVKD-8uA119JpKL9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]
Local testing: Pending

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5822#-:-LZGmYHp61ss4zAdypL-:b-9zfdhh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-linux-x64-1.2.0-ea825c0.deb) is ready for download.
[macOS build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-macos-x64-1.2.0-ea825c0.dmg) is ready for download.
[Windows x64 build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x64-1.2.0-ea825c0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (ea825c0)](https://tc-builds.door43.org/build/bugfix-jay-5686-2/translationCore-win-x32-1.2.0-ea825c0.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Pending https://github.com/translationcoreapps/translationwords/pull/249

**Pull request merged**
