### PR TITLE
Load entire book data

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/4658
- Updates the bible loading to load the full book data when the context changes instead of just the chapter.

#### Please include detailed Test instructions for your pull request:

Needed for https://github.com/translationCoreApps/wordAlignment/pull/47

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4664)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6725d16)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6725d16.zip) is ready for download.
[macOS build 0.10.0 (6725d16)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6725d16.dmg) is ready for download.
[Windows x64 build 0.10.0 (6725d16)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6725d16.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6725d16)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6725d16.setup.exe) is ready for download.

**Comment by jag3773** [comment]
@neutrinog is this for the whole *Bible*  (would be like #4659 ) or just the current project (1 book of the Bible)?

**Comment by da1nerd** [comment]
ah... one book :P I suppose the title was miss-leading.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (e52e8d0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-e52e8d0.zip) is ready for download.
[macOS build 0.10.0 (e52e8d0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-e52e8d0.dmg) is ready for download.
[Windows x64 build 0.10.0 (e52e8d0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-e52e8d0.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (e52e8d0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-e52e8d0.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Reviewed 3 of 5 files at r1, 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4664)*

**Comment by mannycolon** [comment]
Code Review `LGTM`
Local Test `PENDING BUG REPORTED ON https://github.com/translationCoreApps/wordAlignment/pull/47`

**Comment by mannycolon** [comment]
@neutrinog Don't forget to merge w/ latest develop branch

**Comment by richmahn** [comment]
@neutrinog Where are we in getting this in with the bug Manny reported? Waiting fo this PR to be merged before merging the one I reviewed that is related to this.

**Review by mannycolon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4664)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
