### PR TITLE
Add VerseCheck

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request adds VerseCheck to the repo. It also removes CommentBox and ProposedChanges.

#### How to test this pull request:

Initalize the VerseCheck submodule, and be sure that tN and tW are on the latest versions of develop. Also, a PR is pending on tW for this to work with that tool. Open each tool, make sure that that does not fail, and then make sure the versecheck tool is there.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/931)

### CODE REVIEW

**Comment by ihoegen** [comment]
Also, sorry for adding submodules, that was unintentional

**Comment by EllDoubleYew** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tC_apps/ScripturePane, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/931#-KflQ2qBy02pgZUaR0yM:-KflQ2qCAzCLRWieoXdi:b-h7fthx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fea4b420ec6256018c710863b63a64070b736a9e/tC_apps/ScripturePane#L1)):*
> ```
> Subproject commit d83ad7a80f96abd38ab58a094e7f2a2902f18e04
> ```

Could we please take out these tool commits?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/931)*

**Comment by EllDoubleYew** [comment]
@ihoegen all good, could we take them out please 😄 then we should be good to merge

**Comment by ihoegen** [comment]
@EllDoubleYew ScripturePane commit is out, ready to merge

**Comment by mannycolon** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/931)*

**Pull request merged**
