### PR TITLE
Feature 3086/show invalidated selection

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- on verse edit, sets invalidation flag on any selections that are not longer valid in verse.
- on new selection, clears the invalidation flag for that selection
- on tw startup, verify all selections to make sure they are still valid.

#### Please include detailed Test instructions for your pull request:
- test with https://github.com/translationCoreApps/VerseCheck/pull/102
- Open new Titus project in tw:  Test with both VerseCheck editor and ScripturePane editor
- Make sure that edits test all selections in a verse. Do the following steps with both verse check editor and scripture pane editor:
  - [ ] make selection for an apostle and save
  - [ ] make selection for god (1:1 first) and save
  - [ ] verify that you see check mark for first God and for apostle
  - [ ] click left menu apostle
  - [ ] edit verse, change selected words by inserting letters to make 'apos2tle' and 'Go2d'.  Click save.
  - [ ] verify that you see invalided mark (broken link) for first God and for apostle
- test that states persist
  - [ ] exit tw tool and open again
  - [ ] verify that you see invalided (broken link) and edited (pencil when you hover) marks for first God and for apostle
- verify that selections clear invalidated:
  - [ ] edit Titus 1:1, restore selected words to 'apostle' and 'God'.  Click save
  - [ ] verify that you see invalided mark (broken link) for first God and for apostle
  - [ ] make another selection for an apostle
  - [ ] verify that invalided mark is removed for apostle, and you should see check and edit marks
- Make sure selection still works in WA:
  - Open Titus project in tw:  
    - [ ] make selection for an apostle and save
    - [ ] make selection for god (1:1 first) and save
  - change to wa tool:  
    - [ ] open Scripture Pane editor, edit Titus 1:1 change selected words by inserting letters to make 'apos2tle' and 'Go2d'.  save. 
  - Open project in tw and should see warning that selections have been invalidated.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4283)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@PhotoNomad0 Should there be invalidated checks in the tools page as well?

**Comment by RoyalSix** [comment]
Local Testing: 
 - Everything looks good besides one bug, that I cannot reproduce on develop so it might be from this branch
- I tried making an alignment, then went to tW and changed the same verse (invalidating the alignment), then I go back to wA and it shows errors
screen shot 2018-04-20 at 1 23 02 pm
screen shot 2018-04-20 at 1 21 40 pm
Code Review: Few comments
 
image

**Comment by RoyalSix** [comment]
Reviewed 3 of 20 files at r2.
Review status: 3 of 28 files reviewed at latest revision, all discussions resolved.

---

*[__tests__/InvalidatedActions.test.js, line 133 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283#-LAZoV0P1J-U3lBmlUzM:-LAZoV0P1J-U3lBmlUzN:b-kxap7i) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8e4fad690f6622819dde3144fc4c0bfc719647c1/__tests__/InvalidatedActions.test.js#L133)):*
> ```JavaScript
>     const actions = store.getActions();
>     expect(actions.length).toEqual(2);
>     expect(actions[1]).toEqual(expectedActions);
> ```

Just wondering, what is the reasoning for only testing the second action?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 16 files at r1, 10 of 20 files at r2.
Review status: 15 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/actions/SelectionsActions.js, line 177 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283#-LAZusEB3OFW-SxSUWvV:-LAZusEB3OFW-SxSUWvW:b1r0k70) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8e4fad690f6622819dde3144fc4c0bfc719647c1/src/js/actions/SelectionsActions.js#L177)):*
> ```JavaScript
>  * @param {Object} state
>  * @return {String | undefined}
>  */
> ```

This looks like a selector. Would it better fit in `src/js/selectors` ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283)*

**Comment by RoyalSix** [comment]
Reviewed 6 of 16 files at r1, 7 of 20 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283)*

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0

 Should there be invalidated checks in the tools page as well?

Perhaps, but that would be scope creep.  Need a new issue written.

**Comment by PhotoNomad0** [comment]
Review status: 26 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[__tests__/InvalidatedActions.test.js, line 133 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283#-LAZoV0P1J-U3lBmlUzM:-LAnTLCe5vLEPO8RUQtq:bwp6drb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8e4fad690f6622819dde3144fc4c0bfc719647c1/__tests__/InvalidatedActions.test.js#L133)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Just wondering, what is the reasoning for only testing the second action?
</blockquote></details>

Was only wanting to check the setInvalidated, but that's not necessary. Changed to do snapshot.

---

*[src/js/actions/SelectionsActions.js, line 177 at r2](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283#-LAZusEB3OFW-SxSUWvV:-LAnVxCm5bl6Iv43ExrX:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8e4fad690f6622819dde3144fc4c0bfc719647c1/src/js/actions/SelectionsActions.js#L177)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This looks like a selector. Would it better fit in `src/js/selectors` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/unfoldingword-dev/translationcore/4283)*

**Comment by PhotoNomad0** [comment]
> Local Testing:
> 
> Everything looks good besides one bug, that I cannot reproduce on develop so it might be from this branch
> I tried making an alignment, then went to tW and changed the same verse (invalidating the alignment), then I go back to wA and it shows errors
> screen shot 2018-04-20 at 1 23 02 pm

@RoyalSix - I see the first error in the sandbox-v10 branch before I even open a tool.

**Comment by PhotoNomad0** [comment]
@RoyalSix - On the second error, I will need some more detail to reproduce:

It looks like the error is in the ScripturePane Pane() component (lines below).  Don't know how contextId.reference would be null, but looking.

```
class Pane extends React.Component {
  render() {
    let { translate, actions, contextIdReducer, selectionsReducer, removePane, index, bibleId, languageId, resourcesReducer } = this.props;
    const {bibles} = resourcesReducer;
    let { reference } = contextIdReducer.contextId;
```

**Comment by RoyalSix** [comment]
I actually missed that you used `sandbox-0.10` as a base branch! I will test again

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 8 of 16 files at r1, 11 of 20 files at r2, 3 of 4 files at r3, 4 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4283#-:-LArqIS2CXGlJSfctXuu:bnfp4nl)*

**Pull request merged**
