### PR TITLE
Feature - #3559 - Reimport and full-project invalidation check

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Addresses #3559, reimport and project invalidation check for translationWord and other checkData tools.

#### Please include detailed Test instructions for your pull request:
-  Import a project in tC
- Make some alignments and checks
 - Export your project to both usfm2 and usfm3
- Make some changes to those usfm2 and usfm3 files that would affect your alignment/checks
- Go to the context menu of your project and choose "Reimport Project" (same as choosing Local Import from the FAB)
- Import your project with the correct settings to match your project before (keep in mind you are actually doing a new import and it won't know you are reimporting until it sees your import's directory is the same as an existing project, per the chart in #3559 )
- Once reimported, make sure your checks are still there, but the ones that were changed due to text changed are marked as invalidated. Usfm2 import should keep Alignment checks, but Usfm3 imports should invalidated any alignments that have a text change

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4562)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (d73a2f9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-d73a2f9.zip) is ready for download.
[macOS build 0.10.0 (d73a2f9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-d73a2f9.dmg) is ready for download.
[Windows x64 build 0.10.0 (d73a2f9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-d73a2f9.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (d73a2f9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-d73a2f9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (276cbca)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-276cbca.zip) is ready for download.
[macOS build 0.10.0 (276cbca)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-276cbca.dmg) is ready for download.
[Windows x64 build 0.10.0 (276cbca)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-276cbca.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (276cbca)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-276cbca.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@richmahn - if I make an alignment change to the usfm3 file (aligned 1:6 and moved husband into group with wife), reimport doesn't change the alignment

**Comment by PhotoNomad0** [comment]
My USFM3 file and my project:

[ab_tit3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2106045/ab_tit3.usfm.zip)

[ab_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2106047/ab_ult_tit_book.zip)

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (23adf11)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-23adf11.zip) is ready for download.
[macOS build 0.10.0 (23adf11)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-23adf11.dmg) is ready for download.
[Windows x64 build 0.10.0 (23adf11)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-23adf11.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (23adf11)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-23adf11.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-ec39fb9.zip) is ready for download.
[macOS build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-ec39fb9.dmg) is ready for download.
[Windows x64 build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-ec39fb9.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-ec39fb9.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
Reviewed 14 of 22 files at r1, 9 of 15 files at r2, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4562)*

**Comment by PhotoNomad0** [comment]
@richmahn - missing Hindi translation key for reimport option.

**Comment by PhotoNomad0** [comment]
@richmahn - if I do a USFM3 reimport, it overwrites the verse text as well as the alignments.  Is this expected?

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-ec39fb9.zip) is ready for download.
[macOS build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-ec39fb9.dmg) is ready for download.
[Windows x64 build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-ec39fb9.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (ec39fb9)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-ec39fb9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (de45089)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-de45089.zip) is ready for download.
[macOS build 0.10.0 (de45089)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-de45089.dmg) is ready for download.
[Windows x64 build 0.10.0 (de45089)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-de45089.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (de45089)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-de45089.setup.exe) is ready for download.

**Comment by richmahn** [comment]
@PhotoNomad0 This is per-verse/per-alignment. If there are any alignments for the given verse in the new USFM3, it will replace the alignment for the verse. Otherwise, it should keep the verse. Have you seen existing ones that aren't in the USFM3 being removed?

**Comment by mannycolon** [comment]
@richmahn Hey don't forget to merge with latest develop branch

**Review by PhotoNomad0 — COMMENTED** [review]
> Reviewed 133 of 133 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4562)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
