### PR TITLE
bugFix #3920/Fix for Typo in UGNT data

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- migrates projects and converts “ἐgκρατῆ” to “ἐνκρατῆ” in project alignment and tWords data.

#### Please include detailed Test instructions for your pull request:
- depends on https://github.com/translationCoreApps/tC_Resources/pull/25

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3969)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@PhotoNomad0 merge conflicts

**Comment by RoyalSix** [comment]
@PhotoNomad0 merge conflicts

**Comment by mannycolon** [comment]
Reviewed 62 of 64 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3969)*

**Comment by mannycolon** [comment]
Code: LGTM
Local Test: Pending 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3969#-:-L6rqbbjwhIXkyFtq5-F:bedbdys)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Merge latest develop branch into this branch

**Comment by mannycolon** [comment]
`Local Test: LGTM`

**Comment by richmahn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3969#-:-L6sIlpzfkg53XqyCoAD:bnfp4nl)*

**Comment by richmahn** [comment]
Reviewed 62 of 64 files at r1, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3969)*

**Pull request merged**
