### PR TITLE
Feature bspidel 4328

### PR DESCRIPTION
**Pull request by bspidel**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Issue 4328 ensures that import folder is empty before attempting to import a project

#### Please include detailed Test instructions for your pull request:
- with windows explorer clear import folder
- clear project from projects folder
- online import  abu_tit  but...
- kill spp at "Missing verses" This leaves project in import folder
- clear project (leave import)
- restart app
- online import  abu_tit
- before it would complain about already imported
- Now it proceeds normally

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[package.json, line 72 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUp3vM4oQRmCDHQeEZ:-LEUp3vM4oQRmCDHQeE_:bbeppw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/package.json#L72)):*
> ```JSON
>     "electron-packager": "9.1.0",
>     "electron-prebuilt-compile": "1.6.11",
>     "electron-react-devtools": "^0.5.3",
> ```

why is this changed?

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 42 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUnHDG2xX_BKmaCCoB:-LEUnHDG2xX_BKmaCCoC:b-6g76c2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/OnlineImportWorkflowActions.js#L42)):*
> ```JavaScript
> 
> //await delay(10000);
> //dispatch(clearLink());
> ```

Should probably remove these commented commands

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 22 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUoUR35hrBD82DeCd4:-LEUoUR35hrBD82DeCd5:b249rpx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L22)):*
> ```JavaScript
>       return reject("Project has already been imported.");
>     } catch(e) {
>       fs.ensureDirSync(savePath);
> ```

This doesn't seem like a good approach to use exceptions to detect presence of folder.  And It seems that the original code is better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 48 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUpTud703FW-zJULwa:-LEUpTud703FW-zJULwb:bzcbtu5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/ProjectImportFilesystemActions.js#L48)):*
> ```JavaScript
>         const tempDir = path.join( process.cwd(), "oldDir");
>         fs.renameSync(projectImportsLocation, tempDir);
>         fs.remove(tempDir);
> ```

seems that it would be simpler to do a removeSync rather than making this whole function a promise.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 44 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUqel_6akPbFAeLbd6:-LEUqel_6akPbFAeLbd7:bjqxxu1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/LocalImportWorkflowActions.js#L44)):*
> ```JavaScript
>     const importProjectPath = path.join(IMPORTS_PATH, selectedProjectFilename);
> 
>     await dispatch(ProjectImportFilesystemActions.deleteProjectFromImportsFolder());
> ```

Missing a parameter here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by bspidel** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[package.json, line 72 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUp3vM4oQRmCDHQeEZ:-LEUvT2ABjmfpj_Vvrav:b9tcmor) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/package.json#L72)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

why is this changed?
</blockquote></details>

I have no idea. Sometimes I get merge conflicts in files I don't change. Try to respond best I can. Normally i accept new changes.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 44 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUqel_6akPbFAeLbd6:-LEUyu5W3gl1KgUVJZo_:b-vwxc2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/LocalImportWorkflowActions.js#L44)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Missing a parameter here.
</blockquote></details>

How about another hint. I did not intend to make any change here. VS code does not show a problem.

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 42 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUnHDG2xX_BKmaCCoB:-LEUw8Iu7M1t8wDZdyVv:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/OnlineImportWorkflowActions.js#L42)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Should probably remove these commented commands
</blockquote></details>

Done.

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 48 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUpTud703FW-zJULwa:-LEUx7FBBQC3CBb58BzE:bom3a68) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/ProjectImportFilesystemActions.js#L48)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

seems that it would be simpler to do a removeSync rather than making this whole function a promise.
</blockquote></details>

I was advised to make function a promise so that caller would wait. Don't care about actual remove completion, only that rename happens before caller continues.

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 22 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUoUR35hrBD82DeCd4:-LEUxccJ2J_fFmsvfaMm:b-t4pk6u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L22)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This doesn't seem like a good approach to use exceptions to detect presence of folder.  And It seems that the original code is better.
</blockquote></details>

Original code did not work. StatSync throws an error if file does not exist. That is what I was looking for.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/js/actions/Import/LocalImportWorkflowActions.js, line 44 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUqel_6akPbFAeLbd6:-LEVMAxU0t9gCOiaXx1J:bp75t4h) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/LocalImportWorkflowActions.js#L44)):*
<details><summary><i>Previously, bspidel (Bruce Spidel) wrote…</i></summary><blockquote>

How about another hint. I did not intend to make any change here. VS code does not show a problem.
</blockquote></details>

looks like you should pass importProjectPath as parameter to deleteProjectFromImportsFolder() 

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 22 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUoUR35hrBD82DeCd4:-LEVMnSU1yQzhLw9zan3:b-dx71kg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L22)):*
<details><summary><i>Previously, bspidel (Bruce Spidel) wrote…</i></summary><blockquote>

Original code did not work. StatSync throws an error if file does not exist. That is what I was looking for.
</blockquote></details>

The original code called fs.existsSync(savePath)) which seems preferred.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 6 unresolved discussions (waiting on @PhotoNomad0 and @bspidel)

---

*[package.json, line 72 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUp3vM4oQRmCDHQeEZ:-LEmB_aC8XJzeutW4jcE:b-w89bca) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/package.json#L72)):*
<details><summary><i>Previously, bspidel (Bruce Spidel) wrote…</i></summary><blockquote>

I have no idea. Sometimes I get merge conflicts in files I don't change. Try to respond best I can. Normally i accept new changes.
</blockquote></details>

Hey please remove the carrot from "electron-react-devtools": "^0.5.3",

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 42 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUnHDG2xX_BKmaCCoB:-LEmBkC8BojZ8Zm37zpa:borp7vm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/OnlineImportWorkflowActions.js#L42)):*
<details><summary><i>Previously, bspidel (Bruce Spidel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done yet? did you push your changes?

---

*[src/js/actions/Import/OnlineImportWorkflowActions.js, line 81 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEmCJi60In86oCUoXzp:-LEmCJi60In86oCUoXzq:b830zlc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/actions/Import/OnlineImportWorkflowActions.js#L81)):*
> ```JavaScript
> /**
>  * @description - delete project (for link) from import folder
>  */
> ```

Please move up the promise as follow


export const deleteImportProjectForLink = () => {
  return (dispatch, getState) => {
     return new Promise(async (resolve) => {
            try {
          ----code goes here---
            } catch (err) {
         ----code goes here---
            }
      })
   };
}

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 22 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUoUR35hrBD82DeCd4:-LEmDO3Z0JN9h19oEPPg:b-cstnkg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L22)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

The original code called fs.existsSync(savePath)) which seems preferred.
</blockquote></details>

I agree

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 5 files at r2.
Review status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @PhotoNomad0 and @bspidel)

---

*[manifest.json, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFIecIi3DdNodOKPibF:-LFIecIi3DdNodOKPibG:b6qeoc2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/manifest.json#L1)):*
> ```JSON
> {"project":{}}
> ```

This should not be committed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by PhotoNomad0** [comment]
Review status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @PhotoNomad0, @mannycolon, and @bspidel)

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 37 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFIqLig1hSZbQ9uhJP7:-LFIqLig1hSZbQ9uhJP8:b-txq9mi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/src/js/actions/Import/ProjectImportFilesystemActions.js#L37)):*
> ```JavaScript
> /**
>  * Deletes  the imports folder. Since there had been a race condition,
>  * It now renames the "to be deleted folder" then deletes it so that async functions
> ```

update comments

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by mannycolon** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed, 7 unresolved discussions (waiting on @bspidel and @PhotoNomad0)

---

*[manifest.json, line 1 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFIecIi3DdNodOKPibF:-LFZJXIp40ftUteZjyHn:b5vn95p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/manifest.json#L1)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

This should not be committed.
</blockquote></details>

Yes, delete this file. It seems like you have not merged with the latest develop branch for a while. Please do so. 

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 11 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFZK-x6EK_nExzcRAr_:-LFZK-x6EK_nExzcRAra:b-ys2tg) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/src/js/actions/Import/ProjectImportFilesystemActions.js#L11)):*
> ```JavaScript
> // constants
> const IMPORTS_PATH = path.join(ospath.home(), 'translationCore', 'imports');
> const TEMP_DIR = path.join( process.cwd(), "oldDir");
> ```

what is temp_dir needed for ?

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 43 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFZK4CU2U3GkYJ74qeV:-LFZK4CU2U3GkYJ74qeW:bgl9m4u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/src/js/actions/Import/ProjectImportFilesystemActions.js#L43)):*
> ```JavaScript
>   return new Promise( async(resolve) => {
>     try {
>       if (fs.statSync(IMPORTS_PATH)) {   
> ```

why not keep using fs.existsSync()  instead fs.statSync(IMPORTS_PATH)?

---

*[src/js/actions/Import/ProjectImportFilesystemActions.js, line 44 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LFZKBtDCEW-NECE1Rny:-LFZKBtDCEW-NECE1Rnz:b-zigoyn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eeb27fb3061c0852917adae6ea639d1287372541/src/js/actions/Import/ProjectImportFilesystemActions.js#L44)):*
> ```JavaScript
>     try {
>       if (fs.statSync(IMPORTS_PATH)) {   
>         fs.renameSync(IMPORTS_PATH, TEMP_DIR);
> ```

Why do you have to rename it before removing it ?

---

*[src/js/helpers/Import/OnlineImportWorkflowHelpers.js, line 22 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576#-LEUoUR35hrBD82DeCd4:-LFZKG2Y6ZnfGfPF9Mwv:b32wed) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/c09abad7a9fc6358b78759f00e360779cff2f766/src/js/helpers/Import/OnlineImportWorkflowHelpers.js#L22)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I agree
</blockquote></details>

^^

---


*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4576)*

**Comment by mannycolon** [comment]
Merge w/ latest develop branch

**Pull request closed without merging**
