### PR TITLE
create function to copy bibles from static folder to local user folder

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Finished creating the function to move bibles files to user root folder for tC.
- still need to find an appropriate place in the codebase where to call this function.
- pending approval from @RoyalSix  and @klappy about copying all bible files instead of just one bible for a project selected.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1864)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix  @klappy

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1864)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1864#-:-Kn-3s-p3Ic4ORQRTwSn:bnfp4nl)*

**Comment by klappy** [comment]
Looks good.  It looks like you are copying all books of all the bibles all here in this commit.

From your question in a commit message about approval on copying all books of the bible. I feel that it copying them all like you already are makes the most sense. 

In theory this could be done on somewhere in the app level of translationCore before loading a project. Like when the application loads, it checks to see if the resources are there, and if they aren't it shows the loading screen and tells the user that it is copying the required resources over. That way we can cleanly add another function in for copying the other resources.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1864#-:-Kn-B9jC9G9D-2wIouXU:bjdxskm)*

**Pull request merged**
