### PR TITLE
Auto Assign CC-BY-SA License to door 43 Projects

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR addresses a feature that got removed during the refactor

#### How to test this pull request:
Open any project from door43 online and ensure that after importing the manifest has the field ```"license": "CC BY-SA 4.0"``` and that the license portion of the import stepper did not show.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3423)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1, 381 of 381 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3423)*

**Comment by mannycolon** [comment]
@RoyalSix When importing a duplicate project from door43 (a project that was previously imported in tC and is currently in the projects folder)

- The project overwrites the previous project
- The project folder only has the manifest.json file.

**Comment by PhotoNomad0** [comment]
Very confused about the 384 changed files here.  Temp files?   Should the checkdata folder be added to .gitignore?

**Comment by klappy** [comment]
Don't we delete that folder in a migration?
The `checkdata` folder is legacy, and by adding it to the .gitignore, it might get left in there instead of cleaning it up on subsequent commits.
Should we commit the removal of it and then add it to .gitignore?

**Comment by RoyalSix** [comment]
@mannycolon Is that related to auto assigning a door43 license?

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 3 files at r1, 3 of 381 files at r2, 3 of 380 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3423)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3423#-:-L0illSlVWlkkVLv0PuT:bnfp4nl)*

**Comment by richmahn** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3423#-:-L0jTc4EUyhZUmlaGQTx:bnfp4nl)*

**Comment by richmahn** [comment]
Reviewed 1 of 3 files at r1, 3 of 381 files at r2, 3 of 380 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3423)*

**Pull request merged**
