### PR TITLE
Bugfix mcleanb 5356/fix for complex USFM in header 

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- fix whitespace on USFM2 export
- updated usfm-js module

#### Please include detailed Test instructions for your pull request:
- set up:
- do `rm -rf node_modules`
- `npm ci`
- `npm run load-apps`
- use test file in #5356 
- input and USFM2 export file should match except for date.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5362)

### CODE REVIEW

**Comment by richmahn** [comment]
Not matching for me. Getting double tag endings now. For example:

```
1c1
< \id TIT EN_HTST en_English_ltr Wed Oct 31 2018 13:59:58 GMT-0500 (CDT) tc
---
> \id TIT EN_TEST en_English_ltr Fri Nov 02 2018 17:39:07 GMT-0600 (MDT) tc
28c28
< \em Translation it is that opens the window, to let in the light; that breaks the shell,\em*
---
> \em Translation it is that opens the window, to let in the light; that breaks the shell,\em*\em*
34,35c34,35
< \bk King James Version\bk*
< \bk* of the Bible...
---
> \bk King James Version\bk*\bk*
> \bk * of the Bible...\bk*
52c52
< \w miracle\w*
---
> \w miracle\w*\w*
```

**Comment by richmahn** [comment]
Here are the two files, before and after import/export:

[head_test.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/2544443/head_test.usfm.txt)
[head_test2.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/2544444/head_test2.usfm.txt)

**Comment by PhotoNomad0** [comment]
Yes, needed to clean out old usfm-js versions from package-lock. added to test steps.

**Review by richmahn — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5362)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0)

**Comment by richmahn** [comment]
:lgtm:

**Pull request merged**
