### PR TITLE
Windows Installation Improvements

### PR DESCRIPTION
**Pull request by da1nerd**
#### This pull request addresses:

This adds a nicer splash image when installing tC.

#### How to test this pull request:

Make sure all the tests pass, then try out a windows build.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2886)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2886)*

**Comment by RoyalSix** [comment]
@neutrinog I can test this tonight on my windows machine

**Comment by klappy** [comment]
@neutrinog: Looks good, I'll have to have somebody else test the Windows part. Did this add yarn support or a remnant from your local machine?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2886#-:-KwBOiwX5t9nS3CtTmV8:b-ll60qg)*

**Comment by klappy** [comment]
Reviewed 3 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2886)*

**Comment by da1nerd** [comment]
oops yeah I might have run yarn out of habit :P we can delete the yarn lock

**Pull request merged**
