### PR TITLE
Fixed missing text warning not displayed in scripture pane

### PR DESCRIPTION
**Pull request by mannycolon**
I will update tc-ui-toolkit after [tc-ui-toolkit PR 86](https://github.com/translationCoreApps/tc-ui-toolkit/pull/86 is merged) is merged

#### Please include detailed Test instructions for your pull request:
- Run `npm i translationCoreApps/tc-ui-toolkit#bugfix-mannycolon-5266 `
- Open [es-419_reg_luk_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2490175/es-419_reg_luk_book.zip) w/ tW tool
- Go to Luke 1:2 on `word of God, words of God, word of Yahweh, word of the Lord, word of truth, scripture, scriptures` check
- The following warning should show
image

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327)

### CODE REVIEW

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[package.json, line 177 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327#-LPlYYEE-YAay7D0soCS:-LPlYYEE-YAay7D0soCT:b-8ldeky) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/37a06ec2bd66c104a58b321faedf3fedc0e59131/package.json#L177)):*
> ```JSON
>     "tc-strings": "0.1.7",
>     "tc-tool": "^2.0.0-rc.1",
>     "tc-ui-toolkit": "^0.11.4",
> ```

Could you remove the ^, it causes us so much trouble picking up newer versions too soon.

**Comment by PhotoNomad0** [comment]
Works well, just suggest one change before merge.

**Review by mannycolon — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327)* status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

___
*[package.json, line 177 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327#-LPlYYEE-YAay7D0soCS:-LPlc6FK5A9s5Csd8ij1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/37a06ec2bd66c104a58b321faedf3fedc0e59131/package.json#L177)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Could you remove the ^, it causes us so much trouble picking up newer versions too soon.
</blockquote></details>

Done.

**Review by PhotoNomad0 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5327)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
