### PR TITLE
Add Group Name to CSV Export

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds a new field to the csv export by accessing the groupIndex object and populating the the field with the corresponding id.

#### How to test this pull request:
Try exporting a few projects, and look or weird or inconsistent rows. Also make sure that the field groupName is there.
** note some groupNames are not indexed our resources **

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2140)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 368 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgBPilWVaeCaKa_jI:-KorgBPilWVaeCaKa_jJ:b-s3pooc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L368)):*
> ```JavaScript
>  */
> export function addContextIdToCSV(currentRowArray, contextId, username, datetime, indexObject) {
>   if (contextId.groupId == 'astray') debugger;
> ```

Should this debugger still be in here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 338 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgTsaLnHVfeJWEp-P:-KorgTsaLnHVfeJWEp-Q:b-unyvb9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L338)):*
> ```JavaScript
>  * @param {string} dataFolder - folder to save to filesystem
>  */
> export function saveGroupsCSVToFs(obj, dataFolder, currentToolName, indexObject) {
> ```

Can you update the comments for these params, I'm not sure what I would pass in for indexObject.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 367 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgeOgLowX_GhGUelr:-KorgeOgLowX_GhGUels:br1zyt9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L367)):*
> ```JavaScript
>  * @param {object} contextId - contextID object that needs to go onto the csv row
>  */
> export function addContextIdToCSV(currentRowArray, contextId, username, datetime, indexObject) {
> ```

can you update the documentation here as well? a lot of params have been added since the comments were written.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/utils/loadMethods.js, line 120 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgpqTKfLO9EmhP5IP:-KorgpqUeDYBOvDvV0Dt:bm8455e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/utils/loadMethods.js#L120)):*
> ```JavaScript
> }
> 
> export function getGroupName(indexObject, contextId) {
> ```

Can you add comments/documentation for this function? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 311 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korgz3_MT2X7-v-HF3F:-Korgz3_MT2X7-v-HF3G:bjan8qn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L311)):*
> ```JavaScript
>  * @param {string} dataFolder - folder to save to filesystem
>  */
> export function saveRemindersToCSV(obj, dataFolder, currentToolName, indexObject) {
> ```

Documentation needs updated here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 280 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh3-Zta5wv629Llop:-Korh3-_UGhV0ihSgovc:bjan8qn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L280)):*
> ```JavaScript
>  * @param {string} dataFolder - folder to save to filesystem
>  */
> export function saveSelectionsToCSV(obj, dataFolder, currentToolName, indexObject) {
> ```

Documentation needs updated here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 253 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh4_L4Xvwj04_zUHr:-Korh4_L4Xvwj04_zUHs:bjan8qn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L253)):*
> ```JavaScript
>  * @param {string} dataFolder - folder to save to filesystem
>  */
> export function saveCommentsToCSV(obj, dataFolder, currentToolName, indexObject) {
> ```

Documentation needs updated here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/actions/RecentProjectsActions.js, line 224 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh6PuMVdAekFtUio9:-Korh6PuMVdAekFtUioA:bjan8qn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L224)):*
> ```JavaScript
>  * @param {string} dataFolder - folder to save to filesystem
>  */
> export function saveVerseEditsToCSV(obj, dataFolder, currentToolName, indexObject) {
> ```

Documentation needs updated here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by RoyalSix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/js/actions/RecentProjectsActions.js, line 224 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh6PuMVdAekFtUio9:-KorwNd5hDmQOJKmqgs1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L224)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Documentation needs updated here as well
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 253 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh4_L4Xvwj04_zUHr:-KorwOfP4lHpQ5xtKqUw:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L253)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Documentation needs updated here as well
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 280 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korh3-Zta5wv629Llop:-KorwPVLC6_wnce_gqry:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L280)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Documentation needs updated here as well
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 311 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-Korgz3_MT2X7-v-HF3F:-KorwPqil0byH4uJ5TkP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L311)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Documentation needs updated here as well
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 338 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgTsaLnHVfeJWEp-P:-KorwQOuq9RsL96TUuEg:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L338)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you update the comments for these params, I'm not sure what I would pass in for indexObject.
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 367 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgeOgLowX_GhGUelr:-KorwSi75W1s9__aD7Xz:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L367)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

can you update the documentation here as well? a lot of params have been added since the comments were written.
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 368 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgBPilWVaeCaKa_jI:-KorxD7ExGpk48ZxJbAn:bwtcsyp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/actions/RecentProjectsActions.js#L368)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should this debugger still be in here?
</blockquote></details>

No. thanks

---

*[src/js/utils/loadMethods.js, line 120 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgpqTKfLO9EmhP5IP:-KorynYovFQs7uJmzLv_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/utils/loadMethods.js#L120)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Can you add comments/documentation for this function? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/utils/loadMethods.js, line 120 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgpqTKfLO9EmhP5IP:-KosIf7Rytc2g6775LuC:b92uv9y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/utils/loadMethods.js#L120)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The params say contextId but the param is groupId and I don't think that's an object either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
*[src/js/utils/loadMethods.js, line 120 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-KorgpqTKfLO9EmhP5IP:-KosN7_QDhtc0HBLvMDi:b32w0x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/8a2c6883789ece6fa45faf1b53a4f8deab9c4dce/src/js/utils/loadMethods.js#L120)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The params say contextId but the param is groupId and I don't think that's an object either.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-:-KosNFIBg-x-UCGy66Ct:bnfp4nl)*

**Comment by klappy** [comment]
Wait, did you forget to commit and push a file? import * as CSVExportActions from './CSVExportActions';
That file doesn't exist.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140#-:-KosOXyAyucomx4uqe11:bbq1wlz)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2140)*

**Comment by klappy** [comment]
Eventually, we need to replace manual CSV generation with a library that will handle issues we are bound to face.

**Pull request merged**
