### PR TITLE
TSV parser now generating word occurrence number to original quote words

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
- Delete your English tN folder from your resources 
- Open the source content updater and download the latest English resource update
- Open tN
- Verify that all quotes highlighted on the scripture pane for the UGNT match the quotes found in the following TSV files for Titus and Jude projects. (Or book projects of your choice)
[en_tn_57-TIT.tsv.zip](https://github.com/unfoldingWord-dev/translationCore/files/3268233/en_tn_57-TIT.tsv.zip)
[en_tn_66-JUD.tsv.zip](https://github.com/unfoldingWord-dev/translationCore/files/3268234/en_tn_66-JUD.tsv.zip)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6107)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (fcf4801)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-fcf4801.deb) is ready for download.
[macOS build 1.2.0 (fcf4801)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-fcf4801.dmg) is ready for download.
[Windows x64 build 1.2.0 (fcf4801)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-fcf4801.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (fcf4801)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-fcf4801.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (9fc4dbb)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-9fc4dbb.deb) is ready for download.
[macOS build 1.2.0 (9fc4dbb)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-9fc4dbb.dmg) is ready for download.
[Windows x64 build 1.2.0 (9fc4dbb)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-9fc4dbb.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (9fc4dbb)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-9fc4dbb.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (7087430)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-7087430.deb) is ready for download.
[macOS build 1.2.0 (7087430)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-7087430.dmg) is ready for download.
[Windows x64 build 1.2.0 (7087430)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-7087430.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (7087430)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-7087430.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (f1c2ce8)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-f1c2ce8.deb) is ready for download.
[macOS build 1.2.0 (f1c2ce8)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-f1c2ce8.dmg) is ready for download.
[Windows x64 build 1.2.0 (f1c2ce8)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-f1c2ce8.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (f1c2ce8)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-f1c2ce8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (dcf8bd0)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-dcf8bd0.deb) is ready for download.
[macOS build 1.2.0 (dcf8bd0)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-dcf8bd0.dmg) is ready for download.
[Windows x64 build 1.2.0 (dcf8bd0)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-dcf8bd0.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (dcf8bd0)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-dcf8bd0.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.2.0 (7ded2ad)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-linux-x64-1.2.0-7ded2ad.deb) is ready for download.
[macOS build 1.2.0 (7ded2ad)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-macos-x64-1.2.0-7ded2ad.dmg) is ready for download.
[Windows x64 build 1.2.0 (7ded2ad)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x64-1.2.0-7ded2ad.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (7ded2ad)](https://tc-builds.door43.org/build/bugfix-mannycolon-5982/translationCore-win-x32-1.2.0-7ded2ad.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 25 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6107#-:-Lh10I1LCsO2sI2lqWyY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0 and @RoyalSix)

**Comment by richmahn** [comment]
All looks good in the scripture pane!

**Pull request merged**
