### PR TITLE
Percentage Complete For Word Alignment Tool

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds support for finding how much a user has done in the word alignment tool and displaying it in the home page and the tool page.
Percentage based on number of words aligned;

#### How to test this pull request:
Check out the same branch under the tC_resources repo. You will need the index.json file from this PR
https://github.com/translationCoreApps/tC_Resources/pull/10
Open a titus project and use the alignment tool and make a few checks to see the percentage go up.
Make sure you can see it in the home overview and the actual tool card when loading a tool.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3013)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Note: do not merge yet...I have to write tests...

**Comment by RoyalSix** [comment]
Tests for this PR will pass once the submodule PR gets merged.
https://github.com/translationCoreApps/tC_Resources/pull/10

**Comment by RoyalSix** [comment]
I added both storys to this PR...
#2873
#2866

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 5 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/fixtures/project/wordAlignment/normal_project/.apps/translationCore/alignmentData/tit/1.json, line 0 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3013#-KxsJud4I369vykIkzgY:-KxsJud4I369vykIkzgZ:b-194r5r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/daea1e71783df5b8068d995de8cc67e643ffe23a/__tests__/fixtures/project/wordAlignment/normal_project/.apps/translationCore/alignmentData/tit/1.json#L0)):*
any reason why this file is almost 5k lines of code? just wondering if we need all of that?

---

*[src/js/helpers/MissingVersesHelpers.js, line 54 at r6](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3013#-KxsKGXnofHrRpLGi706:-KxsKGXnofHrRpLGi707:b-gkh4kl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/daea1e71783df5b8068d995de8cc67e643ffe23a/src/js/helpers/MissingVersesHelpers.js#L54)):*
> ```JavaScript
>  * @return {*}
>  */
> export function getExpectedBookVerses(bookAbbr, languageId = 'en', bookName = 'ulb', version = 'v11') {
> ```

good job. like that variable assignment inside the function  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3013#-:-KxsKXM_xAM7XaDiZGlF:bnfp4nl)*

**Comment by mannycolon** [comment]
@RoyalSix Tests are failing

**Comment by mannycolon** [comment]
@RoyalSix when testing this branch the progress updates in the circles but doesn't show any progress on the tool card on the home screen.

**Comment by mannycolon** [comment]
@RoyalSix Progress functionality is working. However, tests are still failing.

**Pull request merged**
