### PR TITLE
Adds more Concourse release commands

### PR DESCRIPTION
**Pull request by da1nerd**
#### Describe what your pull request addresses (Please include relevant issue numbers):
related to #4306 

This adds a number of build commands that concourse will use to generate releases:
- Adds a release command for macOS
- Adds a release command for windows x64
- Adds a release command for windows x32

#### Please include detailed Test instructions for your pull request:
- Not much to test here. I've only added a few extra gulp methods that won't affect anything else.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4540)

### CODE REVIEW

**Comment by da1nerd** [comment]
[Linux build a366631 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-a366631.zip) is ready for download.

**Comment by da1nerd** [comment]
This is another comment

**Comment by neutrinog** [comment]
This is another comment

**Comment by neutrinog** [comment]
This is another comment

**Comment by da1nerd** [comment]
Testing PR comments
This is another comment

**Comment by neutrinog** [comment]
Testing PR comments
This is another comment

**Comment by da1nerd** [comment]
[Linux build a366631 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-a366631.zip) is ready for download.
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by neutrinog** [comment]
[Linux build 7e20aba (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7e20aba.zip) is ready for download.
Some builds failed

**Comment by neutrinog** [comment]
[Linux build 7e20aba (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7e20aba.zip) is ready for download.
[macOS build 7e20aba (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7e20aba.dmg) is ready for download.
Some builds failed

**Comment by neutrinog** [comment]
[Linux build 7e20aba (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-7e20aba.zip) is ready for download.
[macOS build 7e20aba (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-7e20aba.dmg) is ready for download.
Some builds failed

**Comment by neutrinog** [comment]
Some builds failed

**Comment by da1nerd** [comment]
[Linux build ca20397 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-ca20397.zip) is ready for download.
[macOS build ca20397 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-ca20397.dmg) is ready for download.
Some builds failed

**Comment by neutrinog** [comment]
[Linux build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-d2f0703.zip) is ready for download.
[macOS build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-d2f0703.dmg) is ready for download.
[Windows build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-d2f0703.setup.exe) is ready for download.
[Windows build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-d2f0703.setup.exe) is ready for download.
Some builds failed

**Comment by da1nerd** [comment]
[Linux build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-d2f0703.zip) is ready for download.
[macOS build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-d2f0703.dmg) is ready for download.
[Windows x64 build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-d2f0703.setup.exe) is ready for download.
[Windows x32 build d2f0703 (v0.10.0)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-d2f0703.setup.exe) is ready for download.

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4540)*

**Pull request merged**
