### PR TITLE
Allow all New Testament books in non-developer mode for 0.8.1 limited release 

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:
- Allow all New Testament books in non-developer mode for 0.8.1 limited release 

#### How to test this pull request:

- Try to load non-titus projects in developer mode and in non-developer mode.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3490)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 194 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490#-L0yaYgoQn-D-yna-wHT:-L0yaYgoQn-D-yna-wHU:b-bcdc6w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b58e8f952ac85e7d39a2219fbc06809c2732f14/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L194)):*
> ```JavaScript
>     let { manifest } = state.projectDetailsReducer;
>     if (manifest && manifest.project && bibleHelpers.isNewTestamentBook(manifest.project.id)) return resolve();
>     else return reject('This version of translationCore only supports Titus projects.');
> ```

Maybe we should change this prompt to be New Testament Projects?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490#-:-L0ycpjz7IqdxhchhZh8:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Works well.  Tested loading:
- psa in developer mode - got warning
- luk in developer mode - imported
- eph in non-developer mode - imported

Works as expected.

**Comment by klappy** [comment]
*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 194 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490#-L0yaYgoQn-D-yna-wHT:-L0yy-5cf7MimfqeFgjA:b-x972gd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b58e8f952ac85e7d39a2219fbc06809c2732f14/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L194)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Maybe we should change this prompt to be New Testament Projects?
</blockquote></details>

@manny, once you update this message, the PR looks good to go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490#-:-L0z7upO3KFhz5Qr7U93:bnfp4nl)*

**Comment by klappy** [comment]
*[src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js, line 194 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490#-L0yaYgoQn-D-yna-wHT:-L0z7x2dmViX2BNjwnVw:bb6ywmx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b58e8f952ac85e7d39a2219fbc06809c2732f14/src/js/helpers/ProjectValidation/ProjectStructureValidationHelpers.js#L194)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@manny, once you update this message, the PR looks good to go.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3490)*

**Pull request merged**
