### PR TITLE
Fix the Modal Tabs

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/549)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/containers/ModalContainer.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549#-KbM4PvicvpgHwv3MFVG:-KbM4PvicvpgHwv3MFVH:bfaw8xq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b81bffe9c508541055d3b167993a94a789957db/src/js/containers/ModalContainer.js#L57)):*
> ```JavaScript
>         </Modal>
>       )
> >>>>>>> develop
> ```

remove this lol

---

*[src/js/reducers/newModalReducer.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549#-KbM4ZMcxwAAddidajMP:-KbM4ZMcxwAAddidajMQ:b-vo774v) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b81bffe9c508541055d3b167993a94a789957db/src/js/reducers/newModalReducer.js#L4)):*
> ```JavaScript
> const merge = require('lodash.merge');
> 
> const initialState = {
> ```

could you please do the same for login reducer it has the same issue and btw i wonder why the loginReducer.js  works thought lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ModalContainer.js, line 57 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549#-KbM4PvicvpgHwv3MFVG:-KbM506Mj4moXkkA8LhP:b-x24o21) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b81bffe9c508541055d3b167993a94a789957db/src/js/containers/ModalContainer.js#L57)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove this lol
</blockquote></details>

haha my b

---

*[src/js/reducers/newModalReducer.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549#-KbM4ZMcxwAAddidajMP:-KbM4zauoVYgiYfl686Z:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/2b81bffe9c508541055d3b167993a94a789957db/src/js/reducers/newModalReducer.js#L4)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could you please do the same for login reducer it has the same issue and btw i wonder why the loginReducer.js  works thought lol
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/549)*

**Pull request merged**
