### PR TITLE
Bugfix 5030/Only load languages used by tool

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- tCore is changed to only load bibles used by tools into reducer.
- Scripture pane changed to get list of bibles to add from getAvailableScripturePaneSelections() and to call makeSureBiblesLoadedForTool() when user selects a new scripture pane resource.
- includes changes to WA and TW tools to pass actions getAvailableScripturePaneSelections() and makeSureBiblesLoadedForTool() to ScripturePane.

#### Please include detailed Test instructions for your pull request:
- Use the latest sandbox build posted below.  This will test all three PRs: this one, https://github.com/translationCoreApps/wordAlignment/pull/77 and https://github.com/translationCoreApps/translationWords/pull/151 combined.
- make sure WA and TW tools open fine (except for other known bug opening projects with front matter).  Make sure you can go into scripture pane in both tools.  And when you add to scripture pane, make sure all bibles are shown in selection (as long as it contains the book of the bible). Also trying adding a resource to make sure it gets shown in scripture pane and doesn't crash.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5034)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (c2263b4)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-c2263b4.zip) is ready for download.
[macOS build 1.0.0 (c2263b4)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-c2263b4.dmg) is ready for download.
[Windows x64 build 1.0.0 (c2263b4)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-c2263b4.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (c2263b4)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-c2263b4.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (b7e4cee)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-b7e4cee.zip) is ready for download.
[macOS build 1.0.0 (b7e4cee)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-b7e4cee.dmg) is ready for download.
[Windows x64 build 1.0.0 (b7e4cee)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-b7e4cee.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (b7e4cee)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-b7e4cee.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
### Can test with sandbox build:

translationCore 1.0.0-9de81b5
Commit 9de81b5 on sandbox-5030
Travis build #9309

win64 http://win64.tc-sandbox.unfoldingword.surge.sh/translationCore-win-x64-1.0.0-9de81b5.setup.exe
mac http://macos.tc-sandbox.unfoldingword.surge.sh/translationCore-macos-x64-1.0.0-9de81b5.dmg
linux http://linux.tc-sandbox.unfoldingword.surge.sh/translationCore-linux-x64-1.0.0-9de81b5.zip

**Comment by PhotoNomad0** [comment]
I was able to coerce a release-sandbox-5030 build in concourse:
### Here are builds for testing:

Linux build cd3fdd6 (v1.0.0) is ready for download. https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-cd3fdd6.zip
macOS build cd3fdd6 (v1.0.0) is ready for download. https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-cd3fdd6.dmg
Windows x64 build cd3fdd6 (v1.0.0) is ready for download. https://tc-builds.door43.org/translationCore-win-x64-1.0.0-cd3fdd6.setup.exe
Windows x32 build cd3fdd6 (v1.0.0) is ready for download. https://tc-builds.door43.org/translationCore-win-x32-1.0.0-cd3fdd6.setup.exe

**Review by richmahn — APPROVED** [review]
:lgtm: 

> Reviewed 16 of 16 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5034#-:-LMNkXhMCisdFQqWSqKq:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
