### PR TITLE
Feature/klappy navigation debug

### PR DESCRIPTION
**Pull request by klappy**
## This PR Addresses
Addresses misc Navigation bugs including: 
- [ ] Next/Previous not hanging on empty GroupId’s GroupData.
- [ ] Collapse/expand icon on menu headers aligned properly.
- [ ] Removed Dummy Data from contextIdReducer.
- [ ] Next/Previous loops around to end/beginning instead of hanging when using previous on the first, and next on the last check.
- [ ] Sorting moved to data input instead of on view rendering to make next/previous work.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1047)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/js/containers/ToolsContainer.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-Kh8Apurkt0D9jBkGONg:-Kh8Apurkt0D9jBkGONh:bvpevz3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/11de867057593fb0a8fb3cb8351ac357646e2713/src/js/containers/ToolsContainer.js#L33)):*
> ```JavaScript
>         valid = (contextId !== null)
>       }
>       this.props.actions.changeCurrentContextId(contextId)
> ```

why do we have all this business logic here?? I could be wrong but it seems off to me that we have to do this here. 

---

*[src/js/utils/localStorage.js, line 55 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-Kh8BC1-rzLsgINf9whD:-Kh8BC1-rzLsgINf9whE:b-1v7kjm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/11de867057593fb0a8fb3cb8351ac357646e2713/src/js/utils/localStorage.js#L55)):*
> ```JavaScript
>       //   modifiedTimestamp: "2017-02-17T22:23:49.357Z"
>       // },
>       // contextIdReducer: {
> ```

can already we get rid of all the dummy data ?? or we still need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047)*

**Comment by mannycolon** [comment]
@klappy I'm getting the following error when testing this branch
```
Container.js [sm]:47 Uncaught TypeError: Cannot read property 'groupId' of null
```

and it wont let me get pass the loading tool screen

**Comment by klappy** [comment]
*[src/js/utils/localStorage.js, line 55 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-Kh8BC1-rzLsgINf9whD:-Kh9HPlL7P9MAzSO7-Mv:b9rjcm6) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/11de867057593fb0a8fb3cb8351ac357646e2713/src/js/utils/localStorage.js#L55)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can already we get rid of all the dummy data ?? or we still need it?
</blockquote></details>

I propose we delete it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047)*

**Comment by klappy** [comment]
*[src/js/utils/localStorage.js, line 55 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-Kh8BC1-rzLsgINf9whD:-Kh9MmBKCXLDKo28enNB:bb7f2mf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/11de867057593fb0a8fb3cb8351ac357646e2713/src/js/utils/localStorage.js#L55)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I propose we delete it now.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047)*

**Comment by klappy** [comment]
*[src/js/containers/ToolsContainer.js, line 33 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-Kh8Apurkt0D9jBkGONg:-Kh9Mnl0tO_qqkD2sNq4:b-7rl0jd) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/11de867057593fb0a8fb3cb8351ac357646e2713/src/js/containers/ToolsContainer.js#L33)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we have all this business logic here?? I could be wrong but it seems off to me that we have to do this here. 
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047)*

**Comment by klappy** [comment]
@mannycolon: Addressed issues, can you see if you get the same error? If so, let me know what book/project.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-:-Kh9N5moKKrUJP5qTJjl:bseoacs)*

**Comment by RoyalSix** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/js/actions/ContextIdActions.js, line 46 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-KhA2Mj65VBk7Eu6Qe2f:-KhA2Mj65VBk7Eu6Qe2g:b-ps08nu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/fcc67a0ddaf9ea746dcd4cd2bafc083b593d1066/src/js/actions/ContextIdActions.js#L46)):*
> ```JavaScript
>         valid = !!contextId
>       }
>       debugger
> ```

debugger

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047)*

**Comment by RoyalSix** [comment]
@klappy I pulled your branch and was getting the error for setting state in the render function so I added the code below instead of in the render to the componentWillReceiveProps func 

---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-:-KhA4Q7HY_K1MzrUL8yX:b-tmwcdq)*

**Comment by RoyalSix** [comment]
`componentWillReceiveProps(nextProps) {
    let { contextId } = nextProps.contextIdReducer
    if (!contextId) nextProps.actions.changeToFirstContextId()
  }`

---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1047#-:-KhA4t0osHcQyMFgtTV9:beshmgb)*

**Pull request merged**
