### PR TITLE
DCS Repo Rename Method

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR creates a method to rename a door 43 repository

#### Please include detailed Test instructions for your pull request:
- This PR does not add anything new to test locally
- The functionality will be testable in PR for #4550
- Ensuring that the tests are robust and passing is sufficient testing

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)

### CODE REVIEW

**Comment by richmahn** [comment]
I was unable to get tests to pass....may be my mac book? Can anyone else see if you get a timeout for the GogsApi tests?

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PhotoNomad0** [comment]
@RoyalSix - don't think we need to merge this PR since there is nothing testable by QA, and there are no points.  Maybe I just merge this into my branch and we work together to get it working?

**Comment by richmahn** [comment]
@PhotoNomad0 Probably the best idea, but did you get his tests to run on your machine? Any idea why it won't run on my MacBook? We also need to make sure it doesn't hinder running tests on Windows.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

___
*[__mocks__/gogs-client.js, line 122 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676#-LGythKk8NBixX9c8kaF:-LGythKk8NBixX9c8kaG:beivmmm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3d108cac2c36f590b07bf8ec66ed865ec860b453/__mocks__/gogs-client.js#L122)):*
> ```JavaScript
>   self.deleteRepo = function() {
>     return Promise.resolve();
>   };
> ```

Seems to do nothing?

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/helpers/GogsApiHelpers.js, line 67 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676#-LGzYfsJ6vSdAerCYNI4:-LGzYfsJ6vSdAerCYNI5:bko1498) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3d108cac2c36f590b07bf8ec66ed865ec860b453/src/js/helpers/GogsApiHelpers.js#L67)):*
> ```JavaScript
>     const {name: repoName, url: repoOwnerUrl} = await git.getRepoNameInfo(projectPath);
>     /** If new repo name exits already then we can not change to that */
>     await throwIfRemoteRepoExists(repoOwnerUrl);
> ```

Seems to be a logic error here.  Shouldn't this be checking the new URL?  repoOwnerUrl here contains the old path, which already exists.

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @RoyalSix)

___
*[src/js/helpers/GogsApiHelpers.js, line 67 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676#-LGzYfsJ6vSdAerCYNI4:-LGzlKS1CJjSuK8JQt5S:by4tz5z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3d108cac2c36f590b07bf8ec66ed865ec860b453/src/js/helpers/GogsApiHelpers.js#L67)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Seems to be a logic error here.  Shouldn't this be checking the new URL?  repoOwnerUrl here contains the old path, which already exists. 
</blockquote></details>

Nevermind about this.  Already fixed on my branch - DCS rename is working well now.

**Review by RoyalSix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @RoyalSix and @PhotoNomad0)

___
*[__mocks__/gogs-client.js, line 122 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676#-LGythKk8NBixX9c8kaF:-LH-jmnGEOoaUdVewUjU:b-xr5wy8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3d108cac2c36f590b07bf8ec66ed865ec860b453/__mocks__/gogs-client.js#L122)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Seems to do nothing?
</blockquote></details>

Yes this is just a mock so that the unit test can run
___
*[src/js/helpers/GogsApiHelpers.js, line 67 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4676#-LGzYfsJ6vSdAerCYNI4:-LH-jmO5AQS-0DxaY3zs:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/3d108cac2c36f590b07bf8ec66ed865ec860b453/src/js/helpers/GogsApiHelpers.js#L67)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Nevermind about this.  Already fixed on my branch - DCS rename is working well now.
</blockquote></details>

Done.

**Comment by RoyalSix** [comment]
@PhotoNomad0 I will close this once all the issues related to the implementation are resolved

**Comment by PhotoNomad0** [comment]
screen shot 2018-07-10 at 6 41 48 am

@RoyalSix - Working on testing failure modes here.  The first error is troubling.  This is when I am calling the repo rename function and have the network disconnected.  It looks like there is an error thrown somewhere, but it doesn't get thrown up to the application so it can be caught.  And I never get a callback.  Any ideas how to handle this?

**Pull request closed without merging**
