### PR TITLE
Fixed multiple bugs for USFM Import

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Fixed bug with target language generated from `USFM` files.
- Fixed bug that wouldn't allow to import`USFM` files with merge conflicts.

##### Both files below should load with no problem.

- [en-x-demo1_php_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1579951/en-x-demo1_php_text_reg.usfm.zip)
- [en_EPH_Ephesians-A.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1579949/en_EPH_Ephesians-A.usfm.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3484)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3484)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3484#-:-L0uBX62Ot3LYEyyEYyo:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3484)*

**Comment by klappy** [comment]
The code looks good, I'm running the tests locally and testing the imports of those projects listed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3484#-:-L0uShBWFVfurFRH55nO:bcq73zd)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3484#-:-L0uXSA2JuaAem2RNDuU:bnfp4nl)*

**Pull request merged**
