### PR TITLE
Feature mcleanb 4424/automatically discover supported languages for tool cards

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- dynamically determines supported GL languages to put on tool cards for a book:
  - for WA tool:
    - supported languages must have at least one bible that:
      - contains the book, and which must have alignments
      - bible has a manifest
    - the book must also be in the Original Language (such as grc).
  - for TW tool has the requirements above plus:
    - the Original Language for book must be at least checking level 2 (in manifest).
    - the aligned bible in the gateway Language:
      - must be at least checking level 3 (in manifest).
      - must have translationWords under translationHelps

#### Note: 
- English will now be missing for every book but Titus until this issue is finished: https://github.com/unfoldingWord-dev/translationCore/issues/4805

#### Please include detailed Test instructions for your pull request:
- install and run build at bottom of PR.
- turn off developer mode
- open a `gal` project:
  - should see no selectable languages for both WA and TW, since the en/ULT `gal` has no alignments and hi/ULB has no `gal`.  There is another issue to add the aligned ULT to app resources
- open a Titus project:
  - should see en & hi as selectable languages for both WA and TW
- in resources folder copy en to el. Then in app, click on projects tab and then click on tools to refresh tool cards.
  - should see en, el & hi as selectable languages for both WA and TW
- in resources folder under el/translationHelps delete translationWords. Then in app, click on projects tab and then click on tools to refresh tool cards.
  - should see only en & hi as selectable languages for TW (since translated helps are required), and should see en, el & hi as selectable languages for WA
- in resources folder under el/bibles delete ust.  Then under el/bibles/ult/v12.1 edit manifest.json to change "checking/checking_level to "2". Then in app, click on projects tab and then click on tools to refresh tool cards.
  - should see en & hi as selectable languages for both WA and TW since the el language now does not have a bible with sufficient checking level.

- to clean up, in resources folder delete el so it doesn't cause trouble for you in future.  

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4840)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (f9daf55)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-f9daf55.zip) is ready for download.
[macOS build 1.0.0 (f9daf55)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-f9daf55.dmg) is ready for download.
[Windows x64 build 1.0.0 (f9daf55)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-f9daf55.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (f9daf55)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-f9daf55.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (edb8ea7)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-edb8ea7.zip) is ready for download.
[macOS build 1.0.0 (edb8ea7)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-edb8ea7.dmg) is ready for download.
[Windows x64 build 1.0.0 (edb8ea7)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-edb8ea7.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (edb8ea7)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-edb8ea7.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (8b4d8a8)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-8b4d8a8.zip) is ready for download.
[macOS build 1.0.0 (8b4d8a8)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-8b4d8a8.dmg) is ready for download.
[Windows x64 build 1.0.0 (8b4d8a8)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-8b4d8a8.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (8b4d8a8)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-8b4d8a8.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.0.0 (cffd437)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-cffd437.zip) is ready for download.
[macOS build 1.0.0 (cffd437)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-cffd437.dmg) is ready for download.
[Windows x64 build 1.0.0 (cffd437)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-cffd437.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (cffd437)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-cffd437.setup.exe) is ready for download.

**Review by richmahn — APPROVED** [review]
:lgtm: - Code review
:lgtm: - Local testing

> Reviewed 18 of 22 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4840#-:-LJPR-ifEUeXud2zrXJ-:buuphxx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Pull request merged**
