### PR TITLE
Added local import dialog and USFM tests

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes some workflow issues with USFM for better testing,
adds more testing for USFM to ensure handling of missing / out of sequence content,
lastly adds a dialog to let the user know the local import succeeeds

#### How to test this pull request:
Try importing a project that is USFM and ensure everything work as expected
Try running <code>npm run</code>

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2586)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/js/actions/ImportLocalActions.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-Ksih3ptZBMpD8VRMJiG:-Ksih3ptZBMpD8VRMJiH:biyajvy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4cdde667985249b418063f565d1493eedcdae47/src/js/actions/ImportLocalActions.js#L40)):*
> ```JavaScript
>       dispatch(BodyUIActions.toggleProjectsFAB());
>       if (filePaths === undefined) {
>         return dispatch(AlertModalActions.openAlertDialog(ALERT_MESSAGE));
> ```

What does returning the dispatch do here? Is it to exit the action early?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by klappy** [comment]
*[src/js/actions/ImportLocalActions.js, line 97 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-KsihDo-s30DzoDBjzOt:-KsihDo-s30DzoDBjzOu:b-9u9dy2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4cdde667985249b418063f565d1493eedcdae47/src/js/actions/ImportLocalActions.js#L97)):*
> ```JavaScript
> }
> 
> export function updateUSFMFolderName() {
> ```

Should we move this to a helper and only pass the `manifest` and `projectSaveLocation` as params to the helper function? 
That will also make this easier to test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by klappy** [comment]
Great job getting this knocked out so quickly!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-:-KsihdoxPIXrIiXhQMVY:b25tmg1)*

**Comment by klappy** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by RoyalSix** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ImportLocalActions.js, line 40 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-Ksih3ptZBMpD8VRMJiG:-Ksj0nYRuTnrLG_NJbqr:bt33chm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4cdde667985249b418063f565d1493eedcdae47/src/js/actions/ImportLocalActions.js#L40)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

What does returning the dispatch do here? Is it to exit the action early?
</blockquote></details>

Yes, I will add documentation

---

*[src/js/actions/ImportLocalActions.js, line 97 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-KsihDo-s30DzoDBjzOt:-Ksjm5tW3aotPrjYx3EH:b-gs742o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4cdde667985249b418063f565d1493eedcdae47/src/js/actions/ImportLocalActions.js#L97)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should we move this to a helper and only pass the `manifest` and `projectSaveLocation` as params to the helper function? 
That will also make this easier to test.
</blockquote></details>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by RoyalSix** [comment]
Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ImportLocalActions.js, line 97 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-KsihDo-s30DzoDBjzOt:-KsjnnQAFyNTJ-PogGnR:b7sgqcz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d4cdde667985249b418063f565d1493eedcdae47/src/js/actions/ImportLocalActions.js#L97)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Maybe. This action uses data thats not passed to it purposefully. It grabs it from the store knowing that whatever is in the store for the project save location is the correct one
</blockquote></details>

Actually I abstracted it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by klappy** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-:-KsnfUQzXcFeBaJ208Hi:bnfp4nl)*

**Comment by klappy** [comment]
The code looks good. I'm about to test the UI with some USFM files.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-:-KsnfVkuKZreQTE6CNY8:b-6uoueu)*

**Comment by klappy** [comment]
@RoyalSix: I have difficulty importing the following project:
[fr_eph_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1264132/fr_eph_text_reg.usfm.zip)

Can you check it out and see what it would take to support it again? 
I believe it's an old tC project export. 
When I delete the \id tag it imports properly. 

If there is a problem with the \id marker, we should look into failing gracefully.  

Here's what it looks like on my machine:
screen shot 2017-08-30 at 11 21 31 am

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-:-KstpYZ5YE0U6wjBoA9w:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Comment by klappy** [comment]
Problem file above now imports properly.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586#-:-Kstp_glijyokyktnGOi:b-cgdjwq)*

**Comment by mannycolon** [comment]
Reviewed 8 of 12 files at r1, 12 of 15 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2586)*

**Pull request merged**
