### PR TITLE
component testing

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1709)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 3 of 42 files at r1.
Review status: 3 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1709)*

**Comment by klappy** [comment]
*[test/index.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1709#-KleJzAAfFNP0h9vqq0z:-KleJzABEks-FeXlS38A:b-ppqamm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/eace0fa5929595ed8b35c645a1d0f847d9e0b12f/test/index.js#L1)):*
> ```JavaScript
> global.path = require('path-extra');
> ```

What do we think of updating all of these in this file to ES6 syntax while we're here in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1709)*

**Comment by klappy** [comment]
Reviewed 38 of 42 files at r1.
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1709)*

**Comment by mannycolon** [comment]
@klappy @RoyalSix I don't feel comfortable merging this PR. there are many inconsistencies that concern me. we should probably talk about those issues before merging.

**Pull request closed without merging**
