### PR TITLE
USFM Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/310)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Dont merge this yet

**Comment by klappy** [comment]
Can you update this issue with an estimate?

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/310)_

**Comment by RoyalSix** [comment]
Ready to merge 😄

**Comment by ihoegen** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/310)_

**Comment by ihoegen** [comment]
Looks good to me.

**Pull request merged**
