### PR TITLE
Non-happy-path Testing

### PR DESCRIPTION
**Pull request by ihoegen**
This brings in Non-Happy path testing for:
- ModuleAPI.js
- LoadOnline.js
- ImportUSFM.js
- CoreActions.js

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/384)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/c.PackageManager.js, line 98 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/384#-KYL43Id4UROppCjwm4C:-KYL43IdDTQH1w58lsEd:b-kx5317) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1bb882dc293a92dd2feb456b9df88f44f9c969e4/tests/c.PackageManager.js#L98)):*
> ```JavaScript
>     assert.isFalse(PackageManager.isInstalled('translationRhymes'));
>   });
> })
> ```

Is it possible to test if isInstalled returns true for an installed package?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/384)*

**Comment by ihoegen** [comment]
Not with the old package manager, but it can with the new one

**Comment by RoyalSix** [comment]
Ok, so are we just excluding that test for now?

**Comment by ihoegen** [comment]
That is correct, I'll add it in when PackageManager is in, and I bring in my other tests

**Comment by RoyalSix** [comment]
Reviewed 2 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/384)*

**Pull request merged**
