### PR TITLE
Fix For \q tags and \f tags and Address Infinite Render Loop

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR fixes an issue with the \q tags filter function removing a needed space, and it also fixes a bug which makes the Scripture Pane endlessly re-render.

#### How to test this pull request:
run ```npm update usfm-js```
Test by opening tW in Ephs and going to the ```Christ``` check, ensure that the verse reads ```5:14 For anything that becomes visible is light. Therefore it says, "Awake, you sleeper, and arise from the dead, and Christ will shine on you."```

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3287)

### CODE REVIEW

**Comment by klappy** [comment]
Are all these files committed to the right PR?
A lot of these seem unrelated.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-3xse1Mz9mNMxt2tZI:b-bk60gb)*

**Comment by klappy** [comment]
@royalsix : It looks like the only files that should be committed and pushed to this PR are the package.json and lock.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-3yBtJNmFbM7oz0Pkv:bsup273)*

**Comment by RoyalSix** [comment]
@klappy I added tests and the test needed a project with translationWords checks

**Comment by klappy** [comment]
I missed the second half of the PR title saying Address Infinite Render Loop, maybe it was added after I read it the first time :)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-72f0DUYgttIbpuTk0:byuvm7h)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1, 56 of 56 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287)*

**Comment by klappy** [comment]
Somehow I'm getting this for the verse: `For anything that becomes visible is light. Therefore it says,\q "Awake, you sleeper, \q and arise from the dead ones, \q and Christ will shine on you."`

Am I doing something wrong? 
"usfm-js": "^1.0.0-beta.17"

I don't see a git diff for the Scripture Pane commit in the branch so I think it is okay.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-7vDHfjGNq2QFlfkn6:bvajyg)*

**Comment by klappy** [comment]
I checked out an old branch, sorry for the false alarm :)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-8GiVWKNGQi1q_p13W:bovr7dr)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287#-:-L-8HI-SjROR4NfcvMHR:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3287)*

**Pull request merged**
