### PR TITLE
Word Alignment Progress Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes the word alignment progress bar value

#### Please include detailed Test instructions for your pull request:
- Open the app.
- A fresh project should have 0% completed on the word alignment tool
- After you complete a verse the progress bar should go up according to the percent complete, verify this.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/3843)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/fixtures/project/wordAlignment/normal_project/LICENSE.md, line 0 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843#-L5QAieTB4ib9ikdgzPy:-L5QAieTB4ib9ikdgzPz:bdbzrc9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/497858a1696fefcedbc97bdf90ef8d4c13e9aa04/__tests__/fixtures/project/wordAlignment/normal_project/LICENSE.md#L0)):*
we dont need this LICENSE file anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/fixtures/project/wordAlignment/normal_project/LICENSE.md, line  at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843#-L5QAieTB4ib9ikdgzPy:-L5R2TgEgRwseTwojQ97:be3ho2b) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/497858a1696fefcedbc97bdf90ef8d4c13e9aa04/__tests__/fixtures/project/wordAlignment/normal_project/LICENSE.md#L)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont need this LICENSE file anymore?
</blockquote></details>

No its just a test folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/3843#-:-L5WK3Tq4NHcfvidTo4a:bnfp4nl)*

**Pull request merged**
