### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5365)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (75245c7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-75245c7.deb) is ready for download.
[macOS build 1.1.0 (75245c7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-75245c7.dmg) is ready for download.
[Windows x64 build 1.1.0 (75245c7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-75245c7.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (75245c7)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-75245c7.setup.exe) is ready for download.

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5365)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PhotoNomad0 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5365)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (dbcdf92)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-dbcdf92.deb) is ready for download.
[macOS build 1.1.0 (dbcdf92)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-dbcdf92.dmg) is ready for download.
[Windows x64 build 1.1.0 (dbcdf92)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-dbcdf92.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (dbcdf92)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-dbcdf92.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (78bba20)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-78bba20.deb) is ready for download.
[macOS build 1.1.0 (78bba20)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-78bba20.dmg) is ready for download.
[Windows x64 build 1.1.0 (78bba20)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-78bba20.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (78bba20)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-78bba20.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (35a46bc)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-35a46bc.deb) is ready for download.
[macOS build 1.1.0 (35a46bc)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-35a46bc.dmg) is ready for download.
[Windows x64 build 1.1.0 (35a46bc)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-35a46bc.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (35a46bc)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-35a46bc.setup.exe) is ready for download.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5365)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (bfe9849)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-bfe9849.deb) is ready for download.
[macOS build 1.1.0 (bfe9849)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-bfe9849.dmg) is ready for download.
[Windows x64 build 1.1.0 (bfe9849)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-bfe9849.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (bfe9849)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-bfe9849.setup.exe) is ready for download.

**Pull request merged**
