### PR TITLE
Bugfix bspidel 5437

### PR DESCRIPTION
**Pull request by bspidel**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- No longer shows duplicate language in "Update Gateway Language Content" dialog

#### Please include detailed Test instructions for your pull request:
1 Make sure you have no "ur*" resources.
2 Click Actions -> Check for content updates
3 Verify ur-Deva resource appears
4 Verify no other ur derivative resource appears
5 Select Urdu
6 Click download
7 After successful download repeat step 2
8 Verify no Urdu resource appears

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5478)

### CODE REVIEW

**Review by richmahn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5478)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bspidel)

___
*[src/js/components/dialogComponents/SourceContentUpdateDialog.js, line 59 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5478#-LSRV2Y6E13kFkh4DY93:-LSRV2Y6E13kFkh4DY94:bqf0czp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/752ae4d3062960c7c8d999550299654a17f2ef49/src/js/components/dialogComponents/SourceContentUpdateDialog.js#L59)):*
> ```JavaScript
>   }
> };
> //console.log( "getLanguageCodes", JSON.stringify( getLanguageCodes() ) );
> ```

I'd suggest removing this (keeping it a blank line) rather than commenting it out.

**Comment by RoyalSix** [comment]
Local Review: Good except for Rich's comment
Local Testing: `LGTM`

**Comment by RoyalSix** [comment]
Need test passing and update of branch w/ develop

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (09a4cd3)](https://tc-builds.door43.org/build/bugfix-bspidel-5437/translationCore-linux-x64-1.1.0-09a4cd3.deb) is ready for download.
[macOS build 1.1.0 (09a4cd3)](https://tc-builds.door43.org/build/bugfix-bspidel-5437/translationCore-macos-x64-1.1.0-09a4cd3.dmg) is ready for download.
[Windows x64 build 1.1.0 (09a4cd3)](https://tc-builds.door43.org/build/bugfix-bspidel-5437/translationCore-win-x64-1.1.0-09a4cd3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (09a4cd3)](https://tc-builds.door43.org/build/bugfix-bspidel-5437/translationCore-win-x32-1.1.0-09a4cd3.setup.exe) is ready for download.

**Comment by bspidel** [comment]
Made Rich's requested change and ran McLean's script to make travis pass.

**Review by richmahn — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5478#-:-LSVNOGQ1mU8dH7wZtQg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
