### PR TITLE
Merge Conflict Check

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR brings in the Merge Conflict Check including the ability to find merge conflicts and resolve them in a usfm file. This PR also has small fixes to interface layout space to improve consistency, and actions for handling project import checks as a whole.

#### How to test this pull request:
Download these two projects:
[ema-x-ora_php_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1206115/ema-x-ora_php_text_ulb.zip)
[ha_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1209066/ha_tit_text_ulb.zip)
Unzip them and open them with tC. 
You should be presented with the merge conflicts to choose. (Remember your choice of version to resolve)
Once you choose one to accept as the resolved git history, you can finish importing the project.
Check to make sure the version you chose shows in the check. (these projects have conflicts on the first check of tN to make it easier to verify.)
This PR assumes that merge conflicts are happening before the project is imported (a tC project or usfm file) and has a usfm file format for the conflict.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2392)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr1GPTqaIwEHqlxpgbf:b-t4l2he) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
> ```JavaScript
>  */
> export function mergeConflictCheck(state, dispatch) {
>   const { projectSaveLocation, manifest } = state.projectDetailsReducer;
> ```

should we have a MergeConflictActions.js and MissingVersesActions.js?

that way we don't have too many lines of code in here. and also it would be easier to find.

---

*[src/js/components/projectValidation/MergeConflictsCheck.js, line 7 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1HX0mJOWoVNrr0C1a:-Kr1HX0mJOWoVNrr0C1b:b-m3ax3z) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/components/projectValidation/MergeConflictsCheck.js#L7)):*
> ```JavaScript
>   render() {
>     return (
>       <div>
> ```

this components should have the jsx that you have in the container.

---

*[src/js/containers/projectValidation/MergeConflictsCheckContainer.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GuwJBUrIuQRR_Cvp:-Kr1GuwJBUrIuQRR_Cvq:bmuhnpt) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/containers/projectValidation/MergeConflictsCheckContainer.js#L58)):*
> ```JavaScript
>   }
> 
>   mergeConflictCards(conflictObject) {
> ```

this should be in the component not here.

---

*[src/js/containers/projectValidation/MergeConflictsCheckContainer.js, line 83 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1H-t4TShEfYf1NaXQ:-Kr1H-t4TShEfYf1NaXR:b-imgo1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/containers/projectValidation/MergeConflictsCheckContainer.js#L83)):*
> ```JavaScript
>       }
>       let borderBottom = conflict.open ? 'none' : '1px solid black';
>       conflictCards.push(
> ```

this should be split up in components

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by mannycolon** [comment]
@RoyalSix I just realized that MergeConflictsCheckContainer.js is not an actual container.


I thought we had said we would have an index.js that would hold all the MergeConflictsCheck components. 

For example,


```
components
         |
        projectValidation
                       |
                       MergeConflictsCheck 
                                        |
                                         index.js
                                          other merge conflict components


```

Then in projectValidationContainer
```
import MergeConflictsCheck from '../components/projectValidation/MergeConflictsCheck'
```

**Comment by mannycolon** [comment]
youre still using 4 spaces in your files.

**Comment by RoyalSix** [comment]
Review status: 9 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr1xVO9PEzKDkD2lmMo:b-w3tcbf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

should we have a MergeConflictActions.js and MissingVersesActions.js?

that way we don't have too many lines of code in here. and also it would be easier to find.
</blockquote></details>

Maybe, I just sucks seeing our actions folder get bigger

---

*[src/js/components/projectValidation/MergeConflictsCheck.js, line 7 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1HX0mJOWoVNrr0C1a:-Kr1xiVx6mSKE4jchGz1:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/components/projectValidation/MergeConflictsCheck.js#L7)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this components should have the jsx that you have in the container.
</blockquote></details>

Done.

---

*[src/js/containers/projectValidation/MergeConflictsCheckContainer.js, line 58 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GuwJBUrIuQRR_Cvp:-Kr1xloK-U9dR79HjliR:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/containers/projectValidation/MergeConflictsCheckContainer.js#L58)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should be in the component not here.
</blockquote></details>

Done.

---

*[src/js/containers/projectValidation/MergeConflictsCheckContainer.js, line 83 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1H-t4TShEfYf1NaXQ:-Kr1xm_JpmUHRgEvGTS_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/containers/projectValidation/MergeConflictsCheckContainer.js#L83)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should be split up in components
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by RoyalSix** [comment]
Review status: 9 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr1xrJaeEZn5OGNG630:b2ni52y) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Maybe, I just sucks seeing our actions folder get bigger
</blockquote></details>

it*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by RoyalSix** [comment]
Review status: 9 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr1yGI1Szmy6pXvpkHs:b8nxyx8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

it*
</blockquote></details>

@klappy what do you think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by mannycolon** [comment]
Reviewed 1 of 15 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by mannycolon** [comment]
@klappy

**Comment by klappy** [comment]
*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr265L68j2PhlIh2bbo:b-td8kvw) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

@klappy what do you think
</blockquote></details>

I would rather have more files than more lines per file, I think these actions should be explicit and organized as separate files to help manage the code. 
100 lines target, once it grows over 200-300 lines, it needs to be broken up.

In this case, we have clear separation of concerns. A lot of these actions are UI related, keep those in here.
But some of these make way more sense as helpers. Then call them in the Actions. 

Let's try to keep the Actions lighter and fs stuff in helpers if we can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr26zzs2TAcZgEWdV_I:b4elpen) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I would rather have more files than more lines per file, I think these actions should be explicit and organized as separate files to help manage the code. 
100 lines target, once it grows over 200-300 lines, it needs to be broken up.

In this case, we have clear separation of concerns. A lot of these actions are UI related, keep those in here.
But some of these make way more sense as helpers. Then call them in the Actions. 

Let's try to keep the Actions lighter and fs stuff in helpers if we can.
</blockquote></details>

That way we can test the helpers more easily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr27GZZ2iayUww6H0qW:-Kr27GZZ2iayUww6H0qX:b6wn2bk) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7458a6d848702c30dac378891e4d63f255941ec2/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
> ```JavaScript
> 
> 
> class MergeConflictsCheckContainer extends Component {
> ```

Since this is in the Components folder, shouldn't this be named 'MergeConflictsCheckComponent' instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 9 of 15 files at r1, 11 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Looks good! just a few things left to address.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-:-Kr27pcAzRDSDphbuCSD:b-ejuq25)*

**Comment by RoyalSix** [comment]
Review status: 11 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/actions/ProjectValidationActions.js, line 77 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr1GPTqaIwEHqlxpgbe:-Kr2WzfJ66R7tgEnElOQ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7815876270a2639480cc6eb7619b32136486d97d/src/js/actions/ProjectValidationActions.js#L77)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

That way we can test the helpers more easily.
</blockquote></details>

Done.

---

*[src/js/components/projectValidation/MergeConflictsCheck/index.js, line 8 at r2](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-Kr27GZZ2iayUww6H0qW:-Kr28gk-f80E_9NT4Co0:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7458a6d848702c30dac378891e4d63f255941ec2/src/js/components/projectValidation/MergeConflictsCheck/index.js#L8)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Since this is in the Components folder, shouldn't this be named 'MergeConflictsCheckComponent' instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r3.
Review status: 12 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r3.
Review status: 12 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 1 of 10 files at r3.
Review status: 13 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 4 of 10 files at r3.
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r3, 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-:-Kr2_MIKtD_MPMPf4M5T:bnfp4nl)*

**Comment by klappy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2392#-:-Kr2_fOTUoGywYSx86GI:bnfp4nl)*

**Pull request merged**
