### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by da1nerd**
Enjoy!

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5471)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (c8db0f9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-c8db0f9.deb) is ready for download.
[macOS build 1.1.0 (c8db0f9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-c8db0f9.dmg) is ready for download.
[Windows x64 build 1.1.0 (c8db0f9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-c8db0f9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c8db0f9)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-c8db0f9.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (370798f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-370798f.deb) is ready for download.
[macOS build 1.1.0 (370798f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-370798f.dmg) is ready for download.
[Windows x64 build 1.1.0 (370798f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-370798f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (370798f)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-370798f.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (71e0d40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-71e0d40.deb) is ready for download.
[macOS build 1.1.0 (71e0d40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-71e0d40.dmg) is ready for download.
[Windows x64 build 1.1.0 (71e0d40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-71e0d40.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (71e0d40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-71e0d40.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (d2e83fe)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-d2e83fe.deb) is ready for download.
[macOS build 1.1.0 (d2e83fe)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-d2e83fe.dmg) is ready for download.
[Windows x64 build 1.1.0 (d2e83fe)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-d2e83fe.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d2e83fe)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-d2e83fe.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 1.1.0 (acd8a40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-linux-x64-1.1.0-acd8a40.deb) is ready for download.
[macOS build 1.1.0 (acd8a40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-macos-x64-1.1.0-acd8a40.dmg) is ready for download.
[Windows x64 build 1.1.0 (acd8a40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x64-1.1.0-acd8a40.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (acd8a40)](https://tc-builds.door43.org/build/l10n_develop/translationCore-win-x32-1.1.0-acd8a40.setup.exe) is ready for download.

**Review by mannycolon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5471#-:-LSVwewj5rhK-ljhq0l3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5471#-:-LSVwgFe4W6CsE5LHogB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mannycolon — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/5471)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
