### PR TITLE
Added Export To CSV Feature

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

This PR allows a user to see the checking data, comments, selections, verse edits, and reminders in csv form.

#### How to test this pull request:

Press the export button on any project. Select location and verify that it output correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/1471)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1471#-:-KjPLYDmL-cojLxQuGUV:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1471)*

**Comment by klappy** [comment]
Looking good! We've got a few workflow issues that I'm trying to figure out.
1) For some reason it only saves translationNotes. I have to cancel translationNotes to get it to ask to save translationWords.
2) Can we save all of the data in one zip file for all csv data including multiple checks? I'm not sure user wants to select multiple times, or deal with multiple files.
3) Can we use a different default location? Maybe desktop or downloads? Maybe even the user's translationCore folder instead of the project's hidden apps folder. The user won't know where to look for the file when it's put there by default. I even had to hunt it down and re-save it.

Can we address all of those by making one zip file for all data, you can make subfolders if needed. And can we use a different default path?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1471#-:-KjQBKIseChApUelNk5p:b-do63og)*

**Comment by klappy** [comment]
Reviewed 6 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/1471)*

**Pull request merged**
