### PR TITLE
Basic Layout and design of ProjectsManagement page. #969

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Basic Layout and design of ProjectsManagement page.
Temporarily, no real projects from your folder, just using current project twice to simulate list.
No functionality like select or 3dot menu yet.

#### How to test this pull request:

- Use the next button on the homescreen to get to the projects page.
- Open a project from the modal and close modal.
- Review basic layout/design and see if it looks close.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/2020)

### CODE REVIEW

**Comment by RoyalSix** [comment]
#969 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020#-:-KnpevMXkOx7aewxgW4p:b-8sbazi)*

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/components/home/projectsManagement/ProjectCard.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020#-Knpf1ocp4H4fnDVTMfe:-Knpf1ocp4H4fnDVTMff:b-gf1wc8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9bbc1d11426b9fde3f818a04b3acad6890f95870/src/js/components/home/projectsManagement/ProjectCard.js#L15)):*
> ```JavaScript
> 
>   if (projectSaveLocation && bookName && params && manifest) {
>     const projectName = path.basename(projectSaveLocation);
> ```

this component has too much logic.

WE SHOULD CONSIDER MOVING THIS INTO ACTIONS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020)*

**Comment by RoyalSix** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/components/home/projectsManagement/MyProjects.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020#-KnpffHMev-8zLcP-_4K:-KnpffHMev-8zLcP-_4L:bwecbsl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9bbc1d11426b9fde3f818a04b3acad6890f95870/src/js/components/home/projectsManagement/MyProjects.js#L6)):*
> ```JavaScript
> import ProjectCard from './ProjectCard';
> 
> let MyProjects = (props) => {
> ```

nice stateless!

---

*[src/js/components/home/projectsManagement/ProjectCard.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020#-Knpf1ocp4H4fnDVTMfe:-KnpfpwslAITwm30YB9W:boxtvft) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9bbc1d11426b9fde3f818a04b3acad6890f95870/src/js/components/home/projectsManagement/ProjectCard.js#L15)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this component has too much logic.

WE SHOULD CONSIDER MOVING THIS INTO ACTIONS
</blockquote></details>

That or the container

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020)*

**Comment by klappy** [comment]
*[src/js/components/home/projectsManagement/ProjectCard.js, line 15 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020#-Knpf1ocp4H4fnDVTMfe:-Knt_tEK8HdeLr-c7mPf:b2lqdv8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/9bbc1d11426b9fde3f818a04b3acad6890f95870/src/js/components/home/projectsManagement/ProjectCard.js#L15)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

That or the container
</blockquote></details>

What this smells like to me is that the reducer does not have the right data in it. I agree that we should move this to actions and populate the reducer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/2020)*

**Pull request merged**
