### PR TITLE
Added a util that handles dispatching redux actions in non-react components

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/754)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddIEQ-E4CvDdwrvudo:-KddIEQ0rtJC4YflchV8:bcmokmh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/actions/SettingsActions.js#L6)):*
> ```JavaScript
> const pathex = require('path-extra');
> const PARENT = pathex.datadir('translationCore')
> const PACKAGE_COMPILE_LOCATION = pathex.join(PARENT, 'packages-compiled');
> ```

I still don't think settings need to go in the `packages-compiled` folder. 

---

*[src/js/actions/SettingsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddIMGRoi8-2rGC19UA:-KddIMGRoi8-2rGC19UB:bw2b55p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/actions/SettingsActions.js#L10)):*
> ```JavaScript
> module.exports.setSettings = function(field, value) {
>   return ((dispatch) => {
>     var dir = pathex.join(PACKAGE_COMPILE_LOCATION, 'settings.json');
> ```

Can we define this as a constant at the top?

---

*[src/js/reducers/settingsReducer.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddJ5OyBzGEaFDZvnNC:-KddJ5OyBzGEaFDZvnND:b-9pmrok) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/reducers/settingsReducer.js#L6)):*
> ```JavaScript
> 
> const initialState = {
>   currentSettings: null,
> ```

Wouldn't this make it so that our settings are default until they change? And that they don't get loaded in until someone changes them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754)*

**Comment by mannycolon** [comment]
@ihoegen you were the one who suggested to put the settings in `packages-compile`.

**Comment by ihoegen** [comment]
@mannycolon I meant on the same level as package-compiled, not inside of it

**Comment by mannycolon** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/actions/SettingsActions.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddIEQ-E4CvDdwrvudo:-KddVrMCljA8zPSHgjNA:b-s3moia) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/actions/SettingsActions.js#L6)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I still don't think settings need to go in the `packages-compiled` folder. 
</blockquote></details>

I thought you had suggested using the `packages-compiled` folder.

---

*[src/js/actions/SettingsActions.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddIMGRoi8-2rGC19UA:-KddVq0CCuek7iIH1VQL:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/actions/SettingsActions.js#L10)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Can we define this as a constant at the top?
</blockquote></details>

Done.

---

*[src/js/reducers/settingsReducer.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754#-KddJ5OyBzGEaFDZvnNC:-KddWB9WQ_HNlGvKbLNO:bysxxdy) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/1c2e82b6c071dcadff0deb2440af8977173cb96c/src/js/reducers/settingsReducer.js#L6)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Wouldn't this make it so that our settings are default until they change? And that they don't get loaded in until someone changes them?
</blockquote></details>

Actually, this is being initialized by an action in App.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/754)*

**Comment by mannycolon** [comment]
@ihoegen should i use parent then???

**Pull request merged**
