### PR TITLE
Addressed QA issues for 4520

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixed bug where tc would load a manifest file for a bible that did not exist.
- Added safeguard so that scripture pane fails gracefully if theres a bible misisng in the resources reducer
- Added support for bibles using the old verse objects data sturcture.
- Fixed a few console log warnings/errors

#### Please include detailed Test instructions for your pull request:
- Verify that both tools work fine w/ fresh settings.json file
- ULT should show text for verses in php and not the empty verse warning.  (**Use** [php.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094622/php.zip) **or** [en_ult_php_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094630/en_ult_php_text.zip))
- You should be able to load this luk project with no blank screen [es_ult_luk_text.zip](https://github.com/unfoldingWord-dev/translationCore/files/2094633/es_ult_luk_text.zip)

#### Dependencies: 
- https://github.com/translationCoreApps/wordAlignment/pull/45
- https://github.com/translationCoreApps/translationWords/pull/137

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4657)

### CODE REVIEW

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (c5172f3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-c5172f3.zip) is ready for download.
[macOS build 0.10.0 (c5172f3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-c5172f3.dmg) is ready for download.
[Windows x64 build 0.10.0 (c5172f3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-c5172f3.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (c5172f3)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-c5172f3.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (b91044d)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-b91044d.zip) is ready for download.
[macOS build 0.10.0 (b91044d)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-b91044d.dmg) is ready for download.
[Windows x64 build 0.10.0 (b91044d)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-b91044d.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (b91044d)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-b91044d.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6a51772.zip) is ready for download.
[macOS build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6a51772.dmg) is ready for download.
[Windows x64 build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6a51772.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6a51772.setup.exe) is ready for download.

**Comment by dsm-git** [comment]
[Linux build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-linux-x64-0.10.0-6a51772.zip) is ready for download.
[macOS build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.0-6a51772.dmg) is ready for download.
[Windows x64 build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x64-0.10.0-6a51772.setup.exe) is ready for download.
[Windows x32 build 0.10.0 (6a51772)](https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-win-x32-0.10.0-6a51772.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
LGTM - local testing
LGTM - code review

**Pull request merged**
